### ISSUE TITLE
How to use pydantic to extract single field in dict?

### ISSUE THREAD

**Issue by kiennguyen1101** [samuelcolvin/pydantic#1000]
# Question
Here's a dict I got from API json:
```python
{'type': 'message', 'id': 'StringID', 'timestamp': '2019-11-15T10:20:26.6469421Z', 'serviceUrl': 'https://service-url/', 'channelId': 'webchat', 'from': {'id': 'ID'}, 'conversation': {'id': 'AnotherID}, 'recipient': {'id': 'RecipientID', 'name': 'AppName'}, 'textFormat': 'plain', 'locale': 'en-US', 'text': 'hello', 'entities': [{'type': 'ClientCapabilities', 'requiresBotState': True, 'supportsListening': True, 'supportsTts': True}], 'channelData': {'clientActivityID': 'activityID'}}
```
Please complete:
* OS: Debian Stretch (docker python:3.7)
* Python version `import sys; print(sys.version)`: 3.7.4
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.32.2

Where possible please include a self contained code snippet describing your question:

```py
import pydantic
from pydantic import BaseModel, Schema
class SkypeMessageModel(BaseModel):
    type: str
    id: str
    timestamp: datetime
    serviceUrl: str
    channelId: str
    recipient: str # i want to get "from.id"
   # from: dict not working because of python keyword
...
```

**Comment by samuelcolvin** [comment]
I'm not quite sure what your question is. If it's related to extracting `from`, you should use [`Config.alias`](https://pydantic-docs.helpmanual.io/usage/model_config/)

**Comment by kiennguyen1101** [comment]
Hi, sorry for the late reply; please allow me to ask again:
With the json input: ``` {"from": {"id": "ID"}} ``` how do I extract only "ID" string?

**Comment by koxudaxi** [comment]
@kiennguyen1101 
You can use validator to assign custom value to a field.
https://pydantic-docs.helpmanual.io/usage/validators/

```
from pydantic import BaseModel, Schema, validator


class Model(BaseModel):
    from_: str = Schema(..., alias='from')  # ... is required.

    @validator('from_', always=True, pre=True)
    def validate_from_id(cls, v):
        if isinstance(v, dict) and 'id' in v:
            return v['id']

exmaple_json = {'from': {'id': 'ID'}}
model = Model.parse_obj(exmaple_json)
print(model.from_)
# > ID
print(model.json(by_alias=True))  # if you want to dump by alias then, you should add 'by_alias=True'
# > {"from": "ID"}
```

I implement the example with pydantic version 0.32.2 which is the previous release.
If you want to use a later version(v1.x), you should use `Filed` instead of `Schema`.

**Comment by samuelcolvin** [comment]
Agreed.

Typo: `Field` not `Filed`
