### ISSUE TITLE
How to reper decimal as string in response?

### ISSUE THREAD

**Issue by heckad** [samuelcolvin/pydantic#1004]
Need that decimal to be string, not float.

**Comment by samuelcolvin** [comment]
Not enough information, didn't fill bother to fill out the standard questions.

**Comment by samuelcolvin** [comment]
perhaps related to FastAPI.

**Comment by heckad** [comment]
No, I want that after call json or dict values of Decimal field be string and if we got values for this fields not sting we raise Validation error. It needs for more accurate mathematic results because exponential form not completely accurate.

**Comment by samuelcolvin** [comment]
For `.json()` you can used [`Config.json_encoders`](https://pydantic-docs.helpmanual.io/usage/exporting_models/#modeljson).

For doing the same with `.dict()` see the dicussion on #951, until that's implemented, you might want to override `.dict()` or `._get_value()`

**Comment by heckad** [comment]
It is a standard pattern for working with decimal and should be configurated throw field only for decimal. Lock at [marshmallow](https://marshmallow.readthedocs.io/en/stable/api_reference.html#marshmallow.fields.Decimal) for example. (as_string parameter)

**Comment by samuelcolvin** [comment]
`.dict()` returns a `Decimal`. That's correct.

For `.json()` I decided to use `float` by default since from my experience that is more often more helpful.

To change the behaviour is as simple as

```py
    ...
    class Config:
        json_encoders = {Decimal: str}
```
It couldn't be much simpler to fix.

**Comment by heckad** [comment]
How to send super big numbers with 200 digits in float?

**Comment by samuelcolvin** [comment]
@heckad I've just read through your comments on the three issues you've created recently. In all of them your comments are extremely blunt and hostile. This is not the best way to engage with the open source community, and it's definitely not the best way to persuade me to spend time considering a change in behaviour or explaining the work around.

I don't get paid to help provide support for pydantic, indeed I take time out of my paid job to answer your questions. If you would like help with pydantic, please be polite and friendly.

If you don't like the decisions I've make while developing pydantic, either:
* politely and clearly propose a change in behaviour, for example changing the default encoder for `Decimal` from `float` to `str`. I would consider your suggestion, take feedback from others, and make a decision explaining my logic. I would also always try to provide an easy workaround, in this case that's already available via `Config.json_encoders` as explained above.
* use another library such as marshmallow, it's really no skin off my back.

**Comment by heckad** [comment]
Sory, My English is poor.

**Comment by samuelcolvin** [comment]
I understand that, and I'm sure it's difficult.

But in discussions like this it's very easy to sound more aggressive than you intend to.
