### ISSUE TITLE
Which method should I use if I want to do sth during class Instantiate?

### ISSUE THREAD

**Issue by i4never** [samuelcolvin/pydantic#1005]
# Question
Hi, what should I do if I want some logic during class instantiate? For example, I want to "register" this class and initialize some class variable starts with '_'. I've tried defining my own ``__metaclass__`` and assign it to ``BaseModel`` inherited class but it seems that ``__ModelMetaclass__`` is the effective one. What's the correct way to do this with pydantic? Thanks.

**Comment by i4never** [comment]
Solved. custom metaclass works if ``ModelMetaclass`` is inherited.

**Comment by dmontagu** [comment]
Another option would be to define `__init_subclass__` in a reused base class.

But if using a custom metaclass that inherits from `MetaModel` works for you, that's fine too!
