### ISSUE TITLE
Support for conditionals in json schema

### ISSUE THREAD

**Issue by stasSajin** [samuelcolvin/pydantic#1021]
# Feature Request
Would it be possible to have support for conditionals in JSON Schema when converting pydantic classes to JSON Schema? 

Here is what I mean: 
https://json-schema.org/understanding-json-schema/reference/conditionals.html

**Comment by samuelcolvin** [comment]
Fine by me.

Just need to find someone to implement it. :smile: 

How would you envisage it being defined in pydantic/python?

**Comment by samuelcolvin** [comment]
Any update on how this would work?

If no one is championing the idea I'd suggest we choose the issue.

**Comment by dmontagu** [comment]
I'm having a hard time thinking of a substantially better API for this than just implementing the logic manually in a validator, and updating the schema manually using `schema_extra`. As a feature it just doesn't seem very amenable to a type-based or derivable representation. (I'd be happy to be proven wrong though.)

I think it might be worth a docs PR to show how a model with the schema on the linked page could be implemented (with corresponding validation) using `validator` and `schema_extra`.

I'd be happy to review such a PR; alternatively I'd be happy to write it up myself if someone expresses interest but isn't sure how to accomplish it.

**Comment by samuelcolvin** [comment]
Closing but happy to open if someone had a brainwave on how to achieve this elegantly.
