### ISSUE TITLE
Enforce choice of types when subclassing a pydantic model

### ISSUE THREAD

**Issue by ValentinCalomme** [samuelcolvin/pydantic#1024]
# Question

Let's assume I have the following models:

```py
import pydantic

class Bar(pydantic.BaseModel):
    
    value: str = "hello world"
    
class Foo(pydantic.BaseModel):
    
    a: Bar
    
class Bar2(Bar):
    
    other_value: str = "bye mars"
    
class Foo2(Foo):
    
    a: Bar2
```

Is there any way to enforce the fact that any subclass of Foo must have an attribute "a" which is itself a subtype of Bar? As far as I know, if I want to create a subclass of Foo, I can make "a" any type I'd like. I understanding this is the Pythonic way to go about it ("everyone is a consenting adult"), but is there a Pydantic way to enforce this? If not, should there be one?

* OS: Windows
* Python version: 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
* Pydantic version: 1.0

**Comment by samuelcolvin** [comment]
as in "enforce" when creating the model/class?

It's not possible at the moment, I doubt it's something many people would want.

You should be able to implement it yourself, perhaps using `__init_subclass__` #867, or your own metaclass.

**Comment by dmontagu** [comment]
I actually do this in my own projects to ensure concrete custom-ABC subclasses have declared class variables through checks inside the `__init_subclass__`. I haven't personally used it to enforce types in models, but I don't see any reason it wouldn't work.
