### ISSUE TITLE
How to throw an error for an empty input value?

### ISSUE THREAD

**Issue by rappongy** [samuelcolvin/pydantic#1030]
# Question

Hello! Does any common way to throw an error for an empty input value?

**Example:**
```py
class Foo(pydantic.BaseModel):
    bar: str

# Wanna throw an error in this case
Foo(bar="")
```

Thank you for your work.

**Comment by koxudaxi** [comment]
You can use `constr` as a type.
```
from pydantic import constr, BaseModel


class Model(BaseModel):
    bar: constr(min_length=1)


Model(bar="")
```
https://pydantic-docs.helpmanual.io/usage/types/#constrained-types

**Comment by samuelcolvin** [comment]
or you can use [validators](https://pydantic-docs.helpmanual.io/usage/validators/)
