### ISSUE TITLE
Generate pydantic class code from JSON-schema

### ISSUE THREAD

**Issue by Gjacquenot** [samuelcolvin/pydantic#1033]
# Generate pydantic class python code from JSON-schema

From great documentation, I have seen that it is possible to create a pydantic class deriving from BaseModel and to have the associated JSON-schema.

It is also possible to create a dynamic model with `create_model`.

I am wondering if there is a script that loads a JSON-schema and generated a string of the associated class. (Or to dump python code from a dynamic model?)

```python
from pydantic import create_code_model_from_json_schema

my_schema = \
{"title": "MyModel",
 "type": "object",
 "properties": {"number": {"title": "Number", "type": "integer"}},
 "required": ["number"]}

create_code_model_from_json_schema(my_schema)
```

It would dump something like this:

    class MyModel(BaseModel):
        number: int = ...

**Comment by samuelcolvin** [comment]
Thanks for asking, unfortunately this isn't possible at the moment.

The question was asked before and there's some discussion on the possibilities of a solution on #643
