### ISSUE TITLE
Integrate (some?) FastAPI tests into Pydantic's CI

### ISSUE THREAD

**Issue by tiangolo** [samuelcolvin/pydantic#1041]
# Feature Request

As proposed in https://github.com/tiangolo/fastapi/pull/646, it would be awesome to have FastAPI tests integrated into Pydantic's CI.

How would you like to approach it?

I can sketch a PR, but I really have no idea how to do it yet...

I wanted to ask first if you have a specific plan, or if you would like to do it directly.

Please complete:
* OS: **N/A**
* Python version `import sys; print(sys.version)`: **N/A**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **N/A**

**Please read the [docs](https://pydantic-docs.helpmanual.io/) and search through issues to
confirm your feature hasn't been asked for before, or already implemented.**

**Comment by samuelcolvin** [comment]
I had some vague plan. Would love help on it.

Rough idea:
* check if the the "fastapi" directory exists:
  * if it does, run `git pull` in that directory
  * if not, run `git clone` to clone into the "fastapi" directory
* check out the latest git tag - assuming this will be the latest released version
* install any necessary extra dependencies
* run `pytest fastapi/tests` or whatever

This should be setup as a single make recipe, e.g. `make test-fastapi`. It should be run as an extra job in travis, I think it's okay to only run it with one python version, e.g. 3.7.

If not all tests are going to pass:
* delete those files before running pytest
* or, mark those tests in the fastapi code base so pydantic can easily exclude them

Does that make sense?

**Comment by tiangolo** [comment]
Yeah, perfect! Do you want to get the specific latest tag or is `master` OK?

It always has the latest of everything, and the CI has to pass in PRs before they are merged, so, tests should always be "correct" in `master`...

**Comment by samuelcolvin** [comment]
I would have though it made most sense to test against the latest released version, e.g. latest tag. But master might be a good start.

Every project where I've ever tried testing against master has failed often enough to annoy people - it doesn't take very much "my PR is failing due to some complex thing that isn't my fault" to put people off contributing.

**Comment by tiangolo** [comment]
Good point.
