### ISSUE TITLE
Support for exporting to YAML

### ISSUE THREAD

**Issue by cdeil** [samuelcolvin/pydantic#1043]
# Feature Request

In #136 there was the feature request to support YAML as input. As explained there, this doesn't need to be built in, one can just parse the YAML and then pass it in. That's fine.

For our use case we need to also write to YAML. We were expecting that `yaml.dump(model.dict())` would work, but for our case where we have custom types it doesn't (see https://github.com/gammapy/gammapy/pull/2621#discussion_r351905842). What does work is this:
```
yaml.dump(yaml.safe_load(self.json())
```
This triggers our custom JSON serialisers, and then because I think JSON is a subset of YAML, this works. I guess this would also work and be a bit cleaner:
```
yaml.dump(json.load(self.json())
```

Is there an option, or would it make sense to add it, to have custom serialisers triggered already in `dict()`?
https://pydantic-docs.helpmanual.io/usage/exporting_models/#modeldict
Then this would work `yaml.dump(model.dict(serialise=True))`

Alternatively, if `yaml.dump(json.load(self.json())` is the way to do it: how about a small pydantic docs addition explaining how to work with YAML or other formats, by re-using the dict / json interface?
If you make a suggestion where to put it I could send a PR.

**Comment by samuelcolvin** [comment]
As discussed on #951 and as a solution to #317, `dict()` is going to get a `simplify` kwarg which will produce a simplified dict suitable for this application.

I'm going to work on it soon.

**Comment by MRigal** [comment]
FYI, this is still problematic in Pydantic V2 if anyone wants to export to YAML. But I guess no "simplify" kwarg will come anymore...
