### ISSUE TITLE
Multiple inheritance with BaseModel

### ISSUE THREAD

**Issue by petroswork** [samuelcolvin/pydantic#105]
I'm trying to implement multiple inheritance with BaseModel, but every way I've tried failed. A minimal example:

```
class A():                     
    def __init__(self, a1, a2, *args, **kwargs):
        print('In A.')                        
        print(a1, a2, args, kwargs)          
        super().__init__()                   
        print('Leaving A.')

class B(pydantic.BaseModel):
    desc: pydantic.constr(min_length=3)
    def __init__(self, desc, *args, **kwargs):
        print('In B')
        super().__init__(*args, **kwargs)
        print('Leaving B.')

class C(B, A):
    def __init__(self, tmp, *args, **kwargs):
        print('In C')
        super().__init__(*args, **kwargs)
        print('Leaving C')


class B():                  
    desc: str                                
    def __init__(self, desc, *args, **kwargs):
        print('In B')
        self.desc = desc
        super().__init__(*args, **kwargs)
        print('Leaving B.')
```
If I use B inheriting from BaseModel, instantiation of C fails:
``` c = C(1,2,3,4)```
>In C
>In B
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-13-a821d313077b> in <module>()
> ----> 1 c = C(1,2,3,4)
>
> <ipython-input-12-f6405bf8d34f> in __init__(self, tmp, *args, **kwargs)
>      2     def __init__(self, tmp, *args, **kwargs):
>      3         print('In C')
>----> 4         super().__init__(*args, **kwargs)
>      5         print('Leaving C')
>
> <ipython-input-11-99f7bc89bb7a> in __init__(self, desc, *args, **kwargs)
>      3     def __init__(self, desc, *args, **kwargs):
>      4         print('In B')
>----> 5         super().__init__(*args, **kwargs)
>      6         print('Leaving B.')
>
> TypeError: __init__() takes 1 positional argument but 3 were given

However, if I use B only inheriting from `object`, everything works fine. Is there a way to make this work?

**Comment by samuelcolvin** [comment]
Both mixins and full inheritance should work fine. 

Please can you explain what you're trying to achieve and I'll explain why. 

Audi your second code example is hard to read/understand. Please can you edit it (perhaps using triple back quotes) to look correct.

**Comment by petroswork** [comment]
I'm just trying to use some methods from another class via inheritance, so that the class inheriting from BaseModel both validates data and includes extra functionality. It is possible to do this by replicating part of the definition of BaseModel (`self.__setstate__(self._process_values(kwargs))` in B's `__init__`), but I've concluded in the end that it would be better if I did it via composition, so that C can use parts of BaseModel only where it makes sense to do so.
