### ISSUE TITLE
Supress title generation

### ISSUE THREAD

**Issue by selimb** [samuelcolvin/pydantic#1051]
# Feature Request

* OS: **Windows 10**
* Python version `import sys; print(sys.version)`: **3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **1.2**

There's no way to suppress/opt-out of the `title` property generation in `schema()`.
```py
# main.py
import pprint

import pydantic

class User(pydantic.BaseModel):
    name: str = pydantic.Field(..., title="", description="User name")
    password: str = pydantic.Field(..., description="User password")
    age: int = pydantic.Field(..., title=None, description="User age")


pprint.pprint(User.schema())
```
spits out:
```py
{'properties': {'age': {'description': 'User age',
                        'title': 'Age',
                        'type': 'integer'},
                'name': {'description': 'User name',
                         'title': 'Name',
                         'type': 'string'},
                'password': {'description': 'User password',
                             'title': 'Password',
                             'type': 'string'}},
 'required': ['name', 'password', 'age'],
 'title': 'User',
 'type': 'object'}
```
notice how all `properties` are given the auto-generated `title`.

I care about this mostly as a [fastapi](https://github.com/tiangolo/fastapi) user. I don't like how Swagger UI renders the title, and find the title to be redundant with `description` anyway (although maybe I'm missing something?)

This can be seen by adding the following to the code above:
```py
import fastapi

app = fastapi.FastAPI()

@app.post("/users")
def create_user(user: User):
    pass
```
and running the server with `uvicorn main:app` (note this will require `pip install fastapi uvicorn`).
`http://127.0.0.1:8000/docs` show:
![image](https://user-images.githubusercontent.com/6503002/69888068-dfce4400-12e1-11ea-8c38-ded37bf97f5f.png)

If I patch `pydantic/schema.py` with the following:
```py
    schema_overrides = False
    # s = dict(title=field.field_info.title or field.alias.title().replace('_', ' '))
    s = {}
    if field.field_info.title:
```
the output is much nicer (IMO):

![image](https://user-images.githubusercontent.com/6503002/69888268-d1ccf300-12e2-11ea-8315-b5cbcf630806.png)

I'd be happy to submit a PR. Adding a `Config` option probably makes sense, but maybe there should also be a way to disable the auto-title only for a specific field?

**Comment by samuelcolvin** [comment]
I don't think we want more config options unless absolutely required.

The solution here is to allow `schema_extra` to be a function which can mutate the schema, #889. Happy to accept a PR for that.

**Comment by selimb** [comment]
See #1054. The added example is actually exactly what I'll be personally using.

Out of curiosity though, why is `title` always auto-generated? Who needs/wants that?

**Comment by samuelcolvin** [comment]
@tiangolo added it when he implemented schema, I think in general it would be more readable.

**Comment by samuelcolvin** [comment]
E.g. to an end user if title was used as the label on a form input.

**Comment by selimb** [comment]
Gotcha. Thanks!
