### ISSUE TITLE
Change global json

### ISSUE THREAD

**Issue by victoraugustolls** [samuelcolvin/pydantic#1059]
# Question

Please complete:
* OS: **Ubuntu 19.03**
* Python version `import sys; print(sys.version)`: **3.7.5**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **1.2**

Is it possible to change global pydantic config to use `orjson` instead of repeating the same piece of code in each `BaseModel`?

**Comment by dmontagu** [comment]
The easiest way to achieve this, I think, is to inherit from a common base class for all the models you want to use `orjson` to encode. Let me know if that doesn't make sense, or you don't like that approach for some reason.

**Comment by victoraugustolls** [comment]
It makes total sense, and it was my first option. Was just wondering if there was another option that I was missing. Thanks!
