### ISSUE TITLE
Missing HISTORY.rst

### ISSUE THREAD

**Issue by pauleveritt** [samuelcolvin/pydantic#106]
pydantic installs fine from pip but via a dependency in setup.py it fails with a missing HISTORY.rst due to your long_description in setup.py. Basically, you need a MANIFEST.in that includes that file.

```
Processing pydantic-0.6.2.tar.gz
Writing /var/folders/4j/00jv8sg138n61hsj6ppf60pm0000gn/T/easy_install-o7rp3h7o/pydantic-0.6.2/setup.cfg
Running pydantic-0.6.2/setup.py -q bdist_egg --dist-dir /var/folders/4j/00jv8sg138n61hsj6ppf60pm0000gn/T/easy_install-o7rp3h7o/pydantic-0.6.2/egg-dist-tmp-7bd8a1a8
error: [Errno 2] No such file or directory: '/private/var/folders/4j/00jv8sg138n61hsj6ppf60pm0000gn/T/easy_install-o7rp3h7o/pydantic-0.6.2/HISTORY.rst'
```

**Comment by samuelcolvin** [comment]
No need for MANIFEST.in, I believe manifest is depricated. 

It can be added to `setup.py`.

**Comment by samuelcolvin** [comment]
or even better just catch the error so those two files don't need to be included in the 99% of cases where the wheel is used.

**Comment by sharksforarms** [comment]
Thanks for fixing was just about to make an issue :)
