### ISSUE TITLE
Different behaviour of Config for pydantic model when Config is inherited and when Config is passed through dataclass decorator

### ISSUE THREAD

**Issue by fervid** [samuelcolvin/pydantic#1081]
* OS: **Ubuntu 19.04**
* Python version `import sys; print(sys.version)`: **3.7.3 (default, Oct  7 2019, 12:56:13) [GCC 8.3.0]**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **1.2**

## 1. When Config is passed through dataclass decorator 
```py
from typing import (
    Optional,
    List,
    Dict,
    Tuple,
    Union,
    # Final
)

from pydantic import (
    BaseModel,
    Field,
    ValidationError,
    validator,
    root_validator,
    Extra
)

from pydantic.dataclasses import dataclass

class ModelConfig:
    extra = Extra.forbid


@dataclass(config=ModelConfig)
class ABC(BaseModel):
    a: Optional[int]
    b: Optional[int]
    c: Optional[int]
```

Call `ABC(**{"a": 0})` returns `TypeError: __init__() missing 2 required positional arguments: 'b' and 'c'`
Call `ABC(**{"a": 0, "b": 0, "c": 0})` returns `AttributeError: __fields_set__`
Call `ABC(**{"a": 0, "b": 0, "c": 0, "garbage": 0})` returns `TypeError: __init__() got an unexpected keyword argument 'garbage'`

## 2. When Config is inherited
```py
class BaseModelConfig(BaseModel):
    class Config:
        extra = Extra.forbid

class XYZ(BaseModelConfig):
    x: Optional[int]
    y: Optional[int]
    z: Optional[int]
```

Call `XYZ(**{"x": 0})` returns right object: `XYZ(x=0, y=None, z=None)`
Call `XYZ(**{"x": 0, "y": 0, "z": 0})` returns right object: `XYZ(x=0, y=0, z=0)`
Call `XYZ(**{"x": 0, "y": 0, "z": 0, "garbage": 0})` returns
```
ValidationError: 1 validation error for XYZ 
garbage 
  extra fields not permitted (type=value_error.extra)
```

**Comment by samuelcolvin** [comment]
This is standard behaviour of dataclasses, not something pydantic can change, see #986 for details.
