### ISSUE TITLE
Incoming and outgoing aliases in JSON

### ISSUE THREAD

**Issue by limelights** [samuelcolvin/pydantic#1082]
* Python version: 3.7.3
* Pydantic version: 1.1

Hello,
I've been struggling with getting this to work "my way".
I have the below model which takes data from a source that I have no control over.
My use case is that I need to have this model returned as JSON but with camel cased output.

```py
import pydantic

class Video(BaseModel):
    secure_video_url: str = Field(None, alias="video:secure_url")

v = Video(**{"video:secure_url": "http://example.com/video=123"})
```

First, getting it into the field is easy `secure_video_url = Field(None, alias="video:secure_url")` and getting it out from the alias is also easy `v.json(by_alias=True)`.
What I find myself struggling with is how to do `v.json()` and get something along the lines of `{"secureVideoUrl": "http://example.com/video=123"}`.

I have read the following issues and PRs but have failed to get the output I need
- https://github.com/samuelcolvin/pydantic/issues/159
- https://github.com/samuelcolvin/pydantic/issues/1056

My understanding is that you can only have 1 alias per field and that has left me thinking that either I should use a custom JSON encoder that transforms it (I would love not to) or write some logic around those aliases that have special case names and store that in the `Config` class of a base class.

**Comment by samuelcolvin** [comment]
I think this is covered by #624, if that doesn't work, please let us know on the issue how you would like it to work.

**Comment by limelights** [comment]
Yes, those options would work for me, but I am assuming (since I cant find it in the docs or code) that it's implemented yet, right?

**Comment by samuelcolvin** [comment]
It's not implemented yet, I will work on it soon. 

Unless someone else wants to submit a PR?
