### ISSUE TITLE
Allow implicit casting for Enum in Literal

### ISSUE THREAD

**Issue by ysmu** [samuelcolvin/pydantic#1086]
# Feature Request

Please complete:
* OS: Windows
* Python version `import sys; print(sys.version)`: **3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **1.2**

I'm actually not sure if this is a bug or a feature request. Currently, `enum.Enum` values aren't automatically converted back to the `enum.Enum` if it is wrapped in a `Literal`. Can we allow this behavior?

```py
import enum

import pydantic
from typing_extensions import Literal


class Fruit(enum.Enum):
    apple = 'apple'
    banana = 'banana'


class Apple(pydantic.BaseModel):
    fruit: Fruit = ...


class LiteralApple(pydantic.BaseModel):
    fruit: Literal[Fruit.apple] = ...


Apple(fruit=Fruit.apple.value)
LiteralApple(fruit=Fruit.apple.value)
```

Output (Exception)
```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    LiteralApple(fruit=Fruit.apple.value)
  File "D:\.virtualenvs\pydantic\lib\site-packages\pydantic\main.py", line 274, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for LiteralApple
fruit
  unexpected value; permitted: <enum 'Fruit'> (type=value_error.const; given=apple; permitted=(<enum 'Fruit'>,))
```

**EDIT: It should be Literal[Fruit.apple] instead of just Literal[Fruit]**

**Comment by samuelcolvin** [comment]
Should be possible to implement. But you don't need `Literal` when working with enums.

**Comment by ysmu** [comment]
I was trying to implement the last example in [Literal Type](https://pydantic-docs.helpmanual.io/usage/types/#literal-type), but with an `enum.Enum` for `flavor` instead of string.

**Comment by dmontagu** [comment]
From https://mypy.readthedocs.io/en/latest/literal_types.html

> Future versions of mypy may relax some of these restrictions. For example, we plan on adding support for using enum values inside Literal[...] in an upcoming release.

I don't think mypy supports enum literals yet -- once they do, I think it will make more sense to implement this.

**Comment by ysmu** [comment]
Ah, I see where @samuelcolvin is coming from. I noticed I made a mistake in my example. It should say `fruit: Literal[Fruit.apple]` instead of `fruit: Literal[Fruit]` in the `LiteralApple` class. Corrected.

Since I can work around this issue by using the string form it's not a big issue.

**Comment by samuelcolvin** [comment]
Okay closing.

New issue please if this is required in future.
