### ISSUE TITLE
EMAIL_REGEX does not match email with internationalized domain name.

### ISSUE THREAD

**Issue by petroswork** [samuelcolvin/pydantic#109]
For example, `a@vidéotron.ca` is considered an invalid email address, while `a@videotron.ca` is considered valid. Note that the `validate_email` module accepts both as valid, which is the correct behaviour.

**Comment by samuelcolvin** [comment]
You mean https://github.com/syrusakbary/validate_email? There's also https://github.com/JoshData/python-email-validator which has fewer stars but looks more thorough (at least in terms of documentation).

That regex is very naive, it was only ever really a first approximation.

I think the best option would be to add one of the above packages as a dependency and use that.

Do you have a strong preference? Would you like to submit a PR?

**Comment by samuelcolvin** [comment]
fixed by #142
