### ISSUE TITLE
Settings inheritance with ENV prefix does not work

### ISSUE THREAD

**Issue by perminovs** [samuelcolvin/pydantic#1091]
# Bug

* OS: ubuntu 18.04
* Python version `import sys; print(sys.version)`: 3.7.5 (default, Nov  7 2019, 10:50:52) 
* Pydantic version `import pydantic; print(pydantic.VERSION)`: `1.0b1` or `1.2`, but works fine with `0.32`

```py
import os
from pydantic import BaseSettings


class MyBaseSettings(BaseSettings):
    var: int = 10


class MySubSettings(MyBaseSettings):
    class Config:
        env_prefix = 'PREFIX_'


os.environ['PREFIX_VAR'] = '2'
k = MySubSettings()
print(k.var)  # 10, but should be 2
```

We expect that `k.var` will be equal to 2, but it has default value 10.
It's reproduced since 1.0b1.

**Comment by samuelcolvin** [comment]
I'm looking into this, but I'm afraid the solution isn't trivial.

Weird that this got 11 :+1: and 2 :eyes: in 2 hours. Any idea why this happened?

**Comment by kataev** [comment]
Yep, we are team.

**Comment by perminovs** [comment]
Thanks for quick support! Hope fix won't be difficult.

**Comment by livestreamx** [comment]
That's what exactly happens when you upgrade your project with Pydantic from `0.32` to `1.2` directly... Thank you for support, @samuelcolvin !

**Comment by samuelcolvin** [comment]
See #1093, sold be fixed there.
