### ISSUE TITLE
How model field can have default, when input object param is missing or is null

### ISSUE THREAD

**Issue by thanosexcite** [samuelcolvin/pydantic#1097]
# Question

Hi all. I'd like to find a way to validate an object with pydantic for correct types and at the same time allow the input property to have a None value or to be missing. But the resulting model field should not have a None value, but a default (empty list in my example).

To explain better, please check the test bellow. The test fails at the last assertion. Does anyone know how the Foo class should be so that the following test can pass? Thank you.

```py
from typing import List

import pytest
from pydantic import BaseModel, Field, ValidationError


class Foo(BaseModel):
    bar: List[int] = Field([], alias="barbar")


def test_pydantic_no_nulls():
    f = Foo.parse_obj({"barbar": [100]})
    assert f.bar == [100]

    with pytest.raises(ValidationError):
        Foo.parse_obj({"barbar": ["whatever"]})

    f_missing = Foo.parse_obj({})
    assert f_missing.bar == []

    f_null = Foo.parse_obj({"barbar": None})
    assert f_null.bar == []
    # This assertion fails :(
```

* OS: **Linux**
* Python version `import sys; print(sys.version)`: **3.6.9**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **1.2**

**Comment by samuelcolvin** [comment]
either:
* use a [`root_validator`](https://pydantic-docs.helpmanual.io/usage/validators/#root-validators) with `pre=True` to remove elements with `value is None` before validation
* or, add a field validator which returns `[] if valid is None else value` or whatever
