### ISSUE TITLE
Directly instantiate/validate AnyUrl (or scalar type)

### ISSUE THREAD

**Issue by andrewmwhite** [samuelcolvin/pydantic#1106]
# Question

Is there a way to validate a scalar like `AnyUrl` directly in 1.2? 

In 0.30, I was able to validate an HttpsUrl without building a full model class: 

```py
from pydantic import UrlStr

class HttpsUrlStr(UrlStr):
    schemes = set(["https"])

HttpsUrlStr.validate(metadata_uri)
```

I can't find an equivalent in 1.2. I've replaced the above class with: 
```py
from pydantic import AnyUrl

class HttpsUrl(AnyUrl):
    allowed_schemes = {'https'}
```

But `HttpsUrl.validate("https://www.example.com")` fails with `TypeError: validate() missing 2 required positional arguments: 'field' and 'config'`.  Trying to instantiate directly (`HttpsUrl("https://www.example.com")`) results in: `TypeError: __init__() missing 2 required keyword-only arguments: 'scheme' and 'host'`. 

My current workaround is:
```py 
        class _Model(BaseModel):
            uri: HttpsUrl

        _Model(uri=metadata_uri)  # force validation
```
which isn't ideal...

* OS: **macOS 10.15.2**
* Python version `import sys; print(sys.version)`: **3.7.4 (default, Sep 16 2019, 17:52:53) 
[Clang 10.0.1 (clang-1001.0.46.4)]**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **1.2**

**Comment by dmontagu** [comment]
@andrewmwhite 

There is the `pydantic.tools.parse_obj_as` function which was more or less intended to formalize the "force validation" approach you described:

```python
import pytest

from pydantic import AnyUrl, ValidationError
from pydantic.tools import parse_obj_as


class HttpsUrl(AnyUrl):
    allowed_schemes = {'https'}


parsed = parse_obj_as(HttpsUrl, "https://blah.com")
print(parsed)
# https://blah.com
print(type(parsed))
# <class '__main__.HttpsUrl'>

with pytest.raises(ValidationError) as exc_info:
    parse_obj_as(HttpsUrl, "http://blah.com")
assert exc_info.value.errors() == [
    {
        'loc': ('__root__',),
        'msg': 'URL scheme not permitted',
        'type': 'value_error.url.scheme',
        'ctx': {'allowed_schemes': {'https'}}
    }
]
```
Obviously if you just want the unparsed type you could check that an error isn't raised and in that case use the input value.

-----

With regard to the changing of `AnyUrl.validate`, I agree it is unfortunate there isn't an easier way to call the validate method directly any more, but I haven't touched that code much so wouldn't be surprised if there were some other benefits to refactoring this way. (@samuelcolvin would know best.)

**Comment by samuelcolvin** [comment]
`parse_obj_as` is the correct approach.

the reason `HttpsUrl.validate()` no longer works is that it needs length validation needs access to the field and model config.

**Comment by charlax** [comment]
Any plan to have something like `HttpUrl.parse(...)`? Advantages:

- Easier to discover/more intuitive
- No need to import one extra `parse_obj_as`

**Comment by zamonia500** [comment]
> Any plan to have something like `HttpUrl.parse(...)`? Advantages:
> 
> * Easier to discover/more intuitive
> * No need to import one extra `parse_obj_as`

I love this idea too!
`parse_obj_as` is even hard to search

**Comment by gusutabopb** [comment]
What about making `AnyUrl.validate` work like `ConstrainedStr.validate`?

I'm used to using `ConstrainedStr` like this:

```python
from pydantic import ConstrainedStr

class MyConstrained(ConstrainedStr):
    regex=re.compile("hey\w+")

MyConstrained.validate("hoho")  # throws StrRegexError
MyConstrained.validate("heyho")  # returns input (i.e. "heyho")
```

In order to make `AnyUrl` (and its subclasses) behave similarly, it should be just a matter of changing the `validate` signature so it takes just a single value and moving other validations included in `validate` to `__get_validators__`:

```diff
diff --git a/pydantic/networks.py b/pydantic/networks.py
index 18a042c..ddb5782 100644
--- a/pydantic/networks.py
+++ b/pydantic/networks.py
@@ -27,7 +27,7 @@ from typing import (

 from . import errors
 from .utils import Representation, update_not_none
-from .validators import constr_length_validator, str_validator
+from .validators import constr_length_validator, str_validator, constr_strip_whitespace

 if TYPE_CHECKING:
     import email_validator
@@ -200,16 +200,16 @@ class AnyUrl(str):

     @classmethod
     def __get_validators__(cls) -> 'CallableGenerator':
+        yield str_validator
+        yield constr_strip_whitespace
+        yield constr_length_validator
         yield cls.validate

     @classmethod
-    def validate(cls, value: Any, field: 'ModelField', config: 'BaseConfig') -> 'AnyUrl':
+    def validate(cls, value: Any) -> 'AnyUrl':
         if value.__class__ == cls:
             return value
-        value = str_validator(value)
-        if cls.strip_whitespace:
-            value = value.strip()
-        url: str = cast(str, constr_length_validator(value, field, config))
+        url: str = cast(str, value)

         m = url_regex().match(url)
         # the regex should always match, if it doesn't please report with details of the URL tried
```

With the above change, the following works fine:

```python

class MyModel(BaseModel):
    url: AnyUrl

MyModel(url="http://www.google.com")   # work as before
AnyUrl.validate("http://www.google.com")   # work as before

AnyUrl.validate("httxxxxxxxww.google.com")  # throws UrlSchemeError
MyModel(url="httxxxxxxxww.google.com")   # throws ValidationError
```

Happy to open a PR in case the above changes are something Pydantic maintainers would be willing to consider.
