### ISSUE TITLE
Is there a way to convert values in BaseModel

### ISSUE THREAD

**Issue by vitalik** [samuelcolvin/pydantic#1108]
# Question

Let's say I have some ORM model that have field birthday

```py

class User(SomeORM):
      id: int
      name: str
      birthdate: date
...
```

Now i want to use this model to output it as json via [fastapi](https://fastapi.tiangolo.com/)
but, instead of birthday I need to output age of the user (calculated based on birthday)

my pydantic model looks like this

```py

class UserOutput(BaseModel):
     id: int
     name: str
     age:  int   # !!! < how do I convert here from birthdate
```

The questions is - is it possible to convert  user.birthdate to age with some function on the layer of pydantic model (**without modifying the ORM user class** ) ?

**Comment by samuelcolvin** [comment]
Currently, no. The solution will be #935 but that's not implemented yet. Any feedback on how the feature should work would be much appreciated, please comment on #935.

**Comment by eladgunders** [comment]
Hi, i faced this issue and what I did is:

```python
class TodoOut(BaseModel):
    id: int
    is_completed: bool
    content: str
    priority: Priority
    todos_categories: Optional[list[TodoCategory]]  # exists in the orm model but to part of the returned TodoOut
    categories: Optional[list[CategoryOut]]  # not exists in the orm model but part of the returned TodoOut

    class Config:
        orm_mode = True

    @classmethod
    # converts todos_categories to categories
    def from_orm(cls, todo_orm):
        model = super().from_orm(todo_orm)
        model.categories = [ct.category for ct in model.todos_categories]
        delattr(model, 'todos_categories')
        return model

```
