### ISSUE TITLE
Validators in nested class cause issues with `parse_raw`

### ISSUE THREAD

**Issue by Ronserruya** [samuelcolvin/pydantic#1109]
# Bug

Please complete:
* OS: **OSX**
* Python version `import sys; print(sys.version)`: **3.8**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **1.2**

**Please read the [docs](https://pydantic-docs.helpmanual.io/) and search through issues to
confirm your bug hasn't already been reported.**

Where possible please include a self contained code snippet describing your bug:

```python
import json

from pydantic import BaseModel, validator

from typing import List

class Company(BaseModel):
    name: str

    @validator('name')
    def validate(cls, value):
        return value


class Req(BaseModel):
    name: str
    age: int
    companies: List[Company]

input_data = {
    'name': 'Daniel',
    'age': 5,
    'companies': [
        {'name': 'abc'}
    ]
}

r = Req.parse_raw(json.dumps(input_data))
print(r)

r2 = Req(name='Daniel', age=5, companies=[Company(name='abc')])
print(r2)
```

Output:
```
name='Daniel' age=5 companies=[{'name': 'abc'}]
name='Daniel' age=5 companies=[Company(name='abc')]
```

When using `parse_raw` to parse a model that has another model in it, validators cause some issues.
If class `Company` has a validator, there are two issues:
1. The `value` param in the validator is the entire dict instead of just the value of `name`
2. The final `r.companies` is a list of dicts, and not Companies.

**This does not happen if no validator is present**, or if a validator is present but the class is created regularly and not using `parse_raw`

**Comment by samuelcolvin** [comment]
This is because your validator is called `validate` which is a method on the model which you're overriding. This should be made less likely by #1018 

We could do more checks on validators to check the function name doesn't override some standard function, but is it really worth it.

---

This has nothing to do with `parse_raw`, it's just that you're using `Req(name='Daniel', age=5, companies=[Company(name='abc')])` while your `parse_raw` case is equivalent to `Req(name='Daniel', age=5, companies=[{'name': 'abc'}])`

**Comment by Ronserruya** [comment]
> This is because your validator is called `validate` which is a method on the model which you're overriding. This should be made less likely by #1018
> 
> We could do more checks on validators to check the function name doesn't override some standard function, but is it really worth it.
> 
> This has nothing to do with `parse_raw`, it's just that you're using `Req(name='Daniel', age=5, companies=[Company(name='abc')])` while your `parse_raw` case is equivalent to `Req(name='Daniel', age=5, companies=[{'name': 'abc'}])`

Thanks for the quick reply Samuel, I can confirm it works when I change the method name.
