### ISSUE TITLE
Custom data type with Generics

### ISSUE THREAD

**Issue by timonbimon** [samuelcolvin/pydantic#1113]
# Feature Request

It would be really cool if it were possible to create custom data types with support for generics.
I am thinking of something like this

```py
import pydantic
from pydantic import BaseModel

class Foo(BaseModel):
    bar: Custom[int]

```

Currently I extended the ModelMetaclass to do some custom type parsing (and basically transform the Custom[int] into a class `Custom` with `Custom.dtype == int`), but it would be nice if there were a less hacky way to do this.

**Comment by samuelcolvin** [comment]
I suspect this is already possible, but I'm not entirely clear what you're looking for.

**Comment by timonbimon** [comment]
Ok maybe it will become more clear with the actual thing I want to get done.
I want to build a pydantic Model for specifying a hyperparameter space of a machine learning model. One "dimension" type of that space can be a categorical hyperparameter that consists of a list of values and prior for drawing each value from the list.

Ideally I would like to write the pydantic Model like so

```
import pydantic
from pydantic import BaseModel

class HSpace(BaseModel):
    num_layers: Categorical[int]
```
where

```
HSpace(num_layers=[1,2,5,10])
```
validates that each value in the list is of type `int` and initializes my custom type `Categorical` with these values and a uniform prior.

I could of course write a custom data type for each data type (like IntCategorical and FloatCategorical) but I would much rather leave this up to the user to decide what kind of type this categorical dimension has.

Does that make any sense?

**Comment by timonbimon** [comment]
For completion's sake the way I currently do this is by extending the BaseModel and giving it a new Metaclass that parses the `Categorical[int]` annotation and dynamically creates an `IntCategorical` class out of it (that pydantic then handles normally). I was just wondering if there is a less hacky way to get this done.

**Comment by timonbimon** [comment]
Currently if you try to use a custom generic class, pydantic will say that fields of this type are not supported.
E.g.

```python
from typing import Generic
from typing import TypeVar

from pydantic import BaseModel

T = TypeVar("T")

class Categorical(Generic[T]):
    pass

class MyModel(BaseModel):
    foo: Categorical[int]

```

gives

```bash
Traceback (most recent call last):
  File "<input>", line 11, in <module>
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/hspace-py3.7/lib/python3.7/site-packages/pydantic/main.py", line 197, in __new__
    config=config,
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/hspace-py3.7/lib/python3.7/site-packages/pydantic/fields.py", line 267, in infer
    field_info=field_info,
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/hspace-py3.7/lib/python3.7/site-packages/pydantic/fields.py", line 236, in __init__
    self.prepare()
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/hspace-py3.7/lib/python3.7/site-packages/pydantic/fields.py", line 301, in prepare
    self._type_analysis()
  File "/Users/timon/Library/Caches/pypoetry/virtualenvs/hspace-py3.7/lib/python3.7/site-packages/pydantic/fields.py", line 383, in _type_analysis
    raise TypeError(f'Fields of type "{origin}" are not supported.')
TypeError: Fields of type "<class '__main__.Categorical'>" are not supported.
```

Maybe one could introduce an interface for custom generics, e.g. sth along the lines

```
class CustomGeneric:
    @abstractmethod
    @classmethod
    def substitute_type(type_args: Tuple[Any]) -> Any:
        raise NotImplementedError

class ModelField(Representation):
    def _type_analysis(self) -> None: 
        ...
        elif issubclass(origin, CustomeGeneric):
            self.type_ =  origin.substitute_type(self.type_.__args__)
        ...
```
which would then allow you to implement a custom generic type class (e.g. like so
```
class Categorical(CustomGeneric, Generic[T]):
    @classmethod
    def substitute_type(type_args: Tuple[Any]) -> Any:
        """Returns a type customized by the parameter of the annotation."
        type_arg = type_args[0]
        # do some stuff and return a new type
        return new_class(
             to_title_case(get_class_name(type_arg) + "Categorical"),
            (Categorical,),
            {},
            lambda ns: ns.update({"dtype": type_arg]}),
        )
```


You have thought much more about the typing system and probably know much better if this makes any sense at all, so curious to hear your thoughts. :)

**Comment by dmontagu** [comment]
@timonbimon Have you looked at GenericModel? I think this might cover what you are trying to do.

[Docs here](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)

**Comment by timonbimon** [comment]
oh wow, sorry for not finding this myself.

Thanks a lot for the help and merry christmas 🎄:)
