### ISSUE TITLE
Is there a way to force all  field validators for a field to run even when an error occurs?

### ISSUE THREAD

**Issue by captain-keystone** [samuelcolvin/pydantic#1120]
```py
 def _apply_validators(
        self, v: Any, values: Dict[str, Any], loc: 'LocStr', cls: Optional['ModelOrDc'], validators: 'ValidatorsList'
    ) -> 'ValidateReturn':
        for validator in validators:
            try:
                v = validator(cls, v, values, self, self.model_config)
            except (ValueError, TypeError, AssertionError) as exc:
                return v, ErrorWrapper(exc, loc)
        return v, None
```
This code from fields.py looks as though it short circuits the validation as soon as one error occurs.  
Is it possible to run the remaining validators on a field even if one throws an error? It doesn't seem so but I'm not sure if I'm missing some configuration setting or some hook that might expose that functionality.

**Comment by samuelcolvin** [comment]
not possible I'm afraid, I imagine it would be very difficult to implement without significant changes.
