### ISSUE TITLE
Support passing model class to schema_extra?

### ISSUE THREAD

**Issue by therefromhere** [samuelcolvin/pydantic#1122]
# Feature Request

As a follow-up to #1054, it would be useful if the model class was passed to the schema_extra callable.

I think @dmontagu was thinking along the same lines in this comment: https://github.com/samuelcolvin/pydantic/issues/937#issuecomment-546459285 was there a decision not to implement this or would a PR be accepted?

Please complete:
* OS: Ubuntu 18.04
* Python version `import sys; print(sys.version)`: 3.7.5
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 1.3

My use case is that I'm adding sub-class configuration in my own nested `Meta` classes, and I'd like to extract information from them in the base class's `schema_extra`

```py
from typing import Any, Dict

import pydantic


class MyBase(pydantic.BaseModel):
    class Config:
        @staticmethod
        def schema_extra(schema: Dict[str, Any], model_class):
            # ...do something with model_class
            schema["something"] = model_class.MyMeta.foo


class MySubclass(MyBase):
    class MyMeta:
        foo = "bar"
```

edit: I originally suggested allowing schema_extra to be a classmethod, but that doesn't work because the cls param would be Config, not the outer model class.

**Comment by samuelcolvin** [comment]
agreed this would be useful, it was an oversight not to add a model argument when we first implemented this.

Options:
* wait until v2 to add this
* add a `model` argument and break `v1.3` - since this was only released yesterday I think we could call it a patch?
* inspect `schema_extra` and pass `model` only if the argument is expected. This would be entirely backwards compatible but involve more code

Thoughts?

**Comment by therefromhere** [comment]
I'd say option 2 or 3?

**Comment by samuelcolvin** [comment]
Let's do option 2. PR welcome.

**Comment by therefromhere** [comment]
Actually I've got a PR ready to go which handles 3, pushing shortly.

Happy to cut it down to 2 if you want though.

**Comment by samuelcolvin** [comment]
3 is fine by me.
