### ISSUE TITLE
Is there any post_init method for ModelBase

### ISSUE THREAD

**Issue by kesavkolla** [samuelcolvin/pydantic#1129]
# Question

Please complete:
* OS: Linux
* Python version `import sys; print(sys.version)`: 3.7.5
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 1.2

I've class that extends from **BaseModel**.  Is it possible to have a post init type functionality?  I would like to perform some operation after the initializing the object.

**Comment by samuelcolvin** [comment]
Just overwrite `__init__`, call `super()`, then do your thing.

**Comment by kesavkolla** [comment]
Getting exception if I overwrite `__init__`  Is there any example for this?

**Comment by kesavkolla** [comment]
My bad.... It's working.  Thanks.
