### ISSUE TITLE
Validation. Field value depends in other fields.

### ISSUE THREAD

**Issue by rappongy** [samuelcolvin/pydantic#1134]
# Question

Can I validate several fields together? For example, I'd like to set up that  ```initiated_by``` cannot be ```NOT_INITIATED``` if the ```status``` is ```PLANNED``` or ```RUNNING```.

Is it possible by standart way? 
Thank you!

```py
from enum import Enum
from pydantic import BaseModel

class Statuses(str, Enum):
    NOT_INDEXED = 'not indexed'
    PLANNED = 'planned'
    RUNNING = 'running'
    COMPLETED = 'completed'

class InitiatedBy(str, Enum):
    NOT_INITIATED = 'not_initiated'
    MANUALLY = 'manually'
    CRON = 'cron'

class Process(BaseModel):
    status: IndexingStatusesTypes = IndexingStatusesTypes.NOT_INDEXED
    initiated_by: InitiatedBy = InitiatedBy.NOT_INITIATED
...
```

Using this with FastAPI.

* OS: Ubuntu 18-04
* Python version 3.7
* Pydantic version 0.32.2

**Comment by samuelcolvin** [comment]
Yes, look at the "password2" validator [here](https://pydantic-docs.helpmanual.io/usage/validators/).
