### ISSUE TITLE
Use existing (.pyi) typing information from library

### ISSUE THREAD

**Issue by luckydonald** [samuelcolvin/pydantic#1137]
# Question

Please complete:
* OS: 
macOS (and docker)
* Python version `import sys; print(sys.version)`:
 **3.7.2 (default, Mar 30 2019, 20:19:11) 
[Clang 10.0.1 (clang-1001.0.46.3)]**
* Pydantic version `import pydantic; print(pydantic.VERSION)`:
**1.3**

**Please read the [docs](https://pydantic-docs.helpmanual.io/) and search through issues to
confirm your question hasn't already been answered.**
K.

Where possible please include a self contained code snippet describing your question:

I want to use a library having objects with python type annotation already.

See the `*.pyi` files like https://github.com/luckydonald/pytgbot/blob/7f39d783c1b939f446121f4d0983f2915c8e3881/code_generation/output/pytgbot/api_types/receivable/media.pyi#L535
I now they have a `to_dict()` method to get json-able python objects out of them, and the variables are all annotated.

How do I use those models in a D.R.Y way in my project?
As that's a library without depending on pydantic in any way so the classes won't be subclasses of `BaseModel `, how can I use that typing information which is already there?

**Comment by samuelcolvin** [comment]
I'm afraid I don't understand the question.

Can you explain how this relates to pydantic and what exactly you're trying to do. A short example is often very helpful.

**Comment by luckydonald** [comment]
This is how Pydantic does it:
```py
class File(BaseModel):
    file_id: str
    file_unique_id: str
    file_size: int
    file_path: str
# end class File
```

However I have 
`library.pyi`:
```py
class File(Receivable):
    file_id: str
    file_unique_id: str
    file_size: int
    file_path: str
# end class File
```

My program:
```py
from library import File
import pydantic

PydanticFile = pydantic.please_make_some_magic_class(File)

PydanticFile(file_id="abcxyz", unique_file_id="abc", file_size=4458, file_path="/o/path/to/file/memes.png")
```

**Comment by luckydonald** [comment]
Basically I try to create a `BaseModel` from an already existing class.

**Comment by samuelcolvin** [comment]
This isn't possible using just pydantic.

You would need to write your own parser to process `library.pyi` and write a new python file using pydantic.

**Comment by luckydonald** [comment]
Would that be possible with regular `py` files?

**Comment by samuelcolvin** [comment]
no, pydantic only interprets annotations on subclasses of `BaseModel` and dataclasses.
