### ISSUE TITLE
Feature request: Allow loading an enum based of its name

### ISSUE THREAD

**Issue by liiight** [samuelcolvin/pydantic#1143]
# Feature Request

I'd love the ability to load an enum field based off its name and not (only) by its value. This is my use case:

I want to supply a user friendly API to end client in order to serialize data categories that a different site uses.

This is how my enum looks like:

```python
class Category(Enum):
    pc_games = 21
    console_games = 33
    hd_movies = 27
```
The values are the actual data that I want to pass to the 3rd party site in an HTTP requests, but I'd like the end user to have the ability to supply it by either name or value (in my case via a yaml config).

I was thinking of something like this:

```python
class Model(BaseModel):
    category: Category = Field(..., allow_enum_population_by_name=True)

m = Model(category='pc_games')
print(m)
#> category=<Category.pc_games: 21>
```

Thanks in advance. If you like this idea, I'd like to take a stab implementing it.

**Comment by samuelcolvin** [comment]
you can implement this yourself, https://github.com/samuelcolvin/pydantic/issues/598#issuecomment-503032706.

**Comment by liiight** [comment]
Thanks for the link!
