### ISSUE TITLE
Will pydantic support case_sensitive=False for BaseModel?

### ISSUE THREAD

**Issue by kemingy** [samuelcolvin/pydantic#1147]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.3
            pydantic compiled: True
                 install path: /home/keming/miniconda3/lib/python3.7/site-packages/pydantic
               python version: 3.7.2 (default, Dec 29 2018, 06:19:36)  [GCC 7.3.0]
                     platform: Linux-4.4.0-19536-Microsoft-x86_64-with-debian-buster-sid
     optional deps. installed: []
```

I'm using `pydantic` to build a library [spectree](https://github.com/0b01001001/spectree) that can generate OpenAPI spec and validate the request&response for Flask, Falcon, Starlette. When I try to support `Headers`, I found that keys in headers are in different cases for different backend framework. In Flask, they are capitalized. In Falcon, they are upper cases. In Starlette, they are lower cases. The library will do the validation before the endpoint function handles the request. This will cause `ValidationError: missing field` unless the user specify different variable names with right case (seems ugly) when they are using different backend framework.

So I'd like to know will pydantic supports setting `case_sensitive=False` for `BaseModel`.

Here is an example that I hope to work:

```py
import pydantic

class Headers(pydantic.BaseModel):
    Lang: str

    class Config:
        case_sensitive=False

headers = Headers(lang='en-US') # starlette
headers = Headers(LANG='en-US') # falcon
headers = Headers(Lang='en-US') # flask
```

**Comment by kemingy** [comment]
For more information, here is how I handle it in the test.

Define 3 Headers with different cases: [Headers](https://github.com/0b01001001/spectree/blob/8a64bf98554084701fd573271c2806e349495625/tests/common.py#L31)

Then different framework uses different headers. [flask](https://github.com/0b01001001/spectree/blob/8a64bf98554084701fd573271c2806e349495625/tests/test_plugin_flask.py#L16) [falcon](https://github.com/0b01001001/spectree/blob/8a64bf98554084701fd573271c2806e349495625/tests/test_plugin_falcon.py#L15) [starlette](https://github.com/0b01001001/spectree/blob/8a64bf98554084701fd573271c2806e349495625/tests/test_plugin_starlette.py#L16)

**Comment by samuelcolvin** [comment]
No pydantic won't support `case_sensitive=False` out of the box, but you can accomplish it very easily.

Just add a [root-validator with `pre=True`](https://pydantic-docs.helpmanual.io/usage/validators/#root-validators) and convert all keys to lower case, then set up field names to be lower case.

**Comment by NotoriousPyro** [comment]
FYI anyone trying to do this, I used the following as per @samuelcolvin:

```python
class MyClass(BaseModel):
    @root_validator(pre=True)
    def lowercase_property_keys(cls, values: Any) -> Any:
        def __lower__(value: Any) -> Any:
            if isinstance(value, dict):
                return {k.lower(): __lower__(v) for k, v in value.items()}
            return value

        return __lower__(values)
```

**Comment by jimkring** [comment]
Thanks @NotoriousPyro. I just tried this with pydantic v2 and I get the following deprecation warning:

```
Pydantic V1 style `@root_validator` validators are deprecated. You should migrate to Pydantic V2 style `@model_validator` validators, see the migration guide for more details 
```

Here is what I think the solution looks like in v2 (note the use of `@model_validator(mode="before")` instead of `@root_validator(pre=True)`)

```python
class CaseInsensitiveModel(BaseModel):
    @model_validator(mode="before")
    def __lowercase_property_keys__(cls, values: Any) -> Any:
        def __lower__(value: Any) -> Any:
            if isinstance(value, dict):
                return {k.lower(): __lower__(v) for k, v in value.items()}
            return value

        return __lower__(values)
```

**Comment by KonScanner** [comment]
After the v2.3 migration (see [here](https://docs.pydantic.dev/2.3/migration/)) the `parse_obj_as` is deprecated in favour for `TypeAdapter`.

 With the changes, it should look something like this:

```
from pydantic import TypeAdapter, BaseModel
from typing import Any

class CaseInsensitiveAdapter(TypeAdapter[Any]):
    def validate_python(self, value: Any) -> Any:
        def __lower__(value: Any) -> Any:
            if isinstance(value, dict):
                return {k.lower(): __lower__(v) for k, v in value.items()}
            return value

        value = __lower__(value)
        return super().validate_python(value)

class MyClass(BaseModel):
    my_property: str

adapter = CaseInsensitiveAdapter(MyClass)
my_obj = adapter.validate_python({"MY_PROPERTY": "hello"})
print(my_obj)
```

**Comment by saumzzz** [comment]
I've found another workaround by going through the codebase, 
I'm not sure if this would be a good way to do this

```python
from pydantic import BaseModel

class Foo(BaseModel):
    Name: str

Foo(name='bar') # raises validation error


for field_name, field_info in Foo.model_fields.items():
    field_info.validation_alias = field_name.lower()

Foo.model_rebuild(force=True)

Foo(name='bar') # raises no validation error
```
