### ISSUE TITLE
Typing issue when using orjson

### ISSUE THREAD

**Issue by aviramha** [samuelcolvin/pydantic#1149]
The signature of `json` function of BaseModel is as follows:
`def json(
        self,
        *,
        include: Union['AbstractSetIntStr', 'DictIntStrAny'] = None,
        exclude: Union['AbstractSetIntStr', 'DictIntStrAny'] = None,
        by_alias: bool = False,
        skip_defaults: bool = None,
        exclude_unset: bool = False,
        exclude_defaults: bool = False,
        exclude_none: bool = False,
        encoder: Optional[Callable[[Any], Any]] = None,
        **dumps_kwargs: Any,
    ) -> str
`
This function calls json_dumps, which in case of orjson, returns bytes.
This is not critical, but influences mypy checking (I'm using ignore right now in my app).
My suggestion is to change the signature to Union[str, bytes].

**Comment by samuelcolvin** [comment]
This is already covered [in the docs](https://pydantic-docs.helpmanual.io/usage/exporting_models/#custom-json-deserialisation), the best solution is to use `orjson.dumps(...).decode()`.

The performance impact of this change will be very small, but if you really care, `ignore` is the best option, or you could override `json()` and change the signature.

using `Uion[str, bytes]` would complicate things for the 99.9% of cases where the value returned is a string.
