### ISSUE TITLE
orjson encoding issue

### ISSUE THREAD

**Issue by aviramha** [samuelcolvin/pydantic#1150]
# Bug

I'm able to reproduce the bug only when using a container, not on the host computer.
I tested various python3.7.x versions (official python images), all had the same issue.
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
import pydantic.utils; print(pydantic.utils.version_info())
             pydantic version: 1.3
            pydantic compiled: True
                 install path: /usr/local/lib/python3.7/site-packages/pydantic
               python version: 3.7.0 (default, Oct 16 2018, 07:10:55)  [GCC 6.3.0 20170516]
                     platform: Linux-4.9.184-linuxkit-x86_64-with-debian-9.5
     optional deps. installed: []
```

```py
import orjson
from pydantic import BaseModel

class DynamicContext(BaseModel):
    lala: int
    class Config:
        json_loads = orjson.loads
        json_dumps = orjson.dumps

DynamicContext(lala=1).json()


```
Will raise:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 379, in pydantic.main.BaseModel.json
TypeError: Expected unicode, got bytes
```

**Comment by samuelcolvin** [comment]
This is because when compiled (which pydantic will be when used in docker, but no on mac or windows) cython does some type checking which is causing your problem. See https://github.com/samuelcolvin/pydantic/pull/799#issuecomment-560168708 and related issues and pull requests.

The easiest solution (like I said in #1149) is to use a wrapper function as suggested in the docs.

Alternatively, you could submit a PR to change the return type to `Union[str]`.

**Comment by samuelcolvin** [comment]
(You'll see when you call `version_info()` outside the container `pydantic compiled: False`.)

**Comment by aviramha** [comment]
> This is because when compiled (which pydantic will be when used in docker, but no on mac or windows) cython does some type checking which is causing your problem. See [#799 (comment)](https://github.com/samuelcolvin/pydantic/pull/799#issuecomment-560168708) and related issues and pull requests.
> 
> The easiest solution (like I said in #1149) is to use a wrapper function as suggested in the docs.
> 
> Alternatively, you could submit a PR to change the return type to `Union[str]`.

Return type of json to Union[str]?

**Comment by samuelcolvin** [comment]
yes

**Comment by samuelcolvin** [comment]
and `Config.json_dumps` I guess, you'll need to check with a test.

**Comment by HonQii** [comment]
You need `decode`, like this

```python
def _orjson_dumps(val, *, default):
    return orjson.dumps(val, default=default).decode()

class Model(BaseModel):
    pass

    class Config:
        json_loads = orjson.loads
        json_dumps = _orjson_dumps
```
