### ISSUE TITLE
Add support for positional arguments

### ISSUE THREAD

**Issue by TimSimpsonR** [samuelcolvin/pydantic#116]
It seems Pydantic does not support positional arguments in the initializers it gives each BaseModel.

This is probably intentional and just a difference in philosophy. However it would be nice if it was supported.

In case this never changes, I'll share my current work around in case it helps anyone who Googles this. I'm extending BaseModel and adding an `__init__` function which checks the `fields` property. This is probably not the fastest solution because it creates a list from the fields each time:

```
import pydantic

class BaseModel(pydantic.BaseModel):

    def __init__(self, *args, **kwargs):
        pos_args = list(self.fields.keys())

        for i in range(len(args)):
            if i >= len(pos_args):
                raise TypeError(f'__init__ takes {len(pos_args)} '
                                'positional arguments but 2 were given.')
            name = pos_args[i]
            if name in kwargs:
                raise TypeError(f'{name} cannot be both a keyword and '
                                'positional argument.')
            kwargs[name] = args[i]

        return super().__init__(**kwargs)
```

**Comment by samuelcolvin** [comment]
positional arguments can be extremely dangerous, particularly:
* when you have lot of fields - it would be very easy to add another field into a model and suddenly all code which assumes fields have a given position breaks silently
* annotation only fields mean the order of pydantic model fields different from that in code, see [here](https://pydantic-docs.helpmanual.io/#strict-optional).

Also the code above will slow down pydantic a fair bit in a critical path.

I'm afraid I won't be adding support for positional arguments and I would recommend you don't use them either, but of course it's your choice :smile_cat:
