### ISSUE TITLE
value of exclusiveMinimum is wrong

### ISSUE THREAD

**Issue by BurningLutz** [samuelcolvin/pydantic#1164]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.3
            pydantic compiled: False
                 install path: /Users/lutz/.pyenv/versions/3.8.0/envs/fastapi-py3/lib/python3.8/site-packages/pydantic
               python version: 3.8.0 (default, Jan 13 2020, 14:48:00)  [Clang 11.0.0 (clang-1100.0.33.16)]
                     platform: macOS-10.15.2-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']

```

According to the [OPENAPI Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#properties) and [JSON Schema Validation](https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-5.5), the value of `exclusiveMinimum` and `exclusiveMinimum` should be a boolean instead of a number, and the `minimum` and `maximum` field should be set to represent the lower/upper limit.

**Comment by samuelcolvin** [comment]
@tiangolo any thoughts?

**Comment by samuelcolvin** [comment]
@dmontagu I see you assigned this to yourself. 

For clarity, do you agree the current schema is wrong? If so, how do we go about changing this? V2?

**Comment by Zac-HD** [comment]
This behaviour depends on which version of JSONSchema you're targeting - draft 4 uses a numeric minimum and boolean exclusiveMinimum, more recent versions just a numeric exclusiveMinimum.

**Comment by samuelcolvin** [comment]
Thank you @Zac-HD.

https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.2.5

**Comment by BurningLutz** [comment]
@Zac-HD @samuelcolvin 
Though the latest JSONSchema defines exclusiveMinimum as a numeric field, but since the latest OPENAPI specification uses the old definition, shouldn't this still be a bug?

In fact, I cannot find an OPENAPI tool to support the numeric exclusiveMinimum. It just get ignored when generating docs.

**Comment by samuelcolvin** [comment]
It should be easy enough to change with [`schema_extra`](https://pydantic-docs.helpmanual.io/usage/schema/#schema-customization) as a function.

Given this has been like this for some time and it matches the latest JSONSchema, I'm not keen to change it.

**Comment by dmontagu** [comment]
@samuelcolvin Sorry for slow response, I assigned it to myself with the intention of investigating more deeply. Thanks @Zac-HD for following up on this.

I think it is unfortunate that the two specs are currently in disagreement, and I know OpenAPI tooling can take a while to get updated. At the same time, I also believe perfectly supporting all nuances of the common JSON specs has to be weighed against the maintenance burden and work on other feature requests, performance improvements, etc.

At this point I'm in agreement with @samuelcolvin that this is best handled by writing a (reusable) `schema_extra` processing function if you need it.

----

@BurningLutz I would be happy to incorporate a function that could be used to do this into https://github.com/dmontagu/fastapi-utils -- if you are interested please create an issue there!
