### ISSUE TITLE
Attribute cannot have the same name as its type

### ISSUE THREAD

**Issue by catethos** [samuelcolvin/pydantic#117]
I am trying to make the class attribute having the same name as its type. The following code does not work and show the `ConfigError`
```
class A(BaseModel):
    pass

class B(BaseModel):
    A: A = None
```

```
ConfigError: unable to infer type for attribute "A"
```

However, if I make the attribute no default value then it works

```
class A(BaseModel):
    pass

class B(BaseModel):
    A: A 
```

Is this behavior intended?

**Comment by samuelcolvin** [comment]
This is a consequence of how python annotations work and not specific to pydantic:

```
In [1]: class Foo:
   ...:     pass
   ...: 

In [2]: class Bar:
   ...:     Foo: Foo = None
   ...:     span: str = None
   ...:     

In [3]: Bar.__annotations__
Out[3]: {'Foo': None, 'span': str}
```

I've no idea if this is intentional behaviour or a bug in the standard library but there's nothing pydantic can do about it since it's just consulting the `__annotations__` dict and finding `None`.

**Comment by hb2638** [comment]
This is related to https://github.com/python/mypy/issues/1775
I ended up using an alias

so using your example

before


```python
class A(BaseModel):
    pass

class B(BaseModel):
    A: A = None`
```



after

```python
class A(BaseModel):
    pass

_A = A

class B(BaseModel):
    A: _A = None
```
