### ISSUE TITLE
How to map deeply nested json property to model property?

### ISSUE THREAD

**Issue by arajkumar** [samuelcolvin/pydantic#1189]
Thanks for your great work!

# Question
How to map deeply nested json property to model property?

```
from pydantic import BaseModel

class Name(BaseModel):
    firstName: str
    lastName: str

class User(BaseModel):
    name: str # how to map Name.firstName to this field

external_data = {
   'foo': {'firstName': 'Foo', 'lastName': 'Bar'},
}
user = User(**external_data)
print(user.dict())

```

In the above example, I would like to map the `Name.firstName` property to `User.name` which is nested inside `foo`. In flask-restplus there is a [way to access it](https://flask-restplus.readthedocs.io/en/stable/marshalling.html#renaming-attributes) using `attribute` property.(`attribute='foo.firstName'` will do the mapping)

Is it possible to do the same in `pydantic`? I tried with `Config` class, but it didn't work. Am I missing something?

**Comment by samuelcolvin** [comment]
The best solution is to use a [root validator](https://pydantic-docs.helpmanual.io/usage/validators/#root-validators) with `pre=True`, and mutate the input data, in this case simply

```py
@root_validator(pre=True)
def extra_foo(cls, v):
    return v['foo']
```

In future we might add a more sophisticated way to extract data from an object, perhaps via `load_alias` #624, but it's not in the immediate future and would be hard while maintaining performance.

**Comment by arajkumar** [comment]
Thanks a lot @samuelcolvin 👍 

I will give it a try using `root_validator`. What about using `Schema`? Will it work in this case?

**Comment by samuelcolvin** [comment]
no, for that you would need to represent the schema you actually want with models, see [here](https://pydantic-docs.helpmanual.io/usage/models/#recursive-models)
