### ISSUE TITLE
How do I expose both alias and non-alias for object construction

### ISSUE THREAD

**Issue by lamdaV** [samuelcolvin/pydantic#1191]
# Question
I would like to be able to create a `BaseModel` in which I could provide an alias for `camelCase` but still be able to construct it using `snake_case` kwargs. Is this supported at the moment?

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.4
pydantic compiled: False
install path: REDACTED
python version: 3.6.9 (default, Oct 28 2019, 11:31:43)  [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)]
platform: Darwin-18.7.0-x86_64-i386-64bit
optional deps. installed: ['typing-extensions']
```

```py
from pydantic import BaseModel

def to_camel(string: str) -> str:
    return ''.join(word.capitalize() for word in string.split('_'))

class Voice(BaseModel):
    name: str
    language_code: str

    class Config:
        alias_generator = to_camel

# aliased kwargs
voice_pascal_case = Voice(Name='Filiz', LanguageCode='tr-TR')
# non-aliased kwargs
voice_snake_case = Voice(name='Filiz', language_code='tr-TR') # throws exception
```

I would like to be able to use both `voice_pascal_case` and `voice_snake_case` construction.

**Comment by samuelcolvin** [comment]
[`allow_population_by_field_name`](https://pydantic-docs.helpmanual.io/usage/model_config/)

Best to try consulting the docs before creating issues.

**Comment by lamdaV** [comment]
Thanks for the quick response. I skimmed past this option while jumping around in the docs.
