### ISSUE TITLE
Adding models to store lists

### ISSUE THREAD

**Issue by gautamsinghania95** [samuelcolvin/pydantic#1196]
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.4
pydantic compiled: False
install path: # Hiding this
python version: 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
platform: Darwin-19.0.0-x86_64-i386-64bit
optional deps. installed: ['email-validator']
```

Can we have a new class called something like `ListModel`, which can store lists of information, the way `BaseModel` does it for a dictionary. An example code is as below:

```py
from pydantic import ListModel

class SampleListModel(ListModel):
    # Should be only one variable with a fixed name
    # That describes the type of each item in the list
    ITEM: int

    # Works on each list element
    @validator
    def check_positive(cls, item):
        if item <= 0:
            raise ValueError("Only positive elements allowed")

    # Works on the whole list
    @root_validator
    def check_sorted(cls, items):
        if sorted(items) != items:
            raise ValueError("Array should be sorted")

# Assignment can be done by giving variable args,
# like BaseModel accepts kwargs

x = SampleListModel(1, 2, 3)
# Happy case

y = SampleListModel(-1, 0, 1)
# Fails for check_positive

z = SampleListModel(3, 2, 1)
# Fails for check_sorted
```

We can also have sequence models like TupleModel when the number of elements are fixed and the type of elements are different.

I believe that this will greatly increase the power of pydantic by unlocking many usecases.

**Comment by dmontagu** [comment]
Have you considered using a model with a custom root type?

**Comment by samuelcolvin** [comment]
use either [custom root types: `__root__`](https://pydantic-docs.helpmanual.io/usage/models/#custom-root-types) or [`parse_obj_as`](https://pydantic-docs.helpmanual.io/usage/models/#parsing-data-into-a-specified-type)

**Comment by Shados** [comment]
@samuelcolvin I can't speak for the OP, but both your stated approaches have at least one downside each:
- Setting something like `__root__: List[ItemType]` doesn't let you treat the created model *as* a `List[ItemType]`; enumerating it doesn't enumerate over `__root__`'s items, you can't subscript it, etc.
- `parse_obj_as(List[ItemType], items)` returns an actual list, rather than a list-like class of your own making, which means you have no obvious place to hang associated functions/methods.

Of course, I could take the custom root type route, and implement the required extra methods needed to emulate a list (and I have), but this *does* seem like something that should have a generic version in pydantic itself.

**Comment by gautamsinghania95** [comment]
@Shados I agree. Even though the solution suggested by @samuelcolvin works, there are a lot of usability issues that needs to be addressed.

**Comment by samuelcolvin** [comment]
So what would you suggest?

**Comment by gautamsinghania95** [comment]
@samuelcolvin I feel that my suggestion above holds merit in this. Please take a look and suggest if any changes are required in that way of working.

**Comment by darkdreamingdan** [comment]
I'm currently struggling trying to use `t.List[constr()]`  in a mypy compatible way.  Currently, the reccomended way to have a a string (not in a list) that's mypy compatible would be:

`my_text: str = Field(max_length=32)`

However, what if you wanted a list of constr?

`my_text_list: t.List[str] = ???`.

I haven't been able to find a solution to this problem.  Breaking out the List object into a custom Pydantic model would allow me to specify the types properly.
