### ISSUE TITLE
Create JSON from empty model

### ISSUE THREAD

**Issue by GeorgeFischhof** [samuelcolvin/pydantic#1202]
# Feature Request

Hi There,

it would be good to have a function which results an empty JSON structure from a module, similar to .json() method. Just should work without validation, and without any data.

Use case:
I created a nested model which contain about 50 fields, that will be requested by UI (I use fastapi)
It is a lot of work to create the appropriate JSON, and then fill up. If there would be an empty JSON, it would be easy to fill it up, and UI developer can work with that mocked data.
In the meantime backend developers can create real data

```
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
             pydantic version: 1.3
            pydantic compiled: False
                 install path: C:\Python37\Lib\site-packages\pydantic
               python version: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.17763-SP0
     optional deps. installed: ['typing-extensions', 'email-validator']
```

```py
from pydantic import BaseModel

class Venue(BaseModel):
    nick_name: str
    address: str = None
    phone_number: str = None

print(Venue.empty_json())

"""
 {
    "nick_name":
    "address":
    "phone_number":
 }
"""

and so on with the nested fields. It is similar to scheme, but without metadata

BR,
George
```

**Comment by samuelcolvin** [comment]
Thanks, but this would be best implemented within your own code.

E,g, use your own custom base model `CustomBaseModel` which implements the `empty_json` method:

```py
class CustomBaseModel(BaseModel):
    def empty_json(self) -> str:
        return json.dumps({f: None for f in self.__fields__.keys()})

class User(CustomBaseModel):
    first_name: str
    ...
```
Obviously you will need to extend `empty_json` to be recursive, but that shouldn't be too hard.
