### ISSUE TITLE
How to provide a custom constructor for a field

### ISSUE THREAD

**Issue by a-recknagel** [samuelcolvin/pydantic#1211]
I have a config file that contains regular expressions (among other things), and I want to parse each line into a `pydantic` class. The relevant part of the class definition is this:

```python
from typing import Pattern

from pydantic import BaseModel

class Rule(BaseModel) :
    pattern: Pattern

Rule(pattern=r'my regex')  # works
```

The only problem here is that I can't specify compile flags for the pattern. I would have thought that there might be a generic way to specify a custom init function for a type if the default one that `pydantic` assumes doesn't cut it for some reason, something like this:

 
```python
from typing import Pattern
import re

from pydantic import BaseModel, Field

class Rule(BaseModel) :
    # this is not how filed works, but you get the idea...
    pattern: Pattern = Field(init_func=lambda x: re.compile(x, re.IGNORE_CASE))

Rule(pattern=r'my regex')  # works, and will ignore case
```

But my googling and searching in the docs didn't turn up with anything. I would probably be able to write a workaround with some kind of post-init or by using properties, but I would really prefer to use a solution that looks like the one I sketched above.

----

edit: adding `def __post_init_post_parse__(self): self.pattern = re.compile(self.pattern.pattern, re.IGNORECASE)` to the initial class definition solves the problem, but feels hackier to me than adding the correct initialisation function to the attribute definition.

**Comment by samuelcolvin** [comment]
you should use [validators with `pre=True`](https://pydantic-docs.helpmanual.io/usage/validators/#pre-and-per-item-validators) and return a compiled regex.

**Comment by samuelcolvin** [comment]
Please use an issue template in future.

**Comment by a-recknagel** [comment]
Thanks for answering. I tried your suggestion, but it doesn't seem to work

```python
>>> import pydantic
>>> from typing import Pattern
>>> import re
>>> class Foo(pydantic.BaseModel):
...     
...     pattern: Pattern
...     @pydantic.validator('pattern', pre=True)
...     def ignore_case(cls, v):
...         return re.compile(v, re.IGNORECASE) 
...     
>>> Foo(pattern='BLA')
```
I'm getting

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "pydantic/main.py", line 283, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Foo
pattern
  str type expected (type=type_error.str)
```
which is triggered by the original pattern-validator. Can I disable or control that one somehow? I'd like to keep using `typing.Pattern` to annotate my field.

**Comment by a-recknagel** [comment]
@samuelcolvin I think that my problem is not solved, but I can't reopen the issue.

**Comment by blakete** [comment]
I was able to resolve my issue by using ```@validator("foo", pre=True)```
