### ISSUE TITLE
 Pydantic Validation with database connection

### ISSUE THREAD

**Issue by ankithherle** [samuelcolvin/pydantic#1227]
#### I want to validate a field against the database., i.e. Check Whether a field exists in the database's table (similar to [Marshmallow](https://marshmallow.readthedocs.io/en/stable/))?
I am using `SQLalchemy` as the ORM, Is it possible to write such validators with `Pydantic`

My code sample looks like

```
class EmailSchema(BaseModel):
    address: str
    inserted_at: datetime

    @validator('email')
    def validate_name(cls, value, db_session:Session = Depends(get_db)):
        if db_session.query(Email).filter(Email.address == value).count():
            raise ValueError('Email already exists')
        return value
```

Currently, it is not working, Is this type of validator allowed in pydantic ? How to use it ?

**Comment by samuelcolvin** [comment]
The short answer is you shouldn't do IO (including db access) in validators, because:
1. most new development would use asyncio for db access which won't work in validators which aren't coroutines
2. it's very useful to have a hard distinction between checking the data integrity and checking whether it's consistent with the rest of the world

However it you really want to do this it should be possible, you just need to make `db_session` global or otherwise accessible via closure inside the validator.

**Comment by ankithherle** [comment]
OK, Then I have to a separate validation methods to do validations with the database things?



> otherwise accessible via closure inside the validator.

Can you please give an example of this ?

**Comment by samuelcolvin** [comment]
```py
def whatever():
    db_session = ...
    
    class EmailSchema(BaseModel):
        address: str
        inserted_at: datetime
    
        @validator('email')
        def validate_name(cls, value):
            if db_session.query(Email).filter(Email.address == value).count():
                raise ValueError('Email already exists')
            return value
```

**Comment by danish-wani** [comment]
Like others I also have done the DB validations inside the validators, which not only as per @samuelcolvin violates the SOC (separation of concerns) but also makes it almost impossible to test while writing unit tests. When you are using the dependency injection in Fast API for creating DB sessions you can easily override this in Fast API by overriding the dependencies like `app.dependency_overrides[get_db] = get_test_db` but there is no way you can send this session to the validator hence you end up using the actual DB session inside the validator thereby halting your unit tests.

**Comment by itjuba** [comment]
> Like others I also have done the DB validations inside the validators, which not only as per @samuelcolvin violates the SOC (separation of concerns) but also makes it almost impossible to test while writing unit tests. When you are using the dependency injection in Fast API for creating DB sessions you can easily override this in Fast API by overriding the dependencies like `app.dependency_overrides[get_db] = get_test_db` but there is no way you can send this session to the validator hence you end up using the actual DB session inside the validator thereby halting your unit tests.

And that's exactly my issue, thank you for sharing
