### ISSUE TITLE
field name is ignored during population if alias specified

### ISSUE THREAD

**Issue by dmig-alarstudios** [samuelcolvin/pydantic#1230]
# Question
I'm trying to populate a model by both an alias and a field name using `allow_population_by_field_name`. Model field gets populated only by alias which always has priority.
I expected a field to be populated by last (or first) specified argument.

Am I doing something wrong or this is a bug?

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: True
                 install path: /home/dmig/.pyenv/versions/3.8.1/envs/marty-services-3.8.1/lib/python3.8/site-packages/pydantic
               python version: 3.8.1 (default, Dec 26 2019, 09:35:25)  [GCC 9.2.1 20191008]
                     platform: Linux-5.3.0-40-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions', 'email-validator']
...
```

```py
from pydantic import BaseModel, Field

class Character(BaseModel):
    mood: str = Field(None, alias='lang')

    class Config:
        allow_population_by_field_name = True
```
```
>>> Character(lang='aa', mood='bb')
Character(mood='aa')
>>> Character(mood='bb', lang='aa')
Character(mood='aa')
```

**Comment by samuelcolvin** [comment]
I think the current behaviour is correct.

Sorry not to be more helpful, I think you might be able to achieve this via a pre-processing function.
