### ISSUE TITLE
Include a `allowed_tlds` property in AnyUrl

### ISSUE THREAD

**Issue by eillarra** [samuelcolvin/pydantic#1235]
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: .../virtualenvs/py-pydantic/lib/python3.7/site-packages/pydantic
               python version: 3.7.4 (default, Sep 26 2019, 11:32:05)  [Clang 10.0.0 (clang-1000.10.44.4)]
                     platform: Darwin-17.7.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

I think it would make sense to have an `allowed_tlds` property in AnyUrl. Use case is very specific, but it would only require to change a couple of lines in the library, and it will allow things like:

```python
class TorUrl(AnyUrl):
    allowed_schemes = {'http', 'https'}
    allowed_tlds = {'onion'}
```

I can prepare a PR if you like the idea.

**Comment by samuelcolvin** [comment]
Humm, I'm torn since it should be fairly easy for you to implement your own custom type to implement this.

Why not start by implementing your own class/type and we'll leave this open to see if anyone is interested.

**Comment by eillarra** [comment]
Sure :)
