### ISSUE TITLE
Support for python datatype complex

### ISSUE THREAD

**Issue by kshitijc** [samuelcolvin/pydantic#1240]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
└─▪ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.3
            pydantic compiled: False
                 install path: /Volumes/workplace/chhabrk/abc/lib/python3.7/site-packages/pydantic
               python version: 3.7.5 (default, Nov  1 2019, 02:16:32)  [Clang 11.0.0 (clang-1100.0.33.8)]
                     platform: Darwin-18.7.0-x86_64-i386-64bit
     optional deps. installed: []
```

```py
from pydantic import BaseModel, conlist

class MatrixType(BaseModel):
    matrix: conlist(conlist(complex, min_items=2), min_items=2)

```
 causes:

```
    raise RuntimeError(f'no validator found for {type_}, see `arbitrary_types_allowed` in Config')
RuntimeError: no validator found for <class 'complex'>, see `arbitrary_types_allowed` in Config
```

How can I incorporate supporting the python datatype [complex](https://docs.python.org/3/library/functions.html#complex) in pydantic for my application ?

**Comment by samuelcolvin** [comment]
You need to either implement a [custom data type](https://pydantic-docs.helpmanual.io/usage/types/#custom-data-types) which wraps `complex` to submit a PR for pydantic to support the native type, but that's quite complicated.

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
