### ISSUE TITLE
Correctly typed default values for specialized types e.g. PositiveInt, Json, ...

### ISSUE THREAD

**Issue by SaschaSchlemmer** [samuelcolvin/pydantic#1243]
Neither in the documentation nor any code on the repo (e.g. in tests) could I find any example of how to work with more exotic pydantic types such as `PositiveInt` or `Json` that have default values:

Take for instance :

```python
class Foo(BaseModel):
    bar: PositiveInt = 1  # mypy complains about a type mismatch between PositiveInt and int
```

fair enough, let's try:

```python
class Foo(BaseModel):
    bar: PositiveInt = PositiveInt(1)  # typechecks, hooray
```

How about `Json` then ?

```python
class Foo(BaseModel):
    bar: Json = {"hello": "world"}  # same as above, Json is not a type alias of Dict
```

```python
class Foo(BaseModel):
    bar: Json = '{"hello": "world"}'  # again, Json is not a type alias of str
```

however:

```python
class Foo(BaseModel):
    bar: Json = Json({"hello": "world"})  # doesn't work as Json takes no arguments
```

How does one add a default value for a `Json` field (or any other more exotic field for that matter)?

**Comment by samuelcolvin** [comment]
Options:
* Use `type: ignore`
* Use `x: int = Field(.., ge=0)`
* Might be a possibility to modify the mypy plugin to accept this.

Regarding `Json` I'm not sure what we can do since the internal data could be anything. Might be possible to alter the mypy plugin, or find another escape hatch.

Maybe we could do something like `if TYPE_CHECKING: Json = Any; else: ...`? PR welcome if that works.

**Comment by SaschaSchlemmer** [comment]
What do you think about introducing fields specifically for parsing json objects and arrays. Imho these solves four issues:

1. Removes the ambiguity that a parsed `Json` can either be a `list`, `dict`, `str`, `int`, `float`, `bool` or `None` at runtime and thus removes additional runtime checks (which is one of the main purposes of parsing, see [this article](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/) for a very well written opinion on the subject of parsing vs validating input)
2. Obvious which type to expect at runtime 
3. Lets the user provide default values that typecheck 
4. Prevents the common mistake of assuming `json == json` object or `json == json object | json array` 

An implementation could look like this:

```python
class JsonObject(dict):
    """Field for parsing json objects into a python dictionary."""

    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        error = ValueError(f'The provided value {v} is not a valid json object')
        try:
            data = json.loads(v)
        except json.JSONDecodeError:
            raise error
        else:
            if not isinstance(data, dict):
                raise error
            return cls(data)


class JsonArray(list):
    """Field for parsing json arrays into a python list."""

    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        error = ValueError(f'The provided value {v} is not a valid json array')
        try:
            data = json.loads(v)
        except json.JSONDecodeError:
            raise error
        else:
            if not isinstance(data, list):
                raise error
            return cls(data)
```

and usage would be 

```python
class Data(BaseModel):
    obj: JsonObject = JsonObject({})
    array: JsonArray = JsonArray([])
    other: Union[JsonArray, JsonObject] = JsonObject({})
```

notice that the above typechecks correctly and that at runtime one could use e.g. `isinstance(..., JsonArray)` for determining the type of `other`. This is imho a clearer expression of intent than using `isinstance(..., list)`

**Comment by samuelcolvin** [comment]
Not necessary, you can already use `Json[List[int]]` or `Json[List[Any]]`.

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
