### ISSUE TITLE
Objects are copied duing validation

### ISSUE THREAD

**Issue by NovaNekmit** [samuelcolvin/pydantic#1246]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
$ python3 -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.4a1
            pydantic compiled: False
                 install path: /home/[user]/git/pydantic/pydantic
               python version: 3.7.5 (default, Nov 20 2019, 09:21:52)  [GCC 9.2.1 20191008]
                     platform: Linux-5.3.0-29-generic-x86_64-with-Ubuntu-19.10-eoan
     optional deps. installed: []
```

Recursive models create a copy of the object during validation, this also happens with `Outer(i=Inner())`.  
This stops the `is` operator from working. I would also assume that it impacts performance slightly more than directly using the object. 

```py
from pydantic import BaseModel, validator

class Inner(BaseModel):
    pass

class Outer(BaseModel):
    i: Inner

    # for prints only
    @validator('i', pre=True)
    def print_id_pre(cls, value):
        print("pre_val: ", hex(id(value)))
        return value

    @validator('i')
    def print_id(cls, value):
        print("normal_val: ", hex(id(value)))
        return value

i = Inner()
print("i: ", hex(id(i)))
o = Outer(i=i)
print("o.i: ", hex(id(o.i)))
print("i is o.i: ", i is o.i)
```
Output:
```
i:  0x7fe11da0ab40
pre_val:  0x7fe11da0ab40
normal_val:  0x7fe11da0abe0
o.i:  0x7fe11da0abe0
i is o.i:  False
```

**Comment by samuelcolvin** [comment]
This is an expected result of how we validate submodels, might be possible to change this behavior in v2.

**Comment by mcgfeller** [comment]
Hi - I'm trying to convert from Marshmallow (where I rolled my own object handling) and stumbled upon this.

Is there a workaround? I assume the `inner` object `i ` has already been validated when passing it into the `outer`. So there is _no need to revalidate_, just check that `Outer.i` is indeed of class `Inner`. 

Is there any way to do this, now or in v2? 

Thank you!

Pydantic looks so much more straightforward than Marshmallow.

**Comment by NovaNekmit** [comment]
I ended up making a custom `BaseModel`, which wraps the `validate` function and does not copy objects of the correct type.

See https://github.com/samuelcolvin/pydantic/blob/master/pydantic/main.py#L575

**Comment by mcgfeller** [comment]
Thank you, @NovaNekmit , that does the trick nicely.

**Comment by mcgfeller** [comment]
@samuelcolvin : I still think the behaviour should change (or be optional) for 2.0. The copy surprised me, and there should be an obvious way to avoid it. Thanks! Martin
