### ISSUE TITLE
GenericModel - inheritance and Optional[TypeX] - fail to instantiate a subclass

### ISSUE THREAD

**Issue by Esadruhn** [samuelcolvin/pydantic#1247]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: /Users/thaisdeboisfosse/envs/thenv/lib/python3.7/site-packages/pydantic
               python version: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21)  [Clang 6.0 (clang-600.0.57)]
                     platform: Darwin-19.3.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```
### Summary

Thank you for the lib ! I found a weird bug while using GenericModel.

I create a BaseClass that inherits GenericModel and uses Generic. It contains a property X of type Optional[TypeX].

I create a subclass that fixes the Generic at runtime. The bug is that I cannot define the type of the Generic without an error.

If `X` is of type `TypeX` instead of `Optional[TypeX]` then there is no error (it is what I ended up doing).

### Code to reproduce the error

```py
import pydantic

TypeX = TypeVar('TypeX')

class BaseClass(GenericModel, Generic[TypeX]):
    X: Optional[TypeX]  # This causes the error

class ChildClass(BaseClass[TypeX], Generic[TypeX]):
    pass

ChildClass[int]
```

Error: 
```
cls = <class 'test_base_format.test_pydantic_failes.<locals>.ChildClass'>
params = <class 'int'>

    def __class_getitem__(cls: Type[GenericModelT], params: Union[Type[Any], Tuple[Type[Any], ...]]) -> Type[Any]:
        cached = _generic_types_cache.get((cls, params))
        if cached is not None:
            return cached
        if cls.__concrete__:
>           raise TypeError('Cannot parameterize a concrete instantiation of a generic model')
E           TypeError: Cannot parameterize a concrete instantiation of a generic model
```

**Comment by samuelcolvin** [comment]
@dmontagu is the expert on `GenericModel`, any idea?

**Comment by daviskirk** [comment]
I'm hitting this as well, it looks like the value of "concrete" is calculated by running:

```
        concrete = all(not _is_typevar(v) for v in concrete_type_hints.values())
```

and Optional[T] does not qualify as a typevar even though it should.
The same goes for any more nested objects (including nested generic models).

Most of it can probably be fixed by modifying `_is_typevar` to detect nested type vars.
