### ISSUE TITLE
Python 3.6 BaseModel Inheritance different than 3.7

### ISSUE THREAD

**Issue by nwalsh1995** [samuelcolvin/pydantic#1259]
# Issue
Python 3.7 inheritance seems to be working as expected but getting some weird results with 3.6.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"` for 3.6:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path:/venv3.6/lib/python3.6/site-packages/pydantic
               python version: 3.6.9 (default, Sep 11 2019, 17:23:51)  [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)]
                     platform: Darwin-19.2.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"` for 3.7:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: /venv/lib/python3.7/site-packages/pydantic
               python version: 3.7.4 (default, Sep 16 2019, 17:52:53)  [Clang 10.0.1 (clang-1001.0.46.4)]
                     platform: Darwin-19.2.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

# Reproduction
```py
from pydantic import BaseModel
from typing import Union

class AuthCodeResponse(BaseModel):
    code: str

class UnvalidatedStatefulAuthCodeResponse(AuthCodeResponse):
    state: str


class AuthCodeResponses(BaseModel):
    response: Union[UnvalidatedStatefulAuthCodeResponse, AuthCodeResponse]

print(type(AuthCodeResponses(response=dict(state="abc", code="def")).response))
# Expected: <class '__main__.UnvalidatedStatefulAuthCodeResponse'>
# 3.7: <class '__main__.UnvalidatedStatefulAuthCodeResponse'>
# 3.6: <class '__main__.AuthCodeResponse'>
```
We can get 3.6 to work as expected by not having `UnvalidatedStatefulAuthCodeResponse` inherit from `AuthCodeResponse`:
```py
from pydantic import BaseModel
from typing import Union

class AuthCodeResponse(BaseModel):
    code: str

class UnvalidatedStatefulAuthCodeResponse(BaseModel):
    code: str
    state: str


class AuthCodeResponses(BaseModel):
    response: Union[UnvalidatedStatefulAuthCodeResponse, AuthCodeResponse]

print(type(AuthCodeResponses(response=dict(state="abc", code="def")).response))
# <class '__main__.UnvalidatedStatefulAuthCodeResponse'>
```
Seems like some issue with 3.6 and inheritance?

**Comment by samuelcolvin** [comment]
I suspect this is a change within python stdlib to how subclasses are handled within Unions.

Pydantic has some relative crude logic about parsing submodels - it converts them to dicts, then tries to validate.

https://github.com/samuelcolvin/pydantic/blob/0f948618bab7d36a7ee153f3ad02594b56554e74/pydantic/main.py#L566

here `UnvalidatedStatefulAuthCodeResponse` is valid as a `AuthCodeResponse`, hence the problem.

Solutions:
* what you have now
* stick to 3.7
* mark `AuthCodeResponse.config.extra = Extra.forbid` so that a `UnvalidatedStatefulAuthCodeResponse` is not valid as a `AuthCodeResponse`
* wait for v2 where I hope to modify how parsing/validation of sub-models works.

**Comment by felixfontein** [comment]
Another workaround is to introduce a base class `AuthCodeResponseBase` where both classes derive from, and which containst the common parts:
```.py
class AuthCodeResponseBase(BaseModel):
    code: str

class AuthCodeResponse(AuthCodeResponseBase):
    pass

class UnvalidatedStatefulAuthCodeResponse(AuthCodeResponseBase):
    state: str
```
With this, `Union[UnvalidatedStatefulAuthCodeResponse, AuthCodeResponse]` also works on Python 3.6.
