### ISSUE TITLE
why limit on number of digits for timedelta?

### ISSUE THREAD

**Issue by tlambert03** [samuelcolvin/pydantic#1261]
# Question
`timedelta` fields provided as `floats` throw an error during validation when there are more than 12 numbers after the decimal point:
```python
from pydantic import BaseModel

class Model(BaseModel):
    td: timedelta

m = Model(td=1.123456123456)  # fine
m = Model(td=1.1234561234567) # invalid duration format (type=value_error.duration)
```
I can see that's due to the way that the `standard_duration_re` is specified:
https://github.com/samuelcolvin/pydantic/blob/31cac4783b2cba2836e7bf2b4a593a3085930da6/pydantic/datetime_parse.py#L36-L44

I'm wondering why though?  It imposes the need for a prefiltering "precision check" when delivering numbers to a timedelta field.  Is it better that way for some reason?

**Comment by tlambert03** [comment]
relatedly... would you consider a PR that truncated the precision of `floats` during conversion to `str` in [`parse_duration`](https://github.com/samuelcolvin/pydantic/blob/31cac4783b2cba2836e7bf2b4a593a3085930da6/pydantic/datetime_parse.py#L214-L216)?  Or is the validation error in this case preferred to implicit truncation of precision

**Comment by NovaNekmit** [comment]
This is especially annoying when dealing with floating point point inaccuracies.

```
>>> print(3*0.1)
0.30000000000000004
>>> print(3/10)
0.3
>>> pydantic.datetime_parse.parse_duration(3*0.1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/datetime_parse.py", line 226, in pydantic.datetime_parse.parse_duration
pydantic.errors.DurationError: invalid duration format
>>> pydantic.datetime_parse.parse_duration(3/10)
datetime.timedelta(microseconds=300000)

```

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
