### ISSUE TITLE
"none is not an allowed value" for Hashable field

### ISSUE THREAD

**Issue by gsakkis** [samuelcolvin/pydantic#1262]
Although `None` is `Hashable`, it fails to validate below. Even stranger, it still fails with the same error if the field is explicitly annotated as `Optional[Hashable]`

```py
from collections.abc import Hashable
from typing import Optional
from pydantic.dataclasses import dataclass


class Config:
    arbitrary_types_allowed = True

@dataclass(config=Config)
class Model:
    v: Hashable
    # v: Optional[Hashable]

assert isinstance(None, Hashable)

Model(None)

# output:
#
#pydantic.error_wrappers.ValidationError: 1 validation error for Model
#v
#  none is not an allowed value (type=type_error.none.not_allowed)
```
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:

```
pydantic version: 1.4
pydantic compiled: True
python version: 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
platform: Linux-4.15.0-76-generic-x86_64-with-Ubuntu-18.04-bionic
optional deps. installed: ['typing-extensions']
```

**Comment by samuelcolvin** [comment]
Surely better to properly implement a check for the `Hashable` type?

**Comment by gsakkis** [comment]
You mean special-case `Hashable` instead of the general proper fix `isinstance(None, self.type_)`  in the PR? Why?

**Comment by samuelcolvin** [comment]
Yes, so we can more generally support `Hashable`

**Comment by gsakkis** [comment]
The PR effectively adds support for `Hashable`; it just so happens that we get for free a fix for any virtual superclasses of `None`, current or future ones, not just `Hashable`.
