### ISSUE TITLE
Optional fields & defaults for BaseModel vs @dataclass

### ISSUE THREAD

**Issue by gsakkis** [samuelcolvin/pydantic#1265]
I'd like a few clarifications about the `BaseModel` and `@dataclass` behaviour with respect to optional fields and default values, based on the following example:
```py
class Foo(BaseModel):
    w: Optional[int]
    x: Optional[int] = None
    y: int = None
    z: int = 'bad'

@dataclass
class Bar:
    w: Optional[int]
    x: Optional[int] = None
    y: int = None
    z: int = 'bad'


print(Foo())
print(Bar(None, z=-1))
print(Bar(None))

# output: 
# 
# w=None x=None y=None z='bad'
# Bar(w=None, x=None, y=None, z=-1)
# Traceback (most recent call last):
# ...
# pydantic.error_wrappers.ValidationError: 1 validation error for Bar
# z
#   value is not a valid integer (type=type_error.integer)
```
1. Are `Foo.w`, `Foo.x` and `Foo.y` three different spellings of the exact same thing, i.e. an optional nullable field? It appears so.
2. Similarly, `Bar.x` and `Bar.y` also appear identical optional nullable fields, but differ from `Bar.w` which is required (aside: the "required optional" fields mentioned in the docs sounds contradictory, perhaps change it to "required nullable").
3. The default value of `Foo.z` is not validated, unlike `Bar.z`; is this difference intentional? If the dataclass is indeed intended to be stricter, shouldn't `Bar.y` also be an error instead of coerced  implicitly to optional?

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.4
pydantic compiled: False
python version: 3.7.1 (default, Dec 14 2018, 19:46:24)  [GCC 7.3.0]
platform: Linux-4.4.0-173-generic-i686-with-debian-stretch-sid
optional deps. installed: ['typing-extensions']
```

**Comment by samuelcolvin** [comment]
1. Yes, they're currently equivalent, I want to make `w` required allow `None` in v2. The reason we weren't sure about making "Optional" fields required was precisely because of the confusing naming "required optional" fields sound weird, but then again `w` not being required is weird too, see #990.
2. (and 3.) dataclasses are fundamentally different from models because pydantic can't alter much of the way dataclasses are initialised, see #986
