### ISSUE TITLE
Failed to generate schema with typing.Pattern

### ISSUE THREAD

**Issue by Gatux** [samuelcolvin/pydantic#1269]
# Bug
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.4
pydantic compiled: True
python version: 3.8.2 (default, Feb 29 2020, 12:01:47)  [GCC 5.4.0 20160609]
platform: Linux-4.15.0-76-generic-x86_64-with-glibc2.17
optional deps. installed: []
```
Code snippet:
```py
from typing import Pattern
from pydantic import BaseModel

class Model(BaseModel):
    filter: Pattern

print(Model(filter="^regex$").schema_json())
```
Ouput:
```
[...]
  File "[...]/venv/lib/python3.8/site-packages/pydantic/schema.py", line 657, in field_singleton_schema
    if issubclass(field_type, Enum):
TypeError: issubclass() arg 1 must be a class
```

https://github.com/samuelcolvin/pydantic/blob/e4cd9d2c87b0e6f42366b617de6441f8cd561085/pydantic/schema.py#L657

`field_type` (`typing.Pattern`) is not a class. 😕 And there is no schema definition for this type.

What's the best way to deal with this?

For now, I'll use a custom class with `__modify_schema__` to get something like that:
```{"title": "Filter", "type": "string", "format": "regex"}```

Thanks for the help and thanks for this awesome package!

**Comment by samuelcolvin** [comment]
thanks for reporting, PR welcome to fix this.

**Comment by PrettyWood** [comment]
When a default value is set I see it working
```python
class Model(BaseModel):
    filter: Pattern = '^regex'
```
by just adding a check like
```python
if field_type is Pattern:  # Pattern is not a class
    f_schema['type'] = 'string'
    f_schema['pattern'] = field.default
    return f_schema, definitions, nested_models
```

Although it would be the exact same thing as
```python
class Model(BaseModel):
    filter: constr(regex='^regex')
```

But without a default value it would probably require some refactoring as the schema generation is based on the class itself and not the instance.
Am I missing something?
