### ISSUE TITLE
Constrained dict (condict)

### ISSUE THREAD

**Issue by and-semakin** [samuelcolvin/pydantic#1277]
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: /Users/andreisemakin/.local/share/virtualenvs/popapi-7C7w-VGz/lib/python3.7/site-packages/pydantic
               python version: 3.7.6 (default, Dec 30 2019, 19:38:26)  [Clang 11.0.0 (clang-1100.0.33.16)]
                     platform: Darwin-19.3.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Is there a way to create constrained dict, for example, I would like to reject empty dicts (i.e. require at least one key):

```py
from pydantic import condict, BaseModel, ValidationError
import pytest


NotEmptyDict = condict(key_type=str, value_type=int, min_items=1)


class KekRequest(BaseModel):
    value: NotEmptyDict


# basic tests
with pytest.raises(ValidationError):
    KekRequest.validate({"value": {}})

model = KekRequest.validate({"value": {"qwe": 1}})
assert model.value == {"qwe": 1}
```

**Comment by and-semakin** [comment]
Another use case for `condict` could be `condict(strict=True)`, which means "don't try to coerce arbitrary iterables to dictionary (as Python do), just require a dictionary/mapping here".

```python
from pydantic import BaseModel, condict, ValidationError
from typing import Dict


class Model1(BaseModel):
    """Non-strict dictionary required."""
    value: Dict[str, int]


class Model2(BaseModel):
    """Strict dictionary required."""
    value: condict(key_type=str, value_type=int, strict=True)


# it will convert empty string to empty dictionary
m1 = Model1.validate({"value": ""})
assert m1.value == {}

# because it works as built-in Python dict
assert dict('') == {}


# but strict dictionary will deny to accept anything else than a dictionary
with pytest.raises(ValidationError):
    Model2.validate({"value": ""})

# and only accept dictionaries
m2 = Model2.validate({"value": {}})
assert m2.value == {}
```

The question is should we accept another subclasses of `typing.Mapping` in such strict mode.

**Comment by dmontagu** [comment]
I think support for strictness would be a good addition (and even better as the default behavior); see my comment on #1268 for more detail. Tl;dr I think we should probably make the dict validator stricter by default in v2, and don't need to add a new type just to achieve that.

----

Regarding bounding the number of items, it seems infrequent enough of a request that it's probably easiest to just use a custom data type in your own code that is a subclass of `dict` and defines `__get_validators__`.

Something along the lines of:

```python
def is_dict(v: Any):
    assert isinstance(v, dict)
    return v

def is_nonempty(v: Any):
    assert v
    return v
    
class NonEmptyDict(Dict[KT, VT]):
    @classmethod
    def __get_validators__(cls):
        yield is_dict
        yield is_nonempty
```
(not tested).

**Comment by and-semakin** [comment]
Wow, thanks @dmontagu! Didn't expect that it would be so easy to implement.

**Comment by and-semakin** [comment]
@dmontagu, unfortunately, this approach doesn't work for dicts. Seems that `__get_validators__ ` is never called for mapping types.

**Comment by samuelcolvin** [comment]
best to use a standard validator:

```py
from typing import Dict
from pydantic import BaseModel, validator
from devtools import debug

class Foo(BaseModel):
    foo: Dict[str, int]

    @validator('foo')
    def check_foo(cls, v):
        assert len(v) < 5, 'too many elements'
        return v

debug(Foo(foo={'x': 5}))
debug(Foo(foo={f'{i}': i for i in range(10)}))
```

**Comment by augustebaum** [comment]
Hitting this use-case also. Same question as @HansBrende, why not have `condict` if there is `conlist`, `conint`, `confloat`...?

**Comment by nick-shapavalau** [comment]
@augustebaum thank you!
