### ISSUE TITLE
Default value is not validated when type annotation is defined

### ISSUE THREAD

**Issue by daniel110** [samuelcolvin/pydantic#1280]
Output of python -c "import pydantic.utils; print(pydantic.utils.version_info())":

```
pydantic version: 1.4
pydantic compiled: False
install path: D:\fun\venvs\advanced_python\Lib\site-packages\pydantic
python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
platform: Windows-10-10.0.18362-SP0
optional deps. installed: []
```

I have a question regarding unexpected behavior (in my opinion): **when a default value does not meet with the type annotation, a validation error is _not_ being raised.**

It is mentioned in the documentation that when a default value is set it determines the type annotation of the field. 
But, the guideline recommends to add a manual type annotation anyway: 

> "Therefore, we recommend adding type annotations to all fields, even when a default value would determine the type by itself to guarentee field order is preserved." [(link)](https://pydantic-docs.helpmanual.io/usage/models/#field-ordering)

When both type annotation and default value are used the default values is not validated, but a new value which is set should meet the manual type annotation.
See test example: (the test pass)
```
def test_default_vs_annotation(self):
        class ConfExample(pydantic.BaseModel):
            ids: List[int] = [1, 2, "a"]

        conf_ex = ConfExample()
        assert conf_ex.ids == [1, 2, "a"]

        with pytest.raises(pydantic.error_wrappers.ValidationError):
            """
            pydantic.error_wrappers.ValidationError: 1 validation error for ConfExample
            ids -> 2
              value is not a valid integer (type=type_error.integer)
            """
            ConfExample(**{"ids": [1, 2, "y"]})
```

I expected that the default value would be validated, whether it is on the class definition or only when an instance is being created and a new value is not supplied.

I could not find a test that contains such a mismatch, so I would be happy to hear your thoughts.

Thanks.

**Comment by samuelcolvin** [comment]
This is the intended behaviour, it's useful in many scenarios and improves performance.

You can however validate defaults, use [`Config.validate_all`](https://pydantic-docs.helpmanual.io/usage/model_config/).
