### ISSUE TITLE
defining model with csv instead of code

### ISSUE THREAD

**Issue by yeyeric** [samuelcolvin/pydantic#1284]
hello,

I'm a bit new to python, about 1.5 year of experience, and come with heavy excel experience before (don't blame me).

I'm working with fast api for a couple of months, and I'm setting my class thanks to pydantic.

However, it's a pain defining all class in models.py, and I was wondering if anyone had managed to do so with a proper csv ? That'd be so easier to manage, although not very technical maybe.

Was just a thought of the evening :)

Thanks

**Comment by samuelcolvin** [comment]
I doubt anyone has, I personally wouldn't use that approach.

You should be able to achieve it by reading a CSV file the using `create_model()`.
