### ISSUE TITLE
Support for JSON-Schema?

### ISSUE THREAD

**Issue by ben-davis** [samuelcolvin/pydantic#129]
I'm wondering if there's been any investigation into translating Pydantic models into json schemas? The use-case for us is simply to expose the schemas to users in our frontend. We're happy to build this ourselves, but just want to check if it's something that is seen as within the scope of the project.

**Comment by samuelcolvin** [comment]
Yes definitely, it's something I've been thinking about a fair bit recently.

In fact it's the same as #7. 

Probably easiest if I have a first crack and you give your opinion. 

AFAIK there's no standard for schema descriptions, but drf is probably the most mature solution.

**Comment by ben-davis** [comment]
Nice. What's the priority on this for you? I had a dig around the source and seems like it wouldn't be too difficult to get something working, essentially just recursively serialise each field base on their `type`.

Well it depends on if you're talking about API schemas or data schemas. DRF has core-api, but then the world most relies on OpenAPI. But then for JSON data, json-schema feels pretty standard. The problem is, API schemas necessarily have to have a data-schema as a subset, so there's a ton of 'standards' that all compete with each other.

Tbh I find the whole thing confusing. The main question for me is where the boundaries of these various tools lie and how Python's type annotations fit in with that. Like when does a type system become a data validator? If json-schema exporting is added to Pydantic, is it a method of translating Python type annotations into json-schema, or type annotations + pydantic validation logic? What's the reason why restricting valid values is beyond the scope of Python's typing? In my mind, Python's type annotations should be able to express everything Pydantic allows for, meaning Pydantic simply becomes a runtime version of mypy. Then there'd a be a separate tool that can translate the Python's type annotations into json-schema, or any other 'standard' people wish for.

Sorry, I didn't intend for this comment to go so awry! The reason I'm so drawn to Pydantic is that leveraging the built-in typing is for sure the right way in my mind.

**Comment by samuelcolvin** [comment]
Humm, it looks like core-api, OpenAPI and json-scheme are all pretty similar but not the same. To make it worse there seems to be http://json-schema.org/ and https://jsonschema.net/#/ are these the same or competing?

From a bit of research they all (except perhaps jsonschema.net) seem to get distracted by the philosophical end of things and  fail to give clear and simple documentation with examples.

For me the main advantage of using one of these proto-standards is the possibility that a (perhaps future) client could plug and play with pydantic with little or no modification - for example [react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form#form-initialization). But this would require work to change pydantic's error messages (which need work anyway) and would limit what types could could be used.

One question: what are the use cases for this? I can imagine:
* auto-generating user forms from the schema
* giving client developers documentation on what an API will and won't accept
* ??? all other cases I can think of either don't work in practice or fall into one of the above cases

I would suggest a common sense schema that is similar to all the above but doesn't treat any of them as gospel. Something like:

```js
{
  "type": "object",
  "title": "the object/document title",
  "description": "aka help text, more detail on what this object is",
  "properties": {
    "first_name": {
      "type": "string",
      "max_length": 255,
      "title": "First Name",
      "required": false  // defaults to true
    },
    "gender": {
      "type": "str",
      "title": "Gender",
      "choices": [
        "male",
        "female",
        "fluid"
      ],
      "default": "fluid"
    },
    "friends": {  // more complex types like List or Dict use sub-type
      "type": "list",
      "sub-type": "int"
    }
  }
}
```

We get the following fields on each property (or field):
* `type`: either `object`, `str`, `boolean`, `int`, `float`, `email`, `list`, `dict` - also perhaps user defined types. `object` is distinct from `dict` as object defines it's properties while dict just defines it's key and value types - think sub model vs `Dict[str, int]`
* `title` user friendly title for the property. defaults to the `key.title()`
* `description` or help text for the property, omitted if not provided.
* `choices` if a enum is used; which values are allowed - perhaps needs two forms `['male', 'Female']` and django-like `[['m', 'Male'], ['f', 'Female']]`
* `required` defaults to true if omitted
* `default` the default value for this field, might be used as the initial value in forms
* `max_length`, `min_length` used on `str` and perhaps `list` and `dict` fields
* `max`, `min` possibly used on int and float fields
* `properties` on `object` the sub properties.
* `sub-type` used on list and dict fields
* `key-type` used on dict fields
* `display-hint` eg. `<input type="text"` vs `<textarea` or radio buttons vs. select multiple.

The other question is how best to let users of pydantic provide all this information. Most similar libraries have the "field" class eg ."Field(int, title='...', description='...')` which makes this stuff easier but it more verbose and doesn't work well with static type analysis etc. Options:
* model docstings could be used for `description` and perhaps even `title` of objects
* easiest to use the `Config` class but it'll be a pain if all the information about a field/property is defined separately from the field itself.
* could use magic comments or similar but this will require custom validation, inspection of the ast and won't play nicely with translations.
* could have a second property after the field definition where all this stuff is defined:
```py
class Foo(BaseModel):
    bar: int
    __bar_info__ = Info(title='Bar', description='whatever')
```

Like most things it looks like doing it simply will be easily, doing it properly will not be so easy.

**Comment by samuelcolvin** [comment]
@Gr1N I want to work on this; before I begin do you have any objections/observations on my suggestion above.

@ben-davis is this something you're still interested in? Does my proposal above work for you?

I guess schema, errors and model objects should all share the same serialisation logic, see #133.

**Comment by Gr1N** [comment]
@samuelcolvin looks good for me, just one moment: it would be good to have any kind of internal/transitional/low-level format which can be used to convert to any representation like JSON Schema, AVRO, Protobuf, etc.

And I don't think that `Info` is a good name, because as I can see you want to include `default` and it's not an info.

**Comment by samuelcolvin** [comment]
I guess the best option would be something like

```py
class Foo(BaseModel):
    # as with normal pydantic the ellipsis indicates that the field is required, but here other stuff can be set 
    bar: int = ..., Info(title='Bar', description='whatever')
```

Then it's very clear what's going on.

**Comment by samuelcolvin** [comment]
Done. Further improvements discussed on #218.

**Comment by 164747** [comment]
I have pydantic records that I want to save in biq-query. That has turned out to be pretty cumbersome. Bigquery demands an avro-schema. There is the dataclasses-avroschema extension to dataclasses

https://marcosschroh.github.io/dataclasses-avroschema/

I wonder is there an easy way to generate an avro-schema to a pydantic model?

**Comment by danhje** [comment]
> I have pydantic records that I want to save in biq-query. That has turned out to be pretty cumbersome. Bigquery demands an avro-schema. There is the dataclasses-avroschema extension to dataclasses
> 
> https://marcosschroh.github.io/dataclasses-avroschema/
> 
> I wonder is there an easy way to generate an avro-schema to a pydantic model?

Have you found a solution for converting pydantic model to avro schema? We've had to write this conversion from scratch (happy to share our solution with you if you'd like), but we keep bumping into cases that aren't handled properly by our implementation. Would be nice to have a more general and polished solution for this.
