### ISSUE TITLE
schema_extra should be allowed to be a classmethod

### ISSUE THREAD

**Issue by laevilgenius** [samuelcolvin/pydantic#1305]
In my opinion, this check is unnecessarily restrictive:
https://github.com/samuelcolvin/pydantic/blob/938335c46f7e31da71e5c2a45eb3cf1ad51030b5/pydantic/schema.py#L470-L471
Also, it raises `TypeError` only for classmethods, but not for regular methods.

**Comment by samuelcolvin** [comment]
PR welcome to relax the check.
