### ISSUE TITLE
Provide both Cython / non-Cython build PyPi project?

### ISSUE THREAD

**Issue by littlebtc** [samuelcolvin/pydantic#1325]
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:

```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: (skipped)
               python version: 3.7.3 (default, Dec 13 2019, 19:58:14)  [Clang 11.0.0 (clang-1100.0.33.17)]
                     platform: Darwin-19.3.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

We are trying to use Pydantic in our website, currently using Django under AWS Lambda with Zappa. But the size of the compiled Cython binaries are considerably large, especially in the limited environment like serverless functions.

AWS had `~250MB` hard limit on the total function size even if unzipped, and Cython version of Pydantic will eat up 25MB (~10%) for it.

But after investigation, it is hard to tell the Pip, Pipenv or Poetry to stick with wheel without Cython manylinux wheels. Although we can still stick with the non-Cython version by assigning wheel URL and hack Zappa to use it, we have to manually update wheel URL.

Can this package use similar technique like `psycopg2` and `psycopg2-binary` to provide separate package with/without Cython, to make people with limited resources to install the package much more easier? Like `pydantic` and `pydantic-pure`.

**Comment by samuelcolvin** [comment]
Just install using the git URL.

Something like:

```
pip install git+git://github.com/samuelcolvin/pydantic.git@1.4
```

(On my phone so haven't tried it)

**Comment by samuelcolvin** [comment]
we already include both in pypi, [see here](https://pypi.org/project/pydantic/#files).

To install pydantic without binaries:

```
pip install --no-binary pydantic pydantic
```

**Comment by Zacharias030** [comment]
`pip install --no-binary pydantic pydantic`
doesn't work for me, but installing from git works.

The problem is that in the end of the installation some copying is missing, and the success message says
`successfully installed pydantic` (and then `pip list` doesn't have it), while a proper installation would show `successfully installed pydantic=<VERSION>`
