### ISSUE TITLE
Color string representation shouldn't always default to named

### ISSUE THREAD

**Issue by pawelad** [samuelcolvin/pydantic#1327]
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: True
                 install path: /root/.local/lib/python3.7/site-packages/pydantic
               python version: 3.7.6 (default, Feb 26 2020, 15:34:58)  [GCC 8.3.0]
                     platform: Linux-4.19.76-linuxkit-x86_64-with-debian-10.3
     optional deps. installed: []

```

---

Hi! This might be very subjective, but I'm dealing with this myself by extending your `Color` class and I love `pydantic` so I thought I might as well open up an issue, see if maintainers agree and offer my help if they do.

First of all, like I mention, I absolutely love `pydantic` and I was very pleasantly surprised that `pydantic.color.Color` exists. That said, I found the default string representation of it confusing:

```py
In[1]: pydantic.color import Color
In[2]: Color("#ffffff")
Out[2]: Color('white', rgb=(255, 255, 255))
In[3]: str(Color("#ffffff"))
Out[3]: 'white
In[4]: Color("#1e1e1e")
Out[4]: Color('#1e1e1e', rgb=(30, 30, 30))
In[5]: str(Color("#1e1e1e"))
Out[5]: '#1e1e1e'
```

I understand that in CSS `white` is the same as `#ffffff` (and `Color("#ffffff").as_named()` works great for that), but implicitly changing that when it comes to `str(Color("#ffffff"))` is very confusing to me.

Even more so when it comes to something like this (real world example):

```py
from typing import List

from pydantic import BaseModel
from pydantic.color import Color


class Colors(BaseModel):
  
    foo: Color = Color("#1e1e1e")
    bar: Color = Color("#ffffff")
    baz: List[Color] = [Color("#1e1e1e"), Color("#eb4755"), Color("#ffffff")]
```

Given that, `Colors().schema()` returns:

```
{
    "title": "Colors",
    "type": "object",
    "properties": {
        "foo": {"title": "Foo", "default": "#1e1e1e", "type": "string", "format": "color"},
        "bar": {"title": "Bar", "default": "white", "type": "string", "format": "color"},
        "baz": {
            "title": "Baz",
            "default": ["#1e1e1e", "#eb4755", "white"],
            "type": "array",
            "items": {"type": "string", "format": "color"},
        },
    },
}
```

The `"default": ["#1e1e1e", "#eb4755", "white"],` bit is what made my extend `Color` and change that behavior.

What I propose is:

```py
assert str(Color("#1e1e1e")) == "#1e1e1e"
assert str(Color("#ffffff")) == "#ffffff"
assert str(Color("white")) == "white"
```

Like I said at the beginning, this is a rather small thing, and I might me in the minority, but I thought I'll make my case anyway : -)
If the maintainers agree, I'd be happy to try and implement this in a PR.

**Comment by samuelcolvin** [comment]
Sorry for the slow reply.

I think the current solution is probably right, and I'm not keen to change it. I think the default output should be independent of how the value was entered.

Imagine a float field which parses a form input, you would expect the float (and therefore a string formatting of that float) to be independent of whether the user entered `'42'` or `'42.00'` or `' 42.00 '`. I think the same should apply by default for floats.

However since we knew people might want this we included the `.original` property of fields to make it possible to access the raw value entered:

https://github.com/samuelcolvin/pydantic/blob/aaec3c9c15581d2de31bcda0fbf096638386ee20/pydantic/color.py#L86-L90

You could either use that or create your own shallow sub-class of `Color` with 

```py
    def __str__(self) -> str:
        self.original
```

**Comment by pawelad** [comment]
Hey, no worries thanks for replying at all : -)

I get your point, but I'd argue that `42.100` -> `42.1` is not really the same as `#fff` -> `white`. Or maybe it is? Dunno : )

What bothers me the most is the mix between hex and named colors (`"default": ["#1e1e1e", "#eb4755", "white"]`), especially when calling `schema()` because I can't control wether `__str__` or `as_hex()` is called. What you be more open to changing that behaviour? Or maybe a `HexColor` subclass?

I actually can't extend your class because in my own code because of this (unless I'm missing something): https://github.com/samuelcolvin/pydantic/blob/960b24a5aab7ae0631bfbfbe0047b4d8600c6012/pydantic/json.py#L20-L40

**Comment by pawelad** [comment]
> I actually can't extend your class because in my own code because of this (unless I'm missing something)

Although I guess https://github.com/samuelcolvin/pydantic/pull/1291 would help with that, right?

**Comment by samuelcolvin** [comment]
Ye, you're right sorry, you'll need #1291 for a sub-class.

**Comment by pawelad** [comment]
> What bothers me the most is the mix between hex and named colors (`"default": ["#1e1e1e", "#eb4755", "white"]`) when calling `schema()` because I can't control wether `__str__` or `as_hex()` is called.

Would you be open to changing how `schema()` works or are you happy with the current behaviour?

**Comment by EssaAlshammri** [comment]
```
class ItemBase(BaseModel):
    name: str
    color: Color

    @validator("color")
    def color_as_hex(cls, v):
        return v.as_hex()
```

this will work and gives back what ever you chose in the validator
