### ISSUE TITLE
JSON serialzation

### ISSUE THREAD

**Issue by xunto** [samuelcolvin/pydantic#133]
How to properly turn pydantic schemas into json?

The problem is that the BaseModel.dict() method returns dict, it's okay but it doesn't convert some default types into string (datetime.date, Enum and etc.).

It seems there is no other way to translate pydantic object into dict and serialize those types which is strange as pydantic can deserialize them and even force specific format in some way (datetime_parse.date_re for example which is hardcoded and hardly changeable).

**Comment by samuelcolvin** [comment]
pydantic doesn't take care of serialisation because:
1. people do it in lots of different ways - for example you might know that your data doesn't contain any complex types and therefore want to use ujson or similar, or you might want to use a completely different serialisation protocol like msgpack.
2. it's very simple - use a custom encoder like [this](https://github.com/tutorcruncher/socket-server/blob/master/tcsocket/app/utils.py#L18) and `json.dumps(m.dict(), cls=MyEncoder)`

> datetime_parse.date_re for example which is hardcoded and hardly changeable

This is unrelated to this issue, if you have a request for a change and a suggestion of how it might work, please create a separate issue. Hint: it is changeable, just add your own validator.

**Comment by xunto** [comment]
@samuelcolvin thanks for an answer. I know about the way to change it with my own validator (as I reported some bug with it recently).

I'm just trying to understand why pydantic take care of serialization and doesn't take care of serialisation when your arguments applicable for both of them.

**Comment by samuelcolvin** [comment]
I guess we should add a `json()` method that serialises using a default and best effort encoder class but allows and optional argument of a different encoder.

**Comment by xunto** [comment]
@samuelcolvin yeah, sounds good.

**Comment by samuelcolvin** [comment]
great, PR welcome.

Otherwise, I'll work on it in a couple of weeks. The link about should be a good starting point, the only thing I can thing of to add would be enums.

**Comment by xunto** [comment]
@samuelcolvin I'm not sure that I'll have time for this but if I will, I would be happy to help.

**Comment by nandoflorestan** [comment]
-1.

In my opinion almost every other issue in the github tracker is more important than this (as of May 2018). Serialization depends on intended usage and it can be done independently of pydantic. Getting the other parts right is much more important and urgent.

**Comment by nandoflorestan** [comment]
By the way, the method should not be called "json()", unless it returns a string. Since it returns a dictionary, it should be called "to_dict()". JSON is another step after we have the dictionary.

**Comment by samuelcolvin** [comment]
Yes, this is what I was saying. 

We already have the `dict()` method which returns a dict.

The problem is that (quite correctly) `dict()` doesn't return a dict which can necessarily be serialised straight to a dict without a custom serialiser.

**Comment by xunto** [comment]
There are a lot of types that will be serialized in the same way from project to project. The point is that nobody wants to implement the same encoder every time and duplicate code.

And It's just strange that pydantic can decode string into date but can't encode date into string. It just doesn't make sense. As if you could read but not write. My opinion is that If you strongly against encoding for user, decoding should be removed too.

**Comment by dsully** [comment]
+1 to @xunto's reasoning here. Serialization that handles aliases would be extremely nice.

**Comment by Gr1N** [comment]
@samuelcolvin I have [simple project](https://github.com/Gr1N/json-ext-encoder) (code base mostly taken from Django plus added support for enums) with extended `JSONEncoder` which can be possible used to solve this issue. What do you think?

**Comment by samuelcolvin** [comment]
I think it would be simplest to keep this code inside harrier. Moreover, I disagree with some of django's decisions, eg. it's generally best to encode timedelta as seconds rather than `P1DT02H00M03.400000S`

**Comment by jasonkuhrt** [comment]
I would welcome a non-intrusive default in pydantic that allows `json.dumps(some_model)` to just work, without blocking customization. I'm new to Python so take my opinion with grain of salt.

**Comment by samuelcolvin** [comment]
It won't quite be `json.dumps(some_model)` it'll be more like `some_model.json()` or equivalently `json.dumps(some_model, cls=PydanticEncoder)`.

I'm going to work on this soon.

**Comment by xunto** [comment]
@samuelcolvin just noticed, cool! But what about Enums?

**Comment by samuelcolvin** [comment]
https://github.com/samuelcolvin/pydantic/blob/master/pydantic/json.py#L32

**Comment by xunto** [comment]
@samuelcolvin oh, sorry. I didn't noticed. Cool! Good job!

**Comment by viniciusd** [comment]
Thoughts on adding this to `dataclasses`?

**Comment by samuelcolvin** [comment]
pydantic enums are as close to vanilla standard library enums as possible. That's not going to change.

However I'd be keen on a bunch of utility functions for processing datacalsses, eg.:
* `dataclass_json()`
* `dataclass_schema()`
* etc.
