### ISSUE TITLE
Validation if a value was set

### ISSUE THREAD

**Issue by floschl** [samuelcolvin/pydantic#1335]
# Question
I would like to init a Model(BaseModel) with external data from a dict, and check during init if a field was given in the dict or the default value was taken.
I did not find a way, since all validator methods cannot access the actual instance of the object. Hence, checking self.__fields_set__ is not possible. Also the cls object of the validator does not contain the given fields.

e.g. in this case, I would like to throw a warning that the default id value 2 was taken.

Is this possible at all?

```py
from pydantic import BaseModel

class User(BaseModel):
    id: int = 2
    name = 'Jane Doe'

print(User(**{'name': 'John'}))
...
```

**Comment by floschl** [comment]
I can certainly add another method `warning_defaults(self...)`, which I call after instantiation:

```py
from pydantic import BaseModel, root_validator, validator

class User(BaseModel):
    id: int = 2
    name = 'Jane Doe'

    def warning_defaults(self):
        fields_not_set = [f for f in list(self.fields.keys()) if f not in self.__fields_set__]
        print('WARNING: the following params were not set, now taking defaults: {}'.format(','.join(fields_not_set)))


user = User(**{'name': 'John'})
user.warning_defaults()
```

So the questions is, if it is possible to call this method implicitely right after all fields are initialised?

**Comment by koxudaxi** [comment]
@floschl 
You can use `root_validator` with `pre=True` option
https://pydantic-docs.helpmanual.io/usage/validators/#root-validators

example:
```python
from pydantic import BaseModel, root_validator


class User(BaseModel):
    id: int = 2
    name = 'Jane Doe'

    @root_validator(pre=True)
    def warning_defaults(cls, values):
        fields_not_set = [f for f in cls.__fields__ if f not in values]
        print('WARNING: the following params were not set, now taking defaults: {}'.format(','.join(fields_not_set)))
        return values


User(**{'name': 'John'})
```
output
```
WARNING: the following params were not set, now taking defaults: id

```

Or, you should call `warning_defaults()` after run `super()._init__()` in `__init__`
```python
from pydantic import BaseModel


class User(BaseModel):
    id: int = 2
    name = 'Jane Doe'

    def warning_defaults(self):
        fields_not_set = [f for f in self.__fields__ if f not in self.__fields_set__]
        print('WARNING: the following params were not set, now taking defaults: {}'.format(','.join(fields_not_set)))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.warning_defaults()


User(**{'name': 'John'})

```

**Comment by floschl** [comment]
great, both solution worked. I took the first one, which is pretty short.
