### ISSUE TITLE
Add argument to require integer to be odd/even in pydantic.conint

### ISSUE THREAD

**Issue by ValentinCalomme** [samuelcolvin/pydantic#1337]
# Feature Request

             pydantic version: 1.4
            pydantic compiled: False
                 install path: D:\source\project\.venv\Lib\site-packages\pydantic
               python version: 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.18362-SP0
     optional deps. installed: ['typing-extensions']
...

Currently, it is possible to add multiple constraints to an integer using `pydantic.conint`, namely:

- `strict`: whether or not the integer has to be a strict integer
- `gt`: integer must be greater than some value
- `ge`: integer must be greater than or equal to some value
- `lt`: integer must be smaller than some value
- `le`: integer must be smaller than or equal to some value
- `multiple_of`: integer must be a multiple of

It would be great if there were an additional boolean option such as `odd` or `even`. For instance:

```py
import pydantic

class SomeModel(pydantic.BaseModel):
    odd_integer: pydantic.conint(odd=True)

good_model = SomeModel(odd_integer=7)

bad_model = SomeModel(odd_integer=2)
>>> ValidationError: 1 validation error for SomeModel
odd_integer
  ensure this value is odd of 2 (type=value_error.number.not_odd; odd=True)
```

If `odd` is set to `True`, it could be the same as setting `multiple_of=2`, but for odd numbers, new validation should be written.

**Comment by samuelcolvin** [comment]
I think this is not a common enough problem to warrant a new argument, you can either:
* use a validator on the model to enforce this
* or create your own custom type to enforce this similar to `conint` or `ConstrainedInt` (the class created by `conint()`
