### ISSUE TITLE
Version 1.5 release - what needs doing?

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#1341]
I want to get version 1.5 released fairly soon.

I guess in roughly a week, but that's not a deadline, more an emotional feeling.

I'll merge all PRs which are ready in that time.

Is there anything else (either PRs or issues) that anyone considers urgent?

**Comment by StephenBrown2** [comment]
Only https://github.com/samuelcolvin/pydantic/pull/1291, but I'm biased.

**Comment by johnanthonyowens** [comment]
Another vote for #1291. Specifically would like to be able to subclass UUID.

**Comment by hellocoldworld** [comment]
Hello @samuelcolvin, will #1192 be fixed in this version?

**Comment by samuelcolvin** [comment]
> Hello @samuelcolvin, will #1192 be fixed in this version?

Yes, provided it is indeed resolved by #1204, please confirm and let me know.

**Comment by hellocoldworld** [comment]
> Yes, provided it is indeed resolved by #1204, please confirm and let me know.
Indeed,mypy runs with success in my projects. Thank you.

**Comment by kittipatv** [comment]
I hope to get https://github.com/samuelcolvin/pydantic/pull/1367 merged in this release. It resolves https://github.com/samuelcolvin/pydantic/issues/1366

**Comment by glarrain** [comment]
Hi @samuelcolvin. Do you think you could release 1.5 with the PRs that are already merged?

Great work by the way!

**Comment by samuelcolvin** [comment]
Hi everyone, I'm so sorry this release has been delayed. I'll try and get it done this week.

I got asked to build a web-app to track ventilators in a London hospital coping with corona virus. As you can imagine, I've dropped everything else to get that done - the app was being used in the hospital 36 hours after I started building it. While the initial thing has been hacked together, there's a lot more I can do to to make it more usable, and usable in multiple hospitals - hence the further delay.

All that said, I know others are waiting on a new release of pydantic, so I will do it soon. Sorry again for the delay.

**Comment by StephenBrown2** [comment]
COVID trumps schema. Do the needful!

**Comment by samuelcolvin** [comment]
I believe this is ready except for #1341, @StephenBrown2 should now be able to work on that as I've merged the JSON benchmarks.

@StephenBrown2 I'm sorry you've had to wait so long to get this fixed. In the interests of getting this release out asap, I might work on your PR tomorrow or friday if you haven't had time.

**Comment by samuelcolvin** [comment]
*"Done.**

Thank you all for being so patient.

**Comment by StephenBrown2** [comment]
Thank you! I'm super excited to be a part of it.

**Comment by bellomatt** [comment]
@samuelcolvin salute to the author!
