### ISSUE TITLE
Issue with dynamic defaults

### ISSUE THREAD

**Issue by didimelli** [samuelcolvin/pydantic#1346]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: True
                 install path: /mnt/c/Users/davide.melli/development/envs/alerting-agent/lib/python3.7/site-packages/pydantic
               python version: 3.7.5 (default, Nov  7 2019, 10:50:52)  [GCC 8.3.0]
                     platform: Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-18.04-bionic
     optional deps. installed: ['devtools']
```

Hi,

thanks for this really great library.

I found an issue while working with a class that had a couple of dynamic defaults.

```python
class Fault(BaseModel):
    
    unique_key: int = int(time())
    when_issued: datetime = str(datetime.utcnow())

# then i instantiated the class
a = Fault()
a.when_issued
# '2020-03-27 16:33:45.765013'
a.unique_key
# 1585326825
id(a)
# 140183774241168

# after some time...
b = Fault()
b.when_issued
# '2020-03-27 16:33:45.765013'
b.unique_key
# 1585326825
id(b)
# 140183774260512

# after some time...
c = Fault()
c.when_issued
# '2020-03-27 16:33:45.765013'
c.unique_key
# 1585326825
id(c)
# 140183774445072
```
So the objects are really different, since their `id`s are different.

I would have expected that everytime the class is instantiated, the attributes are computed.

I do not understand if this is a feature or a bug.

In this application i could just pass the attributes when instantiating the class
```python
a = Fault(when_issued=datetime.utcnow(), unique_key=int(time()))
```
so no big deal, but i would like to understand more about this.

Can anyone help me??

(again, really really great library, thanks!!!)

**Comment by samuelcolvin** [comment]
There are two issues here:
1. The defaults you've setup are not dynamic, `time()` and `utcnow()` are evaluated once when the model is created. Creating the default dynamically is possible now with validators, but will be much simpler once v1.5 is released when `default_factory` will be added, see #1210.
2. `id(model)` is different each time because you have different instances of the model, this is the case with any python classes:

```py
from datetime import datetime

dt1 = datetime(2020, 1, 1)
dt2 = datetime(2020, 1, 1)

dt1 == dt2
True

dt1 is dt2
False

id(dt1)
4460319824

id(dt2)
4460524624
```
