### ISSUE TITLE
Use Validate arguments in custom types validate methods

### ISSUE THREAD

**Issue by j-walker23** [samuelcolvin/pydantic#1347]
First I want to say, you guys are freaking amazing. This lib is one of the best I discovered in years since sqlalchemy itself. 
Coming from `attrs`, the way you guys made all the exporting logic generators is pure genius. So thanks for this, I'm loving moving my first large feature from `attrs` in the hopes of benifiting from the benchmark speeds!

I searched through all open and closed and didn't find anything. Which makes me think its just a current lack of knowledge since I'm just getting started with `pydantic`.

# Question
Ok, my question is pretty simple. 

Is it possible to set [validator arguments like pre](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/class_validators.py#L19) on custom types?

I get `pydantic` isn't a validation library, so no biggie if not. It just seems so close as is, so i figured there is probably a way.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: /Users/john/.virtualenvs/web-aKL4etZ6/lib/python3.7/site-packages/pydantic
               python version: 3.7.4 (default, Oct 12 2019, 19:06:48)  [Clang 11.0.0 (clang-1100.0.33.8)]
                     platform: Darwin-19.3.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
import re
from typing import Type

from pydantic import BaseModel, ConstrainedStr


class NonEmptyStr(ConstrainedStr):
  """"""

  @classmethod
  def validate(cls, v):
    v = super().validate(v) or None
    return v


def nonempty(
  *,
  strip_whitespace: bool = False,
  strict: bool = False,
  min_length: int = None,
  max_length: int = None,
  curtail_length: int = None,
  regex: str = None,
) -> Type[str]:
  # use kwargs then define conf in a dict to aid with IDE type hinting
  namespace = dict(
    strip_whitespace=strip_whitespace,
    strict=strict,
    min_length=min_length,
    max_length=max_length,
    curtail_length=curtail_length,
    regex=regex and re.compile(regex),
  )
  # noinspection PyTypeChecker
  return type('NonEmptyStrValue', (NonEmptyStr,), namespace)


class TestModel(BaseModel):
  """"""
  phone_type: nonempty(curtail_length=1) = None

  # It works when this is included with the `pre`.
  # But the type NonEmptyStr does the same logic, 
  # so if it could run like `pre` is on.
  # It would save me a bunch of duplication.
 
  # @validator("phone_type", pre=True)
  # def _null_strings(cls, v):
  #   return v or None


c = TestModel(
  phone_type='',
)

```

**Comment by samuelcolvin** [comment]
Yes, but not quite the same way. Custom types get their validators from the functions yielded from `__get_validators__`.

See the definition of `__get_validators__` for `ConstrainedStr`:

https://github.com/samuelcolvin/pydantic/blob/aaec3c9c15581d2de31bcda0fbf096638386ee20/pydantic/types.py#L167-L171

If you want to get your `validate` class method run before other validators, override `__get_validators__` and change the order functions are yielded.

Hope that solves your problem, if not feel free to ask for more info or clarify your question.
