### ISSUE TITLE
Calling `copy` doesn't run any validation

### ISSUE THREAD

**Issue by idmitrievsky** [samuelcolvin/pydantic#1351]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: /Users/ivan/.pyenv/versions/3.7.4/envs/warpx/lib/python3.7/site-packages/pydantic
               python version: 3.7.4 (default, Oct 17 2019, 21:19:42)  [Clang 10.0.1 (clang-1001.0.46.4)]
                     platform: Darwin-19.3.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
import pydantic

class CustomField:
    def __init__(self, value):
        self.value = value

class Model(pydantic.BaseModel):
    inner: CustomField
    
    @pydantic.validator("inner", pre=True)
    def inner_is_custom(cls, value):
        if isinstance(value, int):
            value = CustomField(value)
        return value
    
    class Config:
        arbitrary_types_allowed = True

try:
    Model(inner="string")
except pydantic.ValidationError:
    pass
instance = Model(inner=0)  # Model(inner=<__main__.CustomField object at 0x10a6e1390>)
incomplete_instance = instance.copy(update={"inner": 0}). # Model(inner=0)
invalid_instance = instance.copy(update={"inner": "string"})  # Model(inner='string')
```

As you can see, copy doesn't run any validation (type or custom). Is this the intended behaviour?

**Comment by Kuluso97** [comment]
After looking at the source code, I found that the "copy" method does not include the  "validate_model" routine as the __init__ does, but I think the behavior is reasonable, since you also can change the field directly after you instantiate the model object. The validation part only happens at the time you first create the it.

**Comment by samuelcolvin** [comment]
This is the intended behaviour, not a bug.

**Comment by idmitrievsky** [comment]
This seems like a really easy way to create invalid instances. Would it cost too much performance-wise to add a parameter like this?
```py
class Config:
    validate_on_copy = True
```

**Comment by samuelcolvin** [comment]
Create a new model, `copy` is for fast relocation of a model.

> This seems like a really easy way to create invalid instances.

If you're writing python, you're used to the idea that there's no hand rail to stop you doing stuff wrong, this is no different.

**Comment by idmitrievsky** [comment]
All right, what is the best to create a new instance replacing just one field? This seems very convoluted:

```py
model = Model(x=1, y=2, z=3)
Model(**{**dict(model),  "x": 2})
```

**Comment by StephenBrown2** [comment]
Perhaps
```py
model = Model(x=1, y=2, z=3)
other = model.copy(deep=True)
other.x = 4
```
resulting in:
```py
model
Model(x=1, y=2, z=3)

other
Model(x=4, y=2, z=3)
```

**Comment by idmitrievsky** [comment]
Yes, this is certainly an option in general, but the models I'm woking with right now have `allow_mutation = False`, so I unfortunately can't do that.

**Comment by StephenBrown2** [comment]
It doesn't help immediately, but in Python 3.9, you'll be able to use the slightly less convoluted syntax for updating dicts with `|` from [PEP-584](https://www.python.org/dev/peps/pep-0584/):

```py
❯ ipython
Python 3.9.0a4 (default, Apr  2 2020, 09:44:50)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pydantic import BaseModel

In [2]: class Model(BaseModel):
   ...:     x: int
   ...:     y: int
   ...:     z: int
   ...:     class Config:
   ...:         allow_mutation = False
   ...:

In [3]: model = Model(x=1, y=2, z=3)

In [4]: model
Out[4]: Model(x=1, y=2, z=3)

In [5]: other = Model(**(model.dict() | {"x":4}))

In [6]: other
Out[6]: Model(x=4, y=2, z=3)
```

**Comment by gwerbin** [comment]
> Create a new model, `copy` is for fast relocation of a model.
> 
> > This seems like a really easy way to create invalid instances.
> 
> If you're writing python, you're used to the idea that there's no hand rail to stop you doing stuff wrong, this is no different.

Does Pydantic v2 have any additional functionality that would help here, or is the only option to serialize to dict and then create a new model?

It's not always the case that models can be cleanly round-tripped with `dict()` despite everyone's best efforts and intentions, in which case the proposed workaround here could incur a lot of messy boilerplate code. Thus I'd encourage a softer mindset here. It's not necessarily that people want Pydantic to baby them, it's that they would appreciate if Pydantic made it easier to carry out this task, "making easy things easy" so to speak.
