### ISSUE TITLE
Can Field been used as function default argument value?

### ISSUE THREAD

**Issue by xbanke** [samuelcolvin/pydantic#1359]
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5a1
            pydantic compiled: True
                 install path: /home/xxx/.conda/envs/xxx/lib/python3.7/site-packages/pydantic
               python version: 3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0]
                     platform: Linux-4.18.0-80.el8.x86_64-x86_64-with-centos-8.0.1905-Core
     optional deps. installed: ['typing-extensions', 'email-validator']
```
Hi, I am trying the function decorator validate_arguments. Is it possible use Field as the default argument value like this?
```py
from datetime import datetime
from pydantic import validate_arguments, Field

@validate_arguments
def foo(dt: datetime = Field(default_factory=datetime.now)):
    print(dt)

```

**Comment by samuelcolvin** [comment]
This is not currently possible. It won't be added immediately, but I'd definitely consider adding something like this in future.

The way I had previously thought it would work, would be to add a model as an argument to `validate_arguments`, so it would be something like:

```py
from datetime import datetime
from pydantic import BaseModel, validate_arguments, Field

class FooModel(BaseModel):
    dt: datetime = Field(default_factory=datetime.now)

@validate_arguments(model=FooModel)
def foo(dt: datetime):
    print(dt)
```
Then `validate_arguments` is just checking that `FooModel` matches the arguments of `foo()`.

Your `Field` approach would be slightly shorter, but might upset mypy. I'd be open to considering both.

**Comment by xbanke** [comment]
OK, thanks. I will keep this issue open if necessary.

**Comment by thomascobb** [comment]
I didn't even realise that Field wasn't supported in `validate_arguments` (didn't read the docs properly), so I didn't go looking for an issue until I tried to use it for a default argument. I've submitted a PR that fixes this particular case and doesn't break any of the other tests, but I've probably missed something so I'd welcome someone else's opinion on this.

Also, mypy seems happy with this, it doesn't complain about the default value, and if you pass a value of a different type it will catch it

**Comment by thomascobb** [comment]
For reference, the way I am using this at the moment:

```python
class Line(BaseModel):
    key: Any = Field(..., description="An identifier for what to move")
    start: float = Field(..., description="Centre point of the first point of the line")
    stop: float = Field(..., description="Centre point of the last point of the line")
    num: int = Field(..., ge=1, description="Number of points to produce")

    @classmethod
    @validate_arguments
    def bounded(
        cls,
        key=key,
        lower: float = Field(..., description="Lower bound of the first point of the line"),
        upper: float = Field(..., description="Upper bound of the last point of the line"),
        num: int = num,
    ):
        half_step = (upper - lower) / num / 2
        return cls(key=key, start=lower+half_step, stop=upper-half_step, num=num)

    ...
```

I then use the Field info to make a JSON schema of the classes, and create a GraphQL query of both class constructors and alternative classmethod constructors

The re-use of the descriptions from Field definitions is a useful pattern
