### ISSUE TITLE
How to avoid IDE typecheck warnings?

### ISSUE THREAD

**Issue by Thoufak** [samuelcolvin/pydantic#1363]
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: /Users/ss/Desktop/RocketJoiner dev/src/venv/lib/python3.6/site-packages/pydantic
               python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
                     platform: Darwin-18.5.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Is there any nice way to avoid typecheck warnings when passing a plain python type to the field declared as some special pydantic type? For example, when passing **int** to the field of type **StrictInt**.

This is the warning I get in PyCharm (2019.3.4):
![image](https://user-images.githubusercontent.com/40132582/78397700-5960a080-75fa-11ea-9756-6b26715d3349.png)

Please note that I have installed the pydantic plugin (0.0.30) for PyCharm, but it doesn't seem to handle this issue.

**Comment by samuelcolvin** [comment]
Please search before creating issues.

https://pydantic-docs.helpmanual.io/pycharm_plugin/

**Comment by Thoufak** [comment]
I have already installed the pydantic plugin (0.0.30) for PyCharm, and it works. However, it doesn't seem to handle the issue I described. What can I do to find out why?

**Comment by samuelcolvin** [comment]
Please look at the issue tracker for that repo, there is an issue on the problem.

This is not a help a service for those who can't be bothered to research themselves.

The problem is that it's not easy to check that an `int` is valid as a `StrictInt` in a general way.

**Comment by Thoufak** [comment]
Thank you
