### ISSUE TITLE
How to reuse a model in a way that only the field constraint is changed?

### ISSUE THREAD

**Issue by ka-zo** [samuelcolvin/pydantic#1365]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.3
            pydantic compiled: False
                 install path: D:\<my path>\FastAPI\venv\Lib\site-packages\pydantic
               python version: 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows 10 <exact type is deleted>
     optional deps. installed: ['email-validator']
```

My question is about reusing a model multiple times in a way, that the constraint on a field in the model is the only thing that changes.

Example model:
```
from pydantic import BaseModel, Field

class PercentileValueIn(BaseModel):
    unit: PercentileUnit = Field(...)
    value: float = Field(
        ...,
        description="Value of the percentile.",
        ge=3,
        le=97,
    )
```
`PercentileUnit` is another model, but it is not important here, it could also be a string. The most important part is the `value` field, which is a float and must be between 3 and 97. Now my question is that I would like to reuse this exact model a second time and the only difference would be that the value must be between 5 and 95. How can I do it, without redefining the complete class again with different constraints on the `value` field?

Thank you for your help in advance!

**Comment by samuelcolvin** [comment]
Best option is to create a new model sub-classing `PercentileValueIn`, but redefining `value`. If you're worried about duplicating `description`, set up a global `percentile_description` field and use that to populate `description` in both cases.

**Comment by ka-zo** [comment]
Thanks a lot, this was also my idea, but I wanted to know, if there is somehow a more pydantic way to do it.

Have a nice weekend!

**Comment by ghost** [comment]
I've wrote a library which can do arbitrary manipulation of models to create variants [pydantic-variants](https://pypi.org/project/pydantic-variants/)
can also update any field constraint to a new value in a variant of the base model.
I decided to write it after dealing with annying code duplication for models which share most of their content.
