### ISSUE TITLE
BaseSettings can't read from .env file

### ISSUE THREAD

**Issue by fullc0ntr0l** [samuelcolvin/pydantic#1368]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.3
            pydantic compiled: True
                 install path: /home/xxx/playground/fastapi/.venv/lib/python3.6/site-packages/pydantic
               python version: 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
                     platform: Linux-5.3.0-7642-generic-x86_64-with-Ubuntu-18.04-bionic
     optional deps. installed: ['email-validator']
```

The example is from here https://github.com/samuelcolvin/pydantic/pull/1011 and still don't work. Documentation don't help also.

Note that I removed default value for `Settings.foo`

**.env**

```
foo=baz
```

**settings.py**

```py
from pydantic import BaseSettings


class Settings(BaseSettings):
    foo: str = 'bar'

    class Config:
        env_file = ".env"


settings = Settings()
```

**Exception**

```
In [1]: from settings import settings
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-1-89c4f5117928> in <module>
----> 1 from settings import settings

~/playground/fastapi/settings.py in <module>
      9 
     10 
---> 11 settings = Settings()

~/playground/fastapi/.venv/lib/python3.6/site-packages/pydantic/env_settings.cpython-36m-x86_64-linux-gnu.so in pydantic.env_settings.BaseSettings.__init__()

~/playground/fastapi/.venv/lib/python3.6/site-packages/pydantic/main.cpython-36m-x86_64-linux-gnu.so in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for Settings
foo
  field required (type=value_error.missing)

In [2]: 
```

If I `load_dotenv()` manually - it works:

```
In [2]: from dotenv import load_dotenv

In [3]: load_dotenv()
Out[3]: True

In [4]: from settings import settings

In [5]: settings
Out[5]: Settings(foo='baz')

In [6]: 
```

**Comment by samuelcolvin** [comment]
works fine for me.

`foo` is not a required field, so you're error message works fine.

Try using pydantic v1.4 and check your setup.

**Comment by Frank5000** [comment]
Getting the same issue with v1.6. Shouldn't this be able to work without needing to call `load_dotenv()`?

**Comment by HenryDashwood** [comment]
Just adding my own experience with Pydantic 1.6.1...
```python
from pydantic import BaseSettings
from dotenv import load_dotenv
from pathlib import Path
load_dotenv(dotenv_path=Path("~/.env"))


class AppSettings(BaseSettings):
    es: str

    class Config:
        env_file = "~/.env"


settings = AppSettings()
```
...results in this error:
```
Traceback (most recent call last):
  File "settings.py", line 14, in <module>
    settings = AppSettings()
  File "pydantic/env_settings.py", line 33, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 346, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AppSettings
es
  field required (type=value_error.missing)
```

**Comment by PrettyWood** [comment]
@HenryDashwood The issue here is that you use `~/.env`, which is not directly resolved by `pathlib.Path`.
You could change it to

```python
   class Config:
        env_file = os.path.expanduser('~/.env')
```

Maybe we could add `os.path.expanduser` directly in the code when `env_path` is created

**Comment by HenryDashwood** [comment]
Ah that's great. Thanks for that!

**Comment by samuelcolvin** [comment]
#1804 is merge and I can't produce this.

Closing this issue, if anyone else is having trouble and can explain the issue, please create a new issue.

**Comment by lvar** [comment]
Same problem here...

`

       db_url="postgres" # .env file
       
       class Settings(BaseSettings):
           db_url: str

           class Config:
              env_file = ".env"


       settings = Settings()

      
      @lru_cache()
      def get_settings():
         return {
            "db_url": settings.db_url,
       }
`
Getting error -> **pydantic.error_wrappers.ValidationError: 1 validation error for Settings db_url field required (type=value_error.missing)**

**Comment by tuxsisir** [comment]
Make sure that to read from ".env"

**Comment by orihomie** [comment]
Can confirm, for me it cannot resolve nor absolute, nor relative paths to load .env file

**Comment by orihomie** [comment]
It worked for me only with load_dotenv(), so can confirm this is not working nor with relative nor with absolute paths or I'm doing something wrong

**Comment by andreyrusanov** [comment]
@orihomie  I had the same issue because I had nested settings classes. To address the issue, I had to add .env file configuration explicitly in each class.

**Comment by atif1001** [comment]
Same here, does not work for me.

I have a `config.py` file with content:
`
class Settings(BaseSettings):
    app_name: str = 'FastAPI Template'
    PORT: int
    admin_email: Optional[str]

    class Config:
        env_file = ".env"
`

.env file is in the same directory as this `config.py` file.

I get the following error:
`
python app/main.py
Traceback (most recent call last):
  File "app/main.py", line 5, in <module>
    from api.apiv1 import router_api_v1
  File "/Users/aalam/Dropbox/code/fastApi/fastApi-template/app/api/apiv1.py", line 5, in <module>
    from api.demo_feature_1.v1.main import router as router_v1_demo_feature_1
  File "/Users/aalam/Dropbox/code/fastApi/fastApi-template/app/api/demo_feature_1/v1/main.py", line 11, in <module>
    config = get_settings()
  File "/Users/aalam/Dropbox/code/fastApi/fastApi-template/app/config.py", line 22, in get_settings
    return Settings()
  File "pydantic/env_settings.py", line 34, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
PORT
  field required (type=value_error.missing)
make: *** [start] Error 1
`

**Comment by samuelcolvin** [comment]
This is very likely because your `.env` is not in the current working directory.

From the docs:

> either absolute or relative to the current working directory.

E.g. `.env` being in the same directory as `config.py` doesn't matter.

We should make this notice more obvious in the docs to stop all these questions.

That said, it is already in the docs, please try to read them before posting questions on closed issues.

**Comment by tomateit** [comment]
Hi!

Either I do not understand the concept of current directory or something completely unexpected keeps happening.

To better understand the cause of exceptions, I've created the minimal working example with the following project structure:
```
myapp/
    settings.py
.env
app.py
```

where in the `settings.py` I have the following code:
```
from pydantic import BaseSettings
from pathlib import Path
import os
env_location = Path("./.env").resolve()
print(env_location)
print(Path(os.curdir).resolve())
print("File exists", env_location.exists())

class Settings(BaseSettings):
    VAR1: str
    VAR2: str
    
    class Config:
        case_sensitive = True
        _env_file=env_location,
        _env_file_encoding="utf-8"

settings = Settings()
```

which is then imported in `app.py` , which I run with python `app.py`.

The output is:
```
/research_pydantic_settings/.env
/research_pydantic_settings
File exists True
Traceback (most recent call last):
pydantic.error_wrappers.ValidationError: 2 validation errors for Settings
VAR1
  field required (type=value_error.missing)
VAR2
  field required (type=value_error.missing)
```

The docs says _"In either case, the value ... can be any valid path or filename, either absolute or relative to the current working directory."_ I tried both. No effect. If I do print the contents of .env file in settings.py script, everything works fine.

**Comment by OpetherMB** [comment]
IT works only if i add .env in the same directory as config.py :  

``` python
from dotenv import load_dotenv
load_dotenv()

class Settings(BaseSettings):
    API_V1_STR: str
    class Config:
        env_file = ".env"
```

**Comment by andersonmolter** [comment]
Experiencing the same issue that @tomateit experienced. 

`
from typing import List
from dotenv import load_dotenv

from pydantic import BaseModel

load_dotenv() 

class appsettings(BaseModel):
    client_id: str
    client_secret: str
    
    class Config:
        env_file = ".env"
`

This is my settings file but get the following when running. I have a .env in both the root of the project, the model's folder where appsettings.py is, and in the folder in which the router is making this call from. I am able to print out the contents of the .env file and the path of the working directory just to confirm that these secrets are accessible from this python class. 

`pydantic.error_wrappers.ValidationError: 2 validation errors for appsettings
client_id
  field required (type=value_error.missing)
client_secret
  field required (type=value_error.missing)
`

**Comment by samuelcolvin** [comment]
`.env` definitely works, I'll need more information than this to help.

Maybe the `.env` file is in the wrong place?

**Comment by andersonmolter** [comment]
```
myapp/
    settings.py
.env
app.py
``` 
My file structure is like the one above.

**Comment by omerdotdev** [comment]
Observation:

`set = DataBaseSetting(_env_file=os.path.join(os.getcwd(), '.env'))`

works fine while I am running through `python configs/db_config.py` 

And I have `working_dir` different than `config.py` file 




> uvicorn main:app --reload

This might fix in context of Fast API imo.

**Comment by jscheel** [comment]
If you are using py-dotenv, you can use `find_dotenv` to locate your file:

```
from dotenv import find_dotenv
from pydantic import BaseSettings

class Settings(BaseSettings):
    ...

    class Config:
        env_file = find_dotenv(".env")
        env_file_encoding = "utf-8"
```

**Comment by Bncer** [comment]
Hi!
In my case I used clear config.py with

```
from pydantic import BaseSettings

class Settings(BaseSettings):
    
    class Config:
        env_file = ".env"
        env_file_encoding = 'utf-8'
```        
installing pydantic with  dotenv `pip install pydantic[dotenv]`

**Comment by Faizolam** [comment]
here how i solved this issue

```
import os
from pydantic_settings import BaseSettings, SettingsConfigDict

DOTENV = os.path.join(os.path.dirname(__file__), ".env")

class Settings(BaseSettings):
    DATABASE_HOSTNAME:str
    DATABASE_PORT:str
    DATABASE_PASSWORD:str
    DATABASE_NAME:str
    DATABASE_USERNAME:str
    SECRET_KEY:str
    ALGORITHM:str
    ACCESS_TOKEN_EXPIRE_MINUTES:int

    model_config = SettingsConfigDict(env_file=DOTENV)

settings = Settings()
```

`__file__`: Represents the full path of the current Python script or module.
`os.path.dirname(__file__)`: Extracts the directory path from the full path obtained from `__file__`.
`os.path.join()`: Combines the directory path obtained above with the filename ".env" to construct a complete file path.

So, the combination of `os.path.join(os.path.dirname(__file__), ".env")` is used to dynamically create the full path to a file named `".env"` relative to the directory containing the current script or module. This is commonly used to construct file paths relative to the location of the script.

[Source, where I found it.](https://stackoverflow.com/questions/76674272/pydantic-basesettings-cant-find-env-when-running-commands-from-different-places)

**Comment by HurmakR** [comment]
```
    class Config:
        env_file = os.path.join(os.path.dirname(__file__), '..', '..', '.env') 
```
Use '..' for each directory above
In this case, .env is located two directories above.

**Comment by iamciro** [comment]
Hi! 

It looks like a path-related issue. I was having the same problem, and with the suggestion of @HurmakR it worked. 

I think it should be mentioned in the Docs we have to use the OS lib to avoid any path issue like the ones we are facing here, or otherwise fix it.
