### ISSUE TITLE
[BUG] Validator isn't called with inheritance

### ISSUE THREAD

**Issue by xunto** [samuelcolvin/pydantic#137]
Code:
```python
from typing import Optional

import pydantic


class A(pydantic.BaseModel):
    login: str
    password: str


class ClientA(A):
    password: Optional[str] = None

    @pydantic.validator("login")
    def not_called(self):
        return "test"

    @pydantic.validator("password")
    def clean_up(self):
        return None


print(
    ClientA(
        login="login",
        password="password"
    )
)
```
Output:
```python
ClientA login='login' password=None
```

As you can see ```ClientA:not_called``` validator is not called but it will work if I redefine login field in ClientA, like:

Code:
```python
from typing import Optional

import pydantic


class A(pydantic.BaseModel):
    login: str
    password: str


class ClientA(A):
    login: str
    password: Optional[str] = None

    @pydantic.validator("login")
    def not_called(self):
        return "test"

    @pydantic.validator("password")
    def clean_up(self):
        return None


print(
    ClientA(
        login="login",
        password="password"
    )
)
```
Output:
```python
ClientA login='test' password=None
```

**Comment by samuelcolvin** [comment]
Not sure this is a bug, just a current limitation. Isn't that trivial to add validators to fields on inherited classes, but should be possible.

**Comment by xunto** [comment]
@samuelcolvin yeah, maybe. It was just a little bit of a surprise when I stumbled upon it.

**Comment by samuelcolvin** [comment]
I think we should do two things, raise an exception when a validator is set up wrong (eg fields don't match anything). 

Allow validators to operate on attributes of patent classes.

**Comment by xunto** [comment]
Cool! :+1:

**Comment by alecvinent** [comment]
Still happens!! :(

**Comment by samuelcolvin** [comment]
This issue is very old. Please give an example of you think there is still a problem.

**Comment by alecvinent** [comment]
I have this code:

```
from pydantic import BaseModel

class ReviewValidator:
    @validator('score')
    def validate_score(cls, value: int):
        if value < 1 or value > 5:
            raise ValueError('Score is out of range, min 1 and max 5')
        return value

class ReviewRequestPutModel(BaseModel, ReviewValidator):
    review: str
    score: int

```

**Comment by rudneff13** [comment]
> I have this code:
> 
> ```
> from pydantic import BaseModel
> 
> class ReviewValidator:
>     @validator('score')
>     def validate_score(cls, value: int):
>         if value < 1 or value > 5:
>             raise ValueError('Score is out of range, min 1 and max 5')
>         return value
> 
> class ReviewRequestPutModel(BaseModel, ReviewValidator):
>     review: str
>     score: int
> ```
> 
> > This issue is very old. Please give an example of you think there is still a problem.

Hey. Any updates on this one?

**Comment by samuelcolvin** [comment]
We don't anywhere say this should work.

How validators are gathered is changing in v2, but I don't think we want to support this behavior.

**Comment by Cyclone5** [comment]
> > I have this code:
> > ```
> > from pydantic import BaseModel
> > 
> > class ReviewValidator:
> >     @validator('score')
> >     def validate_score(cls, value: int):
> >         if value < 1 or value > 5:
> >             raise ValueError('Score is out of range, min 1 and max 5')
> >         return value
> > 
> > class ReviewRequestPutModel(BaseModel, ReviewValidator):
> >     review: str
> >     score: int
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > This issue is very old. Please give an example of you think there is still a problem.
> 
> Hey. Any updates on this one?

It worked in v2.
