### ISSUE TITLE
Use field names for validation errors in addition to aliases

### ISSUE THREAD

**Issue by inikolaev** [samuelcolvin/pydantic#1371]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: /Users/inikolaev/.local/share/virtualenvs/XdKCdi6v/lib/python3.8/site-packages/pydantic
               python version: 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27)  [Clang 6.0 (clang-600.0.57)]
                     platform: macOS-10.15.3-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions', 'email-validator']
```

I'm working with an external API which uses obfuscated names in the request models, e.g.:

```json
{
  "a1": "value 1",
  "a2": "value 2",
  "a3": "value 3"
}
```

There's no way I can change this API, but in my service I want to use meaningful names when creating models. So I discovered I could use `allow_population_by_field_name` for that purpose.

However, if don't specify all required fields I get error message which prints out aliases and no field names:

```py
from pydantic import (
    BaseModel,
    Field
)

class Simple(BaseModel):
    field: str = Field(..., alias='a1')

    class Config:
        allow_population_by_field_name = True
```

Here's error example:

```
>>> Simple()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/inikolaev/.local/share/virtualenvs/XdKCdi6v/lib/python3.8/site-packages/pydantic/main.py", line 283, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Simple
a1
  field required (type=value_error.missing)
```

What I would like instead is to have actual field name printed in the output, instead of the alias, which does not make much sense to me. Or at least print field name in addition to alias.

I wonder if there's an easy way around it? 

If not, can this feature be added, what do you think about it?

**Comment by samuelcolvin** [comment]
sorry for the slow response here, I thought I wrote an answer for this, but somehow it got lost.

The short answer right not is "not really".

You can process `validation_error.errors()` and look up `Model.__fields__` to get field names, to display errors using names not aliases.

Let me know if that's problematic.

**Comment by inikolaev** [comment]
Thanks for reply, but do you think it could be improved to be available out-of-the-box? I could submit a PR.
