### ISSUE TITLE
Custom root type iteration and subsciption

### ISSUE THREAD

**Issue by mikuhn** [samuelcolvin/pydantic#1372]
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5a1
            pydantic compiled: False
                 install path: /home/kuhnm/projects/pydantic/pydantic
               python version: 3.8.2 (default, Feb 26 2020, 22:21:03)  [GCC 9.2.1 20200130]
                     platform: Linux-5.4.28-1-MANJARO-x86_64-with-glibc2.2.5
     optional deps. installed: ['devtools']
```

Hi! I wanted to ask if it's feasible to have `__iter__` and `__getitem__` automatically implemented when using custom root types. At the moment this has to be done manually, as shown in the following example. If not, would it be possible to add this example to the docs?

```py
from typing import List, Dict
from pydantic import BaseModel, ValidationError

class Pets(BaseModel):
    __root__: List[str]

    def __iter__(self):
        return iter(self.__root__)

    def __getitem__(self, item):
        return self.__root__[item]


pets = Pets.parse_obj(['dog', 'cat'])
print(pets[0])
#> dog
print([pet for pet in pets])
#> ['dog', 'cat']
```

**Comment by samuelcolvin** [comment]
Definitely happy to add it to the docs, but I'll less sure about making it the default. I think custom root types are confusing enough without the model acting (partially) like the root type itself. If you want that, better to use `parse_as_obj`.

**Comment by mikuhn** [comment]
Hum, for me it was more confusing that the objects behave like a dictionary by default, but not like a List if this is the root type. But i understand your concerns.

I did not understand your hint regarding the `parse_as_obj`, do you mean like this?
```
parse_obj_as(List[str],pets.__root__)                                                                                               
#> ['dog', 'cat']
```
I'll submit a PR regarding the documentation.

**Comment by samuelcolvin** [comment]
no, if you want to parse to a list, parse to a list:

```py
pets = parse_obj_as(List[str], ['dog', 'cat'])
```

Don't bother with an explicit model.

**Comment by e-lo** [comment]
> Don't bother with an explicit model.

What if you need to add validation, though? i.e. making sure that list items are unique, etc.

**Comment by RollerKnobster** [comment]
> > Don't bother with an explicit model.
> 
> What if you need to add validation, though? i.e. making sure that list items are unique, etc.

For a lot of use cases, Annotated types with validators are sufficient ([docs](https://docs.pydantic.dev/latest/concepts/validators/#using-the-annotated-pattern)).
