### ISSUE TITLE
Validate IBAN inside Pydantic Model

### ISSUE THREAD

**Issue by vjanz** [samuelcolvin/pydantic#1374]
Hey guys, I hope everyone is doing great through this rough time.

I want to be short, and not to waste your time.
Is there any way to validate IBAN value, inside a pydantic model..
My model is like following:
```
class Account(BaseModel):
      iban:str
```
I found a library called `schwifty` that is to validate IBAN and BIC, but how do I integrate it here..?
Any help is appreciated.
Thank you guys in advance

**Comment by StephenBrown2** [comment]
See the docs for custom types: https://pydantic-docs.helpmanual.io/usage/types/#custom-data-types

```py
In [1]: from pydantic import BaseModel

In [2]: from schwifty import IBAN

In [3]: class Iban(str):
   ...:     @classmethod
   ...:     def __get_validators__(cls):
   ...:         yield cls.validate
   ...:     @classmethod
   ...:     def validate(cls, v):
   ...:         if not isinstance(v, str):
   ...:             raise TypeError('string required')
   ...:         return IBAN(v)
   ...:

In [4]: class Account(BaseModel):
   ...:     iban: Iban
   ...:

In [5]: a = Account(iban='DE89 3704 0044 0532 0130 00')

In [6]: a
Out[6]: Account(iban=<IBAN=DE89370400440532013000>)

In [7]: a.iban.account_code
Out[7]: '0532013000'
```

**Comment by vjanz** [comment]
@StephenBrown2 thank you very much for time and solution.
That solves my problem!
