### ISSUE TITLE
Add `arbitrary_types_allowed` to validate_arguments

### ISSUE THREAD

**Issue by xbanke** [samuelcolvin/pydantic#1376]
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5a1
            pydantic compiled: True
                 install path: /home/xxx/.conda/envs/xxx/lib/python3.7/site-packages/pydantic
               python version: 3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0]
                     platform: Linux-4.18.0-80.el8.x86_64-x86_64-with-centos-8.0.1905-Core
     optional deps. installed: ['typing-extensions', 'email-validator']
```
Hi, when I use the decorator `validate_arguments`, I have to define validate function for every user defined class. Is there a way to set `arbitrary_types_allowed` `True` or add to the arguments of `validate_arguments`?

**Comment by samuelcolvin** [comment]
See #1205

Short answer: yes in future, is be able to accept a pr to implement this.

**Comment by xbanke** [comment]
> See #1205
> 
> Short answer: yes in future, is be able to accept a pr to implement this.

Sorry, I should check that first.

**Comment by mikenerone** [comment]
If it's not too late for backward-compatibility concerns, `arbitrary_types_allowed=True` is probably the most convenient default for people that use `@validate_arguments` (like me).
