### ISSUE TITLE
Clarify behaviour of .dict() and Enum attributes

### ISSUE THREAD

**Issue by coderfromhere** [samuelcolvin/pydantic#1379]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: ~/.venv/lib/python3.7/site-packages/pydantic
               python version: 3.7.6 (default, Feb 27 2020, 15:15:00)  [Clang 7.1.0 (tags/RELEASE_710/final)]
                     platform: Darwin-19.4.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```
Hi!

I wonder if the snippet below should result in AssertionError?
```py
from pydantic import BaseModel
from enum import Enum

class Y(Enum):
    y = 'y'

class X(BaseModel):
    y: Y

assert isinstance(X(y=Y.y).dict()['y'], Y)
```

The reasoning behind this expectation is that a result of `.dict()` should be compatible with the default JSON encoder, whereas the current behaviour produces Enum values that cannot be encoded automatically with the default `json.dumps()`. This leads to downstream exceptions in frameworks that don't support custom JSON encoders, namely Starlette https://github.com/encode/starlette/issues/715.

**Comment by samuelcolvin** [comment]
see https://github.com/samuelcolvin/pydantic/pull/317, many of the linked issues and in fact all of the issues on the "serialization" label.

This is an open question and something I want to solve better in v2.

For now this is not possible, you should use `.json()` or the `pydantic_encoder` function as the `default` argument for `json.dumps()`.
