### ISSUE TITLE
Implement your own list of TLDs

### ISSUE THREAD

**Issue by aeldaly-tc** [samuelcolvin/pydantic#1380]
# Second Level TLDs

In the documentation here: https://github.com/samuelcolvin/pydantic/blob/b7c0dd5b16fe4a730dbb390851fde63334dba369/docs/usage/types.md#url-properties

It says `tld: optional - the top level domain (com above), Note: this will be wrong for any two-level domain, e.g. "co.uk". You'll need to implement your own list of TLDs if you require full TLD validation`

How do I go about doing that?

Thanks.

```
             pydantic version: 1.4
            pydantic compiled: True
                 install path: /usr/local/lib/python3.7/site-packages/pydantic
               python version: 3.7.4 (default, Sep 12 2019, 15:40:15)  [GCC 8.3.0]
                     platform: Linux-4.19.76-linuxkit-x86_64-with-debian-10.1
     optional deps. installed: ['typing-extensions', 'email-validator']
```

**Comment by samuelcolvin** [comment]
I believe there's no good list of top level domains. Better to do a DNS look up to check if the domain has records.
