### ISSUE TITLE
Create model using a function signature

### ISSUE THREAD

**Issue by antoniomdk** [samuelcolvin/pydantic#1391]
# Feature Request

Hi everyone, first things first, thank you for this fantastic tool you're developing.

I think it would be interesting to create a model dynamically based on a function signature.
In my case, I have some kind of function runners: functions that receive a function and
call it adding decorators, etc.  I've created the following snippet to create a model from
a function signature. If you're interested in this feature, I can create a PR for it. 

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: /Users/antonio/Documents/TFG-AntonioMolner/env/lib/python3.7/site-packages/pydantic
               python version: 3.7.7 (default, Mar 10 2020, 15:43:33)  [Clang 11.0.0 (clang-1100.0.33.17)]
                     platform: Darwin-19.2.0-x86_64-i386-64bit
     optional deps. installed: []
```

```py
import pydantic

def create_model_from_signature(func: Callable,
                                model_name: str,
                                base_model: Type[BaseModel] = BaseModel):
    args, _, varkw, defaults, kwonlyargs, kwonlydefaults, annotations = getfullargspec(func)
    defaults = defaults or []
    args = args or []

    non_default_args = len(args) - len(defaults)
    defaults = (...,) * non_default_args + defaults

    keyword_only_params = {param: kwonlydefaults.get(param, Any) for param in kwonlyargs}
    params = {param: (annotations.get(param, Any), default) for param, default in zip(args, defaults)}

    class Config:
        extra = 'allow'

    # Allow extra params if there is a **kwargs parameter in the function signature
    config = Config if varkw else None

    return create_model(
        model_name,
        **params,
        **keyword_only_params,
        __base__=base_model,
        __config__=config,
    )
...
```

### Example

```
In[12] m = create_model_from_signature(open, 'MyModel', BaseModel)

In[13] m.__fields__

Out[14]: 
{'file': ModelField(name='file', type=Optional[Any], required=True),
 'mode': ModelField(name='mode', type=Optional[Any], required=False, default='r'),
 'buffering': ModelField(name='buffering', type=Optional[Any], required=False, default=-1),
 'encoding': ModelField(name='encoding', type=Optional[Any], required=False, default=None),
 'errors': ModelField(name='errors', type=Optional[Any], required=False, default=None),
 'newline': ModelField(name='newline', type=Optional[Any], required=False, default=None),
 'closefd': ModelField(name='closefd', type=Optional[Any], required=False, default=True),
 'opener': ModelField(name='opener', type=Optional[Any], required=False, default=None)}
```

**Comment by antoniomdk** [comment]
I've realized there is a validate_arguments method, I'm closing this issue.

**Comment by StephenBrown2** [comment]
This seems to be a bit like the `@validate_arguments` decorator that's soon to be released? https://github.com/samuelcolvin/pydantic/pull/1179

**Comment by danielbraun89** [comment]
validate_arguments serve a different use case. Personally I don't understand why not going forward with the original idea...

**Comment by marsninja** [comment]
This is a great idea @antoniomdk , though I agree with @danielbraun89 , I'm trying to build an automated function signature to base model to fastAPI request body and would need to extract the base model from function signatures. validate_arguments doesn't actually provide the base model it uses internally it appears, unless I've missed something.

**Comment by marsninja** [comment]
NVM, I just noticed:

https://github.com/samuelcolvin/pydantic/blob/5bc1fcfb92aace50f18bf4ddcc915ef23e1c7431/pydantic/decorator.py#L45

I can use this as the model, didn't see it in the documentation, LMK if putting in a PR in for the docs if useful.

**Comment by drcege** [comment]
So, how can we implement this functionality in version Pydantic V2? `validate_arguments` has been replaced by `validate_call`, but their internal implementations are quite different. 

The scenario I'm facing is that I have a large number of pre-written functions that I have automatically exposed through FastAPI. I want to dynamically create a BaseModel based on the function signatures and use `model.model_validate_json` to validate and convert the JSON data in the request body.

**Comment by tsitsimis** [comment]
> So, how can we implement this functionality in Pydantic V2? `validate_arguments` has been replaced by `validate_call`, but their internal implementations are quite different.
> 
> The scenario I'm facing is that I have a large number of pre-written functions that I have automatically exposed through FastAPI. I want to dynamically create a BaseModel based on the function signatures and use `model.model_validate_json` to validate and convert the JSON data in the request body.

Did yo find any solution on this?

**Comment by antonymilne** [comment]
https://github.com/lmmx/pydantic-function-models provides a pydantic v2 version of pydantic v1's `ValidatedFunction` that can be used to generate a model from a function signature.

**Comment by pycaw** [comment]
> https://github.com/lmmx/pydantic-function-models provides a pydantic v2 version of pydantic v1's `ValidatedFunction` that can be used to generate a model from a function signature.

This `ValidatedFunction` implementation doesn't offer taking arguments like base class and doesn't actually do any validation. At this point you can't configure it, it only accepts one parameter which is the function. There is a model indeed but the API is crazy messy compared to how small it is. What in the world does `build_model` do? And how does one ultimately validate a set of *args and **kwargs against the model derived from a function?

**Comment by pycaw** [comment]
❗❗❗
https://docs.pydantic.dev/latest/api/experimental/#pydantic.experimental.arguments_schema.generate_arguments_schema
