### ISSUE TITLE
Dynamically create new models inherit from other models and override some fields

### ISSUE THREAD

**Issue by LongicornYu** [samuelcolvin/pydantic#1392]
Is it possible for me to dynamically create new models, that inherits from another pydantic model, and override some fields to be optional?

I tried to use create_model, but I cannot find a way to convert the fields of the parent class to the tuple that's needed for create_model.
I tried below code, but it doesn't quite work for fields with enums
```

    fields = {}
    for field in baseclass.__fields__:
        if baseclass.__fields__[field].shape == Shape.LIST:
            fields[field] = (Optional[List[baseclass.__fields__[field].type_]], None)
        else:
            fields[field] = (Optional[baseclass.__fields__[field].type_], None)
    
    return create_model(name, __base__=baseclass, **fields)


```

**Comment by samuelcolvin** [comment]
Why do you want to change every field?

Surely just change the fields you want to change.

I don't think `baseclass.__fields__[field].type_` will work as it gets modified for complex fields.
