### ISSUE TITLE
Clarify regex usage for constr in documentation

### ISSUE THREAD

**Issue by lmcnearney** [samuelcolvin/pydantic#1396]
It might be helpful to clarify that the `constr` type validator's `regex` argument uses `re.match()` which only requires a partial match on the string. This personally bit me as I assumed the `^` and `$` weren't required and put a length restriction in the expression but the field validated as the start of the string matched. 

Updating the example in the documentation would probably cover it:

```
regex_str: constr(regex='^apple (pie|tart|sandwich)$')
```

Alternatively, it could use `re.fullmatch()` but that would change the behavior of the validator.

**Comment by samuelcolvin** [comment]
Thanks for reporting, perhaps `fullmatch` would have been a good idea, but we can't really change the behaviour until v2 (if you think that's a good idea, I guess create a clear new issue).

In terms of documentation, I completely, PR very welcome.
