### ISSUE TITLE
Informing about pydantic-gen

### ISSUE THREAD

**Issue by licht1stein** [samuelcolvin/pydantic#1405]
I've developed a small package to generate pydantic schemas:
https://github.com/licht1stein/pydantic-gen

I hope you think it's something useful.

**Comment by samuelcolvin** [comment]
Thanks for developing this and letting us know.

I'll close this but if the package get's popular I would be happy to link to it from the pydantic docs.

By the way, I think it would be good if your documentation was a bit more explicit about what the package does. E.g. "this package converts YML definitions to pydantic models (either python code or python objects)" - I wasn't at all clear what the package was doing to start with.

Also, there are a few issues here asking for things like this - it might be worth searching for them and adding a comment with a link to your repo. It's completely understandable to want to tell people about code you've written that you think might be useful.

**Comment by licht1stein** [comment]
Thank you for all the comments, I'll work on documentation. Sorry for asking in the wrong spot too

**Comment by samuelcolvin** [comment]
No problem. Good luck.
