### ISSUE TITLE
Missing port in PostgresDsn

### ISSUE THREAD

**Issue by tuantmtb** [samuelcolvin/pydantic#1408]
# Bug

Missing parameter `port` in PostgresDsn

```py
import pydantic

    @validator("SQLALCHEMY_DATABASE_URI", pre=True)
    def assemble_db_connection(cls, v, values):
return    PostgresDsn.build(
            scheme="postgresql",
            user=values.get("POSTGRES_USER"),
            password=values.get("POSTGRES_PASSWORD"),
            host=values.get("POSTGRES_SERVER"),
            port=values.get("POSTGRES_PORT"),
            path=f"/{values.get('POSTGRES_DB') or ''}",
        )
...
```

Hope you fix soon

**Comment by samuelcolvin** [comment]
Please fill in the template for issues.

Please explain better what the issue is here?

**Comment by Sterls** [comment]
While we can work around the missing "port" param, it would be nice to have it. I just spent an hour trying to figure out why the validator wasn't working. It didn't specify that the "port" was the issue and I naturally thought "port" was a valid param.

Code:
Same as OP's function.

Error:
pydantic.errors.ConfigError: Validators defined with incorrect fields: assemble_db_connection (use check_fields=False if you're inheriting from the model and intended this)

**Comment by michaelwiles** [comment]
How do you work around the missing port?

What is the rationale for not including port in this helper?

**Comment by Sterls** [comment]
I can rem exactly but one of these worked: 
1) Append port to host via host = ... + ":" + port num. 
2) Build your own connection string.
