### ISSUE TITLE
PyCharm complains about missing @classmethod for @validators, but validator is ignored when doing so

### ISSUE THREAD

**Issue by JosXa** [samuelcolvin/pydantic#1415]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: D:\projects\josxabot\.venv\Lib\site-packages\pydantic
               python version: 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.18362-SP0
     optional deps. installed: ['typing-extensions']
```

```py
from pydantic import BaseModel, validator

class Foo(BaseModel):
    bar: int
    
    @validator('bar')
    def _(cls, v):
        return v
```

For the above code snippet, the JetBrains PyCharm IDE reports that "Usually first parameter of a method is named 'self'": 

![image](https://user-images.githubusercontent.com/7313176/79987727-13d31d00-84ae-11ea-94d4-e6c01507464e.png)

Usually, the best practice for class methods is to annotate them with the `@classmethod` decorator, which also satisfies the builtin PyCharm linter:

![image](https://user-images.githubusercontent.com/7313176/79987970-5eed3000-84ae-11ea-8e8f-8370e7276231.png)

However, when using this standard decorator, the validator simply does not run (verified by using a simple print statement inside the method body).

Suppressing the warning using `# noinspection PyMethodParameters` works, but is an ugly thing to do everywhere.

**Comment by koxudaxi** [comment]
@JosXa 
You should use Pydantic PyCharm Plugin.

Please check this document.
https://pydantic-docs.helpmanual.io/pycharm_plugin/

![screenshot62](https://user-images.githubusercontent.com/630670/79992555-9b408080-84ee-11ea-8622-32a13114a2a7.png)

**Comment by PrettyWood** [comment]
Hi @JosXa 
Adding a `classmethod` decorator will break your code as `validator` already returns a `classmethod`. It's just an issue with PyCharm

![Screen Shot 2020-04-22 at 4 10 22 PM](https://user-images.githubusercontent.com/18406791/79993585-33217880-84b5-11ea-9afd-d3da5bd92901.png)

But as @koxudaxi said, there is a plugin for _pydantic_, which helps PyCharm linter

**Comment by JosXa** [comment]
Seet, didn't know that was a thing. Awesome :)

**Comment by ianlini** [comment]
It's not PyCharm's issue. [pep8-naming](https://pypi.org/project/pep8-naming/) also complains about this (N805).

They complain about this for some good reasons. I personally don't think the current style in Pydantic is a good coding style or is pythonic ("Explicit is better than implicit." - The Zen of Python). The current way simply makes a method become class method implicitly, so people reading that code won't be sure that this method is really a class method.

It would be nice if we can optionally specify `@classmethod` explicitly.

**Comment by ianlini** [comment]
I seems that the code will work if I specify `@classmethod` after `@validator`:

```python
from pydantic import BaseModel, validator

class Foo(BaseModel):
    bar: int
    
    @validator('bar')
    @classmethod
    def _(cls, v):
        return v
```

but I'm not sure whether this is officially supported.

**Comment by igorbga** [comment]
I've installed the plugin in Pycharm Community 2021.3.3 but it is still complaining about it if I use Pydantic dataclasses instead of BaseModel.

I've opened an issue for the plugin:
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/466
