### ISSUE TITLE
Support for 13/19 digits VISA credit cards in PaymentCardNumber type

### ISSUE THREAD

**Issue by Bahus** [samuelcolvin/pydantic#1416]
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5
            pydantic compiled: True
                 install path: /Users/<hidden>/.pyenv/versions/3.7.2/envs/common-utils/lib/python3.7/site-packages/pydantic
               python version: 3.7.2 (default, Jan 22 2020, 18:22:02)  [Clang 10.0.1 (clang-1001.0.46.4)]
                     platform: Darwin-18.7.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Currently `PaymentCardNumber` type does support 16-digits VISA only:

https://github.com/samuelcolvin/pydantic/blob/3cd8b1ee2d5aac76528dbe627f40fe1c27bf59f6/pydantic/types.py#L677-L679

However as described on wiki page https://en.wikipedia.org/wiki/Payment_card_number:

> While the vast majority of Visa's account ranges describe 16 digit card numbers there are still a few account ranges (forty as of 11 December 2013) dedicated to 13 digit PANs and several (439 as of 11 Dec. 2013) account ranges where the issuer can mix 13 and 16 digit card numbers. Visa's VPay brand can specify PAN lengths from **13** to **19** digits and so card numbers of more than 16 digits are now being seen.

This fact is handler properly in `faker` library:

https://github.com/joke2k/faker/blob/0f86b60178fbbd27d50a184e94c429d4b60d8aef/faker/providers/credit_card/__init__.py#L48-L49

But not handled in pydantic.

**Comment by samuelcolvin** [comment]
happy to accept a PR to fix this.

**Comment by samuelcolvin** [comment]
Just to clarify, is any length between 13 and 19 digits inclusive allowed? Or just 13, 16, or 19 digits?

**Comment by gmcrocetti** [comment]
AFAIU it's not inclusive. Did some research and this formatting [website](https://www.freeformatter.com/credit-card-number-generator-validator.html#cardFormats) came up.

Let me ask you something about implementation. We may create subtypes following faker's approach (`visa13`, `visa19`, `visa16`). In my opinion, we shouldn't replace `visa` in favor of `visa16` as it's going to break. Let's keep the non explicit `visa` brand ? Any thoughts about this ?

**Comment by samuelcolvin** [comment]
I'm opposed to having multiple types. We should have just one card type, people can subclass that or add validators to constrain types more if they wish.
