### ISSUE TITLE
A method to recheck the model

### ISSUE THREAD

**Issue by gk-patel** [samuelcolvin/pydantic#1425]
# Feature Request

Is it possible to add a recheck() method to the model ? 

For example, lets say I have a pydantic BaseModel class called Foo and I have done foo = Foo(**{}) and now I am passing foo to scripts written by others and when I get it back I want to recheck it. 

I could implement something like this,
```
class Foo(BaseModel): 
      v1: int 
      v2: List[float] ..... etc

     def recheck(self): 
           return self.__class__.parse_obj(self.dict())
```
but I dont know if this is the most optimal way. 

Thank you for your time and the wonderful library.

**Comment by samuelcolvin** [comment]
Best to use [`validate_assignment`](https://pydantic-docs.helpmanual.io/usage/model_config/) or add your own method as you have here.
