### ISSUE TITLE
Create Model/Dataclass with/without alias name

### ISSUE THREAD

**Issue by spacemanspiff2007** [samuelcolvin/pydantic#1433]
# Unexpected behavior

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5
            pydantic compiled: True
               python version: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
     optional deps. installed: ['typing-extensions']
```

I am using pydantic to create some API wrappers. At some point I am expecting the user to create instances of the defined schema and pass it into a function.
I am using the Model so I don't have to define a second dataclass with the exact same members.

I'd expect (at least for the pydantic dataclasses) the following to work out of the box
```py
from typing import Dict, Any

from pydantic import BaseConfig, BaseModel, Extra, Field

BaseConfig.extra = Extra.forbid

class ItemChannelLinkDefinition(BaseModel):
    item_name: str = Field(alias='itemName')
    configuration: Dict[str, Any] = {}


ItemChannelLinkDefinition(item_name='asdf')
```
```
pydantic.error_wrappers.ValidationError: 2 validation errors for ItemChannelLinkDefinition
itemName
  field required (type=value_error.missing)
item_name
  extra fields not permitted (type=value_error.extra)
```

I tried both ``Dataclass`` and ``BaseModel`` and they show the same behavior.
The behavior however is (imho) rather un intuitive.

I know I can set
```py
BaseConfig.allow_population_by_field_name = True
```
but PyCharm still shows an error

![grafik](https://user-images.githubusercontent.com/10754716/80270938-aea14680-86bc-11ea-8ba7-8a6d6adb9599.png)

---

I think that it should be possible to create a Model/Dataclass with the defined variable names and that the alias mapping should be done in a factory function like
```python
ItemChannelLinkDefinition.create(itemName='item', channelUID= 'chan')
```
which then would be consistent with
```python
ItemChannelLinkDefinition.parse_obj({'itemName': 'item', 'channelUID': 'chan'})
```

Exporting models is consistent, too since the ``dict`` method accepts the ``by_alias`` argument.

**Comment by spacemanspiff2007** [comment]
This should have been a question, but I can't relabel it.
Behavior has been discussed in #565, but I'd really appreciate a hint how I can solve this.
Creating dataclasses with the same fields just for the users seems awfully backwards.

**Comment by samuelcolvin** [comment]
I understand your problem, but it seems you know of all the current workarounds.

The pycharm issue relates to the [pycharm plugin](https://github.com/koxudaxi/pydantic-pycharm-plugin) please look or create issues there for stuff related to that

With pydantic, I'm not adding more methods like `create`. I could definitely consider adding a utility like `model_to_dataclass`, would that solve your problem. Otherwise what exactly are you looking for?

**Comment by spacemanspiff2007** [comment]
I want to use the model directly as an interface between my API and the user and I'm afraid the additional functions and members of the model will confuse him. That's why my intention is to go with the dataclass from pydantic.
However, I am not sure how to use the alias with dataclass

```python
import dataclasses
from typing import Any, Dict

from pydantic import Field
from pydantic.dataclasses import dataclass


@dataclass
class ItemChannelLinkDefinition:
    item_name: str = Field(alias='itemName')
    channel_uid: str = Field(alias='channelUID')
    configuration: Dict[str, Any] = dataclasses.field(default_factory=dict)

o = ItemChannelLinkDefinition(item_name='asdf', channel_uid='asdfasdf')
o.__pydantic_model__.dict(by_alias=True)
```
because

```python
o__pydantic_model__.dict(by_alias=True)
```
throws

```
TypeError: dict() takes exactly 1 positional argument (0 given)
```

**Comment by spacemanspiff2007** [comment]
@samuelcolvin 
Could you give me a hint how I can serialize pydantic dataclasses with an alias?

**Comment by thepabloaguilar** [comment]
I'm with the same problem here!
Unfortunately, my models have two *"conflicting"* attributes, *fields* and *schema*!
It'll be great if we can use **alias** option with dataclass, as well.
@spacemanspiff2007 Did you find some way to make *alias* work?
@samuelcolvin Could you provide an example for us?

**Comment by spacemanspiff2007** [comment]
Unfortunately not, I was trying to use the dataclass as a single input/output parameter of the api but since it was only a couple of keys I reverted to function parameters and build the dataclass now inside the function.

**Comment by samuelcolvin** [comment]
@thepabloaguilar the problem with conflicting names will change one day once #1001 is fully implemented, but that'll be a long time since we'll have to have a transition period when methods like `fields` remain with warnings.

> Could you provide an example for us?

An example of what?

**Comment by spacemanspiff2007** [comment]
Using and serializing a dataclass with an alias.
See [my previous question](https://github.com/samuelcolvin/pydantic/issues/1433#issuecomment-620977422)

**Comment by samuelcolvin** [comment]
@spacemanspiff2007 I'm afraid there's no way to use aliases with dataclasses as far as I know.

The problem is that we use standard python dataclasses:

https://github.com/samuelcolvin/pydantic/blob/0cee311be59ca09cd29a66c344cd06fb304e9ddd/pydantic/dataclasses.py#L89-L90

python's dataclasses effectively prepare a string of python code which creates the class, then evaluates it to create the dataclass object - that code is generated with argument names matching the field names - with no concept of aliases. Thus there's no way for pydantic dataclasses to have aliases without reimplementing the whole of dataclasses, which is outside the bounds of pydantic.

**Comment by ADR-007** [comment]
Can we use `matadata` for an alias? e. g.:
```
@dataclass
class MyDataclass:
    my_field: int = field(metadata=dict(alias='my_alias')
```

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
