### ISSUE TITLE
Augment model parse behavior to create subtypes of hinted type

### ISSUE THREAD

**Issue by tomplex** [samuelcolvin/pydantic#1435]
# Question

I have input data (essentially configuration data) which contains some information about a file which the process must open. The file might be locally accessible, or it might live on S3. I have specific models which match those representations, like an `S3File`, or a `LocalFile`, but the program can receive input from either type ad nauseum. I'd like to be able to create a `File` class / model which I can use as a hint in my main configuration model, which different implementations of Files can inherit from, and then ideally `pydantic` will dynamically create the right flavor of `File` from the data which was input.

For a concrete example, I'm receiving JSON like this:

```json
{
    "source": {
        "s3": {
            "bucket": "some-bucket",
            "key": "path/to/file.txt"
        },
    }
}
```
```json
{
    "source": {
        "local": {
            "path": "/path/to/file.txt",
        },
    }
}
```

I'd like to write code which looks like this:
```py
import abc
import pydantic


class File(pydantic.BaseModel, abc.ABC):
    """
    This class should be able to delegate to the
    "right" type of file subclass from the input
    JSON.
    """

    @abc.abstractmethod
    def open(self):
        pass


class S3File(File):
    bucket: str
    key: str

    def open(self):
        # S3 specific open functionality
        pass


class LocalFile(File):
    path: str

    def open(self):
        return open(self.path)


class Configuration(pydantic.BaseModel):
    source: File


data = {"source": {"local": {"path": "/tmp/test.txt"}}}
config = Configuration.parse_obj(data)
filehandle = config.source.open()
```

Ideally, I'd like to add other sources I can "open" with different kinds of configuration, without my code needing to care much which flavor of `File` is passed in or where it lives. 
Unfortunately I have no control over the structure of incoming data.

Is this possible, or desirable? Am I approaching it the wrong way?

Thanks in advance for any advice.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /Users/TO010CA/.virtualenvs/activity/lib/python3.8/site-packages/pydantic
               python version: 3.8.0 (v3.8.0:fa919fdf25, Oct 14 2019, 10:23:27)  [Clang 6.0 (clang-600.0.57)]
                     platform: macOS-10.14.6-x86_64-i386-64bit
     optional deps. installed: []

```

**Comment by tomplex** [comment]
Though I read the page for custom types, it didn't really click with me when I read it that I could create a custom Pydantic type which implements this behavior quite elegantly. [Here's a gist](https://gist.github.com/tomplex/c0df7e211908da46836a35af6ab5370f) with my final code which will accept data representing arbitrary files and dynamically create the "right" class.

**Comment by StephenBrown2** [comment]
Not related to pydantic in particular, but you can also use python's builtin pathlib as your type for [LocalFile](https://gist.github.com/tomplex/c0df7e211908da46836a35af6ab5370f#file-pydantic_redirecting_type-py-L42-L46), like so:
```py
from pathlib import Path

class LocalFile(File):
    path: Path
```
which will provide it's own `open()` method for you: https://docs.python.org/3.8/library/pathlib.html#pathlib.Path.open, and the whole gist can be simplified like so:

```py
import typing
import pathlib
import pydantic

class S3File(pydantic.BaseModel):
    bucket: str
    key: str

    def open(self, *args, **kwargs) -> typing.IO:
        raise NotImplementedError

class LocalFile(pydantic.BaseModel):
    path: pathlib.Path

    def open(self, mode="r", *args, **kwargs) -> typing.IO:
        return self.path.open(mode=mode, *args, **kwargs)

class Configuration(pydantic.BaseModel):
    source: typing.Union[S3File, LocalFile]


data = {"source": {"path": "/tmp/test.txt"}}

config = Configuration(**data)
with config.source.open() as f:
    print(f.read())
```
