### ISSUE TITLE
Dynamically construct 'Union' like type

### ISSUE THREAD

**Issue by jqqqqqqqqqq** [samuelcolvin/pydantic#1439]
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: /Users/jiangqiao/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pydantic
               python version: 3.8.1 (default, Feb 29 2020, 20:08:03)  [Clang 11.0.0 (clang-1100.0.33.17)]
                     platform: macOS-10.15.4-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

I have a modularized class definition that injects classes to the main module and then runs pydantic to deserialized some json like configurations. In this case, I have to write something very dirty using `eval` like:

```py
import pydantic
def construct_union(modules: List):  
    # modules is a list of class constructors and has to be accessible in the current global scope
    eval_string = ', '.join([i.__module__ + '.' + i.__name__ for i in modules])
    return eval(f'Union[{eval_string}]')

class FullConfig(BaseModel):
    ...
    Driver: Optional[Dict[str, construct_union(driver_config)]]

    ExtensionConfig: Optional[Dict[str, construct_union(extension_config)]]

    @validator('Driver', pre=True, always=True)
    def generate_empty_dict_if_none(cls, v):
        return v or {}

    @validator('ExtensionConfig', pre=True, always=True)
    def generate_empty_dict_if_none2(cls, v):
        return v or {}
```

Is there a better way to achieve the same goal without eval?

**Comment by samuelcolvin** [comment]
Not really.

Personally I would `Dict[str, Any]` and use a validator to check the type is valid.

The problem is that fundamentally pydantic uses type annotations to validate data - that's great because it works with static type analysis like mypy, IDEs like pycharm and python developers like me.

dynamic unions wouldn't really work with any of those things, so I don't really seem much point in them (or any other dynamic type hints).

**Comment by vdwees** [comment]
@jqqqqqqqqqq  Not sure I understand the question, but you can pass a dynamic list of classes to a Union. Just like the syntax for `__getitem__` in python, you need to provide the list of arguments as a `tuple` to the `Union.__class_getitem__` call. I do this sometimes to dynamically generate `anyOf` lists in json schemas at runtime.

You didn't give any example modules, so I can't say for sure, but something like this might work for you:
```py
def construct_union(modules: List):
    return Union[tuple(modules)]
```

**Comment by jqqqqqqqqqq** [comment]
> @jqqqqqqqqqq Not sure I understand the question, but you can pass a dynamic list of classes to a Union. Just like the syntax for `__getitem__` in python, you need to provide the list of arguments as a `tuple` to the `Union.__class_getitem__` call. I do this sometimes to dynamically generate `anyOf` lists in json schemas at runtime.
> 
> You didn't give any example modules, so I can't say for sure, but something like this might work for you:
> 
> ```python
> def construct_union(modules: List):
>     return Union[tuple(modules)]
> ```

Thank you! This seems to be a better workaround.

**Comment by vdwees** [comment]
Anything for one less eval ;)
