### ISSUE TITLE
test

### ISSUE THREAD

**Issue by kulame** [samuelcolvin/pydantic#1445]
# Bug

raw json 

```py
import pydantic
item =  {
        'id': '46',
        'user_id': None,
        'click_nums': '0',
        'form_id': 'the formId is a mock one',
        'level': '8',
        'create_time': '2019-01-31 15:27:39.263125',
        'update_time': '2020-04-25 19:41:14.512305',
        'is_online': '1',
        'is_deleted': '0',
        'is_vest': '0',
        'is_push': '0',
        'is_click': '0',
        'is_share': '1',
        'fake_exceed_nums': '793',
        'real_click_nums': '0',
}
data =create_model(**item)
...
```
show error message 
pydantic.errors.ConfigError: unable to infer type for attribute "user_id".

how can i do with this issue?  the user_id field is nullable

**Comment by PrettyWood** [comment]
Hi @kulame 
Could you please follow the template given [here](https://github.com/samuelcolvin/pydantic/blob/master/.github/ISSUE_TEMPLATE/bug.md) and please provide the full code to replicate the error. For example what is your `model` here ?

**Comment by kulame** [comment]
my fault,  how can i delete this issue?
