### ISSUE TITLE
add method to parse a value to a given type

### ISSUE THREAD

**Issue by seansfkelley** [samuelcolvin/pydantic#1451]
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /Users/seankelley/Library/Caches/pypoetry/virtualenvs/cl-pydantic-ygGyMK5A-py3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Mar 30 2020, 17:42:05)  [Clang 10.0.1 (clang-1001.0.46.4)]
                     platform: macOS-10.14.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']

```

This issue is a request to add the `parse_obj_to_type` method described at https://github.com/samuelcolvin/pydantic/issues/726#issuecomment-519448391.

I was originally going to file a bug report before I noticed that ticket, because I ran across some odd behavior while trying to implement my own version of `parse_obj_to_type`. Below is the original issue I was going to file, because I think it serves as good motivation for why one can't just implement this method oneself (unless I'm misunderstanding something!).

I've found my own implementation of this method particular useful, since I'm often using things like top-level `Union` types and I don't want to wrap those in `__root__`. I also sometimes use it to validate/parse `int` or `constr` values directly. That said, I ended up here because for reasons out of my control I have to use `__root__` in at least one place.

<hr/>

I'm trying to implement a `parse_type` function like so:

```py
def parse_type(value: Any, type_: Type[T]) -> T:
    class Wrapper(BaseModel):
        field: type_  # type: ignore

    return Wrapper(field=value).field
```

This works great for the majority of types, but when mixing with `__root__`, it starts to fail.

```py
class Nested(BaseModel):
    field: str

class Root(BaseModel):
    __root__: Nested

# raises
parse_type({"field": "str"}, Root)

# ...or...

class Nested1(BaseModel):
    foo: str

class Nested2(BaseModel):
    bar: str

class Root(BaseModel):
    __root__: Union[Nested1, Nested2]

# raises
parse_type({"foo": "str"}, Root)
```

I worked around some cases by updating the implementation like so:

```py
def parse_type(value: Any, type_: Type[T]) -> T:
    try:
        is_base_model = issubclass(type_, BaseModel)
    except TypeError:
        # Probably a Union, or similar.
        is_base_model = False

    if is_base_model:
        return type_.parse_obj(value)
    else:

        class ParseWrapper(BaseModel):
            field: type_  # type: ignore

        return ParseWrapper.parse_obj({"field": value}).field
```

And this works for passing around a simple type with `__root__`, but then it fails on more complex cases that mix the two:

```py
class Nested(BaseModel):
    field: str

class Root1(BaseModel):
    __root__: int

class Root2(BaseModel):
    __root__: Nested

class Outermost(BaseModel):
    field: Union[Root2, Root1]

Outermost(field={"field": "str"})

# raises:
#   pydantic.error_wrappers.ValidationError: 2 validation errors for Outermost
#   field -> __root__
#     field required (type=value_error.missing)
#   field -> __root__
#     field required (type=value_error.missing)
```

At this point I gave up and decided that I can live with this limitation, so I stopped.

As far as I can tell from [the docs](https://pydantic-docs.helpmanual.io/usage/models/#custom-root-types), it seems like this should be supported. My thought process:

> If you call the `parse_obj` method for a model with a custom root type with a dict as the first argument, the following logic is used:
> 
> - If the custom root type is a mapping type (eg., `Dict` or `Mapping`)-- _not this case_
> - For other custom root types, if the dict has precisely one key with the value `__root__`-- _not this case_
> - Otherwise, the dict itself is validated against the custom root type-- _should hit this case_

**Comment by samuelcolvin** [comment]
have you seen [`parse_obj_as`](https://pydantic-docs.helpmanual.io/usage/models/#parsing-data-into-a-specified-type)? 

Why does that not suffice?

If I'm missing something feel free to reply and I'll reopen this issue.

**Comment by seansfkelley** [comment]
Ah, I had not seen that, thanks! My searches on the docs and in the issues didn't turn it up.

However, it looks like it has the same flaws I was trying to work around when I filed this issue. 

```py
class Nested(BaseModel):
    field: str

class Root(BaseModel):
    __root__: Nested

# raises
parse_obj_as(Root, {"field": "str"})

# ...or...

class Nested1(BaseModel):
    foo: str

class Nested2(BaseModel):
    bar: str

class Root(BaseModel):
    __root__: Union[Nested1, Nested2]

# raises
parse_type(Root, {"foo": "str"})
```

They both raise:

```
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[Root]
__root__ -> __root__
  field required (type=value_error.missing)
```

Which is more or less the kind of error I was seeing before I started rewriting my own function to support `__root__` (so hey, at least I'm not crazy).
