### ISSUE TITLE
Can't get json Object from MongoDBModel

### ISSUE THREAD

**Issue by paulogonc** [samuelcolvin/pydantic#1454]
# Question
Hi everybody,

I've a question regarding my error message:
```
File "pydantic/json.py", line 21, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte...
```
I'm using the extension package for fastAPI (fastapi_contrib) to access my MongoDB database. Writing (post) a image into the database works without any problems. When I'm trying to get the collection from the MongoDB, pydantic throws a error message at the "return" postion. I guess the pydantic serializer couldn't codec the image Object (bytes) in the model. Any ideas for a workaround? Is this topic related to this post too https://github.com/samuelcolvin/pydantic/issues/692

Thanks in advance,
Paulo

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pajofego@T440s:~/python/$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: ~/anaconda3/envs/myenv/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Mar 26 2020, 15:53:00)  [GCC 7.3.0]
                     platform: Linux-4.4.0-177-generic-x86_64-with-glibc2.10
     optional deps. installed: []
...
```

```py
import pydantic

class MetaData(MongoDBModel):
    description:str
    title:str

class Picture(MongoDBModel):
    meta:MetaData
    pict:Optional[bytes]
    class Meta:
        collection = 'pictures'

@app.get("/picture/{id}")
async def get_pict(id:int):
    try:
        pict_model = Picture(meta=MetaData(description="description", title="title"), pict=b'')
        result = await pict_model.get(id=id)
        if result == None:
            return JSONResponse(content={'message':'ID doesnt exist.'}, status_code=HTTP_404_NOT_FOUND)
        return result  # <-- here is the exception position       
    except ValidationError as e:
        return e.json()
...
```

**Comment by paulogonc** [comment]
Solved it by transforming the image from binary type to string using `pict64 = b64encode(pict).decode("utf-8")`. If there is no other suggestion this thread can be closed.

**Comment by tonibofarull** [comment]
Any news regarding saving bytes? I'm also getting the same error!
