### ISSUE TITLE
Disable or hide field in child class

### ISSUE THREAD

**Issue by idmitryz** [samuelcolvin/pydantic#1460]
For example, I have

```python
class BaseItem(BaseModel):
    id: str
    name: str


class Company(BaseItem):
    attr1: str
    attr2: str

```

I want my name field to be available, but id is not available after JSON serialization of class Company. How can i do this?

**Comment by samuelcolvin** [comment]
hide for parsing, serialisation or schema?
* You can hide fields when serialising using the `exclude` kwarg to `.dict()` or `.json()`.
* There's currently no way to remove from parsing, though it might be possible in future with #624. I guess you could get something similar by removing a field from the schema, then using a validator to raise an error whenever it's provided.
* you could remove a field from schema using `schema_extra`
