### ISSUE TITLE
SecretStr min_length, max_length

### ISSUE THREAD

**Issue by transfluxus** [samuelcolvin/pydantic#1461]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: True
                 install path: /app/venv/lib/python3.7/site-packages/pydantic
               python version: 3.7.5 (default, Apr 19 2020, 20:18:17)  [GCC 9.2.1 20191008]
                     platform: Linux-5.3.0-51-generic-x86_64-with-Ubuntu-19.10-eoan
     optional deps. installed: ['typing-extensions', 'email-validator']
```
When the constraints min_length or max_length are set for a field of type SecretStr the erorr appear:
e.g.

```
class SecrTest(BaseModel):
    b: SecretStr = Field(None, max_length= 4)

On field "b" the following field constraints are set but not enforced: max_length. 
For more details see https://pydantic-docs.helpmanual.io/usage/schema/#unenforced-field-constraints
```

**Comment by samuelcolvin** [comment]
makes sense, thanks for reporting.

PR welcome to fix this.

**Comment by transfluxus** [comment]
hehe, 
tried to fix it indeed:
https://github.com/transfluxus/pydantic/tree/fix_secret_str_constraints

not sure if all things are propper. Maybe you have a look or shall I just make a pull request?

**Comment by transfluxus** [comment]
oh, however test_schema.test_secret_types fails because the schema changed. So ultimately SecretBytes should have the same constraints I guess?
