### ISSUE TITLE
Support for custom types for validation and schema generation

### ISSUE THREAD

**Issue by coldino** [samuelcolvin/pydantic#1464]
# Question

(relevant to 1.5.1 and current master)

In my project I have a class `FloatProperty` that implements `numbers.Real` that can entirely act as a float. There's also `IntProperty`, etc.

I'd like to be able to use these types in pydantic, one way or another, and get full support including generating schemas. Unfortunately after trying a few approaches it seems there's no solution.

I looked at a few options:

1) Setting these values into `float` type fields unexpectedly converts the value to floats by `float_validator`, losing data.
1) Using `Real` type fields is not supported by pydantic, for validation or schema generation.
1) Tried adding *type* validators for `FloatProperty`, but I could find no acceptable method to do this other than modifying the private `pydantic.validators._VALIDATORS` list.
1) Tried using `FloatProperty` in the field definition with `arbitrary_types_allowed`, but then pydantic can no longer generate a schema.
1) Tried modifying pydantic's `float_validator` method to accept `numbers.Real` as well as `float`, but this is not entirely right, type-wise.

Any ideas how could I support my custom types? I'm not against extending pydantic to achieve this.

**Comment by samuelcolvin** [comment]
It should be as simple as implementing `__get_validators__` and `__modify_schema__` on your classes, see https://pydantic-docs.helpmanual.io/usage/types/#custom-data-types.
