### ISSUE TITLE
OpanAPI links

### ISSUE THREAD

**Issue by r2rstep** [samuelcolvin/pydantic#1469]
Hi,

is it possible to generate OpenAPI links with pydantic?

I tried the following but it doesn't work:
```python
class CompatibleComponents(BaseModel):
    components: List[Union[str, Cassette, RearDerailleur]] = Field([], links=dict(self=''))
```

**Comment by samuelcolvin** [comment]
I'm afraid I don't understand the question. Could you explain what you need in more detail.

**Comment by PrettyWood** [comment]
Closing as there was no answer from the author
