### ISSUE TITLE
uniqueItems support for conlist() ?

### ISSUE THREAD

**Issue by neimad1985** [samuelcolvin/pydantic#1472]
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.5.1
pydantic compiled: False
install path: /home/neimad/git/moodz-api/src/venv/lib/python3.8/site-packages/pydantic
python version: 3.8.2 (default, Mar 24 2020, 13:51:08)  [GCC 7.5.0]
platform: Linux-4.15.0-96-generic-x86_64-with-glibc2.27
optional deps. installed: []
```

Hi,

**Spec**
I'd like to reprensent a Person, a Person has some Attractions.
Attractions is a list of one or two elements (cannot be empty) taken in `male` and `female`.

**What I did**
```py
from enum import Enum
from pydantic import BaseModel,  conlist

class Sex(str, Enum):
    male = 'male'
    female = 'female'

class Attractions(BaseModel):
    __root__: conlist(Sex, min_items=1, max_items=2)

class Person(BaseModel):
    attractions: Attractions

print(Person.schema_json(indent=2))
```
```json
{
  "title": "Person",
  "type": "object",
  "properties": {
    "attractions": {
      "$ref": "#/definitions/Attractions"
    }
  },
  "required": [
    "attractions"
  ],
  "definitions": {
    "Attractions": {
      "title": "Attractions",
      "type": "array",
      "items": {
        "enum": [
          "male",
          "female"
        ],
        "type": "string"
      },
      "minItems": 1,
      "maxItems": 2
    }
  }
}
```

**The problem**
I want to make sure that the elements of the list are unique, hence that those two values are not allowed:
- `['female', 'female']`
- `['male', 'male']`

This constraint is normally represented by the key `uniqueItems` in a JSON schema but the method `conlist()` does not accept a corresponding `unique_items` argument like it does for `minItems => min_items` and `maxItems => max_items`.
I also searched for a `conset()` method because I know that `set` types generate a schema containing a `uniqueItems` entry but could not find one.

**Question/Issue/Feature request**

Is there a way to benefit from the best of both worlds: uniquess from `set` and length constraints from `conlist()`?

**Last but not least**

Thanks a lot for this great lib!

Regards

**Comment by samuelcolvin** [comment]
Right now you'd need to use `schema_extra` to add `uniqueItems` to the schema for that field.

If you'd like to suggest `conset` as a feature, please create a "feature request" issue for that.

**Comment by neimad1985** [comment]
Ok, I will use `schema_extra`, thanks for your response.
Anyway I still think that it is a bit weird (no offense intended) to have `min_items` and `max_items` for `conlist` but not `unique_items` as those are closely related.
