### ISSUE TITLE
validator decorator function does not recognise fields with leading underscores in name

### ISSUE THREAD

**Issue by invokermain** [samuelcolvin/pydantic#1476]
**Example Code**
`from pydantic import BaseModel, validator

class MyModel(BaseModel):
  _var: str = 'hello'

  @validator('_var')
  def validate_var(cls, v):
    return v

MyModel(_var="test")`

**Example Output**
`pydantic.errors.ConfigError: Validators defined with incorrect fields: validate_var (use check_fields=False if you're inheriting from the model and intended this)`

**Expected Behaviour**
I assume that I would be able to use underscored variable names as they are commonly used to indicate a private variable. Or I would expect a more relevant error message as the current error message causes confusion.

**Comment by samuelcolvin** [comment]
fields cannot start with an underscore, use aliases if you need to populate via a name starting with an underscore.

See #288 #655 #1388

**Comment by invokermain** [comment]
Thanks for the quick reply 😄 Luckily, private variables isn't a requirement for my project.

However, I do think there is still room for improvement here. As far as I can see, this behaviour is not mentioned in the (otherwise brilliant) docs. Adding this to the docs, or having an explicit error message/warning when attempting this would be amazing in my opinion.

Currently, the only way for me to learn about this behaviour was to raise an issue, or search previous issues on Github. Seeing as you've linked three other issues around this, seems to be a worth while addition?

**Comment by samuelcolvin** [comment]
PR welcome to improve the documentation.
