### ISSUE TITLE
Support more json schema `$ref` patterns

### ISSUE THREAD

**Issue by Kilo59** [samuelcolvin/pydantic#1479]
# Feature Request

I would like to be able to generate more types of references than can be created via a simple `ref_prefix`. For example, referencing a schema that resides in another file.

`{ "$ref": "/schemas/Foo.json#/}`

https://json-schema.org/understanding-json-schema/structuring.html#reuse
https://docs.opis.io/json-schema/1.x/pointers.html

## Example

```py
import json
from pydantic import BaseModel
from pydantic.schema import schema

class Foo(BaseModel):
    a: int

class Model(BaseModel):
    a: Foo

# Default location for OpenAPI
model_schema = Model.schema(ref_template='/schemas/{name}.json#/')
print(json.dumps(model_schema , indent=2))
```
```json
{
  "Model": {
    "title": "Model",
    "type": "object",
    "properties": {
      "a": {
        "$ref": "/schemas/Foo.json#/"
      }
    },
    "required": ["a"]
  }
}
```

I believe python's [`string.Template`](https://docs.python.org/3/library/string.html#template-strings) could be a good way to implement this (which I have attempted). 
There are still some details that need to be worked out.

[Pull request](https://github.com/samuelcolvin/pydantic/pull/1480)

**Comment by samuelcolvin** [comment]
Sorry for the slow reply and thanks for the feature request and PR.

I haven't personally used `$ref` so I'm personally kind of neutral on the feature.

To accept it I guess I would hope for some other interest here via some 👍s.

Regarding how it's implemented, I don't think it needs `string.Template`. `.format()` should work find, e.g. something like

```py
ref_template = ref_template or '#/definitions/{model}'
m_schema = {'$ref': ref_template.format(model=model_name)}
```

I guess to be clean, if this is accepted, we should depreciate `ref_prefix` in v2 and replaced it with `ref_template`

**Comment by Kilo59** [comment]
@samuelcolvin just updated the PR to use `.format`
