### ISSUE TITLE
Pydantic not checking int initialization?

### ISSUE THREAD

**Issue by dementedhedgehog** [samuelcolvin/pydantic#148]
Howdy I was wondering whether this was supposed to be valid? Do you see this behaviour?

```
import pydantic

class Foo(pydantic.BaseModel):
    x: int = "frog"

Foo()

<Foo x='frog'>
```

**Comment by dementedhedgehog** [comment]
Seems there's some config option to check this.

**Comment by samuelcolvin** [comment]
In general, there's no need to validate the default values as they're set by the developer.

There are also cases where it's helpful to have defaults which wouldn't validate in a standard way. Hence this choice.
