### ISSUE TITLE
Identical name for field and type with default set for enum throws ConfigError

### ISSUE THREAD

**Issue by evetion** [samuelcolvin/pydantic#1481]
# Bug

Versions:
```
❯ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.4
            pydantic compiled: False
                 install path: /Users/evetion/opt/miniconda3/lib/python3.7/site-packages/pydantic
               python version: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56)  [Clang 4.0.1 (tags/RELEASE_401/final)]
                     platform: Darwin-19.3.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions', 'email-validator', 'devtools']
```

This is a niche use case resulting from many nested pydantic classes based on existing json-schemas (hence the camelcasing in names). Pydantic is a fantastic library for handling such data.

The following is a minimal example:

```py
from pydantic import BaseModel
from enum import Enum
from typing import Optional

class Bar(Enum):
    VALUE = "value"

class Foo(BaseModel):
    Bar: Bar = "value"

Foo()
```
throws:
```
field "Bar" not yet prepared so type is still a ForwardRef, you might need to call Foo.update_forward_refs().
```

Taking the advice in the error message won't work as the default isn't a class name:
```
NameError: name 'value' is not defined
```
The easiest fix is either renaming the field or the fieldtype:
```py
class Foo(BaseModel):
    ABar: Bar = "value"
```

I didn't expect that using the same fieldname as fieldtype results in errors on default assignment.

**Comment by evetion** [comment]
Playing with the Enum a bit more, this could be more helpful:

```py
from pydantic import BaseModel
from enum import Enum
from typing import Optional

class Bar(Enum):
    VALUE = "value"

class Foo(BaseModel):
    Bar: Bar = Bar.VALUE

Foo()
```

throws

```
TypeError: issubclass() arg 1 must be a class
During handling of the above exception, another exception occurred:
...[traceback]...
RuntimeError: error checking inheritance of <Bar.VALUE: 'value'> (type: enum)
```

**Comment by samuelcolvin** [comment]
This has been asked before, right now I can't find the issue.

This isn't a limitation of pydantic, but rather of python.

If you do

```py
class Bar:
    pass

class Foo:
    Bar: Bar

print(Foo.__annotations__)
#> {'Bar': <class '__main__.Bar'>}
```
All is well, the annotation of `Foo.Bar` is the class `Bar`.

But if you do

```py
class Bar:
    pass

class Foo:
    Bar: Bar = 1

print(Foo.__annotations__) 
#> {'Bar': 1}
```
`Bar` in the context of the `Foo` definition has been redefined as `1` so now the annotation of `Bar` is itself, e.g. `1`.

Nothing pydantic can do about this I'm afraid.

**Comment by evetion** [comment]
Thanks for the quick reply, quite clear now. 

This is a niche case, but is it something we want to document? Like don't use fieldnames that are the same as their types? Could be a small note somewhere, I could make a PR.
