### ISSUE TITLE
[Question] how does pydantic differ from schema? Is it a good idea for me to use pydantic in this usecase?

### ISSUE THREAD

**Issue by simkimsia** [samuelcolvin/pydantic#1486]
Sorry it's another similar question to #1459 

schema refers to https://github.com/keleshev/schema

I understand that pydantic primary purpose is for parsing and not validation as written [here](https://pydantic-docs.helpmanual.io/usage/models/) 

> pydantic is primarily a parsing library, not a validation library. Validation is a means to an end: building a model which conforms to the types and constraints provided.

In https://www.cosmicpython.com/book/appendix_validation.html#_validating_syntax

it recommends using schema to validate the json data that's meant to be converted into this class called `Allocate`

```python
from schema import And, Schema, Use


@dataclass
class Allocate(Command):

    _schema = Schema({  #(1)
        'orderid': int,
         sku: str,
         qty: And(Use(int), lambda n: n > 0)
     }, ignore_extra_keys=True)

    orderid: str
    sku: str
    qty: int

    @classmethod
    def from_json(cls, data):  #(2)
       data = json.loads(data)
       return cls(**_schema.validate(data))
```

```python
def command(name, **fields):  #(1)
    schema = Schema(And(Use(json.loads), fields), ignore_extra_keys=True)
    cls = make_dataclass(name, fields.keys())  #(2)
    cls.from_json = lambda s: cls(**schema.validate(s))  #(3)
    return cls

def greater_than_zero(x):
    return x > 0

quantity = And(Use(int), greater_than_zero)  #(4)

Allocate = command(  #(5)
    orderid=int,
    sku=str,
    qty=quantity
)

AddStock = command(
    sku=str,
    qty=quantity
```

I feel that actually I can use pydantic to parse the json into the Allocate class instead.

Am I right in my understanding

**Comment by StephenBrown2** [comment]
You can indeed, and Pydantic even has constrained types built in: https://pydantic-docs.helpmanual.io/usage/types/#constrained-types

```py
from pydantic import BaseModel, conint

Allocate(BaseModel):
    orderid: int
    sku: str
    qty: conint(gt=0)

AddStock(BaseModel):
    sku: str
    qty: conint(gt=0)
```

And then you would use it like:
```py
data = Allocate(**json.loads(json_string))
```

If you're using them as function calls, you can use the validate_arguments decorator: https://pydantic-docs.helpmanual.io/usage/validation_decorator/

```py
from pydantic import conint, validate_arguments, ValidationError

@validate_arguments
def allocate(orderid: int, sku: str, qty: conint(gt=0)):
    print(orderid)
    print(sku)
    print(qty)

try:
    a = allocate('hello', 'wrong', 0)
except ValidationError as exc:
    print(exc)
"""
2 validation errors for Allocate
orderid
  value is not a valid integer (type=type_error.integer)
qty
  ensure this value is greater than 0 (type=value_error.number.not_gt; limit_value=0)
"""
```

**Comment by samuelcolvin** [comment]
excellent answer @StephenBrown2, thank you.

**Comment by simkimsia** [comment]
Yes thank you, @StephenBrown2 great answer 👍
