### ISSUE TITLE
`default_factory=` bypasses validation?

### ISSUE THREAD

**Issue by dconathan** [samuelcolvin/pydantic#1488]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: <virtual env>
               python version: 3.7.7 (default, Mar 26 2020, 10:32:53)  [Clang 4.0.1 (tags/RELEASE_401/final)]
                     platform: Darwin-19.4.0-x86_64-i386-64bit
     optional deps. installed: []
...
```

```py
import pydantic

from pydantic import BaseModel, Field


class Test(BaseModel):
    x: int = Field(default_factory=lambda: "hello")

test = Test()

print(type(test.x))
# <class 'str'>

```

This should raise a ValidationError.  Probably at instantiation time since I don't think you can do it at the time of declaring the model without calling the factory.

**Comment by PrettyWood** [comment]
Well default values are not checked by default (see the [doc](https://pydantic-docs.helpmanual.io/usage/validators/#validate-always) for more info)
You could write something like
```python
class Test(BaseModel):
    x: int = 'pika'

test = Test()
```
and it would pass !

You need to add 
```python
    class Config:
        validate_all = True
```
and it will raise the error you want
