### ISSUE TITLE
Mypy type error on PostgresDsn with litteral string assignment

### ISSUE THREAD

**Issue by kdorsel** [samuelcolvin/pydantic#1490]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /.../venv38/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Mar 11 2020, 00:29:50)  [Clang 11.0.0 (clang-1100.0.33.17)]
                     platform: macOS-10.15.4-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
from pydantic import BaseSettings, PostgresDsn

class Cfg(BaseSettings):
    pg_dsn: PostgresDsn = "postgresql://user:password@localhost:5432/test"
    pg_min_size: int = 2
    pg_max_size: int = 10
```

Checking with Mypy gives the following error.

```
app/config.py:5: error: Incompatible types in assignment (expression has type "str", variable has type "PostgresDsn")
```

I'm assuming the other Dsn type definitions have the same issue, and `AnyUrl` would also.

Unfortunately I'm not familiar enough with typing extensions to hunt this down, but if you give me direction I can look into it.

**Comment by cbows** [comment]
I can confirm this also happens with `EmailStr`. I tried to disable `init_typed` (see [docs](https://pydantic-docs.helpmanual.io/mypy_plugin/#plugin-settings)), but errors remain.

**Comment by samuelcolvin** [comment]
`init_typed` relates to initialising the model, so is not related.

The best solution for you is probably to use:

```py
if TYPE_CHECKING:
    PostgresDsn = str
else:
    from pydantic import PostgresDsn
```

We could modify `networks.py` to make this the default, but it would mean `pg_dsn.password` and access to all other attributes would cause an error in static type analysis.

`EmailStr` really can be changed in `networks.py` to

```py
if TYPE_CHECKING:
    EmailStr = str
else:
    class EmailStr(str):
        ...
```
PR welcome for this.

---

Long term I guess it might be possible to extend the mypy plugin fix this, but that would require a lot of work and defining a master list of type equivalencies which would be quite a lot of work, see  https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/36 and #1055
