### ISSUE TITLE
Add datamodel-code-generator link in pydantic document site.

### ISSUE THREAD

**Issue by koxudaxi** [samuelcolvin/pydantic#1500]
# Question

@samuelcolvin 
I want to add a link of `datamodel-code-generator` to the pydnatic document site. 
Where should I put the link?

link:
https://github.com/koxudaxi/datamodel-code-generator
https://koxudaxi.github.io/datamodel-code-generator/

## Related issues
https://github.com/samuelcolvin/pydantic/issues/643
https://github.com/samuelcolvin/pydantic/issues/1452

**Comment by samuelcolvin** [comment]
Yes, great.

I would put it under the pycharm plugin.

Maybe one day we'll need a new sub-menu with add-ons, plugins and extensions. But for now a new item in the main menu is fine.

Thanks so much.

**Comment by koxudaxi** [comment]
@samuelcolvin 

Thank you very much :smile:
