### ISSUE TITLE
mypy reporting incorrect shape of parent class dict when using pydantic plugin

### ISSUE THREAD

**Issue by Code0x58** [samuelcolvin/pydantic#1515]
# Bug
Encountered with pydantic 1.5.1 (latest) and mypy 0.770 (latest) with the pdantic plugin enabeld.

Code to reproduce:
```py
import pydantic

class Parent(pydantic.BaseModel):
  a: int = 1

class Child(Parent):
  b: int = 2

# mypy flags error: "Child" gets multiple values for keyword argument "b"
Child(**Parent().dict(), b=3)
```

**Comment by samuelcolvin** [comment]
This has nothing to do with the mypy pydantic plugin (other than that mypy now knows what fields `__init__` takes)

You get the same error with

```py
import pydantic

class Parent(pydantic.BaseModel):
    a: int = 1

class Child(Parent):
    b: int = 2

def foo(*, a: int, b: int) -> None:
    pass

foo(**Parent().dict(), b=3)
```
without the mypy pydantic plugin enabled.

AFAIK this is how how mypy is, it doesn't know anything about the dictionary returned by `.dict()` so it assumes the worst - e.g. that it might include a key `'b'`.

It might be possible to extend the the mypy plugin to customise what mypy assumes `.dict()` returns to be a `TypedDict` - if you're interested in working on that I'd happily review a PR.

**Comment by hillairet** [comment]
@Code0x58 
Did you try this?
```python
Child(b=3, **Parent().dict())
```

Makes mypy happy for me!
