### ISSUE TITLE
Pydantic to ORM

### ISSUE THREAD

**Issue by David-Lor** [samuelcolvin/pydantic#1522]
When working with Pydantic + ORM (like SQLAlchemy) we have the option to "convert" an ORM object to Pydantic model, using the `from_orm` method. But could we have the inverse method?

I managed to do this:

```python
from pydantic import BaseModel as _BaseModel
from sqlalchemy.ext.declarative import declarative_base

ORMBase = declarative_base()


class BaseModel(_BaseModel):
    class Config:
        orm_mode = True
        orm_model = None # this can be set to the class of ORM model

    def to_orm(self):
        if not self.Config.orm_model:
            raise AttributeError("Class has not defined Config.orm_model")
        return self.Config.orm_model(**self.dict())

class PersonORM(ORMBase):
    __tablename__ = "people"
    person_name = Column(String(255), primary_key=True)

class PersonModel(BaseModel):
    person_name: str

    class Config(BaseModel.Config):
        orm_model = PersonORM
```

Now, when having an instance of PersonModel (pydantic model), I can obtain the ORM model by calling the to_orm() method.

I could try to create a PR if this seems interesting - unless there's already some existing way to do this that I'm not aware of.

**Comment by samuelcolvin** [comment]
Surely you can use something like `PersonORM(**dict(person_model))`?

I don't think this needs to be part of pydantic and it will vary a lot on a case by case basis. Better that you define your own `CustomBaseModel` and define the method on there.

**Comment by jonas-eschle** [comment]
Can we maybe reopen this? Unfortunately it's not that simple: nested objects. `person_model` does not contain any objects and the logic is non-trivial and needs pydantic internal knowledge, namely which constructor to use.

Say we have a `Person` that can have `Pets` (there are a few examples in the docs with all the difficulties such as Unions). The serialization is there but the way back is non-trivial.

Actually, I was quite surprised to find that it's not in pydantic, i.e. that pydantic doesn't support object<->json serialization, but just one way.

What do you think of adding this feature? I am aware that it needs a bit more logic but it would leverage pydantic from a "data serialization" library to a marshallization library a la marshmellow

**Comment by samuelcolvin** [comment]
I'm not really sure what you're asking for. Could you clarify?

The are a lot of changes coming in this regard in v2, e g. we have `from_attributes` already implemented in pydantic-core.

On the serialization side, there's #4456.

**Comment by jonas-eschle** [comment]
Sure, for example the following. Using real-world examples, we cannot just make our actual classes pydantic models but they serve just for the purpose of serialization. The goal is to have obj <-> json (or other serialization)
```
class Person:
    def __init__(self, pets):
        self.pets = pets
        
 class Pet:
     def __init__(self, age):
         self.age = age
 
class PetModel(BaseModel):
    age: float 

class PersonModel(BaseModel):
    pets: list[PetModel]
```
We can create a model from the class and dump it, but we can't recreate the other model, i.e.

```
pet1 = Pet(42)
pet2 = Pet(24)
person1 = Person([pet1, pet2])

person1_model = PersonModel.from_orm(person1)  # obj -> model 
person1_json = person1_model.json()  # model -> json (or other serialization-like format)
person1_model = PersonModel.from_raw(person1_json)  # json -> model
person1 = person1_model.to_orm()  # MISSING: model -> person
```

The last part is the missing link in the chain and it's non-trivial, we cannot simply do
```
person1 = Person(**person1_model.dict())
```
because `Person` expects a list of `Pet`, not a list of dicts , with the latter being something like
```
person1_model.dict() -> {'pets': [{'age': 42}, {'age': 24}]
```

(and there are more complications, we cannot simply traverse down, i.e. when we have a union of different pets etc)

AFAIU from the links, this is not considered to be implemented so far?

**Comment by microHoffman** [comment]
Today I was wondering if there exists something like this in `pydantic`, for similar reasons that @jonas-eschle has written down. cc: @samuelcolvin

**Comment by riotsnotdiets** [comment]
Today I was wondering about the very same thing @David-Lor, @jonas-eschle and @microHoffman were wondering about :)

**Comment by rrluthi** [comment]
I was looking at this over the weekend for my own project, and found this one which I haven't tried yet but will take a look at more in-depth today: https://github.com/Wouterkoorn/sqlalchemy-pydantic-orm

**Comment by nsaccente** [comment]
I'm encountering a need for this myself. I don't want have to define an ORM for both ways, it seems unnatuarl.
