### ISSUE TITLE
BaseSettings what takes precedence when both an initial value and an env value exist?

### ISSUE THREAD

**Issue by ricardogsilva** [samuelcolvin/pydantic#1524]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: False
                 install path: /home/ricardo/dev/pydantic/pydantic
               python version: 3.8.2 (default, Apr 27 2020, 15:53:34)  [GCC 9.3.0]
                     platform: Linux-5.4.0-29-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions', 'email-validator', 'devtools']

```

While working on #1279, when validating tests, I stumbled upon something which seems wierd to me. There are two tests that seem to be contradictory. They are located in `tests/test_settings.py` and are:

1. `test_sub_env_override(env)` - This test seems to make sure that a value passed via `BaseSettings.__init__` overrides the corresponding environment variable. To my understanding this is also in line with the pydantic documentation on what the expected behavior should be

2. `test_env_takes_precedence(env)` - This test seems to make sure that a value supplied via environment overrides a value passed via `BaseSettings.__init__` - i.e. the exact opposite of the previous point. This test is also wierdly redefining `BaseSettings._build_values` in the test function, which seems odd to me.

Are both these tests correct?

**Comment by samuelcolvin** [comment]
They're both correct, as you can see in`test_env_takes_precedence`, `_build_values` has been overridden to change the logic so env vars take precidence.

In general, settings values take the following priority (first is highest priority):
1. arguments to `__init__`
2. environment variables
3. values defined in `.env` files
4. defaults in the class definition
