### ISSUE TITLE
Pydantic in a Podcast

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#1534]
I was a guest on podcast Tobias Macey's `Podcast.__init__`, you might be interest to have a listen.

### https://www.pythonpodcast.com/pydantic-data-validation-episode-263/

I'm afraid I wasn't very articulate, so if you have any questions on what I was rambling about; feel free to create issues to discuss them.

I mentioned a few bigger ideas I have for v2, I'll try and add issues for those things over the next few days.

**Comment by simkimsia** [comment]
Have you been on mike kennedy’s talk python podcast by any chance? I listen to that quite frequently

**Comment by tiangolo** [comment]
I think that was great :smile: 

Although I know the feeling of hearing your own voice recorded saying stuff and not liking it :shrug: But yeah, I think that was great. :tada:
