### ISSUE TITLE
Dynamically creating a field? 

### ISSUE THREAD

**Issue by brdhunga** [samuelcolvin/pydantic#1535]
If i have a class like:
```
class Geometry(BaseModel):
    x: int
    y: int 
    z: int
```

And there is a class that wraps the above as a type
```
class Plane(BaseModel):
    abc: Geometry
    xyz: Geometry
```

However, the `abc` and `xyz` are dynamically generated and there might be 100s of them. 

Is there an easier way to do this, or do I have to iterate over key value pairs and dynamically create  ModelFields ?

If I am creating assigning a ModelField dynamically, is there a place where I can see an example? thanks

**Comment by PrettyWood** [comment]
Hi @brdhunga ,
Have you checked the doc about [dynamic model creation](https://pydantic-docs.helpmanual.io/usage/models/#dynamic-model-creation) ?

You could do something like
```python
from pydantic import BaseModel, create_model

class Geometry(BaseModel):
    x: int
    y: int
    z: int

kw = {
    'abc': {'x': 1, 'y': 2, 'z': 3},
    'def': {'x': 4, 'y': 5, 'z': 6},
    'xyz': {'x': 7, 'y': 8, 'z': 9},
}

fields = {
    field_name: (Geometry, ...)
    for field_name in kw.keys()
}

Plane = create_model('Plane', **fields)

Plane()
# abc
#   field required (type=value_error.missing)
# def
#   field required (type=value_error.missing)
# xyz
#   field required (type=value_error.missing)
```
But I wonder why you would do that instead of having one single field `List[Geometry]`
