### ISSUE TITLE
dataclass field with a class as a default value can't be set

### ISSUE THREAD

**Issue by rshin** [samuelcolvin/pydantic#1537]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: <redacted>/lib/python3.7/site-packages/pydantic
               python version: 3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:36:57)  [Clang 9.0.0 (tags/RELEASE_900/final)]
                     platform: Darwin-19.4.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
import collections
import dataclasses
from typing import Any

from pydantic.dataclasses import dataclass


class Sentinel:
    pass


@dataclass
class X:
    f: Any = Sentinel


x = X(3)
print(x)
```
outputs
```
X(f=<class '__main__.Sentinel'>)
```
in other words, the default value for `x.f` isn't being overridden even though it's being explicitly provided as an argument to `X`.

The same behavior seems to happen for any class put in place of `Sentinel`, such as `list` or `type`.

**Comment by PrettyWood** [comment]
Hello @rshin,
the issue comes from [this line](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/main.py#L261), which prevents _pydantic_ to generate the right signature.
An easy workaround with `BaseModel` would be to set `f: Any = Field(Sentinel)`, but for dataclasses it won't work
