### ISSUE TITLE
when nested dataclass has config it is not respected

### ISSUE THREAD

**Issue by molaxx** [samuelcolvin/pydantic#1556]
# Bug
Nested has an alias_generator to_camel, and `allow_population_by_field_name = True`.
when parsing an object with alias key I encounter an exception:

E           pydantic.error_wrappers.ValidationError: 1 validation error for Outer
E           n
E             __init__() got an unexpected keyword argument 'NumBer' (type=type_error)

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:

```
             pydantic version: 1.5.1
            pydantic compiled: False
                 install path: /home/elil/Code/pydantic/pydantic
               python version: 3.8.0 (default, Oct 28 2019, 16:14:01)  [GCC 9.2.1 20191008]
                     platform: Linux-5.3.0-51-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']

```

```py
import pydantic
def to_camel(string: str) -> str:
    return "".join(word.capitalize() for word in string.split("_"))


def test_nested_dataclass_with_config():
    class Config:
        allow_population_by_field_name = True
        alias_generator = to_camel

    @pydantic.dataclasses.dataclass
    class Nested:
        num_ber: int

    @pydantic.dataclasses.dataclass
    class Outer:
        n: Nested

    assert Outer.__pydantic_model__.parse_obj({"n":{"NumBer":1}}).n == 1
```

**Comment by samuelcolvin** [comment]
This is not related to nesting.

It's a fundamental limitation of dataclasses, see the note [here](https://pydantic-docs.helpmanual.io/usage/dataclasses/_
