### ISSUE TITLE
Union[a,b] is ordered and yields incorrect results.

### ISSUE THREAD

**Issue by jorgecarleitao** [samuelcolvin/pydantic#1558]
# Bug

```
pydantic version: 1.4
            pydantic compiled: False
                 install path: .../venv/lib/python3.7/site-packages/pydantic
               python version: 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52)  [Clang 6.0 (clang-600.0.57)]
                     platform: Darwin-19.3.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

MWE:

```py
import pydantic
import typing


class B(pydantic.BaseModel):
    a: typing.Union[float, str]


class B1(pydantic.BaseModel):
    a: typing.Union[str, float]


print((B(a=1).a == 1, B(a='1').a == '1'))
print((B1(a=1).a == 1, B1(a='1').a == '1'))
assert (
    (B(a=1).a == 1 and B(a='1').a == '1') or
    (B1(a=1).a == 1 and B1(a='1').a == '1')
)
```
this fails and prints

```
(True, False)
(False, True)
```

More generally, given two types `a` and `b` and two values `a1` and `b1` that both can be casted to types `a` or `b`, there is no way to declare that when `a1` is of type `a` and `b1` of type `b`, they should remain in their original type. Instead, pydantic automatically casts the value to the first type of the `Union[a,b]`. This makes "Union" not to really a Union, but more like an "OrderedUnion".

This is relevant when a (fast) API can return either of these on the endpoint, but their types should be the types passed to the data model, i.e. pydantic is actually creating the problem (by casting), not helping.

IMO, when a given type fulfills any of the conditions of the `Union`, it should pass through without being modified. The current behavior should not be present in a `Union`, but in a separate composite type (e.g. `OrderedUnion[]`).

**Comment by samuelcolvin** [comment]
Thanks for the issue, this is a known problem.

See #1423 and #619.
