### ISSUE TITLE
mypy: invalid type comment or annotation

### ISSUE THREAD

**Issue by Gr1N** [samuelcolvin/pydantic#156]
Hi,

I think this issue related more to `mypy`, but maybe you know about any workaround or how to solve this. 

Here is my code:
```
class Test(BaseModel):
    k: constr(min_length=2)
```

And when I run `mypy` I got:
```
error: invalid type comment or annotation
note: Suggestion: use constr[...] instead of constr(...)
```

Any ideas?

**Comment by samuelcolvin** [comment]
Afraid I don't know how to fix this. 

Might be possible to modify constr to `[]`. 

Will look when I have a chance of you're welcome to submit a pr.

**Comment by Gr1N** [comment]
I will try to find solution too.

**Comment by samuelcolvin** [comment]
Should be possible. 

https://www.python.org/dev/peps/pep-0472/

**Comment by samuelcolvin** [comment]
Sadly since pep 472 was never implemented and keyword arguments to `__getitem__` are not permitted this is not possible.

Even the works arounds suggested in pep472 `foobar[{'min_length': 123}]` or `foobar['min_length':123]` are both syntax errors in mypy so they're not an option.

I'm closing this but happy to come back to it if anyone has a bright idea.

**Comment by nandoflorestan** [comment]
I am running into the same issue. We cannot just shrug this off because adding `# type: ignore` to the end of the field line does not make the mypy warning go away. In fact, I only got the mypy warning to go away by not using `constr` at all.

This difficulty must be mentioned in the documentation.

**Comment by Gr1N** [comment]
For me I found simple solution how to use `constr` without `mypy` warnings. Look at example below:
```
UserName = constr(max_length=255, strip_whitespace=True)

class User(BaseModel):
    name: UserName
```

Also using this approach you can share your validation types, for example, between engineers in your company.

**Comment by nandoflorestan** [comment]
@Gr1N nice idea, thank you!

But now I get `error: Invalid type "keepluggable.orchestrator.AtLeastOneChar"`

Here's my code:

    AtLeastOneChar = constr(min_length=1, strip_whitespace=True)


    class Configuration(BaseModel):

        name:  AtLeastOneChar = Required

The error is on the last line.

**Comment by nandoflorestan** [comment]
@Gr1N That did it, thanks!

The final line is simply

    AtLeastOneChar: constr = constr(min_length=1, strip_whitespace=True)

**Comment by Gr1N** [comment]
@nandoflorestan you're welcome :)

**Comment by javiertejero** [comment]
@nandoflorestan @Gr1N that does not look correct, and in fact only works because you probably run `mypy --follow-imports=skip`, if you run `mypy` this would be the output

```
error: Function "pydantic.types.constr" is not valid as a type
note: Perhaps you need "Callable[...]" or a callback protocol?
```

**Comment by brendanlong** [comment]
For future people who find this issue, in v1 you can use `Field` for this:

```
class User(BaseModel):
    name: str = Field(str, max_length=255, strip_whitespace=True)
```

**Comment by m-laniakea** [comment]
The above is not quite right as well, because the first parameter to `Field` is the default value. 
In this case the default would be the *type* `str`, which is not a `str`.

Another possible issue is that a default value was supplied, making this field optional.

Updated example:
```python
class User(BaseModel):
    name: str = Field('Default name', max_length=255, strip_whitespace=True)
```
If you want to make the field a **Required** field,
use an ellipsis:
```python
class User(BaseModel):
    name: str = Field(..., max_length=255, strip_whitespace=True)
```
Something like `required=True` would feel more natural, but that's not an option as of v1.4.
Please be aware that supplying a default of `None` is not the same as supplying no default value.

**Comment by tuukkamustonen** [comment]
So, if the way to do it is:

```py
name: <type> = Field(...)
```

...then how can you use strict types? `Field()` doesn't support `strict=` and if you try to:

```py
class User(BaseModel):
    name: StrictStr = Field(..., max_length=2)
```

You'll get:

```
ValueError: On field "foo" the following field constraints are set but not enforced: max_length. 
For more details see https://pydantic-docs.helpmanual.io/usage/schema/#unenforced-field-constraints
```

**Comment by PrettyWood** [comment]
`Field(..., max_length=2)` is just useful for the schema.
You should do 
```py
class User(BaseModel):
    name: constr(max_length=2)
```
or create a custom class
```py
class Name(StrictStr):
    max_length = 2

class User(BaseModel):
    name: Name
```
For more info check out the [doc](https://pydantic-docs.helpmanual.io/usage/types/#constrained-types)
Hope it helps

**Comment by tuukkamustonen** [comment]
> ```python
> class User(BaseModel):
>     name: constr(max_length=2)
> ```

But exatly this gives the mypy error.

> Or create a custom class
> 
> ```python
> class Name(StrictStr):
>     max_length = 2
> 
> class User(BaseModel):
>     name: Name
> ```

That's pretty verbose. Lots of "wasted" characters, surely there's some more compact way?

> For more info check out the [doc](https://pydantic-docs.helpmanual.io/usage/types/#constrained-types)

Yeah, I've read those, but I think they miss this one. For example, there's no similar example than what you just pasted (setting `max_length` in sub-class).

**Comment by PrettyWood** [comment]
> But exactly this one gives the mypy error.

> That's pretty verbose. Lots of "wasted" characters, surely there's a more compact way?

@tuukkamustonen You're welcome to implement a `mypy` friendly version. I'd be more than happy to review it

**Comment by tuukkamustonen** [comment]
Is there a reason why `Field(..., strict=True)` is not supported? Wouldn't that do it?

**Comment by alecgerona** [comment]
To anyone still running into this, `# type: ignore` now works. Its error code if you want to be pedantic (heh) is `valid-type`. The specific usage would be `# type: ignore["valid-type"]`.

**Comment by nandoflorestan** [comment]
To anyone thinking the meaning of the comment above is hard to discern: that doesn't fix the incompatibility between pedantic and mypy -- it just restricts the errors that mypy will ignore on that line.
https://mypy.readthedocs.io/en/stable/error_codes.html#error-codes

**Comment by alecgerona** [comment]
Yes. My comment was in response to:

> I am running into the same issue. We cannot just shrug this off because adding # type: ignore to the end of the field line does not make the mypy warning go away. In fact, I only got the mypy warning to go away by not using constr at all.

**Comment by mehmetsan** [comment]
I am facing the same issue, however I don't believe I can use Field instead, as my field needs to be condecimal.

```
class User(BaseModel):
    money: condecimal(decimal_places=2)
    name : str = Field(max_length=10)
```
Does anybody have any idea for that?

**Comment by alecgerona** [comment]
@mehmetsan you mean `# type: ignore` is not doing it for you? Mypy is still complaining?

**Comment by mehmetsan** [comment]
Yes, it does work. But I just wanted to know if there was a more robust or appropriate way to do it. I am working on a rather large project and I didn't want to use `# type: ignore` excessively on several lines in different files.

**Comment by alecgerona** [comment]
Ah yes. Like PrettyWood said. Waiting on a PR :D

**Comment by PrettyWood** [comment]
I think now it should be better with `Annotated` that is `mypy` compliant
So with author example
```py
class Test(BaseModel):
    k: constr(min_length=2)
```
becomes
```py
class Test(BaseModel):
    k: Annotated[str, Field(min_length=2)]
```

**Comment by nandoflorestan** [comment]
Aha, now that does look good.  Here is the [PEP explaining Annotated](https://www.python.org/dev/peps/pep-0593/)

**Comment by mattzque** [comment]
This should be mentioned in the documentation:

https://pydantic-docs.helpmanual.io/usage/types/#constrained-types

is incompatible with mypy at the moment

**Comment by lesnik512** [comment]
Another approach is to inherit from ConstrainedStr:

```python
class AtLeastOneChar(ConstrainedStr):
    min_length = 1
    strip_whitespace = True

```

**Comment by hiboo** [comment]
> Another approach is to inherit from ConstrainedStr:
> 
> ```python
> class AtLeastOneChar(ConstrainedStr):
>     min_length = 1
>     strip_whitespace = True
> 
> class Item(BaseModel):
>     field: AtLeastOneChar
>     list_field: List[AtLeastOneChar]
> ```

This totally works when using with Pylance (no warnings nor type errors), thanks!

**Comment by tuukkamustonen** [comment]
Even with `Annotated[]` now supported, defining strict fields with validation "inline" is still not possible:

```py
class Item(BaseModel):
    field: Annotated[StrictStr, Field(min_length=5))  # will throw as StrictStr overrides constraints from Field
    field: StrictStr = Field(min_length=5)  # is same as this, really, and throws for the same reason
```

The workaround of:

```py
class Name(StrictStr):
    max_length = 2

class Item(BaseModel):
    field: Name
```

...is not so great, as it's so verbose.

`StrictStr` now inherits from `ConstrainedStr` which supports validators, and for that reason `field: Constrained* = Field(...validators...)` are not supported.

However, what if `Strict*` did not inherit from `Constrained*` classes and were simply:

```py
class StrictStr(str):
    strict = True
```

In this case, you would _need to_ define the validators via `Field()`:

```py
class Item(BaseModel):
    field: StrictStr = Field(min_length=5)
```

But I guess that would be too limited, as `Constrained*` classes do more than duplicate JSON schema validators (like `constr(strip_whitespace=True, curtail_length=10)`) and you would lose those.

**Comment by phillipuniverse** [comment]
Came across this from Google, in Python 3.9+ this can be solved with `Annotated`:

```python
class Item(BaseModel):
    field: Annotated[str, constr(strict=True, max_length=2), Field(description='Really cool field')]
```

**Comment by skrech** [comment]
> Came across this from Google, in Python 3.9+ this can be solved with [`Annotated`](https://www.python.org/dev/peps/pep-0593/):
> 
> ```python
> class Item(BaseModel):
>     field: Annotated[str, constr(strict=True, max_length=2), Field(description='Really cool field')]
> ```

This doesn't work -- `constr` constraints are not applied.  max_length is neither in schema of `Item` nor during  runtime/parsing (eg. `field` can be longer then 2).

**Comment by ShadowLNC** [comment]
Now that we have Annotated available, should this ticket be reopened?

[This part of the Pydantic docs](https://pydantic-docs.helpmanual.io/usage/types/#constrained-types) suggests the example should work "as is" and I would expect that to include type checking (I got this issue when trying it).

**Comment by alejandraklachquin** [comment]
Using Annotated for restrained decimals as `price: Annotated[Decimal, Field(gt=Decimal("0.00"), decimal_places=2)` with fastapi on 0.75.2 , Python 3.9.*  and pydantic on 1.9.0 -> **works**! Swagger shows correct doc and validation is happening on runtime. No bypass needed now. 
Thanks!

**Comment by tuukkamustonen** [comment]
Unless something has changed, strict fields are still not supported. I don't have a project at hand right now, but if someone wants to test, try this:

```py
class Item(BaseModel):
    field: Annotated[StrictStr, Field(min_length=5))  # will throw as StrictStr overrides constraints from Field
```

**Comment by andylamp** [comment]
Why is this issue closed? From my understanding the typing behavior with `mypy` is still not fixed - or am I misunderstanding something?

**Comment by romatt** [comment]
For anyone who is stumbling across this issue: With Pydantic 2 its recommended to replace `conlist` with an annotated list:
```
from typing import Annotated
from annotated_types import Len
from pydantic import BaseModel

class Foo(BaseModel):
  my_list: Annotated[list[str], Len(min_length=1)]
```

Sources:
https://stackoverflow.com/questions/61468548/check-if-list-is-not-empty-with-pydantic-in-an-elegant-way
https://docs.pydantic.dev/2.6/concepts/types/#generics
