### ISSUE TITLE
Troubles with partially updating

### ISSUE THREAD

**Issue by Dogrtt** [samuelcolvin/pydantic#1563]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.5.1
            pydantic compiled: True
                 install path: F:\PyProj\RevitJsonService\venv\Lib\site-packages\pydantic
               python version: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
                     platform: Windows-10-10.0.18362-SP0
     optional deps. installed: []

```
Hi guys. I got some troubles with partially updating. Let's say we have model `Item` with list of nested models `Embedded` with required fields. Also we have two additional models (`EmbeddedInUpdate`, `ItemInUpdate`) for partially updating with `Optional` fields. If I try to update nested model by partial information, I faced with situation when object returned after `x.copy(update=y)` operation doesn't fit to model conditions. I created example to illustrate what I'm talking about :
```py
from typing import List, Optional

from pydantic import BaseModel
from pydantic.types import StrictInt

db_item = {'C': 1,
           'D': [{
               'A': 2,
               'B': [3, 4]
           }]}


class Embedded(BaseModel):
    A: StrictInt
    B: List[StrictInt]


class Item(BaseModel):
    C: StrictInt
    D: List[Embedded]


class EmbeddedInUpdate(BaseModel):
    A: Optional[StrictInt]
    B: Optional[List[StrictInt]]


class ItemInUpdate(BaseModel):
    C: Optional[StrictInt]
    D: Optional[List[EmbeddedInUpdate]]


def update_item(item: ItemInUpdate) -> Item:
    existed_item = Item(**db_item)
    updated_fields_only = item.dict(exclude_unset=True, exclude_none=True)
    updated_item = existed_item.copy(update=updated_fields_only)
    return updated_item


if __name__ == "__main__":
    updates = ItemInUpdate(D=[EmbeddedInUpdate(A=StrictInt(42))])
    print(update_item(updates))
```
Here, in updated_item variable we got Item object with invalid Embedded object inside. How can I recursively update nested objects partially?

**Comment by Dogrtt** [comment]
Issue #418 explain why invalid data passed validation, but I still have no any idea what to do.

**Comment by samuelcolvin** [comment]
Better to use `validate_model()` directly, then construct the model, rather than using two different models.

Something like [this](https://github.com/samuelcolvin/aiohttp-toolbox/blob/94289388bd1f28e6592d311a019b1d054f3f1872/atoolbox/utils.py#L95-L101), note: that might be for a slightly old version of pydantic.
