### ISSUE TITLE
Support serializing OrderedDict as list of lists

### ISSUE THREAD

**Issue by saulshanabrook** [samuelcolvin/pydantic#1572]
It would be helpful if we could serialize ordereddict's as a list of lists in JSON, so that the ordering semantics are preserved. 

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /usr/local/Caskroom/miniconda/base/envs/python-record-api/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 | packaged by conda-forge | (default, Apr 16 2020, 17:20:38)  [Clang 9.0.1 ]
                     platform: macOS-10.15.4-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']

```

```py
import pydantic
import collections
import typing

class M(pydantic.BaseModel):
    o: collections.OrderedDict

print(M(o=[(1, 2)]).json())
# {"o": {"1": 2}}
```

**Comment by samuelcolvin** [comment]
(corrected the title)

---

I disagree with changing this, the natural JSON representation of an ordered dict, is a dict (ordered correctly) - it's then up to the JSON deserialisation library to preserve order if you care about it.

If you really want to do this, you can implement your own method and alter `config. json_dumps`.

**Comment by saulshanabrook** [comment]
FYI, you probably already know this, but the [JSON spec](https://tools.ietf.org/html/rfc7159#section-4) says that objects are unordered:

>    An object is an unordered collection of zero or more name/value
>   pairs, where a name is a string and a value is a string, number,
>   boolean, null, object, or array.

>    JSON parsing libraries have been observed to differ as to whether or
>   not they make the ordering of object members visible to calling
>   software.  Implementations whose behavior does not depend on member
>   ordering will be interoperable in the sense that they will not be
>   affected by these differences.

**Comment by samuelcolvin** [comment]
fine but both javascript (where the "J" of JSON comes from) and python - the two most popular languages, maintain keep order in objects - so I think serialising `OrderedDict` to `object` is correct.

**Comment by encukou** [comment]
Javascript doesn't *always* keep the order. Integer keys come first, in numeric order:
```
Welcome to Node.js v16.13.2.
Type ".help" for more information.
> {"01": "one", "3": "three", "2": "two"}
{ '2': 'two', '3': 'three', '01': 'one' }
```
