### ISSUE TITLE
Correct use of @property setter for a field

### ISSUE THREAD

**Issue by umesh-timalsina** [samuelcolvin/pydantic#1577]
# Question
I don't know if this justifies the use of `pydantic` here's what I want to use `pydantic` for:
1. Use a set of Fileds for internal use and expose them via `@property` decorators
2. Set the value of the fields from the `@property` setters. But since the `BaseModel` has an implementation for `__setattr__`, using setters for a `@property` doesn't work for me. 

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.5.1
pydantic compiled: True
install path: /path/to/conda-env/lib/python3.7/site-packages/pydantic
python version: 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:33:48)  [GCC 7.3.0]
platform: Linux-5.0.0-32-generic-x86_64-with-debian-buster-sid
optional deps. installed: []
```

```py
from pydantic import BaseModel

class DemoClassWithInternalFields(BaseModel):
    """Class with internal Fields"""
    field1_: str = 'DefaultValueForFieldOne'
    field2_: int = 0
        
    @property
    def field1(self):
        return self.field1_
    
    @property
    def field2(self):
        return self.field2_
    
    @field1.setter
    def field1(self, new_val):
        self.field1_ = new_val
    
    @field2.setter
    def field2(self, new_val):
        self.field2_ = new_val
    
    class Config:
        fields = {
            'field1_': 'field1',
            'field2_': 'field2'
        }
```
```py
>>> obj1 = DemoClassWithInternalFields(field1='ConstructedValue', field2=10)
>>> obj1.field2 = 19  #Doesn't work

site-packages/pydantic/main.cpython-37m-x86_64-linux-gnu.so in pydantic.main.BaseModel.__setattr__()

ValueError: "DemoClassWithInternalFields" object has no field "field2"
```
The workaround I have comeup with is to modify the `__setattr__` method with an extended config like as shown below:
```py
from pydantic import BaseModel

class DemoClassWithPropertySetters(BaseModel):
    """Class with internal Fields exposed as Properties"""
    field1_: str = 'DefaultValueForFieldOne'
    field2_: int = 0
        
    @property
    def field1(self):
        return self.field1_
    
    @property
    def field2(self):
        return self.field2_
    
    def __setattr__(self, key, val):
        if key in self.__config__.alias_to_fields:
            key = self.__config__.alias_to_fields[key]
        super().__setattr__(key, val)
    
    class Config:
        fields = {
            'field1_': 'field1',
            'field2_': 'field2'
        }
        
        alias_to_fields = {
            'field1': 'field1_',
            'field2': 'field2_'
        }
```
```py
>>> obj2 = DemoClassWithPropertySetters(field1='ConstructedValue', field2=10)
>>> obj2.field2 = 11   # This works
>>> obj2.dict(by_alias=True)
{'field1': 'ConstructedValue', 'field2': 11}
```
Questions that stem from this are as follows:
1. Is there a better workaround for this?
2. What is the best way to expose and set values for a Field via `@properties`?

**Comment by samuelcolvin** [comment]
I don't see why you need properties and setters? why not just normal fields?

**Comment by umesh-timalsina** [comment]
Yeah, you could use just fields there was some way of setting field value by aliases. 
May be I am missing something but I wanted a way to perform validation internally and use it as a class attribute. 

This implementation is done here for example. The field `masses_` is used via decorated `@property` like as shown in the second snippet. It would be nice to have this feature work for `property` setters as well. 

https://github.com/MolSSI/QCElemental/blob/846928c80b686e88f2ffc9c3375195db0394f865/qcelemental/models/molecule.py#L147-L154

https://github.com/MolSSI/QCElemental/blob/846928c80b686e88f2ffc9c3375195db0394f865/qcelemental/models/molecule.py#L360-L365

**Comment by samuelcolvin** [comment]
The solution might be computed fields https://github.com/samuelcolvin/pydantic/issues/935#issuecomment-555036039.
They're not that well explained, but I'm hoping to work on them soon.

**Comment by adamal** [comment]
> I don't see why you need properties and setters?

The [`property()`-function](https://docs.python.org/3/library/functions.html#property) is a built-in. 
If a library breaks built-in functionality, is that not almost by definition a bug?

**Comment by nikita-davydov** [comment]
To use property setters and getters use this patch for `BaseModel`

```py
class PatchedModel(BaseModel):
    @no_type_check
    def __setattr__(self, name, value):
        """
        To be able to use properties with setters
        """
        try:
            super().__setattr__(name, value)
        except ValueError as e:
            setters = inspect.getmembers(
                self.__class__,
                predicate=lambda x: isinstance(x, property) and x.fset is not None
            )
            for setter_name, func in setters:
                if setter_name == name:
                    object.__setattr__(self, name, value)
                    break
            else:
                raise e
```

**Comment by gusutabopb** [comment]
When using private attributes which need to be set from outside the class that holds them, not being able to use setters is pretty bad. As pointed out above, I believe breaking language built-in functionality should be considered a bug. 

Instead of overriding `BaseModel.__setattr__` I found it easier to just use an explicit setter function:

```python
from pydantic import BaseModel
from starlette.websockets import WebSocket

class WSConnection(BaseModel):
    host: str
    msg_count: int = 0
    _ws: WebSocket = None
           
    @property
    def ws(self):
        return self._ws
    
    # @ws.setter will not work. See github.com/samuelcolvin/pydantic/issues/1577
    def set_ws(self, ws):
        self._ws = ws

    class Config:
        underscore_attrs_are_private = True
        extra = "forbid"
        
        
ws = WebSocket({"type": "websocket"}, lambda x: x, lambda x: x)   # dummy object
con = WSConnection(host="foo")
con.set_ws(ws)
assert con.ws
```

Some context: I have a simple API (built with FastAPI) that provides and I want to be able to provide an admin endpoint to check basic stats of the WS endpoint usage (`host` and `msg_count` in the example above). Such stats are kept in the wrapper above and returned.

**Comment by tigrus** [comment]
> I found it easier to just use an explicit setter function

Yep, but you still don't have property setter with this approach. When you heavy rely on them and have them in client's code - it's a problem.

**Comment by zulrang** [comment]
> To use property setters and getters use this patch for `BaseModel`

Fantastic!  This should be rolled into the BaseModel, imo

**Comment by wangzyon** [comment]
property and set property
```
class A(BaseModel):

    value: int = 1

    @property
    def coords(self):
        return self.value

    def set_coords(self, value):
        self.value = value

    def __setattr__(self, key, val):
        method = self.__config__.property_set_methods.get(key)
        if method is None:
            super().__setattr__(key, val)
        else:
            getattr(self, method)(val)

    class Config:
        property_set_methods = {"coords": "set_coords"}


a = A()
a.coords = 2
```

**Comment by rboston628** [comment]
I know this is outdated with V2, but just in case someone else out there is also working in a project still pegged to V1.10.  I needed a field that would  only be set when the user asked for it.  This is what eventually worked, emulating the presence of a field called `phantomData`.

``` python

class PhantomDAO(BaseMode):

  visibleData: int
  _phantomData: str = PrivateAttr()

  # enable to init with it, set it, or get it

  def __init__(self, **kwargs):
    super().__init__(**kwargS)
    object.__setattr__(self, "_phantomData", kwargs.get("phantomData"))
		
  def __setattr__(self, name, value):
    try:
      super().__setattr__(name, value)
    except ValueError as e:
      if name == "phantomData":
        object.__setattr__(self, "_phantomData", value)
      else:
        raise e
				
  @property
  def phantomData(self):
    if self._phantomData is None:
      self._phantomData = a_costly_function(self.visibleData)
    return self._phantomData
	
  # serialization

  def dict(self, **kwargs) -> Dict[str, Any]:
    ans = super().dict(**kwargs)
    if self._phantomData is not None:
      ans["phantomData"] = self.phantomData
    return ans
		
  def json(self, **kwargs) -> str:
    return json.dumps(self.dict(), **kwargs)
```

I can't guarantee the `**kwargs` to the dictionary when called from `json()` will be correct, but otherwise it works.

Allows for

``` python
dao1 = PhantomDAO(visibleData = 1, phantomData = "x")

dao2 = PhantomDAO(visibleData = 2)
print(dao2.phantomData) # will call the costly function

dao3 = PhantomDAO(visibleData = 3)
dao3 = "y"

assert dao1.dict().get("phantomData") is None
assert dao2.dict().get("phantomData") is not None 
```

Or just use V2 with usual property getter/setter methods.

**Comment by fpawlows** [comment]
Is any new solution available to this issue?
In my case, I would like to just implement custom assignment logic for some class based on the pydantic BaseModel. I would use field_validator, but I need to access 'self' to get the value before the assignment.
Does anybody have some suggestions for such case? 

```
class UmlElement(BaseModel, validate_assignment=True):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique identifier for the element.")
    builder: Optional[UmlModelBuilder] = None

    @field_validator('id')
    def validate_new_id(cls, id_value: str) -> str:
        old_id = self._id # not working since there is no self in classmethod
        if not id_value.strip():
            raise ValueError("ID must be a non-empty string.")
        
        if self.builder: # not working since there is no self in classmethod
            self.builder.register_if_not_present(self, old_id) # not working since there is no self in classmethod

        return id_value
        ```
