### ISSUE TITLE
Attrs benchmarks

### ISSUE THREAD

**Issue by cyberbudy** [samuelcolvin/pydantic#1582]
# Question

I have a question about attrs-cattrs benchmark code. 
The author of this article (https://stefan.sofa-rockers.org/2020/05/29/attrs-dataclasses-pydantic/) poits out that replacing `dateutil.parser.parse` function with `datetime.isoformat` increases performance of attrs in 7 times.
It may confuse people, that there code with attrs will be noticeably faster then pydantic claims to be.

**Comment by samuelcolvin** [comment]
This is being discussed on #1568

**Comment by cyberbudy** [comment]
Great. Thanks
