### ISSUE TITLE
How to: Customize model structure

### ISSUE THREAD

**Issue by will-e-yams** [samuelcolvin/pydantic#1587]
# Question
I'm querying from a Postgres database with jsonb fields. I'd like to extract _some_ of the values from the json not keeping the bloated, nested structures. Is this possible?

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /.../app/.env/lib/python3.7/site-packages/pydantic
               python version: 3.7.3 (default, Mar  6 2020, 22:34:30)  [Clang 11.0.3 (clang-1103.0.32.29)]
                     platform: Darwin-19.4.0-x86_64-i386-64bit
     optional deps. installed: ['email-validator']
```

```py
import pydantic

class EntityBlob(BaseModel):
    top_level_prop: str
    nested_prop: ???????

class Entity(BaseModel):
    title: str
    created_at: datetime
    updated_at: datetime
    blob: EntityBlob

    class Config:
        orm_mode = True
```

**Comment by samuelcolvin** [comment]
I'm afraid I don't entirely understand the question.

You can change how extra data is processed using the [`extra` config setting](https://pydantic-docs.helpmanual.io/usage/model_config/).

Or you can use a [`@root_validator(pre=True)`](https://pydantic-docs.helpmanual.io/usage/validators/#root-validators) to modify your input data to fit into the model you want.
