### ISSUE TITLE
Add "camelCase" mode

### ISSUE THREAD

**Issue by dnp1** [samuelcolvin/pydantic#159]
Hello guys, 
At my company, our apis uses camelCase for all dictionnaire keys in json request and response bodies. That's a company guideline that came from the fact we communicate with several API's written in diverse languages. Since camelCase is the way variables are written in JS, we chose that.

This awesome library is quite useful for us. I'm using it, but before every *request* and every *response* I have to transform my dict.

Maybe you should support a ***camelCase mode*** just like [Serde](https://serde.rs/) does

**Comment by samuelcolvin** [comment]
I'm not clear how pydantic needs to change. Can't you just set the attribute/field names to be camel case?

**Comment by dnp1** [comment]
I like PEP8, If I rename properties names I can't follow it.

Besides my own classes, the json errors returned by pydantic are written snake_case. 

I would appreciated a "camelCase" mode for the same reason serde.rs support it:  because of naming conventions are important. And  *transform every key* is boring and inneficient.

**Comment by samuelcolvin** [comment]
Humm, you can already have alternative names using config fields. But it would be possible to add such a setting or allow you to easily override the base model. I'll look into it.

**Comment by samuelcolvin** [comment]
ping @dnp1, does #165 satisfy your requirement?

**Comment by dnp1** [comment]
@samuelcolvin , yes, it helped me!!

I'm sorry I could not ping before.
But now I'll use your feature again.

**Comment by samuelcolvin** [comment]
Pleased it helped.
