### ISSUE TITLE
Mixing pydantic model with existing classes

### ISSUE THREAD

**Issue by sadrok** [samuelcolvin/pydantic#1590]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /Users/francois.basson/.virtualenvs/stock-cart-service/lib/python3.7/site-packages/pydantic
               python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24)  [Clang 6.0 (clang-600.0.57)]
                     platform: Darwin-19.4.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```
Is there a way to load, through Pydantic schema, data into non-Pydantic objects complete with recursive loading? I wish to use Pydantic in my unit tests in setting up alarge amount of test objects from JSON but those test objects are not Pydantic models and it's too much "effort" right now to make them Pydantic compatible.
 Those objects also generally have more fields than the Pydantic version which either gets setup in the __init__ or through later means. Things that Pydantic shouldn't worry about. I only need the defined schema's values to be populated.

I think essentially I want to do what ORM mode does for vanilla classes, only in reverse.

Awesome and useful library though!

```py
from pydantic import typing
import pydantic


class MyOwnClassA:
    _class_a_private = None
    class_b_public = None

    def __init__(self):
        self._class_a_private = 123
        self.class_b_public = 456

    def my_method(self):
        print(
            f"Class A private value: {self._class_a_private} and public value: {self.class_a_public}"
        )


class MyOwnClassB:
    _class_b_private = None
    class_b_public = None

    class_a_list = None

    def __init__(self):
        self._class_b_private = "abc"
        self.class_b_public = "def"
        self.class_a_list = [MyOwnClassA()]

    def my_method(self):
        print(
            f"Class B private value: {self._class_b_private} and public value: {self.class_b_public}"
        )
        for a in self.class_a_list:
            a.my_method()


class ModelA(pydantic.BaseModel, MyOwnClassA):
    class_a_public: int = None


class ModelB(pydantic.BaseModel, MyOwnClassB):
    class_b_public: str = None
    class_a_list: typing.List[ModelA] = None

data = {
    "class_b_public": "hello world",
    "class_a_list": [{"class_a_public": 555}, {"class_a_public": 777}],
}

obj = pydantic.parse_obj_as(ModelB, data)
```

**Comment by samuelcolvin** [comment]
I'm afraid this isn't currently possible.

You could use `create_model()` to create pydantic models, you would basically need to iterate over `MyOwnClassB.__dict__` and go from there.

Or you could use `arbitrary_types_allowed` to allow fields which are not pydantic models, but beyond that isn't not currently possible.

When pydantic get's full support for `TypedDict` (#760) you might be able to build `TypedDict`s for the namespace of your classes, but fundamentally that's the same as using `create_model()` now.
