### ISSUE TITLE
When to use validator, when to use custom type?

### ISSUE THREAD

**Issue by tuukkamustonen** [samuelcolvin/pydantic#1593]
# Question

I'm a bit confused when I should use [validator](https://pydantic-docs.helpmanual.io/usage/validators/) and when I should use [Custom Data Type](https://pydantic-docs.helpmanual.io/usage/types/#custom-data-types), when I want to validate values _in a re-usable way_.

I am new to Pydantic, sorry if this has been already documented and I missed it.

Validator functions:

```py
def validate_field(value):
    ...
    return value

class Data(BaseModel):
    field: str
    _validate_field: classmethod = validator('field', allow_reuse=True)(validate_field)
```

Here in specific, why does validator need to return value? If it's a _validator_ and not "mutator"?

Data Types:

```py
class MyField(str):
    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        ...
        return cls(v)

class Data(BaseModel):
    field: MyField
```

Which one is recommended and in which case? A validator, when you want to mix it up with several different types, and type, if it's ok to always bind it with certain type? Is that it?

Also, how do you pass in parameters for the data type? Like `field: MyField(some_param=2)`? Should you just:

```py
def MyField(some_param: int = 0):
    def _class(str):
        @classmethod
        def __get_validators__(cls):
            yield cls.validate

        @classmethod
        def validate(cls, v):
            # do something with some_param...
            return cls(v)

    return _class
```

Like this?

Note: I am aware of the [constrained types](https://pydantic-docs.helpmanual.io/usage/types/#constrained-types), but in this case I need validation that is not supported out of the box.

---

Also, I find both somewhat ugly. For validators, I don't like having to explicitly declare classmethods, re-typing `allow_reuse=True` and re-typing the field name (and even [this shortcut](https://github.com/samuelcolvin/pydantic/issues/940#issuecomment-569765091) feels clumsy). For custom data types, declaring `__get_validators__` seems annoying.

Are there maybe improvements coming in this topic? In `marshmallow` and similar, this is how you do it:

```py
class Data(Schema):
    field: str = fields.Str(validate=[MyValidator()])

class MyValidator(Validator):
    def __call__(self, value):
        ...
        return value
```

Imo, this is less verbose?

**Comment by samuelcolvin** [comment]
It's your choice whether to use validators or custom types. If you're reusing the validator, probably better to implement as a custom data type.

---

> Also, how do you pass in parameters for the data type?

Nothing special required from pydantic, just standard python:

```py
from typing import Type, Any
from devtools import debug
from pydantic import BaseModel

class MyFieldMeta(type):
    def __getitem__(self, some_param: Any) -> Type['MyField']:
        return type('MyFieldValue', (MyField,), {'some_param': some_param})

class MyField(metaclass=MyFieldMeta):
    some_param: Any = None

    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        if cls.some_param is None:
            # do validation without some_param
            return -v
        else:
            pass  # do validation with some_param
            return v * cls.some_param

class Foo(BaseModel):
    x: MyField
    y: MyField[42]

debug(Foo(x=2, y=2))
```

---

> Also, I find both somewhat ugly.

I know it could be better, hopefully it will change in v2. When I have more time, I'll create an issue explaining my vision for validation in v2.

**Comment by tuukkamustonen** [comment]
Hey, thanks for explaining that!

> If you're reusing the validator, probably better to implement as a custom data type.

A recommendation such as this would be nice to see in the docs. Maybe in a slightly more verbose form (like _"use data types if validation is always bound to certain type (e.g. `str`), use validators if you need to target several types (e.g. `str`/`int`/`bool`)"_), 

> Nothing special required from pydantic, just standard python

Ah, using metaclasses, why not. Although... `constr()` et al. are functions that return type, similar to my suggestion above:

```py
def constr(...) -> Type[str]:
```

Is one here better than the other (function returning type vs metaclass)?

It also makes one wonder if metaclasses would just confuse newbies. Plus using meteclasses introduces multiple lines (4 + empty lines), on top current boilerplate. If the target is re-usable one-line validation call with 1 parameter, requiring 12+ lines + empty lines feels bloated.

> I know it could be better, hopefully it will change in v2. When I have more time, I'll create an issue explaining my vision for validation in v2.

Good to hear!

I'm quite sure it has been suggested before, but would something like this work:

```py
class Data(BaseModel):
    field1: String(validate=[some_callable1(depth=3)])
    field2: String[validate=[some_callable2(whatever=False)]]
```

**Comment by samuelcolvin** [comment]
`field2: String[validate=[some_callable2(whatever=False)]]` is discouraged by PEP 484

So is `constr()`, but at least it's concise.

The reason to you parameterisation is that it is in keeping with the rest of typing and doesn't break flake8, or mypy.

If you need named arguments use functions, if you don't use parameterisation of types.
