### ISSUE TITLE
Update tmp_schema_mappings.html to reflect anyOf use case

### ISSUE THREAD

**Issue by JHBalaji** [samuelcolvin/pydantic#1595]
I tried forking the repo to update the docs but 'tmp_schema_mappings.html' which isnt available for update.

This pertains to anyOf vs oneOf in the JSON schema

`Union[str, int]`  behaves more like oneOf when producing the output following a set of deductions in the order it was declared, in this case given supplied `[str, int]` it will output as`str`

But may I also suggest to add `List[Union[str, int]]` this would resemble and produce exact anyOf usage and given `[str, int, List[]]` the outcome would be `[str, int]`  

It would save countless hours for somebody looking for an anyOf usage.

**Comment by samuelcolvin** [comment]
See the beginning of `.tmp_schema_mappings.html`:

```html
<!--
  Generated from docs/build/schema_mapping.py, DO NOT EDIT THIS FILE DIRECTLY.
  Instead edit docs/build/schema_mapping.py and run `make docs`.
-->
```

---

Regarding your point about Union, List etc. I'm afraid I don't know what you mean.

**Comment by JHBalaji** [comment]
Should I update schema_mapping.py to include `List[Union[str, int]]` 

`Union[str, int]` will produce `{"anyOf": [{"type": "string"}], [{"type": "integer"}]}` it would be either `[{"type": "string"}]` or `[{"type": "integer"}]` ,
wherever `List[Union[str, int]]` will output `{"anyOf": [{"type": "string"}, {"type": "integer"}]}` which means it can have both  `[{"type": "string"}]` and `[{"type": "integer"}]` in the same field. 

I'm no expert but I would save time to many those who want to represent a collection of items using `Union`
the present `anyOf` resembles more like `oneOf`.

**Comment by JHBalaji** [comment]
@samuelcolvin

**Comment by PrettyWood** [comment]
Hi @JHBalaji 
I don't understand the issue. You want to add an example in `schema_mapping.py` to explain that
`List[Union[str, int]]` will output `{"anyOf": [{"type": "string"}, {"type": "integer"}]}` whether
`Union[List[str], List[int]]` will output `{"anyOf": [{"type": "array", "items": {"type": "string"}}, {"type": "a'
        'rray", "items": {"type": "integer"}}]}` ?
 For me it's quite obvious and I feel like we have enough examples.
 Closing the issue but feel free to answer
