### ISSUE TITLE
How do I use Union[float, int, str] without typecasting

### ISSUE THREAD

**Issue by tanyaofei** [samuelcolvin/pydantic#1599]
I want to create a field support float, int and str, but this filed will typecasting which i don't need.
```Python
from typing import Union

from pydantic import BaseModel

MyType = Union[float, int, str]


class T(BaseModel):
    value: MyType


t = T(value=1)

print(t.value)
```
I want it to be 1 instead of 1.0, how do i do that?

**Comment by samuelcolvin** [comment]
Change the order of the arguments to Union.

This is a known problem, see #619 and #1423.
