### ISSUE TITLE
strip white space from strings

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#16]
by default. Allow as argument to `constr`

**Comment by nandoflorestan** [comment]
I just wanted to point out that colander has a concept of a *preparer* function that can convert incoming data before validation of a schema node. In colander one would use a *preparer* in order to strip an incoming string -- as well as other uses.

Maybe the same concept would apply here?

**Comment by samuelcolvin** [comment]
This was actually already implemented in #163, I should have closed this issue. Thanks for reminding me.

wrt "preparers", pydantic already has this feature - validators with `pre=True`, see https://pydantic-docs.helpmanual.io/#pre-and-whole-validators.
