### ISSUE TITLE
Add ability to redact specified fields in when serializing models

### ISSUE THREAD

**Issue by apost71** [samuelcolvin/pydantic#1606]
# Feature Request

It would be extremely useful to be able to redact fields when serializing data models.  This is something that would typically be used for logging purposes when handling sensitive data and it does not appear that there is an easy way to handle this right now.  The mapping to determine excluded fields during model exporting seems like a good way to specify keys that need to be redacted, so that logic could be reused to overwrite values with redacted values.

Below is an example of how I might expect this to work

```py
import pydantic

class Person(BaseModel):
    title: str = None
    prefix: str = None
    firstName: str
    middleName: str = None
    lastName: str
    suffix: str = None
    dateOfBirth: datetime.date = None

person = Person(firstName='Johnny', lastName='Appleseed', dateOfBirth='2000-01-01')
person.json(redacted={'dateOfBirth'})
```
and the output would look something like this:

```
{
  "firstName": "Johnny",
  "lastName": "Appleseed",
  "dateOfBirth": "REDACTED-datetime.date"
}
```

I am happy to work on this PR as well.

**Comment by samuelcolvin** [comment]
Thanks for creating the issue.

I think between [`SecretStr`, `SecretBytes`](https://pydantic-docs.helpmanual.io/usage/types/#secret-types) and [the `exclude` kwarg](https://pydantic-docs.helpmanual.io/usage/exporting_models/#modeldict), we have this covered.

We don't need another feature.
