### ISSUE TITLE
More exotic types

### ISSUE THREAD

**Issue by Gr1N** [samuelcolvin/pydantic#161]
Hi,

At my company we would like to migrate to your package, but we need more types out of the box. Below you can find list of additional types and validators and I like to discuss with you what do you think:

1. Min and max length validators for list type, maybe something like `conlist(type_=..., min_length=..., max_length=...)`. Of course I can implement length validation using `validator` decorator, but it's too complex to share as common type for company needs.
2. (Done #175) Decimal type not supported at all. Also we would like to have validators for minimum, maximum, maximum digits and decimal places like in Django (https://github.com/django/django/blob/master/django/forms/fields.py#L322, https://github.com/django/django/blob/master/django/core/validators.py#L388).
3. (Done #166) Float type: minimum and maximum validators.
4. String type:
    1. (Done #163) We need additional `strip_whitespace` argument in `constr` to strip whitespaces, just `value.strip()`. In my opinion it's common practice for validation libraries to have this option. 
    2. Also I would like to discuss with you coerce logic (https://github.com/samuelcolvin/pydantic/blob/master/pydantic/validators.py#L30). Why it supports only for float, int and decimal types? Can we use logic which already implemented for dict and list types (https://github.com/samuelcolvin/pydantic/blob/master/pydantic/validators.py#L83)?
5. (Done #167) UUID type version validation, just `value.version == ...`.

If you are okay with my proposals, then I will create a few PRs for each my proposal.

**Comment by samuelcolvin** [comment]
Yes to all except as per #156 we should use square brackets for type parameters.

**Comment by Gr1N** [comment]
I don't think that we can use square brackets due to syntax limitations:
```
class Foo:
    bars: List[min_length=42]
```
```
$ python --version
Python 3.6.5

$ python test_annotations_sq.py
  File "test_annotations_sq.py", line 2
    bars: List[min_length=42]
                         ^
SyntaxError: invalid syntax
```

PEP-472 is only about indexing with keyboard arguments.

**Comment by Gr1N** [comment]
@samuelcolvin, I found PR https://github.com/samuelcolvin/pydantic/pull/52 where you changed coerce logic to more strict way, so looks like my proposal 4.2 have no reason to implement. Am I right?

**Comment by samuelcolvin** [comment]
is this all done?

**Comment by Gr1N** [comment]
No, `conlist(type_=..., min_length=..., max_length=...)` not implemented yet. I will try to implement soon, have no free time now...

**Comment by Gr1N** [comment]
I'm closing this issue, because have no a good idea how to implement `conlist`. Everything else is implemented.

**Comment by alex-lechner** [comment]
+1
I would need to validate GeoJSON Polygon coordinates with `conlist`. My current approach is:

```python
from typing import List, Union
from pydantic.dataclasses import dataclass
from pydantic import BaseModel, validator
from pydantic.color import Color
import numpy as np

@dataclass
class Geometry:
    type: str
    coordinates: List[List[List[Union[float, int, np.int, np.float]]]]

    @validator('coordinates', whole=True)
    def check_valid_coordinates(cls, v):

        if isinstance(v, list):
            v = np.array(v)

            if len(v.shape) != 3:
                raise ValueError(
                    f'{v} must have an exterior section and coordinates.')
            if v.shape[2] != 2:
                raise ValueError(
                    f'{v} can only have two Points (latitude & longitude)')

            for exterior in v:
                for lon, lat in exterior:
                    if lon < -180 or lon > 180:
                        raise ValueError(
                            f'longitude {lon} in {v} must be in range -180 to 180.')

                    if lat < -90 or lat > 90:
                        raise ValueError(
                            f'latitude {lat} in {v} must be in range -90 to 90.')

        return v


class Properties(BaseModel):
    type: str
    fill: Color
    fill_opacity: float
    marker_color: Color
    stroke: Color
    stroke_opacity: int
    stroke_width: int

    class Config:
        fields = dict(
            fill_opacity=dict(alias="fill-opacity"),
            marker_color=dict(alias="marker-color"),
            stroke_opacity=dict(alias="stroke-opacity"),
            stroke_width=dict(alias="stroke-width")
        )


@dataclass
class Feature:
    type: str
    properties: Properties
    geometry: Geometry


@dataclass
class GeoJSON:
    type: str
    features: List[Feature]
```

**Comment by samuelcolvin** [comment]
I'm still not clear what you're looking for - I suspect the approach you've used above is probably the best way, but not clear.

maybe worth creating a new issue for this.

**Comment by alex-lechner** [comment]
Oh I'm sorry I forgot to elaborate on my issue a bit more. In my case, I need to validate geometry objects based on the [GeoJSON Specification](https://tools.ietf.org/html/rfc7946). In my example above I validate a `Polygon` object. The structure of the `Polygon` in a GeoJSON has to look like this:
```json
{
  "type": "Polygon",
  "coordinates": [
    [
      [0, 0], [10, 10], [10, 0], [0, 0]
    ]
  ]
}
```
As you can see the coordinates are a nested list with an exterior Part (second list) and `Point`s (lists within the second list). The order of a `Point` described by the Geojson is `[longitude, latitude, elevation]`. So a Point can only have either 2 or 3 values in a list but not more or less. That's why `conlist` might come in handy because the `conlist` would set a constraint on the list/array object.

Would you accept a PR for GeoJSON support? Also for the `conlist`?

**Comment by samuelcolvin** [comment]
This is not what `conlist` is for, `conlist` is for controlling the size of the outer list.

You can achieve what you're looking for here either with custom validators, a `Point` type that implements it's own validation, or with a simple tuple:

```py
from typing import List, Tuple, Union
from pydantic.dataclasses import dataclass

@dataclass
class Geometry:
    type: str
    coordinates: List[Union[Tuple[float, float], Tuple[float, float, float]]]

print(Geometry(type='Polygon', coordinates=[[0, 0], [10, 10], [10, 0, 0.5]]))
```

If you have anymore questions, please create a new issue.
