### ISSUE TITLE
Dynamic model creation with dynamic field names

### ISSUE THREAD

**Issue by hhsecond** [samuelcolvin/pydantic#1612]
# Question
How can I create dynamic models with dynamic field names? The [existing mechanism](https://pydantic-docs.helpmanual.io/usage/models/#dynamic-model-creation) to create dynamic models requires the field names to be pre-known, AFIK. 

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /home/hhsecond/miniconda3/envs/userve/lib/python3.8/site-packages/pydantic
               python version: 3.8.3 (default, May 19 2020, 18:47:26)  [GCC 7.3.0]
                     platform: Linux-5.3.0-53-generic-x86_64-with-glibc2.10
     optional deps. installed: []

```
I was thinking something like what namedtuples do when I found there is a mechanism to create models dynamically.
```py
from pydantic import create_model
foo, bar = get_dynamic_attrib_name()
create_model('DynamicFoobarModel', fields={foo:(str, ...), bar:123})
```

**Comment by PrettyWood** [comment]
Hello @hhsecond 
Why doesn't it work with just `create_model('Model', **fields)` where fields is a dict with your dynamic names as keys.
Am I missing something? If yes could you please give us an example ?

**Comment by hhsecond** [comment]
oh crap. I am so stupid. That would totally work. Thanks a ton @PrettyWood 

Closing the issue
