### ISSUE TITLE
Problem running Literal type example with inheritance

### ISSUE THREAD

**Issue by jackieleng** [samuelcolvin/pydantic#1622]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /mnt/c/Users/**********/env/lib/python3.6/site-packages/pydantic
               python version: 3.6.9 (default, Apr 18 2020, 01:56:04)  [GCC 8.4.0]
                     platform: Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-18.04-bionic
     optional deps. installed: ['typing-extensions']
```

I'm trying to run this example from https://pydantic-docs.helpmanual.io/usage/types/#literal-type, but I'm not getting the right results. In my case everything returns as "Dessert" instead the correct types. The other Literal examples are running correctly. Only this one with inheritance seems to fail. I'm also running on WSL, not sure if that might be a problem.

```py
from typing import Optional, Union

from typing_extensions import Literal

from pydantic import BaseModel

class Dessert(BaseModel):
    kind: str

class Pie(Dessert):
    kind: Literal['pie']
    flavor: Optional[str]

class ApplePie(Pie):
    flavor: Literal['apple']

class PumpkinPie(Pie):
    flavor: Literal['pumpkin']

class Meal(BaseModel):
    dessert: Union[ApplePie, PumpkinPie, Pie, Dessert]

print(type(Meal(dessert={'kind': 'pie', 'flavor': 'apple'}).dessert).__name__)
#> ApplePie
print(type(Meal(dessert={'kind': 'pie', 'flavor': 'pumpkin'}).dessert).__name__)
#> PumpkinPie
print(type(Meal(dessert={'kind': 'pie'}).dessert).__name__)
#> Pie
print(type(Meal(dessert={'kind': 'cake'}).dessert).__name__)
#> Dessert
```

Output is:
```
Dessert
Dessert
Dessert
Dessert
```

**Comment by vdwees** [comment]
I just tested this on the python versions on my system. On Python 3.6.9 I get the same output as @jackieleng, but on Python 3.7.5 and Python 3.8.0 the output is as expected.

**Comment by samuelcolvin** [comment]
Thanks for reporting, i don't currently have access to a python 3.6 install. Would be great therefore if someone else could look into this.

**Comment by PrettyWood** [comment]
I had a quick look. The problem comes from the `resolve_annotations` because `__annotations__` is not properly set with python 3.6
```
# python 3.6
ipdb> pp namespace
{'__annotations__': {'dessert': <class 'tests.test_ex.test_1.<locals>.Pie'>},
 '__module__': 'tests.test_ex',
 '__qualname__': 'test_1.<locals>.Meal'}
```
```
# python 3.7/8
ipdb> pp namespace
{'__annotations__': {'dessert': typing.Union[tests.test_ex.test_1.<locals>.ApplePie, tests.test_ex.test_1.<locals>.Pie]},
 '__module__': 'tests.test_ex',
 '__qualname__': 'test_1.<locals>.Meal'}
```
I may check this weekend on a possible fix if noone works on it before

**Comment by samuelcolvin** [comment]
Thanks @PrettyWood, you're absolutely right that that's the problem.

python 3.6 collapses `Union[ApplePie, Pie]` to just `Pie` which kind of makes sense, but obviously causes problems for us and apparently others, hence it changing.

This isn't a problem with pydantic or something pydantic can fix.

I guess we could add some documentation mentioning, but since python 3.6 is pretty old now i think it's outside the scope of our docs.
