### ISSUE TITLE
Empty strings are not considered null values

### ISSUE THREAD

**Issue by guiscaranse** [samuelcolvin/pydantic#1626]
# Bug

Empty strings does not trigger ValueErrors. If my attr is not optional why allow users to send an empty string to a field that is required and is a string?

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /home/guiscaranse/.local/share/virtualenvs/api/lib/python3.7/site-packages/pydantic
               python version: 3.7.7 (default, May 30 2020, 15:17:46)  [GCC 7.5.0]
                     platform: Linux-5.3.0-53-generic-x86_64-with-debian-buster-sid
     optional deps. installed: ['typing-extensions', 'email-validator']
```

Example:
```py
from pydantic import BaseModel
class test(BaseModel):
  a: str


test(a="")
```

**Comment by samuelcolvin** [comment]
This is not at error.  An empty string is a valid string. 

You can use `constr`.

**Comment by mojimi** [comment]
@samuelcolvin What if I want an empty string to trigger the default value without giving an error? Is there a way to do that?

This is common when dealing with frontend frameworks, they tend to send empty strings

**Comment by PrettyWood** [comment]
Hello @mojimi 
You could do something like this
```python
from pydantic import BaseModel, validator


class Model(BaseModel):
    foo: str

    @validator('foo')
    def never_empty(cls, v: str) -> str:
        if not v:
            return 'pika is the best'  # the default value you want
        return v
```

Hope it helps

**Comment by mecampbellsoup** [comment]
+1 seems like Pydantic should offer a way via e.g. `constr` to simply coerce `""` to `None`.
