### ISSUE TITLE
How to model an unused field?

### ISSUE THREAD

**Issue by yurikhan** [samuelcolvin/pydantic#1632]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: False
                 install path: /home/khan/.local/lib/python3.6/site-packages/pydantic
               python version: 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
                     platform: Linux-4.15.0-88-generic-x86_64-with-Ubuntu-18.04-bionic
     optional deps. installed: ['typing-extensions', 'email-validator']
```

I am writing code that will consume an externally generated JSON. For simplicity, let’s assume the following schema:

```
{
  'type': 'object',
  'additionalProperties': False,
  'required': ['foo', 'bar'],
  'properties': {
    'foo': {'type': 'integer'},
    'bar': {'type': 'string'}
  }
}
```

I want to validate that both required fields are present, and that no additional fields are included. To that end, I include both fields in the model and configure the model to forbid extra fields. This works:

```py
from pydantic import BaseModel, Extra

class DataModel(BaseModel):
    class Config:
        extra: Extra.forbid

    foo: int
    bar: int


DataModel(**{'foo': 3, 'bar': 14})
# success

DataModel(**{'foo': 3})
# ValidationError: 1 validation error for DataModel
# bar
#   field required (type=value_error.missing)

DataModel(**{'foo': 3, 'bar': 14, 'baz': 15})
# ValidationError: 1 validation error for DataModel
# baz
#   extra fields not permitted (type=value_error.extra)
```

Further, my code only uses the `foo` field; `bar` is unused. I would like to document this fact to the reader and maintainer of my code. (In practice, I’m using a static analyzer that complains when my classes have attributes that are never used.)

The _obvious way to do it_ is to start the attribute name with an underscore. I thought I could do that and alias it to the original name. However, this does not work:

```py
from pydantic import BaseModel, Extra, Field

class DataModel(BaseModel):
    class Config:
        extra: Extra.forbid

    foo: int
    _bar: int = Field(..., alias='bar')


DataModel(**{'foo': 3, 'bar': 14})
# expected: success
#
# observed:
# ValidationError: 1 validation error for DataModel
# bar
#   extra fields not permitted (type=value_error.extra)

DataModel(**{'foo': 3})
# expected:
# ValidationError: 1 validation error for DataModel
# bar
#   field required (type=value_error.missing)
#
# observed: success

DataModel(**{'foo': 3, 'bar': 14, 'baz': 15})
# expected:
# ValidationError: 1 validation error for DataModel
# baz
#   extra fields not permitted (type=value_error.extra)

# observed:
# ValidationError: 2 validation errors for DataModel
# bar
#   extra fields not permitted (type=value_error.extra)
# baz
#   extra fields not permitted (type=value_error.extra)
```

I understand that the direct cause of my problem is that Pydantic [filters out][1] annotations with names starting with `_`. I do not fully understand why this filtering is needed. I believe I have read all relevant parts of the documentation, and they don’t mention any model field naming restrictions.

[1]: https://github.com/samuelcolvin/pydantic/blob/329b1d3e7b32bd72a4db2d122ef0e325c5725741/pydantic/main.py#L180

**Comment by samuelcolvin** [comment]
Attributes starting with underscores are private in python (soft private because most things are soft in python, but still private), therefore I didn't think it made sense to make them fields which are inherently public.

Whether or not I was wrong about that when I first started building pydantic, it's too late to change it now as it would break a lot of behaviour I think.

Maybe in future we could add a function replacing `keep_untouched` which allowed you to customise which attributes are included as fields. This might be a useful workaround in a few situations without breaking old functionality. Would that work for you?

Currently the best option is to use `bar` and tell the static analysis to shut-up.

**Comment by yurikhan** [comment]
Okay, thanks. I think I’ll have to keep models in a file that is exempt from said static analysis, as touching every field in a 150-line schema is going to be tedious.

**Comment by samuelcolvin** [comment]
what static analysis warns about unused fields? and why should private unused fields be any better than public unused fields?

**Comment by yurikhan** [comment]
[Vulture][1]. It’s pretty stupid and has the same rules for local variables and class attributes, so I reached for the usual convention for unused local variables.

[1]: https://github.com/jendrikseipp/vulture
