### ISSUE TITLE
create_model from JSON Schema

### ISSUE THREAD

**Issue by BCarley** [samuelcolvin/pydantic#1638]
# Feature Request

I've been using a script to generate `pydantic` models from jsonschema. I think I have seen this mentioned in a few issues (#1405) and I would be keen to contribute back if I am able to.

Prior to opening a pull request I thought I would put the code here for a sanity check.

The overall flow is json schema -> pydantic models -> create_model

## Example Build Flow

_Note that this is for illustration and will not run as is_

```python
def _recursive_build(model: Object):
    fields: Dict[str, tuple] = {}

    for key, prop_model in model.properties.items():
        default = model.default or ... if str(key) in model.required else None
        fields[key] = _build_field(key, prop_model, default=default)

    return create_model(
        model.title or "Schema",
        __config__=None,
        __base__=None,
        __module__=None,
        __validators__=None,
        **fields,
    )


def _build_field(field_name: str, model: SchemaTypes, default: Any) -> Tuple[Any, Any]:
    if model.type == "object":
        return (
            _recursive_build(model),
            Field(default),
        )
    elif model.type == "string":
        return (
            str,
            Field(
                default,
                title=model.title or field_name,
                description=model.description,
                min_length=model.minLength,
                max_length=model.maxLength,
                regex=model.pattern,
                const=model.const,
            ),
        )

    # continues with rest of types

```

## Example Schemas

_Note that this is for illustration and will not run as is_

```python
class SchemaBase(BaseModel):
    description: Optional[str]
    title: Optional[str]
    default: Optional[Any]
    examples: Optional[List[Any]]
    enum: Optional[List[Any]]
    const: Optional[Any]

    class Config:
        ignore_extras = True
        exclude_none = True


class Format(str, Enum):
    date_time = "date-time"
    date = "date"
    time = "time"


class Boolean(SchemaBase):
    type: Literal["boolean"]


class Object(SchemaBase):
    type: Literal["object"]
    minProperties: Optional[int]
    maxProperties: Optional[int]
    required: List[str] = []
    additionalProperties: Optional[bool]
    properties: Dict[str, SchemaTypes]
```

## Example Tests

This might not be acceptable but currently for the tests I am comparing `schema()` outputs

```python
def test_simple_integer():
    schema = {
        "type": "object",
        "title": "Simple Integer",
        "properties": {
            "foo": {
                "title": "Integer",
                "type": "integer",
                "maximum": 5,
                "minimum": 4,
                "multipleOf": 1,
            }
        },
    }
    assert schema == schema_to_model(schema).schema()
```

## Potential Issues

- Not currently looking at `definitions` in json-schemas as I don't need them. I expect this would have to be offloaded to a library but that would mean adding a depency
- Lots of fiddly bits that might be difficult to handle in the json schema spec might make it more effort than is worth.
- The lack of a discriminator might have failed validations of the input `Schema` a bit noisy and confusing for users.
- Might encourage people to use json schema rather than `pydantic` models directly.

Thanks!

**Comment by samuelcolvin** [comment]
Have you seen [`datamodel-code-generator`](https://pydantic.helpmanual.io/dev/pr-1635/datamodel_code_generator/)? (note: that's the docs for a recent PR since that page of the docs hasn't been released yet)

If that doesn't solve your problem, I would suggest creating a separate library, if it get's popular we can link to if from pydantic's docs.

Pydantic already takes me far too long to support, I don't want to add anything to library that could potentially split into a separate library.

**Comment by BCarley** [comment]
The linked `datamodel-code-generator` is not quite right for me as I want to generate the models dynamically from some legacy `jsonschema`. The `create_model` solution is working for me at the moment, I'll keep on plugging away with it and if I think others would find it useful I'll look at including it as a library.

Thank you for all your work on `pydantic`, it has been massively helpful! I'll keep my eye out for anything I'm able to lend a hand with.

**Comment by samuelcolvin** [comment]
Thanks so much. Much appreciated.

**Comment by Dens49** [comment]
First of all: sorry for bumping this year old issue. I don't want to start a discussion, I'm just interested in the solution @BCarley has built for this :)

I have the same use case as you and was doing some research before building my own thing. Is there any chance you have published your dynamic pydantic model from json-schema script somewhere that's publicly accessible? If not, would you be willing to do that? I'd understand if you don't want to publish that, though.
In that case, could you describe some of the problems and caveats you encountered along the way? Something painful to watch out for when building this a solution for this?

**Comment by navidRashik** [comment]
I recently had a need for something like this as well. tried @cofin solution but didn't worked for me. 
I was trying to convert following schema
```json
{"properties": {"amount": {"title": "Amount", "type": "integer"},
  "discount_type": {"enum": ["fixed_amount", "percentage"],
   "title": "Discount Type",
   "type": "string"},
  "discount_apply_count": {"title": "Discount Apply Count", "type": "integer"},
  "discount_on": {"enum": ["line_item", "shipping_line"],
   "title": "Discount On",
   "type": "string"}},
 "required": ["amount",
  "discount_type",
  "discount_apply_count",
  "discount_on"],
 "title": "ShopifyDiscountCodeCreationPayloadSchema",
 "type": "object"}
```

anyone have any solution?

**Comment by kroawen** [comment]
> ```json
> Discount
> ```

try this, I test it works fine, Hope help you:
`
class DiscountTypeEnum(str, Enum):
        fixed_amount = "fixed_amount"
        percentage = "percentage"

    class DiscountOnEnum(str, Enum):
        line_item = "line_item"
        shipping_line = "shipping_line"

    class ShopifyDiscountCodeCreationPayloadSchema(BaseModel):
        amount: int = Field()
        discount_type: DiscountTypeEnum = Field()
        discount_apply_count: int = Field()
        discount_on: DiscountOnEnum = Field()

    data = {
        "amount": 100,
        "discount_type": "fixed_amount",
        "discount_apply_count": 1,
        "discount_on": "line_item",
    }

    instance = ShopifyDiscountCodeCreationPayloadSchema(**data)
`

`result: {"amount":100,"discount_type":"fixed_amount","discount_apply_count":1,"discount_on":"line_item"}`

**Comment by alon710** [comment]
Figured out how to do it
https://stackoverflow.com/a/79388695/8622976

**Comment by eschallack** [comment]
I know this reply is incredibly late but I actually just made a working solution for this that supports types from 3rd party libraries, enums and more. https://github.com/eschallack/SQLAlchemyToPydantic# here's a link to an example of the schema generation: https://github.com/eschallack/SQLAlchemyToPydantic/blob/main/example/jsonschema_to_pydantic.py
