### ISSUE TITLE
Model that includes Json field can't be deserialized

### ISSUE THREAD

**Issue by Snakeyyy** [samuelcolvin/pydantic#1639]
# Bug

When using the output of "BaseModel.json" for "BaseModel.parse_raw" and BaseModel consists of Json field type it results in ValidationError.

IMO the expected behavior is that the model should be able to deserialize itself from serialized data.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.5.1
pydantic compiled: True
 install path: /Users/snakey/projects/liber/liber_website_back/venv/lib/python3.8/site-packages/pydantic
python version: 3.8.2 (default, Apr 20 2020, 11:52:12)  [Clang 11.0.3 (clang-1103.0.32.29)]
platform: macOS-10.15.5-x86_64-i386-64bit
optional deps. installed: ['email-validator']
```

```py
from pydantic import BaseModel, Json

class TestModel(BaseModel):
    data: Json


instance = TestModel(data='{"x": "y"}')
json_data = instance.json()
TestModel.parse_raw(json_data)
```

Results in 
```
pydantic.error_wrappers.ValidationError: 1 validation error for TestModel
data JSON object must be str, bytes or bytearray (type=type_error.json)
```

**Comment by samuelcolvin** [comment]
There are many issues around the deserialisation/serialisation process not being idempotent.

It's a fundamental consequence of the fact that pydantic is a parsing library that does some validation, not a validation library.

This is a good example of that - I don't see how we could change the behaviour of either deserialisation or serialisation to make your example pass.
