### ISSUE TITLE
dicussion: Potential code quality improvements

### ISSUE THREAD

**Issue by pnijhara** [samuelcolvin/pydantic#1641]
This repo was forked and then a DeepSource analysis was run on the forked repo.
There:
- 235 Antipattern issues were found
- 43 Bug-Risks issues were found
- 63 Performance issue was found
- 14 Security issues were found
---
Out of which 155 can be auto fixed. Some of them can be found here
- https://deepsource.io/gh/pnijhara/pydantic/issue/PTC-W0018/
- https://deepsource.io/gh/pnijhara/pydantic/issue/PYL-W0612/
- https://deepsource.io/gh/pnijhara/pydantic/issue/BAN-B101/
---
In all total number of issues are listed here - https://deepsource.io/gh/pnijhara/pydantic/

Link to `.deepsource.toml` configuration file that was added to the forked repo for running DeepSource analysis can be found [here](https://github.com/pnijhara/pydantic/blob/pnijhara-patch-1/.deepsource.toml)

Which of these issues you would consider high priority, and which ones would you want to ignore or consider false-positive?

You can also activate this analysis on your own, and have it triggered on each PR, if you integrate [DeepSource](https://deepsource.io) in the repo

Disclaimer: I work for DeepSource

**Comment by pnijhara** [comment]
A PR was also sent with some fixes and  `.deepsource.toml` file.
Refer: #1485

**Comment by samuelcolvin** [comment]
Most of these suggestions make no sense, and/or are in tests where code quality tweaks are not important.
