### ISSUE TITLE
Argument names and types get mangled when using openapi-generator with Pydantic

### ISSUE THREAD

**Issue by jsilverpa** [samuelcolvin/pydantic#1647]
#1154 Question

I'm using Pydantic and FastAPI.  I believe this is an issue/question for Pydantic, but please point me to FastAPI if it is more related to that code.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.5.1
pydantic compiled: True
python version: 3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1 (tags/RELEASE_401/final)]
platform: Darwin-19.3.0-x86_64-i386-64bit 
optional deps. installed: ['typing-extensions', 'email-validator']
```

```
from fastapi import FastAPI
from pydantic import BaseModel

from fastapi_utils.openapi import simplify_operation_ids

class Item(BaseModel):
    name: str

app = FastAPI()

#this works
@app.post("/items/")
async def list_items(item1: Item):
    return item1

#this generates a mangled name
@app.post("/items_bad/")
async def list_items_bad(item1: Item, item2: Item):
    return item1

simplify_operation_ids(app)

```

With the example above, the generated client APIs (after using openapi-generator) look like:
```
api_instance.list_items(item) 
api_instance.list_items_bad(body_list_items_bad_items_bad_post)
```

I would like the 2nd API to look like
```api_instance.list_items_bad(item, item)```

Can someone advise on what I'm doing wrong?

**Comment by PrettyWood** [comment]
Hello @jsilverpa,
For what I know when you write
```python
@app.post("/items_bad/")
async def list_items_bad(item1: Item, item2: Item):
```
FastAPI will understand that `item1` is the request body and the second argument will be the query parameters (see [FastAPI doc](https://fastapi.tiangolo.com/tutorial/body/#request-body-path-parameters)).

Anyway the question has nothing to do with *pydantic* ;)

**Comment by PrettyWood** [comment]
Hello @jsilverpa,
For what I know when you write
```python
@app.post("/items_bad/")
async def list_items_bad(item1: Item, item2: Item):
```
FastAPI will understand that `item1` is the request body and the second argument will be the query parameters ([FastAPI doc](https://fastapi.tiangolo.com/tutorial/body/#request-body-path-parameters)) right?
So I don't understand why you would write something like this.

Anyway the question has nothing to do with *pydantic* and you should ask FastAPI team for some guidance

**Comment by jsilverpa** [comment]
Hi @PrettyWood .  Thanks for the reply.  I'll ask at FastAPI, but I'd like to avoid the client having to wrap the Items in a new "Payload" structure.   Granted, I don't really understand the internal details of FastAPI, but it seems like it forces the client to understand the implementation details of the API.  

Thanks again for your pointers and comments.
