### ISSUE TITLE
Export mock data model

### ISSUE THREAD

**Issue by apost71** [samuelcolvin/pydantic#1652]
# Export mock data model

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /Users/apost/ccde/ccml-terminus-defection/venv/lib/python3.7/site-packages/pydantic
               python version: 3.7.6 (default, Dec 30 2019, 19:38:28)  [Clang 11.0.0 (clang-1100.0.33.16)]
                     platform: Darwin-18.6.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']

```

I would like to be able to export a "default" json object for my data models that contain dummy data without needing to populate it all myself.  I would expect something like strings to be filled with `"string"` and ints to be filled with zeros or something along those lines.  From what I can tell this is not available, so I am posting this as a question to see if I understand correctly that this is the case, and if so I would make this a feature request.

Usage would be something along these lines

```py
import pydantic
from enum import Enum

def ModelEnum(Enum, str):
  A = "A"
  B = "B"

def Model(pydantic.BaseModel):
  string_value: str
  int_value: int
  enum_value: ModelEnum

mock = Model.mock()
```

and the result would be a data model that looks something like this:

```
{
  "string_value": "string",
  "int_value": 0,
  "enum_value": "A"
}
```

**Comment by apost71** [comment]
I would be happy to contribute a PR if this is not currently available

**Comment by samuelcolvin** [comment]
I don't think this should be a feature of pydantic, you could either integrate with an existing tool like factory-boy, or build your own library.

**Comment by rams3sh** [comment]
@samuelcolvin First of all thanks for this great project. This is an absolute beauty and I have become fan of it after having it used just for a month. 😄 😄 


> I don't think this should be a feature of pydantic, you could either integrate with an existing tool like factory-boy, or build your own library.

I understand It may not be in direct interest of the project. But it would definitely make certain use cases easier. 

For example in case , a Model's equivalent dummy json needs to be shown to the end user to get an idea of the structure. It would be nice to have a `mock` attribute to `Field` like the following code snippet.  :- 
```python
class Entity(BaseModel):
    planet : str = Field(default="Earth", mock="Mustafar")
    name: str = Field(mock="Darth Vader")

Entity.mock() # This would return all the mock values as filled values for that BaseModel class
```
This would help define a single base model and use it for validation purposes as well as getting a sample mock of that model avoiding using third  party libraries for this use case.  

Cases which are very niche such as for cases like string pattern type based values , value fuzzing for identification of a valid value as mock data may not be feasible using third party library and only manually fed values may work.  And for just using manually fed values, usage of an independent library may be an overkill.

I fully understand that I  speak for a very specific use case , but I wanted to put this across  in case anyone else feels any value in the proposal.

**Comment by samuelcolvin** [comment]
Have you tried hypothesis? It has integration with pydantic to generate pydantic model data.

**Comment by MRigal** [comment]
[Hypothesis](https://hypothesis.readthedocs.io/en/latest/index.html) 

> Pydantic automatically registers constrained types - so builds() and from_type() “just work” regardless of the underlying implementation) 

or [Polyfactory](https://github.com/litestar-org/polyfactory) are the way to go here.
