### ISSUE TITLE
Validating hierarchical data structures of unknown depth

### ISSUE THREAD

**Issue by codyflynnNC** [samuelcolvin/pydantic#1660]
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
 pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /Users/cflynn15/PycharmProjects/cara/venv/lib/python3.7/site-packages/pydantic
               python version: 3.7.4 (default, Oct 12 2019, 18:55:28)  [Clang 11.0.0 (clang-1100.0.33.8)]
                     platform: Darwin-18.7.0-x86_64-i386-64bit
     optional deps. installed: []

```

# Question
Hello! I'm new to pydantic and am trying to figure out the best way to use a pydantic model as a response_model within fast-api. The tricky part is that the object essentially a hierarchical tree where each node has the same attributes. 
![Screen Shot 2020-06-26 at 23 36 09](https://user-images.githubusercontent.com/18743297/85913810-da988f80-b805-11ea-831f-03cec45eb294.png)

 I've read the docs on post annotations and self-referencing models but am not sure how to/If I should apply them in this case. 
The data structure I want to validate looks like this:
```
{
	"orgid": 1,
	"name": "SomeRootOrg",
	"parentid": -1,
	"level": 0,
	"id": 0,
	"path": [
		0
	],
	"children": [{
			"orgid": 2,
			"name": "SomeChildOrg",
			"parentid": 1,
			"level": 1,
			"id": 1000,
			"path": [
				0,
				1000
			],
			"children": [{
					"orgid": 13,
					"name": "AnotherChild",
					"parentid": 2,
					"level": 2,
					"id": 2000,
					"path": [
						0,
						1000,
						2000
					],
					"children": [{...AndSoOn...}]
}
```

Where the maximum depth would be 5 at this point in time. I wrote a pydantic model which can successfully validate this object however there's always the potential for org changes in the future where a new level could potentially be added. Any advice on how or If this could/should be validated through pydantic is welcome. Thanks!

```py
from typing import List, Optional
from pydantic import BaseModel


class BaseOrg(BaseModel):
    orgid: int
    name: str
    parentid: int
    level: int
    id: int
    path: List[int]


class Level1Org(BaseOrg):
    children: Optional[List[BaseOrg]]


class Level2Org(Level1Org):
    children: Optional[List[Level1Org]]


class Level3Org(Level2Org):
    children: Optional[List[Level2Org]]


class Level4Org(Level3Org):
    children: Optional[List[Level3Org]]


class Level5Org(Level4Org):
    children: Optional[List[Level4Org]]

...
```

**Comment by samuelcolvin** [comment]
I would say self-referencing models and maybe validators would be the best way to go, or what you have above and worry about something more complex when you need it.

**Comment by foreverseer** [comment]
this is very simple
`
class Node(BaseModel):
    title: str
    children: List['Node']
`
yes, just use string 'Node', python can smart find it
