### ISSUE TITLE
How to pickle a generic pydantic class?

### ISSUE THREAD

**Issue by joel314** [samuelcolvin/pydantic#1667]
Hi,

I am trying to pickle a pydantic generic model as illustrated below, using Python 3.7.6 and Pydantic 1.5.1:

```
import pickle
from typing import TypeVar, Generic
from pydantic import BaseModel
from pydantic.generics import GenericModel

T = TypeVar('T')


class MyClass(BaseModel):
    pass


class GenericClass(GenericModel, Generic[T]):
    value: T


obj = MyClass()
instance = GenericClass[MyClass](value=obj)

pickle.dumps(instance)

```

This piece of code generates this error:
```
_pickle.PicklingError: Can't pickle <class '__main__.GenericClass[MyClass]'>: 
attribute lookup GenericClass[MyClass] on __main__ failed
```

It seems to be an error related specifically to pydantic generic models, as I am able to pickle non generic pydantic objects and generic objects that are not pydantic.

Am I doing something wrong or is this not supported yet? 
Thanks for your help!

**Comment by samuelcolvin** [comment]
Looks like it's not currently supported.

Should be possible to fix, but it's not a priority for me.

**Comment by joel314** [comment]
Hi Samuel,

Thanks for your answer and for your great work.
Looking forward to the fix when time allows,

Joël.

**Comment by MrMrRobat** [comment]
I was able to solve this problem by setting the attribute with new class to the module. Will make a PR soon.

**Comment by MrMrRobat** [comment]
Found out that this issue relates not only to generic models, but to any dynamically created model not listed in its module `globals`.

**Comment by captainvera** [comment]
This would be a great feature to add as the inability to pickle generic classes prohibits using these classes for deep learning configurations as multi-gpu setups like [PyTorch Dataparallel](https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html) require pickling capacity of the models.

**Comment by ndavydovdev** [comment]
I'm using this hack

```
class PatchedModel(BaseModel):
    def __getstate__(self) -> 'DictAny':
        """
        Pickling of generic models doesn't work
        this hack fixes it
        """
        state_dict = self.__dict__.copy()
        for key, value in state_dict.items():
            if isinstance(value, GenericModel) and value.__class__.__concrete__:
                state_dict[key] = value.__class__.__base__(**value.dict())
            if (
                    isinstance(value, list)
                    and value
                    and isinstance(value[0], GenericModel)
                    and value[0].__class__.__concrete__
            ):
                state_dict[key] = [v.__class__.__base__(**v.dict()) for v in value]
        return {'__dict__': state_dict, '__fields_set__': self.__fields_set__}

```
