### ISSUE TITLE
Is it necessary that ModelField.default is set to static value from default_factory at import time?

### ISSUE THREAD

**Issue by anentropic** [samuelcolvin/pydantic#1670]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: False
                 install path: /virtualenvs/QajdTuIM-py3.7/lib/python3.7/site-packages/pydantic
               python version: 3.7.7 (default, Jun 24 2020, 15:45:42)  [Clang 10.0.1 (clang-1001.0.46.4)]
                     platform: Darwin-18.7.0-x86_64-i386-64bit
     optional deps. installed: ['email-validator']
```

I'm trying to do some stuff with dynamically created models, one of which has a field with `Field(default_value=my_factory)`

I was expecting that `my_factory` would only be called at runtime. Instead there is [code](https://github.com/samuelcolvin/pydantic/blob/329b1d3e7b32bd72a4db2d122ef0e325c5725741/pydantic/fields.py#L299) in `ModelField.infer`, which is called by `ModelMetaclass.__new__` at import time, which calls the default factory and gets a value (which presumably is never used) and sets it as the `default` on the newly created `ModelField`.

This value doesn't influence the type inference (`annotation` attr) and `default_factory` is called as expected when instantiating the model at runtime. I haven't looked any deeper in the code, but it seems like this `default` value must be unnecessary?

```py
from datetime import datetime
from pydantic import BaseModel, field

class Model(BaseModel):
    dt = Field(default_factory=datetime.now)

mf = Model.__fields__['dt']
# this value should never be used for anything in practice?
mf.default
Out[15]: datetime.datetime(2020, 6, 29, 17, 33, 20, 799276)

# default_factory is called fresh for each instantiation as expected
m = Model()
m.dt
Out[7]: datetime.datetime(2020, 6, 29, 17, 33, 26, 230211)

m = Model()
m.dt
Out[9]: datetime.datetime(2020, 6, 29, 17, 33, 31, 790472)
```

If nothing else it is a small piece of extra work that could be avoided.

I'm sure I will find a workaround for what I am trying to do, which is an awkward thing where the `default_factory` returns an instance of a dynamically created model which initially doesn't exist. But that's how I noticed this quirk, maybe it can be cleaned up (or maybe has some useful purpose I haven't perceived).

**Comment by PrettyWood** [comment]
Hello @anentropic 
This should have been fixed by https://github.com/samuelcolvin/pydantic/pull/1504, which will be in pydantic 1.6.
Could you try with the `master` branch and make sure it works as expected ?

**Comment by samuelcolvin** [comment]
i'l release v1.6 tomorrow.
