### ISSUE TITLE
NotDigitError should be more generic

### ISSUE THREAD

**Issue by ricardo8990** [samuelcolvin/pydantic#1675]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /Users/ricardosanchez/Documents/Projects/cuenca-validations/venv/lib/python3.7/site-packages/pydantic
               python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24)  [Clang 6.0 (clang-600.0.57)]
                     platform: Darwin-19.5.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
from pydantic import NotDigitError

raise NotDigitError
# pydantic.errors.NotDigitError: card number is not all digits
```

The error message and code for `NotDigitError` says `card number is not all digits` and `payment_card_number.digits`. However, this error could refer to more cases than card numbers. 
https://github.com/samuelcolvin/pydantic/blob/259a1a0ff8eb9a0c4450331b9bae6730d55b9124/pydantic/errors.py#L517-L519

**Comment by samuelcolvin** [comment]
I think this error should remain specific to cards, especially since the code is already specific.
