### ISSUE TITLE
Support alternative value resolution for BaseSettings

### ISSUE THREAD

**Issue by ofek** [samuelcolvin/pydantic#1676]
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: C:\Users\ofek\AppData\Local\Programs\Python\Python38\Lib\site-packages\pydantic
               python version: 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.19041-SP0
     optional deps. installed: []
```

My use case is I'm reading a toml config file and passing what is read directly to the model constructor. However, I have no way to allow users env var or .env overrides.

Essentially, configs persisted to disk cannot benefit from BaseSettings. Or did I miss something?

**Comment by samuelcolvin** [comment]
This should be possible, you might just need to reimplement some of [`env_settings.py`](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/env_settings.py).

**Comment by ofek** [comment]
Is it a 👎 for this feature then?

**Comment by samuelcolvin** [comment]
I don't think it should be possible to implement what you need without changes to pydantic.

If that's possible I would rather not make any changes in the library.

If it's not possible or very annoying for some reason, please come back with requests foe specific changes and we'll consider them.
