### ISSUE TITLE
in typing.Union giving different output for different argument order

### ISSUE THREAD

**Issue by arvindjangra1996** [samuelcolvin/pydantic#1677]
# Bug

Hey, Thanks for the great library. 
I ran into an issue. Argument order in Union should not affect the output.

```
from pydantic import BaseModel  
from typing import List, Optional, Mapping, Union, Any

class MyMessage(BaseModel):
    data1 : Union[Mapping[str,Any], List[str]]
    data2:  Union[List[str], Mapping[str,Any]]

d = {'data1': ['ab'], 'data2': ['ab'] }
msg = MyMessage(**d)
assert msg.data1 == {'a': 'b'} # <--------------------------------
assert msg.data2 == ['ab'] 
```

why data1 is converted into a dict ?? This should be list just like data2.
And this is happening only when i pass a string of length 2 in data.

**Comment by PrettyWood** [comment]
Hello @arvindjangra1996 
This is a know issue. See #619 and #1423 for more information.
