### ISSUE TITLE
Mypy crashes with the pydantic mypy-plugin

### ISSUE THREAD

**Issue by Iftahh** [samuelcolvin/pydantic#1680]
# Bug

Mypy crashes with the pydantic mypy-plugin   with assertion `AssertionError: Must not defer during final iteration`

Use case:
I have a bunch of "predicate" functions which get arguments from UI.  I wanted to add json schema and validation so I took the time and converted them from pure functions to Pydantic classes, with a __call__ method.

To get some common functionality I added a metaclass that extends `ModelMetaclass`, and a base class that all predicate classes extend (see code below).

The code works just fine  (thank you for the awesome library!)

but MyPy *with the pydanyic mypy-plugin* crashes when it reaches the class decleration  - see crash below.
I would open an issue for Mypy - but it doesn't crash if I don't use the plugin so I assume its the plugin at fault.

```
mypy --version
0.781
```

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: ~/.virtualenvs/bt/lib/python3.8/site-packages/pydantic
               python version: 3.8.0 (default, Jan 23 2020, 14:58:36)  [Clang 10.0.1 (clang-1001.0.46.4)]
                     platform: macOS-10.14.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

The Mypy crash  (output of `mypy --no-incremental --config-file=mypy.ini src --show-traceback`)
```
src/predicate_types.py:119: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.781
Traceback (most recent call last):
  File "mypy/semanal.py", line 4691, in accept
  File "mypy/nodes.py", line 676, in accept
  File "mypy/semanal.py", line 536, in visit_func_def
  File "mypy/semanal.py", line 568, in analyze_func_def
  File "mypy/semanal.py", line 4419, in defer
AssertionError: Must not defer during final iteration
src/predicate_types.py:119: : note: use --pdb to drop into pdb
```

Code:
```py

# common class properties at the metaclass:

class BasePredicateMetaclass(ModelMetaclass):
    @property
    def description(cls) -> str:
        return cls.__doc__ or cls.__call__.__doc__ or ""

    @property
    def name(cls) -> str:
        return camel_to_snake(cls.__name__.replace("Predicate", ""))

    @property
    def possible_results(cls) -> List[str]:
        return_type = cls.__call__.__annotations__.get("return")
        if return_type:
            assert issubclass(return_type, Enum), "Expected predicate functions to return None or Enum"
            return [rt.name for rt in return_type]
        return []


######### MYPY crashes on this line below ###############
class BasePredicate(GenericModel, Generic[ExecContextType], abc.ABC, metaclass=BasePredicateMetaclass):
    deprecated: ClassVar[Optional[str]] = None

    class Config:
        allow_mutation = False
        extra = Extra.forbid

    @classmethod
    def schema(cls, by_alias: bool = True) -> Dict[str, Any]:
        _schema = super().schema(by_alias)
        _schema["title"] = cls.name
        if cls.deprecated:
            _schema["deprecated"] = cls.deprecated
        _schema["possible_results"] = cls.possible_results
        return _schema

    @abc.abstractmethod
    def __call__(self, execution_context: ExecContextType):
        pass


# the actual predicates look like this:

class XMoreThanYPredicate(BasePredicate):
     x: int
     y: int
     def __call__(self, execution_context: ExecContext) -> YesNoResult:
          return YesNoResult.yes if self.x > self.y else YesNoResult.no
```

**Comment by samuelcolvin** [comment]
I'm afraid this is quite "far out" in terms of pydantic usage, I'm not surprised the mypy extension can't cope.

If you can find a simple fix in the pydantic-mypy extension, I'd happily accept a PR to fix it. Otherwise I doubt I'll have time to work on this.

**Comment by Iftahh** [comment]
Thanks for looking into it  
I was expecting a reply of this sort,  but was hopeful you see something that I don't :-)

I did try to write a minimalistic example to submit, but my minimal example passed mypy+plugin without any crash!
So I ended up writing the complex example here.

I'll try to debug mypy plugin, when I get time...  worse case scenario I'll learn something about Mypy plugins 👍
Feel free to close this issue if you want

**Comment by samuelcolvin** [comment]
Closing for now, but come back to me if you find anything useful.
