### ISSUE TITLE
Field with dictionary key matching

### ISSUE THREAD

**Issue by tomzx** [samuelcolvin/pydantic#1683]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: False
                 install path: G:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\...\Lib\site-packages\pydantic
               python version: 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-7-6.1.7601-SP1
     optional deps. installed: ['typing-extensions']
```

Hello!

I'm trying to find how to properly implement a field that would be a dictionary with fixed keys and where the remaining keys are expected to be of another type.

Example object I'd like to build
```py
Container(
    my_field: {
        "one_key": "demo",
        "another_key": 3,
        # For explanation purposes, the remaining keys would be of the bool type
        # Those keys are dynamic and thus cannot be directly typed
        "other_key": False,
        "yet_another_key": True,
    }
)
```

The following code "works", but the additional properties are not validated since they don't have a schema defined.

```py
from pydantic import BaseModel, Extra

class Container(BaseModel):
    my_field: DictWithKeyMatching

class DictWithKeyMatching(BaseModel):
    one_key: str
    another_key: int

    class Config:
        extra = Extra.allow
```

Looking at the [JSON schema properties documentation](https://json-schema.org/understanding-json-schema/reference/object.html#properties), what I would want is to be able to define the type applied on `additionalProperties`. I did a quick search through the code base for `additionalProperties` but it's unclear to me whether this is already supported.

I thought of using
```py
from pydantic import BaseModel, Extra

class Container(BaseModel:
    my_field: DictWithKeyMatching

class DictWithKeyMatching(BaseModel):
    __root__: Dict[str, TypeForRemainingKeys]
    one_key: str
    another_key: int
```
but this raises
```
ValueError: __root__ cannot be mixed with other fields
```

My question is: what is the suggested implementation approach to this problem?
Thanks!

**Comment by samuelcolvin** [comment]
You should be able to achieve this with validators and customised schema, but I don't think there's a more elegant way.

I guess we could add a special field to validate "extra", something like `__extra__`. If that's something you'd like, it might be best to create a new field specifically requesting it.

Alternatively, if you need more details on how to get something working now, let me know and I'll add an example.

**Comment by tomzx** [comment]
Thanks @samuelcolvin!

**Comment by vnadhan** [comment]
> 

@samuelcolvin I have the same usecase here. Could you provide me an example? Thanks!

**Comment by sisp** [comment]
@samuelcolvin Same here. Could you provide an example how to implement this use case? I'd also need to generate the schema properly, i.e. `additionalProperties` (or actually even `patternProperties`) mixed with regular `properties`. Any help is much appreciated! :pray:
