### ISSUE TITLE
how to enforce uniqueness of attributes across all instances

### ISSUE THREAD

**Issue by RafalSkolasinski** [samuelcolvin/pydantic#1685]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /home/rskolasinski/miniconda3/envs/i3-flow/lib/python3.7/site-packages/pydantic
               python version: 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50)  [GCC 7.5.0]
                     platform: Linux-5.4.0-40-generic-x86_64-with-debian-bullseye-sid
     optional deps. installed: []
```

```py
import pydantic

class Group(BaseModel):
    name: str


g1 = Group(name="a")
g2 = Group(name="a")
```

I wonder if this is possible to somehow enforce uniqueness of `name` across all instances of `Group` objects.

It seems that in "vanilla" Python the good approach would be to use [metaclass](https://stackoverflow.com/questions/34818622/ensure-uniqueness-of-instance-attribute-in-python) approach but not sure how well it would play with `pydantic`.

**Comment by PrettyWood** [comment]
Hello @RafalSkolasinski 
Why not just add a validator on name and assert the name is not in a global list of names ? (Which is more or less what is done via metaclass / registry)

**Comment by RafalSkolasinski** [comment]
Thanks @PrettyWood, will give it a shot!
