### ISSUE TITLE
Get deep attribute with orm_mode

### ISSUE THREAD

**Issue by antonioIrizar** [samuelcolvin/pydantic#1689]
# Question
Hi!

How can I access to a deep attribute with orm_mode = True?

For example:
Response I want:

```json
{
  "fake_A": 1,
  "fake_d": "fuzzy"
}
```
My models:

```py
class A:
    a = 1
    b = '2'

class B:
    d = 'fuzzy'
    c = A()
```

Pydantic models:

```py

class Fake(BaseModel):
    a: int = Field(alias='fake_a') # source='c.a'  like django?
    d: int = Field(alias='fake_d')

     class Config:
         orm_mode = True
         allow_population_by_field_name = True
```

```py
Fake.from_orm(B())
```

On other framekors like Django you can get the ```a``` attribute of Class A throung Class B with ```source='c.a' ```

How can I do it with Pydantic?

**Comment by samuelcolvin** [comment]
Yes, but currently it's not trivial.

You need to subclass and customize `GetterDict`:

https://github.com/samuelcolvin/pydantic/blob/44616e35cb0ddd97af07b95d7209176a29bfea49/pydantic/utils.py#L347-L352

Then use that as the `getter_dict` attribute of `BaseConfig`:

https://github.com/samuelcolvin/pydantic/blob/44616e35cb0ddd97af07b95d7209176a29bfea49/pydantic/main.py#L118
