### ISSUE TITLE
docstring inconsistent of several functions in `datetime_parse.py`

### ISSUE THREAD

**Issue by YannLuo** [samuelcolvin/pydantic#169]
Hello!
I'm doing some research about document inconsistence.

I run  ```
monkeytype run `which pytest`
``` to get the runtime type of functions/methods in test cases and find that `parse_date` in `datetime_parse.py` receives parameters of date, int, float and str type in given test cases, which is inconsistent with its docstring "Parse a string and return a datetime.date". The same as functions `parse_time`, `parse_datetime` and `parse_duration`.

I'm uncertain weather these should be regard a document inconsistence ? And it would be fine if you can modify inconsistent docstring :)

**Comment by samuelcolvin** [comment]
The tests are right and the docstring is wrong, `parse_time`, `parse_datetime` and `parse_duration` should be able to take string, int, float, datetime's etc.

PR welcome to update the docs and type annotations.

**Comment by YannLuo** [comment]
PR has update in #173 .
