### ISSUE TITLE
Ways to handle dynamic schema references

### ISSUE THREAD

**Issue by phylogram** [samuelcolvin/pydantic#1693]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.5.1
pydantic compiled: True
install path: /home/[…]/anaconda3/lib/python3.7/site-packages/pydantic
python version: 3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0]
platform: Linux-5.3.0-62-generic-x86_64-with-debian-buster-sid
optional deps. installed: ['typing-extensions']
```
_This is not the production environment - production env will be the FastApi-Docker-Container_

### Behavior needed

I have a graph class, which can contain arbitrary nodes, as long as they are inheriting from a distinct class and provide a schema, which fields should be used for serialization. The graph class should be (un-) serializable with all its nodes and the correct classes/fields of them.

### Solution found

I am migrating from marshmallow now, and this is how I solved it there: I built a wrapper class for all nodes, which create a schema at runtime. When serializing they add the name of nodes class and call the schema on the node to dump and add this dump as a property of their own dump. When unserializing they look up the name of the node, dynamically create a schema, with the schema of the node to reference as property, and so unserialization works out of the box.

 As far as I see, this could work in pydantic as well.

### Question

Would you know a better/another way to achieve the wanted behavior? Or any other thoughts on the subject :-)?

Thanks!

Philip

**Comment by samuelcolvin** [comment]
This should work, but you can probably use just a `BaseModel` or a very thin wrapper thereof for the subfields. [`__root__`](https://pydantic-docs.helpmanual.io/usage/models/#custom-root-types) might help you.
