### ISSUE TITLE
PydanticModel().dict(exclude_none=True) from Config class

### ISSUE THREAD

**Issue by jhagege** [samuelcolvin/pydantic#1696]
Hi, is it possible to use a parameter to specify to automatically use the option "exclude_none=True" from the Config class of a Pydantic model ?

I'd like to encapsulate this logic and not require from users of the model to know about this option.

Thanks !

**Comment by PrettyWood** [comment]
Hello @jhagege!
There is currently no way of doing it directly in the Config. It could maybe be added to https://github.com/samuelcolvin/pydantic/issues/660.
In the meantime I reckon you can just override the default value in your own `BaseModel`:
```python
class NoNoneBaseModel(BaseModel):
    def dict(self, exclude_none=True, **kwargs):
        return super().dict(exclude_none=exclude_none, **kwargs)
```
```python
class M(NoNoneBaseModel):
    a: str = None
    b: str

m = M(b='a')
assert m.dict() == {'b': 'a'}
assert m.dict(exclude_none=False) == {'a': None, 'b': 'a'}
```

**Comment by jhagege** [comment]
Great, thanks much !
