### ISSUE TITLE
add a required ports kwarg to urls

### ISSUE THREAD

**Issue by flapili** [samuelcolvin/pydantic#1702]
# Feature Request

this feature will add a possibility to force a port to urls

example of my use case:
```py
from logging.handlers import DEFAULT_TCP_LOGGING_PORT
from pydantic import BaseSettings, Field, stricturl

class Config(BaseSettings):
    TCP_logging : stricturl(allowed_schemes=["tcp"], require_port=True) = f"tcp://127.0.0.1:{DEFAULT_TCP_LOGGING_PORT}"
```
a other use case could be replace
```py
from pydantic import BaseSettings, Field

class Config(BaseSettings):
    uvicorn_host: str = "0.0.0.0"
    uvicorn_port: int = Field(8000, gt=0, lt=2**16)
```
for
```py
from pydantic import BaseSettings, AnyHttpUrl

class Config(BaseSettings):
    uvicorn_server: AnyHttpUrl(require_port=True) = "http://0.0.0.0:8080"
```

If you think this proposition make sence I could look for a PR

ps: for the second use case maybe a kind of "bindUrl"/"bindAddress" could be better ?

**Comment by samuelcolvin** [comment]
I think this would be best achieved by either subclassing `AnyUrl` or using a validator on the `Config` class.

I doubt this is a common enough requirement to add it to `AnyUrl` or its subclasses, as per #1665 I want to move the other way and remove `user_required` in v2.
