### ISSUE TITLE
How to enforce IDE (VSCode) showing con* parameters options?

### ISSUE THREAD

**Issue by lowercase00** [samuelcolvin/pydantic#1707]
While working with `constr` I have to keep typing "max_length=" several times.
Is there anyway to get the autocomplete feature on VSCode?

Is this something that would need a plugin?
Or am I just misconfiguring my IDE?

Thanks!

![Screen Shot 2020-07-11 at 01 39 26](https://user-images.githubusercontent.com/21188280/87216610-a8178800-c317-11ea-8aad-f767c39b1e25.png)

**Comment by samuelcolvin** [comment]
Would need a custom plugin.

There's already one for pycharm but nothing that I know of for vacode.
