### ISSUE TITLE
Pydantic 1.6 does not validate nested models when using a default_factory

### ISSUE THREAD

**Issue by jlowin** [samuelcolvin/pydantic#1710]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6
            pydantic compiled: True
                 install path: /usr/local/Caskroom/miniconda/base/envs/server/lib/python3.8/site-packages/pydantic
               python version: 3.8.3 (default, Jul  2 2020, 11:26:31)  [Clang 10.0.0 ]
                     platform: macOS-10.15.5-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

I'm aware that [validation does not apply to default values](https://github.com/samuelcolvin/pydantic/issues/1488), but it appears that it is no longer applied to *user-provided* values that have a default factory value, either. If this is expected, I'm not sure if I saw it in the documentation or changelog. 

```py
from pydantic import BaseModel, Field
from typing import List

class Child(BaseModel):
    x: int

class Parent(BaseModel):
    children: List[Child] = Field(default_factory=list)


p = Parent(children=[{'x':1}, {'y':2}])
```

In Pydantic 1.5.1, an error is raised because the second child fails to validate (it is missing required value 'x')

In Pydantic 1.6, the Parent object is instantiated successfully and contains two dicts:

```py
print(p)
# children=[{'x': 1}, {'y': 2}]
```

To avoid this and recover the expected behavior, `validate_all` must be set on the `Parent` class. However, since I'm providing the child value, I'm surprised that I had to ask for it to be validated.

**Comment by samuelcolvin** [comment]
This is definitely a bug, probably caused by the changes in #1691, specifically removing `alwasy=True` from `list` and `set` child fields.

That it turn was required to solve a problem that came up in #1627.

I see that this is urgent, but I'm flat out with work, will try to fix when I can. @PrettyWood do you have any bright ideas how to solve this without a different regeression?

**Comment by jlowin** [comment]
Perhaps this is a consequence of the issue described in #1566 (and docs update #1592)? Does applying nested models implicitly set `each_item=True` with a default validator?

**Comment by jlowin** [comment]
Ah sorry I see we just crossed messages. Ok, bittersweet glad to hear it :) I'll review the issues you linked and see what we can do in the meantime. Thank you!

**Comment by PrettyWood** [comment]
Hmmm I see I'm sorry for that. I'll have a look as soon as I can (probably on monday in the train).

**Comment by PrettyWood** [comment]
Edit: the bug was way easier than I thought as it was only due to #1504. If any other has the same issue, do not hesitate to try out the fix to make sure there is no further regression.

**Comment by vladarefiev** [comment]
Hey everybody. I just picked up the same example from 1st comment, but without list:

```py
from pydantic import BaseModel, Field
from typing import List

class Child(BaseModel):
    x: int

class Parent(BaseModel):
    child: Child


p = Parent(child={'y':2})
```

```sh
p.child
<class '__main__.Child'>

p.child.x
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: type object 'Child' has no attribute 'x'

p.child.y
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: type object 'Child' has no attribute 'y'
```

Is it expected behaviour or is it a bug?

**Comment by samuelcolvin** [comment]
This bug relates to pydantic 1.6, please upgrade to the newest version of pydantic.
