### ISSUE TITLE
Generate Aliases for Schema Extras

### ISSUE THREAD

**Issue by timbmg** [samuelcolvin/pydantic#1715]
Given that I have a schema like this:

```python3
from pydantic import BaseModel

def to_camel_case(snake_case: str):
    words = snake_case.split("_")
    return "".join([words[0].lower()] + [word.capitalize() for word in words[1:]])


class CamelBaseModel(BaseModel):
    class Config:
        alias_generator = to_camel_case
        allow_population_by_field_name = True

class MyObj(CamelBaseModel):
    class Config:
        extra = "allow"
```

I would like to create objects like this:
```python
my_obj = MyObj(my_attr="test")
```
where now the alias generation should also apply to the extra fields. In this case MyObj should have an attribute ``myAttr`

**Comment by samuelcolvin** [comment]
Currently the best way to achieve this would be using [root validators](https://pydantic-docs.helpmanual.io/usage/validators/#root-validators)

**Comment by ericchansen** [comment]
Can anyone provide an example?

**Comment by nlile** [comment]
I just ran into this unexpected edge case. I ended up using an extremely simple root validator (nice to see in hindsight that's what @samuelcolvin suggested). For my current use case it works, but it has an unexpected effect I haven't gotten around to solving.

> Can anyone provide an example?

I'm probably too late to be useful @ericchansen, but hopefully this saves someone else an hour

https://gist.github.com/nlile/406f28b53dc821569885b71749869c96

**Comment by ericchansen** [comment]
Here's what I ended up doing. Hopefully this is also useful.

```python
import re
import sys
from typing import Callable, Dict

from pydantic import BaseModel, root_validator

if sys.version_info[:2] >= (3, 8):
    from collections.abc import Mapping
else:
    from collections import Mapping


pattern_1 = re.compile(r"(.)([A-Z][a-z]+)")
pattern_2 = re.compile("([a-z0-9])([A-Z])")


def call_func_on_all_keys(root: Dict, func: Callable) -> Dict:
    """Calls a function on all of the keys in a dictionary, recursively.

    Args:
        root (Dict): A dictionary.
        func (Callable): A function that operates on the key. This should
            return the new key.

    Returns:
        Dict: A dictionary with new keys.
    """
    new_root = {}
    for k, v in root.items():
        if isinstance(v, Mapping):
            new_root[func(k)] = call_func_on_all_keys(v, func)
        else:
            new_root[func(k)] = v
    return new_root


def camel_case_or_pascal_case_to_snake_case(camel_case_string: str) -> str:
    """Converts a camelCase or PascalCase string to snake_case."""
    string = pattern_1.sub(r"\1_\2", camel_case_string)
    string = pattern_2.sub(r"\1_\2", string).lower()
    return string


def snake_case_to_camel_case(snake_case_string: str) -> str:
    """Converts a snake_case string to camelCase."""
    string = "".join(
        x.capitalize() if i != 0 else x
        for i, x in enumerate(snake_case_string.split("_"))
    )
    return string


def snake_case_to_pascal_case(snake_case_string: str) -> str:
    """Converts a snake_case string to PascalCase."""
    string = "".join(x.capitalize() for x in snake_case_string.split("_"))
    return string


class OurBaseModel(BaseModel):
    @root_validator(pre=True)
    def make_it_all_snake_case(cls, values: Dict) -> Dict:
        snake_values = call_func_on_all_keys(
            values, camel_case_or_pascal_case_to_snake_case
        )
        return snake_values

    class Config:
        alias_generator = snake_case_to_camel_case
        allow_population_by_field_name = True
        extra = "allow"
```

**Comment by ponquersohn** [comment]
This is my take on this one. The benefit is that model_validate(by_alias=True) will work too.

from pydantic import (
    BaseModel,
    ConfigDict,
    model_validator,
    model_serializer,
)
from pydantic.alias_generators import to_camel, to_snake

class Example(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )

    @model_validator(mode="before")
    @classmethod
    def to_snake_for_all(cls, data):
        ret = {to_snake(k): v for k, v in data.items()}
        return ret

    @model_serializer(mode="plain")
    def to_camel_for_all(self, config):
        if config.by_alias:
            new_data = {}
            for k, v in self:
                new_data[to_camel(k)] = v
            return new_data
        return {k: v for k, v in self}
