### ISSUE TITLE
Pydantic 1.6: fields with default_factory cause parse_obj() to set fields to unparsed values

### ISSUE THREAD

**Issue by johnanthonyowens** [samuelcolvin/pydantic#1717]
# Bug

This is likely related to #1710 but does not explicitly involve validators. This would be a good candidate for a unit test to prevent future regressions.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.6
pydantic compiled: True
install path: /usr/local/lib/python3.8/site-packages/pydantic
python version: 3.8.3 (default, May 16 2020, 07:08:28)  [GCC 8.3.0]
platform: Linux-4.15.0-109-generic-x86_64-with-glibc2.2.5
optional deps. installed: []
```
Here is a self-contained example illustrating the problem:
```py

from pydantic import BaseModel, Field

class Inner(BaseModel):
    val: int = Field(0)

class Outer(BaseModel):
    inner_1: Inner = Field(default_factory=Inner)
    inner_2: Inner = Field(Inner())

default = Outer().dict() # default == {'inner_1': {'val': 0}, 'inner_2': {'val': 0}}
parsed = Outer.parse_obj(default)

print(parsed)
```
In 1.6, this prints:
`inner_1={'value': 'default'} inner_2=Inner(value='default')`
Note that `inner_1` is a dict, not an `Inner` object!

In 1.5.1 this prints:
`inner_1=Inner(val=0) inner_2=Inner(val=0)`

**Comment by PrettyWood** [comment]
Hello @johnanthonyowens you are right !
I added your example in the unit tests of the fix https://github.com/samuelcolvin/pydantic/pull/1712/commits/52ca25a3bfbb082af8a18f276c27095922600986
Thanks for the suggestion as the regression did not only impact the validation of nested models !
