### ISSUE TITLE
AttributeError: module 'pydantic.typing' has no attribute 'AnyType'

### ISSUE THREAD

**Issue by kaiwenw** [samuelcolvin/pydantic#1718]
For pydantic 1.6, I cannot import pydantic.typing.AnyType anymore.

**Comment by PrettyWood** [comment]
Hello @kaiwenw 
Yes it is in the [changelog](https://github.com/samuelcolvin/pydantic/releases/tag/v1.6):
> Update mypy, remove AnyType alias for Type[Any], #1598 by @samuelcolvin
You can just add the alias yourself if needed.
