### ISSUE TITLE
Howto validate references between list items

### ISSUE THREAD

**Issue by p3trus** [samuelcolvin/pydantic#1721]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: False
                 install path: C:\Users\XXXX\Documents\workspace\XXXX\.env\Lib\site-packages\pydantic
               python version: 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:11:50) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.14393-SP0
     optional deps. installed: ['typing-extensions']
```

I really enjoy pydantic so far but validation still troubles me. Let me briefly explain what I'd like to do using a simplified example.
I have some sort of Container class which holds a list of Item classes. Each item has a label. Some items have a reference field which points to one of the labeled items. I would like to validate that all references actually exist meaning that one of the items in the container list must have that label.

```py

import pydantic
from typing import Optional, List
class Item(pydantic.BaseModel):
    label: str
    reference: Optional[str]
        
        
class Container(pydantic.BaseModel):
    items: List[Item]
        
    @pydantic.validator('items')
    def _reference_is_valid(cls, v, values, config, field):
        # Should raise an exception for each incorrect reference
        return v

example = {
    'items': [
        {'label': 'A'},
        {'label': 'B', 'reference': 'F'}, # Error
        {'label': 'C', 'reference': 'B'}, # Exists
        {'label': 'C', 'reference': 'E'}, # Error
    ]
}
    
Container(**example)
```

Of course I can do a validator and manually loop over the items and check each reference. But how would I raise multiple errors then showing which item has an incorrect reference? The ErrorWrapper, used internally would be able to track the item index of the erroneous reference via the loc parameter but I'm not sure If I should raise that from a validator.

Alternatively, I could use the `each_item` parameter which would allow me to raise multiple errors but I don't know how I could access the other items to actually check.

**Comment by PrettyWood** [comment]
Hello @p3trus 
You indeed need to do the validation in the `Container` as you need the whole list for validation.
AFAIK there is currently no direct way to do what you want but doing it manually is quite easy.
I would personally go with something like this:

```python
from pydantic import BaseModel, validator
from pydantic.error_wrappers import ErrorWrapper, ValidationError
from typing import Optional, List


class Item(BaseModel):
    label: str
    reference: Optional[str]


class Container(BaseModel):
    items: List[Item]

    @validator('items')
    def should_have_valid_reference(cls, items: List[Item]):
        all_labels = {item.label for item in items}
        errors = [
            ErrorWrapper(ValueError(f'Invalid reference {item.reference}'), f'item {idx} {item}')
            for idx, item in enumerate(items)
            if item.reference is not None and item.reference not in all_labels
        ]
        if errors:
            raise ValidationError(errors, cls)
        return items


example = {
    'items': [
        {'label': 'A'},
        {'label': 'B', 'reference': 'F'},  # Error
        {'label': 'C', 'reference': 'B'},  # Exists
        {'label': 'C', 'reference': 'E'},  # Error
    ]
}

Container(**example)
```

Output
```
pydantic.error_wrappers.ValidationError: 2 validation errors for Container
items -> item 1 label='B' reference='F'
  Invalid reference F (type=value_error)
items -> item 3 label='C' reference='E'
  Invalid reference E (type=value_error)
```

Hope it helps !

**Comment by p3trus** [comment]
Thank you, this helps.
