### ISSUE TITLE
No way to have a proper Union[int, bool]

### ISSUE THREAD

**Issue by bentheiii** [samuelcolvin/pydantic#1723]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`
```
             pydantic version: 1.6
            pydantic compiled: True
                 install path: C:\py_envs\Python38\Lib\site-packages\pydantic
               python version: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
                     platform: Windows-10-10.0.19041-SP0
     optional deps. installed: ['typing-extensions']
```
The current method of handling `Union`s makes it impossible to specify a union of a string and an int without having no way to differentiate inputs of different types.

```py
from typing import Union

from pydantic import BaseModel


class A(BaseModel):
    x: Union[bool, int]
    y: Union[int, bool]


a = A(x=True, y=True)
print(type(a.x), type(a.y))  # <class 'bool'> <class 'int'>

a = A(x=0, y=0)
print(type(a.x), type(a.y))  # <class 'bool'> <class 'int'>
```

This is problematic if you want to differentiate the values dynamically by their type.

A trivial solution to this (and other confusing `Union` related behavior) when coercing to a `Union`, is to check whether the input type is already one of the `Union` args and if so, perform no conversion.

**Comment by PrettyWood** [comment]
Hello @bentheiii 
This is a know issue. See #619 and #1423 for more information.

**Comment by ilya-kolpakov** [comment]
I faced the same issue and the solution is to use the [strict types](https://pydantic-docs.helpmanual.io/usage/types/#strict-types) provided by pydantic. An example (tested on 1.9.1):

```python3
from typing import Union
from pydantic import BaseModel, StrictBool, StrictInt


class Basic(BaseModel):
    val: Union[bool, int]


class Strict(BaseModel):
    val: Union[StrictBool, StrictInt]


assert Basic(val=1).val == True
assert Strict(val=1).val == 1

```
