### ISSUE TITLE
how to get metaclass about Model where raise ValidationError

### ISSUE THREAD

**Issue by fronterender** [samuelcolvin/pydantic#1724]
question:
i want to get cls where raise ValidationError, for example
.....
class User(basemodel):
    name: str
....
@app.exception_handler(RequestValidationError)
def validation_handler(req, exc):
  # how can i get the  User Model in here
  return JSONResponse(content={ }, status_code=200)

**Comment by StephenBrown2** [comment]
I'm not entirely sure what the question is here, it may be better asked with the framework you're using, possibly FastAPI?

But if you want to return the JSON representation of a model I would check the docs: https://pydantic-docs.helpmanual.io/usage/exporting_models/#modeljson

```py
user = User()
return JSONResponse(content=user.json(), status_code=200)
```

More details are necessary to better answer your question.
