### ISSUE TITLE
Add __post_init__ to BaseModel/non-dataclasses

### ISSUE THREAD

**Issue by jessekrubin** [samuelcolvin/pydantic#1729]
It would be very nice if there were some sort of __post_init__ for the pydantic.BaseModel.

Probably wouldn't be too much work to add either (but IDK).

I can fork and pr the changes, but I would like to hear @samuelcolvin's/others thoughts before doing so

**Comment by rafaellehmkuhl** [comment]
I'm in the same situation.
In my case, I want to populate a list with references to methods of the class, both in a base class and in an inherited one:  

```
class Component(BaseModel):
    force_functions: List = []

    def __post_init__(self):
        self.force_functions.append(self.func1)

    def func1(self):
        pass

class SubComponent(Component):
    def __post_init__(self):
        self.force_functions.append(self.func2)

    def func2(self):
        pass
```

This is possible on dataclasses, but them I lose some of the BaseModel capabilities.

**Comment by jessekrubin** [comment]
@rafaellehmkuhl 

> This is possible on dataclasses, but them I lose some of the BaseModel capabilities.

💯 The basemodel is fire.

**Comment by rafaellehmkuhl** [comment]
@samuelcolvin just to better understand, why was this closed?

**Comment by samuelcolvin** [comment]
frankly because I was going through open issues trying to close them as fast as possible, and I thought from a glance that this was solved.

---

If you need to do validation (and might raise an error that prompts a `ValidationError`) you can use a [root validator](https://pydantic-docs.helpmanual.io/usage/validators/#root-validators) without `pre=True`.

If you don't need to raise validation errors, just override `__init__`, call `super()` then do your thing.

If neither of those solutions work, please let me know why and I'll re-open the issue.

**Comment by rafaellehmkuhl** [comment]
Understood.

Being pretty honest, I found the solution overriding `__init__` after my comment, but it adds a lot of boilerplate to every class that inherits from the base one (based on BaseModel), and eliminating the boilerplate, making classes declaration clear, is one of the big advantages that BaseModel and dataclass (among others) brings to the table.

I just thought that a similar `__post_init__` function would solve the problem (in a simple way, but I can be wrong) while maintaining the class declaration very clear.

**Comment by ryan4yin** [comment]
@rafaellehmkuhl @samuelcolvin @jessekrubin  agree with this. I'm also looking for some thing like `__post_init__` `__post_init_post_parse__` in `BaseSettings`.

I hope my `BaseSettings` can process the static configuration from env, and then generate some dynamic properties for those env.
overriding `__init__` is one of the solutions, but `__post_init__` is clearer.

**Comment by akvadrako** [comment]
> I just thought that a similar `__post_init__` function would solve the problem (in a simple way, but I can be wrong) while maintaining the class declaration very clear.

I was looking for `__post_init__` behavior with BaseModel and came across this bug. However it turned out that overriding `__init__` on a super class worked fine. I am using it to store the name of the subclass as a field:

```py
    def __init__(self, **kw):
        super().__init__(method=self.__class__.__name__.lower(), **kw)
```

I'm curious what is the use case where `__init__` requires boilerplate for each subclass.

**Comment by dphaine** [comment]
Thanks @akvadrako, that is helpful.

My implementations looks like this:

```
    def __init__(self, **kw):
        super().__init__(**kw)
        # --- Initialize and modify what is needed here ---
```

I would second / third the request to have a direct equivalent to @dataclass's __post_init__().   It's a great hook for initializing objects and cleaner-looking than the above!

**Comment by R0ll1ngSt0ne** [comment]
Overwriting __init__ results in missing parameter hints, which is a _huge_ drawback.

**Comment by jessekrubin** [comment]
> Overriding __init__ results in missing constructor parameter hints, which is a _huge_ drawback.
> 
> 

The [jsonbourne](https://github.com/dynamic-graphics-inc/dgpy-libs/blob/main/libs/jsonbourne/jsonbourne/pydantic.py) JsonBaseModel has a post init and doesn't have the param hinting problems; that said I still wish it (post init) were built into pydantic.

**Comment by dphaine** [comment]
You are right, losing those parameter hints with __init__ was a deal-breaker!

However, I was able to do what I used to do with __init__ and __post_init__ using Pydantic's root validators, either with pre=True or False depending on the need.  

Might this work for you?

**Comment by podj** [comment]
Hi guys, sorry for interrupting but the use of root validator is unwanted IMHO.
First, it is unclear because we use a validator to alter an instance without any real validations.
In addition, the root validator accepts a `values` dictionary which has zero type hints.
Using `self` is a much better solution in my opinion.

I really don't mind helping out and making a PR for that small (but very desirable) feature, I just want to make sure that the maintainers are on board with the idea :)

**Comment by samuelcolvin** [comment]
This has just been added (today) to be included in V2, as per #4516 pydantic now calls a function named `model_post_init` if defined.

This isn't documented yet (and won't be released until V2 goes out), but here's a test demoing it:

https://github.com/pydantic/pydantic/blob/594effa279668bd955e98f1cd5c036b37d3bbd40/tests/test_main.py#L1828-L1850

**Comment by podj** [comment]
Cool! Awesome feature and thank you for the quick response!

**Comment by dphaine** [comment]
Awesome, this is a great addition!

**Comment by ryukinix** [comment]
@samuelcolvin Just a question, why waiting for v2? There is any particular reason to hold this feature for so long? 

Context: After a long debug session using `__post_init__` to calculate dynamically some attribute, I saw that actually the project was using pydantic BaseModel instead dataclasses for this particular class... since this feature is not available, I maybe would have to refactor to use dataclasses.

**Comment by samuelcolvin** [comment]
because we're not actively work on v1.10, only issuing critical bug fixes.

We're not a big team and we have to priorities work. I choose to concentrate on finishing V2 and getting that released, rather than sticking plasters for V1.10

**Comment by ryukinix** [comment]
thx for the clarification about that @samuelcolvin good work on that.

**Comment by kim-youngseop-developer** [comment]
hi
i'm just a user using pydantic, and sincerely appreciate your work **@samuelcolvin**.
please understand that i'm not good at english :(

i was searching for the same need, and reached to this thread.
and from what I understood from reading this thread is that,
the feature will be on the v2 pydantic, but not available for now.

but i just wondering that how about using decorator with the current version,
and is this a bad idea for `BaseModel`?

```py

def construct_with(before_attribute: str = None, after_attribute: str = None):
    """
    ```
    >>> @construct_with(after_attribute = "__post_init__")
    ... class SampleModel(BaseModel):
    ...     foo: str
    ...     bar: str
    ... # define method to be called after the constructor
    ... def __post_init__(self, arguments: List[object] = None, knownarguments: Dict[str,object] = None):
    ...     # whatever you want ...
    ```
    """
    def decorate_redefined_constructor(cls):
        # hook the constructor from `cls` which is being decorated.
        constructor = cls.__init__

        # redefine `__init__` which is being wrapped with attributes
        def __init__(self, *arguments, **knownarguments):
            # if there is a specifed attribute name to call before the constructor
            if before_attribute:
                getattr(cls, before_attribute)(self, arguments, knownarguments)
            # inject the hooked constructor
            constructor(self, *arguments, **knownarguments)
            # if there is a specifed attribute name to call after the constructor
            if after_attribute:
                getattr(cls, after_attribute)(self, arguments, knownarguments)

        # replace `cls.__init__` with redefined `__init__(self, ...)`
        cls.__init__ = __init__
        return cls
```

```py
@construct_with(after_attribute = "__post_init__")
class SampleModel(BaseModel):
    foo: str
    bar: str

    def __post_init__(self, arguments: List[object] = None, knownarguments: Dict[str,object] = None):
        self.foo = "{self.foo} (after constructor)"
        self.bar = "{self.bar} (after constructor)"
        print(arguments, knownarguments) # () {'foo': 1, 'bar': 2}

# the intellisense can reach the annotations generated by pydantic.
# i'm using  windows 11 / python3.11 / vscode / pylance (extension) / python (extension)
sample = SampleModel(foo = "1", bar = "2")
# foo='1 (after constructor)' bar='2 (after constructor)'
print(sample)
```

thank you and have a great day!

**Comment by sachinruk** [comment]
@samuelcolvin, maybe I'm missing something with `model_post_init`

```python
import pydantic

class Config(pydantic.BaseModel):
    a: str = "a"
    def model_post_init(self, **kwargs):
        self.b = self.a + "b"
```

Is this how you add a new attribute `b` to your config?

When I do `config = Config()` and try to check on `config.b` it gives me `AttributeError: 'Config' object has no attribute 'b'`.

And if I do `config.model_post_init()` it gives me the following error:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-40991db77bc0> in <cell line: 1>()
----> 1 config.model_post_init()

<ipython-input-11-e5738e3343ca> in model_post_init(self, **kwargs)
      2     a: str = "a"
      3     def model_post_init(self, **kwargs):
----> 4         self.b = self.a + "b"
      5 

~/work/canva/tools/build/python/third_party/.venv/lib/python3.9/site-packages/pydantic/main.cpython-39-darwin.so in pydantic.main.BaseModel.__setattr__()

ValueError: "Config" object has no field "b"
```

**Comment by jessekrubin** [comment]
You need to declare b as a class var I think otherwise pydantic doesn't "allocate" a slot/accessor for it

**Comment by dmontagu** [comment]
By default, you can't set arbitrary attributes on BaseModels — you can only set the values of fields. You may be able to work around this with `model_config = dict(extra='allow')` but depending on usage, that may have other implications you don't want.

Another thing you can do is use PrivateAttribute, which might work for you, but will require that you put a leading `_` on the attribute name:
```python
from typing import Any

from pydantic import BaseModel, PrivateAttr


class User(BaseModel):
    a: str
    _b: str = PrivateAttr()  # the `= PrivateAttr()` is actually unnecessary, it is inferred from leading underscore

    def model_post_init(self, __context: Any) -> None:
        self._b = self.a + 'b'


my_user = User(a='a')
print(my_user)
#> a='a'
print(my_user._b)
#> ab
```

**Comment by jessekrubin** [comment]
@dmontagu Aha yes! that is what I meant to say.
