### ISSUE TITLE
Container class validator not called when submodel fails

### ISSUE THREAD

**Issue by p3trus** [samuelcolvin/pydantic#1731]
# Validator not called when submodel fails
I was under the impression that pydantic should evaluate the whole schema and report all found errors at once, but maybe thats wrong. Let's consider the following example

```py
import pydantic
from typing import Optional, List

class Item(pydantic.BaseModel):
    label: str
    reference: Optional[str]
        
        
class Container(pydantic.BaseModel):
    items: List[Item]
    
    @pydantic.validator('items', each_item=True)
    def _validate_item(cls, v, values, config, field):
        raise ValueError('Validator called even when an error occurs.')
    
    @pydantic.validator('items')
    def _validate(cls, v, values, config, field):
        raise ValueError('Validator not called when an error occurs.')
        
        return v

example = {
    'items': [
        {'label': 'A'},
        {'label': ['wrong_type']}, # Error
    ]
}
    
Container(**example)
```
The container has two validators, a regular one and an `each_item` one. In this example, the second item triggers a TypeError, correctly shown in the resulting error message. 

```py
ValidationError: 2 validation errors for Container
items -> 0
  Validator called even when an error occurs. (type=value_error)
items -> 1 -> label
  str type expected (type=type_error.str)
```

Additionally, the `_validate_item` method of the container is also called. The regular validator, however, is not. 
My question is why?

Conversely, when the `_validate` method is marked as a prevalidator like this
```py
    @pydantic.validator('items', pre=True)
    def _validate(cls, v, values, config, field):
        raise ValueError('Validator not called when an error occurs.')
        
        return v
```
it get's called but the others are not validated. Is there a way to get all errors to show up?

---

For reference:
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: False
                 install path: C:\Users\mh890176\Documents\workspace\RaptorSpecDB\.env\Lib\site-packages\pydantic
               python version: 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:11:50) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.14393-SP0
     optional deps. installed: ['typing-extensions']
```

**Comment by samuelcolvin** [comment]
for one field, you would need to do all the validation in one validator, since they won't both be called if the first raises an error.
