### ISSUE TITLE
Dynamically create_model that contains forward refs

### ISSUE THREAD

**Issue by remi-debette** [samuelcolvin/pydantic#1734]
# Question

Hi, I am asking this as a question but I feel it could be a bug. 

In my usecase I actually get type declarations (potentially with cycle deplendencies, optional, ...) dynamically at runtime.
I am building a static dict of those types and when it is ready, I will create the models with `create_model()` and apply `update_froward_refs()`.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /Users/A492YC/.virtualenvs/sam-quote-ujUy7lE3/lib/python3.7/site-packages/pydantic
               python version: 3.7.4 (default, Feb 17 2020, 12:06:24)  [Clang 11.0.0 (clang-1100.0.33.17)]
                     platform: Darwin-19.4.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

I think that this type dict would be enough to play the role of localns.
But apparently, the function call `update_froward_refs()` fails because such models do not have `cls.__module__`

A simplified implementation:

```py
import pydantic

test_types = {
    'Sub': {
        "name": (str, ...),
        "param": (str, ...)
    },

    'Main': {
        "name": (str, ...),
        "male": (bool, ...),
        "sub": ("Sub", ...)
    }
}


sub = test_types["Sub"]
sub_model = pydantic.create_model("Sub", **sub)
sub_instance = sub_model(**{
    "name": "hello",
    "param": "there"
})

main = test_types["Main"]
main_model = pydantic.create_model("Main", **main)
main_instance = main_model(**{
    "name": "world",
    "male": True,
    "sub": {
        "name": "hello",
        "param": "there"
    }
})

# Traceback (most recent call last):
#  File "<input>", line 31, in <module>
#   File "pydantic/main.py", line 336, in pydantic.main.BaseModel.__init__
#   File "pydantic/main.py", line 861, in pydantic.main.validate_model
# pydantic.errors.ConfigError: field "sub" not yet prepared so type is still a ForwardRef, you might need to call Main.update_forward_refs().
```

Because of the error above, I instead try to update_forward_refs on my dynamic model

```py
main_model.update_forward_refs(Sub=sub_model)

# Traceback (most recent call last):
#   File "<input>", line 1, in <module>
#   File "pydantic/main.py", line 663, in pydantic.main.BaseModel.update_forward_refs
# KeyError: None
```

Could you provide a way to implement this if I am missing something?

**Comment by samuelcolvin** [comment]
`localns` I think needs to be a dict of names -> classes, not names -> dicts of attributes.

I think you need something like `main_model.update_forward_refs(Sub=sub_model)`

**Comment by remi-debette** [comment]
Hi @samuelcolvin sorry I have not been entirely clear.
I was actually already doing the code you shared (I edited my sample code to reflect it).

The error stays the same: 
in the file main.py of pydantic, the code is:
```python
    @classmethod
    def update_forward_refs(cls, **localns: Any) -> None:
        """
        Try to update ForwardRefs on fields based on this Model, globalns and localns.
        """
        globalns = sys.modules[cls.__module__].__dict__.copy()

        ...
```

As I stated, the function call `update_forward_refs()` fails because such models do not have `cls.__module__`

I do not know if the implementation of pydantic.create_model is broken if I am supposed to do something else for the update_forward_refs to work.

**Comment by remi-debette** [comment]
Hi, 

I do not think this issue should be closed. 
Any way to reopen it, or should I create a bug issue?

**Comment by PrettyWood** [comment]
Hello @remi-debette,

You're right I think the error you mention is just because you run the code in a script.
I created a tiny fix to make it work.
You'll still need of course to write either
- `Sub = pydantic.create_model("Sub", **sub)` and use `main_model.update_forward_refs()`
- keep `sub_model` as a name and use `main_model.update_forward_refs(Sub=sub_model)`

**Comment by remi-debette** [comment]
Hi @PrettyWood ,

Thank you for your insight (and your PR)
In your understanding, if I put my custom defined types in python submodules and import them, my code should work as is?

**Comment by PrettyWood** [comment]
@remi-debette Exactly!

**Comment by remi-debette** [comment]
Anyways, I encountered this this while myself writing unit tests for implementing this feature in my codebase. (TDD mode)
So your PR would be very welcome to smooth that out.

Thanks

**Comment by remi-debette** [comment]
Hi @PrettyWood @MrMrRobat

Just to keep you updated, I tried to split my sample code and import the models from another models.py
It actually does not work in the same version of pydantic (1.5.1):

```python
from models import sub_model, main_model

sub_instance = sub_model(**{
    "name": "hello",
    "param": "there"
})


main_model.update_forward_refs(Sub=sub_model)
# Traceback (most recent call last):
#   File "/Users/A492YC/Library/Application Support/JetBrains/PyCharm2020.2/scratches/scratch_3.py", line 9, in <module>
#     main_model.update_forward_refs(Sub=sub_model)
#   File "pydantic/main.py", line 663, in pydantic.main.BaseModel.update_forward_refs
# KeyError: None
```

So actually there is no workaround currently.

Thank you!

**Comment by MrMrRobat** [comment]
@remi-debette please, see temporary workaround in https://github.com/samuelcolvin/pydantic/pull/1686#issuecomment-692327793
