### ISSUE TITLE
Doesn't correctly validate when type is Enum

### ISSUE THREAD

**Issue by zabzug-pfpt** [samuelcolvin/pydantic#1735]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /Users/<redacted>/.venvs/<redacted>/lib/python3.6/site-packages/pydantic
               python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55)  [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
                     platform: Darwin-18.7.0-x86_64-i386-64bit
     optional deps. installed: []
```
Type validation works as expected when using children of Enums (e.g., [here](https://pydantic-docs.helpmanual.io/usage/types/#enums-and-choices)) but not when using Enums themselves.

```py
from enum import Enum

from pydantic import BaseModel


class FruitEnum(Enum):
    pear = 'pear'
    banana = 'banana'


class CookingModelA(BaseModel):
    fruit: FruitEnum


print(CookingModelA(fruit=FruitEnum.banana)) # works as expected


class CookingModelB(BaseModel):
    fruit: Enum


print(CookingModelB(fruit=FruitEnum.banana)) # fails validation with error
    """
    ValidationError: 1 validation error for CookingModelB
    fruit
      value is not a valid enumeration member; permitted:  (type=type_error.enum; enum_values=[])
    """
```
My expectation is that both should validate correctly, since `FruitEnum` is an instance of `Enum`.

**Comment by zabzug-pfpt** [comment]
To be clear, I understand why there is a need for the type of validation that is currently provided: [ensuring that an argument is one of the authorized values in a given enum](https://github.com/samuelcolvin/pydantic/blob/70d531ff4c1ae3980615cee07a948fe49b1bc7cf/pydantic/validators.py#L248).

But there is also a need to be able to check that an argument is an instance of `Enum`, without caring about what the keys and values of that `Enum` are.

**Comment by PrettyWood** [comment]
Hi @zabzug-pfpt 
I agree with you it should be a valid syntax. I opened a PR to add a basic support of `Enum` as valid type.
Feel free to try it out.

**Comment by zabzug-pfpt** [comment]
Thanks so much @PrettyWood! I added one small testing comment on your PR, otherwise it looks good!

**Comment by AtaiAmbus** [comment]
This is not the exact scenario in the issue, but there is still a problem in the case where there is a middle class inheriting from enum without specifying values. If you have something like

```python
class SpecialEnum(Enum):
    def do_stuff(self):
         # some cool operation
```

And then have

```python
class MySpecialEnum(SpecialDescriptorEnum):
   A = 1
   B = 2 
```
And then

```python
class MyModel(BaseModel):
    my_field: SpecialEnum
```

I want pydantic to validate that my_field is some instance of a SpecialEnum subclass.
However, pydantic uses its enum member validator instead, resulting in what will always be a `ValidationError` — since SpecialEnum was only ever meant to provide functionality or interface, and not values.

**Comment by samuelcolvin** [comment]
Let's look at getting this right in v2. We can't change it before then.
