### ISSUE TITLE
Generate titles for model properties (using `schema_json()`) only if explicitly provided

### ISSUE THREAD

**Issue by abunuwas** [samuelcolvin/pydantic#1740]
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.6.1
pydantic compiled: True
install path: /Users/j/.local/share/virtualenvs/asfd-asdf-2c-XNDzz/lib/python3.7/site-packages/pydantic
python version: 3.7.5 (default, Nov  1 2019, 02:16:32)  [Clang 11.0.0 (clang-1100.0.33.8)]
platform: Darwin-18.7.0-x86_64-i386-64bit
optional deps. installed: []
```
---
## Description

When generating JSON schemas out of Pydantic models, all outputs come persistently with a title keyword describing each property and each model. However, as per the [JSON Schema documentation](https://json-schema.org/understanding-json-schema/reference/generic.html), the `title` keyword is not a required descriptor for a property, it's optional:

>JSON Schema includes a few keywords, title, description, default, examples that aren’t strictly used for validation, but are used to describe parts of a schema.
**None of these “annotation” keywords are required**, but they are encouraged for good practice, and can make your schema “self-documenting”.

It should be the responsibility of the developer to include good titles for their models. Otherwise `titles` are not required, and a developer omitting a `title` may have reasons to do so. The fact that Pydantic picks up on the `title` keyword and generates a title version of the attribute or class name seems like an arbitrary behaviour. 

## Request
Would it be possible to change the implementation to make it optional to generate JSON Schemas with titles only if developer explicitly provides a title for the attribute? 

---
The script:
test.py
```py
from pydantic import BaseModel


class Item(BaseModel):
    attribute: str


item = Item(attribute='attribute')

print(item.schema_json())
```

```
$ python test.py | jq
```

```javascript
{
  "title": "Item",
  "type": "object",
  "properties": {
    "attribute": {
      "title": "Attribute",
      "type": "string"
    }
  },
  "required": [
    "attribute"
  ]
}
```

**Comment by samuelcolvin** [comment]
If you just need models without titles, you could use [`schema_extra`](https://pydantic-docs.helpmanual.io/usage/schema/#schema-customization) to remove `title`.

More generally, I'm basically opposed to this change, because:
1. No one else has asked for this
2. I can't think of any scenarios where it would be problematic
3. It would be a breaking change (it could be done in v2)
4. Making no title the default would mean many people not including titles in their schemas which could be useful

If enough other people really want to remove title-by-default, I'll consider it, but closing for now.

**Comment by xtay** [comment]
> If you just need models without titles, you could use [`schema_extra`](https://pydantic-docs.helpmanual.io/usage/schema/#schema-customization) to remove `title`.
> 
> More generally, I'm basically opposed to this change, because:
> 
> 1. No one else has asked for this
> 2. I can't think of any scenarios where it would be problematic
> 3. It would be a breaking change (it could be done in v2)
> 4. Making no title the default would mean many people not including titles in their schemas which could be useful
> 
> If enough other people really want to remove title-by-default, I'll consider it, but closing for now.

**you could use [schema_extra](https://pydantic-docs.helpmanual.io/usage/schema/#schema-customization) to remove title**

**Comment by xtay** [comment]
> If you just need models without titles, you could use [`schema_extra`](https://pydantic-docs.helpmanual.io/usage/schema/#schema-customization) to remove `title`.
> 
> More generally, I'm basically opposed to this change, because:
> 
> 1. No one else has asked for this
> 2. I can't think of any scenarios where it would be problematic
> 3. It would be a breaking change (it could be done in v2)
> 4. Making no title the default would mean many people not including titles in their schemas which could be useful
> 
> If enough other people really want to remove title-by-default, I'll consider it, but closing for now.

`json_schema_extra` is a model level config, is there any way i could specify to erase all the 'title' fields in the `model_json_schema` or `json_schema` call?

**Comment by erbenmo** [comment]
> I can't think of any scenarios where it would be problematic

This is problematic for MCP because generating too many titles can consume a huge amount of the LLM context window

**Comment by Kludex** [comment]
You can do this:
```py
from __future__ import annotations

from typing import TYPE_CHECKING
from pydantic.json_schema import GenerateJsonSchema

if TYPE_CHECKING:
    from pydantic.annotated_handlers import CoreSchemaOrField


class CustomGenerateJsonSchema(GenerateJsonSchema):
    def field_title_should_be_set(self, schema: CoreSchemaOrField) -> bool:
        return False
```
