### ISSUE TITLE
Unable to use custom config using @dataclass / deny all unknown fields

### ISSUE THREAD

**Issue by alvassin** [samuelcolvin/pydantic#1741]
I need to deny all unknown fields in my models. But when i tried to dig i found that it is not possible to control this behaviour (allow/deny/etc).

This works well:
```py
from pydantic import BaseModel

class Example(BaseModel):
    test: str

model = Example(test='works well')
```

But when i try to use custom config as [described in docs](https://pydantic-docs.helpmanual.io/usage/model_config/) it does not work:

```
from pydantic import BaseModel, Extra
from pydantic.dataclasses import dataclass


class MyConfig:
    extra = Extra.allow


@dataclass(config=MyConfig)
class Example(BaseModel):
    test: str

model = Example(test='does not work')
```

I see following output:
```
Traceback (most recent call last):
  File "/Users/alvassin/Work/example/t.py", line 13, in <module>
    model = Example(test='does not work')
  File "<string>", line 3, in __init__
  File "pydantic/main.py", line 363, in pydantic.main.BaseModel.__setattr__
AttributeError: __fields_set__
```

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /Users/alvassin/Work/example/env/lib/python3.7/site-packages/pydantic
               python version: 3.7.7 (v3.7.7:d7c567b08f, Mar 10 2020, 02:56:16)  [Clang 6.0 (clang-600.0.57)]
                     platform: Darwin-19.5.0-x86_64-i386-64bit
     optional deps. installed: []
```

**Comment by PrettyWood** [comment]
Hi @alvassin,

You shouldn't mix `@dataclass` and `BaseModel`. You can use `@dataclass` for most cases but it's less complete than `BaseModel` (see the [note](https://pydantic-docs.helpmanual.io/usage/dataclasses/) in the doc).
In your case I would stick with just `BaseModel` and do

```python
class Example(BaseModel):
    test: str

    class Config:
        extra = Extra.allow
```

Hope it helps!

**Comment by alvassin** [comment]
@PrettyWood not obvious interface. Thank you very much!
