### ISSUE TITLE
Validating nested dataclasses without class ownership

### ISSUE THREAD

**Issue by dylrich** [samuelcolvin/pydantic#1743]
# Question

Hi! I want to validate a model whose definition I don't control from a package we depend on. That model consists of nested dataclasses. I thought I'd be able to subclass that model with pydantic's `dataclass` decorator and it would work just fine, and it does, but only if the model I am subclassing doesn't have any nested dataclasses. Here's what I mean:

```py
from dataclasses import dataclass
from pydantic.dataclasses import dataclass as pydataclass

# FROM AN EXTERNAL PACKAGE
@dataclass
class NavbarButton:
    href: str


@dataclass
class Navbar:
    button: NavbarButton
# END EXTERNAL PACKAGE

@pydataclass
class CustomNavbar(Navbar):
    pass

navbar = CustomNavbar("https://example.com",)
print(navbar)
```

This throws:

`RuntimeError: no validator found for <class '__main__.NavbarButton'>, see arbitrary_types_allowed in Config`

Is there any way to get Pydantic to play nice with these classes except by essentially copying code?

**Comment by samuelcolvin** [comment]
Yes, I think we haven't implemented validation on nested dataclasses. We should.

This has been bugging me for ages, and I can't understand why there isn't another issue about it. Maybe there is and I can't find it. Partially related to #744.

PR welcome to fix this.

**Comment by hawkaa** [comment]
I too would love to see this functionality! I have a third-party library and I want to extend the dataclasses from that library with pydantic validation.

**Comment by PrettyWood** [comment]
Hello @dylrich @hawkaa,

I just opened a [PR](https://github.com/samuelcolvin/pydantic/pull/1817) to add basic support on built-in `dataclass`.
Could you please tell me if this helps and, if yes, if it work as expected ?

Thanks

**Comment by hawkaa** [comment]
@PrettyWood it sure does! Amazing!

**Comment by dylrich** [comment]
@PrettyWood This does fix our problem! Thanks so much. Looking forward to it in stable!
