### ISSUE TITLE
Document GetterDict for ORM mode properly properly

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#1745]
As per #1726 and #1689 we need to document `GetterDict` and how to use it properly.

**Comment by kevlarr** [comment]
Docs also say GetterDict can be modified, but how is that the case? Any attempt just raises

**Comment by alexschoeberl** [comment]
@kevlarr the original orm object is stored in the getter dict under self._obj.
For a quick solution you can just modify this object directly.
For a cleaner solution you can create your own GetterDict subclass like it is described in the PR linked above.
