### ISSUE TITLE
Field title and description being overridden for Enums.

### ISSUE THREAD

**Issue by joshourisman** [samuelcolvin/pydantic#1748]
# Bug

When using the Field() function with an Enum, I can set an alias, but if I try to set a title or description they are ignored for default values of both (the name of the Enum subclass for the title, and 'An enumeration' for the description).

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /Users/joshourisman/.local/share/virtualenvs/forms-test-3oF3wXzB/lib/python3.8/site-packages/pydantic
               python version: 3.8.3 (default, Jun 30 2020, 11:16:06)  [Clang 11.0.0 (clang-1100.0.33.8)]
                     platform: macOS-10.15.5-x86_64-i386-64bit
     optional deps. installed: []

```

```py
>>> from enum import Enum                          
>>> from pydantic import BaseModel, Field          
>>> class TestEnum(str, Enum): 
...     foo = 'foo' 
...     bar = 'bar'                                
>>> class TestModel(BaseModel): 
...     test: TestEnum = Field(alias='functioning_alias', title='I Will Be Ignored')                      
>>> TestModel.schema()                             
{'title': 'TestModel', 'type': 'object', 'properties': {'functioning_alias': {'$ref': '#/definitions/TestEnum'}}, 'required': ['functioning_alias'], 'definitions': {'TestEnum': {'title': 'TestEnum', 'description': 'An enumeration.', 'enum': ['foo', 'bar'], 'type': 'string'}}}
```

**Comment by PrettyWood** [comment]
Hello @joshourisman,

I agree it should be possible. I opened a PR. Feel free to check it out and comment if you see anything unexpected.

**Comment by PrettyWood** [comment]
Hello @joshourisman,

You're totally right! I opened a PR #1749 to support this. Feel free to try it out and comment if you see anything unexpected.

**Comment by skewty** [comment]
I found this issue when I realized the default title generation does not seem to occur for enums.  By default titles are set to something like: `title_value = field_name.replace('_', ' ').title()`.  But I see that `title` field is missing from the generated JSON schema (the default title generation process isn't being done).  Please ensure this PR also does the default title generation if it doesn't already.
