### ISSUE TITLE
pydantic types subclassed from primitive types | input validation

### ISSUE THREAD

**Issue by adrpp** [samuelcolvin/pydantic#1751]
First of all, thanks for this great library :)

I'm trying add 'input' validation as I'm aware of https://pydantic-docs.helpmanual.io/usage/models/#data-conversion.
My thought is subclassed "BaseModel" from "pydantic.BaseModel", looks like this:

```python
class BaseModel(PydanticBaseModel):

    class Config:
        validate_assignment = True
        validate_all = True

    @validator('*', pre=True, always=True, each_item=True)
    def strict_type_validator(cls, *args, **kwargs):
        """
        Force type strictness for pydantic's (input) model.
        https://pydantic-docs.helpmanual.io/usage/models/#data-conversion
        """
        value = args[0]
        if value:
            if kwargs:
                expected_type = kwargs['field'].type_
                if expected_type is not Any:
                    if issubclass(expected_type, str):
                        expected_type = str
                        if not isinstance(value, expected_type):
                            raise TypeError(f'Value "{value}" is not an instance of expected ("{expected_type}") type')
        return value
```

I've played a bit with few types / models and it looked good so far unless I've got to `HttpUrl` | `AnyHttpUrl` | `AnyUrl` (originates in pydantic.networks).
That brought me to adding some extra checks:
`
if issubclass(expected_type, str):                        
    expected_type = str
`

Is there a way how to programmatically obtain such information ?
By such information I mean cases where specific pydantic types are subclasses of primitive types.
For example: HttpUrl -> AnyUrl -> str

Atrributes like `kwargs['field'].type_` or `outer_type_` results in type of `HttpUrl`, but such is "build" from str type.

Thanks,
Adrian

**Comment by PrettyWood** [comment]
Hi @adrpp,

Maybe you could use `__bases__` recursively as shown [here](https://stackoverflow.com/a/1401708) and remove `object` from parent types.
There is indeed no direct way implemented in *pydantic*.
I'm not sure how I can help more than that.

**Comment by adrpp** [comment]
@PrettyWood 
I'm on it and would like to share / discuss my approach soon, if you don't mind.
Could be interesting for those looking for 'input' validation (too). :)

**Comment by adrpp** [comment]
@PrettyWood 

Ended up with something like:

`
class BaseModel(PydanticBaseModel):

    class Config:
        validate_assignment = True
        validate_all = True

    @validator('*', pre=True, always=True, each_item=True)
    def strict_type_validator(cls, *args, **kwargs):
        """
        Force type strictness for pydantic's (input) model.
        https://pydantic-docs.helpmanual.io/usage/models/#data-conversion
        """
        value = args[0]
        if value:
            if kwargs:
                expected_type = kwargs['field'].type_
                if expected_type is not Any:
                    expected_types_by_mro = expected_type.__mro__[:-1]
                    expected_type_from_mro = None

                    if isinstance(value, expected_type):
                        print(f'value {value} is top-level-type {expected_type}')
                    else:
                        for parent_type in expected_types_by_mro:
                            if not isinstance(value, parent_type):
                                print(f'value {value} is NOT type of {expected_type}')
                                continue
                            else:
                                expected_type_from_mro = parent_type
                                print(f'FOUND expected type from mro {expected_type_from_mro}')
                                break
                        else:
                            raise TypeError(f'Value "{value}" is not an instance of expected ("{expected_type_from_mro or expected_type}") type')
        return value
`

Tested with few models, seems to work however there might be cases where it does not work properly.
This way it's possible to make 'input' type validation happen.

Rgds,
Adrian

**Comment by PrettyWood** [comment]
Hi @adrpp,

Thanks for the code. Could you share all the tests you used too ? (maybe just push a branch).

I'm a bit concerned about the `if value` for example, which means it won't test values like `0`. So if we set `a: float` and set `a = 1`, it will break and ask for `a = 1`. But it will work for `a = 0`. I think this is unexpected.

Does something like this (without `if value` and `if kwargs`) break in some cases?

```python
    @validator('*', pre=True, always=True, each_item=True)
    def strict_type_validator(cls, value, values, config, field):
        """
        Force type strictness for pydantic's (input) model.
        https://pydantic-docs.helpmanual.io/usage/models/#data-conversion
        """
        expected_type = field.type_
        if expected_type is not Any:
            breakpoint()
            expected_types_by_mro = expected_type.__mro__[:-1]
            expected_type_from_mro = None

            if isinstance(value, expected_type):
                print(f'value {value} is top-level-type {expected_type}')
            else:
                for parent_type in expected_types_by_mro:
                    if not isinstance(value, parent_type):
                        print(f'value {value} is NOT type of {expected_type}')
                        continue
                    else:
                        expected_type_from_mro = parent_type
                        print(f'FOUND expected type from mro {expected_type_from_mro}')
                        break
                else:
                    raise TypeError(f'Value "{value}" is not an instance of expected ("{expected_type_from_mro or expected_type}") type')
        return value
```

Cheers

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
