### ISSUE TITLE
Field ordering, dynamic default values with validators and inheritance

### ISSUE THREAD

**Issue by Weissger** [samuelcolvin/pydantic#1754]
# Field ordering, dynamic default values with validators and inheritance

I have a BaseModel defining a 'uri' field. This field should be provided when the model is instantiated. Another Model inheriting from my BaseModel defined fields, which could be used to construct the 'uri' field. As far as I understand for purposes like this validators can be used to construct dynamic default values as seen in the [documentation](https://pydantic-docs.helpmanual.io/usage/validators/). Nevertheless the field to be extended with a dynamic default value validator needs to be defined after the other fields used for the dynamic value creation or they won't be available in the value parameter. Due to the inheritance I unfortunately can't change the field definition order. Is there a way to access other attributes in the validator while preserving the inheritance structure? My code looks somewhat like following example:
```
import pydantic
from pydantic import BaseModel


class ModelA(BaseModel):
    uri: str = ...

class ModelB(ModelA):
    foo: str = ...
    bar: str = "a"
    uri: str = None

    @pydantic.validator('uri', pre=False, always=True)
    def default_uri(cls, v, *, values, **kwargs):
        return v or "{}#{}".format(values['foo'], values['bar'])

**Comment by PrettyWood** [comment]
Hi @Weissger 
You're right `uri` will always be validated before. So it's a good idea to overwrite the default value to `None` and then you can use [`root_validator`](https://pydantic-docs.helpmanual.io/usage/validators/#root-validators) to set the real default value.
I would do something like this

```python
from pydantic import BaseModel, root_validator


class ModelA(BaseModel):
    uri: str = ...

class ModelB(ModelA):
    uri: str = None
    foo: str = ...
    bar: str = "a"

    @root_validator
    def set_default_uri(cls, values):
        if values['uri'] is None:
            values['uri'] = f"{values['foo']}#{values['bar']}"
        return values


print(ModelB(foo='qwe').dict())
# {'uri': 'qwe#a', 'foo': 'qwe', 'bar': 'a'}
```

Hope it helps!

**Comment by Weissger** [comment]
Thanks this solved my issue!
