### ISSUE TITLE
Environment variable not overiding sent paramenter

### ISSUE THREAD

**Issue by freis** [samuelcolvin/pydantic#1760]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /home/vagrant/venv/api_fastapi/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Jul 16 2020, 14:00:26)  [GCC 9.3.0]
                     platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.29
     optional deps. installed: ['devtools']
```

Hello, I'm not sure if I'm doing something that is impossible or doing something wrong, but while trying to use pydantic for settings importing I've built the code in the snippet and I was expecting the following result:
```
DevConfig(ENV_STATE='dev', PgStore=PostgresConfig(POSTGRES_HOST='127.0.0.1'))
```
instead I've got:
```
DevConfig(ENV_STATE='dev', PgStore=PostgresConfig(POSTGRES_HOST='192.168.1.1'))
```
I was under the impression that I could do something like that, building the class with some default values and if the environment variable existed it would be picked up and changed to that value.

Can someone help me understand why and on how (if I can) achieve this?

```py
import os
from typing import Any, Optional, Dict, Tuple, Type, Union
from pydantic import BaseSettings, Field

os.environ["POSTGRES_HOST"] = '127.0.0.1'
os.environ["ENV_STATE"] = 'dev'

class PostgresConfig(BaseSettings):
    POSTGRES_HOST: str = Field(None, env="POSTGRES_HOST")

class GlobalConfig(BaseSettings):
    ENV_STATE: Optional[str] = Field(None, env="ENV_STATE")

class DevConfig(GlobalConfig):
    """Development configurations."""
    PgStore: PostgresConfig = PostgresConfig(
        POSTGRES_HOST="192.168.1.1"
    )

class ProdConfig(GlobalConfig):
    """Production configurations."""
    PgStore: PostgresConfig = PostgresConfig(
        POSTGRES_HOST="192.168.1.2"
    )

class FactoryConfig:
    """Returns a config instance dependending on the ENV_STATE variable."""

    def __init__(self, env_state: Optional[str]):
        self.env_state = env_state

    def __call__(self):
        if self.env_state == "dev":
            return DevConfig()

        elif self.env_state == "prod":
            return ProdConfig()

cnf = FactoryConfig(GlobalConfig().ENV_STATE)()
print(cnf.__repr__())
```

**Comment by PrettyWood** [comment]
Hello @freis 
This is the expected behaviour as explained in [the doc](https://pydantic-docs.helpmanual.io/usage/settings/#field-value-priority). You are setting the value of `POSTGRES_HOST` explicitly so it uses this value.
There is currently no easy way to change the default value on the fly so I would go with something like this to keep things simple

```python
class PostgresConfig(BaseSettings):
    DEFAULT_POSTGRES_HOST: str
    POSTGRES_HOST: str = Field(default=None, env="POSTGRES_HOST")

    @validator('POSTGRES_HOST')
    def handle_unset_postgres_host(cls, v, values):
        if v is None:
            v = values['DEFAULT_POSTGRES_HOST']
        return v


class DevConfig(BaseSettings):
    """Development configurations."""
    ENV_STATE: Optional[str] = Field(None, env="ENV_STATE")
    PgStore: PostgresConfig = PostgresConfig(DEFAULT_POSTGRES_HOST="192.168.1.2")
```

Hope it helps!

**Comment by freis** [comment]
@PrettyWood sadly I didn't want to go this way since its more than 1 parameter and I didn't want to create validators for each one of them. What I'm trying to achieve is something along the lines of having those values picked from a file and then use them as default and then whenever a env var exists use that env var, or by explicitly putting them on the code like that and if the env var exists change to that. So far I found no easy way to do this. Anyone has any good ideas?

**Comment by PrettyWood** [comment]
Hello @freis 
If you really want to prioritize values fron environ over init values, I create my own `BaseSettings` with the behaviour.
Something like this for example:

```python
from pydantic import BaseSettings as PydanticBaseSettings, Field
from pydantic.utils import deep_update

class BaseSettings(PydanticBaseSettings):
    """Custom `BaseSettings` that prioritizes env values over init values"""
    def _build_values(self, init_kwargs, _env_file = None, _env_file_encoding = None):
        env = self._build_environ(_env_file, _env_file_encoding)
        # we override init values with default values from environ
        kwargs = {**init_kwargs, **env}
        return deep_update(env, kwargs)
```

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
