### ISSUE TITLE
s/django/apps/config.py", line 133, in create     if not issubclass(cls, AppConfig): TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by OikoDavid** [samuelcolvin/pydantic#1762]
# Bug
****views***

if request.method == "POST":
    user_form = UserForm(request.POST)
    store_form = StoreForm(request.POST, request.FILES)

    if user_form.is_valid() and store_form.is_valid():
        new_user = User.objects.create_user(**user_form.cleaned_data)
        new_store = store_form.save(commit=False)
        new_store.user = new_user
        new_store.save()

        login(request, authenticate(
             username = user_form.cleaned_data['username'],
             password = user_form.cleaned_data['password']
        ))
        return redirect(store_home)

return render(request, 'store/sign_up.html', {
     "user_form": user_form,
     "store_form": store_form
})

if request.method == "POST":
    user_form = UserForm(request.POST)
    store_form = StoreForm(request.POST, request.FILES)

    if user_form.is_valid() and store_form.is_valid():
        new_user = User.objects.create_user(**user_form.cleaned_data)
        new_store = store_form.save(commit=False)
        new_store.user = new_user
        new_store.save()

        login(request, authenticate(
             username = user_form.cleaned_data['username'],
             password = user_form.cleaned_data['password']
        ))
        return redirect(store_home)

return render(request, 'store/sign_up.html', {
     "user_form": user_form,
     "store_form": store_form
})

****forms****

class Meta:
    model = User
    fields = ("username", "password", "first_name", "last_name", "email")

****models***

 def __str__(self):
    return self.name

**Comment by samuelcolvin** [comment]
Please describe and format your issue properly.
