### ISSUE TITLE
Use of Type[T] with class from imported module

### ISSUE THREAD

**Issue by arodmor** [samuelcolvin/pydantic#1763]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /home/arodmor/anaconda3/envs/jupyterlab/lib/python3.8/site-packages/pydantic
               python version: 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:43:00)  [GCC 7.5.0]
                     platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.10
     optional deps. installed: []
```

Hi, thanks for this great package. I'm using (now extensively) pydantic in the development of a custom graph analysis package, and I've encountered this issue: I'm defining a model ```MarketGraph``` by using Type[T] (as per the [documentation](https://pydantic-docs.helpmanual.io/usage/types/#type)), in particular to specify the class ```Graph``` from ```networkx``` package.  
```py
from typing import Type
from pydantic import BaseModel, ValidationError
from networkx import Graph

class MarketGraph (BaseModel):
    name: str = None
    graph: Type[Graph] = None

G = networkx.Graph()
M = MarketGraph(name="M", graph=G)
```
Throws the following error:
```
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
In  [82]:
Line 1:     M = MarketGraph(name="M", graph=G)

File pydantic/main.py, in pydantic.main.BaseModel.__init__:
Line 346:   

ValidationError: 1 validation error for MarketGraph
graph
  subclass of Graph expected (type=type_error.subclass; expected_class=Graph)
---------------------------------------------------------------------------
```

Checking G's class and classname gives:
```
>>> type(G)
>>> <class 'networkx.classes.graph.Graph'>
>>> type(G).__name__
>>> 'Graph'
```
Changing:
```py
graph: Type[Graph] = None
```
to
```py
graph: Type[networkx.classes.graph.Graph] = None
```
in the definition of the ```MarketGraph``` model throws the same error.

My question is: am I using this feature correctly? How do I use ```Type[T]``` when T is a class that is imported from an external module/package?

Thanks!

**Comment by PrettyWood** [comment]
Hi @arodmor 
Writing `graph: Type[Graph]` means you expect a class not an instance.
You can just write `graph: Graph`

**Comment by arodmor** [comment]
Hi @PrettyWood 
Thanks for the prompt response.

I understand that I can always specify ```graph:Graph```, when I want an instance of MarketGraph to be **exactly** of type Graph (is this correct?), but along my code I use a hierarchy of graph classes, and some of the algorithms I'm developing should also work with subclasses along this hierarchy. 

So, for example, let's say that later on I define BipartiteGraph as a subclass of Graph, but I still want to use the ```MarketGraph``` model previously defined.  If so, I would then expect to do:

```py
class BipartiteGraph(Graph):
 ...

G2 = BipartiteGraph()
M2 = MarketGraph(name="M2", graph=G2)
```
Is this correct?

At the same time, some algorithms could be subclass-specific, and for those I guess I'll have to define a different model, maybe like:

```py
class HavelHakimiBiGraph(BipartiteGraph):
...

class MarketHavelHakimiBiGraph (BaseModel):
    name: str = None
    graph: Type[HavelHakimiBiGraph] = None
```
if I want to use this model in an algorithm that works with instances of ```HavelHakimiBiGraph``` but not with instances upstream the class hierarchy (for example, not with instances of ```BipartiteGraph```)

Is this possible? Or, if I'm not understanding it right, how should I code it?

**Comment by PrettyWood** [comment]
Hello @arodmor 
So if you use classes which inherit from `BaseModel`, `graph: Graph` will work with `Graph` instances or subclasses instances.
In your case you want to use your own class so I would create a decorator to [validate it](https://pydantic-docs.helpmanual.io/usage/types/#classes-with-__get_validators__) like this:

```python
def enforce_subclass(kls):
    """
    decorator that adds validation on a given class and enforces
    that only instances of this class or subclasses are valid
    """
    def __get_validators__(cls):
        yield cls.validate

    def validate(cls, v):
        if not isinstance(v, cls):
            raise TypeError(f'Instance of {cls.__name__!r} required')
        return v

    kls.__get_validators__ = classmethod(__get_validators__)
    kls.validate = classmethod(validate)

    return kls
```

and then apply it on your `Graph` class.

```python
Graph = enforce_subclass(Graph)
```

Now it should accept only `Graph` or subclasses of `Graph`
So with

```python
class OtherGraph: ...

class SubGraph(Graph): ...

class SubSubGraph(SubGraph): ...

class MarketGraph (BaseModel):
    name: str
    graph: Graph
```

it raises an error with

```python
M = MarketGraph(name="M", graph=OtherGraph())
```

```
pydantic.error_wrappers.ValidationError: 1 validation error for MarketGraph
graph
  Instance of 'Graph' required (type=type_error)
```

but works with

```python
M = MarketGraph(name="M", graph=SubSubGraph())
```

Note that you can now enforce only `SubGraph` instances as the `validator` is inherited.
So if you change your model like this

```python
class MarketGraph (BaseModel):
    name: str
    graph: SubGraph
```

it will fail for `graph=Graph()` but will be valid for `graph=SubGraph()` or `graph=SubSubGraph()`

Hope it helps !

**Comment by arodmor** [comment]
@PrettyWood , thanks again! 

I've tried it with a simple case and it works well. I'll give it a try in more complex cases along the package, and let you know how it went.

I think I understand now better the rationale for ```Type[T]``` in ```pydantic```, and I'll likely use it for some factory-related pattern with data parsing & validation. That, together with the validator you propose should provide me with all I need.

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
