### ISSUE TITLE
Validation messages should be customizable

### ISSUE THREAD

**Issue by nandoflorestan** [samuelcolvin/pydantic#177]
This is a feature request for a future version -- not urgent.

There should be some mechanism to easily change the validation strings since these will appear in multiple systems with multiple personalities and multiple target audiences who might need less or more detail in the messages.

In my library *pluserable*, this is achieved simply by accumulating the strings in a base class which can then be subclassed by the user and dependency-injected:

https://github.com/nandoflorestan/pluserable/blob/master/pluserable/strings.py

**Comment by samuelcolvin** [comment]
I'm not sure what you mean, could you give a fuller example.

Really I think this should use `gettext` translations.

**Comment by Gr1N** [comment]
I think @nandoflorestan means something like this https://github.com/django/django/blob/master/django/forms/fields.py#L45. As you can see each field have a `default_error_messages`, but it's possible to redefine them passing `error_messages` into constructor.

**Comment by nandoflorestan** [comment]
Yes, this is about changing the text of the default error messages. I am not talking about i18n.

If I understand the django code correctly... I don't like it. It feels like too much work to need to pass in a dictionary of default error messages for every form (or every field!) that an application creates. I would prefer a simpler, global mechanism first. I would just configure pydantic at application startup and then forget about it.

**Comment by samuelcolvin** [comment]
Maybe this can be done as part of #162, or maybe once #162 is implemented it would be possible to process the error dictionary and substitute your custom messages into each error based on the code.

**Comment by nandoflorestan** [comment]
The second idea does not sound very good to me because validation messages might contain variables in them, making it hard to substitute these.

Anyway, we shouldn't worry much about this right now. There are more important things to do.

By the way, thank you for creating this awesome library!

**Comment by samuelcolvin** [comment]
closing this, let's discuss on #162.
