### ISSUE TITLE
Inherited `__field_defaults__` persists even when subclass makes the field required

### ISSUE THREAD

**Issue by leilanilumen** [samuelcolvin/pydantic#1772]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: False
                 install path: /Users/leilanil/Library/Caches/pypoetry/virtualenvs/tesseract-vBkELJq4-py3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Mar 26 2020, 18:03:31)  [Clang 11.0.0 (clang-1100.0.33.17)]
                     platform: macOS-10.15.5-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

We have a use case where we're defining a pydantic model (`Foo` in the example below) with an optional integer field. A subclass of this model (`Bar` in the example below) overrides the type annotation of the field so that it's required instead.

`Bar` behaves as expected in that it prevents instantiation of the class if a value isn't provided for the required field. 

However, a successfully instantiated object still has the value of `__field_defaults__` that come from its parent `Foo`.

This creates a problem for us because downstream in our application, we are using `__field_defaults__` for Avro schema generation. From the valid class definitions below, the resulting Avro schema will be invalid because `int` type cannot have a default value of `None` - the default must be a valid integer. (Reference: https://avro.apache.org/docs/current/spec.html#schema_primitive)

```py
from typing import Optional

from pydantic import BaseModel

class Foo(BaseModel):
    lorem: Optional[int]

class Bar(Foo):
    lorem: int

bar = Bar()
# ValidationError: 1 validation error for Bar
# lorem
#  field required (type=value_error.missing)

bar = Bar(5)
bar.__field_defaults__
# {'lorem': None}
```

I've looked through the pydantic source code and identified how this is happening. Note we are using version 1.5.1 but I checked the latest source code and the things I'm pointing out below are still the same.

When a subclass like `Bar` in the example above gets instantiated:

- First, fields from the parent class (apart from `BaseModel`) are inherited and assigned to the `fields` dictionary: https://github.com/samuelcolvin/pydantic/blob/v1.5.1/pydantic/main.py#L206
- Then, another dictionary called `fields_defaults` is assigned values per the inherited fields: https://github.com/samuelcolvin/pydantic/blob/v1.5.1/pydantic/main.py#L218

NOTE: if I were instantiating a class that did NOT have a parent class (apart from `BaseModel` itself) then `fields` and `fields_defaults` at this point are still empty dictionaries.

- Later in the code, the definition of `fields` gets populated using the definition of the class itself: https://github.com/samuelcolvin/pydantic/blob/v1.5.1/pydantic/main.py#L246. This line executes whether or not the class has a parent. In this way, `fields` gets updated to reflect the class, rather than its parent.
- However, `fields_defaults` does NOT get similarly updated--or rather it gets updated but not in a way that removes pre-existing entries in that dictionary: https://github.com/samuelcolvin/pydantic/blob/v1.5.1/pydantic/main.py#L253

**Comment by PrettyWood** [comment]
Hello @leilanilumen 
FYI https://github.com/samuelcolvin/pydantic/pull/1755 may remove completely `__field_defaults__`

**Comment by PrettyWood** [comment]
`__field_defaults__` has been removed in v1.7
