### ISSUE TITLE
Nested model with Dict __root__ init behaviour

### ISSUE THREAD

**Issue by Okonos** [samuelcolvin/pydantic#1773]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /home/pawecich/.virtualenvs/foundation/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Jul 16 2020, 14:00:26)  [GCC 9.3.0]
                     platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
```

Hello,

I'm trying to nest a model with custom `Union[str, Dict]` root type in another model and seem to be getting some inconsistent behavior during model init. Consider following code snippet:

```py
from typing import Dict, Union

from pydantic import BaseModel, ValidationError


class StrDict(BaseModel):
    __root__: Union[str, Dict[str, str]]

    def __init__(self, *args, **kwargs):
        print(f"{kwargs=}")
        super().__init__(*args, **kwargs)


class StrDictModel(BaseModel):
    d: StrDict


print(StrDictModel(d='asdf').dict())
print()
try:
    print(StrDictModel(d={'k': 'v'}).dict())
except ValidationError as e:
    print(e)
print()
print(StrDictModel(d={'__root__': {'k': 'v'}}).dict())
```

This outputs:
```
kwargs={'__root__': 'asdf'}
{'d': 'asdf'}

kwargs={'k': 'v'}
1 validation error for Model
d -> __root__
  field required (type=value_error.missing)

kwargs={'__root__': {'k': 'v'}}
{'d': {'k': 'v'}}
```

In case of passing a string, it gets nested under the `__root__` key automatically, which is not the case with the dict, which seems to require explicit nesting.
Is this expected?

**Comment by PrettyWood** [comment]
Hi @Okonos 
It is intended yes as described in https://github.com/samuelcolvin/pydantic/pull/1607:
> This does not make that change at the outermost level, so .dict() still always returns a dict (as discussed in #1193).

**Comment by Okonos** [comment]
Thanks, @PrettyWood 
I admit I find it somewhat confusing. From the discussions linked I gather that this custom root functionality is to be changed in the next major version. Do you happen to know what the scope of the changes is going to be and if this particular behavior is to be addressed somehow?

**Comment by PrettyWood** [comment]
I'm afraid it won't be available anytime soon (see https://github.com/samuelcolvin/pydantic/milestone/2)
@samuelcolvin is quite busy at the moment and the whole covid situation didn't help. Yet I agree we may need to put more effort on v2 (or at least give more visibility)

**Comment by Okonos** [comment]
No problem, I believe it should be rather simple to work around.
Thanks again.
