### ISSUE TITLE
Python 3.7 dataclasses

### ISSUE THREAD

**Issue by Gaunt** [samuelcolvin/pydantic#178]
I don't know if this is supposed to work. Would be nice. I can try to fix it if you propose the way.

```
@dataclasses.dataclass
class C(pydantic.BaseModel):
     i:int
c = C(1)
....
RecursionError: maximum recursion depth exceeded
```

**Comment by samuelcolvin** [comment]
It's not, I haven't really looked into `dataclass` yet.

I'm not exactly clear on what they do or why they'd be useful with pydantic. Could you explain?

**Comment by Gaunt** [comment]
It seems that pydantic offers similar functionality, but dataclass is going to be a standard way how to write value classes in the future. It would be nice, if we can use pydantic for runtime validation dataclasses.

**Comment by Gaunt** [comment]
simple solution is to don't use dataclass __init__ method
```
@dataclasses.dataclass(init=False)  
class C(pydantic.BaseModel):
    i:int 
```
but the pydantic's __init__ method does not accept positional arguments, so the code using dataclasses can't start using pydantic easily.

**Comment by pawelswiecki** [comment]
It would be freaking awesome we could use pydantic's validation in Python's dataclasses.

**Comment by samuelcolvin** [comment]
@pawelswiecki sounds good to me, PR welcome.

**Comment by pawelswiecki** [comment]
Using `init=False` (`@dataclasses.dataclass(init=False)`) indeed fix maximum recursion issue.

Quick poking around with class defined this way (that is with both `@dataclass` decorator and inheriting from `pydantic.BaseModel`) results in an optimistic conclusion: it does work and the object behaves as both dataclass and pydantic's validator. I will possibly try to use this combination in some simple cases. Will report here if there's anything to report.

**Comment by pauleveritt** [comment]
As a small FYI, there's a backport of dataclasses to Python 3.6: https://github.com/ericvsmith/dataclasses

**Comment by Gaunt** [comment]
why is a significant rewrite needed? Seems to me that the functions for validation are there already.

**Comment by samuelcolvin** [comment]
Yes that's a way to do it. It would require support for positional arguments with don't currently work.

**Comment by pauleveritt** [comment]
I disagree on the point about data classes: I don’t think it will get rich serialization and validation in the core. The standard library is very conservative.

—Paul

**Comment by Gaunt** [comment]
hi, I have returned from my vacation yesterday. Sorry for the delay. I wanted to understand the code better. I will finish it tomorrow.

**Comment by samuelcolvin** [comment]
Dataclasses now merged, I'll release a new version of pydantic in a couple of days.

**Comment by amogorkon** [comment]
I haven't looked at the code of pydantic, but I guess you don't inherit from dataclasses.dataclass since I'm missing useful features I had expected when I checked https://docs.python.org/3/library/dataclasses.html - fields and asdict. Do you need a hand with that?

**Comment by samuelcolvin** [comment]
we do user standard dataclasses (let's not user `inherit` here, since we're not talking about class inheritance).

The reason you're not seeing `asdict` is because the 3.6 [backport of dataclasses](https://github.com/ericvsmith/dataclasses) doesn't implement it.

```py
# python 3.6
from dataclasses import dataclass

@dataclass
class InventoryItem:
    name: str
    unit_price: float
    quantity_on_hand: int = 0

    def total_cost(self) -> float:
        return self.unit_price * self.quantity_on_hand

item = InventoryItem('hammers', 10.49, 12)
item.asdict()
#> AttributeError: 'InventoryItem' object has no attribute 'asdict'
```

**Comment by amogorkon** [comment]
I see. Confusing :p
Keep up the good work! Finally a good use for the typing module ;-) 
Constantly coming up with new ways to use pydantic in my projects, it's really fun!

**Comment by samuelcolvin** [comment]
> Finally a good use for the typing module

:+1:
