### ISSUE TITLE
Can we get hyped about 3.9 Annotations?

### ISSUE THREAD

**Issue by wozniakty** [samuelcolvin/pydantic#1781]
# Question

https://docs.python.org/3.9/library/typing.html#typing.Annotated adds ways to specify things that look a _whole lot_ like validators.  Any long-term roadmap plan to eventually use these?  This is a super low-pri issue, I just like pydantic a lot and saw this incoming feature and wanted to hype over it.  Keep up the good work, folks <3

**Comment by mcgfeller** [comment]
I think this is related to #837. It would make Pydantic more pythonic, I think (and more pythonic than dataclasses). It could rationalize the `Field ` function.  Best regards, Martin
