### ISSUE TITLE
Mention pydantic IDE plugins to support the claim: "pydantic plays nicely with your linter/IDE/brain"

### ISSUE THREAD

**Issue by Luttik** [samuelcolvin/pydantic#1784]
# Documentation Request

The second line of the readme says "pydantic plays nicely with your linter/IDE/brain". Id argue that, out of the box, it doesn't play nicely with at least PyCharm since the shown constructor definition is just `def __init__(__pydantic_self__, **data: Any) -> None:`. 

However, this is easily solved with the Pydantic pycharm plugin (if you know that it exists). Therefore I'd argue that you should give it a prominent role in the readme if possible with similar solutions for other prominent IDE's (most notably vscode).

**Comment by samuelcolvin** [comment]
I think that the pycharm plugin is already prominent in the documentation, if you want to add a note about it in the readme, feel free to submit a PR.

Regarding the "pydantic plays nicely with your linter/IDE/brain" claim, it was originally a reference to using type hints to set the type of fields - in DRF for example the "type" of field attributes on a model class is always `Field`. I think that claim is still fair even without the pycharm plugin, though of course it could always be better.
