### ISSUE TITLE
Please add parse_raw_as

### ISSUE THREAD

**Issue by jet10000** [samuelcolvin/pydantic#1789]
I want to parse json string to List[User]

like `parse_obj_as(List[User], objs)`

thanks

**Comment by PrettyWood** [comment]
Hello @jet10000 
Following the [doc example](https://pydantic-docs.helpmanual.io/usage/models/#parsing-data-into-a-specified-type)

```python
import json

item_data_json = '[{"id": 1, "name": "My Item"}]'
items = parse_obj_as(List[Item], json.loads(item_data_json))
```

works as expected. If it doesn't solve your problem please provide a full example of expected behaviour or add your feedback in #481
