### ISSUE TITLE
Detecting extra keys being provided to BaseModel

### ISSUE THREAD

**Issue by captainvera** [samuelcolvin/pydantic#1791]
# Question

Hey, 

First of all, thanks for the awesome work you've done with Pydantic. We have been slowly adopting Pydantic on all our projects across my team and loving it so far.

Our biggest issue so far is that we couldn't find a simple way to throw an error when erroneous keywords are passed into the BaseModel `__init__` . When working with project with very large and nested configurations it is extremely easy to make a typo when creating this configuration and this error gets silently ignored. 

Is there any simple way of doing this that I am unaware of? 

```
 pydantic version: 1.4
            pydantic compiled: False
                 install path: /Users/miguelvera/env/miniconda2/envs/mirta/lib/python3.7/site-packages/pydantic
               python version: 3.7.8 | packaged by conda-forge | (default, Jul 23 2020, 03:39:37)  [Clang 10.0.0 ]
                     platform: Darwin-19.4.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Small example:

```py
import pydantic

class Configuration(BaseModel):
    input: FilePath = 'input'
    output: FilePath = 'output'


if __name__ == '__main__':
   args_dict = { 
                        "input"  :  '/mnt/mypath/inputs',
                        "outptu" :  '/myotherpath/output',
   } 
   # How can I make this throw an error for receiving a keyword that does not exist? (outptu)
   Configuration(**args_dict)

```

Thanks in advance!

**Comment by philipp-sontag-by** [comment]
There is a model config Option called [extra](https://pydantic-docs.helpmanual.io/usage/model_config/). By default is is set to 'ignore', but you can set it to 'forbid' to throw a validation error when an unknown attribute is included.

Would this suffice for your use case?

**Comment by PrettyWood** [comment]
@philipp-sontag-by is right.

```python
from pydantic import BaseModel, Extra, FilePath

class Configuration(BaseModel):
    input: FilePath = 'input'
    output: FilePath = 'output'

    class Config:
        extra = Extra.forbid  # or just 'forbid'
```

and you will have a validation error

```bash
pydantic.error_wrappers.ValidationError: 1 validation error for Configuration
outptu
  extra fields not permitted (type=value_error.extra)
```

**Comment by captainvera** [comment]
Sorry for the late response. 
This is exactly what I was looking for, thanks!

**Comment by ramushetty** [comment]
Hi, how to handle the duplicate keys in the request payload, I trying to raise the error if there are multiple keys with the same name 

{"input" : "input", "input":"input","output":"output"}
class Configuration(BaseModel):
    input: FilePath = 'input'
    output: FilePath = 'output'

**Comment by samuelcolvin** [comment]
Please format your example code, see my answer on #4995.
