### ISSUE TITLE
How to change the field type dynamically 

### ISSUE THREAD

**Issue by jamb0ss** [samuelcolvin/pydantic#1799]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /usr/local/lib/python3.8/site-packages/pydantic
               python version: 3.8.4 (default, Jul 19 2020, 13:42:30)  [GCC 5.4.0 20160609]
                     platform: Linux-4.4.0-185-generic-x86_64-with-glibc2.17
     optional deps. installed: ['typing-extensions', 'email-validator']

```

```py
import pydantic
import typing

class User(pydantic.BaseModel):
    name: str = pydantic.Field(...)

```
I have a `User` class with the required field name, what is the right way to create a new class from it, that will have this field (actually all fields) optional. Class can contain many fields, there are dozens of classes, so I'm trying to automate this process and make them dynamically. e.g. I need this class to be created at runtime (using `create_model` or whatever)

```
class CustomUser(pydantic.BaseModel):
    name: typing.Optional[str] = pydantic.Field(None)
```

**Comment by PrettyWood** [comment]
Hello @jamb0ss 

You just need to add `None` as default value for all the fields of the base model when you create your model.
Something like this

```python
from typing import Any, Dict, Tuple, Type

from pydantic import BaseModel, create_model


class User(BaseModel):
    name: str


def to_optional_fields(model: Type[BaseModel]) -> Dict[str, Tuple[Any, None]]:
    """
    Generate `field_definitions` for `create_model` by taking fields from
    `model` and making them all optional (setting `None` as default value)
    """
    return {f.name: (f.type_, None) for f in model.__fields__.values()}


CustomUser = create_model('CustomUser', **to_optional_fields(User))
print(repr(CustomUser(name='qwe')))
print(repr(CustomUser()))
```
```bash
CustomUser(name='qwe')
CustomUser(name=None)
```

**Comment by jamb0ss** [comment]
Thanks. Is it possible to keep all meta info? like `title` and `description` etc. Just an exact copy of the origin field but optional.

**Comment by PrettyWood** [comment]
I would go with something like this then

```python
def model_with_optional_fields(model: Type[BaseModel]) -> Type[BaseModel]:
    """Generate a `BaseModel` class with all the same fields as `model` but as optional"""
    class OptionalModel(model): ...

    for field in OptionalModel.__fields__.values():
        field.required = False
    
    # for generated schema for example (can be removed)
    OptionalModel.__name__ = f'Optional{model.__name__}'

    return OptionalModel
```

and then use it directly `OptionalUser = model_with_optional_fields(User)`

**Comment by jamb0ss** [comment]
looks good, thanks

**Comment by shurshilov** [comment]
IN v2 i use
class Partial(BaseModel):
    @classmethod
    def __pydantic_init_subclass__(cls, **kwargs: Any) -> None:
        super().__pydantic_init_subclass__(**kwargs)

        for name, field in list(cls.model_fields.items()):
            if field.is_required():
                field.default = None
                field.annotation = Union[field.annotation, type(None)]

        cls.model_rebuild(force=True)
