### ISSUE TITLE
Union type during field initialization has some kind of priority

### ISSUE THREAD

**Issue by i4never** [samuelcolvin/pydantic#1805]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
1.5.1
```

```py
from pydantic import BaseModel

class A(BaseModel):
    a: Union[str, int]

a = A(a=1)
print(a)
# Out: a='1'

a = A(a='1')
print(a)
# Out: a='1'

```

```py
from pydantic import BaseModel

class A(BaseModel):
    a: Union[int, str]

a = A(a=1)
print(a)
# Out: a=1

a = A(a='1')
print(a)
# Out: a=1
```

I believe `Union[str, int]` and `Union[int, str]` should be equivalent but it seems different order will lead to different result. Value of union field will be transformed to first type in Union if possible (Try `Union[float, str]` and initialize with `A(a='a')`)

**Comment by PrettyWood** [comment]
Hello @i4never 
This is a known issue. See #619 and #1423 for more information.
