### ISSUE TITLE
AnyHttpUrl raises an error if a URL ends with “#”

### ISSUE THREAD

**Issue by ninoseki** [samuelcolvin/pydantic#1807]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
            pydantic version: 1.6.1
            pydantic compiled: False
                 install path: /foo/bar/pydantic
               python version: 3.8.2 (default, Apr  8 2020, 09:35:26)  [Clang 11.0.3 (clang-1103.0.32.29)]
                     platform: macOS-10.15.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions', 'email-validator', 'devtools']
```

```py
from pydantic import BaseModel, AnyHttpUrl


class Test(BaseModel):
    url: AnyHttpUrl


test = Test(url="https://example.org#")
```

It raises the following error.

```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    test = Test(url="https://example.org#")
  File "/foo/bar/pydantic/main.py", line 356, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Test
url
  URL invalid, extra characters found after valid URL: '#' (type=value_error.url.extra; extra=#)
```

I know this is a very rare case but I found such a URL in the real world.

**Comment by StephenBrown2** [comment]
This is true, it is invalid, as there is no anchor specifier after the hash. I've also run into this and worked around it by simply adding a validator that stripped the `#` from the end of url values with `.rstrip("#")`.

**Comment by ninoseki** [comment]
Thanks for the tip. 🙏 

But I think the URL, `https://example.org#`, is not invalid because [RFC3986](https://tools.ietf.org/html/rfc3986#page-24) does not prohibit  an empty fragment.

For example, [rfc3986](https://github.com/python-hyper/rfc3986) library says it is valid.

```python
from rfc3986 import uri_reference

example = uri_reference('http://example.com')
example.is_valid()
# => True
```
