### ISSUE TITLE
R.e Comparing variables in validators

### ISSUE THREAD

**Issue by abercon** [samuelcolvin/pydantic#1808]
Hello. Apologies if this has already been asked somewhere.

I have a use case where I would like to validate that the lengths of two list-like arguments are equal and I haven't been able to do this within a pydantic model. Is this possible, or do I need to move this validation outside of pydantic? If it's possible in pydantic, what is the best approach? A simplified version of the model I currently have is as follows:

```
import numpy as np
from pydantic import BaseModel, validator, PositiveInt

class InputModel(BaseModel):
        sample_1: np.ndarray
        sample_2: np.ndarray

        @validator("sample1", "sample2")
        def parse_samples(cls, v):
            # Parses samples to an ndarray
            return np.ndarray(v, dtype=np.float64)

# I then want to validate the following expression:
# len(sample_1) == len(sample_2)

        class config:
            arbritrary_types_allowed = True
```

Thanks in advance.

pydantic version: 1.6.1
pydantic compiled: True
install path: C:\Users\joshw\.conda\envs\htk3.6.8\Lib\site-packages\pydantic
python version: 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
platform: Windows-10-10.0.18362-SP0
optional deps. installed: []

**Comment by PrettyWood** [comment]
Hello @abercon,
You basically just need to validate the second field and compare it to the first one.
Checking the second one is important as validation is done in the order fields are defined so `sample_2` will have access to `sample_1`.
I used list of ints in my example but it's the same.

```python
from typing import List

from pydantic import BaseModel, validator


class InputModel(BaseModel):
        sample_1: List[int]
        sample_2: List[int]

        @validator('sample_2')
        def same_size_as_sample_1(cls, sample_2, values):
            if len(sample_2) != len(values['sample_1']):
                raise ValueError('sample_1 and sample_2 should have the same length')
            return sample_2

print(repr(InputModel(sample_1=[1, 2], sample_2=[3, 4])))
# InputModel(sample_1=[1, 2], sample_2=[3, 4])
print(repr(InputModel(sample_1=[1, 2], sample_2=[3, 4, 5])))
# pydantic.error_wrappers.ValidationError: 1 validation error for InputModel
# sample_2
#   sample_1 and sample_2 should have the same length (type=value_error)
```

**Comment by abercon** [comment]
Ah, great, that's much simpler than I thought. I hadn't realised that values behaved as a dictionary of args, a bit of an oversight on my part!

Thanks a lot for your help! :)
