### ISSUE TITLE
JSON Schema patternProperties with Pydantic

### ISSUE THREAD

**Issue by pkucmus** [samuelcolvin/pydantic#1809]
# Can one declare patternProperties like on JSON Schema in Pydantic to use it for validation of extra fields?  

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: False
                 install path: /home/pkucmus/.cache/pypoetry/virtualenvs/oas-to-pydantic-215_x-7b-py3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.3 (default, Jul  4 2020, 13:00:05)  [GCC 9.3.0]
                     platform: Linux-5.4.0-7634-generic-x86_64-with-glibc2.29
     optional deps. installed: []
```

I would like to make a Python Pydantic based OAS3 schema validator, so write the schema "in" Pydantic to later validate API specs with Pydantic. 

I have no idea how to represent `patternProperties` that are allowed by JSONSchema (Draft04 up): https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.json#L93-L95

With `schema_extra` I won't get the fields that are allowed by `patternProperties` represented by the model.

So I'm looking for something like:

```python
class Info(BaseModel):
    title: str
    description: Optional[str]
    termsOfService: Optional[str] = Field(format='uri-reference')
    version: str

InfoPatternProperties = constr(regex=r'^x-$')
InfoPatternPropertiesDict = Dict[InfoPatternProperties, str]

class OpenAPI3(BaseModel):
    openapi: Pattern = Field(..., pattern=r"^3\\.0\\.\\d(-.+)?$")
    info: Union[Info, InfoPatternPropertiesDict]
```

to later be able to do this:

```python

>>> oas = OpenAPI3.parse_obj({"openapi": 3.0.0, "info": {"title": "Test", "version": "1", "x-test": true}})
>>> oas.info.x_test
True
```

Is this making sense? Or am I confused? Please aid me with my experiment :)

**Comment by PrettyWood** [comment]
Hi @pkucmus 
You're right there is currently no easy way to do this directly. But it should be possible.
You can't really do a union of models but you can allow extra fields and then check them!

```python
class Info(BaseModel):
    title: str
    description: Optional[str]
    termsOfService: Optional[str] = Field(format='uri-reference')
    version: str

    class Config:
        extra = 'allow'

    @root_validator
    def check_extra_fields(cls, values):
        """Make sure extra fields are only valid fields matching regex"""
        pattern_regex = r'^x-'

        for k, v in list(values.items()):
            if k in cls.__fields__:
                continue

            assert re.match(pattern_regex, k)
            values[re.sub(pattern_regex, 'x_', k)] = values.pop(k)

        return values


class OpenAPI3(BaseModel):
    openapi: Pattern = Field(..., pattern=r"^3\\.0\\.\\d(-.+)?$")
    info: Info
```

Basically I just allow extra fields for the model, but check them all via the `root_validator`. And then I just rename the field as you wanted. Does that help you ?

**Comment by pkucmus** [comment]
Thank you kindly, I will check later today.

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
