### ISSUE TITLE
allow arbitary types

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#182]
Remove the exception `pydantic.exceptions.ConfigError: no validator found for <class 'Foobar'>` and just require that any value provided is an instance of `Foobar`.

**Comment by oldPadavan** [comment]
I'm not sure whether I understand the issue correctly. Does it cover the following case which raises exception mentioned by You?

```
from datetime import datetime
from typing import List
from pydantic import BaseModel

class MyClass:
    pass

class User(BaseModel):
    id: int
    name = 'John Doe'
    signup_ts: datetime = None
    friends: List[int] = []
    my: MyClass

external_data = {'id': '123', 'signup_ts': '2017-06-01 12:22', 'friends': [1, '2', b'3'], 'my': MyClass()}
user = User(**external_data)
```

**Comment by samuelcolvin** [comment]
Exactly the user case. 

I guess we need a config variable to enable/disable this.

**Comment by Gr1N** [comment]
implemented in #209

**Comment by mr-bjerre** [comment]
Is this supposed to be fixed? I still get an error

**Comment by samuelcolvin** [comment]
Yes.

Are you using `arbitrary_types_allowed = True`?

**Comment by mr-bjerre** [comment]
Aha no. Where to set that? As an attribute to the class?

**Comment by samuelcolvin** [comment]
please read the documentation.

**Comment by mr-bjerre** [comment]
Do you mind pointing to where in the documentation? I didn’t find this thread by not looking. I was actively looking for it in the docs

**Comment by dmontagu** [comment]
A ctrl+f for `arbitrary_types_allowed` on the [pydantic docs](https://pydantic-docs.helpmanual.io/) should get you to the right place.

Here's an demonstration that I believe should work (not tested):
```python
from pydantic import BaseModel

class MyClass: 
    pass

class Model(BaseModel):
    v: MyClass

    class Config:
        arbitrary_types_allowed = True
```

**Comment by cknoll** [comment]
I was affected by this error and this thread (and especially the example by @dmontagu ) helped me solving it. 

However:
> @mr-bjerre A ctrl+f for arbitrary_types_allowed on the pydantic docs should get you to the right place.

Either I am surprisingly blind on this or something has changed: If I open the linked page in the docs <https://pydantic-docs.helpmanual.io/> I cannot find anything for `arbitrary_types_allowed` or meaningful substrings. I also have not found a global search function. The only way I could find this in the docs was to manually open subpages which sound somehow relevant and using ctrl-f there. Result: <https://pydantic-docs.helpmanual.io/usage/dataclasses/#use-custom-types>.

Is there a better strategy to find the relevant section in the docs?

**Comment by mr-bjerre** [comment]
Its in the model congig section. 

https://pydantic-docs.helpmanual.io/usage/model_config/

**Comment by teplinsky-maxim** [comment]
I had the same problem, but then I found out that I forgot to inherit from `BaseModel`

```
# WRONG
class AuthorType:
    name: str
    username: str


# OK
class AuthorType(BaseModel):
    name: str
    username: str

```

**Comment by stl-gilesbartonowen** [comment]
I had the same issue but it turned out I was using `=` rather than `:`
`# WRONG
class AuthorType(BaseModel):
    name = str
    username = str


# OK
class AuthorType(BaseModel):
    name: str
    username: str
`
