### ISSUE TITLE
Validation of nested models based on global entry

### ISSUE THREAD

**Issue by aknaut** [samuelcolvin/pydantic#1823]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.6.1
pydantic compiled: False
python version: 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
platform: Windows-10-10.0.19041-SP0
optional deps. installed: ['typing-extensions']
```
I would like to validate a nested model entry based on values that are defined in the global model class. For example the length of lists should be checked based on the entry `max_length` in the global class. I am aware that a root validator may help in a simple case when I know in which places the entries are that should be checked. However, in my case the entries that should be checked can appear in different parts of my nested model. Is there any possibility on how to do this?

Here is a simple example of what I would like to do:
```py
from typing import List
from pydantic import BaseModel, validator

class Nested(BaseModel):

    array: List[int]
    
    @validator("array")
    def check_array(cls, value, values, config):
        return value
    

class Global(BaseModel):
    max_length: int
    nested: Nested
```

The creation of `Global(max_length=2, nested={"array": [1, 2]})` should work fine and `Global(max_length=1, nested={"array": [1, 2]})` should throw a ValidationError. In addition I would like the validation part to be located within the `Nested` class and not in the `Global` part.
Is there any way on how to get the `max_length` value into the nested validator?

**Comment by PrettyWood** [comment]
Hello @aknaut 
In order to have the `max_length` value, you need to do the validation where it is set i.e. in `Global`

```python
class Global(BaseModel):
    max_length: int
    nested: Nested

    @validator('nested')
    def ensure_length(cls, value: Nested, values: Dict[str, Any]) -> Nested:
        max_length = values['max_length']
        if len(value.array) > max_length:
            raise ValueError(f'nested should have a max length of {max_length}')
        return value


Global(max_length=2, nested={"array": [1, 2]})
# ok !
Global(max_length=1, nested={"array": [1, 2]})
# pydantic.error_wrappers.ValidationError: 1 validation error for Global
# nested
#   nested should have a max length of 1 (type=value_error)
```

Hope it helps !

**Comment by aknaut** [comment]
Thanks for the fast response! This would indeed work if it is the only entry I want to perform validation on. In addition I would also like to be able to perform the check on other appearences of `Nested`. Here is a more complex example I would like to check:

```py
from typing import List
from pydantic import BaseModel, validator

class Nested(BaseModel):

    array: List[int]
    
    @validator("array")
    def check_array(cls, value, values, config):
        if hasattr(config, "max_array_length"):
            if len(value) > config.max_array_length:
                raise ValueError("The values of the array are too long.")
        return value

class OtherEntry(BaseModel):
    
    data: Nested
    

class Global(BaseModel):
    max_length: int
    nested: Nested
    other_nested: OtherEntry
```

For the above example I can achieve the behavior I would like to have by doing something like this:
```py
Global.Config.max_array_length = 2

Global(max_length=2, nested={"array": [1, 2]}, other_nested={"data": {"array": [2, 3, 4]}})
# results in
# other_nested -> data -> array
#  The values of the array are too long. (type=value_error)
Global(max_length=2, nested={"array": [1, 2]}, other_nested={"data": {"array": [2, 3]}})
# works fine
Global(max_length=2, nested={"array": [1, 2, 3]}, other_nested={"data": {"array": [2, 3, 4]}})
# results in
# nested -> array
#  The values of the array are too long. (type=value_error)
# other_nested -> data -> array
# The values of the array are too long. (type=value_error)
```
This solution works fine so far but seems a bit hacky. The `max_array_length` needs to be passed to the config before the creation of the instance and is not dynamically retrieved from the `max_length` entry itself. So I think it would be nice to have a better way of doing this.

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
