### ISSUE TITLE
Add an option in Config to choose which fields to use in __repr_args__

### ISSUE THREAD

**Issue by Lotram** [samuelcolvin/pydantic#1831]
I may have missed something, but it seems there is no way to exclude a field from an object's representation 
# Feature Request
I think it would be nice to have an option in Config to choose which fields to use in `__repr_args__`.

Another solution would be to include an `repr` boolean in the `Field` class, exactly like in dataclasses. I don't find it as convenient as the other solution, but maybe it makes more sense, since it's a per-field option.

# Why
I have multiple big models ( more than 10 fields) and I'd like to reduce the size of their representation (either when using `str()` or `repr()`
So I could override the `BaseModel` to do something like this:
 ```py
from typing import List, Optional

from pydantic import BaseModel


class Model(BaseModel):
    def __repr_args__(self):
        if self.Config._fields_in_repr is None:
            return super().__repr_args__()

        return (
            (key, value)
            for key, value in super().__repr_args__()
            if key in self.Config._fields_in_repr
        )

    class Config:
        _fields_in_repr: Optional[List[str]] = None


class User(Model):
    id: int
    login: str
    bio: str
    # lot of other fields

    class Config:
        _fields_in_repr = ["id", "login"]

user = User(id=1, login="Lotram", bio="This could be a rather long description, I don't want it in the the repr")
repr(user) #  "User(id=1, login='Lotram')"
```
However, IMHO we almost always want to exclude some fields from the object's repr, and I feel like this is generic enough to justify a new option in the `BaseConfig` class.

**Comment by jab** [comment]
> ```python
> class User(Model):
>     ...
>     class Config:
>         _fields_in_repr = ["id", "login"]
> ```

Rather than having list all the fields you want below in a custom Config, what if `pydantic.Field` allowed passing `repr=False` (similar to [`dataclasses.field()`](https://docs.python.org/3/library/dataclasses.html#dataclasses.field) and [`attr.ib()`](https://www.attrs.org/en/stable/api.html#attr.ib))? That way you could opt out of repr participation for a field right at the field definition site:

```python
class User(Model):
    password_hash: bytes = p.Field(..., repr=False)
    ...
```

**Comment by Lotram** [comment]
Yep that's actually the other solution I suggested in the issue :) . I think I said I find it less convenient because you have to call the `Field` class instead of using only annotations, but that's not a real problem, so that's a good solution too.

**Comment by efenka** [comment]
For the `repr=False` I currently use this helper:

```python3
class ReducedRepresentation:
    def __repr_args__(self: BaseModel) -> "ReprArgs":
        return [
            (key, value)
            for key, value in self.__dict__.items()
            if self.__fields__[key].field_info.extra.get("repr", True)
        ]
```
… like this …
```python3
class Instance(ReducedRepresentation, BaseModel):
    node: str
    url: str = Field(repr=False)
```

But would also prefer to have this in the library.
