### ISSUE TITLE
Model-based data generator

### ISSUE THREAD

**Issue by satra** [samuelcolvin/pydantic#1833]
# Question

Is there an automated way to generate data corresponding to a model that passes validation?

i can code something like this up, but wanted to check first if anyone has already implemented something similar.

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
