### ISSUE TITLE
"default" missing in generated schema when default_factory is used

### ISSUE THREAD

**Issue by sjstelmach** [samuelcolvin/pydantic#1836]
The generated schema using .schema() is missing the default when a default_factory is used in lieu of a default.

Using "default" (positional argument):

```
class ManualTaskLogBase(BaseModel):
    timestamp: datetime = Field(datetime.utcnow())
    comment: str = None

    class Config:
        orm_mode = True
```

```
{"title":"ManualTaskLogUpdate","type":"object","properties":{"timestamp":{"title":"Timestamp","default":"2020-08-16T15:15:36.164194","type":"string","format":"date-time"},"comment":{"title":"Comment","type":"string"}}}
```

Using "default_factory"

```
class ManualTaskLogBase(BaseModel):
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    comment: str = None

    class Config:
        orm_mode = True
```

```
{"title":"ManualTaskLogUpdate","type":"object","properties":{"timestamp":{"title":"Timestamp","type":"string","format":"date-time"},"comment":{"title":"Comment","type":"string"}}}
```

**Comment by PrettyWood** [comment]
Hello @sjstelmach 
We used to put a default value in the schema but it has been removed in #1504 to solve issue #1520. And I feel like a field it's less confusing like this. Imagine a datetime that is generated on schema generation. If the default is set with this value, one would expect to have this exact value if not set. Maybe we should just make this clear in the documentation and explain how you can add manually the default value yourself via __modify_schema__

**Comment by sjstelmach** [comment]
Thanks. I think your argument is fair, however the `schema_extra` function seems to be static and can't be set with dynamic values, so it doesn't seem to solve my issue. I'm using this default argument to autogenerate a form in my front end, and it seems desirable for the front end to auto-populate with the default timestamp as of the time the schema is requested. If you can think of another method to achieve this behavior, I'd appreciate it.

**Comment by PrettyWood** [comment]
@sjstelmach 
Here is a hacky solution but at least it should solve your problem.

```python
from datetime import datetime as builtin_datetime
from pprint import pprint
from typing import Any, Dict

from pydantic import BaseModel, Field


class datetime(builtin_datetime):
    @classmethod
    def __modify_schema__(cls, field_schema: Dict[str, Any]) -> None:
        field_schema['default'] = datetime.utcnow()

class ManualTaskLogBase(BaseModel):
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    comment: str = None

    class Config:
        orm_mode = True

pprint(ManualTaskLogBase.schema())
```
```
{'properties': {'comment': {'title': 'Comment', 'type': 'string'},
                'timestamp': {'default': datetime(2020, 8, 16, 21, 5, 52, 919763),
                              'format': 'date-time',
                              'title': 'Timestamp',
                              'type': 'string'}},
 'title': 'ManualTaskLogBase',
 'type': 'object'}
```

You can't directly monkey patch builtins so this is a workaround.
We could however have a parameter in `Field` to decide whether or not we want to feed the default value in the schema (with default value set to `False`).

**Comment by sjstelmach** [comment]
Thanks very much for the response. I gave that a try and it actually ended up cached as well (although possible I'm doing something wrong). I ended up implementing this other hack which is more similar to your proposed solution:

```
class BaseModelDefaultFactory(BaseModel):
    @classmethod
    def schema(cls):
        schema = super().schema()
        for fld_n, fld_v in cls.__fields__.items():
            if fld_v.default_factory is not None:
                schema['properties'][fld_n]['default'] = fld_v.default_factory()
        return schema

class ManualTaskLogBase(BaseModelDefaultFactory):
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    comment: str = ""

    class Config:
        orm_mode = True
```

**Comment by PrettyWood** [comment]
Ah yes indeed the datetime won't be computed again so you'll have the same default value.
So the solution you suggest seems like a very good one and mimics in fact what was done before.

**Comment by RunOrVeith** [comment]
Is there some way to use this base class with potentially nested dataclasses?

If I inherit BaseModelDefaultFactory on my toplevel class I want it to propagate down to any potentially nested dataclass-typed (or List of dataclass, Optional dataclass, ...) fields.
