### ISSUE TITLE
Class variables?

### ISSUE THREAD

**Issue by dsully** [samuelcolvin/pydantic#184]
Is it possible to have class variables that are not part of the schema that is parsed by pydantic?

ie:

```
class MyModel(BaseModel):

     # This is part of pydantic
     group: str = None

     # This is not.
     ACTIONS = ['a', 'b', 'c']```

**Comment by samuelcolvin** [comment]
https://github.com/samuelcolvin/pydantic/blob/0698384788e78b3353877bc44340a00089ea1d3f/pydantic/main.py#L121

Start the name with `_` or use a function with the `@property` decorator.

**Comment by dsully** [comment]
Thanks. Would you accept a PR that also ignored all uppercase class variable names?

**Comment by samuelcolvin** [comment]
Probably not excluding all uppercase variables, but I would accept a PR which either:
* `exclude_uppercase: bool` which when `True` caused uppercase variables to be excluded from validation
* `exclude_vars: Set[str]` where you could provide a bunch of variables names which you wished to exclude

**Comment by jaheba** [comment]
Being able to define attributes which are not being part of the schema being part is also something I'm looking for.

However, I have the suspicion that doing so based on the case of the variable name could be too inflexible. Thus, I would prefer the `exclude_vars` approach much more.

But how about we add a new type, which marks variables as internal?

```py
class MyModel(BaseModel):
     # This is part of pydantic
     group: str = None

     # This is not.
     ACTIONS: Internal[List[str] = ['a', 'b', 'c']```
```

**Comment by samuelcolvin** [comment]
`Internal` makes a lot of sense to me.

I guess it might upset mypy, but that doesn't both me much.

**Comment by jaheba** [comment]
I think I've found a way to trick mypy. We can abuse a `Union`, where one case is an internal field. That way, we can check whether that var is internal and still have the mypy guarantees.

```py
class _internal:
    pass

T = TypeVar('T')

Internal = Union[_internal, T]

# accepted by mypy
x: Internal[int] = 42
```

**Comment by samuelcolvin** [comment]
Makes sense to me, I neither know nor care whether it's an abuse of typing.

**Comment by samuelcolvin** [comment]
Humm, maybe we need to think harder about using types to indicate things that don't relate to type. Could be very confusing.

**Comment by jaheba** [comment]
> Humm, maybe we need to think harder about using types to indicate things that don't relate to type. Could be very confusing.

I agree.

I think what we are looking for is a way to annotate settings for each field. The problem is that we are limited in ways to do so:

    a) variable name (e.g. variables starting with an `_` are currently ignored)
    b) type annotation
    c) default value the field is set to
    d) using external annotations, such as the `Config` class

In Rust for example, one can also annotate things using the `#[...]` syntax. But we don't have that option in Python.

Out of the ones listed, I would currently prefer c) :

```python
class MyModel(BaseModel):
    x: int = Internal(42)
```

What I am currently worried about, if there are other annotations we would like to add which would make this approach unfeasable. Maybe something like this would be better than:

```python
class MyModel(BaseModel):
    x: int = Field(42, internal=True, allow_mutation=False)
```

**Comment by jaheba** [comment]
> That's already work going on. See #190, #129.

Oh, that looks nice. I think that would probably be the right place to add the feature then.

> Also, internal is a confusing name as it indicates they can only be used inside the class. Maybe it should be called "ignored". And I'd rather just keep it in config for cleanness.

Agreed `internal` is just what first came to mind. Although I'm not sure if `ignored` is unambigious either. But I guess that's a discussion for another time.

**Comment by koliyo** [comment]
First of all, I would also like this feature.

As a workaround I am trying to use the `_foo` declaration syntax. But with this I am not allowed to explicitly set the value of the object.
```python
o = Foo(**data)
o._bar = 3
```
Then I get
```
ValueError: "Foo" object has no field "_bar"
```

**Comment by Michael-J-Ward** [comment]
Would taking advantage of `typing.ClassVar` be a good candidate for this? Seems like `pydantic` doesn't currently allow those.

```
from typing import ClassVar
from pydantic import BaseModel

class MyModel(BaseModel):
    foo: ClassVar[int] = 3
    bar: float

Traceback (most recent call last):
  File "python3.6/site-packages/pydantic/validators.py", line 262, in find_validators
    if issubclass(type_, val_type):
TypeError: issubclass() arg 1 must be a class
```

**Comment by tiangolo** [comment]
You can always create a class inside of the model class.

And store there any class-level constants you need.

Pydantic won't interact with it:

```Python
from pydantic import BaseModel

class User(BaseModel):
    username: str
   
    class Meta:
        model_type = "user"

user = User(username="john")

print(user)
print(user.dict())
print(user.Meta.model_type)
```

prints:

```
User username='john'
{'username': 'john'}
user
```

**Comment by Midnighter** [comment]
That's a fair workaround. I just had some dataclasses already defined and then got bitten by two things:

1. Can't nest dataclasses using pydantic (yet).
2. Can't use `typing.ClassVar`.
