### ISSUE TITLE
How to define unnecessary path parameter?

### ISSUE THREAD

**Issue by FyZzyss** [samuelcolvin/pydantic#1845]
I want to define unnecessary path parameter. How I can do this?
My attempt:
```python
@router.post("/payments/{file_type}", response_description='', response_model=StatsOutputList)
async def payments(stats: StatsInput, file_type: Optional[str] = Path(None)):
```

**Comment by PrettyWood** [comment]
@FyZzyss I edited your code please pay attention to the formatting of your message.
Furthermore by the look of it, it seems like a *fastapi* question.
If it's in fact a pydantic one, please give more details
