### ISSUE TITLE
Can I make a default value in pydantic if None is passed in the field without using validators?

### ISSUE THREAD

**Issue by FyZzyss** [samuelcolvin/pydantic#1851]
Can I make a default value in pydantic if None is passed in the field without using validators?
 
I have the following code, but it seems to me that the validator here is superfluous for contract_ndfl. Is there any way to do without a validator?

**My code:**

      class User(BaseModel):
            user: int
            s_name: str
            contract_ndfl: Optional[int]
            
    
           @validator('contract_ndfl')
           def set_contract_ndfl(cls, v):
               return v or 13

**Wishful code:**

    class User(BaseModel):
          user: int
          s_name: str
          contract_ndfl: Optional[int] = 13

**Comment by PrettyWood** [comment]
Hello @FyZzyss 
If you want to allow `None` as value, you need to do exactly what you did (maybe just do `return v if v is not None else 13` to allow `0` as value.
You could also write a small helper if you really don't want the validator

```python
class User(BaseModel):
    user: int
    s_name: str
    contract_ndfl: int = 13

def create_user(**kwargs) -> User:
    return User(**{k: v for k, v in kwargs.items() if v is not None})

u = create_user(user=1, s_name='a', contract_ndfl=None)
assert u.contract_ndfl == 13
```

**Comment by FyZzyss** [comment]
@PrettyWood Hello!
Thanks for the answer. The second example is convenient, but it doesn't work when some fields can be left with None. I think it would be convenient for `Optional` or another entity to make a default value if the field is None.

**Comment by zshimanchik** [comment]
How is it completed?
