### ISSUE TITLE
Get rid of mypy forward ref error with plugin

### ISSUE THREAD

**Issue by hector-sab** [samuelcolvin/pydantic#1853]
# Question
Is it possible to get rid of the following error with the current plugin of pydantic when updating the forward references?

```
[mypy error] [E] "Type[MetricsConfig]" has no attribute "__pydantic_model__"
```

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /home/hector/anaconda3/envs/store_tester/lib/python3.8/site-packages/pydantic
               python version: 3.8.3 (default, May 19 2020, 18:47:26)  [GCC 7.3.0]
                     platform: Linux-5.8.0-2-MANJARO-x86_64-with-glibc2.10
     optional deps. installed: ['typing-extensions']
```

# Snipets to reproduce
```py
# test.py
from pydantic.dataclasses import dataclass

@dataclass
class A:
    a: int

A.__pydantic_model__.update_forward_refs()
```

```
# mypy.ini
[mypy]
plugins = pydantic.mypy
```

```bash
$ mypy test.py --config-file mypy.ini
```

**Comment by PrettyWood** [comment]
Hello @hector-sab 
The real issue is that with
```python
@dataclass
class A: ...
```
`A` is of type `A` and not of type `Type[DataclassType]`
Don't know how hard it would be to tweak this

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
