### ISSUE TITLE
Access pydantic models for code generation to other languages

### ISSUE THREAD

**Issue by hellozyemlya** [samuelcolvin/pydantic#1855]
# Question

Is that possible somehow traverse pydantic models structures in order to get all fields, possible validations and other stuff in order to generate models code for other languages?

**Comment by hellozyemlya** [comment]
Looks like models has __fields__ member that can help me.

**Comment by hellozyemlya** [comment]
Any additional input for this question is welcome.

**Comment by hmvp** [comment]
Somewhat related:
We use [the json schema functionality](https://pydantic-docs.helpmanual.io/usage/schema/) to generate a form in the frontend. I am not sure if that satisfies your requirements, but it is an implementation and the json schema generally encode quite a lot of the constraints (not custom validations though)

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
