### ISSUE TITLE
Union is not interpreted correctly with nested lists

### ISSUE THREAD

**Issue by StefanUlbrich** [samuelcolvin/pydantic#1861]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: False
                 install path: /home/XXXXX/.cache/pypoetry/virtualenvs/XXXXX-py3.7/lib/python3.7/site-packages/pydantic
               python version: 3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0]
                     platform: Linux-5.4.0-42-generic-x86_64-with-debian-bullseye-sid
     optional deps. installed: ['typing-extensions']
```

Hi, I want to serialize a tree like structure composed of nodes that have children.
However, each node not only has children of the same type, it should also accept a list thereof (this list represents a serial sub-tree without forks). My code looks like this:

```py
import pydantic

class NodeModel(BaseModel):

    name: Optional[str]

    children: Optional[
        Union[
            List["NodeModel"], 
            List[List["NodeModel"]]
        ]
    ]

    class Config:
        orm_mode = True
```

Children should either be a list of nodes or a (nested) list of list of nodes. Is this supposed to be possible?

When I create a tree:

```py
n=NodeModel(
    children = [
          [n1,n2],
          n3
)
# 
```

The JSON output looks like this

```json
{
    "children": [
        {
            "children": null,
            "name": null,
        },
        {
            "children": null,
            "name": "n3",
        },
    ],
}
```

the list of list of nodes seems to be mistaken as a node and not parsed at all. Right now, I resolve to only accepting lists of lists (which is semantically the same in my case), but I would prefer if the union were respected.

**Comment by PrettyWood** [comment]
Hello @StefanUlbrich 
There is a known issue about unions. See #619 and #1423 for more information.
But still here I can't reproduce your issue.
Could you please provide a working example of the issue ?

**Comment by StefanUlbrich** [comment]
Thanks for the answer and my apologies for getting back so late :-( 

I extended the code example and run it in a notebook:

```python
from pydantic import BaseModel
from typing import Optional, List, Union
from json import dumps, loads


class NodeModel(BaseModel):

    name: Optional[str]

    children: Optional[Union[List["NodeModel"], List[List["NodeModel"]]]]

    class Config:
        orm_mode = True

n1, n2, n3 = NodeModel(name="1"), NodeModel(name="2"), NodeModel(name="3")
n = NodeModel(name="root", children=[[n1, n2], n3])
print(dumps(loads(n.json()), indent=4))
```

The output is:

```json
{
    "name": "root",
    "children": [
        {
            "name": null,
            "children": null
        },
        {
            "name": "3",
            "children": null
        }
    ]
}
```

However, what I expect / intend is the following structure:

```json
{
    "name": "root",
    "children": [
        [
            {
                "name": "1",
                "children": null
            },
            {
                "name": "2",
                "children": null
            },
        ],
        {
            "name": "3",
            "children": null
        }
    ]
}
```

**Comment by StefanUlbrich** [comment]
Just realized that there is a logical error in the example above ( `[[n1, n2], n3]` should not fit the definition for children).

Correctly, the class should be:

```python
class NodeModel(BaseModel):
    name: str
    children: Optional[List[Union["NodeModel", List["NodeModel"],]]]
```

The main problem in my example, however, is that not all attributes can be Optional. Otherwise, any list object will be interpreted as a NodeModel (without name or children). 

I would have expect the validation to recognize that it is a list object and raise an error. Why doesn't this happen?

**Comment by samuelcolvin** [comment]
I think this is covered by #619 and #1423
