### ISSUE TITLE
How to trigger validation manually on object?

### ISSUE THREAD

**Issue by iedmrc** [samuelcolvin/pydantic#1864]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /usr/local/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Jul 21 2020, 10:48:26)  [Clang 11.0.3 (clang-1103.0.32.62)]
                     platform: macOS-10.15.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```
Hi, I create a pydantic model that doesn't validate on creation, by using `construct()` method. But I want to validate on the object after creation, manually. How to trigger validation? 
E.g.:
```py
from pydantic import BaseModel
class OrderModel(BaseModel):
    name: str

order = OrderModel.construct()
order.a_method_that_validates_the_model() # I need that function.
```

I tried, `validate()` but got `TypeError: validate() takes exactly 2 positional arguments (1 given)` . I looked at the codebase and seems like this is not I want? because it excepts the model as the first argument and it is a classmethod.

**Comment by PrettyWood** [comment]
Hello @iedmrc 
Here you go
```python
from pydantic import BaseModel, validate_model


class OrderModel(BaseModel):
    name: str

order = OrderModel.construct()

def validate(model: BaseModel):
    *_, validation_error = validate_model(model.__class__, model.__dict__)
    if validation_error:
        raise validation_error

validate(order)
# pydantic.error_wrappers.ValidationError: 1 validation error for OrderModel
# name
#   field required (type=value_error.missing)
```
Hope it helps !

**Comment by iedmrc** [comment]
Thanks a lot! Do you mind to add this to `BaseModel` itself?

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).

**Comment by PATAPOsha** [comment]
@PrettyWood is it possible to write same method but for `@dataclass` objects?

**Comment by PrettyWood** [comment]
@PATAPOsha you can do the same on `__pydantic_model__` attribute.
In 1.9 you may have an easier way with https://github.com/samuelcolvin/pydantic/pull/2557/files#diff-6e41cd44e1651989bc1c3b905e42ea4c7bc97eba421b5a9f1e975de512df5416R21

**Comment by kmccurley** [comment]
This was closed, but I wasn't able to find any resolution of the issue.

**Comment by jgunstone** [comment]
@PrettyWood - I've been try to use your snippet above but am slightly confused by the behaviour / don't think it works for my use case... 

in my use case I'm using validators to create relationships between properties, so i tested as follows:

```py
from pydantic import BaseModel as PydanticBaseModel, validate_model

class BaseModel(PydanticBaseModel):
    def check(self):
        *_, validation_error = validate_model(self.__class__, self.__dict__)
        if validation_error:
            raise validation_error

class OrderModel(BaseModel):
    name: str = 'default name'
    
    @validator("name", always=True, pre=True)
    def _name(cls, v, values):
        print('check run')
        return 'validator name'

# 1
# upon initiation validator called as normal 
>>> OrderModel()
"check run"
OrderModel(name='validator name')

# 2
# upon construct, validator not called. model reverts to default. 
>>> order = OrderModel.construct()
>>> order 
OrderModel(name='default name')

# 3
# use check to run the validator
>>> order.check()
"check run" # validator called
>>> order 
OrderModel(name='default name') # but name still remains as "default name" rather than "validator name"

```

so your snippet works for catching validation errors but doesn't work for updating relationships between properties using validators? is there a way to add this functionality? 

many thanks

**Comment by ryshoooo** [comment]
> @PrettyWood - I've been try to use your snippet above but am slightly confused by the behaviour / don't think it works for my use case...
> 
> in my use case I'm using validators to create relationships between properties, so i tested as follows:
> 
> ```python
> from pydantic import BaseModel as PydanticBaseModel, validate_model
> 
> class BaseModel(PydanticBaseModel):
>     def check(self):
>         *_, validation_error = validate_model(self.__class__, self.__dict__)
>         if validation_error:
>             raise validation_error
> 
> class OrderModel(BaseModel):
>     name: str = 'default name'
>     
>     @validator("name", always=True, pre=True)
>     def _name(cls, v, values):
>         print('check run')
>         return 'validator name'
> 
> # 1
> # upon initiation validator called as normal 
> >>> OrderModel()
> "check run"
> OrderModel(name='validator name')
> 
> # 2
> # upon construct, validator not called. model reverts to default. 
> >>> order = OrderModel.construct()
> >>> order 
> OrderModel(name='default name')
> 
> # 3
> # use check to run the validator
> >>> order.check()
> "check run" # validator called
> >>> order 
> OrderModel(name='default name') # but name still remains as "default name" rather than "validator name"
> ```
> 
> so your snippet works for catching validation errors but doesn't work for updating relationships between properties using validators? is there a way to add this functionality?
> 
> many thanks

I was having the same issue. After a bit of digging, I found the piece of code which validates and update values from validators as well:
```
class BaseModel(PydanticBaseModel):
    def check(self):
        values, fields_set, validation_error = validate_model(
            self.__class__, self.__dict__
        )
        if validation_error:
            raise validation_error
        try:
            object.__setattr__(self, "__dict__", values)
        except TypeError as e:
            raise TypeError(
                "Model values must be a dict; you may not have returned "
                + "a dictionary from a root validator"
            ) from e
        object.__setattr__(self, "__fields_set__", fields_set)
```

**Comment by pinkfrog9** [comment]
`validate_model` is removed in V2, any alternative approach?

**Comment by warvariuc** [comment]
My workaround is 
```python
obj = MyModel(**obj.model_dump())
```
But it's a little bit ugly.

**Comment by melwil** [comment]
I was using model_validate in my unit tests for models, since I'm doing some logic on certain models, and depending on how they were treated in FastAPI, the model may not be served correctly by FastAPI.

So my question would also be; what pydantic validations do FastAPI apply before serving data now? I would like to have these unit tests still, but adding custom validators to all my models seems a bit excessive?

**Comment by atlantis-dsf** [comment]
> My workaround is
> 
> ```python
> obj = MyModel(**obj.model_dump())
> ```
> 
> But it's a little bit ugly.

Yeah this doesn't work if you're using field_serializers

**Comment by Ja-sonYun** [comment]
from pydantic v2, it seems like we can do this
```python
from pydantic import BaseModel
from pydantic_core import SchemaValidator

class Model(BaseModel):
    def check(self) -> None:
        schema_validator = SchemaValidator(schema=self.__pydantic_core_schema__)
        schema_validator.validate_python(self.__dict__)
```
This works well. It looks like this workaround is faster than MyModel(**obj.model_dump()) as well.
I didn't check about field_serializers.

**Comment by Ja-sonYun** [comment]
from pydantic v2, it seems like we can do this
```python
from pydantic import BaseModel
from pydantic_core import SchemaValidator


def check_schema(model: BaseModel) -> None:
    schema_validator = SchemaValidator(schema=model.__pydantic_core_schema__)
    schema_validator.validate_python(model.__dict__)


class Sample(BaseModel):
    number: int
    string: str


sample = Sample(number=1, string="string")
sample.number = "string"
sample.string = 1
check_schema(sample)
# pydantic_core._pydantic_core.ValidationError: 2 validation errors for Sample
# number
#   Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='string', input_type=str]
#     For further information visit https://errors.pydantic.dev/2.5/v/int_parsing
# string
#   Input should be a valid string [type=string_type, input_value=1, input_type=int]
#     For further information visit https://errors.pydantic.dev/2.5/v/string_type

```
This works well. It looks like this workaround is faster than `MyModel(**obj.model_dump())` as well.
I didn't check about field_serializers.
