### ISSUE TITLE
[Question] BaseSettings dynamic / computed values?

### ISSUE THREAD

**Issue by 1oglop1** [samuelcolvin/pydantic#1865]
# BaseSettings computed / dynamic values
Hello, can anyone please guide me to what is the correct way create computed fields by using Base settings?
I may be misunderstanding it's purpose though, if you find that true, could you please point me to the better solution?

At the moment I'm using this as a workaround and I do not think this is the correct way to do it.

```py
from pydantic import BaseSettings
from typing import Optional

class MySettings(BaseSettings):
    DB_USER: str = "usr"
    DB_PASSWORD: str = "pwd"
    URL: Optional[str]


settings = MySettings()

settings.DB_URL = f"https://{settings.DB_USER}:{settings.DB_PASSWORD}@localhost:8080"

print(settings.DB_URL)

```

**Comment by zoopp** [comment]
YMMV but I've been using root validators to achieve this kind of behavior:

```python
from typing import Optional

from pydantic import BaseSettings, root_validator


class Settings(BaseSettings):
    DB_USER: str = "usr"
    DB_PASSWORD: str = "pwd"
    DB_URL: Optional[str]

    @root_validator
    def _maybe_parse_url(cls, values):
        if values.get('DB_URL', None) is None:
            values['DB_URL'] = f"https://{values['DB_USER']}:{values['DB_PASSWORD']}@localhost:8080"
        return values


print(Settings())
# DB_USER='usr' DB_PASSWORD='pwd' DB_URL='https://usr:pwd@localhost:8080'

print(Settings(DB_USER='Mario'))
# DB_USER='Mario' DB_PASSWORD='pwd' DB_URL='https://Mario:pwd@localhost:8080'
```

**Comment by 1oglop1** [comment]
Thanks @zoopp I intended to use validators for this but I missed the important section in the docs that you can use `values` to get the dict!


> values: a dict containing the name-to-value mapping of any previously-validated fields
> config: the model config
> field: the field being validated
> **kwargs: if provided, this will include the arguments above not explicitly listed in the signature

This goes well with the `root_validator` and feels more like intended behaviour.
Thanks again this helped me a lot!

**Comment by PrettyWood** [comment]
Why not simply use `validator` like [here](https://pydantic-docs.helpmanual.io/usage/validators/#validate-always)
Using `root_validator` for this seems a bit overkill

**Comment by zoopp** [comment]
That works if you don't depend on other field values that are part of the model. With `@validator` you don't get access to other fields or the instance itself, right?

**Comment by PrettyWood** [comment]
Yes you do. You have access to all the fields prior to the one currently checked.
Look at the first example on validators
```python
    @validator('password2')
    def passwords_match(cls, v, values, **kwargs):
        if 'password1' in values and v != values['password1']:
            raise ValueError('passwords do not match')
        return v
```

**Comment by zoopp** [comment]
Ah, you're right, I was not aware of that. I should have paid better attention when reading the docs. :+1:

**Comment by 1oglop1** [comment]
Thanks @PrettyWood  for clearing out, I was trying to use simple validator but I kept getting validation error

```
pydantic.error_wrappers.ValidationError: 1 validation error for MySettings
DB_URL
  'NoneType' object is not subscriptable (type=type_error)
```

After reading your code the problem became more obvious that your function `passwords_match` function takes 3 arguments while I just simply tried to use it like `passwords_match(cls, values)` and did not realise the problem until now.

so this is the final solution

```
class MySettings(BaseSettings):
    DB_USER: str = "usr"
    DB_PASSWORD: str = "pwd"
    DB_URL: str = None

    @validator('DB_URL', pre=True)
    def passwords_match(cls, values):
        print(values)
        return f"together: {values['DB_USER']} and {values['DB_PASSWORD']}"

settings = MySettings()
assert settings.DB_URL == "together: usr and pwd"
```

I usually have troubles reading and if things are not super obvious (colour coding or in the right place) I miss them.

This made me thinking if the argument explanation section did not come a little late in docs and for these reasons I tend to explore `apidoc` usually generated with sphinx. I'm happy to contribute this if there is an interest.

**Comment by creatineabuser** [comment]
# Solution for Pydantic V2+ using @field_validator:
```python
from typing import Optional
from pydantic import BaseSettings, Field, field_validator
from pydantic_core import ValidationInfo

class Settings(BaseSettings):
    DB_HOST: str = 'localhost'
    DB_PORT: int = 5432
    DB_USER: str = 'postgres'
    DB_PASS: str = 'password'
    DB_NAME: str = 'database'
    DB_URL: Optional[str] = Field(default=None)

    @field_validator("DB_URL", mode="before")
    @classmethod
    def assemble_db_url(cls, v: Optional[str], values: ValidationInfo) -> str:
        if v is None:
            return (
                f"postgresql+asyncpg://{values.data['DB_USER']}:"
                f"{values.data['DB_PASS']}@{values.data['DB_HOST']}:"
                f"{values.data['DB_PORT']}/{values.data['DB_NAME']}"
            )
        return v

settings = Settings()

print(settings.DB_URL) # prints 'postgresql+asyncpg://postgres:password@localhost:5432/database'
```
The @field_validator("DB_URL", mode="before") decorator is used to validate and compute the value of DB_URL; **'mode='before' indicates that the validator should be called before the field is validated**.
Method `assemble_db_url` checks if DB_URL is None. If it is, the method constructs the URL based on other fields (DB_USER, DB_PASS, DB_HOST, DB_PORT, and DB_NAME); **`values: ValidationInfo` parameter provides access to fields' values via values.data**

**Comment by amoralesc** [comment]
Small nitpick for those using typing in the solution presented by https://github.com/pydantic/pydantic/issues/1865#issuecomment-2222725343, I have to import `FieldValidationInfo` from `pydantic_core.core_schema` like this:

```python
from typing import Optional

from pydantic import BaseSettings, Field, field_validator
from pydantic_core.core_schema import FieldValidationInfo # <- here

class Settings(BaseSettings):
    DB_HOST: str = 'localhost'
    DB_PORT: int = 5432
    DB_USER: str = 'postgres'
    DB_PASS: str = 'password'
    DB_NAME: str = 'database'
    DB_URL: Optional[str] = Field(default=None)

    @field_validator("DB_URL", mode="before")
    @classmethod
    def assemble_db_url(
        cls,
        v: Optional[str],
        values: FieldValidationInfo, # <- here
    ) -> str:
        if v is None:
            return (
                f"postgresql+asyncpg://{values.data['DB_USER']}:"
                f"{values.data['DB_PASS']}@{values.data['DB_HOST']}:"
                f"{values.data['DB_PORT']}/{values.data['DB_NAME']}"
            )
        return v

settings = Settings()

print(settings.DB_URL) # prints 'postgresql+asyncpg://postgres:password@localhost:5432/database'
```

`ValidationInfo` isn't a member of a `pydantic_core`.
