### ISSUE TITLE
How to properly extend on non-validated BaseModel?

### ISSUE THREAD

**Issue by iedmrc** [samuelcolvin/pydantic#1867]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /usr/local/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Jul 21 2020, 10:48:26)  [Clang 11.0.3 (clang-1103.0.32.62)]
                     platform: macOS-10.15.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```
I need a model that extends on pydantic BaseModel which doesn't validate on initialization. I tried many methods but either couldn't really extend on BaseModel or got recursion error. Some examples are:

```py
from pydantic import BaseModel, create_model

class PydanticBaseModel(BaseModel):
    def __new__(cls, *args, **kwargs):
        return super().construct(BaseModel)
```

```py
from pydantic import BaseModel, create_model

class PydanticBaseModel(BaseModel):
    def __new__(cls, *args, **kwargs):
        return create_model(
            'PydanticBaseModel',
            apple='russet',
            banana='yellow',
            __base__=BaseModel,
        )
```

```py
from pydantic import BaseModel, create_model

class PydanticBaseModel(BaseModel):
    def __new__(cls, *args, **kwargs):
        model = create_model(
            'PydanticBaseModel',
            apple='russet',
            banana='yellow',
            __base__=BaseModel,
        )
        return type("PydanticBaseModel", (model, ), dict(model.__dict__))
```

This one which only works:

```py
from pydantic import BaseModel, create_model

class PydanticBaseModel(BaseModel):
    def __new__(cls, *args, **kwargs):
        return BaseModel.construct()
```

But I'm not sure is this the correct way? I don't want to call a function (e.g. `create_model()`) directly. I need to extend that model so I can integrate this with my other classes and keep my code clean.

**Comment by iedmrc** [comment]
Okay, this is what is the best IMO:

```py
from pydantic import BaseModel, validate_model

class PydanticBaseModel(BaseModel):
    def __new__(cls, *args, **kwargs):
        cls.__new__ = super().__new__
        return super().construct()
```

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
