### ISSUE TITLE
Extra.ignore seems not working

### ISSUE THREAD

**Issue by iedmrc** [samuelcolvin/pydantic#1871]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /usr/local/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Jul 21 2020, 10:48:26)  [Clang 11.0.3 (clang-1103.0.32.62)]
                     platform: macOS-10.15.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

[docs](https://pydantic-docs.helpmanual.io/usage/model_config/) says Extra.ignore will silently ignore any extra attributes but it throws error in my case:
```
File "pydantic/main.py", line 345, in pydantic.main.BaseModel.__setattr__
ValueError: "Order" object has no field "_id"
```

And when I checked these lines https://github.com/samuelcolvin/pydantic/blob/master/pydantic/main.py#L362 , I saw that there is no checking on "ignore" config. Shouldn't have been added an `if` case there?

**Comment by PrettyWood** [comment]
@iedmrc could you please provide a full code example to reproduce please?

**Comment by iedmrc** [comment]
Sorry my bad. Here is an example model:

```py
from pydantic import BaseModel

class Order(BaseModel):
    name: str

    class Config:
        extra = "ignore"


order = Order.construct(name="John")
order.extra_field = "test"
print(order)
```

with this piece of code, I get
```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    order.extra_field = "test"
  File "pydantic/main.py", line 345, in pydantic.main.BaseModel.__setattr__
ValueError: "Order" object has no field "extra_field"
```
If I replace 'ignore' with allow, it works. Ignore just works as "forbid". Doesn't handle silently.

**Comment by PrettyWood** [comment]
Yes you're right but the doc says
> whether to ignore, allow, or forbid extra attributes during model initialization
So it's only ignored at init not when you set attributes after.
Don't know if this should be changed also for setattr

**Comment by iedmrc** [comment]
Shouldn't I add extra fields after initialization? Or is there any workaround do you suggest?

**Comment by PrettyWood** [comment]
You can hack it! Instead of doing `order.extra_field = "test"` do `object.__setattr__(order, 'extra_field', 'test')` ;)
Hope it helps!
