### ISSUE TITLE
How to avoid circular imports when using models (defined in different modules) which refers to each other?

### ISSUE THREAD

**Issue by AntonOvsyannikov** [samuelcolvin/pydantic#1873]
How to avoid circular imports when using models (defined in different modules) which refers to each other?

Just to illustrate there is synthetic example.
```
# m1.py
from typing import Optional
from pydantic import BaseModel
from m2 import M2
class M1(BaseModel):
    foo: Optional[M2]
```

```
# m2.py
from typing import Optional
from pydantic import BaseModel
from m1 import M1
class M2(BaseModel):
    bar: Optional[M1]
```
```
# main.py
from m1 import M1
print(M1(**{'foo': {'bar': None}}))
# ImportError: cannot import name 'M1' from 'm1' in m2.py line 3
```

The way I found is to modify **m1.py**  like this

```
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel
class M1(BaseModel):
    foo: Optional[M2]  # or use ForwardRef('M2') instead of from __future__ import annotations
from m2 import M2
M1.update_forward_refs()
```
Now main.py works
```
foo=M2(bar=None)
```

But the solution is quite counterintuitive, so we we need to modify **m1.py** while import error happens in **m2.py**, and if there are more models, with some graph of dependencies, things goes more complicated, not sure we can handle three or more models this way. Also placing import in the bottom of the file violates PEP-8. 

Is there some more generalized solution? Maybe place `ForwardRef` s in separate module and use it as C-style header files?

**Comment by ri-gilfanov** [comment]
@AntonOvsyannikov, if use standard data classes, then circular imports is solved like this:
```
# m/__init__.py
import m1
import m2
```
```
# m/m1.py
from typing import Optional
from dataclasses import dataclass
import m
@dataclass
class M1:
    foo: Optional['m.m2,M2']
```
```
# m/m2.py
from typing import Optional
from dataclasses import dataclass
import m
@dataclass
class M2:
    bar: Optional['m.m1.M1']
```
```
# main.py
from m.m1 import M1
from m.m2 import M2
e1 = M1(foo=M2())
e2 = M2(bar=M1())
```
But this approach doesn't work with Pydantic.

P.S. A very similar question has already been raised here https://github.com/samuelcolvin/pydantic/issues/707 a year ago.

**Comment by shawnwall** [comment]
also having this problem, and not figuring out any clear solutions besides heavy refactoring. Note I'm using this in a fastapi context following some rather modular patterns for crud with a lot of specific files.

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
