### ISSUE TITLE
GenericModel "got 'GenericAlias" instead"

### ISSUE THREAD

**Issue by vitidev** [samuelcolvin/pydantic#1878]
How to solve this problem? Whose bug is this?
pycharm 2020.2 python3.8.5
![Image 3](https://user-images.githubusercontent.com/2243958/91462033-61172f00-e892-11ea-91ca-1a188b3d9230.png)

**Comment by PrettyWood** [comment]
Hi @vitidev 
Make sure to set `GenericModel` before `Generic[DataT]`
Other than that I'm sorry but I can't reproduce with PyCharm 2020.1 CE and Python 3.8.2. Do you use PyCharm plugin?
