### ISSUE TITLE
Why is pydantic not converting values according to the fields types when using copy or assignment?

### ISSUE THREAD

**Issue by gidgid** [samuelcolvin/pydantic#1896]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /Users/gidgid/.pyenv/versions/3.8.3/envs/testenv/lib/python3.8/site-packages/pydantic
               python version: 3.8.3 (default, Jul 12 2020, 10:07:38)  [Clang 11.0.3 (clang-1103.0.32.62)]
                     platform: macOS-10.15.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

I just came across a surprising behavior. I was expecting Pydantic to convert values according to the item's types when using `copy(update={...})` or when using assignment but I was surprised to find out this is not the case. 
Better explained with this piece of code:
```py
from typing import List
from pydantic import BaseModel


class Person(BaseModel):
    name: str
    nicknames: List[str]


p1 = Person(name="test-name1", nicknames={"n1", "n2"})
assert sorted(p1.nicknames) == ["n1", "n2"]

p2 = p1.copy()
p2.nicknames = {"n1", "n2"}
assert p2.nicknames == {"n1", "n2"}

p3 = p1.copy(update={"nicknames": {"n1", "n2"}})
assert p3.nicknames == {"n1", "n2"}

```

I was expecting both `p2` & `p3` to have `nicknames` converted to list and I was wondering what is the reason for not enforcing this logic?

Thanks!

**Comment by PrettyWood** [comment]
Hello @gidgid 
It has nothing to do with `copy` but with assignment
```python
p1 = Person(name="test-name1", nicknames={"n1", "n2"})
assert isinstance(p1.nicknames, list)
p1.nicknames = 'qweqwe'
assert isinstance(p1.nicknames, str)
```

If you want to validate at initialisation but also at assignment, you can just add
```python
class Person(BaseModel):
    ...

    class Config:
        validate_assignment = True
```

which will then raise the error
```
pydantic.error_wrappers.ValidationError: 1 validation error for Person
nicknames
  value is not a valid list (type=type_error.list)
```

**Comment by gidgid** [comment]
Thanks again @PrettyWood for responding so quickly
I've got a couple of questions regarding your answer:
1. this is a somewhat surprising behavior - do you happen to know what's the rationale for not making the `validate_assignment = True` by default? What are the use cases for using it as it is now?
2. Is it possible to make Pydantic perform the conversion for me on assignment (from `Set[str]` to `List[str]`)? If so, how?
3. Does `copy` use assignment under the hood?

Thanks again for taking the time to reply

**Comment by PrettyWood** [comment]
To answer your questions in order:
- I tend to agree with you. Tbh I set to `True` it by default in my own custom `BaseModel` that we use in one of the projects I lead. Maybe we could suggest to change it in version 2 like here https://github.com/samuelcolvin/pydantic/issues/809 (in which case we should open a new issue and add it in the milestone)
- You should be able to do it via a `validator`. I can have a look once I put my hands on my computer
- No

**Comment by gidgid** [comment]
it does help
Thanks for taking the time to answer all these questions 🙏

**Comment by mojtabaahn** [comment]
Great question and great answer.
I also think this (validate_assignment=True) should be default behavior.
Thank you

**Comment by samuelcolvin** [comment]
I think mostly I don't want assignment validation on, but I can see it both ways.

**Comment by edmondop** [comment]
Conversion does not occur when using set_attr. Any workaround?
