### ISSUE TITLE
slow dynamic model creation / schema caching?

### ISSUE THREAD

**Issue by havok2063** [samuelcolvin/pydantic#1919]
I need to be able to dynamically create a large number of schema, and de-serialize a list of objects for each schema.  I won't know ahead of time how many schema/objects I'll have so it needs to be dynamic and relatively fast.  It seems `create_model` is quite slow when generating a schema compared to `marshmallow`.  Is there a recommended way of speeding this up or caching schema creation?   Any ideas why `create_model` is slow, or any alternatives to speed this up?

`pydantic` is faster than `marshmallow` at object deserialization but much slower at dynamic schema creation.   Here are some timing tests compared to `marshmallow`.  

First test is dynamic schema creation for 1 schema, by itself.
```
# Pydantic 
303 µs ± 3.99 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

# Marshmallow
185 µs ± 2.03 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

Second test is object deserialization for 1 object, by itself.
```
# Pydantic 
6.57 µs ± 299 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

# Marshmallow
26 µs ± 826 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

Third test is the dynamic schema creation and object deserialization for 5 schema (defined in yaml files), each schema having between 2-12 objects to deserialize.  One schema has ~100 objects.  
```
# pydantic schema generation + object deserialization
%timeit -n 10 -r 7 pyd(models)
871 ms ± 173 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

# marshmallow schema generation + object deserialization
%timeit -n 10 -r 7 marsh(models)
112 ms ± 3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.6.1
pydantic compiled: True
install path: /Users/Brian/anaconda3/lib/python3.7/site-packages/pydantic
python version: 3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1 (tags/RELEASE_401/final)]
platform: Darwin-18.7.0-x86_64-i386-64bit
optional deps. installed: ['typing-extensions', 'email-validator']
```

**Comment by havok2063** [comment]
So after digging a bit deeper, I realized I wasn't comparing apples to apples.  I had one terminal testing `pydantic` in a conda virtual environment and one terminal testing `marshmallow` in my base conda environment.  When I test both packages in the same environment, `pydantic` is a bit faster, but both packages are incredibly slow inside a conda virtual environment running python 3.8.5.

Both environments run the following code, using `pydantic 1.6.1` and `marshmallow 3.7.1`, running my third test from above.
```
import os, pathlib
from cthreepo.io.yaml import get_yaml_files, read_yaml
from cthreepo.core.models import generate_models
from cthreepo.core.pydmodels import generate_models as pyd_gen_model

datamodel_dir = os.environ['CTHREEPO_DIR'] / pathlib.Path('datamodel/manga')
models = get_yaml_files(datamodel_dir, get='models')

def pyd(models):
    dd={}
    for file in models:
        data = read_yaml(file)
        dd[file.stem] = pyd_gen_model(data)
        return dd

def marsh(models):
    dd={}
    for file in models:
        data = read_yaml(file)
        dd[file.stem] = generate_models(data)
        return dd
```

My default anaconda environment running Python 3.7.3 
```
python -c "import pydantic.utils; print(pydantic.utils.version_info())"
pydantic version: 1.6.1
pydantic compiled: True
install path: /Users/Brian/anaconda3/lib/python3.7/site-packages/pydantic
python version: 3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1 (tags/RELEASE_401/final)]
platform: Darwin-18.7.0-x86_64-i386-64bit
optional deps. installed: ['typing-extensions', 'email-validator']
```
times as the following with pydantic and marshmallow being comparable
```
%timeit marsh(models)
117 ms ± 3.01 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

%timeit pyd(models)
109 ms ± 1.34 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
and inside a conda virtual environment running Python 3.8.5
```
python -c "import pydantic.utils; print(pydantic.utils.version_info())"
pydantic version: 1.6.1
pydantic compiled: True
install path: /Users/Brian/anaconda3/envs/cthreepo/lib/python3.8/site-packages/pydantic
python version: 3.8.5 | packaged by conda-forge | (default, Aug 29 2020, 01:18:42)  [Clang 10.0.1 ]
platform: macOS-10.14.6-x86_64-i386-64bit
optional deps. installed: ['typing-extensions', 'email-validator']
```
times as, with pydantic being slower than marshmallow 
```
%timeit marsh(models)
500 ms ± 170 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

%timeit pyd(models)
823 ms ± 21.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Perhaps it's the c-compiler used in the virtual env?

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
