### ISSUE TITLE
Is there a way to have a field be a representation of two fields

### ISSUE THREAD

**Issue by bb-rrogers** [samuelcolvin/pydantic#1928]
What I am trying to do here is have two fields make up a third field like so:
```
class Person(BaseModel):
    first_name: str
    last_name: str
    full_name: str = first_name + last_name
```

From what I can tell this isn't possible? but hoping someone has come up with a solution, that allows it to be done during object instantiation.

**Comment by StephenBrown2** [comment]
You can do it pretty easily with a validator, though you will need to use the `always` flag to ensure it runs when the value isn't provided:
```python
In [1]: from pydantic import BaseModel, validator
   ...:
   ...: class Person(BaseModel):
   ...:     first_name: str
   ...:     last_name: str
   ...:     full_name: str = None
   ...:
   ...:     @validator("full_name", always=True)
   ...:     def composite_name(cls, v, values, **kwargs):
   ...:         return " ".join([values['first_name'], values['last_name']])
   ...:
In [2]: Person(first_name="Robert", last_name="Rogers")
Out[2]: Person(first_name='Robert', last_name='Rogers', full_name='Robert Rogers')
```

See: https://pydantic-docs.helpmanual.io/usage/validators/#validate-always

**Comment by PrettyWood** [comment]
Hello @bb-rrogers 
Some day we may have a `@computed_field` decorator (see https://github.com/samuelcolvin/pydantic/issues/935#issuecomment-555036039).
In the meantime @StephenBrown2's solution is the way to go!

**Comment by bb-rrogers** [comment]
Thank you both. Apologies if I had formulated my question incorrectly or missed checkboxes. I appreciate the quick response given.

I will close this, and will track the comment regarding the computed_field validator.
