### ISSUE TITLE
Incorrect conversion for Union fields

### ISSUE THREAD

**Issue by ods** [samuelcolvin/pydantic#1930]
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: .venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.3 (default, Jun 18 2020, 17:01:13)  [Clang 11.0.3 (clang-1103.0.32.59)]
                     platform: macOS-10.15.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Fields declared as `Union` are converted to the first type listed in it and this causes loose of data:

```py
import pydantic
from typing import Union

@dataclass
class C:
    attr: Union[int, float]

print(C(1.23), type(C(1.23).attr))  # C(attr=1) <class 'int'>

class D(pydantic.BaseModel):
    attr: Union[int, float]

print(D(attr=1.23), type(D(attr=1.23).attr))  # attr=1 <class 'int'>
```

**Comment by PrettyWood** [comment]
Hello @ods 
Please follow the whole template as this issue has been discussed so many times (for example in #619 or #1423).
This is a known issue that will probably be fixed in v2.

**Comment by ods** [comment]
> Please follow the whole template as this issue has been discussed so many times (for example in #619 or #1423).

Sure, I've searched through open bug before reporting. As you can see the titles of none of your examples can be easily correlated with reported problem. So you have a good chance to continue enlarging your collection of duplicates.

**Comment by PrettyWood** [comment]
@ods There are many issues with 'Union' for example https://github.com/samuelcolvin/pydantic/issues/1887, https://github.com/samuelcolvin/pydantic/issues/1805, https://github.com/samuelcolvin/pydantic/issues/1599...
But indeed if you searched only through open bugs I understand. We should rename one of those issues to avoid this situation thanks!
