### ISSUE TITLE
Use subclasses of Abstract Base Class model for validation?

### ISSUE THREAD

**Issue by niloch** [samuelcolvin/pydantic#1932]
Is there a good way to get pydantic to validate against the subclasses of an Abstract Base Class? This seems related to the discriminated union type described in #619. I have a libary where users may create custom subclasses of a pydantic model that conform to an interface and then use them as attributes in other pydantic models. Similar to the following example:

# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```sh
pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /Users/csullivan/.local/share/virtualenvs/colin_net-CG-pir0f/lib/python3.7/site-packages/pydantic
               python version: 3.7.3 (default, Apr 24 2020, 18:51:23)  [Clang 11.0.3 (clang-1103.0.32.62)]
                     platform: Darwin-19.6.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
from pydantic import BaseModel
from abc import ABC, abstractmethod
from typing import List


class Pet(BaseModel, ABC):
    name: str
    age: int = 2

    class Config:
        extra = "allow"

    @abstractmethod
    def get_relative_age(self) -> int:
        raise NotImplementedError


class Dog(Pet):

    name: str = "Fido"
    food: str = "kibble"

    def get_relative_age(self) -> int:
        return self.age * 7


class Cat(Pet):

    name: str = "Fluffy"
    collar_color: str = "Red"

    def get_relative_age(self) -> int:
        return self.age * 4


class Owner(BaseModel):
    pets: List[Pet]


cat = Cat()
dog = Dog()

orig_owner = Owner(pets=[dog, cat])

print(repr(orig_owner))

new_owner = Owner(**orig_owner.dict())

print(repr(new_owner))

```
Output:
```
Owner(pets=[Dog(name='Fido', age=2, food='kibble'), Cat(name='Fluffy', age=2, collar_color='Red')])
Traceback (most recent call last):
  File "test.py", line 47, in <module>
    new_owner = Owner(**orig_owner.dict())
  File "pydantic/main.py", line 346, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Owner
pets -> 0
  Can't instantiate abstract class Pet with abstract methods get_relative_age (type=type_error)
pets -> 1
  Can't instantiate abstract class Pet with abstract methods get_relative_age (type=type_error)
```

**Comment by shyamd** [comment]
The issue here is that `dict` actually serializes all the fields:
`orig_owner.dict()`
Output:
`{'pets': [{'name': 'Fido', 'age': 2, 'food': 'kibble'},
  {'name': 'Fluffy', 'age': 2, 'collar_color': 'Red'}]}`

You need some way of storing the subclass info and deserializing it back to an object. That is not in pydantic as of now.

**Comment by niloch** [comment]
Yup.

If I change Owner to
```python
class Owner(BaseModel):
    pets: List[Union[Cat, Dog]]
```
Then it works.  The problem is that I can't specify all the possible types in the Union, because the users will be implementing their own.

I've been stewing on how to leverage a subclass registry created from `__init_subclass__`

```python
subclass_registry = {}

class ModifiedBaseModel(BaseModel):
    def __init_subclass__(cls, is_abstract: bool = False, **kwargs: Any) -> None:
        super().__init_subclass__(**kwargs)  # type: ignore
        if not is_abstract:
            subclass_registry[cls.__name__] = cls


class Pet(ModifiedBaseModel, ABC, is_abstract=True):
    name: str
    age: int = 2

    class Config:
        extra = "allow"

    @abstractmethod
    def get_relative_age(self) -> int:
        raise NotImplementedError


class Dog(Pet):

    name: str = "Fido"
    food: str = "kibble"

    def get_relative_age(self) -> int:
        return self.age * 7


class Cat(Pet):

    name: str = "Fluffy"
    collar_color: str = "Red"

    def get_relative_age(self) -> int:
        return self.age * 4


class Owner(ModifiedBaseModel):
    pets: List[Pet]
```

With this implementation, the `subclass_registry` contains references all the subclasses to attempt to  validate against.  I still need to workout how to override `BaseModel.__init__` or `validate_model` method to use the subclass registry properly

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).

**Comment by berzi** [comment]
If there has been further discussion on this topic, could it be linked to here, please?

**Comment by simberaj** [comment]
I ended up using the solution from <https://github.com/pydantic/pydantic/discussions/3091>
