### ISSUE TITLE
Dynamically adding fields inplace to an existing model classes?

### ISSUE THREAD

**Issue by mcgfeller** [samuelcolvin/pydantic#1937]
Hi, is there a way to dynamically add a field to a model class? 

I'm creating some models using [Dynamic Model Creation](https://pydantic-docs.helpmanual.io/usage/models/#dynamic-model-creation). As I'm using a pluggable architecture, I would like to add further fields to these model classes after their creation (but before instances have been created)?

Is this possible? I'm looking for something like `model.add_fields(foo=(str, ...), bar=123)`, i.e. a class method with similar arguments the `**field_definitions` arguments of `create_model()`.

It needs to be "in-place", i.e., not creating a new model class, as the model class is already embedded in other model classes. 

Thank you and best regards,
Martin

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: C:\Program Files\Python38\Lib\site-packages\pydantic
               python version: 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.18362
     optional deps. installed: ['typing-extensions', 'email-validator']
```

**Comment by PrettyWood** [comment]
Hello @mcgfeller!
I think you already answered your own question ;) I would go with something like this

```python
from pydantic import BaseModel as PydanticBaseModel, create_model

class BaseModel(PydanticBaseModel):
    @classmethod
    def with_fields(cls, **field_definitions):
        return create_model('ModelWithFields', __base__=cls, **field_definitions)
```
With a model like
```python
class Model(BaseModel):
    foo: str
    bar: int = 123
```
you could simply create a new one
```python
NewModel = Model.with_fields(baz=(int, ...))
NewModel(foo='awe')

pydantic.error_wrappers.ValidationError: 1 validation error for ModelWithFields
baz
  field required (type=value_error.missing)
```

**Comment by mcgfeller** [comment]
I got it working with this snippet, adding a new `field_type` with `field_name` and `field_default` to an existing_model:

```
existing_model.__fields__[field_name] = pydantic.fields.ModelField(name=field_name,type_=typing.Optional[field_type,required=False,
    default=field_default,class_validators=None,model_config=pydantic.BaseConfig)
existing_model.__schema_cache__.clear()
```
However, I think this is using internal stuff and is not a proper way.

**Comment by PrettyWood** [comment]
Ah sorry I didn't see the **inplace** mention, which is why you're playing with `__fields__` I reckon.
If so I would probably use `ModelField.infer` like this:
```python
from typing import Any, Dict, Optional

from pydantic import BaseModel
from pydantic.fields import ModelField


class Model(BaseModel):
    foo: str

    @classmethod
    def add_fields(cls, **field_definitions: Any):
        new_fields: Dict[str, ModelField] = {}
        new_annotations: Dict[str, Optional[type]] = {}

        for f_name, f_def in field_definitions.items():
            if isinstance(f_def, tuple):
                try:
                    f_annotation, f_value = f_def
                except ValueError as e:
                    raise Exception(
                        'field definitions should either be a tuple of (<type>, <default>) or just a '
                        'default value, unfortunately this means tuples as '
                        'default values are not allowed'
                    ) from e
            else:
                f_annotation, f_value = None, f_def

            if f_annotation:
                new_annotations[f_name] = f_annotation

            new_fields[f_name] = ModelField.infer(name=f_name, value=f_value, annotation=f_annotation, class_validators=None, config=cls.__config__)

        cls.__fields__.update(new_fields)
        cls.__annotations__.update(new_annotations)


m = Model(foo='qwe')

Model.add_fields(bar=(str, ...), baz='qwe')

m = Model(foo='qwe')

# pydantic.error_wrappers.ValidationError: 1 validation error for Model
# bar
#   field required (type=value_error.missing)
```

Note that I copied the part about annotations but it's not really complete and can be removed.
Hope it helps!

**Comment by mcgfeller** [comment]
Thank you very much @PrettyWood! This works fine. I've added "inplace" to the title, in case others search for the solution.

By the way, this is very hard to do in Marshmallow - inplace seems impossible without accessing internals. 

Thanks again!

**Comment by tstorek** [comment]
@PrettyWood Does this one have a chance to get included into the BaseModel?

**Comment by samuelcolvin** [comment]
no, because it would break static typing consistency.

You'd probably be better off using `create_model()`

**Comment by tstorek** [comment]
@samuelcolvin Ok. I Understand. 'create_model()' works for me. But is there a way to add at least extra attrs if needed? I cannot allow exactly the structure how extra are generated

**Comment by jakubczaplicki** [comment]
For those who find this issue a year later, nowadays you can simply do: 
```
from pydantic import BaseModel, BaseConfig


class FooBarBaz(BaseModel):
    foo: Optional[str]

    class Config(BaseConfig):
        extra = "allow"


details = {"bar": 1}

FooBarBaz(**details)
> FooBarBaz(foo=None, bar=1)

FooBarBaz(foo=None, bar=1).dict(exclude_none=True)
> {'bar': 1}
```

**Comment by andrewshvv** [comment]
Maybe that might work?
```
from pprint import pprint

from pydantic import Field

from common.validation import BaseModel


class SomeValueMixin:
    some_value: int = Field()


class AnotherValueMixin:
    another_value: str = Field()


def add_fields_dynamically(*mixin_cls):
    return type(f"DynamicModel[{','.join([c.__name__ for c in mixin_cls])}]", (BaseModel, *mixin_cls), {})


DynamicModel = add_fields_dynamically(
    SomeValueMixin,
    AnotherValueMixin
)

instance = DynamicModel(**{'some_value': 1, 'another_value': 'hehe haha'})
pprint(instance.model_dump())

```

**Comment by tonycosentini** [comment]
I was using @PrettyWood's example above to test out some scenarios with pickling when new fields are added in a new release.

Here's what I ended up with to make that work in Pydantic 2:
```python3
    # Source: https://github.com/pydantic/pydantic/issues/1937#issuecomment-695313040
    @classmethod
    def add_fields(cls, **field_definitions: Any):
        new_fields: Dict[str, FieldInfo] = {}
        new_annotations: Dict[str, Optional[type]] = {}

        for f_name, f_def in field_definitions.items():
            if isinstance(f_def, tuple):
                try:
                    f_annotation, f_value = f_def
                except ValueError as e:
                    raise Exception(
                        'field definitions should either be a tuple of (<type>, <default>) or just a '
                        'default value, unfortunately this means tuples as '
                        'default values are not allowed'
                    ) from e
            else:
                f_annotation, f_value = None, f_def

            if f_annotation:
                new_annotations[f_name] = f_annotation

            new_fields[f_name] = FieldInfo(annotation=f_annotation)

        cls.model_fields.update(new_fields)
        cls.model_rebuild(force=True)
```

**Comment by mattdst1** [comment]
> ```python
> ModelField
> ```

How does this work in new version of pydantic? ModelField doesn't exist in the quoted package anymore

**Comment by sukiluvcode** [comment]
> I was using @PrettyWood's example above to test out some scenarios with pickling when new fields are added in a new release.
> 
> Here's what I ended up with to make that work in Pydantic 2:
> 
> ```python
>     # Source: https://github.com/pydantic/pydantic/issues/1937#issuecomment-695313040
>     @classmethod
>     def add_fields(cls, **field_definitions: Any):
>         new_fields: Dict[str, FieldInfo] = {}
>         new_annotations: Dict[str, Optional[type]] = {}
> 
>         for f_name, f_def in field_definitions.items():
>             if isinstance(f_def, tuple):
>                 try:
>                     f_annotation, f_value = f_def
>                 except ValueError as e:
>                     raise Exception(
>                         'field definitions should either be a tuple of (<type>, <default>) or just a '
>                         'default value, unfortunately this means tuples as '
>                         'default values are not allowed'
>                     ) from e
>             else:
>                 f_annotation, f_value = None, f_def
> 
>             if f_annotation:
>                 new_annotations[f_name] = f_annotation
> 
>             new_fields[f_name] = FieldInfo(annotation=f_annotation)
> 
>         cls.model_fields.update(new_fields)
>         cls.model_rebuild(force=True)
> ```
Great, I am just looking for the updated version of the implementation. btw, it's better to keep the default value in the passed field definitions.
``` new_fields[f_name] = FieldInfo(annotation=f_annotation, default=f_value) ```
