### ISSUE TITLE
ValidationErrors are not helpful in logs

### ISSUE THREAD

**Issue by JosXa** [samuelcolvin/pydantic#1938]
I noticed that validation errors that happen in production can yield quite unhelpful exception messages. Maybe I am just missing some configuration and this is already built in, if so please let me know! What I'm referring to is that for instance in an `Enum` type, the `ValidationError` only says something along the lines of `value is not a valid enumeration member; permitted: 'first-value', 'second-value' (type=type_error.enum; enum_values=[<MyEnumType.first_value: 'first-value'>, <MyEnumType.second_value: 'second-value'>])`, but doesn't actually tell you what has been the offending value... If you're not logging the object to be parsed, you're now out of luck because you have no way of knowing how to fix it going forward.

I'm wondering if this is a concious design decision and, as I said, I'm hopeful that there's a simple knob I can turn to know what exactly breaks my models. 
Here's an example stack trace:

```
    Traceback (most recent call last):
      File "C:\projects\josxabot\app\modules\todoist_module\__init__.py", line 65, in route_received_event
        parsed = Model.parse_raw(item.content)
      File "pydantic\main.py", line 478, in pydantic.main.BaseModel.parse_raw
      File "pydantic\main.py", line 455, in pydantic.main.BaseModel.parse_obj
      File "pydantic\main.py", line 346, in pydantic.main.BaseModel.__init__
    pydantic.error_wrappers.ValidationError: 1 validation error for Model
    __root__ -> 0 -> event
      value is not a valid enumeration member; permitted: 'item:completed', 'item:added' (type=type_error.enum; enum_values=[<EventType.completed: 'item:completed'>, <EventType.added: 'item:added'>])
```

and the corresponding model:

```
class EventType(Enum):
    completed = "item:completed"
    added = "item:added"
```

Through some experimentation I then found out I was missing an item `uncompleted = "item:uncompleted"`, but from the production stack trace I had no way of knowing that. I'd argue the message should say `value 'item:uncompleted' is not a valid enumeration member; ...`

**Comment by PrettyWood** [comment]
Hello @JosXa 
Please follow the template for issues.
I reckon this issue https://github.com/samuelcolvin/pydantic/issues/784 is related. Do you agree?
If yes, please add your feedback on this issue, which will be the reference for the feature.

**Comment by JosXa** [comment]
Thanks, closing as duplicate.

**Comment by VianneyMI** [comment]
I am willing to help ! Just need a bit of guidance there @PrettyWood
