### ISSUE TITLE
Please consider adding OmegaConf to the benchmarked optioned

### ISSUE THREAD

**Issue by maximveksler** [samuelcolvin/pydantic#1939]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this feature/change is needed
* [ ] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Feature Request

[OmegaConf](https://github.com/omry/omegaconf) supports schema validation in a somewhat similar way to pydantic, please consider setting up a benchmark to run against it as well.

**Comment by samuelcolvin** [comment]
Thanks for the question.

Every new library added to the benchmarks, adds workload to keep it up-to-date and correct.

The benchmarks were originally created to demonstrate that pydantic was on a par with, or more performant than other libraries. It therefore only included libraries that were more popular than pydantic (by github stars and download numbers primarily).

I've subsequently refused to add a number of other libraries that are less popular than pydantic. #1525 #814

OmegaConf has many few stars (273 vs. 4.2k) and many fewer downloads ([65k/month](https://pypistats.org/packages/omegaconf) vs. 1.5m/month) compared to pydantic, therefore I'm afraid I would suggest we do not add it to the benchmarks.

**Comment by maximveksler** [comment]
This makes sense, however, please be advised that it's being developed by Facebook, and it the powerhouse behind [Hydra](https://hydra.cc) (also FB) which is getting lots of traction in the ML communities.

**Comment by omry** [comment]
@maximveksler, I am guessing that OmegaConf is slower than Pydantic for a few reasons:
1. It's doing more, the returned value is not a primitive dataclass object but a DictConfig which offers subsequent runtime safety and other features.
2. While performance is decent for most use case, it was never a top priority and I am sure it can be improved.

@samuelcolvin's comment is also on point: coding costs some time up front and a lot of time in the long run.
If you are interested in such a benchmark you are very welcome to create it in your own repo (or a fork of pydantic to get started faster), I for one would be happy to see the results - but I can understand @samuelcolvin reluctance to add more benchmarks to his repo.
