### ISSUE TITLE
ImportError: cannot import name 'AbstractSetIntStr' from 'pydantic.typing' (/home/backprop/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/pydantic/typing.cpython-38-x86_64-linux-gnu.so)

### ISSUE THREAD

**Issue by backpropogation** [samuelcolvin/pydantic#1946]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.6.1
pydantic compiled: True
 install path: /home/backprop/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/pydantic
python version: 3.8.2 (default, Jul 16 2020, 14:00:26)  [GCC 9.3.0]
platform: Linux-5.4.0-48-generic-x86_64-with-glibc2.29
optional deps. installed: []
...
```

```py
from pydantic.typing import AbstractSetIntStr
...
```
The result of running is `Traceback (most recent call last):
  File "...................", line 1, in <module>
    from pydantic.typing import AbstractSetIntStr
ImportError: cannot import name 'AbstractSetIntStr' from 'pydantic.typing' (/home/backprop/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/pydantic/typing.cpython-38-x86_64-linux-gnu.so)`

**Comment by PrettyWood** [comment]
Hello @backpropogation 
Why would you want to import this ? It's just there for `mypy`

**Comment by backpropogation** [comment]
> Hello @backpropogation
> Why would you want to import this ? It's just there for `mypy`

I have overrided `dict()` method of `BaseModel`, now I need type hint include and exclude args with default types of pydantic

**Comment by PrettyWood** [comment]
Just write
```python
AbstractSetIntStr = AbstractSet[Union[int, str]]
```
