### ISSUE TITLE
Model.json() ignores json_encoder when the type is IntEnum

### ISSUE THREAD

**Issue by me-ransh** [samuelcolvin/pydantic#1947]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
 python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /homes/<redacted>/.conda/envs/py37-tmp/lib/python3.7/site-packages/pydantic
               python version: 3.7.7 (default, Mar 26 2020, 15:48:22)  [GCC 7.3.0]
                     platform: Linux-4.9.0-0.bpo.6-amd64-x86_64-with-debian-8.11
     optional deps. installed: ['typing-extensions']
```

Hi,

I recently started using pydantic and I'm loving it, but there seems to be an issue with customizing how `IntEnum` classes are serialized to json.
Below is a minimal example showing the issue:

```py
from enum import IntEnum
from pydantic import BaseModel

class Foo(IntEnum):
    FIRST = 0
    SECOND = 1
    
    def encode(self):
        return self.name
    
    @classmethod
    def __get_validators__(cls):
        yield cls.decode
    
    @classmethod
    def decode(cls, val):
        if isinstance(val, str):
            return cls[val]
        else:
            return cls(val)

class Bar(BaseModel):
    f: Foo
        
    class Config:
        json_encoders = {
            Foo: Foo.encode,
            # i also tried: Foo: lambda x: x.name
        }
        
b = Bar(f=1)
print(Bar.__json_encoder__)
#> functools.partial(<cyfunction custom_pydantic_encoder at 0x7fffc4d94d50>, {<enum 'Foo'>: <function Foo.encode at 0x7fffc4b4e830>})
print(b)
#> f=<Foo.SECOND: 1>
print(b.json())
#> {"f": 1}
print(b.f.encode())
#> SECOND
print(Foo.__mro__)
#> (<enum 'Foo'>, <enum 'IntEnum'>, <class 'int'>, <enum 'Enum'>, <class 'object'>)
```

At first I thought the `custom_pydantic_encoder` interpreted the class as an int, but that's not the case, as the above `__mro__` shows. The custom encoder isn't even used! I think that `json.dumps()` uses the custom encoder only on non-primitive types, but I might be wrong.
Also, this doesn't occur when changing `IntEnum` to `Enum` (obviously).

How should I work around it? Is this something you'd consider fixing?

Thanks in advance!

**Comment by PrettyWood** [comment]
Hello @me-ransh 
The issue is that when you use `json_encoders`, it is injected as default param for [`JSONEncoder`](https://docs.python.org/3/library/json.html#json.JSONEncoder) used by `json.dumps`

```python
from enum import IntEnum
import json


class Foo(IntEnum):
    FIRST = 0
    SECOND = 1

def encoder(x):
    if isinstance(x, Foo):
        print('trigger')

print(json.dumps({'f': Foo.SECOND}, default=encoder))

# {"f": 1}
```

As you can see, the `encoder` function is never called because it is directly understood by `json.dumps` and doesn't need a fallback for this. You could try to use a custom json encoder and use it like this

```python
class Bar(BaseModel):
    f: Foo

    class Config:
        json_dumps = partial(json.dumps, cls=CustomEncoder)
```

Can't really help more as it's out of *pydantic* scope here :/ 
Hope it helps !

**Comment by PrettyWood** [comment]
Yes it's normal and as I told you you should have a look on `json` side.

```python
from enum import Enum
import json

class Foo(Enum):
    FIRST = 0
    SECOND = 1

def encoder(o):
    if isinstance(o, Foo):
        return o.name
    raise TypeError

print(json.dumps({ 'test': Foo.SECOND }, default=encoder))
# > {"test": "SECOND"}
print(json.dumps({ Foo.SECOND: 'test' }, default=encoder))
# TypeError: keys must be str, int, float, bool or None, not Foo
```

Try to make it work on `json` side and then you'll be able to just plug it in *pydantic* with `json_encoders` if you want the kwarg `default` of `json.dumps` (but I think it won't work) or directly overwrite `Config.json_dumps`, which will replace the `cls` kwarg of `json.dumps`

**Comment by me-ransh** [comment]
Sorry for the ignorance. I'm not used to working with json.
Thank you for your patience.
I'm closing.
