### ISSUE TITLE
Guidance on custom dual type

### ISSUE THREAD

**Issue by Subaku** [samuelcolvin/pydantic#1949]
Hello all,

I've managed to get a working custom type working but there's aspects that could use improvement. Typing in python is new to me so any guidance is greatly appreciated! Here's the goal. A DualType that takes a string and returns a tuple. The tuple will have two values of potentially different types. These values are parsed from the string which are delimited with a character (default ',').

Here's what it looks like to use currently.
```python
class MyModel(BaseModel):
    dual: DualValue[int, bool]

m = Model(dual='1,True')
print(type(m.dual[0]))
print(type(m.dual[1]))
```

```bash
>>> <class 'int'>
>>> <class 'bool'>
```

Here's how I implemented `DualValue`.

```python
DEFAULT_SEP = ','


FirstType = TypeVar('FirstType')
SecondType = TypeVar('SecondType')


class DualValue(Generic[FirstType, SecondType]):
    separator: str = DEFAULT_SEP

    @classmethod
    def __get_validators__(cls):
        yield str_validator
        yield cls.split_validator
        yield cls.validate_types
        
    def __getitem__(self, key: int):
        # This is just to satisfy IDE complaining about the type not having this capability.
        # Don't know enough yet about typing to know how to solve this differently.
        return super().__getitem__(key)
    
    @classmethod
    def split_validator(cls, v) -> tuple:
        if cls.separator not in v:
            raise ValueError("'{}' is not present.".format(cls.separator))
        return tuple(v.split(cls.separator))

    @classmethod
    def validate_types(cls, v, field: ModelField) -> tuple:
        if len(field.sub_fields) != 2:
            raise TypeError('Missing one or more sub_fields.')
        first_field = field.sub_fields[0]
        second_field = field.sub_fields[1]

        first_value, first_error = first_field.validate(v[0], {}, loc='First Value')
        second_value, second_error = second_field.validate(v[1], {}, loc='Second Value')

        errors = []
        if first_error:
            errors.append(first_error)
        if second_error:
            errors.append(second_error)
        if errors:
            raise ValidationError(errors, cls)
        
        return first_value, second_value
```

Functionally this works but here's some gaps I don't know how to deal with.
1. Besides inheritance how might I override the separator?
2. I couldn't get the type of `DualValue` to be a `tuple` hence `__getitem__`. Any way to annotate the class?

I'm sure my naive approach has other gaps not mentioned.

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
