### ISSUE TITLE
A pre-commit hook for exporting models to json schemas

### ISSUE THREAD

**Issue by aorumbayev** [samuelcolvin/pydantic#1950]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question

Recently wrote a very simply pre-commit hook that takes models from input directory and dumps json schemas to output directory. Feel like users in this community might find this useful -> https://github.com/aorumbayev/pydantic-to-schema. 
Was wondering if there is a third party integrations section in docs or something similar to that where I can list this pre-commit hook ?

**Comment by aorumbayev** [comment]
@samuelcolvin any opinion on this?

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
