### ISSUE TITLE
support make_dataclass for pydantic.dataclasses

### ISSUE THREAD

**Issue by Dothion** [samuelcolvin/pydantic#1954]
It would be better if `pydantic.dataclasses` support `make_dataclass` function, which is similar to `dataclasses.make_dataclass` or `pydantic.create_model`. 

Here is an example from dataclasses document:
```
C = make_dataclass('C',
                   [('x', int),
                     'y',
                    ('z', int, field(default=5))],
                   namespace={'add_one': lambda self: self.x + 1})
```
which is equivalent to
```
@dataclass
class C:
    x: int
    y: 'typing.Any'
    z: int = 5

    def add_one(self):
        return self.x + 1
```

**Comment by PrettyWood** [comment]
Hi @Dothion 

We could copy paste the `dataclasses.make_dataclass` method in `pydantic.dataclasses` code and it would work.
But with #1817, you could just create your regular `dataclass` with `make_dataclass` and convert it to `pydantic.dataclass`.
I think it would be easier. WDYT?

**Comment by Dothion** [comment]
@PrettyWood:

This works for me. Thanks a lot!
