### ISSUE TITLE
Nested Config class causes nuisance type errors in Pyright when subclassing models

### ISSUE THREAD

**Issue by layday** [samuelcolvin/pydantic#1958]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /Users/.../.py-venvs/3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Sep 10 2020, 08:51:33)  [Clang 7.1.0 (tags/RELEASE_710/final)]
                     platform: macOS-10.14.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

When Pydantic is used in conjunction with Pyright, and when subclassing models which define a `Config` class, Pyright reports errors in the form of:

```
"Config" overrides symbol of same name in class "Foo"
  "Type[Config]" is incompatible with "Type[Config]"
  Type "Type[Config]" cannot be assigned to type "Type[Config]"
```

... where:

```py
from pydantic import BaseModel

class Foo(BaseModel):
    class Config:
        ...

class Bar(Foo):
    class Config:
        ...
```

Pyright is technically correct here - `Bar.Config` does not derive from `Foo.Config` so it cannot be used in its place - this would be like having a variable `foo` of type `str` on the parent class and attempting to redefine it as an `int` on the subclass.  There are several ways to work around this, like applying a `# type: ignore` comment or by assigning `Config` to a temporary name, e.g.  `_Config`, and then re-assigning it to `Config` with type `Any`, but none of them are particularly elegant.  `Config` also poses another issue in that Pyright cannot type check it even when it does not violate its supertype nor offer completion suggestions, etc.  I wonder if there is some other way to define configuration that would be more in keeping with static typing in Python or if an alternative would be considered.

**Comment by pikeas** [comment]
This happens even without nesting, from the user's perspective:

```
class Settings(BaseSettings):
    foo: str

    class Config:
        allow_mutation = False
```

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
