### ISSUE TITLE
how to have a model which is just a primitive plus validation?

### ISSUE THREAD

**Issue by mdavis-xyz** [samuelcolvin/pydantic#1973]
### Checks

* [x] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question

I have many pydantic models. Some of them include the same field, that I want validated in the same way. This field is a string. I want to validate that the string is always a certain length.

Because I want to refer to this field in multiple places, I want to factor out this validation into one standalone class. (e.g. so I only have to define the minimum length once.)

Pydantic models seem to be good for validating a dictionary of ints, or a list of strings. But what if all I want is for my model to be *just* a string?

```
from pydantic import BaseModel, ValidationError, validator, root_validator
from typing import List, Optional, Dict, Union
from collections import UserString

class SiteId(BaseModel):
    id: str

    @validator('id')
    def id_min_length(cls, id):
        if len(id) < 3:
            raise ValueError('must be at least 3 chars long')
        return id

class Site(BaseModel):
    id: SiteId

class SomethingElse(BaseModel):
    site_id: SiteId

if __name__ == '__main__':
  Site(id='ab3')
  try:
      Site(id='a')
  except ValidationError as e:
      pass
  SomethingElse(site_id='ab3')
  try:
      SomethingElse(site_id='a')
  except ValidationError as e:
      pass
```

This script currently throws an error:

```
Traceback (most recent call last):
  File "pydantic_str.py", line 26, in <module>
    Site(id='ab3')
  File "pydantic/main.py", line 346, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Site
id
  value is not a valid dict (type=type_error.dict)
```

Because Pydantic is expecting a dictionary for `SiteId`, but it should just be a string.

## Possible Approaches

e.g. can I make `SiteId` a sub-class `str` itself, or `collections.UserString`?

Or should I override `parse_raw`, `dict` etc to return/take in just a string, instead of `{'id': x}`?

## Use cases

I have a few use cases. e.g.

* I have many sites I'm controlling with my python code. They are identified with certain IDs, in a certain 4 letter format. Many different models need to contain site ID info
* Each site has an electricity meter number, which is a string in a certain format. (Similar to UUID, or ISBN) Many different API calls in my Flask server need to receive or return objects which contain these meter numbers

## Version Info

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
 pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /home/ec2-user/.local/lib/python3.6/site-packages/pydantic
               python version: 3.6.12 (default, Aug 31 2020, 18:56:18)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
                     platform: Linux-4.14.193-113.317.amzn1.x86_64-x86_64-with-glibc2.3.4
     optional deps. installed: []
```

**Comment by PrettyWood** [comment]
Hello @mdavis-xyz 
Why do you want to create a `BaseModel` for only one field. I feel like you just want a custom class with validation
Here you could actually directly use `constr` like this

```python
from pydantic import BaseModel, constr

SiteId = constr(min_length=3)


class Site(BaseModel):
    id: SiteId


class SomethingElse(BaseModel):
    site_id: SiteId
```

If you want to add extra rules, you can simply define you [own custom class](https://pydantic-docs.helpmanual.io/usage/types/#custom-data-types)

**Comment by mdavis-xyz** [comment]
Ah yes, that looks like what I want.

Yes, using something other than `BaseModel` is the solution. I just didn't know what to use.

**Comment by mdavis-xyz** [comment]
One more quick question @PrettyWood,

what if I want to instantiate `SiteId` directly?

(In my application I want to be able to answer site calls about "what's the list of all site ids?", as well as "here's an update for one particular site which includes the ID and a bunch of other stuff." So I need both models that include `SiteId`, and variables which are just a `SiteId`.)

It has no `.parse_obj` method. Calling the following does *not* result in a `ValidationError` being thrown.

```
from pydantic import BaseModel, constr
SiteId = constr(min_length=3)
SiteId('a') # less than min length
```

Similarly `SiteId.validate('a')` doesn't throw a `ValidationError`.

I tried subclassing `pydantic.ConstrainedStr` directly but I get the same result.

**Comment by mdavis-xyz** [comment]
One more quick question @PrettyWood,

what if I want to instantiate `SiteId` directly?

(In my application I want to be able to answer site calls about "what's the list of all site ids?", as well as "here's an update for one particular site which includes the ID and a bunch of other stuff." So I need both models that include `SiteId`, and variables which are just a `SiteId`.)

It has no `.parse_obj` method. Calling the following does *not* result in a `ValidationError` being thrown.

```
from pydantic import BaseModel, constr
SiteId = constr(min_length=3)
SiteId('a') # less than min length
```

Similarly `SiteId.validate('a')` doesn't throw a `ValidationError`.

I tried subclassing `pydantic.ConstrainedStr` directly but I get the same result.

**Comment by PrettyWood** [comment]
```python
from pydantic.tools import parse_obj_as

parse_obj_as(SiteId, 'qwe')

# pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[ConstrainedStrValue]
# __root__
#   ensure this value has at least 3 characters (type=value_error.any_str.min_length; limit_value=3)
```

Basically `parse_obj_as` will generate a fake model
```python
class Model(BaseModel):
  __root__: SiteId
```
and instantiate it with `Model(__root__='qwe')` to validate the value

Hope it helps
