### ISSUE TITLE
Add NonNegativeFloat, NonPositiveFloat etc

### ISSUE THREAD

**Issue by mdavis-xyz** [samuelcolvin/pydantic#1975]
### Checks

* [y] I added a descriptive title to this issue
* [y] I have searched (google, github) for similar issues and couldn't find anything
* [y] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this feature/change is needed
* [y] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

I'll write this PR myself. Just checking here in case anyone else has feedback.

# Feature Request

Pydantic already has types `PositiveFloat`, `NegativeFloat`, `PositiveInt`, `NegativeInt`.
These values all exclude zero.

I want to have a class that allows all positive numbers, including zero.

# Proposed Solution

After eyeballing [types.py](https://github.com/samuelcolvin/pydantic/blob/e985857e5a9ede8d346b010a5a039aa84a089826/pydantic/types.py#L429) I think we should have:

```

class NonPositiveFloat(ConstrainedFloat):
    le = 0


class NonNegativeFloat(ConstrainedFloat):
    ge = 0


class NonPositiveInt(ConstrainedInt):
    le = 0


class NonNegativeInt(ConstrainedInt):
    ge = 0

```

Yes I know the end user can do that. This just seems like the kind of thing that's probably quite common, so would be nice out of the box.

One thing I'm not sure about is the capitalisation. `NonPositiveInt` or `NonpositiveInt`?

**Comment by mdavis-xyz** [comment]
Which tests, docs etc do I need to update when I add this class?

* pydantic/docs/examples/types_constrained.py
* pydantic/tests/test_types.py
* pydantic/tests/test_schema.py
* pydantic/docs/build/schema_mapping.py

Anything else?

**Comment by samuelcolvin** [comment]
I'm not sure this is necessary. Does anyone else need this?

If the issue gets sufficient 👍 s (e.g. 5 let's say), I'll accept it.

**Comment by samuelcolvin** [comment]
You can always use `conint()` or `confloat()` or define your own types, this doesn't have to be included in pydantic.

**Comment by mdavis-xyz** [comment]
I'm struggling to think of a use case where `PositiveInt`, `PositiveFloat` etc are useful. Surely that's a more obscure use case that one including zero?

e.g. my data is all physical measurements. Durations, lengths, litres etc. All of those can be zero.
I'm using these values *a lot*, hence why I think it would be nice to put them in the library itself.

**Comment by PrettyWood** [comment]
It's been closed because it was released ;)

**Comment by kasperschnack** [comment]
Oh, nice! Thx for clarifying that 🙏
