### ISSUE TITLE
Coverage is broken due to a problem with codecov

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#1979]
Codecov is somehow considering coverage from the windows builds (I assume) as a completely different code base and therefore showing lines not covered in windows as misses, screenshot from codecov:

<img width="1154" alt="Screenshot 2020-10-09 at 10 10 24" src="https://user-images.githubusercontent.com/4039449/95565315-e8220000-0a17-11eb-944c-6511bb666300.png">

It's showing a second root direct `D:/a/pydantic/pydantic/pydantic` as well as `pydantic`.

I guess this could be a problem with github actions somehow, but either way it's really annoying.

Looking through the commit history, it seems to have happened fairly recently without us doing anything to cause the problem.

Any suggestions on a fix would be great.

**Comment by samuelcolvin** [comment]
example of the problem #1976, but this is also effecting master.

**Comment by samuelcolvin** [comment]
Issue on the codecov community forum [here](https://community.codecov.io/t/bug-project-path-prefix-of-codecov-action-running-on-windows-is-incorrectly-kept-in-report-data/2141/2).

**Comment by PrettyWood** [comment]
Seems like it is indeed solved! (back to 100% coverage on recent PRs)
