### ISSUE TITLE
AnyUrl doesn't accept file URLs with implicit host

### ISSUE THREAD

**Issue by torfsen** [samuelcolvin/pydantic#1983]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /shared/conda/envs/ubide-mastr/lib/python3.6/site-packages/pydantic
               python version: 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)  [GCC 7.3.0]
                     platform: Linux-5.4.0-48-generic-x86_64-with-debian-buster-sid
     optional deps. installed: []
```
```py
import pydantic

class MyModel(pydantic.BaseModel):
    url: pydantic.AnyUrl

MyModel(url='file:///foo/bar')
```
raises:
```
ValidationError: 1 validation error for MyModel
url
  URL host invalid (type=value_error.url.host)
```
However, `MyModel(url='file://hostname/foo/bar')`, i.e. a URL with an explicit hostname, works.

RFC 8089 [says](https://tools.ietf.org/html/rfc8089#section-2) that the hostname is optional. Hence I would expect that `AnyUrl` would accept that.

**Comment by samuelcolvin** [comment]
I guess we could add `host_required` like `user_required`, then make it true for most of the descendant types.

**Comment by harshach** [comment]
anyurl doesn't work for JDBC connection URL either "jdbc:mysql://localhost/test" invalid or missing URL scheme (type=value_error.url.scheme)

**Comment by dharmveer18** [comment]
I have made Optional[HttpUrl] = None, still not working
