### ISSUE TITLE
Is it possible to use Pydantic to coerce models to valid JSON models?

### ISSUE THREAD

**Issue by gidgid** [samuelcolvin/pydantic#1988]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [X] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /Users/gideon/.pyenv/versions/3.8.2/envs/test_env/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Mar 21 2020, 12:42:02)  [Clang 11.0.0 (clang-1100.0.33.17)]
                     platform: macOS-10.15.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

I was wondering if it's possible to coerce Pydantic models into valid JSONs? The following test doesn't pass but I would like to know if there's any equivalent code that achieves the same goal

```py
from typing import Set

import pytest
from pydantic import BaseModel, Json, validate_arguments


class Person(BaseModel):
    name: str
    scores: Set[int]


@validate_arguments
def convert(payload: Json):
    return payload


def test_coerces_inputs_to_valid_json():
    p1 = Person(name="John", scores={1, 3, 4, 3})
    converted = convert(p1)
    scores = dict(converted)["scores"]

    assert sorted(scores) == [1, 3, 4]

```

Note how the type coercion made `scores` a `List[int]` instead of a `Set[int]` so it could be used as a valid JSON

Why is this useful? I've got a piece of pymongo code that can only save valid JSONs and I want to avoid making explicit type conversions if it can be done using Pydantic

Thanks in advance 🙏

**Comment by PrettyWood** [comment]
Hello @gidgid 
Just change `converted = convert(p1)` into `converted = convert(p1.json())`.
Is it what you're looking for ?

**Comment by gidgid** [comment]
🤯 
I feel embarrassed asking it
Thanks @PrettyWood you're the best
