### ISSUE TITLE
How can I distinguish between iterable and iterator?

### ISSUE THREAD

**Issue by sasano8** [samuelcolvin/pydantic#1995]
# version
```
# Execution environment is google colaboratory
pydantic version: 1.6.1
pydantic compiled: True
install path: /usr/local/lib/python3.6/dist-packages/pydantic
python version: 3.6.9 (default, Jul 17 2020, 12:50:27)  [GCC 8.4.0]
platform: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
optional deps. installed: ['typing-extensions']
```

# Question
When I define an iterable field, the value I set will be interpreted as an iterator.
How can I distinguish between iterable and iterator?

## inspection result
1. set a list in an iterable field, a list will be converted to an iterator value.
2. Since the iterator is consumed, the  iterator cannot be performed twice.
3. Fields of type "typing.Iterator" are not supported.

The definition of iterable in docs.python implements either __iter__ or __getitem__.(Iterable does not have to implement __next__ method.)
Therefore, I feel that the definition of iterable between pydantic and typing is unmatched.

- [docs.python](https://docs.python.org/3.5/glossary.html#term-iterable)
- [# 1152](https://github.com/samuelcolvin/pydantic/pull/1152)

## code
```py
from pydantic import BaseModel
from typing import List, Iterable, Iterator

class MyIterable(BaseModel):
  iterable: Iterable[int] = None
  # ==========================
  # 3. Fields of type "typing.Iterator" are not supported.
  # ==========================
  # iterator: Iterator[int] = None

# ==========================
# 1. set a list in an iterable field, a list will be converted to an iterator value.
# ==========================
iterable = [1, 2, 3]
obj = MyIterable(iterable=iterable)
print(type(iterable))  # <class 'list'>
print(type(obj.iterable))  # <class 'list_iterator'>

print(isinstance(iterable, Iterable))  # True
print(isinstance(iterable, Iterator))  # False
print(isinstance(obj.iterable, Iterable))  # True
print(isinstance(obj.iterable, Iterator))  # True

# ==========================
# 2. Since the iterator is consumed, the  iterator cannot be performed twice.
# ==========================
# return 3 + 0 elements.
for item in obj.iterable:
  print(item)

for item in obj.iterable:
  print(item)

# ==========================
# return 3 + 0 elements.
iterator = iterable.__iter__()
for item in iterator:
  print(item)

for item in iterator:
  print(item)

# ==========================
# return 3 + 3 elements.
for item in iterable:
  print(item)

for item in iterable:
  print(item)

# ==========================
# return 3 + 3 elements.
for item in iterable.__iter__():
  print(item)

for item in iterable.__iter__():
  print(item)
```

**Comment by layday** [comment]
Perhaps @tiangolo might have some insight into why `Iterable` was chosen or if it was simply an oversight.

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
