### ISSUE TITLE
Global default config for models

### ISSUE THREAD

**Issue by baterflyrity** [samuelcolvin/pydantic#2003]
Now each model can be configured individually or fully nested. So id like to have feature that allows more configuration flexibility. Other issue asked for customizable nesting of configs when i suppose to add global default configuration to all models (or maybe scoped?).

```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: D:\Python\Lib\site-packages\pydantic
               python version: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.19041-SP0
     optional deps. installed: ['typing-extensions']
```

Currently im using small hack but i think its not 'true' way:

```py
from pydantic import BaseModel

class BaseModel(BaseModel):
    class Config:
        ...

class MyModel(BaseModel):
    a:int
    ...
```

**Comment by StephenBrown2** [comment]
Yes, that is how it is recommended to be done, though often your custom BaseModel will be named differently:
```python
from pydantic import BaseModel

class ConfiguredBaseModel(BaseModel):
    class Config:
        ...

class MyModel(ConfiguredBaseModel):
    a:int
    ...
```
So that you can then import it from other files and not worry about name conflicts.

Alternatively, you could rename the Pydantic BaseModel for the same effect:

```python
from pydantic import BaseModel as PydanticBaseModel

class BaseModel(PydanticBaseModel):
    class Config:
        ...

class MyModel(BaseModel):
    a:int
    ...
```

**Comment by eyalk11** [comment]
Related: 
```
from pydantic.dataclasses import dataclass as pyddataclass
confdict=ConfigDict(arbitrary_types_allowed=True)
dataclass=partial(pyddataclass,config=confdict)
```

**Comment by Nithin745** [comment]
Hi, i'm trying to do something like, how can we do something like this in V2

**Comment by BlackHC** [comment]
```
import pydantic

pydantic.BaseModel.model_config[...] = ...
```

**Comment by Viicos** [comment]
Tracking in https://github.com/pydantic/pydantic/issues/12556.
