### ISSUE TITLE
py3.9 pydantic.errors.ConfigError: duplicate validator function

### ISSUE THREAD

**Issue by Yajo** [samuelcolvin/pydantic#2009]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

When starting to add python 3.9 to a project, pydantic started to fail badly. My pytest log is full of this:

```py
copier/__init__.py:3: in <module>
    from .main import *  # noqa
copier/main.py:18: in <module>
    from .config import make_config
copier/config/__init__.py:1: in <module>
    from .factory import make_config  # noqa
copier/config/factory.py:19: in <module>
    from .user_data import load_answersfile_data, load_config_data, query_user_data
copier/config/user_data.py:50: in <module>
    class Question(BaseModel):
copier/config/user_data.py:128: in Question
    def _check_var_name(cls, v):
.venv/lib/python3.9/site-packages/pydantic/class_validators.py:86: in dec
    f_cls = _prepare_validator(f, allow_reuse)
.venv/lib/python3.9/site-packages/pydantic/class_validators.py:145: in _prepare_validator
    raise ConfigError(f'duplicate validator function "{ref}"; if this is intended, set `allow_reuse=True`')
E   pydantic.errors.ConfigError: duplicate validator function "copier.config.user_data.Question._check_var_name"; if this is intended, set `allow_reuse=True`
```

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:

```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /var/home/yajo/prodevel/copier/.venv/lib64/python3.8/site-packages/pydantic
               python version: 3.8.6 (default, Sep 25 2020, 00:00:00)  [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
                     platform: Linux-5.8.15-201.fc32.x86_64-x86_64-with-glibc2.2.5
     optional deps. installed: ['typing-extensions']
```

(although where it fails is on python 3.9, but with those same versions of everything else. I use dependencies pinned with poetry, so they should be the same, but I don't have Python 3.9 locally, just in the CI; see below)

Useful info:

- [Full test log](https://github.com/copier-org/copier/runs/1264093372?check_suite_focus=true) (although almost all failures are the same).
- [The piece of code where the validator is defined](https://github.com/copier-org/copier/blob/598388af30e851c34fcd9bd76ee5aad2ce2fd039/copier/config/user_data.py#L125-L136), and that works OK on python 3.6-3.8.

**Comment by PrettyWood** [comment]
Hi @Yajo 
Python 3.9 is currently not supported. It will be in https://github.com/samuelcolvin/pydantic/pull/1844
Have you tried with it ?

**Comment by Yajo** [comment]
I just tried it in this draft PR: https://github.com/copier-org/copier/pull/294

It goes all green :green_heart: !

**Comment by PrettyWood** [comment]
#1844 has been merged. Please reopen if needed

**Comment by Yajo** [comment]
It seems to work. Are there any plans for a release that supports py3.9?
