### ISSUE TITLE
Default enum values does not respect the use_enum_values config

### ISSUE THREAD

**Issue by dharmagetic** [samuelcolvin/pydantic#2010]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:

             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: <path-to-virtualenv>/lib/python3.7/site-packages/pydantic
               python version: 3.7.7 (default, May 30 2020, 23:15:38)  [Clang 9.0.0 (clang-900.0.39.2)]
                     platform: Darwin-19.6.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']

```py
from enum import Enum

from pydantic import BaseModel


class FruitEnum(str, Enum):
    pear = 'pear'
    banana = 'banana'


class CookingModel(BaseModel):
    fruit: FruitEnum = FruitEnum.pear

    class Config:
        use_enum_values = True

print(CookingModel().dict())
# outputs: {'fruit': <FruitEnum.pear: 'pear'>}
```

**Comment by PrettyWood** [comment]
Hello @dharmagetic 
The issue is that `use_enum_values` will be triggered when the default value is validated.
And by default, default values are not!
You could write `fruit: FruitEnum = 123` and you would get `{'fruit': 123}`.
If you want to make it work, just switch from
```python
    class Config:
        use_enum_values = True
```
to
```python
    class Config:
        use_enum_values = True
        validate_all = True
```

**Comment by dharmagetic** [comment]
Hello @PrettyWood 
That's solved my issue.

Thank you very much !!!
