### ISSUE TITLE
Question:custom serializer on dict with the field not getting serialized

### ISSUE THREAD

**Issue by kbhatia** [samuelcolvin/pydantic#2012]
example: 
```
class TestModel(pydantic.BaseModel):
    class Config:
        json_encoders = {
            dict: lambda x: json.dumps(urlencode(x))
        }

    a: dict

```
Basically the behavior I am expecting for is `t = TestModel(a={"v1":"val"} `and then t should be` a: "v1%27Val"` a urlencoded string. Is this possible? I may very well have a bug in my code above as well. Any hints appreciated.

**Comment by PrettyWood** [comment]
Hi @kbhatia 

You actually want to change directly the content of your object, not the `.dict` representation ?
If so you can just do

```python
from pydantic import BaseModel, validator
import json
from urllib.parse import urlencode

class TestModel(BaseModel):
    a: str

    @validator('a', pre=True)
    def url_encode(cls, a):
        return json.dumps(urlencode(a))
```

**Comment by kbhatia** [comment]
Correct, but I also want to be able to take a urlencoded string as an input via parse_raw and convert it into TestModel. So for example, 
`a='"v1=val"'
 TestModel.parse_raw(a) should become a={'v1': 'val'}
`

Would I be able to achive that with this as well? As far as I think, this will complain when I use parse_raw because it is requiring a dict through validator

**Comment by PrettyWood** [comment]
You could go with something like
```python
import json
from urllib.parse import urlencode, parse_qsl

from pydantic import BaseModel


def load(v) -> dict:
    if isinstance(v, str):
        query_str = json.loads(v)
        return dict(parse_qsl(query_str))
    return v


def dump(v, default):
    if isinstance(v, dict):
        return urlencode(v)
    return default(v)


class TestModel(BaseModel):
    __root__: dict

    class Config:
        json_loads = load
        json_dumps = dump

assert TestModel.parse_raw('"v1=val"').__root__ == {'v1': 'val'}
assert TestModel(__root__={'v1': 'val'}).__root__ == {'v1': 'val'}
assert TestModel(__root__={'v1': 'val'}).json() == 'v1=val'
```

Please do not hesitate to add all the expected assertions instead of just one.
It could help us suggesting the best suitable solution

Hope it helps

**Comment by kbhatia** [comment]
Thank you so much!
