### ISSUE TITLE
How to allow initialization but not allow assignment/setter for one single field

### ISSUE THREAD

**Issue by tybluware** [samuelcolvin/pydantic#2019]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/pydantic
               python version: 3.6.9 (default, Nov 11 2019, 11:24:16)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
                     platform: Linux-5.4.0-51-generic-x86_64-with-centos-7.8.2003-Core
     optional deps. installed: ['typing-extensions']
...
```

```py
from uuid import uuid4
import pydantic

class MyData(BaseModel):
    data_id: UUID = Field(default_factory=uuid4)
    name: str = ...
    age: int = Field(..., ge=0, le=200)

data1 = MyData(name="John", age=12)
try:
    data1.data_id = uuid4()
    assert False # I would like somehow I can disable the setting of "data_id" once object instantiated
except:
    assert True
...
```
What I want to enforce is that for field "data_id" once the an instance of MyData is created, one can not change it anymore

**Comment by PrettyWood** [comment]
Hello @tybluware 
You could use `validate_assignment` to check values when assigned in combination with a validator or `const = True`. Check with `const` is a bit hacky as the default value is `None` (it doesn't check the default value set by the `default_factory`) for it but it does the job!
So you can do either

```python
class MyData(BaseModel):
    data_id: UUID = Field(default_factory=uuid4, const=True)
    name: str = ...
    age: int = Field(..., ge=0, le=200)

    class Config:
        validate_assignment = True
```

or 


```python
class MyData(BaseModel):
    data_id: UUID = Field(default_factory=uuid4)
    name: str = ...
    age: int = Field(..., ge=0, le=200)

    class Config:
        validate_assignment = True

    @validator('data_id')
    def should_not_be_changed(cls, v):
        raise ValueError('data_id should not be changed')
```

Hope it helps!

**Comment by tybluware** [comment]
Thanks a lot for pointing out the "const=True" solution. I was actually using 2nd solution you provided. I also tried your 1st solution. However they all missing one thing is that now one can not create an instance of MyData by also provide a "data_id" which now can only be generated by the default factory method. In other words, following code now will throw exception:
'''
data1 = MyData(uuid4(), "john", 23)
'''

**Comment by mdavis-xyz** [comment]
What exception does that code throw? Please paste it in.

Also, when putting code snippets into github comments, use three *backticks* not three apostophes. Backticks are the button up the top left, same button as `~`. That way your code will look like:

```
data1 = MyData(uuid4(), "john", 23)
```

**Comment by tybluware** [comment]
Ah, sorry my bad. here is the error:
```
    def test_task_constructor():
        task_id = Entity(name="task1")
        p_id = str(uuid.uuid4())
>       task1 = Task(task_id=task_id, is_global=True, parent_id=p_id, mask_categories=[4])

tests/bmle/entity/test_task.py:25: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   pydantic.error_wrappers.ValidationError: 1 validation error for Task
E   task_id
E     unexpected value; permitted: None (type=value_error.const; given=name: "task1"
E   ; permitted=[None])

pydantic/main.py:346: ValidationError
```

**Comment by mdavis-xyz** [comment]
So you're saying you want the default value of `task_id` to be something invalid? Is that the question? That sounds like something you shouldn't be trying to do. Just change to schema to accept the default value.

**Comment by tybluware** [comment]
looks like I am doing a terrible job explaining. 
NO, I do NOT want task_id to be something invalid. it has nothing to with valid or not valid.
what I want is: a field it can be initialized and validated; but then prohibit it from being changed, such as via the setter. As stated previously: 
**- field can be initialized during contruction
- but can not be modified via setter**

**Comment by PrettyWood** [comment]
@tybluware Feels like #2196 should solve your issue right?

**Comment by tybluware** [comment]
Yes! that would work.
