### ISSUE TITLE
Question about typing  a bunch of subclasses using base class

### ISSUE THREAD

**Issue by lijok** [samuelcolvin/pydantic#2021]
If I have a ton of classes inheriting from the same base, like so:
```py
import typing
from pydantic import BaseModel


class Base(BaseModel):
    pass


class A1(Base):
    id: int


class A2(Base):
    name: str


...


class A501(Base):
    var: str


def do_something(schema: Base):
    print(schema.name)

```

Is there a mechanism for constructing a type hint for `do_something` `schema` arg, such that, pycharm would be able to do code suggestion on fields of all the classes which inherit from Base? Or is my only option to build a massive type hint for schema such as `typing.Union[A1, A2, A3, ... A501, A502]` ?

**Comment by zdlovett** [comment]
I would normally do something like: 
```python
AnyA = typing.Union[A1, A2, A3, ... A501, A502]

def do_something(schema: AnyA):
    print(schema.name)
```

You do still end up needing the huge type hint, but at least in this method its only in one location, and its easy to import into other models as needed.

**Comment by lijok** [comment]
> 
> 
> I would normally do something like:
> 
> ```python
> AnyA = typing.Union[A1, A2, A3, ... A501, A502]
> 
> def do_something(schema: AnyA):
>     print(schema.name)
> ```
> 
> You do still end up needing the huge type hint, but at least in this method its only in one location, and its easy to import into other models as needed.

Ah, this will work
Thank you !
