### ISSUE TITLE
How to add submodel ids as a list to the model?

### ISSUE THREAD

**Issue by atuldhanorker** [samuelcolvin/pydantic#2022]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question

the frontend expects the api to return the data in following format.

"users": {
"id": 5,
"full_name": "XYZ",
"email": "XYZ@xyz.com",
"items": [1, 2]
}

How can I return the id's of item as a list rather than returning the item model

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /apps/anaconda3/lib/python3.7/site-packages/pydantic
               python version: 3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0]
                     platform: Linux-3.10.0-1127.10.1.el7.x86_64-x86_64-with-redhat-7.8
     optional deps. installed: ['typing-extensions', 'email-validator']
```

```py
from pydantic import BaseModel

# sqlalchemy models

class User(Base):
    __tablename__ = "user"
    id = Column( Integer, primary_key=True, index=True)
    full_name = Column( String, index=True)
    email = Column( String, unique=True, index=True)
    hashed_password = Column( String)
    is_active = Column( Boolean(), default=False)
    is_superuser = Column( Boolean(), default=False)
    items = relationship("Item", back_populates="owner")

class Item(Base):
    __tablename__ = "items"
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, index=True)
    description = Column(String, index=True)
    owner_id = Column(Integer, ForeignKey("user.id"))
    owner = relationship("User", back_populates="items")

# pydantic models

class UserBase(BaseModel):
    email: Optional[str] = None
    full_name: Optional[str] = None
   items: Optional[List[ItemInDBBase]]

class ItemBase(BaseModel):
    title: str = None
    description: str = None
    owner_id: int

class ItemInDBBase(ItemBase):
    id: int
    title: str
    owner_id: int
```

**Comment by mdavis-xyz** [comment]
I'm not quite sure what the question is. This code doesn't look complete. It also looks like it contains more than is required for a minimal working example. (e.g. you only need one or two classes to illustrate your question.) You talk about an API. Is this code part of a server, or client? Where's the call to/from the server?

I'm not sure which class matches the json you put.

You're probably doing something like this:

```
x = UserBase(*args) # or UserBase.parse_obj(d)
requests.post(body=x)
```

If you want to get rid of all the nested pydantic models, export the model to a dict with `x.dict()` or `x.json()`.

**Comment by akettmann-e24** [comment]
if I am understanding your question right, the parse_orm function and a differently written model might be the ticket here:
```py
from pydantic import BaseModel
from typing import List, Dict

class UserItem(BaseModel):
    id: int
    full_name: str
    email: str
    items: List[int]


def get_user_from_orm(user_id: int) -> Dict:
    orm_user = session.query(User).filter(User.id == user_id).one()
    return UserItem.from_orm(orm_user).dict()

    return user.dict()
```

Also one thing on the SQLAlchemy side I would recommend if this is a frequent way to use this model, either define on the relationship an eager load with something like this:

```py
class User(Base):
    # snip
    items = relationship("Item", back_populates="owner", lazy="joined")
```

or if it is easier, you can specify it on the query:
```py
def get_user_from_orm(user_id: int) -> Dict:
    orm_user = session.query(User).filter(User.id == user_id).options(joinedload('items')).one()
    return UserItem.from_orm(orm_user).dict()

    return user.dict()
```

Otherwise the items are not retrieved from the DB until you access the User.items attribute, meaning each object will result in two queries instead of one. Or if you are pulling back 100 at a time, then it would be 101 queries instead of 1 query.

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
