### ISSUE TITLE
Generating random data that matches schema

### ISSUE THREAD

**Issue by mdavis-xyz** [samuelcolvin/pydantic#2023]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this feature/change is needed
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Feature Request

[Hypothesis](https://hypothesis.readthedocs.io/) is a great tool for generating random data that matches a schema, to check that an API server can handle all valid edge cases for inputs, and only returns responses that match the schema.

I want to do something similar for an API client, including testing the code before and after the actual API call.
To do this, I want to instantiate my classes with random data that matches all the constraints.

In the past, I've done this manually. e.g.

```
class MyEnum(str, Enum):
    A = 'A'
    B = 'B'

    @classmethod
    def random(cls):
        return cls(choice(list(cls.__members__)))


class MyDict(BaseModel):
    x: Optional[MyEnum]
    y: MyEnum
    z: NegativeFloat

    @classmethod
    def random(cls):
        return cls(
            x=choice([None, MyEnum.random()]),
            y=MyEnum.random(),
            z=random.uniform(-1000, 0)
        )
```

Then I call 

```
x = MyDict.random()
```

These `random()` functions are written by me by hand. Is there an easier way to do this?
I tried reading the Hypothesis code to understand what they do, but I couldn't find the relevant part.

The hard part will be dealing with custom validators. I'm happy to just keep rolling a dict generating random data until it happens to match a custom validator. (As opposed to the sophisticated black-magic approach Hypothesis uses.)

**Comment by mdavis-xyz** [comment]
@Zac-HD can you point me in the right direction?

**Comment by Zac-HD** [comment]
https://pypi.org/project/hypothesis-jsonschema/ might be what you're after?

Or if you're looking at doing it from the Python objects, check out the `st.builds()` strategy - you can supply a specific strategy for the arguments with tricky validators, and let everything else be handled by `st.from_type()`.  You can even use `st.register_type_strategy()` to teach `st.from_type()` to use that custom strategy for every instance of your class.  For example:

```python
st.register_type_strategy(
    MyDict,
    # Hypothesis can automatically sample from Enums and understands typing types
    z=st.floats(max_value=-0.0, exclude_max=True),
)

@given(st.from_type(MyDict))
def test_foo(x): ...
```

And see #2017 for my proposal to handle Pydantic-specific types like `NegativeFloat` automatically too :grin: 

-------------

If that's not what you're after, please give me an example usage and a class with some complicated validators, and I'll have a look - this is a use-case I want Hypothesis to make *really* easy.

**Comment by mdavis-xyz** [comment]
Yeah `hypothesis-jsonschema` might be what I need. I could extract the relevant components from my swagger file, load it into that module, then test my code with it. (I'll need to de-reference the schemas, but I'm sure there's a tool somewhere for doing that.)

> this is a use-case I want Hypothesis to make really easy.

Phew. That's great to hear.

I'll give these things a go. Thanks

**Comment by Zac-HD** [comment]
Ah, sounds like Schemathesis! https://schemathesis.readthedocs.io/en/stable/

**Comment by mdavis-xyz** [comment]
Yeah, I know about schemathesis. That's for testing API servers. I want to test an API client. You can't do that directly with schemathesis, right?

Here's what I've got:

```
import unittest
import pydantic
from hypothesis import given
from hypothesis_jsonschema import from_schema
from schemathesis.specs.openapi.references import ConvertingResolver
from openapi_schema_to_json_schema import to_json_schema
from hypothesis_jsonschema import from_schema as from_json_schema
import yaml
import json

with open('swagger/aws2epic.yaml', 'r') as f:
    raw_schema = yaml.safe_load(f)
    
# resolve any $ref references
resolver = ConvertingResolver("", raw_schema, nullable_name="nullable")
schema = resolver.resolve_all(raw_schema)

# now convert to json schema, for each model
component_schemas = to_json_schema(schema['components']['schemas'])

class MyModel(pydantic.BaseModel):
   # code generated by https://github.com/koxudaxi/datamodel-code-generator/
   # then modified
   id: str # simplified example

class TestModels(unittest.TestCase):
    @given(from_json_schema(component_schemas['MyModel']))
    def test_site_standing_data(self, data):
        MyModel.parse_obj(data)
```

**Comment by Zac-HD** [comment]
I think you might be able to just run `hypothesis_jsonschema.from_schema(raw_schema['components']['schemas']['MyModel'])`; that has non-recursive `$ref` resolution built in (and see https://github.com/Zac-HD/hypothesis-jsonschema/issues/33).

>  I want to test an API client. You can't do that directly with schemathesis, right?

I believe you're correct, but @Stranger6667 might know better.  In any case if what you want to test is that "any JSON blob accepted by my schema can be passed to my Pydantic classes", then `hypothesis-jsonschema` is probably the tool you're after.

**Comment by Stranger6667** [comment]
Yep, depends on how exactly you'd like to test your client, but I suppose that the best way would be to use `hypothesis-jsonschema` :)

**Comment by Stranger6667** [comment]
There are some differences in how Schemathesis and `hypothesis-jsonschema` handle references, so it depends on your concrete use case.  Schemathesis handle files & network resources by default and bounds recursive references resolving

**Comment by mdavis-xyz** [comment]
I'm finding that whilst my approach above works, I'm getting hypothesis health check errors about examples taking too long to generate, even though my real classes are not very complex.

My OpenAPI schema includes regex strings for UUIDs and datetimes. I'm assuming `hypothesis-jsonschema` just treats these as normal strings. @Zac-HD does `hypothesis-jsonschema` use [`st.from_regex`](https://hypothesis.readthedocs.io/en/latest/data.html?highlight=max_size#hypothesis.strategies.from_regex)? Would that explain why my generation is so slow?

snippets from my spec are:

```
timestamp:
          type: string
          example: "2020-09-10T16:20:00+10:00"
          pattern: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\+10:00
          nullable: False
```

```
RequestId:
      # UUID4 standard
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89aAbB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
      type: string
      example: 16c26f16-148a-4602-a4fa-894e02d04780
```

**Comment by Zac-HD** [comment]
Depends on the OpenAPI schema I think, but the most likely cause of too-slow healthchecks is generating large data, in which case I'd just disable that check.

We do use `from_regex()` and `\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\+10:00` is going to generate a lot of unicode digits.  This is not performance advice, but if timestamps are meant to be ASCII you should use `[0-9]` instead of `\d` :wink:

**Comment by mdavis-xyz** [comment]
Hi @Zac-HD , can you clarify [your comment above](https://github.com/samuelcolvin/pydantic/issues/2023#issuecomment-714870060) about using `register_type_strategy` for specifying a strategy for only one field of a pydantic model?


You said I can do:

```
st.register_type_strategy(
    MyDict,
    # Hypothesis can automatically sample from Enums and understands typing types
    z=st.floats(max_value=-0.0, exclude_max=True),
)

@given(st.from_type(MyDict))
def test_foo(x): ...
```

But when I try that, I get an error, because `register_type_strategy` doesn't understand `z=`.

Full MWE:

```
from hypothesis import given, strategies as st
from pydantic import BaseModel

class MyDict(BaseModel):
    z: float
    x: str
    y: int

st.register_type_strategy(
    MyDict,
    # Hypothesis can automatically sample from Enums and understands typing types
    z=st.floats(max_value=-0.0, exclude_max=True),
)

@given(st.from_type(MyDict))
def test_foo(x):
    assert isinstance(x, MyDict)
    assert x.z < 0
    
test_foo()
```

Actual Result:

```
Traceback (most recent call last):
  File "hs.py", line 9, in <module>
    st.register_type_strategy(
TypeError: register_type_strategy() got an unexpected keyword argument 'z'
```

Expected result:
Script passes with no exceptions.

**Comment by mdavis-xyz** [comment]
Did you mean to say this?

```
st.register_type_strategy(
    MyDict,
    st.builds(
        MyDict,
        z=st.floats(max_value=-0.0, exclude_max=True),
    )
)
```

Or is there a way to write it as simply as your original comment?

**Comment by Zac-HD** [comment]
You're correct, there does need to be a `st.builds(...)` in there - I've updated my comment above too.

**Comment by danielmoessner** [comment]
I came here via Google. I'm not interested in property based testing and was somewhat lead astray by trying hypothesis. 

I found this repository which does nothing more than generate simple fake data from json schema:
https://github.com/ghandic/jsf

Now this can be used really easy in combination with pydantic like:
```
from jsf import JSF

class Person(BaseModel):
    name: str
    id: int

faker = JSF(Person.schema())
print(faker.generate())
# {'name': 'quas nobis ipsum, consectetur veniam', 'id': 3598}
```

Maybe this is helpful for the next person coming to this thread via google.

**Comment by rahulreghunath** [comment]
You can use this library to generate randum data for pydantic model
[https://www.google.com/url?sa=t&source=web&rct=j&url=https://github.com/starlite-api/pydantic-factories&ved=2ahUKEwiV68KchoH8AhVSyosBHUc4CkwQFnoECBoQAQ&usg=AOvVaw2xi0qG1x6ncx_0WZBAPIF-](https://www.google.com/url?sa=t&source=web&rct=j&url=https://github.com/starlite-api/pydantic-factories&ved=2ahUKEwiV68KchoH8AhVSyosBHUc4CkwQFnoECBoQAQ&usg=AOvVaw2xi0qG1x6ncx_0WZBAPIF-)

**Comment by kamyarghiam** [comment]
Here's a general solution for any pydantic class that uses poylfactory instead of JSF:

```
import typing

from pydantic import BaseModel
from polyfactory.factories import pydantic_factory

def basemodel_with_random_data(base_model_class: typing.Type[BaseModel]) -> BaseModel:
    """Fills in a basemodel with random data based on type hints"""

    class Factory(pydantic_factory.ModelFactory[base_model_class]):
        __model__ = base_model_class

    return base_model_class.parse_obj(Factory.build())
```

and you can use it like:

```
class Person(BaseModel):
    name: str
    id: int

print(basemodel_with_random_data(Person))
```

JSF worked for me, but I kept seeing a deprecation warning, namely:
```
site-packages/rstr/xeger.py:2: DeprecationWarning: module 'sre_parse' is deprecated
```

So I decided to use pydantic-factories as suggested above. But it looks like the project was moved to `polyfactory`, so I used that instead

**Comment by glaucouri** [comment]
Unfortunately, hypothesis is no longer supported. Is there some alternative?

**Comment by nylinary** [comment]
Been handling the same problem - found [nice gist][1] for it

```<!-- language: «python» -->
class ExampleData(pydantic.BaseModel):
    a: int
    b: str = pydantic.Field(min_length=10, max_length=10)

model_object = ModelObjectGenerator().generate(ExampleData)
```





  [1]: https://gist.github.com/nylinary/f5140c2a45421832f02ec8fb81418af4
