### ISSUE TITLE
Truncates `float` to fit an `int` rather than erroring

### ISSUE THREAD

**Issue by SamuelMarks** [samuelcolvin/pydantic#2025]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /Users/samuel/repos/.venvs_py3/ml-env/lib/python3.8/site-packages/pydantic
               python version: 3.8.6 (default, Oct  8 2020, 14:06:32)  [Clang 12.0.0 (clang-1200.0.32.2)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
from pydantic.dataclasses import dataclass

class MyConf:
    validate_assignment = True
    validate_all = True
    arbitrary_types_allowed = False

@dataclass(config=MyConf)
class Z:
    a: int = 5

print(Z(6)) # A(a=6)

print(Z(6.6)) # A(a=6)
```

Would be good to have a `ValueError`, `TypeError`… or any error TBH. Rather than it just silently truncating…

**Comment by mdavis-xyz** [comment]
This doesn't seem like a bug to me.

As per [the docs](https://pydantic-docs.helpmanual.io/usage/validation_decorator/#coercion-and-strictness), pydantic is not strict. It *coerces* input to the desired class. e.g. you would expect that 6.0 gets converted to 6.

In python, `int(6.6)` returns 6. The default float->int conversion is to round down. That's what's happening here.

See #1098

**Comment by SamuelMarks** [comment]
Okay I've switched to https://github.com/PJCampi/runtime-type-checker in the meantime.
