### ISSUE TITLE
Dynamically create a model with multiple base classes?

### ISSUE THREAD

**Issue by cknoll** [samuelcolvin/pydantic#2029]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
            pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /home/ck2/miniconda3/envs/base37/lib/python3.7/site-packages/pydantic
               python version: 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08)  [GCC 7.5.0]
                     platform: Linux-4.19.0-11-amd64-x86_64-with-debian-10.6
     optional deps. installed: []
...
```

I understand this:

```py
import pydantic

class User(pydantic.BaseModel):
    id: int
    name: str

class Student(pydantic.BaseModel):
    semester: int

# this works as expected
class Student_User(User, Student):
    building: str

print(Student_User.__fields__.keys())
#> dict_keys(['semester', 'id', 'name', 'building'])

```

but now I want to create the model for `Student_User` dynamically. I tried 

```py
pydantic.create_model("Student_User2", __base__=(User, Student))
```

but I get an `TypeError`:

```
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

```

Question: How to dynamically create a model with multiple base classes?

**Comment by Apo-** [comment]
If you see the signature of `create_model` looks like this
```python
def create_model(
    __model_name: str,
    *,
    __config__: Type[BaseConfig] = None,
    __base__: Type[BaseModel] = None,
    __module__: Optional[str] = None,
    __validators__: Dict[str, classmethod] = None,
    **field_definitions: Any,
) -> Type[BaseModel]:
```
As you can see `__base__` is a `Type[BaseModel]` and you're trying to pass a `Tuple[Type[BaseModel], ...]`.

This (the `__base__` accepting a single type) is not accidental as the last line of the `create_model` function is this

```python
return type(__model_name, (__base__,), namespace)
```

so what is passed, is expanded to 

```python
return type("Student_User2", ((User, Student),), namespace)
```
which is not what you want.

One solution is to no pass the two bases and just get the fields from the bases and pass them to `create_model`. This will create a class with all the fields from the base classes, but will fail if you want `isinstance(Student_User2, <Base>)` to work.

In that case a workaround would be
```python
Student_User2 = pydantic.create_model("Student_User2", __base__=type("_UserStudentBase", (User, Student), {}))
```

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
