### ISSUE TITLE
Maintain ordering between annotation only fields and fields with defaults

### ISSUE THREAD

**Issue by niconorsk** [samuelcolvin/pydantic#203]
It would be nice if we could have the fields maintain the order they are defined in as it is quite confusing to write validation on fields that depend on each other and knowing which order thing will be called in.

Looking at the code it appears to me that it's an artifact of the way it is written, rather than something the user of the library should care about? I would like to work on a PR but is there a reason outside of the way the fields are discovered in the metaclass that the ordering is the way that it is?

**Comment by niconorsk** [comment]
For the record, I think this diff will maintain the ordering:
`diff --git a/pydantic/main.py b/pydantic/main.py
index e9b57a0..4c4c107 100644
--- a/pydantic/main.py
+++ b/pydantic/main.py
@@ -108,25 +108,16 @@ class MetaModel(ABCMeta):
         annotations = namespace.get('__annotations__', {})
         # annotation only fields need to come first in fields
         for ann_name, ann_type in annotations.items():
-            if not ann_name.startswith('_') and ann_name not in namespace:
+            value = namespace.get(ann_name, ...)
+            if not ann_name.startswith('_') and not isinstance(value, TYPE_BLACKLIST):
                 fields[ann_name] = Field.infer(
                     name=ann_name,
-                    value=...,
+                    value=value,
                     annotation=ann_type,
                     class_validators=vg.get_validators(ann_name),
                     config=config,
                 )

-        for var_name, value in namespace.items():
-            if not var_name.startswith('_') and not isinstance(value, TYPE_BLACKLIST):
-                fields[var_name] = Field.infer(
-                    name=var_name,
-                    value=value,
-                    annotation=annotations.get(var_name),
-                    class_validators=vg.get_validators(var_name),
-                    config=config,
-                )
-
         vg.check_for_unused()
         new_namespace = {
             '__config__': config,`

**Comment by samuelcolvin** [comment]
Maybe I'm missing something, but I don't think that works if you have attributes without annotations eg.

```py
class FoobarModel(BaseModel):
   anne: str
   ben: int = 1
   charlie = 'xxx'
```

`charlie` doesn't have a type annotation, instead, its type is inferred from the default.

**Comment by niconorsk** [comment]
You are indeed correct. I had completely missed the infering from default behaviour.

I agree that if ordering isn't guaranteed in all cases, then the current situation is a lot clearer.
