### ISSUE TITLE
Pattern type serialisation error

### ISSUE THREAD

**Issue by adrienyhuel** [samuelcolvin/pydantic#2045]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7
            pydantic compiled: True
                 install path: /root/.local/lib/python3.8/site-packages/pydantic
               python version: 3.8.6 (default, Oct 13 2020, 20:49:19)  [GCC 8.3.0]
                     platform: Linux-3.10.0-1127.19.1.el7.x86_64-x86_64-with-glibc2.2.5
     optional deps. installed: ['email-validator']
```

```py
from typing import Pattern
from pydantic import BaseModel

class Model(BaseModel):
    filter: Pattern

Model(filter="^regex$").json()
```

This produce an error : 
TypeError: Object of type 'Pattern' is not JSON serializable

I had to write a custom encoder to be able to serialize properly a Pattern type : 

```py
from typing import Pattern
from pydantic import BaseModel
import re

class Model(BaseModel):
    filter: Pattern
    class Config:
        json_encoders = {
            re.Pattern: lambda v: v.pattern,
        }

Model(filter="^regex$").json()
```

**Comment by adrienyhuel** [comment]
@PrettyWood @samuelcolvin 
Although this resolve the problem with the code provided in this issue, I have now a problem with FastAPI, when returning an object which contains a field of Pattern type.

> mft_api.1.zpratbdtmkmb@mft.local    | [2021-03-01 15:49:42 +0000] [11] [ERROR] Exception in ASGI application
mft_api.1.zpratbdtmkmb@mft.local    | Traceback (most recent call last):
mft_api.1.zpratbdtmkmb@mft.local    |   File "/root/.local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
mft_api.1.zpratbdtmkmb@mft.local    |     result = await app(self.scope, self.receive, self.send)
mft_api.1.zpratbdtmkmb@mft.local    |   File "/root/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
mft_api.1.zpratbdtmkmb@mft.local    |     return await self.app(scope, receive, send)
mft_api.1.zpratbdtmkmb@mft.local    |   File "/root/.local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
mft_api.1.zpratbdtmkmb@mft.local    |     await super().__call__(scope, receive, send)
mft_api.1.zpratbdtmkmb@mft.local    |   File "/root/.local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
mft_api.1.zpratbdtmkmb@mft.local    |     await self.middleware_stack(scope, receive, send)
mft_api.1.zpratbdtmkmb@mft.local    |   File "/root/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
mft_api.1.zpratbdtmkmb@mft.local    |     raise exc from None
mft_api.1.zpratbdtmkmb@mft.local    |   File "/root/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
mft_api.1.zpratbdtmkmb@mft.local    |     await self.app(scope, receive, _send)
mft_api.1.zpratbdtmkmb@mft.local    |   File "/root/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
mft_api.1.zpratbdtmkmb@mft.local    |     raise exc from None
mft_api.1.zpratbdtmkmb@mft.local    |   File "/root/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
mft_api.1.zpratbdtmkmb@mft.local    |     await self.app(scope, receive, sender)
mft_api.1.zpratbdtmkmb@mft.local    |   File "/root/.local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
mft_api.1.zpratbdtmkmb@mft.local    |     await route.handle(scope, receive, send)
mft_api.1.zpratbdtmkmb@mft.local    |   File "/root/.local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
mft_api.1.zpratbdtmkmb@mft.local    |     await self.app(scope, receive, send)
mft_api.1.zpratbdtmkmb@mft.local    |   File "/root/.local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
mft_api.1.zpratbdtmkmb@mft.local    |     response = await func(request)
mft_api.1.zpratbdtmkmb@mft.local    |   File "/root/.local/lib/python3.8/site-packages/fastapi/routing.py", line 209, in app
mft_api.1.zpratbdtmkmb@mft.local    |     response_data = await serialize_response(
mft_api.1.zpratbdtmkmb@mft.local    |   File "/root/.local/lib/python3.8/site-packages/fastapi/routing.py", line 127, in serialize_response
mft_api.1.zpratbdtmkmb@mft.local    |     return jsonable_encoder(
mft_api.1.zpratbdtmkmb@mft.local    |   File "/root/.local/lib/python3.8/site-packages/fastapi/encoders.py", line 57, in jsonable_encoder
mft_api.1.zpratbdtmkmb@mft.local    |     return jsonable_encoder(
mft_api.1.zpratbdtmkmb@mft.local    |   File "/root/.local/lib/python3.8/site-packages/fastapi/encoders.py", line 90, in jsonable_encoder
mft_api.1.zpratbdtmkmb@mft.local    |     encoded_value = jsonable_encoder(
mft_api.1.zpratbdtmkmb@mft.local    |   File "/root/.local/lib/python3.8/site-packages/fastapi/encoders.py", line 104, in jsonable_encoder
mft_api.1.zpratbdtmkmb@mft.local    |     jsonable_encoder(
mft_api.1.zpratbdtmkmb@mft.local    |   File "/root/.local/lib/python3.8/site-packages/fastapi/encoders.py", line 90, in jsonable_encoder
mft_api.1.zpratbdtmkmb@mft.local    |     encoded_value = jsonable_encoder(
mft_api.1.zpratbdtmkmb@mft.local    |   File "/root/.local/lib/python3.8/site-packages/fastapi/encoders.py", line 141, in jsonable_encoder
mft_api.1.zpratbdtmkmb@mft.local    |     raise ValueError(errors)
mft_api.1.zpratbdtmkmb@mft.local    | ValueError: [TypeError("'re.Pattern' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]

When I put back my workaround in my code, it works : 
```python
json_encoders = {
            re.Pattern: lambda v: v.pattern,
        }
```

**Comment by PrettyWood** [comment]
Well `fastapi` uses its own json encoder and reuses `ENCODERS_BY_TYPE` from _pydantic_ here
https://github.com/tiangolo/fastapi/blob/5614b94ccc9f72f1de2f63aae63f5fe90b86c8b5/fastapi/encoders.py#L126-L127
We could maybe add `Pattern` directly in `ENCODERS_BY_TYPE` to make it work

**Comment by adrienyhuel** [comment]
@PrettyWood 
I installed pydantic from your branch (https://github.com/PrettyWood/pydantic/archive/pattern-fastapi.zip) and it works.

Well done 👍
