### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by binderclip** [samuelcolvin/pydantic#206]
https://github.com/samuelcolvin/pydantic/blob/f0f9de5f968810b0762778a056a9f4dab1a486e6/docs/examples/validators_pre_whole.py#L23
https://github.com/samuelcolvin/pydantic/blob/f0f9de5f968810b0762778a056a9f4dab1a486e6/docs/examples/validators_pre_whole.py#L43

`number to large` should be `number too large`?

**Comment by samuelcolvin** [comment]
Thanks. Pr welcome.
