### ISSUE TITLE
Constructor arguments that validate as-is should be used directly, preserving identity

### ISSUE THREAD

**Issue by mikenerone** [samuelcolvin/pydantic#2068]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything  - _Although the generic terms involved make it hard to search for_
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this feature/change is needed
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Feature Request
Let me first point out that I may be missing something in the docs somewhere, because this seems like a common need. Apologies if that's the case.

For many domains, modeling the data involves many-to-1/many relationships. To maintain consistency in such cases, it's important to prevent duplication of instances, which can lead to conflicting states of that instance being represented. To illustrate:

```py
from pydantic import *
from typing import *
class Person(BaseModel):
    name: str
    licensed: bool = True
class Car(BaseModel):
    owner: Person
joe = Person(name='Joe')
car1 = Car(owner=joe)
car2 = Car(owner=joe)

car1.owner == car2.owner
# -> True  # Well I certainly hope so.

car1.owner is car2.owner
# ->False  # But I want this to be true so that...

car1.owner.licensed = False
assert car1.owner.licensed == car2.owner.licensed
# -> AssertionError  # ...this can't happen
```
I would argue that in a perfect world, preserving the original identity of all passed objects that validate should be the default behavior (the caller can always call `.copy()` if they don't want that), but obviously backward-compatibility suggests otherwise in this case, so my ask is for a `Config`/`Field` option to enable it.

This alternative constructor seems to work around the issue for me so far (though I haven't done all that much with it yet), but it has some obvious caveats. If this feature isn't something that can be part of Pydantic itself, perhaps you could provide advice about a better approach. :)

```py
class MyBaseModel(BaseModel):
    @classmethod
    def new(cls, **kwargs):
        instance = cls(**kwargs)  # Everything passed validation, defaults set, etc.
        for attr, value in kwargs.items():  # Now just preserve what was passed in if it doesn't seem like it changed.
            if getattr(instance, attr) == value:
                setattr(instance, attr, value)
        return instance

```

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7
            pydantic compiled: False
                 install path: /Users/mikenerone/Library/Caches/pypoetry/virtualenvs/tq-sdt-ZTYqhc-v-py3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.6 (default, Sep 28 2020, 04:41:02)  [Clang 11.0.3 (clang-1103.0.32.62)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: []
```

**Comment by PrettyWood** [comment]
Hi @mikenerone 
This is a known issue (see #1246)
In the meantime I would do something like this
```python
from typing import Any, Type

from pydantic import BaseModel as PydanticBaseModel

class BaseModel(PydanticBaseModel):
    @classmethod
    def validate(cls: Type[PydanticBaseModel], value: Any) -> PydanticBaseModel:
        if isinstance(value, cls):
            return value
        return super().validate(value)


class Person(BaseModel):
    name: str
    licensed: bool = True


class Car(BaseModel):
    owner: Person


joe = Person(name='Joe')
car1 = Car(owner=joe)
car2 = Car(owner=joe)


assert car1.owner == car2.owner
assert car1.owner is car2.owner
```
Hope it helps!

**Comment by mikenerone** [comment]
> This is a known issue (see #1246)
@PrettyWood Ah, I knew someone must have brought this up before. Sorry my search-fu failed me. Thanks much for the interim solution, that's much better! :)
