### ISSUE TITLE
AnyHttpUrl failing validation with Postgresql

### ISSUE THREAD

**Issue by holyoaks** [samuelcolvin/pydantic#2072]
### Checks

* [X ] I added a descriptive title to this issue
* [ X] I have searched (google, github) for similar issues and couldn't find anything
* [ X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /Users/Shawn/project/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Sep 24 2020, 19:37:08)  [Clang 12.0.0 (clang-1200.0.32.21)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions', 'email-validator']
```

I'm having a strange issue with validating a Pydantic BaseModel, sending the data as a Body parameter with FastAPI. I have setup a Joined Table inheritance in my SqlAlchemy models (against Postgresql 12) as shown below (following the [docs][1]:

```python

class Employee(Base):
    __tablename__ = "employee"
    __mapper_args__ = {"polymorphic_identity": "employee", "polymorphic_on": "employee_type"}
    id = Column(Integer, primary_key=True, index=True)
    ...
    employee_type = Column(String, nullable=False)


class Manager(Employee):
    __tablename__ = "manager"
    __mapper_args__ = {"polymorphic_identity": "manager_employee"}
    id = Column(Integer, ForeignKey("employee.id"), primary_key=True, index=True)
    text = Column(String, nullable=False)


class Engineer(Employee):
    __tablename__ = "engineer"
    __mapper_args__ = {"polymorphic_identity": "engineer_employee"}
    id = Column(Integer, ForeignKey("employee.id"), primary_key=True, index=True)
    link_url = Column(String, nullable=False)
```

I then have setup Pydantic BaseModel Create schemas as shown below. The `EmployeeCreate` schema is designed to take either `text`, in the case of a Manager being submitted, or `link_url` if an Engineer is submitted. 

```python
class EmployeeBase(BaseModel):
    title: str

    class Config:
        arbitrary_types_allowed = True
        orm_mode = True


class EmployeeCreate(EmployeeBase):
    text: Optional[str]
    link_url = Optional[AnyHttpUrl]
```

My route, to handle creating a new Manager or Engineer:

```python
async def create_employee(division_id: int, emp_create: EmployeeCreate):
    ...
```

Everything works fine when I submit my body parameters with a `text` key, like so:

`{"title":"Manager", "text":"some text"}`

If I submit a url, though, with the `link_url` key, like so:

`{"title":"Engineer", "link_url":"https://www.google.com/"}`

I get `422 Unprocessable Entity`. When I step through the code, I see that I'm failing validation (Pydantic.fields.py, line 725, _apply_validators, for some reason I can't step into that code), and the error I'm getting back from fastapi is:

```json
{
    "detail": [
        {
            "loc": [
                "body",
                "link_url"
            ],
            "msg": "instance of _GenericAlias expected",
            "type": "type_error.arbitrary_type",
            "ctx": {
                "expected_arbitrary_type": "_GenericAlias"
            }
        }
    ]
}
```

I'm also seeing problems returning from Postgresql, shown below:

```
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type '_GenericAlias'
[SQL: INSERT INTO engineer (id, link_url) VALUES (%(id)s, %(link_url)s)]
[parameters: {'id': 9, 'link_url': typing.Union[pydantic.networks.HttpUrl, NoneType]}]
```

Is this a Pydantic bug, or am I missing something really simply here. Thank you!

  [1]: https://docs.sqlalchemy.org/en/13/orm/inheritance.html#joined-table-inheritance

**Comment by layday** [comment]
You have an equals sign instead of a colon:

```py
link_url = Optional[AnyHttpUrl]
```

This should be:

```py
link_url: Optional[AnyHttpUrl]
```

**Comment by holyoaks** [comment]
Well, I'm embarrassed. Thank you for your kind response.
