### ISSUE TITLE
Dynamically adding validator to existing model

### ISSUE THREAD

**Issue by evetion** [samuelcolvin/pydantic#2076]
# Question

I'm trying to add a validator after (non-dynamic) model creation, but it seems never to be called. Issue https://github.com/samuelcolvin/pydantic/issues/262 is similar, but for dynamic model creation.

Attached a snippet of something that I'd hoped would work. Is it possible to replace `__validators__` like this?

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
❯ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /Users/evetion/opt/miniconda3/lib/python3.7/site-packages/pydantic
               python version: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56)  [Clang 4.0.1 (tags/RELEASE_401/final)]
                     platform: Darwin-19.6.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions', 'email-validator', 'devtools']

```

```py
from pydantic.class_validators import validator
from pydantic import BaseModel


class Data(BaseModel):
    a: float

def limit_max_a(cls, value):
    if value > 50.0:
        value = 0.0

    return value

Data.__validators__ = {
    "a": [validator("a")(
        validator_maximum_water_depth
    )],
}

d = Data(a=100)
assert d.a == 0.0  # AssertionError
```

**Comment by samuelcolvin** [comment]
This isn't supported, as validators are built into fields when the model is created.

Either include the validators in the model when it's created, or use `create_model()`.

**Comment by evetion** [comment]
That's clear. Thanks for the quick reply!

**Comment by evetion** [comment]
For those interested in a (unsupported) solution:

```py
from pydantic.class_validators import Validator
from pydantic import BaseModel

class Data(BaseModel):
    a: float

def limit_max_a(cls, value):
    if value > 50.0:
        value = 0.0

    return value

Data.__fields__["a"].class_validators = {
    "a": Validator(limit_max_a)
}
Data.__fields__["a"].populate_validators()

d = Data(a=100)
assert d.a == 0.0
```

Had to go down the rabbit hole for this, but I understand pydantic a bit better now. This isn't guaranteed to work in combination with other validators and will probably require version pinning, as it uses undocumented internals.

**Comment by HansBrende** [comment]
@samuelcolvin it would be great to support this for the following use-case:

```python
@validated_by_my_reusable_validator('field_a')
class Foo(BaseModel):
    field_a: int
```

where `validated_by_my_reusable_validator` is a simple custom decorator that adds `my_reusable_validator` to the class.

Unfortunately, by the time this annotation runs, the class has already been populated and it is too late to add the validator!

The alternative, of course, is this:
```python
class Foo(BaseModel):
    field_a: int
    
    _field_that_really_doesnt_need_to_be_visible_to_IDEs = my_reusable_validator('field_a')
```

However, the second approach just feels like clutter 😢
