### ISSUE TITLE
Mapping Pydantic JSON schema to SQLAlchemy's Postgres JSON field

### ISSUE THREAD

**Issue by NAVHITS** [samuelcolvin/pydantic#2087]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question
I tried to create a rest API with FastAPI using Postgres. I use SQLAlchemy ORM. With Pydantic I create a schema and I used `JSON` field first. I then tried `dict` as JSON becomes a dictionary while while working on the data in Python. 
Then I received an error saying that the `table' was not found and I also found the table wasn't created (I use Alembic)

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
        pydantic version: 1.7.2
       pydantic compiled: True
            install path: /usr/local/lib/python3.9/site-packages/pydantic
          python version: 3.9.0 (default, Oct 27 2020, 14:15:17)  [Clang 12.0.0 (clang-1200.0.32.21)]
                platform: macOS-10.15.7-x86_64-i386-64bit
optional deps. installed: []
```
This is the Pydantic schema
```py
class User(BaseModel):
    data: dict  # Tried using "Json" module from pydantic.types
    class Config:
        orm_mode = True
```

And this is my SQLAlchemy model
```Python
from sqlalchemy.dialects.postgresql import JSON
class User(Base):
    __tablename__ = "test"
    id = Column(Integer, primary_key=True, index=True)
    data = Column(JSON)
```

Alembic was not able to create a table but the migration scripts ran without any errors. The migration file was created for me. While using `Pydantic Json` type I got an 422 error and when using `dict` I have this above issue.

**Comment by NAVHITS** [comment]
Edit: Used `Dict[Any, Any]` and now it seems to work fine for me. Let me know if this is the right way to do it.

```py
from typing import Dict,Any
class User(BaseModel):
    data: Dict[Any, Any] = None
    class Config:
        orm_mode = True
```

**Comment by NAVHITS** [comment]
Since this doesn't seem like an issue, I'm closing it now. If any of you have suggestions or comments drop them here. Might help someone :)

**Comment by StephenBrown2** [comment]
Using `Dict[Any, Any]` will work, because it allows for anything inside the Dict. Have you tried setting up a sub-model with the schema you expect to be stored in that JSON field, or is the data more free-form that doesn't necessarily always match a given schema?

**Comment by NAVHITS** [comment]
@StephenBrown2 I don't have to worry about how it comes in. It works like a MongoDB instance. Only thing I need to see is each transaction has a key and Dict. So probably I could do `Dict[str, Dict]`. Thanks for the heads up :)
