### ISSUE TITLE
Possible regression: Enum schema generation creates superfluous `allOf` when description is present

### ISSUE THREAD

**Issue by ml-evs** [samuelcolvin/pydantic#2088]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Firstly, thanks for pydantic, it's already hard to imagine working without it. We ran into a problem when updating pydantic to 1.7.1 over at https://github.com/Materials-Consortia/optimade-python-tools/pull/578 & https://github.com/Materials-Consortia/optimade-python-tools/pull/576 (cc @CasperWA).

When using an `Enum` field, the generated OpenAPI schema changes depending on whether a description has been provided for the field. In 1.6.1 this description was ignored, but in 1.7.1 this description is included, with the side effect of adding what seems like a superfluous `allOf` instead of just using the reference directly.

Please see the MWE:

```python
from enum import Enum
from typing import Optional
import json
from pydantic import BaseModel, Field
import pydantic.utils

class MyEnum(Enum):
    """Class docstring. """
    RED = "red"
    BLUE = "blue"

class MyModel(BaseModel):
    colour: Optional[MyEnum] = Field(None, description="Field desc")

if __name__ == "__main__":
    print(pydantic.utils.version_info())
    print(json.dumps(MyModel.schema(), indent=2))
```

Pydantic 1.6.1:
```
$ python mwe.py
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /home/mevans/.local/conda/envs/pydantic_17/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]
                     platform: Linux-5.4.67-1-MANJARO-x86_64-with-glibc2.10
     optional deps. installed: []
{
  "title": "MyModel",
  "type": "object",
  "properties": {
    "colour": {
      "$ref": "#/definitions/MyEnum"
    }
  },
  "definitions": {
    "MyEnum": {
      "title": "MyEnum",
      "description": "Class docstring. ",
      "enum": [
        "red",
        "blue"
      ]
    }
  }
}
```

Pydantic 1.7.1:
```
$ python mwe.py
             pydantic version: 1.7.1
            pydantic compiled: True
                 install path: /home/mevans/.local/conda/envs/pydantic_17/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]
                     platform: Linux-5.4.67-1-MANJARO-x86_64-with-glibc2.10
     optional deps. installed: []
{
  "title": "MyModel",
  "type": "object",
  "properties": {
    "colour": {
      "description": "Field desc",
      "allOf": [
        {
          "$ref": "#/definitions/MyEnum"
        }
      ]
    }
  },
  "definitions": {
    "MyEnum": {
      "title": "MyEnum",
      "description": "Class docstring. ",
      "enum": [
        "red",
        "blue"
      ]
    }
  }
}
```

Or as a diff between 1.6.1 and 1.7.1:
```diff
1c1
<              pydantic version: 1.6.1
---
>              pydantic version: 1.7.1
12c12,17
<       "$ref": "#/definitions/MyEnum"
---
>       "description": "Field desc",
>       "allOf": [
>         {
>           "$ref": "#/definitions/MyEnum"
>         }
>       ]
```

And if you delete the field description, with pydantic 1.7.1 (i.e. no `allOf`):

```shell
$ python mwe_no_desc.py
{
  "title": "MyModel",
  "type": "object",
  "properties": {
    "colour": {
      "$ref": "#/definitions/MyEnum"
    }
  },
  "definitions": {
    "MyEnum": {
      "title": "MyEnum",
      "description": "Class docstring. ",
      "enum": [
        "red",
        "blue"
      ]
    }
  }
}
```

Is there some OpenAPI/JSONSchema rule that prohibits pydantic from generating the following (or must `$ref` only appear as the only key when present)?

```json
{
  "title": "MyModel",
  "type": "object",
  "properties": {
    "colour": {
      "description": "Field desc",
      "$ref": "#/definitions/MyEnum"
    }
  },
  "definitions": {
    "MyEnum": {
      "title": "MyEnum",
      "description": "Class docstring. ",
      "enum": [
        "red",
        "blue"
      ]
    }
  }
}
```

Thanks!

**Comment by PrettyWood** [comment]
Hello @ml-evs 
Thanks for reporting. I'll have a look tomorrow night but in the meantime have you checked #1749?
Just to be sure your questions have not already been answered there.
Cheers

**Comment by ml-evs** [comment]
Thanks for the helpful response @PrettyWood, that does look like the relevant comment/commit (I guess my keywords when searching for relevant issues/PRs didn't pick this up, apologies!)

So it seems the answer can be summarized as "it works better with documentation generation tools", which is as good a reason as any. I'll have a deeper read of that thread, but will close this issue for now.

**Comment by philipbjorge** [comment]
I'm not sure if it warrants reopening the issue, but this change breaks many (most?) openapi generators.
https://github.com/OpenAPITools/openapi-generator
