### ISSUE TITLE
How to keep mypy happy using `pydantic.DirectoryPath` with a default value

### ISSUE THREAD

**Issue by michael0liver** [samuelcolvin/pydantic#2098]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.2
            pydantic compiled: True
                 install path: /Users/michaeloliver/echo/app/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.0 (default, Oct 27 2020, 14:15:17)  [Clang 12.0.0 (clang-1200.0.32.21)]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

I would like to use `DirectoryPath` with a default value if no environment override exists (using `BaseSettings`)

```py
from pathlib import Path

from pydantic import BaseSettings, DirectoryPath

BASE_DIR = Path(__file__).parent


class Config(BaseSettings):
    CONTENT_DIR: DirectoryPath = BASE_DIR / "content"

```

`mypy` complains:
```
src/hublib/config.py:8: error: Incompatible types in assignment (expression has type "Path", variable has type "DirectoryPath")
```

What would be the best approach ?

**Comment by PrettyWood** [comment]
Hello @michael0liver thanks for reporting

There are three main ways
- handle it in your code thanks to a `# type: ignore` or better with a `if TYPE_CHECKING` condition
- handle the custom types directly in _pydantic_ code
- handle the custom types in _pydantic_ `mypy` plugin

I just opened a PR with the second solution. You can add [this](https://github.com/samuelcolvin/pydantic/pull/2099/files#diff-f7a381c0918da7ec905bfbe6aff2ccc72c2d0fd6da0dd3011ef1da892e42d57aR548) directly in your code or add a `# type: ignore` in the meantime

**Comment by michael0liver** [comment]
@PrettyWood Thanks for the response 😄
