### ISSUE TITLE
Allow specifying json mapping at definition level

### ISSUE THREAD

**Issue by jasonkuhrt** [samuelcolvin/pydantic#211]
[Carried over from discussion in the first json serialization feature PR](https://github.com/samuelcolvin/pydantic/pull/210#discussion_r198862833). It quickly became clear that this is a feature beyond the scope of that PR.

The idea here is to allow specifying things like `exclude`:

```python
model.json(exclude={'foobar'})
```

At the data definition level (aka. Class):

```python
class Model(BaseModel):
  # Hypothetical API, just to make the point, not a precise API suggestion
  foobar: Optional[str] = None @json_exclude
```

Because I have an assumption that JSON mapping will typically by app-wide not ad-hoc/call-site specific. 

Inspiration:

In Go structrs can be annotated with so-called tags to create a mapping to JSON:

* https://medium.com/golangspec/tags-in-golang-3e5db0b8ef3e
* https://stackoverflow.com/questions/10858787/what-are-the-uses-for-tags-in-go

**Comment by samuelcolvin** [comment]
I think this is excessively confusing, you could add something to `Schema` like `exclude_from_output`, but if it's excluded from `json()` it should be excluded from `dict()` too, then why bother validating it at all.

If people want this feature they could implement it on a model by a `special_json()` method which calls `json(exclude={a,b,c})` this could even be defined on a alternative base class and reused.
