### ISSUE TITLE
pyinstaller question

### ISSUE THREAD

**Issue by zhaojunliing** [samuelcolvin/pydantic#2113]
pyinstaller unable to work when I improt pydantic

import pydantic

if __name__ == '__main__':
    print(pydantic.utils.version_info())

**Comment by zhaojunliing** [comment]
I use 1.4 version,python version 3.7.7,can work. 1.7.2 has quesion.

**Comment by samuelcolvin** [comment]
Please:
* Answer the questions in the issue template
* Format your issue so it's easy to read
* Give more details on what it is and how is "unable to work"

Maybe best to start again.
