### ISSUE TITLE
Add support for Visual Studio Code

### ISSUE THREAD

**Issue by MartinThoma** [samuelcolvin/pydantic#2121]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this feature/change is needed
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.2
            pydantic compiled: True
                 install path: /home/math/.pyenv/versions/3.7.8/lib/python3.7/site-packages/pydantic
               python version: 3.7.8 (default, Aug 18 2020, 10:52:32)  [GCC 9.3.0]
                     platform: Linux-4.19.104-microsoft-standard-x86_64-with-debian-bullseye-sid
     optional deps. installed: ['typing-extensions']
```

This is more of a pointer, I think, less of a feature request. At the moment, with VS Code 1.51.1 and pylance 2020.11.1, the type hints just say `**data: Any` when a pydantic object is created. It would be cool if that could be improved.

* [microsoft/vscode-python/issues/6320](https://github.com/microsoft/vscode-python/issues/6320): This sounds as if it works / worked with the default Python language server
* [microsoft/python-language-server/issues/1898](https://github.com/microsoft/python-language-server/issues/1898): This sounds as it will never happen using pylance

**Comment by PrettyWood** [comment]
Hi @MartinThoma 
You're absolutely right! It's something a lot of us want. There is actually an [opened issue](https://github.com/samuelcolvin/pydantic/issues/650) to add `BaseModel` autocompletion among other things on Pycharm (already done) and VSCode.

**Comment by MartinThoma** [comment]
Nice! Should I close this issue then?

**Comment by nzig** [comment]
Since this is the first result when googling "vscode pydantic", I'd like to link this here:
Until samuelcolvin/pydantic#2721 is merged, you can add a small snippet to pydantic to get completions. Instructions [here](https://github.com/microsoft/pyright/blob/main/specs/dataclass_transforms.md#applying-to-pydantic).
