### ISSUE TITLE
How to prevent password re-hashing on multiple model instantiations

### ISSUE THREAD

**Issue by andreixk** [samuelcolvin/pydantic#2125]
### Checks

* [X] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question

I am trying to create a user model which also hashes their password. However I'm running into a problem: if I put the same data through the model twice, it re-hashes an already hashed password. I tried setting a dynamic property on the class in the validator, but that doesn't seem to work (at least not properly). I'm probably missing some feature not using it correctly. Any help is appreciated.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.2
            pydantic compiled: True
                 install path: /private/var/www/apps/api/.env/lib/python3.8/site-packages/pydantic
               python version: 3.8.1 (default, Dec 27 2019, 18:06:00)  [Clang 11.0.0 (clang-1100.0.33.16)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['email-validator']
```

```py
from pydantic import BaseModel
from pydantic import validator
from pydantic import Field
from pydantic import EmailStr

def hash_str(text: str):
    return 'fake-hash' + text

class UserModel(BaseModel):
    email: EmailStr = Field(example='test@example.com')
    password: str = Field(min_length=3, max_length=28)
    @validator('password')
    def hash_password(cls, passw):
        # i tried doing things here like cls.__is_pass_hashed = True
        return hash_str(passw)

mock_data = {'email': 'hello@good.bye', 'password': '123'}

valid_data = UserModel(**mock_data) # password == 'fake-hash123'
second_pass = UserModel(**valid_data.dict()) # password == 'fake-hashfake-hash123'

```

**Comment by PrettyWood** [comment]
Hello @andreixk 

The thing is that you have no way when using bare strings to keep the information of "hashed" or "not hashed".
The easiest way would be to add a `__hash__` or something like this in front and use it to know if the password has actually been hashed or not.

However imo it's dangerous to do this kind of logic in validators as it can be critical. Furthermore you should be able to tell (at least in the scenarios I have in mind) whether or not you handle raw password (input validation) or hash (check with the database). Making a "do it all" class may be a bad idea here.

Anyway here is some code that could maybe help you!

```python
import binascii
import hashlib
import os

from pydantic import BaseModel, validator, Field, EmailStr


def hash_password(password: str) -> str:
    """Hash a password for storing."""
    salt = b'__hash__' + hashlib.sha256(os.urandom(60)).hexdigest().encode('ascii')
    pwdhash = hashlib.pbkdf2_hmac('sha512', password.encode('utf-8'),
                                  salt, 100000)
    pwdhash = binascii.hexlify(pwdhash)
    return (salt + pwdhash).decode('ascii')


def is_hash(pw: str) -> bool:
    return pw.startswith('__hash__') and len(pw) == 200


def verify_password(stored_password: str, provided_password: str) -> bool:
    """Verify a stored password against one provided by user"""
    salt = stored_password[:72]
    stored_password = stored_password[72:]
    pwdhash = hashlib.pbkdf2_hmac('sha512',
                                  provided_password.encode('utf-8'),
                                  salt.encode('ascii'),
                                  100000)
    pwdhash = binascii.hexlify(pwdhash).decode('ascii')
    return pwdhash == stored_password


class UserModel(BaseModel):
    email: EmailStr = Field(example='test@example.com')
    password: str

    @validator('password')
    def hash_password(cls, pw: str) -> str:
        if is_hash(pw):
            return pw
        return hash_password(pw)


mock_data = {'email': 'hello@good.bye', 'password': '123'}

valid_data = UserModel(**mock_data)  # password == 'fake-hash123'
second_pass = UserModel(**valid_data.dict())  # password == 'fake-hashfake-hash123'

print(valid_data)
print(second_pass)
```

Cheers

**Comment by andreixk** [comment]
@PrettyWood Thanks for the example. I realized later on that my design is flawed. You're 100% correct in that a 'do-it-all' is a terrible idea. It'll be either extremely complicated or prone to attacks.
