### ISSUE TITLE
Get field access statistics

### ISSUE THREAD

**Issue by kilsenp** [samuelcolvin/pydantic#2130]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [ ] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question

Hi,
thank you for this cool library. I am venturing a bit outside the scope of the common usecases for pydantic and am trying to track, how many times a field in a Model has been accessed from the outside.

```python
class User(BaseModel):
    id: int
    name = 'John Doe'
    signup_ts: Optional[datetime] = None
    friends: List[int] = []

external_data = {
    'id': '123',
    'signup_ts': '2019-06-01 12:22',
    'friends': [1, 2, '3'],
}
user = User(**external_data)

user.id #  count one up
user.id #  count one up

### And if that was also magically possible
print(user) #  don't count up
```
And then calling a `get_stats` function on `user` would return something like
```
{
    'id': 2,
    'signup_ts': 0,
    'friends': 0,
}
```

Are there any pointers how this could be achieved?
Best regards

**Comment by PrettyWood** [comment]
Hello @kilsenp 

I would do something like this (it may have an impact on performance!) to avoid overwriting the default metaclass
```python
from collections import defaultdict
from datetime import datetime
from typing import Dict, List, Optional

from pydantic import BaseModel


class User(BaseModel):
    id: int
    name = 'John Doe'
    signup_ts: Optional[datetime] = None
    friends: List[int] = []

    _field_access = defaultdict(int)

    class Config:
        underscore_attrs_are_private = True

    def __getattribute__(self, item):
        if not item.startswith('_') and item in self.__fields__:
            self._field_access[item] += 1
        return super().__getattribute__(item)

    def get_stats(self) -> Dict[str, int]:
        return dict(self._field_access)

external_data = {
    'id': '123',
    'signup_ts': '2019-06-01 12:22',
    'friends': [1, 2, '3'],
}
user = User(**external_data)

print(user.get_stats())  # {}
user.id
print(user.get_stats())  # {'id': 1}
user.id
print(user.get_stats())  # {'id': 2}
print(user)
print(user.get_stats())  # {'id': 2}
```

Hope it helps!

**Comment by kilsenp** [comment]
Awesome, thanks a lot, exactly what I was looking for!
