### ISSUE TITLE
Best practice to use pydantic as parser and validator for configs of functional python classes

### ISSUE THREAD

**Issue by tstorek** [samuelcolvin/pydantic#2146]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question

Hello, 

I am new to Pydantic and I'd like to use it within a modular framework for implementing generic functional Python classes
within an extendable framework. I'd like to give new developers of new modules all the programming flexibility python offers them. I'd like to prevent them from experiencing unexpected behavior of their modules only because they are not too familiar with Pydantic. Especially, the behavior of the BaseModel für "private_attr" and "properties" might be rather surprising to new developers. Hence, inheriting directly from pydantic.BaseModel does not seem to fit here because of the described behavior. 
After playing around with Pydantic for realizing this I tried many different things but finally came up with the workaround below.

However, I am wondering if there is no better solution to do this. Maybe I dug at the wrong places in the documentation or in the github-issues. I know that Pydantic's primary purpose is not validation, but I think that it might help to ensure valid modules in my framework that later can also be initialised from the outer scope via JSON-configs or from orm.

Environment is a wrapper of a third-party package. Here I can uses BaseClass directly but I am not sure if that is important. However, it also seems a little hacky. The interface class does not implement any pydantic related functions. I did not posted them here in order to keep the description as short as possible.

Or is it even abusive use of Pydantic?
An option that I did not try so far would be to make the whole class a pydantic.dataclass but that wouldn't give me the nixe parsing options, right?

It would be nice if someone could help out here.

Related issues: #935, #2105 and probably some more I cannot find adhoc.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:

```
pydantic version: 1.7.2
pydantic compiled: True
install path: D:\Python\anaconda3\envs\agent\Lib\site-packages\pydantic
python version: 3.8.1 (default, Jan  8 2020, 15:55:49) [MSC v.1916 64 bit (AMD64)]
platform: Windows-10-10.0.17134-SP0
optional deps. installed: ['typing-extensions']
```

```
import abc
import pydantic
import logging
from typing import Union, Optional, Any
from interface import Interface
from .datamodels import *
from .environment import Environment

class Module(Interface):
    _name: str = None
    _type: str = None
    _env: Environment = Environment()

    def __init__(self, env: Union[simpy.Environment, Environment] = None):
        self.env=env

    @property
    def env(self):
        return self._env.env

    @env.setter
    def env(self, env: Union[simpy.Environment, Environment]):
        self._env = Environment(env=env)
        self._env.process(self.process())

    @env.deleter
    def env(self):
        self.env = Environment()
```

```
class Controller(Module):
    """
    Base class for all controller tasks within an agent
    """
    class ConfigParser(PropertyBaseModel): #inherits from the solution in #935 by @ludwig-weiss
        """
        Pydantic data model for controller configuration parser
        """
        t_sample:   Union[int, float] = 1
        dt:         Union[int, float] = 1
        outputs:    Union[List[Output], Output] = []
        inputs:     Union[List[Input], Input] = []


        class Config:
            """
            Pydantic internal model settings
            """
            underscore_attrs_are_private = True
            validate_assignment = True
            arbitrary_types_allowed = True

        @validator('inputs', 'outputs')
        def check_inputs(cls, ls):
            if isinstance(ls, list):
                return ls
            elif isinstance(ls, (Input, Output)):
                return [ls]
            elif ls == None:
                return []
            else:
                raise ValidationError

    def __init__(self, env=None, t_sample: Union[int, float] = 1, dt: Union[int, float] = 1,
                 outputs: List[Output] = None, inputs: List[Input] = None):
        super().__init__(env=env)
        config=self.ConfigParser(**locals())
        for attr, value in config.dict().items():
            self.__setattr__(''.join(['_', attr]), value)

    @property
    def dt(self):
        return self._dt

    @dt.setter
    def dt(self, dt):
        self._dt = self.ConfigParser(**locals()).dt

    @dt.deleter
    def dt(self):
        self._dt=self.ConfigParser().dt

    @property
    def t_sample(self):
        return self._dt

    @t_sample.setter
    def t_sample(self, t_sample):
        self._t_sample = self.ConfigParser(**locals()).t_sample

    @t_sample.deleter
    def t_sample(self):
        self._t_sample = self.ConfigParser().t_sample
```

**Comment by SaschaSchlemmer** [comment]
I currently use something similar because I'd like to keep the surface of my classes small/ reuse dunder methods that pydantic already uses (e.g. `__iter__`)

What I do is something like this:

```python
class FieldValidationMixin:
    """Mixin class that provides validation methods to work as field in pydantic models"""

    @classmethod
    def __get_validators__(cls) -> Iterator[Callable]:
        yield cls._validate

    @classmethod
    def _validate(cls, value, **kwargs):
        if isinstance(value, cls):
            return value
        else:
            return cls(**value)  # type: ignore
```

and my functional class is then something like this:

```python
class Foo(FieldValidationMixin):  # functional class 

    class Foo(BaseModel):  # class for parsing settings goes here
        foo = ... # 

    def __init__(self, **kwargs):
        self._settings = self.Foo(**kwargs)
        
    def __iter__(self): 
         # do something with self._settings here
         
 class Bar(BaseModel):
    foo: Foo  # works 
```

**Comment by tstorek** [comment]
Thanks, for the response. As I understand you substitute my Parent class with your Mixin model. However, I am not exactly sure if I understand the rest of the code.

So that's how I understand it: 

It mostly about your class Bar. 
After adding the mixing class to 'Foo' you are now able to not only validate 'isinstance()' (which would be the cass if arbitrary types are allowed) but also return an instance of 'Foo' if 'Bar' is only given a dict of foo-settings. 

This is quite similar to the BaseModel, where I find this: 

`    @classmethod
    def __get_validators__(cls) -> 'CallableGenerator':
        yield cls.validate

    @classmethod
    def validate(cls: Type['Model'], value: Any) -> 'Model':
        if isinstance(value, dict):
            return cls(**value)
        elif isinstance(value, cls):
            return value.copy()
        elif cls.__config__.orm_mode:
            return cls.from_orm(value)
        elif cls.__custom_root_type__:
            return cls.parse_obj(value)
        else:
            try:
                value_as_dict = dict(value)
            except (TypeError, ValueError) as e:
                raise DictError() from e
            return cls(**value_as_dict)
`

Hence, this would substitute my rather silly workaround for the environment 👍 . That helps a lot with that thing, I guess.
Thank you very much. 

However, I do not exactly understand how and when __get_validators__() of the mixin-class is called.

Furthermore, I do not understand what you are doing with __iter__.

**Comment by samuelcolvin** [comment]
For `__iter__`, you might just need to do your own research, it's standard python.

For `__get_validators__` pydantic looks for this to see if a class has valuation and calls the validators returned/yielded by `__get_validators__` to parse/validate an input.

You might find it useful to read some of the code concerned with custom types in pydantic, e.g. `network.py`

**Comment by tstorek** [comment]
Well, thank you. I know that '__iter__' is from basic python ;) I was just wondering if it was interpreted by pydantic in some way, because the post said that pydantic already uses this dunder method. 

networks.py helps a lot though. I think I was too focused on the BaseModel.

To validate my inner settings-class I simply use the BaseModel? And if I want to reuse 
the whole functional class in a BaseModel, I might want to validate it as custom type, correct?

This is even more as I initially intended to do :D

@samuelcolvin Last thing: 
Can I use the CustomTypes also without the BaseModel? 
Where can I find the snippet where '__get_validators__' is called or is it too deep in the core of pydantic?

@SaschaSchlemmer  Thank you anyways :) 
@samuelcolvin Thank you for Pydantic in general! It helps a lot to keep things clean ones you understand how its magic works :) Some of the features by the community will make it even greater :). Looking forward to it.
