### ISSUE TITLE
Deserialize data with the Any type.

### ISSUE THREAD

**Issue by guibos** [samuelcolvin/pydantic#2150]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

```
pydantic version: 1.6.1
pydantic compiled: True
install path: venv/lib/python3.8/site-packages/pydantic
python version: 3.8.2 (default, Jul 16 2020, 14:00:26)  [GCC 9.3.0]
platform: Linux-5.4.0-48-generic-x86_64-with-glibc2.29
optional deps. installed: []
```

# Question
I want to serialize a Model like this:

```python
class Data(BaseModel):
    extra_fields: typing.OrderedDict[str, typing.Any]
```

```
data = Data(extra_fields=OrderedDict((('birth_date', datetime.now()), ('age', 0))))
# extra_fields={'birth_date': datetime.datetime(2020, 11, 30, 22, 59, 13, 803888), 'age': 0}

data_serialized = data.json()
# '{"extra_fields": {"birth_date": "2020-11-30T22:59:13.803888", "age": 0}}'

data_parsed = data.parse_raw(data_serialized)
# extra_fields={'birth_date': '2020-11-30T22:59:13.803888', 'age': 0}
# expected output: extra_fields={'birth_date': 'datetime.datetime(2020, 11, 30, 22, 59, 13, 803888), 'age': 0}
```
There any way to solve this problem? I think that problem is data structure but I don't find any way to solve this problem. There any way to solve with pydantic?

**Comment by PrettyWood** [comment]
Hi @guibos 
Could you please provide a full example of what you do and what you expect to have?
The goal is to help us as much as you can so we can help you as much as we can :)
Thanks

**Comment by guibos** [comment]
Hi @PrettyWood 
I updated question. Thank you very much for your attention.

**Comment by PrettyWood** [comment]
Hi again @guibos
So it's quite normal as _pydantic_ has no way to know that `'2020-11-30T22:59:13.803888'` is supposed to be parsed as a datetime. So you should just add a validator to handle it.
```python
import typing
from datetime import datetime

from pydantic import BaseModel, validator


class Data(BaseModel):
    extra_fields: typing.OrderedDict[str, typing.Any]

    @validator('extra_fields', each_item=True)
    def bibou(cls, v: typing.Any):
        try:
            return datetime.fromisoformat(v)
        except (ValueError, TypeError):
            return v

data_serialized = '{"extra_fields": {"birth_date": "2020-11-30T22:59:13.803888", "age": 0}}'
data_parsed = Data.parse_raw(data_serialized)
print(data_parsed.dict())
# {'extra_fields': {'birth_date': datetime.datetime(2020, 11, 30, 22, 59, 13, 803888), 'age': 0}}
```
Hope it helps!
