### ISSUE TITLE
Union[str, Decimal] annotation always convert Decimal to str

### ISSUE THREAD

**Issue by zen-xu** [samuelcolvin/pydantic#2156]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.2
            pydantic compiled: True
                 install path: /home/xzy/dev/airport/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Aug 18 2020, 10:14:10)  [GCC 7.4.0]
                     platform: Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.27
     optional deps. installed: []
```

```py
from pydantic import BaseModel
from decimal import Decimal
from typing import Union

class Model(BaseModel):
    v: Union[str, Decimal]

model = Model(v=Decimal("1.1"))
model.v   # '1.1' rather than Decimal('1.1')

# But change Union position is correct
class Model(BaseModel):
    v: Union[Decimal, str]

model = Model(v=Decimal("1.1"))
model.v # Decimal('1.1')
```

**Comment by PrettyWood** [comment]
Hi @zen-xu 
This is a know issue (see https://github.com/samuelcolvin/pydantic/issues/453 or https://github.com/samuelcolvin/pydantic/issues/1423)
I recently opened a PR https://github.com/samuelcolvin/pydantic/pull/2092 and am planning to work on this on my spare time.
Hope it helps
