### ISSUE TITLE
data-urls not working with AnyUrl (or any scheme without "//")

### ISSUE THREAD

**Issue by yu-ichiro** [samuelcolvin/pydantic#2157]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.2
            pydantic compiled: False
                 install path: ***masked (using poetry virtualenv)
               python version: 3.8.1 (default, May 13 2020, 21:26:33)  [Clang 11.0.3 (clang-1103.0.32.59)]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
>>> from pydantic import AnyUrl, parse_obj_as
>>> url = parse_obj_as(AnyUrl, "data:text/plain;base64,SGVsbG8sIFdvcmxkIQ%3D%3D")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "***/pydantic/tools.py", line 35, in parse_obj_as
    return model_type(__root__=obj).__root__
  File "***/pydantic/main.py", line 362, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[AnyUrl]
__root__
  invalid or missing URL scheme (type=value_error.url.scheme)
```

I know AnyUrl is being discussed in other issues but none of them mentioned this so I would like to bring it up.

**Comment by yu-ichiro** [comment]
probably most related to #1983

**Comment by samuelcolvin** [comment]
maybe related to #1983, but I think data urls are a beast of their own and probably need a custom validator.

I don't think this is really a bug as we don't say anywhere that we support data urls.

**Comment by yu-ichiro** [comment]
I guess its necessary to introduce AnyUri as a superclass of AnyUrl (or a completely different class?) which is fully compatible with [rfc3986](https://tools.ietf.org/html/rfc3986) maybe?

See, actually I didn't want to validate a DataURL specifically but wanted a more generic Url/Uri which could be parsed/loaded on a browser.

**Comment by samuelcolvin** [comment]
Sounds like a lot of work for a fairly rare usecase, could you not just use a regex and see if that's sufficient?

**Comment by yu-ichiro** [comment]
I don't know if this is a negligible usecase, but I'm doing that way currently. (Making my own URI handling class so to speak)

I guess I'll just post a gist for anyone looking for a solution and close this for now.
https://gist.github.com/yu-ichiro/ded4d704316a3b986b006467557850a4
