### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by debdutgoswami** [samuelcolvin/pydantic#2171]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

There is a typo in install snipet. it shows `pip install datamodel-code-generato`. The `r` is missing at the end.

Upon inspecting the https://github.com/samuelcolvin/pydantic/blob/master/docs/datamodel_code_generator.md I found that there is no typo in it. I built the docs on my own system using `make docs` and it worked fine. I guess I different version of the file is being served.

https://pydantic.helpmanual.io/dev/pr-1635/datamodel_code_generator/#install

**Comment by samuelcolvin** [comment]
You're not using the main docs, but instead a deploy preview of an ancient pull request:

https://pydantic-docs.helpmanual.io/datamodel_code_generator/

**Comment by debdutgoswami** [comment]
Sorry my bad. Don't know how I missed that.
