### ISSUE TITLE
Validate a value using other value

### ISSUE THREAD

**Issue by horseinthesky** [samuelcolvin/pydantic#2184]
### Checks

* [v ] I added a descriptive title to this issue
* [v ] I have searched (google, github) for similar issues and couldn't find anything
* [v ] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [v ] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.7.2
            pydantic compiled: True
                 install path: /home/horseinthesky/netinfra/fabric-automation/fabric/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
                     platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
     optional deps. installed: []
```

# Question
Hello.
Reading the documentation and googling could not provide me an answer to the question of if I can use other field's value to validate current one.

Better to see an example:
```
def interface_available(hostname, interface):
    <some logic>


class Device(BaseModel):
    asset_tag: int
    device_role: str
    tenant: str
    console_server: str
    console_server_port: str
    mgmt_switch: str
    mgmt_switch_port: str

    @validator('mgmt_switch_port')
    def _mgmt_port_fmt(cls, v):
        if not interface_available(self.mgmt_switch, v):
            raise ValueError(f'Mgmt port {v} does not exist or not available')
        return v
```
So I have a custom func which expects to get two values: mgmt switch hostname and interface name.
However if I use `self.mgmt_switch` in here I get:
```
     92     @validator('mgmt_switch_port')
     93     def _mgmt_port_fmt(cls, v):
---> 94         if not interface_available(self.mgmt_switch, v):
     95             raise ValueError(f'Mgmt port {v} does not exist or not available')
     96             # raise ValueError('mgmt port must follow the format of "GigabitEthernet0/0/[1-48]"')

NameError: name 'self' is not defined
```

Is it possible to achieve what I want? Thank you.

**Comment by PrettyWood** [comment]
Hi @horseinthesky 
The trick is to use `values` in your validators. Check the [doc](https://pydantic-docs.helpmanual.io/usage/validators/) with the example
```python
    @validator('password2')
    def passwords_match(cls, v, values, **kwargs):
        if 'password1' in values and v != values['password1']:
            raise ValueError('passwords do not match')
        return v
```

Here you just want to do the same
```python
    @validator('mgmt_switch_port')
    def _mgmt_port_fmt(cls, v: str, values: Dict[str, Any]) -> str:
        if 'mgmt_switch' in values and not interface_available(values['mgmt_switch'], v):
            raise ValueError(f'Mgmt port {v} does not exist or not available')
        return v
```
Hope it helps!

**Comment by horseinthesky** [comment]
@PrettyWood 
I've read this but misinterpreted `values` as *ValuesView* from dict.

`values` fit my scenario perfectly fine.
Thank you very much.
