### ISSUE TITLE
How to not set an attribute at all if it's not provided?

### ISSUE THREAD

**Issue by emremrah** [samuelcolvin/pydantic#2197]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question
First of all, thank a lot for this amazing library!

```python
class A(BaseModel):
    x: int
    y: Optional[str]

A(x=3).dict()  # {'y': None, 'x': 3}
```
In this example, I would like `y` not to be seen at all if it's not provided. Is it possible? Expected output is: `{'x': 3}`

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.2
            pydantic compiled: True
                 install path: /home/.../.venv38/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
                     platform: Linux-5.4.0-56-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
```

**Comment by PrettyWood** [comment]
Hi @emremrah 
The solution is in the [doc](https://pydantic-docs.helpmanual.io/usage/exporting_models/#modeldict) with the option `exclude_unset` ;)

```python
class A(BaseModel):
    x: int
    y: Optional[int]

print(A(x=3).dict(exclude_unset=True))  # {'x': 3}
print(A(x=3, y=None).dict(exclude_unset=True))  # {'x': 3, 'y': None}
print(A(x=3, y=2).dict())  # {'x': 3, 'y': 2}
```

**Comment by layday** [comment]
You might be aware, but the `Optional` type is a synonym for `Union[T, None]`; it does not mean that the attribute is optional; there's no way to annotate an attribute as being optional with type hinting in Python.  Therefore if you were to implement an `exclude_none` flag on `Field`s and the attribute were absent from model instances, your static type checker of choice would not know it.  This would result in false positives, e.g. when attempting to access a missing attribute.

**Comment by emremrah** [comment]
@layday This may not be the best but it's something, what do you think:
```python
class A(BaseModel):
    x: int
    y: Optional[int]
    z: Optional[int]
            
    def dict(self, **kwargs):
        d = super().dict(**kwargs)

        if 'exclude_none' not in kwargs or kwargs['exclude_none'] == False:
            if self.y is None:
                del d['y']

        return d  # {'x': 1, 'z': None}
```
In case we want to exclude `y` if it's none but not want to exclude `z`.

**Comment by layday** [comment]
I think I misintepreted your question, assuming that you wanted to exclude the field from the model.  As for excluding it from the dictionary, this would also work without having to override `BaseModel.dict`, depending on your requirements:

```py
(a := A(x=1, z=2)).dict(exclude={'y'} if a.y is None else set())
```

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).

**Comment by adriangb** [comment]
For what it's worth, here's my solution:

```python
import typing as t

from pydantic import BaseModel as PydanticBaseModel


class BaseModel(PydanticBaseModel):
    """Custom BaseModel that excludes fields marked with `Field(..., exclude_unset=True)`"""

    def dict(
        self,
        *,
        include: t.Union[set, dict[str, t.Any]] = None,
        exclude: t.Union[set, dict[str, t.Any]] = None,
        by_alias: bool = False,
        skip_defaults: bool = False,
        exclude_unset: bool = False,
        exclude_defaults: bool = False,
        exclude_none: bool = False,
    ) -> dict[str, t.Any]:
        d = super().dict(include=include, exclude=exclude, by_alias=by_alias, skip_defaults=skip_defaults, exclude_unset=exclude_unset, exclude_defaults=exclude_defaults, exclude_none=exclude_none)
        if exclude_unset:
            to_pop = []
            unset = d.keys() - self.__fields_set__
            for k in unset:
                field_kwgs: dict[str, t.Any] = self.__fields__[k].field_info.extra
                if field_kwgs.get("exclude_unset", False):
                    to_pop.append(k)
            for k in to_pop:
                d.pop(k)
        return d


from pydantic import Field

class A(BaseModel):
    y: t.Optional[int]
    z: t.Optional[int] = Field(exclude_unset=True)

assert A().dict() == {'y': None}
assert A(y=None).dict() == {'y': None}
assert A(y=2).dict() == {'y': 2}
assert A(z=None).dict() == {'y': None, 'z': None}
assert A(z=2).dict() == {'y': None, 'z': 2}
```
