### ISSUE TITLE
Return a Union of subclasses for a given base class

### ISSUE THREAD

**Issue by yiliev-fincad** [samuelcolvin/pydantic#2200]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [X] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question
I will explain what I would like to achieve and provide two examples and the resulting schemas.

The goal is instead of a base class to get a Union of its subclasses. 
To achieve this we can add a special attribute/method to the base class i.e. ``__collection__``.
Also, the following code change was done https://github.com/enkidulan/pydantic/pull/1/files.

However, this code is inside the `__new__`, and the function `resolve_annotations()` returns annotations only for the currently loaded module(s), hence the Union does not have all subclasses and the __field__ is incomplete. This means that in order to achieve our goal it is important how the code is structured and/or the tree of imported modules (which module is imported where).  
The following examples illustrate the issue. In Example 1 you will notice that ``AssetInstrument`` is missing from the resulting
schema, while in Example 2 it is present.  The correct behaviour should be all subclasses listed in the schema, hence the schema from example 2 is what we would like to achieve.
As the code base is in a mature state it would be impossible to make any changes, so any solution/advice/workaround is appreciated.
Thank you in advance!

* Example 1:

```py
# base_model.py
from pydantic import BaseModel

class Instrument(BaseModel):
    __collection__: bool = True # special attribute 

class ParInstrument(Instrument):
    a: int

class Trade(BaseModel):
    instrument: Instrument # I need to get Union of subclasses
```
```py
# child_model.py
from base_model import Instrument

class AssetInstrument(Instrument):
    b: float
```
```py
# parameters.py
from base_abc import Trade, BaseModel

class Parameters(BaseModel):
    model: Trade
```

* Example 2:

```py
# base_model.py
from pydantic import BaseModel

class Instrument(BaseModel):
    __collection__: bool = True # special attribute 

class ParInstrument(Instrument):
    a: int

class Trade(BaseModel):
    instrument: Instrument # I need to get Union of subclasses
```
```py
# child_model.py
from base_model import Instrument, BaseModel

class AssetInstrument(Instrument):
    b: float

class Trade(BaseModel):
    instrument: Instrument
```
```py
# parameters.py
from child_model import Trade, BaseModel

class Parameters(BaseModel):
    model: Trade
```

* __main__.py
```py
from parameters import Parameters

if __name__ == "__main__":
    print(Parameters.schema())
```

* Result from Example 1
```json
{
  "title": "Parameters",
  "type": "object",
  "properties": {
    "model": {
      "$ref": "#/definitions/Trade"
    }
  },
  "required": [
    "model"
  ],
  "definitions": {
    "ParInstrument": {
      "title": "ParInstrument",
      "type": "object",
      "properties": {
        "a": {
          "title": "A",
          "type": "integer"
        }
      },
      "required": [
        "a"
      ]
    },
    "Trade": {
      "title": "Trade",
      "type": "object",
      "properties": {
        "instrument": {
          "$ref": "#/definitions/ParInstrument"
        }
      },
      "required": [
        "instrument"
      ]
    }
  }
}
```

* Result from Example 2
```json
{
  "title": "Parameters",
  "type": "object",
  "properties": {
    "model": {
      "$ref": "#/definitions/Trade"
    }
  },
  "required": [
    "model"
  ],
  "definitions": {
    "ParInstrument": {
      "title": "ParInstrument",
      "type": "object",
      "properties": {
        "a": {
          "title": "A",
          "type": "integer"
        }
      },
      "required": [
        "a"
      ]
    },
    "AssetInstrument": {
      "title": "AssetInstrument",
      "type": "object",
      "properties": {
        "b": {
          "title": "B",
          "type": "number"
        }
      },
      "required": [
        "b"
      ]
    },
    "Trade": {
      "title": "Trade",
      "type": "object",
      "properties": {
        "instrument": {
          "title": "Instrument",
          "anyOf": [
            {
              "$ref": "#/definitions/ParInstrument"
            },
            {
              "$ref": "#/definitions/AssetInstrument"
            }
          ]
        }
      },
      "required": [
        "instrument"
      ]
    }
  }
}
```
You can notice that in the `Trade` class the  `Instrument` type is replaced by its subclasses when call the .schema(),  which is the goal.

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).

**Comment by yiliev-fincad** [comment]
I did a monkey patch, but this is not a good long term solution. For now the functionality is postponed but it will hit back at some point.

**Comment by samuelcolvin** [comment]
I really don't understand what this is about. Can you give the most minimal example possible please.

**Comment by yiliev-fincad** [comment]
This is the most simple example.
```
class BaseX:
  base: int

class DerivedA(BaseX):
  a: int

class DerivedB(BaseX):
  b: int

class Point:
  point: BaseX
```
The json representation of Point.point type needs to be substituted as: point: Union[DerivedA, DerivedB]
because BaseX doesn't give much info to the user. 
```
 "Point": {
      "title": "Point",
      "type": "object",
      "properties": {
        "point": {
          "title": Piont",
          "anyOf": [
            {
              "$ref": "#/definitions/DerivedA"
            },
            {
              "$ref": "#/definitions/DerivedB"
            }
          ]
        }
...
    }
```
We can go one level deeper when Point is a type of another class such as 
```
class Cube:
  p: Point
```

Then I would like to build a tree like structure 

Does this clarify the problem?

**Comment by bmaranville** [comment]
This is something I am wondering about too.

**Comment by yiliev-fincad** [comment]
> This is something I am wondering about too.
that would be very useful
I have a monkey patch for it but this is not the way we should go with. Our project is still under development and I am considering the idea on creating "official" branch.

**Comment by PrettyWood** [comment]
Why not just
```py
class BaseX(BaseModel):
    base: int

class DerivedA(BaseX):
    a: int

class DerivedB(BaseX):
    b: int

class Point(BaseModel):
    point: Union[tuple(BaseX.__subclasses__())]
```
?

**Comment by bmaranville** [comment]
Thanks, that works!  

I found this to be unexpected behavior because in most cases the python-typing compliance overlays the schema compliance nicely, while in this case you have to be very explicit. I just expected pydantic to pull in all subclasses to the schema because that is what the typing semantics implies, and it is non-obvious that it will deviate from the typing semantics in this case.

Also, using dynamically-generated Unions as above creates a mypy error.

**Comment by bmaranville** [comment]
I think this issue is very similar to #2036

**Comment by yiliev-fincad** [comment]
> Why not just
> 
> ```python
> class BaseX(BaseModel):
>     base: int
> 
> class DerivedA(BaseX):
>     a: int
> 
> class DerivedB(BaseX):
>     b: int
> 
> class Point(BaseModel):
>     point: Union[tuple(BaseX.__subclasses__())]
> ```
> 
> ?
That is a very valid question, which I think explained in the original post.
BaseX.__subclasses__() depends on how the files are included. Lets assume that DeriveB is in different file. 
Only class BaseX and DeriveA is imported in the file where class Point is but not DeriveB. Then the Union is incomplete.
I hope, this clarifies the issue I face
