### ISSUE TITLE
in place update with data validation 

### ISSUE THREAD

**Issue by SylvainGuieu** [samuelcolvin/pydantic#2204]
### Checks
I haven't see a builtin way to update a model in place, with data validation. Am I missing something ?

The only thing I could come with is this ugly stuff :

```py
class MyModel(BaseModel): 
    x: float = 0.0 
    y: float = 0.0 

>>> m = MyModel()  
>>> for k,v in m.parse_obj( m.copy(update={'x':4.5}) ).dict().items(): setattr(m, k, v) 
>>> m.x
4.5
...
```

a `m.update( x=4.5 )` would be nice.

**Comment by samuelcolvin** [comment]
Use `validate_assignment` on the config, then just set the property.

Example in the docs.

**Comment by SylvainGuieu** [comment]
Thanks, but if I used validate_assignment  the data will be validated all time and not in demand, which is not suitable when they are updated at high frequency from trusted source (a server in my case).

**Comment by SylvainGuieu** [comment]
This seems to be closed. However the proposed solution does not fill the requirement. 
I guess so that the feature is not wanted.

**Comment by PrettyWood** [comment]
Hi @SylvainGuieu 
I would go with something like this
```python
class MyModel(BaseModel):
    x: float = 0.0
    y: float = 0.0

    class Config:
        validate_assignment = True

    def update(self, **kwargs: Any) -> None:
        set_validate_assignment = self.__config__.validate_assignment
        try:
            self.__config__.validate_assignment = False
            for k, v in kwargs.items():
                setattr(self, k, v)
        finally:
            self.__config__.validate_assignment = set_validate_assignment
```
But it means you can indeed do `m.update(x=[0], y=123)`
Hope it helps
