### ISSUE TITLE
Deep copy of Model class

### ISSUE THREAD

**Issue by SaschaSchlemmer** [samuelcolvin/pydantic#2205]
### Checks
* [x]  I added a descriptive title to this issue
* [x]  I have searched (google, github) for similar issues and couldn't find anything
* [x]  I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [x]  After submitting this, I commit to one of:
   * Look through open issues and helped at least one other person
  * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
  * Implement a Pull Request for a confirmed bug

### Question
Is there currently a way to deep copy a model class (yes the class; not an instance)? I tried using `create_model` with some success for re-creating an already existing model but noticed that there is some functionality missing for this to make a 100% compatible copy; in particular:

- support for `root_validator` in `create_model`
- `create_model` has an argument `__base__` to specify a **single** base class for the new model (instead of a tuple of classes such as `Model.__bases__` ). I currently solve this by creating a single base class from `Model.__bases__` via `type`

My use case for this is a decorator that basically makes all fields on a model optional so that one can create a blank instance and fill it by setting its attributes (basically a more fancy version of what was requested [here](https://github.com/samuelcolvin/pydantic/issues/2152)). If anyone is interested, my current work-in-progress decorator is 

```python
def lazy_validation(cls):
    
    fields = cls.__fields__
    
    for name, field in fields.items():
        if field.required:
            field.required = False
            
            if issubclass(field.type_, BaseModel):
                
                field.type_.Config.allow_mutation = True
                field.type_.Config.validate_assignment = True
                
                lazify(field.type_) 
                field.default_factory = field.type_.construct
    return cls
```

The general idea for using this is:

```python
# import/define some regular models
class Foo(BaseModel):
    a: int
    b: int
        
class Example(BaseModel):
    first: Foo
    second: Foo
    
Data = lazy_validation(deep_copy(Example)) # create a version of the same model that is lazy about its data 

data = Data(first=dict(a='hello world))  # raises ValidationError about a not being an integer
data = Data(first=dict(a=1))   # succeeds

data.second.a = 1  # succeeds
data.second.b = 'hello world'  #raises ValidationError about b not being an integer

example = Example(**data.dict()) # raises Validation error about missing first -> b, and missing second -> b 

```

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).

**Comment by pirate** [comment]
I'm curious about this as well, I tried a solution with `.model_dump_schema()` but unfortunatley the recreated models from JSON miss out on a lot from the original types (e.g. `@properties`, private field variables, ClassVars, etc.).
