### ISSUE TITLE
Is this a decent way of incorporating non-pydantic classes and supporting serialization?

### ISSUE THREAD

**Issue by MatrixScenary** [samuelcolvin/pydantic#2215]
pydantic version: 1.7.3
            pydantic compiled: True
               python version: 3.8.5
     optional deps. installed: ['typing-extensions']

I'm trying to standardize a way to incorporate non-pydantic classes with serialization/deserialization or structuring/unstructuring (could be implemented either the wrapped or the wrapper side; I now chose the wrapper side). I know pydantic is primarily a validation/parsing library but I don't think this is far-fetched use case.

```py
import pydantic, re, textwrap

class SimpleMatch:
    """What if this class were more complex or we wouldn't want to use pydantic with it?"""
    def __init__(self, pattern, flags=None):
        self.pattern = pattern
        self.flags = flags

class SimpleMatchModel(SimpleMatch):
    """
    Let's create this model wrapper for it.
    
    Some functions could be defined in the wrapped class as well.
    """
    @classmethod
    def __get_validators__(cls):
        yield cls.valid

    @classmethod
    def valid(cls, v):
        if isinstance(v, SimpleMatch):
            return v
        elif isinstance(v, dict): # or mapping, eh
            return cls.__deserialize__(v)
        else:
            raise TypeError()

    @staticmethod
    def __serialize__(v):
        return {
            'pattern': v.pattern,
            'flags': v.flags
        }

    @staticmethod
    def __deserialize__(v):
        match = object.__new__(SimpleMatch)
        match.pattern = v['pattern']
        match.flags = v.get('flags')
        return match

    @classmethod
    def __modify_schema__(cls, field_schema):
        field_schema['description'] = 'No schema for you.'

class A(BaseModel):
    """A demonstration of non-intrusive incorporation of a type into a model."""
    simple_match: SimpleMatchModel
    class Config:
        json_encoders = {
            SimpleMatch: SimpleMatchModel.__serialize__
        }

d = dict(pattern=r'y.s\W', flags=re.I|re.A)
a = A(simple_match=d)
a2 = A(simple_match=SimpleMatch(**d))
assert d == a.simple_match.__dict__ == a2.simple_match.__dict__
assert re.search(a.simple_match.pattern, 'yEsű', flags=a.simple_match.flags)
assert A.schema_json(indent=4) == textwrap.dedent('''
    {
        "title": "A",
        "description": "A demonstration of non-intrusive incorporation of a type into a model.",
        "type": "object",
        "properties": {
            "simple_match": {
                "title": "Simple Match",
                "description": "No schema for you."
            }
        },
        "required": [
            "simple_match"
        ]
    }
''').strip()
```

My import system is dysfunctional with pydantic for some reason, so I can't comment on mypy output.

**Comment by MatrixScenary** [comment]
Come on guys, this is an important, if not essential, use case of pydantic. Sometimes you want limit the proliferation of a library like this. The best methods to achieve this must be documented or discussed.

**Comment by PrettyWood** [comment]
Hi @MatrixScenary and happy new year! (a hi never hurts am I right? 😄  )
No need for the "come on guys" tone. We do this on our spare time for free next to our actual job. Plus there are other open issues that may be more urgent than this one. If your usecase was actually essential I guess it would be known by now 😉 

---

Your solution looks good to me I don't know if this is THE solution, probably depends on your usecase. Are you looking for a generic solution? If this is just a matter of documentation I guess we could have an example with a custom type and serialization support

**Comment by MatrixScenary** [comment]
Hey, to you too; and thanks for responding! I apologize if I hit a wrong note, I directed that to the community as a whole, not just the MVPs :).

I will expose this method to a wider range of testing and survey additional approaches, I will be able to reflect only later, much later probably.

Let me though, please, briefly express myself on the essence of the issue here, namely the more explicit handling of (de)serialization by Pydantic, I'm curious if there are others that wish for this as well. As a newcomer to this library, I found a number of things quite weird. Why abstain from calling it a serialization library (alongside validation/parsing)? Clearly it's a primary use case and at least a hundred issues are just about that. To pick library component, why not be explicit around mutating and non-mutating validators? Instead of _mutating validators_ (how does this even not sound repelling) marshmallow has the `pre_load` decorator, (attrs+)cattrs has converters. According to #1984, there are plans of different sort to make this operation more explicit. Seeing more symmetry when it comes to (de)serialization would really be great. A new special member function in the model could replace the need to create a `Config` class with `json_encoders` member. 

Am I that out of sync here? Do I have my terminology mixed up? Are all those people wrong who mention Marshmallow and Pydantic in the same class? I feel as if there were more potential to this library within an arm's reach but it's being ignored. Pydantic's usage of type hints and reliance on json-schema is, in my opinion, the ultimate method to prototype serializable and validatable Python types, including dynamically if need be; with interfaces of a standardized format produced, which is HUGE.

**Comment by orf** [comment]
FYI I had a similar issue: https://github.com/samuelcolvin/pydantic/issues/2316

I took a slightly different approach here because I like having pydantic create and manage the schema for me. I created a small base type to handle Python types (and actually GRPC types as well, but that's out of scope here):

```python
PythonType = TypeVar("PythonType")

class FrameworkModel(BaseModel, Generic[PythonType]):
    PYTHON_REGISTRY: ClassVar = {}
    def __init_subclass_(cls, **kwargs):
       # Put the generic type into the registry
      ...
```

This lets me define a model like this (`CustomPointType` is a complex class inheriting from `ndarray` with an `x` and `y` property):

```python
class PointModel(FrameworkModel[CustomPointType]):
    x: int
    y: int
    
    def to_python(self) -> CustomPointType:
        return CustomPointType(x=self.x, y=self.y)

    def from_python(cls, obj: CustomPointType) -> "PointModel":
        return cls(x=obj.x, y=obj.y)
```

I then have a small method to create a model from a dataclass:

```python
def resolve_type(resolved_type: Type) -> Any:
    # Check if we have a generic type like 'Optional[MyType]`.
    # If we do, construct a new `Optional` instance replacing `MyType`
    # with any models in the model registry.
    origin = get_origin(resolved_type)
    if origin is not None:
        args = get_args(resolved_type)
        return resolved_type.copy_with(tuple(resolve_type(t) for t in args))

    if dataclasses.is_dataclass(resolved_type):
        return create_model_from_type(resolved_type.__name__, resolved_type)
    elif resolved_type in FrameworkModel.PYTHON_REGISTRY:
        return FrameworkModel.PYTHON_REGISTRY[resolved_type]
    else:
        return resolved_type

def create_model_from_type(name: str, cls: Type) -> Type[FrameworkModel]:
    fields = {}
    field: dataclasses.Field
    resolved_hints = get_type_hints(cls)
    for field in dataclasses.fields(cls):
        resolved_type = resolved_hints.get(field.name, field.type)
        default = ...
        if field.default is not dataclasses.MISSING:
            default = field.default
        fields[field.name] = (resolve_type(resolved_type), default)

    model_cls = create_model(name, __base__=DataclassWrapper, **fields)
    model_cls.FromType = cls
    return model_cls
```

Now I have bi-directional `model -> python type` and `python type -> model` conversions. But overall this is _horrible_ - I'm now working out how to correctly handle `List[NestedClass]` which will basically end up very similar to the `ModelField.validate` functions. But because they are really hard to extend nicely, this duplication seems unavoidable.

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
