### ISSUE TITLE
Validate re-declaration

### ISSUE THREAD

**Issue by ognjen-sq** [samuelcolvin/pydantic#2219]
Hello, 

I killed my self googling and reading the docs, and I couldn't find the answer/solution to the problem I am facing below. 

Say I have validator based on BaseModel

```
class MyBaseValidator(BaseModel):
    id : str = 'ID'
    
class ChildValidator(MyBaseValidator):
    some_field: str = "field1"
    some_field_2: str = "field2"

# and so on
```

Now, I'd like to have another validator that has one of the above as a sub-model

```
class BigValidator(BaseModel):
    bv_1: str = 'some_field'
    bv_2: str = 'some_other_field'
    sub_model: MyBaseValidator

class BigValidator_Child(BigValidator):
   sub_model: ChildValidator
```

Question: Is there a way to force/validate the re-declaration of the field `sub_model` in all child classes of the class `BigValidator` to allow only the children of the `MyBaseValidator` class?

P.S. I am super new to pydantic! Awesome package!

**Comment by PrettyWood** [comment]
Hi @ognjen-sq 
Using `@abc.abstractproperty` (more exactly `@property` and `@abc.abstractmethod`) doesn't really work well with _pydantic_.
Personnally if I would probably do something like this
```python
import abc
from pydantic import BaseModel


class ParentClass: ...


class ChildClass(ParentClass): ...


class ChildClass2(ParentClass): ...


class AbstractModel(BaseModel, abc.ABC):
    common: str

    class Config:
        arbitrary_types_allowed = True

    def __init_subclass__(cls, **kwargs):
        try:
            field = cls.__fields__['to_override']
        except KeyError:
            raise NotImplementedError(f'{cls.__name__} needs to set "to_override"')
        else:
            if not issubclass(field.type_, ParentClass):
                raise TypeError(f'Field "to_override" of {cls.__name__} needs to be a subclass of "ParentClass"')


class SubModel(AbstractModel):
    to_override: ChildClass


class SubModel2(AbstractModel):
    to_override: ChildClass2


SubModel(common='123', to_override=ChildClass())  # ok
```
Hope it helps!

**Comment by ognjen-sq** [comment]
Oh yes! This helped a lot! many thanks!

**Comment by PrettyWood** [comment]
Closing the issue then 😉 Happy holidays ☃️
