### ISSUE TITLE
Flatten nested model environment variables

### ISSUE THREAD

**Issue by quulah** [samuelcolvin/pydantic#2232]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [X] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question

I would like to specify my nested models' configuration using simpler, flat environment variables rather than JSON. I'm not quite sure if some of the open issues are related to this, at least #717 is quite close, I think. :)

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /home/vscode/.local/lib/python3.9/site-packages/pydantic
               python version: 3.9.1 (default, Dec 18 2020, 05:16:04)  [GCC 8.3.0]
                     platform: Linux-4.19.121-linuxkit-x86_64-with-glibc2.28
     optional deps. installed: ['typing-extensions']
```

```py
import os
from pydantic import BaseModel, BaseSettings

class Nested(BaseModel):
    text: str = "hello"

class MyConfig(BaseSettings):
    nested: Nested = Nested()

    class Config:
        env_prefix = "MY_"

os.environ["MY_NESTED_TEXT"] = "world"

config = MyConfig()

print(config.nested.text)
assert config.nested.text == "world"
```

So `os.environ["MY_NESTED_TEXT"] = "world"` rather than `os.environ["MY_NESTED"] = '{"text":"world"}'`.

I guess I could specify the env field manually on each one, but that is a bit cumbersome. Is there a more automatic way to go about this?

**Comment by daviskirk** [comment]
Right now there is no nice way of doing it as far as I know (although if there is I'd be happy to know as well). 

In fact we even built in pydantic support for our settings lib: https://github.com/daviskirk/climatecontrol#pydantic which does support this. The way that works is basically by interpreting some string (in our case "__" as the "nested" part), which you could also to yourself if you wanted.

Alternatively, you could specify the env_prefix on your nested model as well (which I think will work, and does at least on your example):

```python
from pydantic import BaseModel, BaseSettings

class Nested(BaseSettings):
    text: str = "hello"
    class Config:
        env_prefix = "MY_NESTED_"

class MyConfig(BaseSettings):
    top_level: str = "foo"
    nested: Nested = Nested()

    class Config:
        env_prefix = "MY_"

os.environ["MY_TOP_LEVEL"] = "bar"
os.environ["MY_NESTED_TEXT"] = "world"

config = MyConfig()

assert config.top_level == "bar"
assert config.nested.text == "world"
```

**Comment by quulah** [comment]
@daviskirk Thanks! Good to know I'm not alone. :)

`climatecontrol` actually looks very useful and at a first glance has a lot of things I need. I'll take a closer look.

I'd rather not set the env_prefixes on submodels / settings since I want to keep configuration things in one place and not scatter them in all of the models.

I have two ideas:

- Read all prefixed environment variables and put them into a dict delimited by `_`
  - This works, but if there's a variable with an underscore rather the value being in a nested model it fails
    - `MY_TOP_LEVEL` -> `{"top": {"level": "bar"}}` vs. `{"top_level": "bar"}`
    - This could be solved with something like the double underscores
- Flatten the Pydantic nested schema keys into a dict with a delimiter and use those keys to read environment variables directly
  - This would solve the underscores in variable names
    - But I'm unsure how I can instantiate / get the whole schema without providing a full set of data in the first place (required values, or empty defaults)
    - If there's nested models as `Optional[Nested] = None` those Nested keys are not visible using `.construct()` for example
  
  Any way, I guess I got my answer. :)
