### ISSUE TITLE
Regex Validation in Field

### ISSUE THREAD

**Issue by a-n-s** [samuelcolvin/pydantic#2241]
I have a field email as a string. I want the email to be striped of whitespace before the regex validation is applied.
```Python
from pydantic import Field
email: str = Field(..., strip_whitespace=True, regex=<EMAIL_REGEX>)
```
The <EMAIL_REGEX> doesn't handle before and trailing whitespace so I want to first strip whitespace and then the regex validation should be applied on the email variable. How should I achieve this ?

**Comment by PrettyWood** [comment]
Hi @a-n-s and happy new year!
You should use `constr` to add constraints (see the [doc](https://pydantic-docs.helpmanual.io/usage/types/#constrained-types))
```python
from pydantic import BaseModel, constr

class Test(BaseModel):
    email: constr(strip_whitespace=True, regex='\d')
```
Hope it helps!
