### ISSUE TITLE
Creating alternate field names (similar to alias) but use those only to parse input

### ISSUE THREAD

**Issue by RamiAwar** [samuelcolvin/pydantic#2247]
Hello!

I basically have an API that sends responses with different field names than the ones I'd like to use and save. For example:

API Response:  {'abcd': 'Test Name', 'efgh': 'Test City'}

I'd like to create a pydantic model that is able to create an instance from such an object, but save it as follows: {'first_name': 'Test Name', 'city': 'Test City'}

Marshmallow has such a feature called data_key, where you could specify this 'alias-like' argument:
```
# Actual marshmallow code
city = fields.Str(data_key="8pial")
```

I don't believe this is what alias is for, as it seems to save '8pial' in the database (on model serialization). My requirement is using this 'data-key' only on model interpretation.

Thanks!

**Comment by PrettyWood** [comment]
Hi
I don't understand why you say `alias` doesn't work for you
```python
from pydantic import BaseModel, Field


class User(BaseModel):
    first_name: str = Field(alias='abcd')
    city: str = Field(alias='efgh')

payload = {'abcd': 'Test Name', 'efgh': 'Test City'}
user = User(**payload)
print(repr(user))
# User(first_name='Test Name', city='Test City')
print(user.dict())
# {'first_name': 'Test Name', 'city': 'Test City'}
```
Did I not understand your question properly?

**Comment by RamiAwar** [comment]
Hmm no you did actually. It seems like I have a bug on my team's end! This makes so much more sense now thanks @PrettyWood !
