### ISSUE TITLE
How to declare fields using dashes instead of underlines

### ISSUE THREAD

**Issue by ssbarnea** [samuelcolvin/pydantic#2266]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this feature/change is needed
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Feature Request

We should have an option that allows use to map a field that can be named "foo-bar" inside the JSON file to a `foo_bar` member.

At this. moment it is not possible to produce a pydandic schema if you already have the data that uses dashes.

I am not yet sure if this should be configurable per field or generic, when the schema is generated.

**Comment by juanarrivillaga** [comment]
You can do this using:

```
from pydantic import BaseModel, Field
class Foo(BaseModel):
    valid_identifier: int = Field(alias='invalid-identifier')
```

So, as an example:

```
>>> from pydantic import BaseModel, Field
>>> class Foo(BaseModel):
...     valid_identifier: int = Field(alias='invalid-identifier')
...
>>> Foo.parse_obj({'invalid-identifier':2})
Foo(valid_identifier=2)
```

**Comment by ofek** [comment]
@samuelcolvin I think this should be reopened because the alias workaround does not work for default values, it uses the variable name instead

**Comment by odoublewen** [comment]
I agree with @ofek 

In the example above, I need `Foo.parse_obj({'invalid-identifier':2}).dict()` to return:
```
{'invalid-identifier': 0}
```

Sometimes, the dashed name really *is* the correct key, but Pydantic treats it as, well, an alias. I understand alias was written for a different use case.  I think we need an argument to `Field()` like `actual_name`, which would be honored when serializing the validated object.

**Comment by maciejmatczak** [comment]
Try the following:

```python
from pydantic import BaseModel, Field


def hyphenize(field: str):
    return field.replace("_", "-")


class MyBaseModel(BaseModel):
    class Config:
        alias_generator = hyphenize


class Foo(MyBaseModel):
    invalid_identifier: int


Foo.parse_obj({'invalid-identifier':2}).dict(by_alias=True)
```

**Comment by shi0rik0** [comment]
> I agree with @ofek
> 
> In the example above, I need `Foo.parse_obj({'invalid-identifier':2}).dict()` to return:
> 
> ```
> {'invalid-identifier': 2}
> ```
> 
> Sometimes, the dashed name really _is_ the correct key, but Pydantic treats it as, well, an alias. I understand alias was written for a different use case. I think we need an argument to `Field()` like `actual_name`, which would be honored when serializing the validated object.

In this case you can set the `by_alias` parameter, e.g., `Foo.parse_obj({'invalid-identifier':2}).dict(by_alias=True)`. Hope it helps!
