### ISSUE TITLE
Type annotation for parsable dictionary

### ISSUE THREAD

**Issue by beanaroo** [samuelcolvin/pydantic#2268]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question

Thank you for the amazing project. I've been using it successfully for configuration schemas and now I'm trying to use it for event handling too.

Is there a method for annotating anticipated dictionaries prior to them being parsed into models and/or after they are serialized from a model? Currently I've started redefining models using TypedDicts as follows:

```python
from typing import TypedDict
from pydantic import BaseModel

class UserDict(TypedDict):
    first_name: str
    last_name: str

class User(BaseModel):
    first_name: str
    last_name: str

def handle_user_event(input: UserDict) -> User:
    return User.parse_obj(input)

def emit_user_event(user: User) -> UserDict:
    return user.dict()
```
This is obviously not ideal as I'm needing to duplicate large and complex event models.

Having clear function argument type annotation is significantly better than `Dict[str, Any]` and useful for
- IDE introspection
- Generating Documentation
- Developing tests

I did come across possibly relevant https://github.com/samuelcolvin/pydantic/issues/760#issuecomment-654055651 and https://github.com/samuelcolvin/pydantic/issues/1590#issuecomment-639690519.

Is there a better way to achieve what I'm trying to do? Does this warrant a feature request? Or is this outside of the scope of the project?

**Comment by PrettyWood** [comment]
Hi @beanaroo 
I added helpers in #2216 to allow people to do the conversion manually like so
```python
from typing import TypedDict

from pydantic import typeddict_to_model


class User(TypedDict):
    name: str
    id: int


UserM = typeddict_to_model(User)
print(repr(UserM(name=123, id='3')))
# UserModel(name='123', id=3)
```
Would this solve your issue?

**Comment by beanaroo** [comment]
That's awesome, thanks @PrettyWood! I had a look at the plain `create_model` prior.

We do employ model config, custom validators, aliased fields so I'm leaning towards `TypedDict` from `BaseModel`. I do like your suggestion and I believe it would be relatively easy to make it work for nested models.

Unfortunately, as you say, it only has an affect at runtime. Until then, it's regarded as `Any` (at least by PyCharm and Mkdocstrings)

Maybe what I'm after isn't possible yet.

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
