### ISSUE TITLE
How do I create a custom Model which is recursively dependent on different classes?

### ISSUE THREAD

**Issue by kushalj001** [samuelcolvin/pydantic#2273]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer

I have a class `Document`:
```python
class Document:
   sentences: List[Sentence]
   cls_vector: np.array
   average_vector: np.array
```
 Here the `Sentence` class is another python class which has different set of properties like `List[Token]` where `Token` is yet another python class.
 I wish to create a pydantic model for the `Document` class, since I need my endpoint (FastAPI) to return a `Document` object. I cannot use `Document` as a type hint since it is not a pydantic model. 
 Is there a way to achieve this with pydantic or even FastAPI? I cannot recursively go on and create pydantic models for all classes that `Document` depends upon, like `Sentence` and then `Token` because their fields in turn have external dependencies. 
 Thank you.

**Comment by PrettyWood** [comment]
Hi @kushalj001 
Adding __get_validators__ should do the trick (see the [doc](https://pydantic-docs.helpmanual.io/usage/types/#custom-data-types))

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).
