### ISSUE TITLE
Modelling question - Feed

### ISSUE THREAD

**Issue by AntonioL** [samuelcolvin/pydantic#2275]
# Question

I have to model this kind of Feed.
Every entry is a dictionary of this kind:

```json
            "1": "0",
            "2": "2",
            "3": "A41",
            "4": "0",
            "5": "0",
            "6": "0",
            "7": "0",
```

Basically the 2nd entry defines the meaning of the rest of the values.

Like if "2" is 2 then only the 3rd entry has a meaningful value and represents a specific e-gaming player which could be modelled with something like this

```py
from pydantic import BaseModel
from enum import Enum

class Action(Enum, str):
    PLAYER = "2"

class Player(BaseModel):
    action : Action = Field(alias="2")
    player_code : str = Field(alias="3")
```

I have then a bunch of events which are esentially a pair of (action, player_code).

However if the second value is "3" let's say then the record has a totally radically different meaning.

```py
from pydantic import BaseModel
from enum import Enum

class Action(Enum, str):
    PLAYER = "2"
    SHOT = "3"

class Shot(BaseModel):
    action : Action = Field(alias="2")
    shooter : str = Field(alias="3")
    killed : str = Field(alias="4")
```

To me it looks like I am looking for something like a Variant, how can I model this?

**Comment by samuelcolvin** [comment]
you might be able to achieve this with validators or root validators, but it might also be so specific that you'd be better off writing your own logic rather than using pydantic.
