### ISSUE TITLE
enums are not json-serializable in dictionary keys

### ISSUE THREAD

**Issue by roganov** [samuelcolvin/pydantic#2278]
### Checks

* [+] I added a descriptive title to this issue
* [+] I have searched (google, github) for similar issues and couldn't find anything
* [+] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /Users/yroganov/PycharmProjects/workflow-reporting/venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.6 (default, Jan 14 2021, 13:24:20)  [Clang 12.0.0 (clang-1200.0.32.28)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']

```
Pydantic is not able to json-serialize a model when enum is used as a dictionary key.

Repro:
```py
import enum
import pydantic
import typing as t


class MyEnum(enum.Enum):
    A = 'A'


class Model(pydantic.BaseModel):
    m: t.Dict[MyEnum, str]


Model(m={MyEnum.A: 'a'}).json()
```

Expected behaviour:
Correctly serializes the enum using its value.

Actual behaviour:
`TypeError: keys must be str, int, float, bool or None, not MyEnum`

**Comment by PrettyWood** [comment]
Hi @roganov 
It's expected by _pydantic_ and I would argue it's the right behaviour.
You have at least 2 ways of doing it

- Use [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
```python
class Model(pydantic.BaseModel):
    m: t.Dict[MyEnum, str]

    class Config:
        use_enum_values = True
```

- Make your enum inherit from `str`
```python
class MyEnum(str, enum.Enum):
    A = 'A'
```

Hope it helps :)

**Comment by roganov** [comment]
Hi @PrettyWood

This sounds inconsistent. Why does this work then?
```
class ModelList(pydantic.BaseModel):
    m: t.List[MyEnum]
    
ModelList(m=[MyEnum.A]).json()
```

**Comment by PrettyWood** [comment]
You're right about the inconsistency but it's actually understandable. When you use plain python you have this
```python
import json
json.dumps({MyEnum.A: 'a'})  # TypeError: keys must be str, int, float, bool or None, not MyEnum
json.dumps({'a': MyEnum.A})   # TypeError: Object of type MyEnum is not JSON serializable
```

The first error arrives before even using a custom encoder for `json.dumps`. This is why _pydantic_ has the same error.
The second one can be prevented with a custom encoder, which _pydantic_ has to [handle by default `Enum` types](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/json.py#L29)

This is why I suggested to use `use_enum_values` to directly replace in the dictionary sent to `json.dumps` the enum value or make the Enum inherit from `str` so that `json.dumps` will understand it as a valid key.

Hope it's clearer

**Comment by roganov** [comment]
I understand why this is happening, but I still think this could be fixed for several reasons: 

1) `use_enum_values` breaks typing expectations:
```python
class Model(pydantic.BaseModel):
    m: t.Dict[MyEnum, str]

    class Config:
        use_enum_values = True


print(type(Model(m={MyEnum.A: '123'}).m.popitem()[0])) # <class 'str'>
```
2) `class MyEnum(str, enum.Enum)` works (this is what I actually went with before submitting the issue), but also suboptimal. I have to modify perfectly fine code only for serialization sake. If the enum is coming from a dependency, I can't event do that.

I understand that this is a limitation of Python's json module, but it seems there is a way to achieve custom dictionary keys serialization: https://stackoverflow.com/a/28079502.

I also understand that this approach may not work for pydantic, but in any case it's probably worth documenting this behaviour.

**Comment by PrettyWood** [comment]
@roganov I don't know I feel like it's just python and not really _pydantic_ scope but could be wrong.
The solution to your problem has nothing to do with *pydantic* per se and needs indeed a custom JsonEncoder
And the doc is [explicit](https://pydantic-docs.helpmanual.io/usage/exporting_models/#modeljson) regarding that matter: you can forward all the kwargs you want to `json.dumps`
So here
```python
import enum
import json
from pydantic import BaseModel
import typing as t


def _sanitize(o):
    if isinstance(o, dict):
        return {_sanitize(k): _sanitize(v) for k, v in o.items()}
    elif isinstance(o, (set, tuple, list)):
        return type(o)(_sanitize(x) for x in o)
    elif isinstance(o, enum.Enum):
        return o.value
    return o


class HandleKeyEnumEncoder(json.JSONEncoder):
    def encode(self, o):
        return super().encode(_sanitize(o))


class MyEnum(enum.Enum):
    A = 'A'


class Model(BaseModel):
    m: t.Dict[MyEnum, str]


print(repr(Model(m={MyEnum.A: 'a'}).json(cls=HandleKeyEnumEncoder)))  # '{"m": {"A": "a"}}'
print(repr(Model.parse_raw('{"m": {"A": "a"}}')))  # Model(m={<MyEnum.A: 'A'>: 'a'})
```
could be a solution

**Comment by roganov** [comment]
Thanks @PrettyWood, feel free to close if it's out of pydantic's scope.

**Comment by EvanSchalton** [comment]
I see this is merged, but I came across it ~a year later and thought I'd add an option for future wonderers:


pydantic uses `_get_value` when recursing to build json so adding that method to your enums allows them to be serializable by the native `Basemodel.json()` call
```
from enum import Enum as BaseEnum

class Enum(BaseEnum):
    """
    A string-able enum
    """

    def _get_value(self, **kwargs) -> str:
        return self.value
```

Here are tests to clarify expected behavior (Basemodel.dict() maintains the Enum since it doesn't naturally marshal to __primitive__ types)
```
from huedoo.utilities import Enum
from pydantic import BaseModel
import pytest
import json


class EnumTest(Enum):
    """
    Enum For Testing Purposes
    """
    A = "a"
    B = "b"
    C = "c"


class ModelTest(BaseModel):
    """
    Model for Testing Purposes
    """
    test_enum: EnumTest
    number: int


@pytest.fixture
def test_model() -> ModelTest:
    return ModelTest(
        test_enum=EnumTest.A,
        number=1
    )


def test_enum_is_enum(test_model):
    """
    The model should maintain an Enum
    """
    assert isinstance(test_model.test_enum, EnumTest)


def test_model_dict_has_enum_as_string(test_model):
    """
    The model.dict() should maintain enum
    """
    assert test_model.dict()['test_enum'] == test_model.test_enum


def test_model_json_has_enum_as_string(test_model):
    """
    The model.json() should work, unmarshal enum
    """
    assert json.loads(test_model.json())[
        'test_enum'] == test_model.test_enum.value


```

**Comment by mrkiril** [comment]
@EvanSchalton is `_get_value` is merged already ?

**Comment by aaraney** [comment]
@mrkiril, I've run into a similar issue and thanks to @EvanSchalton comments, I think I can provide a decent work around?

To your question, @mrkiril, it looks like [`_get_value`](https://github.com/pydantic/pydantic/blame/725b3c3bcf13af1cabab1e35ddf2f979cf1874fb/pydantic/main.py#L304) has been a `classmethod` on `BaseModel` for some time now (> 5 years), however it has evolved overtime. It looks like support for `Enum`s was added [here](https://github.com/pydantic/pydantic/blame/a96794ddc1d8b9101bb8dc4e1f7d1e57b0ec03c0/pydantic/main.py#L447) 2 years ago. Here is the code that I think we are concerned with:

```python
    @classmethod
    @typing.no_type_check
    def _get_value(
        cls,
        v: Any,
        to_dict: bool,
        by_alias: bool,
        include: AbstractSetIntStr | MappingIntStrAny | None,
        exclude: AbstractSetIntStr | MappingIntStrAny | None,
        exclude_unset: bool,
        exclude_defaults: bool,
        exclude_none: bool,
    ) -> Any:
    # ...
    elif isinstance(v, Enum) and getattr(cls.Config, 'use_enum_values', False):
      return v.value
```

So, it appears we should be able to override `_get_value` in a subclass of `BaseModel` and add application specific logic there to handle enums. Here is a working example:

```python
class MyEnum(enum.Enum):
    A = "A"


class Model(pydantic.BaseModel):
    m: t.Dict[MyEnum, str]
    # enum values variant also works
    n: t.Dict[str, MyEnum]

    @classmethod
    def _get_value(cls, v, *args, **kwargs) -> t.Any:
        if isinstance(v, enum.Enum):
            return v.name
        if isinstance(v, dict):
            return {
                cls._get_value(k, *args, **kwargs): cls._get_value(v, *args, **kwargs)
                for k, v in v.items()
            }
        return super()._get_value(v, *args, **kwargs)

Model(m={MyEnum.A: "a"}, n={"a": MyEnum.A}).json()

```

**Comment by aaraney** [comment]
One drawback of the above example solution is `Model(...).dict()` will return a dict where the enum key or enum values will be enum names rather than an instance of the enum (i.e. this `{'m': {'A': 'a'}, 'n': {'a': 'A'}}` instead of this `{'m': {<MyEnum.A: 'A'>: 'a'}, 'n': {'a': <MyEnum.A: 'A'>}}`). We could do something a little hacky to get around this by overriding the `json` and `_get_value` methods, but I am not so fond of this. For theses reasons, I am going with @PrettyWood's [solution](https://github.com/pydantic/pydantic/issues/2278#issuecomment-764706840) and just overriding the `json` method to set the `cls` keyword arg by default.

**Comment by mrkiril** [comment]
@aaraney in comment @EvanSchalton "_get_value" is method of "Enum" and my questions was about it. Because if your model has multiply Enum with different logic it become difficult to manage it in one "_get_value" method of model.

So I hope to see it in Enum, as write @EvanSchalton . But no.

**Comment by aaraney** [comment]
> @aaraney in comment @EvanSchalton "_get_value" is method of "Enum" and my questions was about it. Because if your model has multiply Enum with different logic it become difficult to manage it in one "_get_value" method of model.
> 
> So I hope to see it in Enum, as write @EvanSchalton . But no.

I see. @mrkiril, it sounds like [`json_encoders`](https://docs.pydantic.dev/usage/exporting_models/#json_encoders) will better handle your use case then. Here is an example:

```python
from pydantic import BaseModel
from enum import Enum


class IntEnum(Enum):
    field = 1


class TupleEnum(Enum):
    values = (1, "some value")


class Model(BaseModel):
    int_enum: IntEnum
    tuple_enum: TupleEnum

    class Config:
        json_encoders = {IntEnum: lambda v: v.name, TupleEnum: lambda v: v.value[1]}


m = Model(int_enum=IntEnum.field, tuple_enum=TupleEnum.values)
print(m.json())

>>> '{"int_enum": "field", "tuple_enum": "some value"}'
```
