### ISSUE TITLE
Possibility to access fields within fields?

### ISSUE THREAD

**Issue by jesusch** [samuelcolvin/pydantic#2280]
### Checks

* [ x] I added a descriptive title to this issue
* [ x] I have searched (google, github) for similar issues and couldn't find anything
* [ x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [ x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question

I'm trying to solve the following scenario:

```
class Settings(BaseSettings):
    env:     str = 'prod'
    bucket: str = None
```

actually I'd love to have a naming convention for bucket like `f'mybucket-{self.env}'`
I could do that via a property but then I'm loosing the availability to change the bucket via e.g. dotenv files for debugging

Any good ideas how to solve this?

**Comment by Amndeep7** [comment]
You could potentially abuse `root_validator` though I'm not sure how well that works with BaseSettings - haven't needed to use that functionality yet:

```
>>> from pydantic import BaseModel, root_validator
>>> class Test(BaseModel):
...     env: str = 'prod'
...     bucket: str = None
...     @root_validator
...     def set_bucket(cls, values):
...             e = values.get('env')
...             b = values.get('bucket')
...             if b is None:
...                     b = f'mybucket-{e}'
...             values['bucket'] = b
...             return values
...
>>> Test()
Test(env='prod', bucket='mybucket-prod')
>>> Test(env='asdf')
Test(env='asdf', bucket='mybucket-asdf')
>>> Test(env='asdf', bucket='fdsa')
Test(env='asdf', bucket='fdsa')
```

**Comment by samuelcolvin** [comment]
```py
from pydantic import BaseSettings, validator
from devtools import debug


class Settings(BaseSettings):
    env: str = 'prod'
    bucket: str = None

    @validator('bucket', always=True)
    def set_bucket(cls, v, values):
        if v is None:
            return 'mybucket-{env}'.format(**values)
        else:
            return v


debug(Settings())
debug(Settings(bucket='custom'))
```
outputs:
```
test.py:16 <module>
    Settings(): Settings(
        env='prod',
        bucket='mybucket-prod',
    ) (Settings)
test.py:17 <module>
    Settings(bucket='custom'): Settings(
        env='prod',
        bucket='custom',
    ) (Settings)
```
