### ISSUE TITLE
Passing classes leads to unexpected validation error

### ISSUE THREAD

**Issue by spacemanspiff2007** [samuelcolvin/pydantic#2292]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Validation does not work when passing classes.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
               python version: 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.18362-SP0
     optional deps. installed: []
```

Code to reproduce
```py
from pydantic import BaseModel, validator


def validate_type(obj) -> str:
    print('call validate_type')
    return str(obj)


def validate_str(obj) -> str:
    print('call validate_str')
    return str(obj)


class TestClass(BaseModel):
    type: str
    id: str
    msg: str = ''

    # validators
    _validate_type = validator('type', allow_reuse=True)(validate_type)
    _validate_id = validator('id', allow_reuse=True)(validate_str)


TestClass(type='Pass', id='id')
TestClass(type=1, id='id')
print('-' * 50)
TestClass(type=TestClass, id='id')
```

expected
```
call validate_type
call validate_str
call validate_type
call validate_str
--------------------------------------------------
call validate_type
call validate_str
```

actual output
```
call validate_type
call validate_str
call validate_type
call validate_str
--------------------------------------------------
call validate_str
Traceback (most recent call last):
  File "C:/test/my_test.py", line 27, in <module>
    TestClass(type=TestClass, id='id')
  File "pydantic\main.py", line 346, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TestClass
type
  str type expected (type=type_error.str)
```

**Comment by PrettyWood** [comment]
Hello @spacemanspiff2007 
The error is raised by `str_validator`
Maybe we could change this [here](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/validators.py#L59) even though I'm not convinced

**Comment by spacemanspiff2007** [comment]
I was under the assumption that I was adding a custom validator for the type filed with
```py
_validate_type = validator('type', allow_reuse=True)(validate_type)
```
Imho the ``str_validator`` should not be called at all.

**Comment by mpkocher** [comment]
```python
 try:
       return str(v)
    except:
       raise errors.StrError()
```

Naked exceptions should be avoided if possible. 

- https://codeandbitters.com/things-i-hate-naked-python-except/
- https://docs.python.org/3/library/exceptions.html#exception-hierarchy

**Comment by spacemanspiff2007** [comment]
> Naked exceptions should be avoided if possible.

Can you elaborate? 
I am adding a custom validator that does not raise any exception at all.
For me it's unclear where this exception is coming from.

**Comment by PrettyWood** [comment]
It was meant for me but I just wanted to suggest we can do (a) nothing, (b) add class to the tuple or (c) finish with a try...except...approach.
I didn't mean we write exactly this in the end without `TypeError` or anything. It was not my point

**Comment by mpkocher** [comment]
@spacemanspiff2007  By default, Pydantic has a strongly opinionated approach to casting before any custom validation. For example, a str type is cast using `str_validator`. This defines the core `Any -> str` casting, or will raise an exception. It's probably not a good idea for the current version of `str_validator` to become any more liberal, or change the current semantics.

However, Pydantic allows you to run your validator before the core validator(s) by using `pre=True`. This allows your custom "validator" (or more accurately, casting) to jump ahead of `str_validator`.  Below is a demo that is tweaked from your original example. As @PrettyWood has suggested, you probably want to avoid a super heavy handed casting approach and consider a more targeted `isinstance` model. 

https://pydantic-docs.helpmanual.io/usage/validators/#pre-and-per-item-validators

```python
from pydantic import BaseModel, validator


def validate_forced_to_str(obj) -> str:
    print('call validate_str')
    return str(obj)


class Record:
    pass


class TestClass(BaseModel):
    type: str
    id: str
    msg: str = ''

    _validate_type = validator('type', allow_reuse=True, pre=True)(validate_forced_to_str)


def demo():
    xs = [('Pass', 'id'), (1, 'id'), (Record, 'id')]
    for type_, id_ in xs:
        tc = TestClass(type=type_, id=id_)
        print(tc)

demo()
```

**Comment by spacemanspiff2007** [comment]
> Pydantic has a strongly opinionated approach to casting before any custom validation.

That was something I was not aware of and still think casting should not be done when using custom validators.
Anyway thank you for your help and support, I can work around with "pre".
