### ISSUE TITLE
RedisDsn.build() method can not  generate current redis_dsn

### ISSUE THREAD

**Issue by ZXiangQAQ** [samuelcolvin/pydantic#2296]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

When I use RedisDsn.build() method to generate the redis_dsn with password, it doesn't work properly.

For example:

```python
>>> from pydantic import RedisDsn

>>> RedisDsn.build(password='123456', port='6379', host='127.0.0.1', scheme='redis')
'redis://127.0.0.1:6379'

But current_dsn is 'redis://:123456@127.0.0.1:6379'
```
The password is generated only when the user parameter is not None.

```python
class RedisDsn(AnyUrl):
    allowed_schemes = {'redis'}

class AnyUrl(str):
    @classmethod
    def build(
        cls,
        *,
        scheme: str,
        user: Optional[str] = None,
        password: Optional[str] = None,
        host: str,
        port: Optional[str] = None,
        path: Optional[str] = None,
        query: Optional[str] = None,
        fragment: Optional[str] = None,
        **kwargs: str,
    ) -> str:
        url = scheme + '://'
        if user:
            url += user
            if password:
                url += ':' + password
            url += '@'
        url += host
        if port:
            url += ':' + port
        if path:
            url += path
        if query:
            url += '?' + query
        if fragment:
            url += '#' + fragment
        return url
```

But redis versions prior of Redis 6 were only able to understand the one argument version of the command: `AUTH <password>`, 

not required user parameter.

https://redis.io/commands/auth

**Comment by PrettyWood** [comment]
Hi @ZXiangQAQ 
This has already been fixed in [#1911](https://github.com/samuelcolvin/pydantic/pull/1911/files#diff-8abeeb43d603572249b3aab74cf2152ca8a929d590bb5ae7e1af913b3c66e80bR2).
This will be available in 1.8.
In the meantime you can install pydantic with the right merge commit
`pip install -U git+https://github.com/samuelcolvin/pydantic.git@aacf5920402f374069af0c80e37d4d251f418d35`
Hope it helps

**Comment by ZXiangQAQ** [comment]
Thanks! :+1:

**Comment by PrettyWood** [comment]
Closing the issue :)
