### ISSUE TITLE
RedisDsn doesn't support password

### ISSUE THREAD

**Issue by hardbyte** [samuelcolvin/pydantic#2297]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Ref https://github.com/samuelcolvin/pydantic/issues/1275

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /home/brian/.cache/pypoetry/virtualenvs/j7nrLfcR-py3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
                     platform: Linux-5.4.0-65-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions', 'email-validator']
```

Redis can be configured to require a password but not a user. The pydantic RedisDsn doesn't support this, and can't seem to be tricked by passing user as an empty string or `None`:

```py
>>> from pydantic import RedisDsn
>>> RedisDsn.build(scheme='redis', user='', password="testpass", host="host", path='')
'redis://host'
>>> RedisDsn.build(scheme='redis', user=None, password="testpass", host="host", path='')
'redis://host'
>>> RedisDsn.build(scheme='redis', password="testpass", host="host", path='')
'redis://host'
```

Expected behaviour:

```py
>>> from pydantic import RedisDsn
>>> RedisDsn.build(scheme='redis', user='', password="testpass", host="host", path='')
'redis://:testpass@host'
```

**Comment by PrettyWood** [comment]
Hi @hardbyte 
The exact same issue has been opened this morning and [answered](https://github.com/samuelcolvin/pydantic/issues/2296#issuecomment-768936443) ;)
Hope it helps!

**Comment by hardbyte** [comment]
Thanks!
