### ISSUE TITLE
Overwriting field title when dynamically creating a model

### ISSUE THREAD

**Issue by felipemmelo** [samuelcolvin/pydantic#2298]
Hi there, first of all, congrats for the awesome work!

I'm working on a project where I need to dynamically convert a Pandas dataframe to a list of Pydantic "beans", which I later dispatch as Avro. I use the `create_model()` method to generate the model.

To generate the Avro schema, I leverage the `.schema_json()` method from Pydantic models.

However, names of the fields in the resulting Json are written as titles (e.g. "CustomerKey" becomes "Customerkey"). Because of that, there is a mismatch between the names in the records and the schema.

My question: is it possible to retain the field name when using `schema_json()`. If not, is it possible to overwrite/define the title of the field when calling `create_model()`? I've searched a lot but could not find an example on how to do it.

Thanks in advance.

**Comment by PrettyWood** [comment]
Hi @felipemmelo 
You can overwrite it with the`title` kwarg passed to `Field`
```python
class Model(BaseModel):
    CustomerKey: str = Field(title='CustomerKey')
```
So with `create_model` it's the same
```python
from pydantic import create_model, Field


field_definitions = {
    'CustomerKey': str
}

MyModel = create_model('MyModel', **{
    field_name: (field_type, Field(title=field_name))
    for field_name, field_type in field_definitions.items()
})


assert MyModel.schema() == {
    'title': 'MyModel',
    'type': 'object',
    'properties': {
        'CustomerKey': {'title': 'CustomerKey', 'type': 'string'}
    },
    'required': ['CustomerKey']
}
```
Hope it helps!

**Comment by felipemmelo** [comment]
Hi @PrettyWood , definitely helped. Tks a lot!
