### ISSUE TITLE
complex types schema

### ISSUE THREAD

**Issue by majidaldo** [samuelcolvin/pydantic#230]
```
class Test(pydantic.BaseModel):
    size: List[int] =[1]
```
Why does the schema not indicate that it's an array/list is required?
```
>>> Test().schema
Test().schema_json()
'{"type": "object", "title": "Test", "properties": {"size": {"type": "int", "title": "Size", "required": false, "default": [1]}}}'


```

**Comment by Gr1N** [comment]
Because you have a default value `[1]`. Field with default can't be required.

**Comment by majidaldo** [comment]
@Gr1N  I was referring to the type. Why doesn't the type indicate that it should be an array/list of int?

**Comment by samuelcolvin** [comment]
this is a duplicate of #213, I'm going to work on a fix soon.

**Comment by Gr1N** [comment]
@majidaldo oh I see, my bad sorry.
