### ISSUE TITLE
Why do InitVar parameters not get validated + cast to their annotation like normal parameters?

### ISSUE THREAD

**Issue by Amndeep7** [samuelcolvin/pydantic#2309]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person: https://github.com/samuelcolvin/pydantic/issues/2280
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
$ poetry run python3 -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /home/amn/.cache/pypoetry/virtualenvs/works.asm.heterogeneous-groups-nPjqETfo-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.1 (default, Jan 16 2021, 13:27:01)  [GCC 9.3.0]
                     platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

Second code sample from the [initialize hooks section of the dataclasses section](https://pydantic-docs.helpmanual.io/usage/dataclasses/#initialize-hooks) with some additional lines to showcase the weirdness:
```py
from dataclasses import InitVar
from pathlib import Path
from typing import Optional

from pydantic.dataclasses import dataclass


@dataclass
class PathData:
    path: Path
    base_path: InitVar[Optional[Path]]

    def __post_init__(self, base_path):
        print(f'Received path={self.path!r}, base_path={base_path!r}')
        #> Received path='world', base_path='/hello'

    def __post_init_post_parse__(self, base_path):
        if base_path is not None:
            self.path = base_path / self.path


path_data = PathData('world', base_path='/hello')
# Received path='world', base_path='/hello'
```
If you add this line, everything goes as expected where it fails due to a type mismatch:
```
fails_on_type_validation = PathData(10, base_path='/hello')
"""
Received path=10, base_path='/hello'
Traceback (most recent call last):
  File "/home/amn/heterogeneous_groups/lib/pydantictest.py", line 30, in <module>
    path_data = PathData(10, base_path='/hello')
  File "<string>", line 4, in __init__
  File "pydantic/dataclasses.py", line 107, in pydantic.dataclasses._process_class._pydantic_post_init
    #    +--- order= parameter
pydantic.error_wrappers.ValidationError: 1 validation error for PathData
path
  value is not a valid path (type=type_error.path)
"""
```
But if you use this line instead, you fail due to ints and paths not supporting the / operator:
```
fails_at_runtime = PathData('world', base_path=10)
"""
Traceback (most recent call last):
  File "/home/amn/heterogeneous_groups/lib/pydantictest.py", line 30, in <module>
    path_data = PathData('world', base_path=10)
  File "<string>", line 4, in __init__
  File "pydantic/dataclasses.py", line 111, in pydantic.dataclasses._process_class._pydantic_post_init
    # +=======+=======+=======+
  File "/home/amn/heterogeneous_groups/lib/pydantictest.py", line 21, in __post_init_post_parse__
    self.path = base_path / self.path
TypeError: unsupported operand type(s) for /: 'int' and 'PosixPath'
"""
```
Here it throws an error right away because of the usage of this operator, but what happens if instead of division it was being added to an array?  In my actual usecase, it passed a raw dict through instead of converting it into the custom dataclass specified in the annotation; consequently, when I tried to access that variable's attributes it failed due to a dict not having those attributes.

Am I misunderstanding what InitVar is supposed to do?  I just thought it meant that that variable wouldn't become an instance variable and that it would additionally be sent to the `__post_init__` func (and `__post_init_post_parse__` func), not that it wouldn't be validated and converted into the types specified in the annotation.

**Comment by rhuille** [comment]
Hi @Amndeep7 
I agree this is not explicit in the documentation but `InitVar` are not parsed by pydantic. 

This is due to the fact the pydantic model for dataclasses is based on `dataclasses.fields`: https://github.com/samuelcolvin/pydantic/blob/master/pydantic/dataclasses.py#L147 which does not contains the `InitVar` fileds.

**Comment by Amndeep7** [comment]
@rhuille Thank you for the explanation!  Looked it up in the python stdlib documentation and [there](https://docs.python.org/3/library/dataclasses.html#dataclasses.fields) it was plain as day too.

I guess this is where this line of the documentation becomes more relevant if I don't want to manually cast things: "There are cases where subclassing pydantic.BaseModel is the better choice [over dataclasses]."
