### ISSUE TITLE
Rename field after validation (Proper way)

### ISSUE THREAD

**Issue by david-shiko** [samuelcolvin/pydantic#2310]
Hello. I come across the same [question](https://github.com/tiangolo/fastapi/issues/923#issue-555858097). I have the field `password` and want to rename it to `hashed_password` after a validation (and also change the value to a hash of the password). 
But a proposed solution anyway returns `password` field instead of `hashed_password`. 
In DB field named `hashed_password` and I'm creating a DB record like `new_user = models.User(**(user.dict()))  # user: schemas.UserLogIn`, so schemas fields must conform with db fields.

I found this solution, but is this the right way to do it?
P.S. I published this question because I think that this question will be useful to the community. If you do not agree - give me a hint, I will stop posting such (already solved) questions.

```
class UserLogIn(BaseModel):

    email: EmailStr = Field(default=..., description="email", example='dsb321mp@gmail.com')
    password: str = Field(default=..., min_length=8, max_length=64, description="pass", example='blah blah')

    @root_validator
    def password_hashing(cls, values):
        values['hashed_password'] = pwd_context.hash(values['password'])
        del values['password']
        return values
        
    class Config:
        orm_mode = True
```

**Comment by Alllrox** [comment]
Hello, David! 
1) Have you used "alias" argumet? It can be set via Field(..., alias=<alias>), on a parent model.
2) Can you set hashed password after initialization?

class UserLogIn(BaseModel):

    email: EmailStr = Field(..., description="email", example='dsb321mp@gmail.com')
    password: str = Field(..., min_length=8, max_length=64, description="pass", example='blah blah',  alias='hashed_password')
    
    class Config:
        orm_mode = True

user = UserLogIn(email = 'test@example.com', password = 'supersecret')
user.password = pwd_context.hash(user.password)

**Comment by Alllrox** [comment]
Hello, David!
1) Have you tried use aliase? You can set via Field(..., alias=<alias>), on a parent model
2) Can you hash password after initialization model?

class UserLogIn(BaseModel):

    email: EmailStr = Field(..., description="email", example='dsb321mp@gmail.com')
    password: str = Field(..., min_length=8, max_length=64, description="pass", example='blah blah',  alias = 'hashed_password')

class Config:
    orm_mode = True

user = UserLogIn(email = 'test@example.com', hashed_password = 'supersecret')
user.password = pwd_context.hash(user.password)

new_user = models.User(**(user.dict()))

**Comment by PrettyWood** [comment]
I just want to recall that
> pydantic is primarily a parsing library, not a validation library. Validation is a means to an end: building a model which conforms to the types and constraints provided.
> In other words, pydantic guarantees the types and constraints of the output model, not the input data.
> This might sound like an esoteric distinction, but it is not. If you're unsure what this means or how it might effect your usage you should read the section about Data Conversion below.

So I would personally do something like this
```py
from pydantic import BaseModel, EmailStr, Field, root_validator


class UserLogIn(BaseModel):
    email: EmailStr = Field(default=..., description="email", example='dsb321mp@gmail.com')
    hashed_password: str = Field(default=..., min_length=8, max_length=64, description="pass", example='blah blah')

    @root_validator(pre=True)
    def gen_hashed_password(cls, values):
        values['hashed_password'] = values['password'] + '__hash'
        return values


print(repr(UserLogIn.parse_obj({'email': 'pika@chu.com', 'password': 'my_pass'})))
# UserLogIn(email='pika@chu.com', hashed_password='my_pass__hash')
```

**Comment by david-shiko** [comment]
It was working for me when I removed `pre=True`. Now I can get schemes with any field names (defined in incoming schema), convert it correspond with database column names, and pass them directly to DB
