### ISSUE TITLE
Runtime type introspection in pydantic.typing.resolve_annotations() doesn't support standard collections

### ISSUE THREAD

**Issue by phinate** [samuelcolvin/pydantic#2314]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

Last one of the day, I promise :) (thanks for all your swift replies!)

In python 3.8. this is valid code:
```py
from __future__ import annotations

class A:
    x: tuple[str]
```

But if I use `BaseModel`, this fails due to runtime checks:

```py
from pydantic import BaseModel

class A(BaseModel):
    x: tuple[str]

> ~/.venvs/clarinet/lib/python3.8/site-packages/pydantic/typing.cpython-38-darwin.so in pydantic.typing.resolve_annotations()

~/opt/miniconda3/lib/python3.8/typing.py in _eval_type(t, globalns, localns)
    268     """
    269     if isinstance(t, ForwardRef):
--> 270         return t._evaluate(globalns, localns)
    271     if isinstance(t, _GenericAlias):
    272         ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)

~/opt/miniconda3/lib/python3.8/typing.py in _evaluate(self, globalns, localns)
    516                 localns = globalns
    517             self.__forward_value__ = _type_check(
--> 518                 eval(self.__forward_code__, globalns, localns),
    519                 "Forward references must evaluate to types.",
    520                 is_argument=self.__forward_is_argument__)

<string> in <module>

TypeError: 'type' object is not subscriptable
```

Is it possible to modify this to support [PEP 585](https://www.python.org/dev/peps/pep-0585/)?

**Comment by PrettyWood** [comment]
Hi @phinate 
In fact it's not possible. You are mixing two things:
- `from __future__ import annotations` means you use postponed evaluation of annotations by default, which becomes the default behaviour in python 3.10
- using builtin generics `tuple[str]` instead of `typing.Tuple[str]`, which has been added in python 3.9 and is not supported in python 3.8 by default

So when you run this on python 3.8, it crashes
```py
from __future__ import annotations

import sys
from typing import get_type_hints


class A:
    x: tuple[str]


assert sys.version_info[:2] == (3, 8)
assert A.__annotations__ == {'x': 'tuple[str]'}  # for now it's ok because the type is not evaluated directly but is invalid!
hints = get_type_hints(A)  # it tries to evaluate the annotation and it fails 
```

Running this with python 3.9 or 3.10, it works!
```py
import sys
from typing import get_args, get_origin, get_type_hints


class A:
    x: tuple[str]


assert sys.version_info >= (3, 9)
hints = get_type_hints(A)
assert hints == {'x': tuple[str]}
assert get_args(hints['x']) == (str,)
assert get_origin(hints['x']) == tuple
```

Since I had the exact same wish as you (use new generic types with python 3.8), I created [a backport](https://github.com/PrettyWood/future-typing) for python 3.6 to 3.8.
If you ever want to give it a try feedback welcome 😄

**Comment by phinate** [comment]
Thanks for the quick response again!

I would say that the code snippet from py3.8 being "not supported" feels like a misnomer -- the thing that fails here specifically is `get_type_hints`, which is a byproduct of trying to do runtime type inspection, something outside the scope of the intentions behind static typing. The class structure is definitely supported.

I do understand your point though, because pydantic does leverage this to good effect, and changing that design aspect is not something that is in your scope.

I'll keep things lightweight for now and see how far I get with py3.9 :)
