### ISSUE TITLE
Best way to iterate through a model's fields?

### ISSUE THREAD

**Issue by gdungca-fn** [samuelcolvin/pydantic#2322]
Is it through `.schema()`? I'd prefer a different representation that allows me to easily retrieve information like Python type and whether it's required. `.schema()` requires me to parse jsonschema.

For context, I'd like, given a Pydantic class, to be able to convert it to a representation required for a particular datastore.

**Comment by PrettyWood** [comment]
Hi @gdungca-fn!
Have a look at `BaseModel.__fields__`

**Comment by gdungca-fn** [comment]
@PrettyWood exactly what I needed. Thanks!
