### ISSUE TITLE
Unclear how to subclass a built-in type to add custom validation

### ISSUE THREAD

**Issue by johtso** [samuelcolvin/pydantic#2324]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: False
                 install path: ../.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.0 (default, Dec  6 2020, 19:27:10)  [Clang 12.0.0 (clang-1200.0.32.27)]
                     platform: macOS-11.0.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
from datetime import timedelta

from pydantic import BaseModel


class MillisecondTimedelta(timedelta):
    __origin__ = timedelta

    @classmethod
    def __get_validators__(cls):
        # timedelta expects seconds
        yield lambda v: v / 1000
        yield cls


class MyModel(BaseModel):
    td: MillisecondTimedelta

    class Config:
        arbitrary_types_allowed = True
data = {
    "td": 7598040,
}

print(MyModel(**data))
```

This just results in `td=datetime.timedelta(days=87, seconds=81240)`.. the custom validation isn't happening.

Also, I was surprised that I needed to specify `arbitrary_types_allowed` as I was hoping my custom type would just masquerade as `timedelta` which is normally allowed.

Am I missing something? Is there a more appropriate way to preprocess all fields of a certain type without having to explicitly add a validator for each field?

-----------------

Investigating further I've found that I can get this working by omitting `__origin__`, and instantiating the `timedelta` in the validator.

```py
class MillisecondTimedelta(timedelta):
    @classmethod
    def __get_validators__(cls):
        # timedelta expects seconds
        yield lambda v: cls(milliseconds=v)
```

Is it not possible to subclass a type and just add some validation before the usual validation?
Also, I want the resulting object to just be a `datetime.timedelta`, not my custom object. How do I get the custom validation to happen if I specify `__origin__`?

**Comment by johtso** [comment]
Investigating further I've found that I can get this working by omitting `__origin__`, and instantiating the `timedelta` in the validator.

```py
class MillisecondTimedelta(timedelta):
    @classmethod
    def __get_validators__(cls):
        # timedelta expects seconds
        yield lambda v: cls(milliseconds=v)
```

Is it not possible to subclass a type and just add some validation before the usual validation?
Also, I want the resulting object to just be a `datetime.timedelta`, not my custom object. How do I get the custom validation to happen if I specify `__origin__`?

**Comment by PrettyWood** [comment]
Hi @johtso 
How about
```py
from datetime import timedelta

from pydantic import BaseModel


class MillisecondTimedelta:
    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v: int) -> timedelta:
        # timedelta expects seconds
        return timedelta(microseconds=v)


class MyModel(BaseModel):
    td: MillisecondTimedelta


data = {
    "td": 7598040,
}

m = MyModel(**data)
assert repr(m) == 'MyModel(td=datetime.timedelta(seconds=7, microseconds=598040))'
assert isinstance(m.td, timedelta)
```

Why do you want to set `__origin__` ?

**Comment by johtso** [comment]
Ah, oops! I was shooting myself in the foot. Obviously my validator wasn't returning a `timedelta`, it was returning an instance of my subclass.

Awesome. Thanks!

In this case this approach works totally fine. But how about if I wanted to keep the default validation and just add some pre-validation?
