### ISSUE TITLE
Is it possible to map multiple top level values to a sub-model?

### ISSUE THREAD

**Issue by johtso** [samuelcolvin/pydantic#2326]
Say for example instead of having something like:

```json
{
  "description": "birthday",
  "type": "happy",
  "user":
    {
      "id": 123,
      "name": "foo"
    }
}
```
..you had something flat like:

```json
{
  "description": "birthday",
  "type": "happy",
  "user_id": 123,
  "user_name": "foo"
}
```

Is there a neat way to map those fields to your user model?

Currently the only solution I have found is to do something like this:

```python
class UserModel(BaseModel):
    id: int
    name: str

class EventModel(BaseModel):
    description: str
    type: str
    user_id: int
    user_name: str
    user: UserModel = None

    @validator('user', always=True)
    def assemble_user(cls, v, values):
        return UserModel(user_id=values['user_id'], user_name=values['user_name'])
```

This is obviously not ideal, as the field definitions end up being verbose and redundant, and you end up with extra top level fields littering your model.

Is there another way?
If not, would there be a neat way we could allow this, maybe in the Config? Basically just the idea of a field not necessarily mapping to a single field in the schema..

**Comment by PrettyWood** [comment]
Hi @johtso 
I agree it would be very useful in some situations.
Closing this issue since another one is already open https://github.com/samuelcolvin/pydantic/issues/717.
Feedback welcome
