### ISSUE TITLE
Tuple with Optional models still expects fixed length 

### ISSUE THREAD

**Issue by shubhendumadhukar** [samuelcolvin/pydantic#2332]
I am currently working with nested models which look like following:

```
class Model1(BaseModel):
    count: int

class Model2(BaseModel):
    method: str
    selector: dict
    count: int

class Final(BaseModel):
    slow: bool
    models: Tuple[
        Optional[Model1],
        Optional[Model2],
    ]]
```

I am expecting the Tuple to have a variable length since I'd like to pass in either Model1 or Model2 or both based on the requirements. However, the tuple seems to be expecting a fixed length of 2.

Please note that Union is not an option for me since I expect number of models to increase in future and the possible combinations will increase as well.

I'd appreciate any guidance.

**Comment by PrettyWood** [comment]
Hi @shubhendumadhukar 
When you write `Tuple[Optional[Model1], Optional[Model2]]`
you actually expect a tuple of length 2 with `None` or an instance of Model1 at index 0 and `None` or an instance of Model2 at index1.
I think I would simply use `Tuple[Union[Model1, Model2],...]` and then check in a validator the length and duplicates

**Comment by shubhendumadhukar** [comment]
It works perfectly. Thank you!
