### ISSUE TITLE
Field name "x" shadows a BaseModel attribute, while BaseModel does not have "x".

### ISSUE THREAD

**Issue by alexvoronov** [samuelcolvin/pydantic#2334]
### Checks

* [ x ] I added a descriptive title to this issue
* [ x ] I have searched (google, github) for similar issues and couldn't find anything
* [ x ] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [ x ] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question

I try to use an abstract class (`A`) with an abstract property (`x`), as a base class to my pydantic model `M`. However, when I provide field `x`, pydantic raises an exception that `x` is a field of BaseModel. I know I should not declare fields that are part of BaseModel (like `fields`), and aliases can resolve it, but what is the reason to disallow fields that are declared in (non-pydantic) parent classes?

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /home/kfwm779/.conda/envs/AZdock/lib/python3.7/site-packages/pydantic
               python version: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)  [GCC 7.3.0]
                     platform: Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core
     optional deps. installed: ['typing-extensions']
```

Here is the example:

```py
import pydantic
import abc


class A(abc.ABC):
    @property
    @abc.abstractmethod
    def x(self) -> str:
        pass


class M(A, pydantic.BaseModel):
    x: str = "foo"

```

This examples raises an error:
```
Traceback (most recent call last):
  File "/home/kfwm779/.conda/envs/AZdock/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-58032113f6b5>", line 12, in <module>
    class M(A, pydantic.BaseModel):
  File "pydantic/main.py", line 254, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/utils.py", line 144, in pydantic.utils.validate_field_name
NameError: Field name "x" shadows a BaseModel attribute; use a different field name with "alias='x'".
```

**Comment by samuelcolvin** [comment]
I'm not sure what the question is here, the error wording, while not perfect is pretty clear:

The `x` model on `A` and the field `x: str` on `M` conflict.

**Comment by alexvoronov** [comment]
I wonder if this conflict can be resolved by ignoring abstract properties/fields? There is no way to use `A().x` anyway. I'd really like to be able to specify an interface (minimum set of required fields) that each child model should follow.

**Comment by gdungca-fn** [comment]
@alexvoronov I think I'm looking for the same solution. I'd like to be able to define fields within an abstract base class that its children must define. I haven't been able to implement this using Pydantic and `abc`.

**Comment by gdungca-fn** [comment]
Continued the discussion here: https://github.com/samuelcolvin/pydantic/discussions/2410
