### ISSUE TITLE
Add support for TOML files in `parse_file`

### ISSUE THREAD

**Issue by gbdlin** [samuelcolvin/pydantic#2335]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this feature/change is needed
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /home/gwynbleidd/.local/share/virtualenvs/pydantic-test/lib/python3.8/site-packages/pydantic
               python version: 3.8.6 (default, Sep 25 2020, 09:36:53)  [GCC 10.2.0]
                     platform: Linux-5.8.0-41-generic-x86_64-with-glibc2.32
     optional deps. installed: []
```

# Feature Request

Allow for parsing [TOML](https://toml.io/) files directly, using `parse_file` method on pydantic model class. This feature may require additional, optional dependency to be installed (`toml` python library).

For given example TOML file:

```toml
foo = "bar"
bar = 123

[section]
name = "some_section"

[[people]]
name = "John Doe"
age = 19 
```

and models:

```py
from typing import List

from pydantic import BaseModel, Field


class Section(BaseModel):
    name: str


class Person(BaseModel):
    name: str
    age: int


class SomeData(BaseModel):
    foo: str
    bar: int
    section: Section
    people: List[Person] = Field(default_factory=list)
```

currently it is required to load file manually:

```py
import toml

with open(PATH_TO_TOML_FILE, 'r') as fd:
    data = SomeData(**toml.load(fd))
```

it should be possible to parse given TOML file:

```py
data = SomeData.parse_file(PATH_TO_TOML_FILE)
```

alternatively, if file doesnt have proper extension, it should be possible to load it, providing correct mime type:

```py
data = SomeData.parse_file(PATH_TO_TOML_FILE, content_type="application/yaml")
```

**Comment by samuelcolvin** [comment]
I'm afraid the short answer is "no".

---

**Longer answer:**

I'm definitely not touching the `toml` package, see https://github.com/samuelcolvin/pydantic/pull/2151#issuecomment-735413630 for a summary of my concerns about it.

There's [rtoml](https://github.com/samuelcolvin/rtoml) which I would argue is in a better state, but then I'm biased :-).

But the bigger problem is that I don't wan't to add another dependencies and I don't want to extend `parse_file`, see https://github.com/samuelcolvin/pydantic/issues/136#issuecomment-370232244

---

The good news is I'm working when I get a chance on another solution to this problem and others, I'll update this issue when I'm ready to announce something.

For now you'll just have to do:

```py
data = SomeData.parse_obj(toml.loads(Path('path/to/file.toml').read_text()))
```

**Comment by gbdlin** [comment]
For the dependency on the parser library - that's why I've proposed to make it optional. `toml` and `rtoml` are sharing the same API structure, at least in the scope that will be useful for the `pydantic` integration, so `pydantic` can require either of them for parsing TOML files, but...

I understand that file parsing, in current state, is somehow deprecated and it's pointless to add new file types to it, so I agree that this request is to be closed. Waiting for your announcement then :)

**Comment by ericfrederich** [comment]
Since Python 3.11 there is now official support for TOML within Python's standard library.

Could we consider re-opening this?

**Comment by samuelcolvin** [comment]
But without an external toml parser dependency, we'd have "python 3.11 only TOML parsing", which doesn't sound very appealing.

Also until a future release with a custom JSON and TOML parser, we couldn't add line numbers to errors, meaning the errors wouldn't be as good as they should be.

I have plans for a future separate library that takes care of file loading, which I think would be a better route. Hopefully, we'll get to that later this year.

**Comment by jayqi** [comment]
> without an external toml parser dependency

Python 3.11's tomllib is basically just [tomli](https://github.com/hukkin/tomli), which has zero dependencies. Personally, I think of tomli as a backport more than a typical external dependency. (Recognizing that this only addresses one of the objections.)

**Comment by Lawouach** [comment]
Hey @samuelcolvin,

So I tried to add toml as a source for pydantic_settings and pydantic v2 but I'm not clear whethere this is correct or not.
The documentation example with json is perhaps not explanatory enough.

```python
import os
from pathlib import Path
from typing import Any, Dict, Literal, Tuple, Type

import typer
from pydantic.fields import FieldInfo
from pydantic_settings import (
    BaseSettings,
    DotEnvSettingsSource,
    EnvSettingsSource,
    InitSettingsSource,
    PydanticBaseSettingsSource,
    SecretsSettingsSource,
    SettingsConfigDict,
)

class LogSection(BaseModel):
    level: Literal["debug", "info", "error", "warn", "notset"] = "info"


class TOMLConfigSettingsSource(PydanticBaseSettingsSource):
    def __init__(
        self,
        settings_cls: type[BaseSettings],
    ) -> None:
        super().__init__(settings_cls)
        self.env_vars = self._load_toml()
        print(self.env_vars)

    def get_field_value(
        self, field: FieldInfo, field_name: str
    ) -> Tuple[Any, str, bool]:
        field_value = self.env_vars.get(field_name)
        return field_value, field_name, False

    def prepare_field_value(
        self,
        field_name: str,
        field: FieldInfo,
        value: Any,
        value_is_complex: bool,
    ) -> Any:
        return value

    def __call__(self) -> Dict[str, Any]:
        d: Dict[str, Any] = {}

        for field_name, field in self.settings_cls.model_fields.items():
            field_value, field_key, value_is_complex = self.get_field_value(
                field, field_name
            )
            field_value = self.prepare_field_value(
                field_name, field, field_value, value_is_complex
            )
            if field_value is not None:
                d[field_key] = field_value

        return d

    def _load_toml(self) -> Dict[str, Any]:
        toml_file = os.getenv("CLI_CONFIG")
        if not toml_file:
            toml_file = self.config.get("toml_file")

        if not Path(toml_file).exists():
            return {}

        encoding = self.config.get("env_file_encoding")
        return tomllib.loads(Path(toml_file).read_text(encoding=encoding))


class Settings(BaseSettings):
    log: LogSection = LogSection(level="info", as_json=False)

    model_config = SettingsConfigDict(
        env_prefix="myapp_",
        env_nested_delimiter="_",
        env_file_encoding="utf-8",
        toml_file=Path(typer.get_app_dir("myapp")) / "config.toml",
    )

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: Type[BaseSettings],
        init_settings: InitSettingsSource,
        env_settings: EnvSettingsSource,
        dotenv_settings: DotEnvSettingsSource,
        file_secret_settings: SecretsSettingsSource,
    ) -> Tuple[
        InitSettingsSource,
        EnvSettingsSource,
        DotEnvSettingsSource,
        TOMLConfigSettingsSource,
        SecretsSettingsSource,
    ]:
        return (
            init_settings,
            env_settings,
            dotenv_settings,
            TOMLConfigSettingsSource(settings_cls),
            file_secret_settings,
        )
```

**Comment by fnep** [comment]
Not @samuelcolvin, but maybe I can help with this question.

There is now a separate repository for settings over here: https://github.com/pydantic/pydantic-settings

I would implement it just like this:

```python
import os
import tomllib
from pathlib import Path
from typing import Any, Dict, Literal, Tuple, Type

import typer
from pydantic import BaseModel
from pydantic.fields import FieldInfo
from pydantic_settings import (
    BaseSettings,
    DotEnvSettingsSource,
    EnvSettingsSource,
    InitSettingsSource,
    PydanticBaseSettingsSource,
    SecretsSettingsSource,
    SettingsConfigDict,
)


class LogSection(BaseModel):
    level: Literal["debug", "info", "error", "warn", "notset"] = "info"
    as_json: bool = False


class TOMLConfigSettingsSource(PydanticBaseSettingsSource):

    def get_field_value(
        self, field: FieldInfo, field_name: str
    ) -> Tuple[Any, str, bool]:
        # This is not necessary for TOML, but the current implementation
        # of PydanticBaseSettingsSource requires it. In case it becomes relevant,
        # we only raise an error to notice it.
        raise NotImplementedError

    def __call__(self) -> Dict[str, Any]:
        toml_file = os.getenv("CLI_CONFIG")
        if not toml_file:
            toml_file = self.config.get("toml_file")
        if not Path(toml_file).exists():
            return {}
        encoding = self.config.get("env_file_encoding")
        return tomllib.loads(Path(toml_file).read_text(encoding=encoding))


class Settings(BaseSettings):
    log: LogSection = LogSection(level="info", as_json=False)

    model_config = SettingsConfigDict(
        env_prefix="myapp_",
        env_nested_delimiter="_",
        env_file_encoding="utf-8",
        toml_file=Path(typer.get_app_dir("myapp")) / "config.toml",
    )

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: Type[BaseSettings],
        init_settings: InitSettingsSource,
        env_settings: EnvSettingsSource,
        dotenv_settings: DotEnvSettingsSource,
        file_secret_settings: SecretsSettingsSource,
    ) -> Tuple[
        InitSettingsSource,
        EnvSettingsSource,
        DotEnvSettingsSource,
        TOMLConfigSettingsSource,
        SecretsSettingsSource,
    ]:
        return (
            init_settings,
            env_settings,
            dotenv_settings,
            TOMLConfigSettingsSource(settings_cls),
            file_secret_settings,
        )


print(Settings())
```

I had a discussion there yesterday about the same uncertainties. https://github.com/pydantic/pydantic-settings/issues/102

From my understanding, the `get_field_value` / `prepare_field_value` are mostly for interpreting types for the `EnvSettingsSource` (in case they are complex or not it is parsed via JSON or not) and its siblings, where everything is a flat string and needs to be converted to a dict or a list, maybe. For TOML this is probably not necessary. So just like the `InitSettingsSource`, the `get_field_value` is not used. I prefer to not return it empty, so you at least notice if this implementation changes. 

Hope this helps or you can get the relevant bit from the other issue.

**Comment by Lawouach** [comment]
Appreciated the feedback. I will bring your ideas into my code and see how this pans out :)

**Comment by hramezani** [comment]
Actually, `get_field_value` is for fetching the value for the field, and `prepare_field_value` is for parsing the field's value.
In the case of envs, `get_field_value` fetch the string value for the field from environment variables, and `prepare_field_value` parse the value for list, dict, and other complex fields. 

So, for `TOML` file source, we may see it like `InitSettingsSource` as @fnep mentioned. because the loaded value from toml file is parsed by the toml library.

If you need to parse the loaded value by `tomllib.loads`, you need to go with `get_field_value`/ `prepare_field_value` approach.

**Comment by kinuax** [comment]
In case someone arrives here, `pydantic-settings` 2.2.0+ supports TOML files via `TomlConfigSettingsSource`, as explained here: https://docs.pydantic.dev/latest/concepts/pydantic_settings/#other-settings-source

**Comment by gaversano-irco** [comment]
> In case someone arrives here, `pydantic-settings` 2.2.0+ supports TOML files via `TomlConfigSettingsSource`, as explained here: https://docs.pydantic.dev/latest/concepts/pydantic_settings/#other-settings-source

Tried to execute the code in the example and got:

```
ValidationError: 2 validation errors for Settings
foobar
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
nested
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
```
