### ISSUE TITLE
Object of type 'NameEmail' is not JSON serializable

### ISSUE THREAD

**Issue by gjcarneiro** [samuelcolvin/pydantic#2341]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /app/env/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
                     platform: Linux-5.8.0-43-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions', 'email-validator']

```

This issue was mentioned in #462, but was only solved for the case of SecretStr, NameEmail was left unsolved.

```py
import pydantic

class MyModel(pydantic.BaseModel):
    email: pydantic.NameEmail

MyModel(email="foo <zzz@bar.com>").json()
```
I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 506, in pydantic.main.BaseModel.json
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "pydantic/json.py", line 65, in pydantic.json.pydantic_encoder
TypeError: Object of type 'NameEmail' is not JSON serializable
```

**Comment by samuelcolvin** [comment]
Thanks for reporting. Amazing this has never come up before.

Should be relatively simple to fix in [`pydantic/json.py`](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/json.py), the only tricky thing is dealing with conditional imports.

**Comment by alecgerona** [comment]
@samuelcolvin hey I'm trying to fix this bug and I'm encountering the tricky conditional imports thing. Would it be easier to move `NameEmail` to `pydantic/types.py` like `SecretStr`?

**Comment by samuelcolvin** [comment]
Humm, I would prefer not to.

What is the problem? network.py shouldn't import json.py

**Comment by alecgerona** [comment]
I got it to work. @gjcarneiro @samuelcolvin my PR's ready. #2479
