### ISSUE TITLE
Access validator wrapper fields in validator function

### ISSUE THREAD

**Issue by MarcMueltin** [samuelcolvin/pydantic#2344]
Hi, 

I am trying to find a way to access the fields in the validator wrapper so I can avoid duplicating code. Here's the scenario:
I have a class based on BaseModel which contains bytes fields that represent percentage values from 0 to 100 ('soc' = state of charge). I wrote a validator function to check that the provided byte value is between 0 and 100. 

```
@validator('current_soc', 'minimum_soc', 'target_soc', allow_reuse=True)
def soc_value_range(cls, value):
    if validate_bytes_value_range([the validator field name], value, 0, 100):
        return value
```

The validate_bytes_value_range function takes 4 parameters as input: the field name, the given value, the minimum allowed value and the maximum allowed value, as I'm resuing that validator function in several places. 

Now instead of repeating the `def soc_value_range(cls, value)` function three times, each time with a different soc field (so I can put that field name as the first parameter for validate_bytes_value_range), I'd like to somehow access each field of `@validator('current_soc', 'minimum_soc', 'target_soc', allow_reuse=True)`. It just seems more elegant to me. 

Is there such a solution or do I really need to repeat the code for each field, given that I want the error message to reflect the field name for clarity's sake?

**Comment by PrettyWood** [comment]
Hi @MarcMueltin 
Quoting the [doc](https://pydantic-docs.helpmanual.io/usage/validators/)
```
you can also add any subset of the following arguments to the signature (the names must match):

    values: a dict containing the name-to-value mapping of any previously-validated fields
    config: the model config
    field: the field being validated
```

So in your case you can use `field.name` (or `field.alias` if needed)
```py
@validator('current_soc', 'minimum_soc', 'target_soc', allow_reuse=True)
def soc_value_range(cls, value, field):
    if validate_bytes_value_range(field.name, value, 0, 100):
        return value
    ...
```
Hope it helps!

**Comment by MarcMueltin** [comment]
Thank you so much @PrettyWood for the quick and crystal clear answer! Sorry, but I must have overlooked that part of the documentation somehow.
