### ISSUE TITLE
Utility types that 1) check for equality, 2) validate against lambdas 

### ISSUE THREAD

**Issue by Tor1mo** [samuelcolvin/pydantic#235]
I've experimented with a few functions/classes that extend the annotation capabilities. In particular, I present two functions and examples of their use: one is for validating that field values are equal to some specified value; the other one takes a function and checks if the function, when executed with the value of the field as its argument, returns a truthy value 

```
def Eq(value):
	class Eq:
		@classmethod
		def get_validators(cls):
			def validate(cls, v):
				if v == value:
					return v
				else:
					raise ValueError(f" the value `{value}` is not equal to `{v}`")
			yield validate
	return Eq

def Fu(func):
	class Fu:
		@classmethod
		def get_validators(cls):
			def validate(cls, v):
				try:
					result = func(v)
				except:
					raise ValueError("Exception while executing the annotated function")
				else:
					if result:
						return v
					else:
						raise ValueError(f"Annotated function returned `{v}`, which is falsy")
			yield validate
	return Fu

```

and then

```

class T(BaseModel):
	a: Eq('abc')
	b: Fu(lambda val: val > 10)

T.validate({'a':'abcz', 'b':10})
```
```
pydantic.error_wrappers.ValidationError: 2 validation errors
a
   the value `abc` is not equal to `abcz` (type=value_error)
b
  Annotated function returned `False`, which is falsy (type=value_error)

```

**Comment by samuelcolvin** [comment]
I'm not sure what the feature request or question is here? 

Looks like what you have here works fine, although I would say it's less pythonic than normal [validators](https://pydantic-docs.helpmanual.io/#validators).

Also, your code would be much easier to read if you used 4 spaces (the norm in python) rather than tabs for indentation.
