### ISSUE TITLE
Exotic type for urls validation

### ISSUE THREAD

**Issue by Gr1N** [samuelcolvin/pydantic#236]
Hi,

In my projects I need to validate URLs. And I think that it's good to have such type in `pydantic` and I can port URLs validation logic from Django project. 

@samuelcolvin what do you think?

**Comment by samuelcolvin** [comment]
:+1: 

But are you sure we can't use stdlib urlparse? 

A lot of django's extra stuff came about because it predated the equivalent feature in the stdlib; then they couldn't replace with the stdlib version as their's was slightly different.

**Comment by Gr1N** [comment]
We will use stdlib, but there a lot of extra stuff for example for IPv4 or IPv6. I can also look how URL validation implemented for example in `marshmallow`.

Below list of implementations I like:
- https://github.com/django/django/blob/master/django/core/validators.py#L74
- https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/validate.py#L37

**Comment by samuelcolvin** [comment]
There's also trafaret https://github.com/Deepwalker/trafaret/blob/master/trafaret/internet.py

I have no idea which is best.

**Comment by Gr1N** [comment]
I will try to review all of this first. I think we need something simple to support but useful for projects.
