### ISSUE TITLE
Wrong error raised for invalid dict data

### ISSUE THREAD

**Issue by sisarolo** [samuelcolvin/pydantic#2362]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: ../python3.8/site-packages/pydantic
               python version: 3.8.7 (default, Dec 21 2020, 20:10:35)  [GCC 7.5.0]
                     platform: Linux-4.15.0-135-generic-x86_64-with-glibc2.27
     optional deps. installed: []
```

In the following code snippet, you can see that the error message for invalid dict data (e.g. if it is wrapped within a list) might not be correct. I would like to handle such errors in user input data (which can be intentionally or accidentally wrong) and want to point to the corresponding error source location. But as you can see in the last case of the code snippet, the error would be misleading. It should be detected as invalid dictionary or am I wrong?

```py
from pydantic import BaseModel, ValidationError

class A(BaseModel):
    foo: str
    bar: str

class B(BaseModel):
    data: A

# valid dict data -> no errors
data = {'data': {'foo': 'Foo', 'bar': 'Bar'}}
B(**data)

# invalid dict data -> error message is correct
try:
    data = {'data': [{'foo': 'Foo'}]}
    B(**data)
except ValidationError as e:
    print(e)
    """
    1 validation error for B
    data
      value is not a valid dict (type=type_error.dict)
    """

# invalid dict data -> error message is not correct
try:
    data = {'data': [{'foo': 'Foo', 'bar': 'Bar'}]}
    B(**data)
except ValidationError as e:
    print(e)
    """
    1 validation error for B
    data -> bar
      field required (type=value_error.missing)
    """
```

**Comment by PrettyWood** [comment]
Hi @sisarolo 
The issue comes from the way `dict` is validated. Since pydantic is fine with coercing, it tries to call `dict()` on the object.
In your case `dict([{'foo': 'Foo'}])` raises an error but `dict([{'foo': 'Foo', 'bar': 'Bar'}])` is valid for python and gives `{'foo': 'bar'}` hence the error after.
This will change in v2. See https://github.com/samuelcolvin/pydantic/pull/2211 and the related issues.
