### ISSUE TITLE
Empty model when using cython

### ISSUE THREAD

**Issue by WarKaa** [samuelcolvin/pydantic#2373]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: C:\GitLab-Runner\builds\pQrpa1tV\0\ATP\fgui-web\fcli\lib\site-packages\pydantic
               python version: 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.14393-SP0
     optional deps. installed: ['typing-extensions']
```

```py
from pydantic import BaseModel


class I18n(BaseModel):
    en: str

obj = I18n(en="test")

print(obj)           # empty output
print(obj.dict())    # {}
print(type(obj))     # <class 'I18n'>

```

I have not found any issue related to this problem. I only managed to reproduce this behaviour when I compile my package with cython.

Is this the expected behaviour of pydantic with cython?
Is this a cython bug?

Thank you in advance for your help

**Comment by samuelcolvin** [comment]
Sadly cython strips annotations, hence the class being empty, see https://github.com/samuelcolvin/pydantic/issues/1162#issuecomment-621962027
