### ISSUE TITLE
Cannot pickle GenericModel with Nested GenericModel field

### ISSUE THREAD

**Issue by tfwillems** [samuelcolvin/pydantic#2377]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
 pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /cluster/home/willems/.local/lib/python3.9/site-packages/pydantic
               python version: 3.9.1 (default, Dec  8 2020, 10:15:57)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
                     platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-glibc2.17
     optional deps. installed: ['typing-extensions']
```

First off, thank you as always for creating a fantastic package!

While expanding on one of the *GenericModel* examples in the [documentation](https://pydantic-docs.helpmanual.io/usage/models/#generic-models), I tried to *pickle* a GenericModel instance that contains another GenericModel as a field.

```py
### Code from docs starts here
import pickle
import pydantic

from typing import Generic, TypeVar

from pydantic import BaseModel, ValidationError
from pydantic.generics import GenericModel

T = TypeVar('T')


class InnerT(GenericModel, Generic[T]):
    inner: T


class OuterT(GenericModel, Generic[T]):
    outer: T
    nested: InnerT[T]


nested = InnerT[int](inner=1)
print(OuterT[int](outer=1, nested=nested))
### Code from docs ends here

pickle.dumps(OuterT[int](outer=1, nested = InnerT(inner=11)))
# Results in the following error _pickle.PicklingError:
# Can't pickle <class 'pydantic.generics.InnerT[T][int]'>: attribute lookup InnerT[T][int] on pydantic.generics failed
```

Dill also fails to pickle but with a slightly different error message:
```py
import dill
dill.dumps(OuterT[int](outer=1, nested = InnerT(inner=11)))
# Results in the following error: _pickle.PicklingError:
# Can't pickle <class 'pydantic.generics.Config'>: it's not found as pydantic.generics.Config
```

However, pickling a GenericModel with a nested BaseModel seems to work just fine:
```py
T = TypeVar('T')

class Inner(BaseModel):
    inner: int = 11

class OuterT2(GenericModel, Generic[T]):
    outer: T
    nested: Inner

pickle.dumps(OuterT2[int](outer=1, nested=Inner(inner=11)))
# b'\x80\x04\x95\xb0\x00\x00\x00\x00\x00\x00\x00\x8c\x08__main__\x94\x8c\x0cOuterT2[int]\x94\x93\x94)\x81\x94}\x94(\x8c\x08__dict__\x94}\x94(\x8c\x05outer\x94K\x01\x8c\x06nested\x94h\x00\x8c\x05Inner\x94\x93\x94)\x81\x94}\x94(h\x05}\x94\x8c\x05inner\x94K\x0bs\x8c\x0e__fields_set__\x94\x8f\x94(h\x0e\x90\x8c\x1c__private_attribute_values__\x94}\x94ubuh\x0f\x8f\x94(h\x08h\x07\x90h\x11}\x94ub.'
```

I suspect this has something to do with the dynamic nature of GenericModels, but I'd love to know if there's a potential fix!

Thanks!
Thomas

**Comment by daviskirk** [comment]
So I'm not sure if this is just me, but if you take the very first example and just run in in a clean process it actually works, with the result being:

```python
In [4]: pickle.dumps(OuterT[int](outer=1, nested = InnerT(inner=11)))
Out[4]: b'\x80\x04\x95\xb5\x00\x00\x00\x00\x00\x00\x00\x8c\x08__main__\x94\x8c\x0bOuterT[int]\x94\x93\x94)\x81\x94}\x94(\x8c\x08__dict__\x94}\x94(\x8c\x05outer\x94K\x01\x8c\x06nested\x94h\x00\x8c\x0bInnerT[int]\x94\x93\x94)\x81\x94}\x94(h\x05}\x94\x8c\x05inner\x94K\x0bs\x8c\x0e__fields_set__\x94\x8f\x94(h\x0e\x90\x8c\x1c__private_attribute_values__\x94}\x94ubuh\x0f\x8f\x94(h\x07h\x08\x90h\x11}\x94ub.'
```

could you try running it on the current master and see if it works?

**Comment by tfwillems** [comment]
@daviskirk Upgrading from pydantic version *1.7.3* to *1.8* seems to have resolved this issue for me as well, so I'll go ahead and close this issue. Thanks for flagging that this has been fixed!

**Comment by lucas-landreau** [comment]
Hello, the same problem is occuring for me with pydantic v1.10.2 ... Can anyone confirm this ?
