### ISSUE TITLE
Nested Model Does Not Work in A Function Scope Or with `from __future__ import annotations`

### ISSUE THREAD

**Issue by Congee** [samuelcolvin/pydantic#2411]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
       pydantic version: 1.7.3
      pydantic compiled: True
           install path: /home/cwu/.cache/pypoetry/virtualenvs/magic-GqpcoQ51-py3.8/lib/python3.8/site-packages/pydantic
         python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
               platform: Linux-5.8.0-44-generic-x86_64-with-glibc2.29
optional deps. installed: ['typing-extensions', 'email-validator']

```

```py
from __future__ import annotations

from pydantic import BaseModel, Field

def main():
  class Nested(BaseModel):
      name_nested: str = Field(alias='nameNested')

  class M(BaseModel):
      nested: Nested  # delay via 'Nested' does not help in any case

  m = M.parse_obj({'NamEStr': 'dd', 'nested': {'nameNested': ''}})
  print(m)

main()
```
This snippet outputs an error
> pydantic.errors.ConfigError: field "nested" not yet prepared so type is still a ForwardRef, you might need to call M.update_forward_refs().

It is interesting that if I move the function body to the module scope, no error; If I remove the top line `from __future__ annotations`, no error.

I guess this is still a corner case of https://github.com/samuelcolvin/pydantic/issues/1736 and https://github.com/samuelcolvin/pydantic/issues/1668

**Comment by PrettyWood** [comment]
Hi @Congee

Just add `M.update_forward_refs(Nested=Nested)` after declaring your model `M` ;)
Just an issue with retrieving the right locals by default.

**Comment by Congee** [comment]
Oh thank you for that solution! I never know BaseModel.update_forward_refs could accept some args. Its type signature is `update_forward_refs: (**localns: Any) -> None`. And I could not find it documented here https://pydantic-docs.helpmanual.io/usage/postponed_annotations/ either. Maybe something should be added to docs :thinking:

**Comment by samuelcolvin** [comment]
Feel free to create a PR to improve the docs.

**Comment by Kludex** [comment]
> Simply add M.update_forward_refs(Nested=Nested) after declaring your model M ;)
Just an issue with retrieving the right locals by default.

@PrettyWood Do you mind explaining why this happens? :cry: I'd really appreciate. :kissing: 

Also, thanks for the solution! :)

**Comment by samuelcolvin** [comment]
See https://github.com/samuelcolvin/pydantic/issues/2678#issuecomment-821437650

**Comment by Kludex** [comment]
Thank you @samuelcolvin :)
