### ISSUE TITLE
parse_obj_as subclass returns parent class

### ISSUE THREAD

**Issue by mdavis-xyz** [samuelcolvin/pydantic#2433]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.8
            pydantic compiled: False
                 install path: /home/ec2-user/.local/lib/python3.6/site-packages/pydantic
               python version: 3.6.12 (default, Feb 18 2021, 17:29:24)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
                     platform: Linux-4.14.219-119.340.amzn1.x86_64-x86_64-with-glibc2.3.4
     optional deps. installed: ['email-validator', 'typing-extensions']
```

When subclassing a pydantic class, and then doing `parse_obj_as`, the object that is returned is of the parent class, not the child class. 

```
import pydantic
from uuid import uuid4

class MyUUID(pydantic.UUID4):
    pass

u = pydantic.parse_obj_as(MyUUID, uuid4())

assert isinstance(u, MyUUID), f"u is type {type(u)}"
```

Expected behavior: `parse_obj_as(x, y)` *always* returns a value of class `x` (or throws an exception)

Actual behavior:

`parse_obj_as(x, y)` returns object that is not of class x.

```
Traceback (most recent call last):
  File "uu.py", line 9, in <module>
    assert isinstance(u, MyUUID), f"u is type {type(u)}"
AssertionError: u is type <class 'uuid.UUID'>
```

**Comment by PrettyWood** [comment]
Hi @mdavis-xyz 
Yes it's the same root cause as #2189

**Comment by mdavis-xyz** [comment]
Ok. I'll close this ticket as a duplicate then.
