### ISSUE TITLE
Broken MkDocs rendering of Validators page

### ISSUE THREAD

**Issue by johnthagen** [samuelcolvin/pydantic#2445]
https://pydantic-docs.helpmanual.io/usage/validators/

The third bullet looks like it was meant to have nested bullets in it.

<img width="819" alt="Screen Shot 2021-03-01 at 2 51 05 PM" src="https://user-images.githubusercontent.com/10340167/109550833-c9dba000-7a9d-11eb-868d-035aac524ad0.png">

Related to #2439

**Comment by PrettyWood** [comment]
@johnthagen Thanks for reporting again 🙏 
If you want to submit a PR to fix it feel free! :) Otherwise I'll do it tomorrow
