### ISSUE TITLE
pydantic dataclass with Field(..., alias=) can't be constructed

### ISSUE THREAD

**Issue by ahirner** [samuelcolvin/pydantic#2446]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8
            pydantic compiled: True
                 install path: /Users/dafcok/miniconda3/lib/python3.6/site-packages/pydantic
               python version: 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
                     platform: Darwin-19.6.0-x86_64-i386-64bit
     optional deps. installed: ['devtools', 'dotenv', 'email-validator', 'typing-extensions'
```
```py
from pydantic import Field, BaseModel
from pydantic.dataclasses import dataclass

# works
class Ab(BaseModel):
    a: int = Field(..., alias="b")

Ab(b=10)

##########
@dataclass
class A:
    a: int = Field(..., alias="b")

# works
assert A.__pydantic_model__.schema()["properties"]["b"]["type"] == "integer"

# fails with:
# File "~/python3.6/site-packages/pydantic/dataclasses.py", line 99, in _pydantic_post_init
#     raise validation_error
# pydantic.error_wrappers.ValidationError: 1 validation error for A
# b
#   field required (type=value_error.missing)
A(a=10)
# fails the same way as above
A(10)
# fails but with: TypeError: __init__() got an unexpected keyword argument 'b'
A(b=10)
```
It seems that `FieldInfo` values are honored by `__has_field_info_default__` but an alias is not warranted before processing the dataclass.

**Comment by PrettyWood** [comment]
Hi @ahirner and thanks for reporting
The issue is the same with
```py
@dataclass
class A:
    a: int = field(metadata=dict(alias="b"))
```
The real problem is that `dataclass.__init__` will write the signature with `"a"`, which may conflict with the model attached to it used for validation.
I can have a look later but it's not that trivial

**Comment by samuelcolvin** [comment]
I think this has been reported before. It's virtually impossible to fix since the `dataclass` decorator constructs the `__init__` function.

Very happy to accept a PR to document this though.
