### ISSUE TITLE
ValidationError raised when using .parse_obj with a model instance

### ISSUE THREAD

**Issue by sralloza** [samuelcolvin/pydantic#2474]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8
            pydantic compiled: True
                 install path: D:\.dev\backend-dev\.venv\Lib\site-packages\pydantic
               python version: 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
                     platform: Windows-10-10.0.19041-SP0
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

When I try to use `Model.parse_obj` but one of the attributes is not a python dict but an expected pydantic model (maybe generated by a validator) it raises a `ValidationError`. It's worth mentioning that the model's instance previously mentioned is a custom model redefining `__root__ `as a list of another model.

The code is self-explanatory.

This code does not raise any validation error in pydantic version 1.7.3

```py
from typing import List, Literal

from pydantic import BaseModel


class Item(BaseModel):
    name: str
    kind: Literal["A", "B"]


class ItemList(BaseModel):
    __root__: List[Item]

    def __iter__(self):
        return iter(self.__root__)


class Report(BaseModel):
    person: str
    items: ItemList
    destination: str


# This passes
result1 = Report.parse_obj(
    {
        "person": "Peter",
        "items": [{"name": "apple", "kind": "A"}],
        "destination": "Los Angeles",
    }
)

# This fails
items = ItemList(__root__=[{"name": "apple", "kind": "A"}])
result2 = Report.parse_obj(
    {
        "person": "Peter",
        "items": items,
        "destination": "Los Angeles",
    }
)

```

Last raises this validation error:

```python
Traceback (most recent call last):
    File "E:\sandbox\test.py", line 35, in <module>
        result2 = Report.parse_obj(
    File "pydantic\main.py", line 563, in pydantic.main.BaseModel.parse_obj
    File "pydantic\main.py", line 391, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Report
items -> __root__
  value is not a valid list (type=type_error.list)
```

**Comment by PrettyWood** [comment]
Hi @sralloza 
It has been solved. You can try with `v1.8.1` :)

**Comment by sralloza** [comment]
Oh, I'm really sorry, I really thought I had  version 1.8.1 installed.
Really nice library, by the way!
