### ISSUE TITLE
Empty tuple type does not generate valid JSON schema

### ISSUE THREAD

**Issue by ghost** [samuelcolvin/pydantic#2496]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
 python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.8.1
            pydantic compiled: True
                 install path: /Users/smacpher/.virtualenvs/nucleus/lib/python3.6/site-packages/pydantic
               python version: 3.6.9 (default, Oct 16 2019, 11:14:39)  [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)]
                     platform: Darwin-17.7.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
import jsonschema
import pydantic

from typing import Tuple

class Model(pydantic.BaseModel):
    f: Tuple[()]

jsonschema.Draft7Validator.check_schema(Model.schema())
```

This fails with:

```
SchemaError: [] is not valid under any of the given schemas

Failed validating 'anyOf' in metaschema['properties']['properties']['additionalProperties']['properties']['items']:
    {'anyOf': [{'$ref': '#'}, {'$ref': '#/definitions/schemaArray'}],
     'default': True}

On schema['properties']['f']['items']:
    []
```

The generated schema is:

```py
{'title': 'Model',
 'type': 'object',
 'properties': {'f': {'title': 'F', 'type': 'array', 'items': []}},
 'required': ['f']}
```

Is this expected behavior? Would the desired behavior be to set `maxItems: 0` and remove `items: []` like such (that would make the generated schema valid)?

```
{'title': 'Model',
 'type': 'object',
 'properties': {'f': {'title': 'F', 'type': 'array', 'maxItems': 0}},
 'required': ['f']}
```

BTW, glad to see that empty tuples (`Tuple[()]`) are now supported (https://github.com/samuelcolvin/pydantic/issues/2318)! Thank you 🙏 .

**Comment by PrettyWood** [comment]
Hi @smacpher-myst and thanks a lot for reporting!
I opened #2497 and tackled your issue at the same time. Feedback welcome :)

**Comment by smacpher-myst** [comment]
@PrettyWood no problem! Awesome, thanks for the super quick turn around :D. Looked over your changes and they look good to me – approved as well (FWIW).
