### ISSUE TITLE
Order of serialized attributes is not preserved

### ISSUE THREAD

**Issue by dmfigol** [samuelcolvin/pydantic#250]
For bugs/questions:
* OS: **macOS**
* Python version `import sys; print(sys.version)`: **3.6.5**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **0.13**

Where possible please include a self contained code snippet describing your 
bug, question, or where applicable feature request:

```py
from typing import Optional
from pydantic import BaseModel, Schema, validator

class Template(BaseModel):
    id: str = Schema(
        ...,
        alias='templateId',
    )
    num: int = Schema(
        10,
        alias='NUM'
    )
    some_var: Optional[str]

    @validator("id", pre=True)
    def parse_id(cls, value):
        return value[:10]


t = Template(templateId="csdfsdf2351fsdfs", NUM="123")
t.dict()
# > {'some_var': None, 'id': 'csdfsdf235', 'num': 123}
```
It seems that attributes without `Schema` take precedence over attributes with `Schema`

**Comment by samuelcolvin** [comment]
This is explained in the docs: https://pydantic-docs.helpmanual.io/#strict-optional

As per #203 it's not possible to preserve the field order completely.
