### ISSUE TITLE
Mypy doesn't like **dict syntax for model instance creation

### ISSUE THREAD

**Issue by raph90** [samuelcolvin/pydantic#2516]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
```py
class TestMod(RSBaseModel):
    name: Optional[str]
    age: int


x = {"age": "hello"}

my_test = TestMod(**x) <--- error appears here

```

This code creates the following mypy error: Argument 1 to "TestMod" has incompatible type "**Dict[str, str]"; expected "int".
Is there any way to keep init type checking (ie init_typed = True in mypy.ini in the pydantic plugin config) and also to get rid of this error?

Thanks in advance and apologies if this has been covered before. I've honestly spent a good deal of time trying to find a solution.

**Comment by samuelcolvin** [comment]
This is not a bug, but a question. And you haven't described what `RSBaseModel `.

Please use discussions for questions and describe your question fully.

**Comment by nikicat** [comment]
@raph90 did you find a solution? I have the same problem too.
