### ISSUE TITLE
validators called twice

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#254]
from @dmfigol on gitter:

I am failing to understand why validator is applied several times on the complex field:

```py
import json
from typing import List, Dict, Any

from pydantic import BaseModel, ValidationError, validator

class DemoModel(BaseModel):
    data: Dict[str, Any] = {}

    @validator('data', pre=True, whole=True)
    def json_decode(cls, v):
        print(f'value is {v!r}, type: {type(v)}')
        if isinstance(v, str):
            try:
                return json.loads(v)
            except ValueError:
                pass
        return v

print(DemoModel(data='{"foo": {"bar": 123}}'))

# > value is '{"foo": {"bar": 123}}', type: <class 'str'>
# > value is 'foo', type: <class 'str'>
# > DemoModel data={'foo': {'bar': 123}}
```
I would appreciate if you could explain :) because of this I spent a lot of time debugging my code and after I found the problem, I still don't understand why it is working this way :(

**Comment by samuelcolvin** [comment]
Sorry you had trouble. I can understand that this was confusing.

First of all, for parsing json you would be much better off using the `Json` meta type:

```py
from typing import Dict, Any

from pydantic import BaseModel, Json


class DemoModel(BaseModel):
    data: Json[Dict[str, Any]] = {}

print(DemoModel(data='{"foo": {"bar": 123}}'))
```
This is documented [here](https://pydantic-docs.helpmanual.io/#json-type) unfortunately I broke that section of the docs when last deploying so it wouldn't have made much sense, but it's now fixed

On the particular problem you're having, the reason is that the validator is being called twice is that it's also being called when validating the dict keys:

https://github.com/samuelcolvin/pydantic/blob/c7c15bc41533551c3ad2a3655c06cc12ca68d6e9/pydantic/fields.py#L241

I guess this should be fixed so there's another keyword for validators `key` which means they're called on values, and `whole` validators shouldn't be called on keys or values.

**Comment by dmfigol** [comment]
@samuelcolvin thanks for the hint with JSON type and fixing docs!

>I guess this should be fixed so there's another keyword for validators key which means they're called on values, and whole validators shouldn't be called on keys or values.
Yeah, I'd expect that the `whole` validator is applied once and is not invoked later when we are checking the type defined in the annotation.

**Comment by amogorkon** [comment]
Your check on duplicate validators breaks validators in jupyter notebooks if a cell is executed more than once.

```
from pydantic import BaseModel, validator
import yaml
from ipaddress import ip_address

class Config(BaseModel):
    ip: str
    name: str
    port: int
        
    @validator("ip")
    def check_ip(cls, value):
        return ip_address(value)            
            

with open("config") as f:
    d = yaml.safe_load(f)
    c = Config(**d)
    print(c)
```
Returns 
Config ip=IPv4Address('123.0.0.200') name='asdf' port=2392
when the cell is called first and raises

> ConfigError                               Traceback (most recent call last)
> <ipython-input-2-f5fc04cf284b> in <module>()
>       3 from ipaddress import ip_address
>       4 
> ----> 5 class Config(BaseModel):
>       6     ip: str
>       7     name: str
> 
> <ipython-input-2-f5fc04cf284b> in Config()
>       8     port: int
>       9 
> ---> 10     @validator("ip")
>      11     def check_ip(cls, value):
>      12         return ip_address(value)
> 
> ~/anaconda3/lib/python3.7/site-packages/pydantic/main.py in dec(f)
>     449         ref = f.__module__ + '.' + f.__qualname__
>     450         if ref in _FUNCS:
> --> 451             raise ConfigError(f'duplicate validator function "{ref}"')
>     452         _FUNCS.add(ref)
>     453         f_cls = classmethod(f)
> 
> ConfigError: duplicate validator function "__main__.Config.check_ip"
The second time the same cell is called.

I was somewhat surprised by this behaviour and when I checked the code, I didn't really get why this exception is raised since we're dealing with a set here, so behaviour shouldn't change.
I would suggest to replace this exception with a logger message, warning level, which won't mess with people's code and is well supported by jupyter.

**Comment by samuelcolvin** [comment]
@amogorkon this is not related to the issue being discussed here. Would be great if you could create a new issue and delete your comment.

**Comment by amogorkon** [comment]
Sorry, didn't notice your reply here. Opened a new issue and deleted comment as requested.
