### ISSUE TITLE
Bug: ignore_extra=False and allow_population_by_alias=True do not work together

### ISSUE THREAD

**Issue by dmfigol** [samuelcolvin/pydantic#257]
* OS: **macOS**
* Python version `import sys; print(sys.version)`: **3.6.6**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **0.13**

Code snippet:
```py
from pydantic import BaseModel, Schema
from typing import Optional

class Model(BaseModel):
    last_updated_by: Optional[str] = Schema(None, alias="lastUpdatedBy")

    class Config:
        ignore_extra = False
        allow_population_by_alias = True

m1 = Model(lastUpdatedBy="dmitry") # ok
m2 = Model(last_updated_by="dmitry") # fails

# >
"""
ValidationError: 1 validation error
last_updated_by
  extra fields not permitted (type=value_error.extra)
"""
```
Additional info: read docs, including the warning, but it does not seem like this is an expected behavior.

**Comment by samuelcolvin** [comment]
This is exactly what you would expect unless I'm missing something.

**Comment by samuelcolvin** [comment]
Oh, I missed `allow_population_by_alias`. 

I guess this is wrong but I think that seeing is dumb anyway, maybe we shouldn't have included it.
