### ISSUE TITLE
Question/Feature Request: Support forward references

### ISSUE THREAD

**Issue by koliyo** [samuelcolvin/pydantic#258]
Do you support [forward references](https://www.python.org/dev/peps/pep-0484/#forward-references)? If not, I would request this feature :)
```py
from pydantic import BaseModel
from typing import List, Dict, Tuple, Any

class Attribute(BaseModel):
    type: 'Model' = None

class Model(BaseModel):
    attributes: List[Attribute]
```

**Comment by samuelcolvin** [comment]
#234, or maybe the confusing issue title meant you missed it?
