### ISSUE TITLE
AnyUrl cannot be an Optional field in a BaseModel

### ISSUE THREAD

**Issue by holyoaks** [samuelcolvin/pydantic#2602]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /usr/local/lib/python3.8/dist-packages/pydantic
               python version: 3.8.5 (default, Jan 27 2021, 15:41:15)  [GCC 9.3.0]
                     platform: Linux-4.19.121-linuxkit-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions', 'email-validator']
```

Not possible to include a self contained snippet, as I'm using this against a SQLAlchemy ORM backend, but to give the idea...

```py
import pydantic
from typing import Optional

class ResourceBase(pydantic.BaseModel):
    title: str
    url: Optional[pydantic.AnyUrl]

    class Config:
        orm_mode = True

r = Resource(title="Title") #i.e., no url specified in the underlying db model
rr = ResourceBase.from_orm(r)
```

Throws
```
/usr/local/lib/python3.8/dist-packages/pydantic/main.cpython-38-x86_64-linux-gnu.so in pydantic.main.BaseModel.from_orm()

ValidationError: 1 validation error for ResourceBase
url
  ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)
```

This is because of `pydantic.networks.AnyUrl` line 94, `min_length = 1`, which makes the validation (line 179) fail, even though the field is marked as Optional, combined with the specific failure on my part to make my DB field nullable. The url is being written to the DB as a zero length string, not null, and is therefore returning `''` to the validator instead of None. Based on all other usage of `Optional` in pydantic, I expect `Optional` to "override" the underlying validation. Otherwise, `Optional` isn't really optional. If this is indeed the intended behavior, then I would suggest the docs need to be updated to make explicit that AnyUrl (and probably other url classes) cannot be made `Optional`

**Comment by PrettyWood** [comment]
```py
from typing import Optional

import pydantic


class TestCls:
    title = 'Title'
    url = None


class ResourceBase(pydantic.BaseModel):
    title: str
    url: Optional[pydantic.AnyUrl]

    class Config:
        orm_mode = True


ResourceBase.from_orm(TestCls())
```
works as expected. I'm quite sure you have `url == ''` and not `url is None` hence the error.
