### ISSUE TITLE
parse_obj not working as it should 

### ISSUE THREAD

**Issue by bendidi** [samuelcolvin/pydantic#2603]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8.1
            pydantic compiled: True
                 install path: /home/obendidi/.cache/pypoetry/virtualenvs/datasets-libs-qs-tjU-u7JD-py3.7/lib/python3.7/site-packages/pydantic
               python version: 3.7.9 (default, Mar 15 2021, 11:49:48)  [GCC 9.3.0]
                     platform: Linux-5.4.0-70-generic-x86_64-with-debian-bullseye-sid
     optional deps. installed: ['typing-extensions']
```

```py
from pydantic import BaseModel

class CategoryModel(BaseModel):

    _id: int
    name: str


category = {"_id": "ah", "name": "test"} # _id is string here
CategoryModel.parse_obj(category) # does not raise ValidationError
...
```

**Comment by PrettyWood** [comment]
Hi @bendidi 
`_id` is not considered as a field and is hence not checked
See https://github.com/samuelcolvin/pydantic/issues/288 for more information
