### ISSUE TITLE
"schema" used instead of "scheme" in docs

### ISSUE THREAD

**Issue by nuno-andre** [samuelcolvin/pydantic#2619]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

> This is not a Pydantic bug, but a "docs bug".

Despite the URL property is correctly named `scheme`, it's [referenced in docs](https://pydantic-docs.helpmanual.io/usage/types/#url-properties) as _schema_. English is not my first language (needless to say :sweat_smile:) and I don't fully understand the semantic difference between both terms, but this attribute is consistently named _scheme_ in IETF's RFCs and [IANA docs](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml).

Also, _schema_ is widely used in Pydantic to mean "JSON Schema" so this misnomer could lead to confusion.

**Comment by PrettyWood** [comment]
You're right @nuno-andre it's indeed scheme ;)
