### ISSUE TITLE
Question: create_model with validator

### ISSUE THREAD

**Issue by koliyo** [samuelcolvin/pydantic#262]
How can I attach a validator to a model generated dynamically with `create_model`? I have tried looking at the decorator and model creation flow, but unable to figure it out :/

**Comment by hmvp** [comment]
Isn't this done using the `__validators__` argument to create_model?

eg
```
def function(v, values):
    ...
validator_function = validator("field", pre=True)(function)
create_model("name", *fields, __validators__={"some_validator": validator_function})
```

**Comment by dmontagu** [comment]
I think @hmvp is right, here is a self-contained working example:
```python
from pydantic import validator, create_model


def function(cls, v, values):
    if v < 0:
        raise ValueError
    return v

validator_function = validator("number", pre=True, check_fields=False)(function)
MyModel = create_model("MyModel", __validators__={"validator1": validator_function}, number=(int, ...))
MyModel(number=0)  # OK
MyModel(number=-1)  # Not OK
"""
pydantic.error_wrappers.ValidationError: 1 validation error
number
   (type=value_error)
"""
```

@koliyo Depending on your requirements, it may also be possible to take an approach similar to what `GenericModel` is doing where you strip the validators off an existing class (if, for example, the validators you want to add are always the same) using `pydantic.class_validators.gather_validators`. (Depending on the use case it may also be possible to just use `GenericModel`.)

**Comment by dmontagu** [comment]
I'm going to close this issue since it looks like it is addressed by the above comments. But feel free to reopen it, and please let us know if you are still having any related issues.
