### ISSUE TITLE
Impossible to use Pydantic objects other than as data objects

### ISSUE THREAD

**Issue by jenia** [samuelcolvin/pydantic#2627]
### Checks

* [ X ] Cannot make calculation for Pydantic object fields
* [ X ] I have searched (google, github) for similar issues and couldn't find anything
* [ X ] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

I need to both specify an alias and make some calculation on a Pydantic field. But it is possible to do only one or the other.

```
from pydantic import Field
from pydantic.main import BaseModel


class ComplexObject(BaseModel):
    for0: str = Field("This is rediculous. I want to make complex calculation here" , alias="for")

    @classmethod
    def create(cls, x: int, y: int):
        co = ComplexObject(for0=str(x * y))
        return co


co = ComplexObject(x=1, y=2)
print(co.json(by_alias=True))

# returns {"for" : "This is rediculous. I want to make complex calculation here"}
# I want it to return {"for" : "2"}
```
If I remove the `Field("This is rediculous. I want to make complex calculation here" , alias="for")` then it works as expected except now the JSON field is not named correctly.
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.1
            pydantic compiled: True
                 install path: /home/jenia/.local/lib/python3.9/site-packages/pydantic
               python version: 3.9.2 (default, Feb 20 2021, 18:40:11)  [GCC 10.2.0]
                     platform: Linux-5.11.11-arch1-1-x86_64-with-glibc2.33
     optional deps. installed: ['dotenv', 'typing-extensions']
```

**Comment by jenia** [comment]
I fact even this does not work (I moved the `@classmethod` out of the object. Still it doesn't work.

from pydantic import Field
from pydantic.main import BaseModel

```
class ComplexObject(BaseModel):
    for0: str = Field("This is rediculous. I want to make complex calculation here", alias="for")


def create(x: int, y: int):
    co = ComplexObject(for0=str(x * y))
    return co


co = ComplexObject(x=1, y=2)
print(co.json(by_alias=True))
```

**Comment by kmorris81** [comment]
Try this:

```
from pydantic import Field
from pydantic.main import BaseModel


class ComplexObject(BaseModel):
    for0: str = Field("This is rediculous. I want to make complex calculation here", alias="for")

    @staticmethod
    def create(x: int, y: int):
        dyn_for = {"for": str(x*y)}
        co = ComplexObject(**dyn_for)
        return co


co = ComplexObject.create(x=1, y=2)
print(co.json(by_alias=True))
```
Produces:
```
{"for": "2"}
```

**Comment by jenia** [comment]
Thank you!! Worked perfectly. I wish this super common use case would be better documented but thank you kindly  @kmorris81

**Comment by PrettyWood** [comment]
Hi @jenia 
You can also set `allow_population_by_field_name=True` in your config to be able to use `for0`.

**Comment by jenia** [comment]
@PrettyWood Thanks!!
