### ISSUE TITLE
QUESTION: Field types which don't have validators

### ISSUE THREAD

**Issue by pauleveritt** [samuelcolvin/pydantic#267]
*Note: This is partly in relation to the dataclasses branch due to the system I'm using pydantic in, but isn't really about dataclasses.*

I have a system in which dataclasses can have values dependency-injected. For example, a "view":

```python

@pydantic.dataclasses.dataclass
class ArticleView:
    resource: Resource
    name: str = 'One Pydantic View'
```

The system inspects the fields. If the caller passed in a prop (e.g. ``name``) it is used in the constructor. Otherwise, the system looks at the field's type and sees if it has an injectable value of that type. Otherwise, the field needs to have a default.

In the above, ``Resource`` is a dependency-injected field. I get a value from the system and add it to the dict that I'm going to construct ``ArticleView`` with.

But the ``Request`` value isn't a pydantic model. So validation fails.

I believe this is a very normal part of what pydantic expects so I probably have a lot of choices:

- Have my views such as ``ArticleView`` subclass from a base model which has a Config that 
  knows some well-known names aren't to be validated

- Put some kind of marker on those classes, such as Request, to indicate they don't get validated

- etc.

**Comment by samuelcolvin** [comment]
You can use the [`arbitrary_types_allowed`](https://pydantic-docs.helpmanual.io/#model-config) config option which should just allow any value to `resource` which is an instance of `Resource`. Currently config options can't be used on dataclasses, but I could we could allow them in future.

Alternatively you could add the `get_validators` method to resource:

```py
class Resource:
    ...
    
    @classmethod
    def validate(cls, v):
        # do some validation or simply pass through the value
        return v

    @classmethod
    def get_validators(cls):
        yield cls.validate
```

So pydantic knows how to validate Resources.

Hope that helps, I'll close this but feel free to ask follow up questions.

**Comment by pauleveritt** [comment]
I know the ticket is closed, but to follow up on the point about config options and dataclasses...that means the ``class Config`` stuff at https://pydantic-docs.helpmanual.io/#model-config won't apply when using ``@pydantic.dataclasses.dataclass`` right?

At the moment I'm using config pretty heavily but I can look for other ways to accomplish what I'm doing there.

**Comment by samuelcolvin** [comment]
Happy to add more key word arguments to dataclass as required.
