### ISSUE TITLE
QUESTION: Only do validation based on a configuration flag, e.g. in development mode

### ISSUE THREAD

**Issue by pauleveritt** [samuelcolvin/pydantic#268]
I have a system which embraces dataclasses and pydantic models in lots of places beyond data. For example, components which describe their "interface".

In these cases, some people might want pydantic validation during development but not in production. I was curious if there's a Config option for this, but I doubt it.

If not, I was thinking I could do something like the following. I have a dataclass for a component:

```python
@dataclass
class ArticleView:
    name: str = 'One Pydantic View'
```

In my system, users don't construct ``ArticleView``, the system does. In the place of construction, I could:

- Construct an article_view instance
- Look at the configuration value to see if validation is on
- If so, *also* construct (and throw away) a pydantic instance
- E.g.

**Comment by samuelcolvin** [comment]
surely simply do something like


```py
from dataclasses import dataclass as std_dataclass
from pydantic.dataclasses import dataclass as pydantic_dataclass

if in_development_mode:
    dataclass = pydantic_dataclass
else:
    dataclass = std_dataclass

@dataclass
class ArticleView:
    name: str = 'One Pydantic View'

# or if you only know what mode you're in a runtime

class NakedArticleView:
    name: str = 'One Pydantic View'

def foobar():
    if in_development_mode:
        dc = pydantic_dataclass
    else:
        dc = std_dataclass
    
    ArticleView = dc(NakedArticleView)
    ...
```

again, closing this but feel free to ask follow-up questions.
