### ISSUE TITLE
Union types don't recognize bools in coercion order if ints or floats are included

### ISSUE THREAD

**Issue by dlopuch** [samuelcolvin/pydantic#2701]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.1
            pydantic compiled: True
                 install path: ~/.local/share/virtualenvs/XXX-D1SziJ_u/lib/python3.6/site-packages/pydantic
               python version: 3.6.13 (default, Feb 18 2021, 16:38:18)  [GCC Apple LLVM 12.0.0 (clang-1200.0.32.29)]
                     platform: Darwin-20.3.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

This is kinda related to https://github.com/samuelcolvin/pydantic/issues/2135, but a different enough case that it probably warrants its own issue.

In that bug, it was said "pydantic tries to coerce in the order of the union". The [docs](https://pydantic-docs.helpmanual.io/usage/types/#unions) say something similar: "pydantic will attempt to 'match' any of the types defined under Union and will use the first one that matches."

That behavior appears to not work for bools -- bools seem to be cooerced to ints or floats if int or float is defined in the list:

```py
import typing as t
from pydantic import BaseModel

class UnionTest(BaseModel):
     mixed: t.Optional[ t.Union[bool, int, str] ]

UnionTest(mixed=False)
# ===> UnionTest(mixed=0) -- BUG: coerced into int, not the bool!
```

**Comment by PrettyWood** [comment]
@dlopuch If you can use python 3.7+ you won't have this issue

**Comment by PrettyWood** [comment]
@dlopuch If you can use python 3.7+ you won't have this issue
This works in 3.6 and fails with 3.7+
```py
from typing import Union

assert Union[bool, int, str] == Union[int, str]
```
