### ISSUE TITLE
Incomplete type annotations in BaseConfig yield mypy errors when Config is defined from BaseConfig

### ISSUE THREAD

**Issue by mpkocher** [samuelcolvin/pydantic#2719]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

1. The `BaseConfig` is missing type annotations for a few fields. Inheriting from `BaseConfig` and setting values yields type errors from `mypy`. 

```python
from pydantic import BaseConfig, BaseModel, Extra


class Record(BaseModel):
    alpha: str
    beta: str

    class Config(BaseConfig):
        title = "Record"
        extra = Extra.ignore
        max_anystr_length = 1234

```

yields

```bash
mypy --version && mypy example.py
mypy 0.812
example.py:9: error: Incompatible types in assignment (expression has type "str", base class "BaseConfig" defined the type as "None")  [assignment]
example.py:11: error: Incompatible types in assignment (expression has type "int", base class "BaseConfig" defined the type as "None")  [assignment]
Found 2 errors in 1 file (checked 1 source file)
```

I believe the type annotations should be:

```python
from typing import Union, Optional

class BaseConfig:
    title: Optional[str] = None
    min_anystr_length: Optional[int] = None # can this just be int = 0 ?
    max_anystr_length: Optional[int] = None
    extra = Union[str, Extra] = Extra.ignore
```

Inheriting from `BaseConfig` is useful for autocomplete and avoids typos like the following.

```python
from pydantic import BaseModel

class Point(BaseModel):
    x: int
    y: int
    
    class Config:
        extras = "forbid"
```

2. The [Config docs](https://pydantic-docs.helpmanual.io/usage/model_config/) look to be inconsistent with the default values defined in `BaseConfig`.

- the default for `max_anystr_length` is listed as `2 ** 16` in the docs, however, `None` is defined in `BaseConfig` (i.e., there is no limit)
- Setting `max_anystr_length = 0` ignores the validation completely and has a different semantic meaning than any other positive integer. In other words, `max_anystr_length = 0` is the same as `max_anystr_length = None`.
- Similarly, the default for `min_anystr_length` is listed as `0` in the docs, but the listed default is `None` in `BaseConfig`. If these are semantically the same, then perhaps set `min_anystr_length:int = 0` as the default?
- In general, it might be useful to clarify the truthyness of these `0` vs `None` values 

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.1
            pydantic compiled: False
               python version: 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)  [Clang 11.0.1 ]
                     platform: macOS-11.2.3-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by PrettyWood** [comment]
Hi @mpkocher 
Thanks for reporting! I opened https://github.com/samuelcolvin/pydantic/pull/2720
Just a remark for `Config.extra`. I think it's better to just type `Extra` instead of `Union[Extra, str]` if the goal is safety.
We could do `Union[Extra, Literal["ignore", "forbid", "allow"]]` but even with this `extra = "forbid"` wouldn't work. It would need to be enforced with `Final` or `Literal`.
WDYT?

**Comment by mpkocher** [comment]
@PrettyWood I agree that keeping the type as `Extra` would be a better approach if possible. The primary motivation for adding `str` was an attempt to be consistent with some of the docs. 

https://pydantic-docs.helpmanual.io/usage/models/#model-creation-from-namedtuple-or-typeddict
