### ISSUE TITLE
parse_obj_as fails with Optional generic type in a specific situation

### ISSUE THREAD

**Issue by fernandocamargoai** [samuelcolvin/pydantic#2723]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.1
            pydantic compiled: True
                 install path: /home/fernandocamargo/.cache/pypoetry/virtualenvs/bento2seldon-j7OH65zf-py3.7/lib/python3.7/site-packages/pydantic
               python version: 3.7.6 (default, Jan  8 2020, 19:59:22)  [GCC 7.3.0]
                     platform: Linux-5.10.30-1-MANJARO-x86_64-with-arch-Manjaro-Linux
     optional deps. installed: ['typing-extensions']
```

I tried to create a simplified version of the code as follows:

```py
from typing import Any, Dict, Generic, Optional, TypeVar
import pydantic
from pydantic.main import BaseModel
from pydantic.generics import GenericModel
from pydantic.tools import parse_obj_as

R = TypeVar("R", bound=BaseModel)


class SeldonMessage(GenericModel, Generic[R]):
    jsonData: Optional[R]


class RankingRequest(BaseModel):
    user_id: int


class Feedback(GenericModel, Generic[R]):
    request: Optional[SeldonMessage[R]]


obj = parse_obj_as(Feedback[RankingRequest], {"request": {"jsonData": {"user_id": 1}}})
assert obj.request.jsonData.user_id == 1
```

And it was supposed to fail, but strangely it doesn't. So, here is more complex way to reproduce the bug:
First, install `pip install bento2seldon==0.1.0` or copy the following file:
https://github.com/fernandocamargoai/bento2seldon/blob/v0.1.0/bento2seldon/seldon.py
Create a module called `model.py` with the following code (for some reason the error only happens if those classes are specified in another module):

```py
from typing import Union, List, Optional

from pydantic.main import BaseModel
from pydantic import validator


ID = Union[int, str]


class RankingRequest(BaseModel):
    user_id: Optional[ID]
    item_id: Optional[ID]
    top_k: int = 10

    @validator("item_id", always=True)
    def item_is_required_if_user_id_none(cls, item_id: Optional[ID], values: dict, **kwargs):
        if values.get("user_id") is None:
            assert item_id is not None, "Either user_id or item_id must be provided"
        return item_id


class RankingResponse(BaseModel):
    item_ids: List[ID]
```

And run the following:

```py
from pydantic.tools import parse_obj_as

from bento2seldon.seldon import SeldonMessage, Feedback

from model import RankingRequest, RankingResponse

obj = parse_obj_as(Feedback[RankingRequest, RankingResponse], {'request': {'jsonData': {'user_id': 0, 'top_k': 10}}, 'response': {'status': {'code': 200, 'status': 'SUCCESS'}, 'meta': {'puid': '13deee6a-52d6-4021-ba21-76ba2aff1332', 'tags': {'predictive_unit_id': '0'}, 'routing': {}, 'requestPath': {}}, 'jsonData': {'item_ids': [4231, 1392, 3598, 1253, 4062, 2234, 2224, 4289, 833, 4112]}}, 'truth': {'status': {'code': 200, 'status': 'SUCCESS'}, 'meta': {'puid': '13deee6a-52d6-4021-ba21-76ba2aff1332', 'tags': {'predictive_unit_id': '0'}, 'routing': {}, 'requestPath': {}}, 'jsonData': {'item_ids': [1253]}}, 'reward': 1})
assert obj.request.jsonData.user_id == 0
```

It raises:

```
Traceback (most recent call last):
  File "/home/fernandocamargo/anaconda3/envs/rurax_recsys_training/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-7a27ea4a18b8>", line 2, in <module>
    assert obj.request.jsonData.user_id == 0
AttributeError: 'BaseModel' object has no attribute 'user_id'
```

But if I change the SeldonMessage and Feedback, replacing `<field>: Optional[R]` by `<field>: R = None`, it works. But then, MyPy starts complaining that it thinks those fields can't be None.

This bug is very strange and It was quite hard to reproduce it. If RankingRequest and RankingResponse are specified in the same module, for example, it doesn't happen.

**Comment by daviskirk** [comment]
Perhaps you can try to isolate the issue further to simplify the reproduction.

I used you instructions 

* copy file: https://github.com/fernandocamargoai/bento2seldon/blob/v0.1.0/bento2seldon/seldon.py
* Add model.py as stated
* Ran code (replace bento2seldon.seldon with "seldon" because the file is directly copied)

to reproduce the error and could not reproduce the issue on 1.8.1 and also not on master. (assert statement runs through fine `object.request.jsonData` prints to `user_id=0 item_id=None top_k=10`).

**Comment by fernandocamargoai** [comment]
@daviskirk, I've tried to reproduce it and the error happens. When looking for the version, I noticed that I was using Pydantic 1.7.3. Then, I upgraded to 1.8.1. After that, the error is gone. I guess whatever it was, it got fixed.

**Comment by PrettyWood** [comment]
Thanks @daviskirk!
