### ISSUE TITLE
It should be easier to deconstruct a list

### ISSUE THREAD

**Issue by oliverdain** [samuelcolvin/pydantic#2746]
I have some data that looks something like this:

```json
{
   "foo": [1, 2]
}
```

And I'd like to deserialize it into a model like:

```py
class Points(BaseModel):
    left: int
    right: int

class TheFoo(BaseModel):
    foo: Points
```

In particular, I know that the list will always contain 2 values and I'd like the first to become the value of `left` and the 2nd to be the value of `right`. I think it's somewhat common to have JSON APIs return lists with a fixed number of values like this where each value has a meaning.

I tried to get this to work using an `@root_validator` but that does not behave as I expect:

```py
class Point(pydantic.BaseModel):
    left: int
    right: int

    @pydantic.root_validator(pre=True)
    def deconstruct(cls, v):
        assert len(v) == 2
        return {'left': v[0], 'right': v[1]}

class Foo(pydantic.BaseModel):
    foo: Point

def test_foo():
    val = {'foo': [1, 2]}
    f = Foo(**val)
   assert f.foo.left == 1
```

But that gives me:

```
E   pydantic.error_wrappers.ValidationError: 1 validation error for Foo
E   foo
E     value is not a valid dict (type=type_error.dict)
```

I did some looking at the custom data types an `__get_validators__` stuff but didn't have much luck with that either.

**Comment by StephenBrown2** [comment]
Your use case looks rather close to the example for NamedTuple as a type: https://pydantic-docs.helpmanual.io/usage/types/#namedtuple

```pycon
In [1]: from typing import NamedTuple
   ...:
   ...: from pydantic import BaseModel, ValidationError
   ...:

In [2]: class Point(NamedTuple):
   ...:     left: int
   ...:     right: int
   ...:

In [3]: class Foo(BaseModel):
   ...:     foo: Point
   ...:

In [4]: def test_foo():
   ...:     val = {'foo': [1, 2]}
   ...:     f = Foo(**val)
   ...:     assert f.foo.left == 1
   ...:     return f
   ...:

In [5]: test_foo()
Out[5]: Foo(foo=Point(left=1, right=2))
```

Would that work for your case?

**Comment by oliverdain** [comment]
Thanks for the quick response @StephenBrown2. That does seem to do the trick in this case. It seems like there's a valid use-case for being able to manually construct truly arbitrary fields from a list and/or support something like this without requiring a `NamedTuple`. I think the only thing preventing that kind of flexibility is that pydantic requires that the values passed to `parse_obj` are a `dict` and not a `list` before the `@root_validator` gets called. For example, the following works:

```
class Example(pydantic.BaseModel):
    x: int
    y: str
    z: int

    @pydantic.root_validator(pre=True)
    def doit(cls, values):
        return {'x': values['x'], 'y': values['y'], 'z': 2 * values['x']}
```

then `Example.parse_obj({'x': 22, 'y': 'foo'})` returns `Example(x=22, y='foo', z=44)`. But trying to do something similar where it expects `values` to be a `list` fails:

```
class Example(pydantic.BaseModel):
    x: int
    y: str
    z: int

    @pydantic.root_validator(pre=True)
    def doit(cls, values):
        return {'x': values[0], 'y': values[1], 'z': 2 * values[0]}
```

But then `Example.parse_obj([22, 'foo'])` fails with:

```
ValidationError: 1 validation error for Example
__root__
  Example expected dict not list (type=type_error)
```

What do you think about adding something like a `skip_type_check` option to the `Config`?

**Comment by oliverdain** [comment]
It seems you can't put a validator on a `NamedTuple` which is another reason it might be nice to allow the `root_validator` to handle lists.

**Comment by PrettyWood** [comment]
Hi @oliverdain 

You're right _pydantic_ handles dicts by default hence the class workaround with [custom root types](https://pydantic-docs.helpmanual.io/usage/models/#custom-root-types)
```py
class Example(BaseModel):
    x: int
    y: str
    z: int

class ExampleRoot(BaseModel):
    __root__: Example

    @validator('__root__', pre=True)
    def doit(cls, values):
        return {'x': values[0], 'y': values[1], 'z': 2 * values[0]}

assert ExampleRoot.parse_obj([22, 'foo']).__root__ == Example(x=22, y='foo', z=44)
```

If you really want to do it inside `Example`, there is a dirty workaround for now:
```py
class Example(BaseModel):
    __custom_root_type__ = True

    x: int
    y: str
    z: int

    @root_validator(pre=True)
    def doit(cls, values: dict[str, list]) -> dict[str, object]:
        if set(values) == {'__root__'}:
            values = values['__root__']
            return {'x': values[0], 'y': values[1], 'z': 2 * values[0]}

        return values

assert Example.parse_obj([22, 'foo']) == Example(x=22, y='foo', z=44)
```
As you can see you need to add `__custom_root_type__` to tell _pydantic_ to act like `__root__` was here. If it's not it will automatically be added. And then you need to handle both cases in your `root_validator` to still support default init.
My recommendation would be to use first example but depends on you ;)

Hope it helps!

**Comment by oliverdain** [comment]
Thanks @PrettyWood. Very helpful!

**Comment by oliverdain** [comment]
BTW: Personally I'd vote to keep `__custom_root_type__`. It seems much nicer to be able to refer to `example.x` rather than `ExampleRoot.__root__`. In my particular case the thing I want to construct via a list is nested so I wouldn't be able to do: `example = ExampleRoot.parse_obj([...]).__root__`. I'd end up having to do `the_thing.nested_thing.__root__.x` everywhere which is a big ugly.
