### ISSUE TITLE
Dataclass configuration

### ISSUE THREAD

**Issue by jarekkar** [samuelcolvin/pydantic#276]
# Question

* OS: **Windows 10**
* Python version `import sys; print(sys.version)`: **3.6.6**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **0.14**

How to pass the pydantic configuration to classes annotated by `@dataclass`  in the correct way?

**Comment by samuelcolvin** [comment]
Right now you can't. Happy to accept a pr.
