### ISSUE TITLE
Allow configuring env letter case rules for settings parser

### ISSUE THREAD

**Issue by jasonkuhrt** [samuelcolvin/pydantic#277]
Issue derived from https://github.com/samuelcolvin/pydantic/issues/275

Currently `BaseSettings` defaults to looking for env variables in uppercase. This issue is a feature proposal to make this behaviour configurable.

The current workaround is to use the settings config class to set up aliases, e.g.:

```python
 class S(pydantic.BaseSettings):
      test:str

      class Config:
          fields = dict(test=dict(alias="test"))
```
However this is verbose and onerous to do (for the developer), if there are many such env vars.

It would be nice if the developer could do something like:

```python
 class S(pydantic.BaseSettings):
      class Config:
          letter_case = "lower" # or:  "upper" | "any"

      test:str
```

About this concern raised for case insensitive option https://github.com/samuelcolvin/pydantic/issues/275#issuecomment-430336275.

* we could log a warning or raise an error at a certain configurable threshold of
    * env var count
    * or perhaps based on measured processing time exceeding configurable budget (e.g. 1ms)
* we could cache the calculation of `env2` (but probably the entire settings result would just be cached by the app)
* the env prefix could help reduce the amount of work needed to do

**Comment by samuelcolvin** [comment]
I think just a warning in the docs is enough for the size thing.
