### ISSUE TITLE
parse_generic method to allow parsing non Model types

### ISSUE THREAD

**Issue by dnp1** [samuelcolvin/pydantic#278]
# Feature Request 
I'm writting a middleware for aiohttp that uses pydantic (inspired by webargs that uses marshmallow), [see](https://github.com/dnp1/argantic)

The development is still in the beggining

I would appreciate an additional helper functions for parsing types like:
-  `List[Model]  # where model is a pydantic model`
- `Dict[int, List[Model]]`  

and several other derivations of generic types.
Do you think make sense for pydantic scope, provides a function like:

```py
def parse_object_into_generic(type: Union[GenericType, Type], object) -> Any:
    pass

```

**Comment by samuelcolvin** [comment]
I'm not entirely clear what the function does. Could you give an example.

**Comment by samuelcolvin** [comment]
Makes more sense, longer term I'm thinking about a pydantic decorator for validating types. The idea is you could use it in multiple scenarios:
* at an interface between different components to provide a hard check of types
* in development and testing to validate your code, then disable it to just a pass-through decorator in production

I'm not expecting to work on that in the immediate future. However it shouldn't be very hard to build your own logic for this, take a look at how dataclasses are validation for inspiration:

https://github.com/samuelcolvin/pydantic/blob/cd50601172462b49cdf09e4d988906ba8f14af87/pydantic/dataclasses.py#L32-L34

**Comment by dnp1** [comment]
Thank you very much.

I'll try implement this at my project tonight.

But in my opinion it would be better placed as a pydantic funcionality. 
I'm still thinking about a proper name., `parse_object_into_generic` is terrible.

**Comment by samuelcolvin** [comment]
I would put it in your library for now, if you get it working well, then we can consider moving it into pydantic.

Otherwise you'll get annoyed as you'll want to iterate with it quickly and I'll be slower than you want to accept changes.
