### ISSUE TITLE
Deprecation warning emitted by "generate_model_signature"

### ISSUE THREAD

**Issue by domdfcoding** [samuelcolvin/pydantic#2786]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

With Python 3.10.0b1 a deprecation warning is emitted from the `pydantic.utils.generate_model_signature` function.
This is due to the following line:

https://github.com/samuelcolvin/pydantic/blob/b718e8e62680c2d7a42f1cf946094e1c0fe28c1d/pydantic/utils.py#L234

Accessing one enum member from another member is discouraged and is deprecated in Python 3.10, with removal scheduled for 3.12. See [bpo-43162](https://bugs.python.org/issue43162) and https://github.com/python/cpython/pull/24486 for more information.

This can be reproduced as follows:

`python3.10 -Werror -c "import pydantic"`

<details><summary>Traceback</summary>

```python traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/pydantic/__init__.py", line 2, in <module>
    from . import dataclasses
  File "/usr/lib/python3.10/site-packages/pydantic/dataclasses.py", line 7, in <module>
    from .main import create_model, validate_model
  File "/usr/lib/python3.10/site-packages/pydantic/main.py", line 376, in <module>
    class BaseModel(Representation, metaclass=ModelMetaclass):
  File "/usr/lib/python3.10/site-packages/pydantic/main.py", line 369, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
  File "/usr/lib/python3.10/site-packages/pydantic/utils.py", line 235, in generate_model_signature
    if config.extra is config.extra.allow:
  File "/usr/lib/python3.10/enum.py", line 151, in __get__
    warnings.warn(
DeprecationWarning: accessing one member from another is not supported,  and will be disabled in 3.12
```

</details>

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: False
                 install path: /usr/lib/python3.10/site-packages/pydantic
               python version: 3.10.0b1 (default, May  6 2021, 02:43:13) [GCC 9.3.0]
                     platform: Linux-5.8.0-50-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']

```

**Comment by tirkarthi** [comment]
I have created https://github.com/samuelcolvin/pydantic/pull/2788 as a potential fix.
