### ISSUE TITLE
Question: Too many arguments for dataclass

### ISSUE THREAD

**Issue by playpauseandstop** [samuelcolvin/pydantic#280]
# Question

* OS: **macOS 10.14**
* Python version: **3.7.0**
* Pydantic version **0.14**

----

Hi. I decided to try using pydantic instead of JSON Schemas for validating input / output data in my aiohttp web application, and so far run into strange mypy issue. Let consider next code of adding new project,

```py
from aiohttp import web
from pydantic.dataclasses import dataclass


@dataclass
class AddProject:

    """Add new user project."""

    name: str
    slug: Optional[str]
    description: Optional[str]


@login_required
async def add_project(request: web.Request) -> web.Response:
    """Add new user project."""
    data = AddProject(**await api_request(request))
    user_id = await get_user_id(request)

    async with request.app[APP_DB_KEY].acquire() as conn:
        project = await create_project(
            conn,
            user_id=user_id,
            name=data.name,
            slug=data.slug,
            description=data.description)

    return api_response(project.dict(), status=201)
```

It works as expected in runtime, but mypy failed with,

```
error: Too many arguments for "AddProject"
```

I tried to satisfy mypy by changing `AddProject` instantiation to,

```py
    raw_data = await api_request(request)
    data = AddProject(
        name=raw_data.get('name'),
        slug=raw_data.get('slug'),
        description=raw_data.get('description'))
```

but that made mypy failed with,

```
error: Unexpected keyword argument "name" for "AddProject"
error: Unexpected keyword argument "slug" for "AddProject"
error: Unexpected keyword argument "description" for "AddProject"
```

I'm a bit curious, as behind that mypy seems to work properly with `AddProject`, for example, it knows its attributes and fail in case of using missed ones, like `data.does_not_exist`.

----

Any suggestions on how to make mypy happy? Or this is an expected behaviour, which fixed only by `# type: ignore` comment?

ps. `api_request` coroutine returns `Dict[Any, Any]` if that necessary

**Comment by samuelcolvin** [comment]
Afraid I'm not sure. Does it give the same error if you use a vanilla dataclass?

**Comment by playpauseandstop** [comment]
@samuelcolvin 

Unfortunately not. It works well with,

```py
from dataclasses import dataclass as py_dataclass


@py_dataclass
class PyAddProject:

    """Add new user project."""

    name: str
    slug: Optional[str]
    description: Optional[str]
```

mypy succeed, where previously failed with _Too many arguments_ error.

**Comment by playpauseandstop** [comment]
@samuelcolvin 

Thanks for your answer. As of now I'm OK with `# type: ignore` comments, so feel free to close this as `wontfix`

**Comment by samuelcolvin** [comment]
thanks for understanding, I'll leave it open to make it easier for others to find and in case someone else has a solution.

**Comment by samuelcolvin** [comment]
I don't get this. Might have been fixed by mypy.

**Comment by samuelcolvin** [comment]
Need to add a section to the docs explain about usage of `typing.TYPE_CHECKING`

**Comment by swannknani** [comment]
Enabling `mypy` [plugin](https://pydantic-docs.helpmanual.io/usage/mypy/) fixed the issue for me.
