### ISSUE TITLE
Migrate codebase to an autoformater?

### ISSUE THREAD

**Issue by jasonkuhrt** [samuelcolvin/pydantic#281]
I cloned the codebase tonight to work on a few issues. Was wondering if @samuelcolvin you'd be open to using an autoformatter (yapf, black, ...) to manage the project's style, to make collaborating easier?

fwiw I have experience setting yapf and black up including integrating into CI.

**Comment by samuelcolvin** [comment]
I'll try them and give you an answer.

I'm afraid probably the answer is "no", I'm too used to reading code that looks like this.

**Comment by jasonkuhrt** [comment]
Sure!

**Comment by Gr1N** [comment]
`black` one love :)

**Comment by jasonkuhrt** [comment]
@Gr1N how do you feel about the long multi-item lines it enforces in the codebase?

**Comment by Gr1N** [comment]
@jasonkuhrt I feel nothing. When I started use `black` I had many complaints and WTFs, but now, thanks `balck`, code for me just a code which I (and my colleagues) can write in one style-guide.

**Comment by samuelcolvin** [comment]
Ok, I've just done some playing (and wasted 30 minutes of my life reading https://github.com/ambv/black/issues/118).

I'd be happy to switch to black provided we use `-S -l 120` (I'm not sure I'm ready yet to switch to double quotes), hopefully some day there will be a companion to black that enforces single quotes.

This will have another advantage that we can get away from flake8, pycodestyle and all that mess.

**Comment by Gr1N** [comment]
We can't get away from flake8, because black is only about code formatting and flake8 still can help you to show unused imports, vars or even possible bugs.

**Comment by samuelcolvin** [comment]
boring, but ok

**Comment by MartinThoma** [comment]
I'm confused by this. Does pydantic use black now? Because when I run black, I see 173 file changes.

**Comment by MartinThoma** [comment]
If black is used, you might want to consider to state this in the README with a badge:

```
[![Code style: black](https://img.shields.io/badge/code%20style-black-000000.svg)](https://github.com/psf/black)
```

**Comment by samuelcolvin** [comment]
Yes black is used, see the `Makefile` for configuration options.

No need for a badge for this, or isort or flake8 or mypy.
