### ISSUE TITLE
Unexpected casting order of List[Union[float, int]] when importing Pandas (1.2.4)

### ISSUE THREAD

**Issue by wfranceys** [samuelcolvin/pydantic#2835]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/wfranceys/tmp/pydantic-casting/.venv/lib/python3.7/site-packages/pydantic
               python version: 3.7.4 (default, Sep 13 2019, 10:50:17)  [Clang 10.0.1 (clang-1001.0.46.4)]
                     platform: Darwin-19.6.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Output of `python -c "import pandas as pd; print(pd.__version__)"`
```
1.2.4
```

```py
# main.py

from pydantic import BaseModel

from typing import List, Union

# Toggle import on and off to get different result
import pandas as pd

class Model(BaseModel):
    data: List[Union[float, int]]


data = [0.1234, 0.4567]
print(Model(data=data).dict())

```

What I would expect based on the behaviour of [Unions](https://pydantic-docs.helpmanual.io/usage/types/#unions):

```
{'data': [0.1234, 0.4567]}
```

What I see running the script above (with the `import pandas as pd`):

```
$ python main.py
{'data': [0, 0]}
```

What I see when removing the pandas import from above:

```
$ python main.py
{'data': [0.1234, 0.4567]}
```

# Notes

<details>
  <summary>Dockerfile to reproduce</summary>
  
Dockerfile: 
```
FROM python:slim-buster

RUN python -m pip install pydantic==1.8.2 pandas==1.2.4

# See above
COPY main.py .

CMD python main.py
```

Results:
```
$ docker build -t pydantic-test .
$ docker run -t pydantic-test
{'data': [0, 0]}
```
</details>

<details>
  <summary>Weirdness with pandas - what is causing the issue?</summary>
  

Now the part which looses me completely 

Added into this collapsible section as it seems like a red herring..

- Create a virtual environment (`.venv`): `python -m venv .venv`
- Activate the environment: `source .venv/bin/activate`
- Install dependencies: `  pip install pandas==1.2.4 pydantic==1.8.2`
- Run the main.py script above:

```
$ python main.py
{'data': [0, 0]}
```

- Go to `.venv/lib/python3.7/site-packages/pandas/io/formats/format.py`
- Go to ~L1565, it should look like

```
def format_percentiles(
    percentiles: Union[
        np.ndarray, List[Union[int, float]], List[float], List[Union[str, float]]
    ]
) -> List[str]:
```

- Remove the types on the input, it should now look like
```
def format_percentiles(
    percentiles
) -> List[str]:
```

- Now rerun the above script:

```
$ python main.py
{'data': [0.1234, 0.4567]}
```

And we now have the correct parsing again 🤔

Toggle the types on and off to get the correct results

</details>

**Comment by LeuDuan** [comment]
Actually I guess this has nothing to do with pydantic. It's something weird from pandas
You can try this snipnet (no pydantic model involved)

```python
from typing import List, Union

# Toggle import on and off to get different result
# import pandas as pd

class Model(object):
    data: List[Union[float, int]]

print(Model.__annotations__['data'])
```
It will print `typing.List[typing.Union[float, int]]` if pandas is not imported (which is correct) and print `typing.List[typing.Union[int, float]]`  (which is incorrect and leads to that behavior in your code) if pandas is imported.
Quite weird!

**Comment by PrettyWood** [comment]
Thanks @LeuDuan for catching this! The side effect comes indeed from `pandas`.
FYI @wfranceys it should not be a problem in v1.9 with [`Config.smart_union`](https://github.com/samuelcolvin/pydantic/pull/2092)

```py
from pydantic import BaseModel

from typing import List, Union

import pandas as pd


class Model(BaseModel, smart_union=True):
    data: List[Union[float, int]]


data = [0.1234, 0.4567]
assert Model(data=data).dict() == {'data': [0.1234, 0.4567]}
```

**Comment by wfranceys** [comment]
Thanks both @LeuDuan  @PrettyWood - good catch on the separation from Pydantic!

Will check in with `pandas`.

----

Indeed the side effect comes from `pandas` weirdly I can toggle some type annotations in Pandas (see the bottom of top post under "Weirdness with pandas - what is causing the issue?") which then removes this issue... 🤔

From (`pandas/io/formats/format.py`): 
```
def format_percentiles(percentiles: Union[np.ndarray, List[Union[int, float]], List[float], List[Union[str, float]]]) -> List[str]:
```

To: 

```
def format_percentiles(percentiles) -> List[str]:
```

**Comment by djpugh** [comment]
@PrettyWood it would probably be helpful to flag that this can occur in the docs - given https://docs.python.org/3/library/typing.html#typing.Union says

> When comparing unions, the argument order is ignored, e.g.:
> `Union[int, str] == Union[str, int]`

That the docs on https://pydantic-docs.helpmanual.io/usage/types/#unions should maybe have a warning about that

**Comment by djpugh** [comment]
it actually occurs in the Union arg directly
```
In [23]: x = typing.Union[int, float]

In [24]: y = typing.Union[float, int]

In [25]: x
Out[25]: typing.Union[int, float]

In [26]: y
Out[26]: typing.Union[float, int]

In [27]: x.__hash__()
Out[27]: -8081589475256396770

In [28]: y.__hash__()
Out[28]: -8081589475256396770
```

**Comment by djpugh** [comment]
I've opened a PR for a docs update #2839

**Comment by asmodehn** [comment]
Just a quick note that I experienced the same issue with `Optional[Union[float,str]]` and `import requests`

**Comment by asmodehn** [comment]
Tricky to track down, but it boils down to this:

The pydantic doc says:

> By default, as explained here, pydantic tries to validate (and coerce if it can) in the order of the Union. 

However there is no such thing as "the order of the Union" as explained in python docs : https://docs.python.org/3/library/stdtypes.html#types-union

```python
int | str == str | int
```
