### ISSUE TITLE
Pydantic allows weird types on field with nested model

### ISSUE THREAD

**Issue by elpapi42** [samuelcolvin/pydantic#2841]
Currently i have this script:

```python
from typing import List
from uuid import uuid4, UUID

from pydantic import BaseModel, Field


class Id(BaseModel):
    value:UUID = Field(default_factory=uuid4)

class User(BaseModel):
    id:Id = Field(default_factory=Id)
    roles:List[str] = ['student']

class Project(BaseModel):
    id:Id = Field(default_factory=Id)
    creator:User

id = Id()
print(id)

user = User()
print(user)

project = Project(creator={})
print(project)
````
The script should run as it is

When i instantiate a project, pydantic allows me to put non User objects, like dicts, strings, Id(objects of type Id) and some others, but i feel this is not expected. The weirdest thing is the fields are auto filled with an object of the correct type when a bad value is passed

what is happening here? Thanks in advance!

**Comment by mdavis-xyz** [comment]
This looks like desired behavior to me. What exactly is the issue?

Could you please modify the python script to add an assertion that would pass if the behavior matched what you want, and doesn't pass with today's existing behavior.

e.g. you say "put non User objects". Where? How? (`.parse_obj()` or `User(attr=val)`)

Note that the default behavior of pydantic is to *coerce* values into the schema. So if you give a list of ints to `roles`, those ints will be cast into strings.  (This can be changed per-model if required.)

**Comment by mdavis-xyz** [comment]
Note that something like `User(x='x')` will pass, and that's designed behavior, even though you're passing an unexpected argument and omitting the usual ones.

What's happening is that by default pydantic discards unexpected arguments (e.g. `x`). If you want the whole model to fail validation when unexpected additional fields are added, [set `extra` to `forbid`.](https://pydantic-docs.helpmanual.io/usage/model_config/).

All of your fields in all or your models have default values, so pydantic will use default values if they're missing.

**Comment by elpapi42** [comment]
Sorry for the delay, i studied Pydantic and learned that it does not enforce types on model instantiation, i managed to go around this, it was more a unexpected behavior from my side, but it is ok, thanks!
