### ISSUE TITLE
cannot create weak reference when mapping sqlalchemy to pydantic

### ISSUE THREAD

**Issue by BayerSe** [samuelcolvin/pydantic#2897]
# Bug

We are trying to map sqlalchemy queries to pydantic models as e.g. discussed [here](https://github.com/tiangolo/fastapi/issues/214). We're using `pydantic==1.8.2` and `sqlalchemy==1.4.17`.

This works well when we use the `pydantic.dataclasses.dataclass` decorator. It fails, however, when we sublass from `pydantic.BaseModel`. There, we get: `TypeError: cannot create weak reference to 'Data2' object`.

I was unsure if I should open this issue here or at [sqlalchemy](https://github.com/sqlalchemy/sqlalchemy) - so if you think the other issue tracker is more suitable please let me know and I'll approach them.

```py
import pydantic
from sqlalchemy import Column, String, create_engine, select
from sqlalchemy.orm import registry, Session

mapper_registry = registry()
Base = mapper_registry.generate_base()


class Table(Base):
    __tablename__ = "table"

    id = Column(String, primary_key=True)


@pydantic.dataclasses.dataclass
class Data1:
    id: str


class Data2(pydantic.BaseModel):
    id: str


if __name__ == "__main__":
    engine = create_engine("sqlite:///:memory:", echo=True)
    Base.metadata.create_all(engine)

    select_id = select(Table.id).subquery()

    mapper_registry.map_imperatively(Data1, select_id)
    mapper_registry.map_imperatively(Data2, select_id)

    with Session(engine) as session:
        session.add(Table(id="id"))

        q1 = session.query(Data1).all()
        q2 = session.query(Data2).all()
```

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/bay2rng/.local/share/virtualenvs/p356_rtp_production_scheduling-03q6S6S0/lib/python3.9/site-packages/pydantic
               python version: 3.9.4 (default, Apr  9 2021, 01:10:48)  [GCC 7.5.0]
                     platform: Linux-4.15.0-142-generic-x86_64-with-glibc2.27
     optional deps. installed: ['typing-extensions']

```

**Comment by PrettyWood** [comment]
Hi @BayerSe 
Can you try with https://github.com/samuelcolvin/pydantic/discussions/2857#discussioncomment-802379?

**Comment by BayerSe** [comment]
Hi @PrettyWood thanks for the quick feedback!

This indeed resolved the first error!

Now I'm getting: `ValueError: "Data2" object has no field "_sa_instance_state"`

**Comment by PrettyWood** [comment]
You are not using sqlalchemy + pydantic correctly. You are not supposed to use the `BaseModel` directly in your query.

```py
from sqlalchemy import Column, String, create_engine, select
from sqlalchemy.orm import registry, Session

import pydantic
from pydantic.dataclasses import dataclass

mapper_registry = registry()
Base = mapper_registry.generate_base()


class Table(Base):
    __tablename__ = "table"

    id = Column(String, primary_key=True)


@dataclass
class DataCls:
    id: str


class Data(pydantic.BaseModel):
    id: str

    class Config:
        orm_mode = True


engine = create_engine("sqlite:///:memory:", echo=True)
Base.metadata.create_all(engine)

select_id = select(Table.id).subquery()

mapper_registry.map_imperatively(DataCls, select_id)

with Session(engine) as session:
    session.add(Table(id="id"))

    q1 = session.query(DataCls).one()

pydantic_q1 = Data.from_orm(q1)
```

Check the [doc](https://pydantic-docs.helpmanual.io/usage/models/#orm-mode-aka-arbitrary-class-instances)

**Comment by BayerSe** [comment]
Thank you for the pointer!

The interim step with
```py 
mapper_registry.map_imperatively(DataCls, select_id)
```
is not even necessary.

This here works perfectly:
```py
import pydantic
from sqlalchemy import Column, String, create_engine, select
from sqlalchemy.orm import registry, Session

mapper_registry = registry()
Base = mapper_registry.generate_base()


class Table(Base):
    __tablename__ = "table"

    id = Column(String, primary_key=True)


class Data(pydantic.BaseModel):
    id: str

    class Config:
        orm_mode = True


engine = create_engine("sqlite:///:memory:", echo=True)
Base.metadata.create_all(engine)

select_id = select(Table.id).subquery()

with Session(engine) as session:
    session.add(Table(id="id"))

    q1 = session.query(select_id).one()

pydantic_q1 = Data.from_orm(q1)
```

**Comment by isac322** [comment]
@BayerSe @PrettyWood
You don't have to use declarative and `from_orm`.
Imperative mapping is more performant than Declarative one in this case because you don't have to parse object via `from_orm`.
In this way, you can use all validation functionality of pydantic.
```py3
from typing import Any

import pydantic
from sqlalchemy import Column, String, Table, create_engine
from sqlalchemy.orm import Session, registry
from sqlalchemy.orm.base import DEFAULT_STATE_ATTR

mapper_registry = registry()


@pydantic.dataclasses.dataclass
class Data1:
    id: str


SQLAlchemyBaseModel = pydantic.create_model(
    'SQLAlchemyBaseModel',
    **{DEFAULT_STATE_ATTR: (Any, pydantic.PrivateAttr())},
    __slots__='__weakref__',
    __abstract__=True,
)


class Data2(SQLAlchemyBaseModel):
    id: str


_table = Table(
    'table',
    mapper_registry.metadata,
    Column('id', String, primary_key=True),
)

if __name__ == "__main__":
    mapper_registry.map_imperatively(Data1, _table)
    mapper_registry.map_imperatively(Data2, _table)

    engine = create_engine("sqlite:///:memory:", echo=True)
    mapper_registry.metadata.create_all(engine)

    with Session(engine) as session:
        session.add(Data2(id="id"))

        q1 = session.query(Data1).all()
        q2 = session.query(Data2).all()
```

**Comment by BayerSe** [comment]
Thank you, @isac322; that looks interesting as well. For now we settled on the `from_orm` version but I will keep it in mind when touching this are of the code again.

**Comment by zulrang** [comment]
> @BayerSe @PrettyWood
> You don't have to use Declarative Mapping and `from_orm`.
> Imperative Mapping is more performant than Declarative one in this case because you don't have to parse object via `from_orm`.
> In this way, you can use all validation functionality of pydantic.
> 
> ```python
> from typing import Any
> 
> import pydantic
> from sqlalchemy import Column, String, Table, create_engine
> from sqlalchemy.orm import Session, registry
> from sqlalchemy.orm.base import DEFAULT_STATE_ATTR
> 
> mapper_registry = registry()
> 
> 
> @pydantic.dataclasses.dataclass
> class Data1:
>     id: str
> 
> 
> SQLAlchemyBaseModel = pydantic.create_model(
>     'SQLAlchemyBaseModel',
>     **{DEFAULT_STATE_ATTR: (Any, pydantic.PrivateAttr())},
>     __slots__='__weakref__',
>     __abstract__=True,
> )
> 
> 
> class Data2(SQLAlchemyBaseModel):
>     id: str
> 
> 
> _table = Table(
>     'table',
>     mapper_registry.metadata,
>     Column('id', String, primary_key=True),
> )
> 
> if __name__ == "__main__":
>     mapper_registry.map_imperatively(Data1, _table)
>     mapper_registry.map_imperatively(Data2, _table)
> 
>     engine = create_engine("sqlite:///:memory:", echo=True)
>     mapper_registry.metadata.create_all(engine)
> 
>     with Session(engine) as session:
>         session.add(Data2(id="id"))
> 
>         q1 = session.query(Data1).all()
>         q2 = session.query(Data2).all()
> ```

Your example doesn't work.  When just trying to instantiate the Model, you get:
```
/lib/python3.9/site-packages/sqlalchemy/orm/base.py in _is_mapped_class(entity)
    357     return (
    358         insp is not None
--> 359         and not insp.is_clause_element
    360         and (insp.is_mapper or insp.is_aliased_class)
    361     )

AttributeError: 'tuple' object has no attribute 'is_clause_element'
```

**Comment by zulrang** [comment]
> @BayerSe @PrettyWood
> You don't have to use Declarative Mapping and `from_orm`.
> Imperative Mapping is more performant than Declarative one in this case because you don't have to parse object via `from_orm`.
> In this way, you can use all validation functionality of pydantic.
> 
> ```python
> from typing import Any
> 
> import pydantic
> from sqlalchemy import Column, String, Table, create_engine
> from sqlalchemy.orm import Session, registry
> from sqlalchemy.orm.base import DEFAULT_STATE_ATTR
> 
> mapper_registry = registry()
> 
> 
> @pydantic.dataclasses.dataclass
> class Data1:
>     id: str
> 
> 
> SQLAlchemyBaseModel = pydantic.create_model(
>     'SQLAlchemyBaseModel',
>     **{DEFAULT_STATE_ATTR: (Any, pydantic.PrivateAttr())},
>     __slots__='__weakref__',
>     __abstract__=True,
> )
> 
> 
> class Data2(SQLAlchemyBaseModel):
>     id: str
> 
> 
> _table = Table(
>     'table',
>     mapper_registry.metadata,
>     Column('id', String, primary_key=True),
> )
> 
> if __name__ == "__main__":
>     mapper_registry.map_imperatively(Data1, _table)
>     mapper_registry.map_imperatively(Data2, _table)
> 
>     engine = create_engine("sqlite:///:memory:", echo=True)
>     mapper_registry.metadata.create_all(engine)
> 
>     with Session(engine) as session:
>         session.add(Data2(id="id"))
> 
>         q1 = session.query(Data1).all()
>         q2 = session.query(Data2).all()
> ```

Your example doesn't work:
```
<ipython-input-2-7c51403c4f17>:16: RuntimeWarning: fields may not start with an underscore, ignoring "_sa_instance_state"
  SQLAlchemyBaseModel = pydantic.create_model(
<ipython-input-2-7c51403c4f17>:16: RuntimeWarning: fields may not start with an underscore, ignoring "__slots__"
  SQLAlchemyBaseModel = pydantic.create_model(
<ipython-input-2-7c51403c4f17>:16: RuntimeWarning: fields may not start with an underscore, ignoring "__abstract__"
  SQLAlchemyBaseModel = pydantic.create_model(
```
