### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#29]
* clean methods
* more explanation on usage
* more benchmarks
* Any

**Comment by pauleveritt** [comment]
@samuelcolvin Are the clean_ methods implemented in any way? I don't see "clean" in the source anywhere.

Here's the use case: I want to have an img_url *or* an img_src, but not both. If both, or neither, are supplied, I want to raise an exception. Will that fit what you have in mind for the clean methods?

**Comment by samuelcolvin** [comment]
Currently implemented via `validate_*` but not documented properly as I mean to change it completely.

**Comment by pauleveritt** [comment]
Is the usage I described a valid use case for what you intend to do?

**Comment by pauleveritt** [comment]
Actually if you're going to change it then I'll avoid bugging you about it. No sense making you write stuff down, I can wait.

**Comment by samuelcolvin** [comment]
That's exactly the kind of use case.

**Comment by samuelcolvin** [comment]
This should be fixed by version v0.6.

@pauleveritt documentation should now be available on validators, see [here](https://pydantic-docs.helpmanual.io/#validators).

**Comment by pauleveritt** [comment]
@samuelcolvin Thanks for working on this, and perfect timing, I'm in an overhaul. FWIW, I'm working on a system to put structured YAML data in Sphinx docs, validated by pydantic.

**Comment by pauleveritt** [comment]
@samuelcolvin As an FYI, I'm using pydantic in an extensible system atop Sphinx. You register classes with models and can then embed schema-validated YAML in documents: https://github.com/pauleveritt/kaybee/blob/master/docs/features.rst#yaml-models
