### ISSUE TITLE
Q: How to get memory usage of a pydantic object?

### ISSUE THREAD

**Issue by ramazanpolat** [samuelcolvin/pydantic#290]
# Question 

Trying to get the memory usage of a pydantic object.
``sys.getsizeof`` works for most objects but not in this case.
It always return 64 for a pydantic object.

```py
import pydantic
from sys import getsizeof

from pydantic import BaseModel


class Sample(BaseModel):
    a: int
    b: str
    c: float


s1 = Sample(a=1, b='b', c=1.1)

print(getsizeof(s1))  # 64

s1.b = 'longer string-> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum'

print(getsizeof(s1)) # 64

...
```

**Comment by samuelcolvin** [comment]
Directly form [python's docs](https://docs.python.org/3.6/library/sys.html#sys.getsizeof)

> Only the memory consumption directly attributed to the object is accounted for, not the memory consumption of objects it refers to.

in other words, `getsizeof` wouldn't work on a `dict` or `list` or any other structure. So why would you expect it to work on pydantic models?

I suggest you use a variant of the recipes referenced in the docs., perhaps operating on `s1.__values__`

**Comment by ramazanpolat** [comment]
> So why would you expect it to work on pydantic models?

Because I am relatively new to Python, that's why.
Also, there is a [benchmark ](https://pydantic-docs.helpmanual.io/#benchmarks) section in documents which is great. I thought it would be much more complete if documentation also mentioned about memory footprint of pydantic objects. 

BTW, ``s1.__values__`` worked for that matter. Thanks.

**Comment by samuelcolvin** [comment]
> So why would you expect it to work on pydantic models?

Sorry to be rude, busy day.

Pleased you found the solution.
