### ISSUE TITLE
BaseSettings evaluates default_factory on class definition

### ISSUE THREAD

**Issue by ShadowLNC** [samuelcolvin/pydantic#2940]
## Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

Similar to #1670 but this applies to `BaseSettings`, not `BaseModel`.

## Example File

```py
from pydantic import BaseModel, BaseSettings, Field

def _gen() -> str:
    print("Called")
    return "x"

print("Pre Settings definition")

class Settings(BaseSettings):
    val: str = Field(default_factory=_gen)

print("Post Settings definition")
Settings()
print("Post instantiation")
```

## Expected Behaviour

`_gen` should not be called during the definition of the `Settings` class (as per #1670 ).

## Actual behaviour

It is called. This raises `NameError` as my factory function (the real one, not the example) is referencing things that aren't yet defined (though I can reorder my code).

If I swap `BaseSettings` for `BaseModel`, it is not called (matches expected behaviour).

## Version

```
>>> print(pydantic.utils.version_info())
             pydantic version: 1.8.2
            pydantic compiled: False
                 install path: ...\.venv\Lib\site-packages\pydantic
               python version: 3.10.0b3 (tags/v3.10.0b3:865714a, Jun 17 2021, 20:39:25) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.19042-SP0
     optional deps. installed: ['dotenv', 'typing-extensions']
```

**Comment by PrettyWood** [comment]
Hi @ShadowLNC 
A fix #2566 has already been done and merged for this.
It will be available in next version 1.9.
In the meantime feel free to either:
- wait for v1.9
- install `pydantic` from git with this PR
`$ pip install git+git://github.com/samuelcolvin/pydantic.git@31c4efb7f05d9c45e187591af7bf331e72719b71`
- use your own fork
Cheers

**Comment by ShadowLNC** [comment]
Apologies - obviously I missed this one when searching. Thanks for the info 😃

**Comment by samuelcolvin** [comment]
When I have time, probably September.
