### ISSUE TITLE
mypy plugin errors with custom __init__

### ISSUE THREAD

**Issue by tlambert03** [samuelcolvin/pydantic#2949]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/pydantic
               python version: 3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:27:35)  [Clang 11.1.0 ]
                     platform: macOS-11.3.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']

                   (and) mypy: mypy-0.910
```

I'm trying to use the mypy plugin with a custom `__init__` method.  Taking the example from the [docs](https://pydantic-docs.helpmanual.io/usage/models/#model-signature):

```py
from pydantic import BaseModel

class MyModel(BaseModel):
    id: int
    info: str = 'Foo'

    def __init__(self, id: int = 1, *, bar: str, **data) -> None:
        super().__init__(id=id, bar=bar, **data)
```

It seems like it should be valid to initialize with a positional argument in this case:

```py
assert MyModel(4, bar='foo').id == 4
```

however, mypy complains

```sh
t.py:13: error: Too many positional arguments for "MyModel"
Found 1 error in 1 file (checked 1 source file)
```

(mypy settings)
```ini
[mypy]
plugins = pydantic.mypy
```

additionally... if I add `init_forbid_extra = True` to the mypy settings, then I also get the `Unexpected keyword argument "bar" for "MyModel"`, even though that too is actually required by the `__init__` method.

Is this a bug, or am I missing the intention of the plugin?  (happy to take a stab at fixing if it's a bug)

**Comment by tlambert03** [comment]
can anyone confirm whether this is indeed a bug or not?

**Comment by tlambert03** [comment]
cc @dmontagu (based on the mypy plugin blame).  should the mypy plugin be compatible with positional args in a custom init?

**Comment by meijie-yamamoto** [comment]
I'm having the same problem.
As long as I've been using pydantic.mypy, there didn't seem to be a setting to avoid this error.
I would like to see a pydantic.mypy configuration item that allows positional arguments.

**Comment by keithrfung** [comment]
I'm having this same issue. You can add more __init__'s to try to resolve the problem and then it just shifts.

**Comment by pawelswiecki** [comment]
The same here, **pydantic `1.9.0`**, **mypy `0.942`** (as well as **`0.950`**), **Python `3.10.3`**.

**Comment by samuelcolvin** [comment]
I don't think we can realistically support this.

There might be a way to disable the plug-in on a per-model basis and fallback to dataclass transforms.
