### ISSUE TITLE
Root validator error

### ISSUE THREAD

**Issue by mmorri21** [samuelcolvin/pydantic#2950]
When running [this snippet](https://pydantic-docs.helpmanual.io/usage/validators/#root-validators) with version 1.8.2, I encounter the following:

```
Traceback (most recent call last):
  File "pydantic/main.py", line 408, in pydantic.main.BaseModel.__init__
TypeError: __dict__ must be set to a dictionary, not a 'NoneType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 410, in pydantic.main.BaseModel.__init__
TypeError: Model values must be a dict; you may not have returned a dictionary from a root validator
```

I am encountering this error in any attempts to use root_validator.

**Comment by PrettyWood** [comment]
There is an issue template for a reason... Snippets are run when building doc so if the output is different we need more information. Please recreate it and fill up the needed information
PS: a "hi" never hurts
