### ISSUE TITLE
Config.max_anystr_length works only for __init__

### ISSUE THREAD

**Issue by ramazanpolat** [samuelcolvin/pydantic#297]
# Bug

* OS: **Windows 7 x64**
* Python version: **3.6.6**
* Pydantic version: **0.14**

``Config.max_anystr_length`` is only respected when object instantiated.

```py
import pydantic

class Image(BaseModel):
    img_id: int = None
    img_base64: str = None

params = {"img_id": 1, "img_base64": "data:image/jpeg;base64....REALLY_LONG_STRING..."}
img = Image(**params)
# pydantic.error_wrappers.ValidationError: 1 validation error
# img_base64
#   ensure this value has at most 65536 characters (type=value_error.any_str.max_length; 
# limit_value=65536)
```
Since default value for ``Config.max_anystr_length`` is 2^16 and my img_base64 is larger than 2^16, this is expected but setting ``img_base64`` after instantiation works without any validation error:

```py
...
params = {"img_id": 1, "img_base64": "data:image/jpeg;base64....REALLY_LONG_STRING..."}
img = Image()
img.img_id = params["img_id"]
img."img_base64" = params[""img_base64""]
print(img)
# Image img_id=1 img_base64='data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAQEBAQEBAQ…'
```

**Comment by samuelcolvin** [comment]
Looks like you didn't set the [`validate_assignment` config option](https://pydantic-docs.helpmanual.io/#config).
