### ISSUE TITLE
Validation error "value is not a valid dict" w/ Union[List[model], List[basetype]]

### ISSUE THREAD

**Issue by gistart** [samuelcolvin/pydantic#2973]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

I need to receive a list of objects, but these are simple objects that I can easily construct from one of their fields, so I declare a Union, and add a simple parser as `root_validator` to support both formats. Problem is when input is incorrect, error message from the library is confusing:
1. it suggests every element in the list is invalid
2. description message is kind of misleading, it may confuse user more than actually help.

Example:
```python
from typing import List, Union
from pydantic import version, BaseModel

class Sub(BaseModel):
    val: str

class Main(BaseModel):
    id: int
    subs: Union[List[Sub], List[str]]

print("pydantic version:", version.VERSION)
Main(id=1, subs=["a", [1,2], "b"])
```

Output:
```
pydantic version: 1.8.2
Traceback (most recent call last):
  File "./pyderr.py", line 12, in <module>
    Main(id=1, subs=["a", [1,2], "b"])
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 4 validation errors for Main
subs -> 0
  value is not a valid dict (type=type_error.dict)
subs -> 1
  value is not a valid dict (type=type_error.dict)
subs -> 2
  value is not a valid dict (type=type_error.dict)
subs -> 1
  str type expected (type=type_error.str)
```

Ideally, in this case error message should be just `subs -> 1:  str type expected (type=type_error.str)`. 

Maybe errors are collected from all parsers in union, it could explain this behaviour.

**Comment by smoshkovits** [comment]
The validations try to consume the input as a whole.
For your input of ["a", [1,2], "b"] 

The input is not a List[str] - so you get 1 error "str type is expected"

On the other hand

The input is not a List[Sub] - so you get 3 errors "value is not a valid dict"


The errors are sum of the errors of each validator. What you describe is more of a case of you wanting to get the validation that failed the least, which is (in my opinion) not the correct report.

**Comment by samuelcolvin** [comment]
This is not a bug.
