### ISSUE TITLE
Mypy plugin fails when configured from `pyproject.toml`

### ISSUE THREAD

**Issue by jgerityneurala** [samuelcolvin/pydantic#2981]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
$ python3.8 -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.8.1
            pydantic compiled: True
                 install path: /home/jgerity/.local/lib/python3.8/site-packages/pydantic
               python version: 3.8.7 (default, Feb 16 2021, 16:20:43)  [GCC 9.2.1 20191008]
                     platform: Linux-5.3.0-64-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
```

# Bug

Mypy can be [configured via `pyproject.toml`](https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml-file), but pydantic's mypy plugin [seems to assume](https://github.com/samuelcolvin/pydantic/blob/a4cb4ee3bc57911a18b13643c44ab14e2ea28d33/pydantic/mypy.py#L113-L114) that it has always been configured by `mypy.ini`. When this assumption is particularly bad, it causes a fatal error

## Details
In particular, the INI parser does not understand options that are specified across multiple lines, and I have experienced `configparser.DuplicateOptionError` when configuring `filterwarnings` for pytest (it thinks the multiple `"ignore::..."` lines are dupes), as well as `configparser.ParsingError` with multi-line strings (namely when setting `tool.pylint.TYPECHECK.generated-members`). A reproduction is given below.

I can suppress the errors I've experienced by reworking my `pyproject.toml` to avoid the incompatibility between `ConfigParser` and TOML, but it's likely there are user configurations that do not have this option at all.

# Reproduction

## Files
* `test.py` (empty)
* `pyproject.toml`:
  ```toml
  [tool.mypy]
  plugins = "pydantic.mypy"

  [tool.pytest.ini_options]
  filterwarnings = [
  "ignore::FooWarning:",
  "ignore::BarWarning:"
  ]
  ```

## Output
```
$ python3.8 -m mypy .
Error constructing plugin instance of PydanticPlugin

Traceback (most recent call last):
  File "/home/jgerity/.pyenv/versions/3.8.7/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jgerity/.pyenv/versions/3.8.7/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jgerity/.pyenv/versions/3.8.7/lib/python3.8/site-packages/mypy/__main__.py", line 23, in <module>
    console_entry()
  File "/home/jgerity/.pyenv/versions/3.8.7/lib/python3.8/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 87, in main
  File "mypy/main.py", line 165, in run_build
  File "mypy/build.py", line 179, in build
  File "mypy/build.py", line 229, in _build
  File "mypy/build.py", line 475, in load_plugins
  File "mypy/build.py", line 453, in load_plugins_from_config
  File "pydantic/mypy.py", line 77, in pydantic.mypy.PydanticPlugin.__init__
  File "pydantic/mypy.py", line 114, in pydantic.mypy.PydanticPluginConfig.__init__
  File "/home/jgerity/.pyenv/versions/3.8.7/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/home/jgerity/.pyenv/versions/3.8.7/lib/python3.8/configparser.py", line 1093, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from 'pyproject.toml' [line  7]: option '"ignore' in section 'tool.pytest.ini_options' already exists
```

# Suggested fix

It seems to me that checking if  `options.config_file` ends in `.toml` and using an appropriate TOML parser in that case would suffice to avoid this problem, if the external dependency is not a show-stopper. Otherwise, it might be a good idea to catch `configparser.Error` when calling `ConfigParser.read()`, and maybe emit a more useful error message if the `options.config_file` has this suffix.

**Comment by johnthagen** [comment]
Duplicate of #2895

**Comment by jgerityneurala** [comment]
Oops, didn't realize this was already tracked. Thanks, closing.
