### ISSUE TITLE
Pydantic as mongo ORM

### ISSUE THREAD

**Issue by ramazanpolat** [samuelcolvin/pydantic#300]
# Need your ideas for a possible Pydantic extension

Hello, although I am new to Python ecosystem, I've found that pydantic is really helpful on lots of cases. In fact, I've tried to write something similar named [Prodict](https://github.com/ramazanpolat/prodict) but noticing pydantic, I quit developing it in favor of pydantic. Because it looks like you guys already did most of the work what I wanted to do with Prodict. Thank you this awesome package!

I've developed a MongoDB document mapper with pydantic.
It converts pymongo ``find`` and ``find_one`` results to pydantic objects. The usage is almost exactly same, the only difference is if you provide a class derived from ``BaseModel``, the result is mapped to an object instantiated from that class.

```py
from pydantic import BaseModel
import pymongodantic

class Customer(BaseModel):
    _id: Any
    name: str
    age: int

mongo_client = MongoClient(...).get_database('test')
customers_table = ModeledCollection(database=db_test, name='customers').
customer = customers_table.find_one({'name':'john'}, model=Customer)
print(customer)
# Customer _id = ObjectId("...."), name = 'john', age=25

# It also works for find_one
customers = customers_table.find({}, model=Customer)
for customer in customers:
    print(isinstance(customer, Customer))  # True

```

So my question is:
Would you consider to make ``pymongodantic`` an extension of ``pydantic`` like ``ujson``?
If so, what should I do?

**Comment by samuelcolvin** [comment]
I think you're slightly confused about extenions/dependencies.

pydantic has a few dependencies, eg. `dataclasses` and optionally `ujson`.

In turn, some other packages have pydantic as a dependency of them, you can see an incomplete list of them [here](https://libraries.io/pypi/pydantic) under "Used by".

I'd be very flattered if you use pydantic in your package, I'm fine with you calling it `pymongodantic`. I'll even try to help where possible with advice or any changes you need to pydantic.

It wouldn't make sense to make `pymongodantic` a dependency of `pydantic`, indeed you'd end up with circular dependencies and nothing would work.

Hope that makes sense. I'll close this but feel free to comment again if you have any more questions.

**Comment by ramazanpolat** [comment]
Ok, what if pydantic would have an optional dependency, pymongo?
If pydantic installed with ``pydantic[pymongo]``, then developers could use pydantic as mapped object to mongodb document.

I think I should create the repo for ``pymongodantic`` first, then you will see how it makes sense to use pydantic as an object mapped to mongodb document. I already made it using ``Prodict`` and created [mongoman](https://github.com/ramazanpolat/mongoman) but since I've started using pydantic for all my projects, I will rewrite it for pydantic.

You have a better name in your mind, other than ``pymongodantic``?

**Comment by pauleveritt** [comment]
I agree with @samuelcolvin the pydantic project itself shouldn't have any connection to mongo, even optional. Let's not sign pydantic up for any obligations more than its job.

**Comment by samuelcolvin** [comment]
I don't mind about names.

For me it doesn't make sense to have an optional dependency of `pymongo`, it's very easy to install both (just `pip install pydantic pymongo`) and pydantic itself has no requirements for pymongo.

**Comment by RamiAwar** [comment]
I've developed a wrapper around PyMongo and Pydantic that would make this easy, hope somebody finds this useful:

https://ramiawar.github.io/Mongomantic/

**Comment by gustavorps** [comment]
Nice work @RamiAwar!
Why is ready-only?

**Comment by RamiAwar** [comment]
> Nice work @RamiAwar! Why is archived and read-only?

Thanks, I marked it that way today actually, I felt like I won't be working on this anytime soon and there are better alternatives out there now with full async support and fancy sprinkles. Mine was just something I hacked together in a couple of days for a small project that I ended up quitting on!

**Comment by manditri** [comment]
> > Nice work @RamiAwar! Why is archived and read-only?
> 
>  there are better alternatives out there now with full async support and fancy sprinkles

@RamiAwar what are these better alternatives that you mentioned. I have been looking for something in this direction. Thanks.

**Comment by j-riebe** [comment]
@manditri Have a look at this: https://github.com/roman-right/beanie
