### ISSUE TITLE
distinctions between `allow_extra` and `ignore_extra` options 

### ISSUE THREAD

**Issue by alexyiu875** [samuelcolvin/pydantic#301]
# Question 

For bugs/questions:
* OS: **macOS 10.13.6**
* Python version: **3.6.6**
* Pydantic version: **0.14**

I am relatively new to pydantic. This is one of most well-documented (also concise) Open Source Project that I have encountered so far. Thank you for great work so far. 

I am looking at documentation of 2 options:
```
ignore_extra: | whether to ignore any extra values in input data (default: True)
allow_extra: | whether or not too allow (and include on the model) any extra values in input data (default: False)
```

We may be able to improve clarity of distinctions between these 2 options.
At first glance, `allow_extra` and `ignore_extra` options have quite a bit overlapping. 

Based on my own trials of these 2 configuration options (4 combinations): 
```
    class Config: 
        ignore_extra = True    	
        allow_extra = False
```
This combination makes sense by dropping any extra fields from the input data. 

```
    class Config: 
        ignore_extra = False   	
        allow_extra = True
```
As far as I can tell, allow_extra essentially overrides ignore_extra behavior. 
No ValidationError would be raised. 

```
    class Config: 
        ignore_extra = True    	
        allow_extra = True
```
As far as I can tell, allow_extra essentially overrides ignore_extra behavior. 
Any extra field from input data would be stored in the target Python data object. 

```
    class Config: 
        ignore_extra = False
        allow_extra = False
```
(Trivial) ValidationError would be raised. 

Maybe, we can consider the following wordings in the documentation: 
```
ignore_extra: | whether to ignore any extra values in input data; if this option is set to be true, any extra attributes will be dropped without raising a ValidationError (default: True)
allow_extra: | whether or not to allow (and include on the model) any extra values from input data to be stored as attributes of Python data object; when allow_extra option is set to be true, that will essentially override ignore_extra option  (default: False)
```

Thoughts? 
Thanks again.

**Comment by alexyiu875** [comment]
(Note: the above testing is based on `BaseModel` usage pattern, when I test it with `@dataclass` pattern, it has another set of behavior, which I would file another issue )

**Comment by samuelcolvin** [comment]
Makes sense, please submit a PR to update the docs.

**Comment by samuelcolvin** [comment]
thanks for pointing this out, I agree it could be clearer.

**Comment by alexyiu875** [comment]
Thank you for following this up. 
Just to confirm the target of this PR would be this file, right? 
https://github.com/samuelcolvin/pydantic/blob/master/docs/index.rst
