### ISSUE TITLE
Bug with dataclass attribute when value is set to a subclass of a dataclass

### ISSUE THREAD

**Issue by robons** [samuelcolvin/pydantic#3011]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/yyy/.local/share/virtualenvs/x-d3EKqbxH/lib/python3.9/site-packages/pydantic
               python version: 3.9.5 (default, May  4 2021, 03:33:11)  [Clang 12.0.0 (clang-1200.0.32.29)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['devtools', 'typing-extensions']
```

```py
from dataclasses import dataclass
import pydantic.dataclasses


@dataclass
class A:
    thing_a: str


class B(A):
    thing_b: str


class Config:
    arbitrary_types_allowed = True


@pydantic.dataclasses.dataclass(config=Config)
class C:
    thing: A


b = B("Thing A")
c = C(thing=b)
print(c)
```

Resulting output:

```
Traceback (most recent call last):
  File "/Users/yyy/Library/Application Support/JetBrains/PyCharm2021.1/scratches/scratch_7.py", line 23, in <module>
    c = C(b)
  File "<string>", line 4, in __init__
  File "pydantic/dataclasses.py", line 99, in pydantic.dataclasses._generate_pydantic_post_init._pydantic_post_init
    # | True  | add   |       |  <- the default
pydantic.error_wrappers.ValidationError: 1 validation error for C
a
  instance of A, tuple or dict expected (type=type_error.dataclass; class_name=A)

Process finished with exit code 1
```

The above code is perfectly valid since `thing` is of type `B`, hence also of type `A`.

Note that the above code behaves identically when `B` is marked as a `@dataclass` too. 

Also note that if I run the following code where `A` and `B` are not `dataclass`es (and I allow arbitrary types), we find that `C` validates without issue. This is the behaviour I would expect when `A` or `B` are `@dataclass`es

```python
from dataclasses import dataclass
import pydantic.dataclasses


class A:
    thing_a: str


class B(A):
    thing_b: str


class Config:
    arbitrary_types_allowed = True


@pydantic.dataclasses.dataclass(config=Config)
class C:
    thing: A


b = B()
c = C(thing=b)
print(c)
```

**Comment by PrettyWood** [comment]
Hi @robons 
Before I look at your PR I first want to talk about the issue here.
You say you expect `B` to be valid for `A` but I would say "it depends"
This is the whole issue with covariance/contravariance. For example
```py
from pydantic.dataclasses import dataclass


@dataclass
class A:
    x: str


@dataclass
class B(A):
    y: int


a = A(x='a')
b = B(x='a', y=1)

try:
    A(x='a', y=1)
    assert False
except Exception:
    assert True

assert isinstance(b, A)
```

If I had a `list[A]`, I could or could not expect my values to have extra attributes other than `x`
So I see your point but I'm afraid it's not always desired and we should consider a more generic approach depending on the desired behaviour
