### ISSUE TITLE
`copy()` does not correctly parse sub-models in `update` dict

### ISSUE THREAD

**Issue by djpetti** [samuelcolvin/pydantic#3039]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/daniel/git/mallard/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.0 (default, Jan 13 2021, 09:58:55)  [GCC 9.3.0]
                     platform: Linux-5.8.0-63-generic-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'typing-extensions']
...
```

I've noticed some odd behavior of the `copy()` method when used on models that include sub-models. To illustrate, I will borrow the example from the documentation:

```py
from pydantic import BaseModel


class BarModel(BaseModel):
    whatever: int


class FooBarModel(BaseModel):
    banana: float
    foo: str
    bar: BarModel


m = FooBarModel(banana=3.14, foo='hello', bar={'whatever': 123})

print(m.copy(update={"bar": {"whatever": 1}}))
```

Expected output:

```
banana=3.14 foo='hello' bar=BarModel(whatever=1)
```

Actual output:

```
banana=3.14 foo='hello' bar={'whatever': 1}
```

The fact that `bar` is set as a raw dict instead of a `BarModel` appears to violate the typing constraints imposed by the model definitions.

**Comment by PrettyWood** [comment]
Hi @djpetti 
It's not a bug (see https://github.com/samuelcolvin/pydantic/issues/1351).
The documentation could be more explicit on the behaviour of copy that acts like `construct()`.
