### ISSUE TITLE
support Sequence

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#304]
### Feature Request

`Sequence` should be supported, I guess list and tuple should work, anything else?

**Comment by samuelcolvin** [comment]
Useful when you want a `Tuple` but don't yet know it's length.

**Comment by pilosus** [comment]
> Useful when you want a Tuple but don't yet know it's length.
Isn't a ``Sequence`` type always has ``__len__`` and ``__getitem__`` methods, so length should be known.
Could you give an example?

 > I guess list and tuple should work, anything else?
``range`` maybe?

**Comment by samuelcolvin** [comment]
I guess the Tuple case we can support with `Tuple[int, ...]` etc.

Point of `Sequence` would just be to allow either `List` or `Tuple`.
