### ISSUE TITLE
Deserialisation of a standard dataclass with __post_init__ can fail due to wrong field types

### ISSUE THREAD

**Issue by barisione** [samuelcolvin/pydantic#3046]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /usr/local/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Jul 21 2020, 10:42:08)  [Clang 11.0.0 (clang-1100.0.33.17)]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
import dataclasses
from typing import Set

import pydantic


@dataclasses.dataclass
class SetWrapper:
    set: Set[int]

    def __post_init__(self):
        assert isinstance(
            self.set, set
        ), f"self.set should be a set but it's {self.set!r} of type {type(self.set).__name__}"


class Model(pydantic.BaseModel):
    set_wrapper: SetWrapper


model = Model(set_wrapper=SetWrapper({1, 2, 3}))
print(f"Created model: {model}")
json_text = model.json()
print(f"Serialised model: {json_text}")

Model.parse_raw(json_text)
...
```

The behaviour of `__post_init__`/`__post_init_post_parse__` is clearly documented in https://pydantic-docs.helpmanual.io/usage/dataclasses/#initialize-hooks but this is a standard Python dataclass, not a pydantic one, so it's behaviour should not change just because we are converting some JSON.

**Comment by PrettyWood** [comment]
Hi @barisione 
I added https://github.com/samuelcolvin/pydantic/pull/2557/commits/aa03d6a1dbacc4f0852c116d6237276ecd8dec02#diff-3e3db6df6bdaeed8dd98e5be4a800b1e02fcbf5701f8486d1c577d72612a43a8R1192 in my PR
Feedback welcome :)

**Comment by barisione** [comment]
The change seems good and it looks like the current behaviour is tested by `test_post_init_post_parse_types`.
Maybe it's worth adding a comment in `test_post_init_post_parse_types` referencing the alternative behaviour and the new test you wrote, and vice versa.
