### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions' when using pipenv and python 3.8

### ISSUE THREAD

**Issue by namoscagnm** [samuelcolvin/pydantic#3054]
Hi, I have installed fastapi thru pipenv which indirectly require pydantic, and since I have asked pipenv to use python 3.8 with the setting

```
[requires]
python_version = "3.8"
```

I have started to get an exception on pydantic, which is the following:

_..\..\..\..\.virtualenvs\app-backend-ombd6ijq\lib\site-packages\fastapi\params.py:4: in <module>
    from pydantic.fields import FieldInfo, Undefined
pydantic\__init__.py:2: in init pydantic.__init__
    ???
pydantic\dataclasses.py:3: in init pydantic.dataclasses
    ???
pydantic\class_validators.py:8: in init pydantic.class_validators
    ???
pydantic\errors.py:5: in init pydantic.errors
    ???
pydantic\typing.py:23: in init pydantic.typing
    ???
E   ModuleNotFoundError: No module named 'typing_extensions'_

The pydantic code leading to this error is:

https://github.com/samuelcolvin/pydantic/blob/5ccbdcb5904f35834300b01432a665c75dc02296/pydantic/typing.py#L23

Pydantic manual says that typing extensions is not needed if python version is newer enough, but this line still requires it.

Is it possible for you to either:

- remove this lib from the dependencies, or 
- make a clear statement on your [install instructions](https://pydantic-docs.helpmanual.io/install/) that this dependency has to be installed  (for instance by telling it to be installed with pip install pydantic[typing-extensions]), or similar, or 
- make typing_extensions lib be automatically downloaded when pydantic is installed
- somehow tell people from fastapi that they should add this dep? 
- tell people from typing_extensions that they should stop blocking python 3.8 on it?
- any other?

I dont know what is the best way forward here, Im just proposing some ideas.

Thanks,

**Comment by PrettyWood** [comment]
Hi @namoscagnm 
`typing-extensions` [IS required](https://github.com/samuelcolvin/pydantic/blob/master/setup.py#L134).
>Pydantic manual says that typing extensions is not needed if python version is newer enough

Can you please share the link to this statement in the doc ?
Thanks

**Comment by IOR88** [comment]
I am not sure why but pipenv is not installing typing-extensions, I think this is due to the configuration that pipenv is using to install dependent packages, because when You use pip install pydantic it will install typing-extensions for python 3.8 version, even though it is not required.

**Comment by PrettyWood** [comment]
Can't reproduce

**Comment by etoiledemer** [comment]
@namoscagnm @PrettyWood 
I have this problem when compiling a FastApi app using Nuitka

pydantic==1.9.0
fastapi==0.7.20
Nuitka==0.6.19.3

pipenv, version 2021.11.23

python is 3.9.6 installed with `pyenv`; the problem is not present when I downgrade to python 3.7.11

How did you fix this @namoscagnm ?
