### ISSUE TITLE
feature request "convert_extra_dict" option

### ISSUE THREAD

**Issue by alexyiu875** [samuelcolvin/pydantic#307]
# Feature Request 

( Continue on the "extra"/"unknown"/"open-content" fields or "Schema Evolution" topic ... ) 

When using 'allow_extra' option and when extra field is a Python dictionary itself. E.g.:
```py
class User(BaseModel):
    id: int
    name: str = 'John Doe'
    signup_ts: datetime = None
    friends: List[int] = []
    email: Optional[str] = None

    class Config:
        ignore_extra: bool = False
        allow_extra: bool = True
        validate_assignment: bool = True

external_data: Dict[str, Any] = {'id': '123', 'signup_ts': '2017-06-01 12:22', 'friends': [1, '2', b'3'],
                                 "extra01":"some_value", "extra02":456,
                                 "extra03": { "foo1": "bar", "foo2": 456.78, "foo3": [1, 2, 3] }}
user: User = User(**external_data)
```

It would be nice for us to have an option to access fields inside an extra dict as if it is a (plain old) Python object, instead of a Dictionary. E.g.
```py
    # this form: 
    print(user.extra03.foo2)
    # instead of this: 
    print(user.extra03["foo2"])
```
With this "convert_extra_dict" option enabled, it will allow us to perform some kind of schema evolution more easily. It will allow us to access those fields in a consistent manner, regardless whether the related Python class has those fields defined or now. 

Implementation of this feature may be relatively simple, if we decide that it is OK to depend on another Python open-source-library. E.g.: https://pypi.org/project/python-box/

We can just call this "Box" wrapper to wrap around that extra dictionary. 
Some more code for references: 
```py
    extra03_obj = Box(user.extra03)
    print(extra03_obj.foo2)
    print(extra03_obj.foo3[2])
    extra03_obj.foo3[2] = 3.14
    print(user.extra03["foo3"])
    # print output = [1, 2, 3]
    print(extra03_obj.to_dict())
    # print output = {'foo1': 'bar', 'foo2': 456.78, 'foo3': [1, 2, 3.14]}
```

**Comment by samuelcolvin** [comment]
I'm open to others input on this but personally I think it's an added and unnecessary confusion.

It might be possible to implement this for yourself using a modified BaseModel, if not I'd be willing to make changes to make customisations like this easier.
