### ISSUE TITLE
Nested item assignment breaks with `root_validator`

### ISSUE THREAD

**Issue by JWDobken** [samuelcolvin/pydantic#3070]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/joostdobken/miniconda/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Sep  4 2020, 02:22:02)  [Clang 10.0.0 ]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Whenever a nested field is provided with a dictionary, the fields class gets assigned to the attribute.
But this behavior no longer works when the nested item has a `root_validator`:

```py
class AlphaItem(BaseModel):
    name: str

class BetaItem(BaseModel):
    name: str

    @root_validator
    def validate(cls, values):
        return values
        
class MainItem(BaseModel):
    alpha_item: AlphaItem
    beta_item: BetaItem
```

No check the subtle difference in the output:
```py
>>> item = MainItem(alpha_item={'name': 'George'}, beta_item={'name': 'Edward'})
>>> item
MainItem(alpha_item=AlphaItem(name='George'), beta_item={'name': 'Edward'})
```

Check how the item is assigned:
```py
>>> type(item.alpha_item)
__main__.AlphaItem
```

... and how this works different for the beta item with a `root_validator`:

```py
>>> type(item.beta_item)
dict
```

Thanks a lot for this wonderful library!

**Comment by PrettyWood** [comment]
Hi @JWDobken 
Isn't it because you named your root validator `validate`, which overwrites pydantic one?
(I'm on my phone sorry if I don't try it myself)

**Comment by JWDobken** [comment]
ouch you are correct, thanks
