### ISSUE TITLE
pydantic_encoder ignores dataclass' Config.json_encoders

### ISSUE THREAD

**Issue by Lacrymology** [samuelcolvin/pydantic#3081]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /usr/local/lib64/python3.6/site-packages/pydantic
               python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
                     platform: Linux-5.13.7-arch1-1-x86_64-with-centos-7.9.2009-Core
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

I know the option of using `BaseModel` is there, but a big part of selling pydantic to my team lies in the fact that we can more or less just replace dataclasses. My issue is that trying to use `json_encoders` in a dataclass' `Config` (which should be fully supported, according to the docs), gets ignored by the `pydantic_encoder` which is the recommended way of dumping dataclasses.

```py
import pydantic

from pydantic import dataclasses
from decimal import Decimal
from datetime import datetime

@dataclasses.dataclass
class Foo:
    x: datetime
    y: Decimal
    class Config:
        json_encoders = {
            datetime: lambda v: repr(v),
            Decimal: str
        }

foo = Foo(datetime.now(), '1.23')
foo
# Foo(x=datetime.datetime(2021, 8, 10, 15, 55, 36, 523047), y=Decimal('1.23'))

import json
from pydantic.json import pydantic_encoder

json.dumps(foo, default=pydantic_encoder)
# '{"x": "2021-08-10T15:55:36.523047", "y": 1.23}'
```

I believe this stems from the fact that the Config class doesn't seem to get copied over to the inner `__pydantic_model__`, but I'm not sure:

```python
foo.Config.json_encoders
# {datetime.datetime: <function __main__.Foo.Config.<lambda>(v)>,
#  decimal.Decimal: str}
foo.__pydantic_model__.Config.json_encoders
# {}
```

I can't find if there's another way of serializing pydantic dataclasses. There's always the option of writing a custom json encoder and using `json.dumps(asdict(foo), encoder=my_encoder)`, but this looked like an oversight.

**Comment by akshay-r13** [comment]
You're right, the configuration is not passed to `foo.__pydantic_model__` during object creation.

I was able to fix it by  modifying `dataclasses.dataclass()`

https://github.com/samuelcolvin/pydantic/blob/5ccbdcb5904f35834300b01432a665c75dc02296/pydantic/dataclasses.py#L250-L251

as follows

```python
def wrap(cls: Type[Any]) -> Type['Dataclass']:
        return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen, _cls.Config) # Pass class configuration
```
The  `config` object is None which is causing the issue.

I think it shouldn't break anything. I'll be raising a PR on this after running tests.

**Comment by PrettyWood** [comment]
The config needs to be added in the decorator for dataclasses `@dataclass(config=MyConfig)`

**Comment by Lacrymology** [comment]
Thank you for the example

**Comment by Lacrymology** [comment]
Shouldn't the `pydantic_encoder` or some other do that for us in a way cleaner than accessing private objects?
