### ISSUE TITLE
`parse_obj_as` will return a dict instead of object if `root_validator` defined

### ISSUE THREAD

**Issue by lukmy** [samuelcolvin/pydantic#3117]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8.2
pydantic compiled: True
install path: /home/leyan/dev/robocop/.venv/lib/python3.8/site-packages/pydantic
python version: 3.8.5 (default, Jan 27 2021, 15:41:15)  [GCC 9.3.0]
platform: Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.29
optional deps. installed: ['typing-extensions']
```

For this code, it's a normal behavior. `parse_obj_as` returned a `Store` object

```py
from pydantic import root_validator
from typing import Literal, Optional, Union
from pydantic import BaseModel, parse_obj_as

ConfigId = Optional[Literal['1', '2']]

EcpImpls = Literal["dy", "ks", "xhs", "jd", "sn"]
Impls = Union[EcpImpls, Literal['taobao']]


class Store(BaseModel):
    sid: str
    seller_nick: str
    config_id: ConfigId = None
    token: Optional[str]
    impl: Impls = 'taobao'

seller_nick = 'hello'
store = parse_obj_as(Store, {'sid': '6660001', 'seller_nick': seller_nick})
assert isinstance(store, Store)
```

If I add a `root_validator`, `parse_obj_as` returned a dict instead

```py
from pydantic import root_validator
from typing import Literal, Optional, Union
from pydantic import BaseModel, parse_obj_as

ConfigId = Optional[Literal['1', '2']]

EcpImpls = Literal["dy", "ks", "xhs", "jd", "sn"]
Impls = Union[EcpImpls, Literal['taobao']]


class Store(BaseModel):
    sid: str
    seller_nick: str
    config_id: ConfigId = None
    token: Optional[str]
    impl: Impls = 'taobao'

    @root_validator(pre=True)
    def validate(cls, values):
        return values

seller_nick = 'hello'
store = parse_obj_as(Store, {'sid': '6660001', 'seller_nick': seller_nick})
assert isinstance(store, Store)
```

![image](https://user-images.githubusercontent.com/1225713/130047293-a927826a-4dfb-40a0-837e-868cc6f0c245.png)

**Comment by PrettyWood** [comment]
Hi @lukmy 
Don't call your validator `validate`. It overrides `pydantic` method.
The names will be changed in v2 to be private and avoid this kind of undesired behaviour

**Comment by lukmy** [comment]
> Hi @lukmy
> Don't call your validator `validate`. It overrides `pydantic` method.
> The names will be changed in v2 to be private and avoid this kind of undesired behaviour

Renaming solves the problem. Thanks for reply!~
