### ISSUE TITLE
datetime fields are validating boolean values

### ISSUE THREAD

**Issue by SunsetOrange** [samuelcolvin/pydantic#3154]
### Checks

* [ ] I added a descriptive title to this issue
* [ ] I have searched (google, github) for similar issues and couldn't find anything
* [ ] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

```
             pydantic version: 1.8.2
            pydantic compiled: True
               python version: 3.9.6 (default, Jul 16 2021, 00:00:00)  [GCC 11.1.1 20210531 (Red Hat 11.1.1-3)]
                     platform: Linux-5.13.12-200.fc34.x86_64-x86_64-with-glibc2.33
     optional deps. installed: ['typing-extensions']
```

# Bug?

datetime fields in Pydantic are validating boolean values and setting their date time's to the epoch.

Example:
```py
from datetime import datetime
from pydantic import BaseModel, ValidationError

class Example(BaseModel):
	datetime_received: datetime = datetime.utcnow()

model_data = {"datetime_received": True}
now = Example(**model_data)
print(now)

model_data = {"datetime_received": False}
now = Example(**model_data)
print(now)

>>> datetime_received=datetime.datetime(1970, 1, 1, 0, 0, 1, tzinfo=datetime.timezone.utc)
>>> datetime_received=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)
```
Expected: raise ValidationError

Python throws TypeErrors when parsing bools.
```py
from datetime import datetime

datetime(True)
datetime(False)

>>> Exception has occurred: TypeError
>>> function missing required argument 'month' (pos 2)
```

**Comment by PrettyWood** [comment]
Hi @SunsetOrange 
Well _pydantic_ tries to coerce by default so `False` -> `0` -> utcfromtimestamp
Unless a strict mode is added (will be in v2), this will most likely be "expected"
