### ISSUE TITLE
Issue with aliases in dictionary representations

### ISSUE THREAD

**Issue by majorgilles** [samuelcolvin/pydantic#321]
Question
For bugs/questions:
* OS: OSX Mojave
* Python 3.6.6
* Pydantic ==0.16

In some rare cases, I 've had to rebuild a base model from it's dictionary representation. When using aliases, is there a way to convert to a dict using the alias also, rather than the actual property name?

It's a major pain if you reuse an already sucessfully validated BaseModel subclass by passing its dict representation to another BaseModel. Pydantic will try to repopulate by the alias (e.g. "SomeAttr", but only "some_attr" is present in the dictionary.

```py
from pydantic import BaseModel, Schema

...
class SomeClass(BaseModel):
    some_attr: str = Schema(..., "SomeAttr")
    some_num: float = Schema(None, "SomeNum")
payload = {
     "SomeAttr": "test",
     "SomeNum" 123
}
an_instance = SomeClass(**payload) # valid, the object is populated using the alias
a_second_instance = SomeClass(**an_instance.dict())
```

**Comment by samuelcolvin** [comment]
I'm pretty sure this is the exact use case that @bendemaree implemented [`allow_population_by_alias`](https://pydantic-docs.helpmanual.io/#config) for in #160.

Let me know if that doesn't solve your problem.
