### ISSUE TITLE
EmailStr is parsed as str when setting default for EmailStr

### ISSUE THREAD

**Issue by jd-0001** [samuelcolvin/pydantic#3217]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
        pydantic version: 1.8.2
      pydantic compiled: True
            install path: /home/bapu/.cache/pypoetry/virtualenvs/ts-tools-LCrNCC4S-py3.8/lib/python3.8/site-packages/pydantic
          python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
                platform: Linux-5.4.0-84-generic-x86_64-with-glibc2.29
optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

```py
from pydantic import BaseSettings, EmailStr
from typing import List

class Settings(BaseSettings):
    admins: List[EmailStr] = ["mymail@mail.com"]
```

The above code gives:
```
Expression of type "list[str]" cannot be assigned to declared type "List[EmailStr]"
```
![Screenshot from 2021-09-15 12-46-06](https://user-images.githubusercontent.com/47495003/133388128-1056e44c-79e1-4207-98a9-c92e70d2ffe5.png)

Current workaround:
```python
from pydantic import BaseSettings, EmailStr
from typing import List, cast

class Settings(BaseSettings):
    admins: List[EmailStr] = [cast(EmailStr, "mymail@mail.com")]
```

**Comment by samuelcolvin** [comment]
There's no parsing error here, just your ide giving a warning

**Comment by jd-0001** [comment]
In this case, Do I have to use `cast` as stated in the workaround to avoid warning?
