### ISSUE TITLE
Question: Use more than one alias

### ISSUE THREAD

**Issue by liiight** [samuelcolvin/pydantic#324]
Question 

For bugs/questions:
* OS: MAC
* Python version 3.6
* Pydantic version 0.14

Is it possible to use more than 1 alias? I have data that can sometime have an attribute `like_this` and sometimes `likeThis` and I want to reuse the model

Thanks!

**Comment by samuelcolvin** [comment]
Not currently possible, probably easiest to write your own logic before passing the data to pydantic to coerce the keys to a single alias.

**Comment by liiight** [comment]
for prosperity's sake, this is the solution I went for:

```python
class Location(BaseModel):
    country: str
    city: str
    region: str
    country_iso_code: str = None
    countryIsoCode: str = None

    @property
    def iso_code(self):
        """A hack since sometime the API return country_iso_code and other times countryIsoCode..."""
        return self.country_iso_code or self.countryIsoCode
```

**Comment by samuelcolvin** [comment]
In this case (where you only have two possible names for the field) you could also use [`allow_population_by_alias` in config](https://pydantic-docs.helpmanual.io/#model-config).

**Comment by liiight** [comment]
great, that's exactly what I was looking for (besides better API schema from the devs, but that's beside the point).
Thanks!

**Comment by samuelcolvin** [comment]
No problem. I wasn't sure about allowing `allow_population_by_alias`, but it seems to come in handy fairly often.

**Comment by liiight** [comment]
Yeah, you kinda implemented a hack to the validation logic, but it matches the fairly common use case of bad API design.

**Comment by tomplex** [comment]
I know this is a late response, but I'm very happy to have come across this. Essentially I'm trying to parse and create JSON with `camelCase` keys without ever having to write it in my Python, and this made it possible, and even easy. Thanks for your work on this awesome library!

**Comment by davidpochon** [comment]
This is a super useful config option.

Note: The name of `allow_population_by_alias` was **changed in v1.0** to `allow_population_by_field_name`.

**Comment by Sourabh-dot** [comment]
Hi Does the latest Pydantic lib have this feature?

**Comment by jmkd3v** [comment]
I am trying to build a library built around a not-so-great API schema - it defines a `PartialUser` in many different ways, like `{"Id": 1", "Name": "abc"}` or `{"targetId": 1, "userName": "abc"}`

I want my Pydantic model to accept all of these types and always parse it into an `id` and `name` field. I can implement this logic outside of Pydantic, but then I can't define models as easy as `field_name: PartialUser` anymore.

Being able to assign multiple aliases would be a huge time-saver for this.
It would also be really neat if we could assign a custom parser that takes in the input parameters and outputs new parameters to generate the object with:
```py
class PartialUser(BaseModel):
    name: str
    id: int
    
    def filter_parameters(cls, *args, **kwargs):
        return {
            "id": kwargs.get("Id") or kwargs.get("targetId"),
            "name": kwargs.get("Name") or kwargs.get("userName")
        }
```

**Comment by jmkd3v** [comment]
Hi @samuelcolvin, any thoughts about this usecase?

**Comment by samuelcolvin** [comment]
I think a function to match input fields to model fields would be a good idea, should be possible in V2.

**Comment by jmkd3v** [comment]
Right now this is what I do:
```py
class PartialUser(BaseUser):
    def __init__(self, **data):
        super().__init__(
            id=data.get("id") or data.get("userId"),
            name=data.get("name") or data.get("username"),
            display_name=data.get("displayName")
        )

    id: int
    name: str
    display_name: str
```

**Comment by ericchansen** [comment]
Chiming in that multiple aliases (and even multiple alias_generator functions) would be awesome!

**Comment by dlopuch** [comment]
Ran across this for use-case of renaming an API field -- had to support both old field name and new field name going to same place in order to maintain API stability.

For the web archives, a slight twist on @jmkd3v's solution for when you have many fields on your model and don't want to type everything out:

```python
class PartialUser(BaseUser):
    def __init__(self, **data):
        super().__init__(
            id=data.pop("old_id", None) or data.pop("id", None),
            **data,
        )

    id: int
    name: str
    display_name: str
```

**Comment by david-shiko** [comment]
> Not currently possible, probably easiest to write your own logic before passing the data to pydantic to coerce the keys to a single alias.

Still not allowed multiple aliases? :(

**Comment by samuelcolvin** [comment]
https://pydantic-docs.helpmanual.io/blog/pydantic-v2/#more-powerful-aliases

It will be possible in V2. It's already implemented in pydantic-core.

**Comment by Neykuratick** [comment]
@samuelcolvin how to use that? Can't install pydantic v2 :(

**Comment by samuelcolvin** [comment]
ye, V2 isn't built yet, I'm working on it.

Hopefully, there will be a (beta) release by the end of the year. See https://pydantic-docs.helpmanual.io/blog/pydantic-v2/.

**Comment by georgebv** [comment]
@samuelcolvin sorry if this has already been discussed, but have you considered named aliases? E.g., I want my model to be exportable to different mediums: e.g., to "client_1" and to "client_2". The way this could work is:

```python
class MyModel(BaseModel):
    first_name = Field(aliases={"client_1": "firstName", "client_2": "FirstName"})

model = MyModel(first_name="Jon")

model.to_dict(by_alias="client_1")["firstName"]
model.to_dict(by_alias="client_2")["FirstName"]
```

**Comment by samuelcolvin** [comment]
Interesting idea, but that's not what we're doing in v2.

**Comment by rhajou** [comment]
hello @samuelcolvin , any idea how to have multiple aliases for one field? as I am seeing that aliases works differently than alias. 
What I want to do is the following (with pydantic v2) but it is not working.. 

`class GetInfo(BaseModel):
    name: str = Field(aliases=['name1', 'name_1', 'name_one'])
    name2: str = Field(aliases=[['name2', 'name_2', 'name_two']])


# The following will all be equal
assert all((
    GetInfo(name1="Sam", name2="Colvin"),
    GetInfo(name_1="Sam", name_2="Colvin"),
    GetInfo(name_one="Sam", name_two="Colvin"),
))`

**Comment by it176131** [comment]
> Never mind, we found the solution, that's it:
> 
> ```
> import pydantic
> print(pydantic.__version__ )  # 2.1.0 
> from pydantic import BaseModel, Field, AliasChoices
> from pydantic import BaseModel, Field, AliasChoices
> class User(BaseModel):
>     first_name: str = Field(validation_alias=AliasChoices('first_name', 'fname'))
> print(User(first_name="Sam"))
> print(User(fname="toto"))
> ```

Links to docs in case anyone shows up later:
- https://docs.pydantic.dev/2.6/concepts/alias/#aliaspath-and-aliaschoices
- https://docs.pydantic.dev/2.6/api/aliases/

**Comment by yuvraj-sequoia** [comment]
hey, can we provide only two alias choices or more than that??
