### ISSUE TITLE
root_validator in a nested model breaks field validation

### ISSUE THREAD

**Issue by qweeze** [samuelcolvin/pydantic#3269]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/qweeze/tochka/stories/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.5 (default, May 27 2021, 16:13:30)  [GCC 10.2.0]
                     platform: Linux-5.11.0-36-generic-x86_64-with-glibc2.33
     optional deps. installed: ['dotenv', 'typing-extensions']
```

It seems that if a `root_validator` is present in a nested model, normal field validation is being skipped:

```py
from pydantic import BaseModel, Field, root_validator

class Child(BaseModel):
    x: int = Field(..., lt=10)

    @root_validator
    def validate(cls, values):
        return values

class Parent(BaseModel):
    child: Child

Parent.parse_obj({'child': {'x': 9000}})  # passes validation
```

**Comment by freeseacher** [comment]
Just dont use name `validate` for root_validator. you are overriding internal method of BaseModel
