### ISSUE TITLE
Allow ConstrainedStr as K in Dict[K, V] types

### ISSUE THREAD

**Issue by demosdemon** [samuelcolvin/pydantic#329]
# Feature Request

I would like to use `ConstrainedStr` types as keys in my mapping relationships. These should be represented as [patternProperties](https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.5.5) in the JSON schema.

```py
import pprint
import typing
import pydantic

EnvironmentVariable = pydantic.constr(regex=r'^([a-zA-Z_][a-zA-Z0-9_]*)$')
EnvironmentVariables = typing.Dict[EnvironmentVariable, str]


class Job(pydantic.BaseModel):
    env: EnvironmentVariables = {}


# expected output
pprint.pprint(Job.schema())
"""
{'title': 'Job',
 'type': 'object',
 'properties': {'env': {'title': 'Env',
   'default': {},
   'type': 'object',
   'patternProperties': {
     '^([a-zA-Z_][a-zA-Z0-9_]*)$': {'type': 'string'}}}}}
"""

# This already works
Job.parse_obj({"env": {"0123": "test"}}) 
"""
ValidationError: 1 validation error
env -> __key__
  string does not match regex "^([a-zA-Z_][a-zA-Z0-9_]*)$" (type=value_error.str.regex; pattern=^([a-zA-Z_][a-zA-Z0-9_]*)$)
"""
```

**Comment by samuelcolvin** [comment]
@tiangolo what do you think?

**Comment by tiangolo** [comment]
It sounds sensible.

I got curious enough about the details as to go and implement it: #332

**Comment by pkucmus** [comment]
@samuelcolvin @tiangolo I'm trying to make an OAS3 validator with Pydantic and maybe generator, like OAS3 to Pydantic (even if only to exercise) but I got stuck quite fast on: https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.json#L93-L95.
How would one represent that?

**Comment by PrettyWood** [comment]
Hi @pkucmus,
Please do not hesitate to open a new issue with your exact scenario.
I had a quick look on the `Info` part in the schema. Are you trying to create a model to generate this exact schema ? Are you worried about the `'patternProperties'` ?
If so you can add extra parts on a given schema. Here is an example for the `Info` part:

```python
class Info(BaseModel):
    title: str
    description: Optional[str]
    termsOfService: Optional[str] = Field(format='uri-reference')
    version: str

    class Config:
        extra = Extra.forbid
        schema_extra = {
            'patternProperties': {'^x-': {}},
        }
```

output of generated schema

```
{'additionalProperties': False,
 'patternProperties': {'^x-': {}},
 'properties': {'description': {'title': 'Description', 'type': 'string'},
                'termsOfService': {'format': 'uri-reference',
                                   'title': 'Termsofservice',
                                   'type': 'string'},
                'title': {'title': 'Title', 'type': 'string'},
                'version': {'title': 'Version', 'type': 'string'}},
 'required': ['title', 'version'],
 'title': 'Info',
 'type': 'object'}
```

**Comment by pkucmus** [comment]
Thank you, here it is: https://github.com/samuelcolvin/pydantic/issues/1809
