### ISSUE TITLE
typerror in example: Incompatible types in assignment (expression has type "ellipsis", variable has type "int")

### ISSUE THREAD

**Issue by graingert** [samuelcolvin/pydantic#34]
with:

```python
from datetime import datetime
from pydantic import BaseModel

class UserModel(BaseModel):
    id: int = ...
    name = 'John Doe'
    signup_ts: datetime = None

external_data = {'id': '123', 'signup_ts': '2017-06-01 12:22'}
user = UserModel(**external_data)
print(user)
# > UserModel id=123 name='John Doe' signup_ts=datetime.datetime(2017, 6, 1, 12, 22)
print(user.id)
# > 123
```
I get:
```
error: Incompatible types in assignment (expression has type "ellipsis", variable has type "int")
error: Incompatible types in assignment (expression has type None, variable has type "datetime")
```

**Comment by samuelcolvin** [comment]
Weird, are you sure you're using 3.6.

**Comment by graingert** [comment]
@samuelcolvin 100%

**Comment by samuelcolvin** [comment]
I'm now guessing this relates to using mypy? 

Might be worth mentioning that, it wasn't clear.

**Comment by gregwebs** [comment]
Same issue here. I am running in a docker container that only has python 3.6 installed and using pipenv to ensure the MyPy installation.

mypy 0.501
Python 3.6.1

This issue seems to indicate that this warning is very much expected for an ellipses: https://github.com/python/mypy/issues/675

Have there been any successful tests of using MyPy with this library without warning?

**Comment by samuelcolvin** [comment]
No successful tests with mypy, I need to switch pydantic to use

```python
class Model(BaseModel):
    foobar: str
```

With no ellipsis, that should fix it. I'll try to get it done tomorrow.

**Comment by gregwebs** [comment]
Thanks! no ellipsis or sentinel value is ideal. If you need a sentinel you could try to do something like:

``` python
string = TypeVar("string", Any)

class Model(BaseModel):
    foobar: str = string
```

There is also an issue with the way the examples assign `None` to *non-Optional* types: they actually need their type to be wrapped in `Optional` for MyPy to be happy. Make sure to set `strict_optional` to true. Try this for your `mypy,ini`

```
strict_optional = True
check_untyped_defs = True
warn_redundant_casts = True
warn_unused_ignores = True
disallow_untyped_calls = True
disallow_untyped_defs = True
```
