### ISSUE TITLE
Environment variable overrides broken

### ISSUE THREAD

**Issue by optiz0r** [samuelcolvin/pydantic#340]
# Bug

For bugs/questions:
* OS: Fedora
* Python version: 3.6
* Pydantic version: 0.16

I believe v0.15 may have introduced a breaking change with respect to environment variable overrides for config values. The following change was made which I believe inverts the precedence.

https://github.com/jasonkuhrt/pydantic/commit/003c0a747b56b1e3cc5153c540525fd3ad8d986c#diff-d53d7b6b6983ebeac2c0807412bad8a8L16
```py
-        values.update(self._substitute_environ())
+        values = {
+            **self._substitute_environ(),
+            **values,
+        }
...
```

From PEP448 (https://www.python.org/dev/peps/pep-0448/#specification)
> The keys in a dictionary remain in a right-to-left priority order, so {**{'a': 1}, 'a': 2, **{'a': 3}} evaluates to {'a': 3}. There is no restriction on the number or position of unpackings.

So previously, `values.update(self.substitute_environ())` meant that the environment variables took precedence. Now, `**values` being on the right means they take precedence over env vars.

This matches my manual testing, in that env vars are only used if a particular setting is not listed in a configuration file which is fed into the `BaseSettings` constructor.

**Comment by samuelcolvin** [comment]
Just seen this, sorry. Now we've started, let's finish the discussion on #341 to avoid confusion.

I think the commit you're looking at is confusion, it might be that guy updating his fork that was way out of date. See the code at v0.12 for example:

https://github.com/samuelcolvin/pydantic/blob/86da135a0573b1627c9fa5f81750dcb7e3be2af7/pydantic/env_settings.py#L30-L35

This code hasn't changed for a long time.
