### ISSUE TITLE
Default value ignored when used alias

### ISSUE THREAD

**Issue by benyaming** [samuelcolvin/pydantic#3446]
First of all, thank you for the huge amount of great job, this library is amazing.

## Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/benyaming/Library/Caches/pypoetry/virtualenvs/******-_kPoNHuC-py3.7/lib/python3.7/site-packages/pydantic
               python version: 3.7.11 (default, Jul 21 2021, 17:32:51)  [Clang 12.0.5 (clang-1205.0.22.11)]
                     platform: Darwin-21.1.0-x86_64-i386-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']

```

When I create field with alias and default (both value or factory), this default ignores if i pass value by alias:

```py
>>> import pydantic

>>> class A(pydantic.BaseModel):
...     a: int = pydantic.Field(5, alias='b')
    
>>> A(**{'a': 1})
A(a=5)
>>> A(**{'a': None})
A(a=5)
>>> A(**{'b': 1})
A(a=1)
>>> A(**{'b': None})
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for A
b
  none is not an allowed value (type=type_error.none.not_allowed)
```

Same with `default_factory`:
```py
>>> class A(pydantic.BaseModel):
...     a: int = pydantic.Field(alias='b', default_factoty=lambda: 5)
    
>>> A(**{'b': None})
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for A
b
  none is not an allowed value (type=type_error.none.not_allowed)

...
```

**Comment by benyaming** [comment]
In addition, this is also strange behaviour:

```py

>>> class A1(pydantic.BaseModel):
...     a: int = pydantic.Field(5, alias='b')
    
>>> class A2(pydantic.BaseModel):
...     a: int = pydantic.Field(alias='b', default_factoty=lambda: 5)
    
>>> A1()
A1(a=5)
>>> A2()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for A2
b
  field required (type=value_error.missing)


```

**Comment by benyaming** [comment]
it was typo in `default_factory` 🤦‍♂️

**Comment by benyaming** [comment]
closed by mistake, sorry

**Comment by Shackelford-Arden** [comment]
@benyaming Glad I'm not the only one :)

I have been able to get around this for now (would kind of hope that Pydantic would do this for us) by using a custom validator for the field that I have trouble with. 

Example:

```python
>>> from pydantic import BaseModel, Field, validator

class A(BaseModel):
    a: int = Field(default=1, alias='b')

    @validator('a', pre=True)
    def a_is_not_none(cls, v):
        if v is None:
            return 1
        return v


>>> A(**{'b': 2})
A(a=2)
>>> A(**{'b': None})
A(a=1)
```

For larger objects that have tens of fields, this can get pretty unwieldy though 😐 

The `pre=True` piece is important so that it runs before Pydantic attempts to actually build the model. Kinda like sneaking in the default value before any larger work is initiated.

Found the following by checking out the examples provided [here in the docs](https://pydantic-docs.helpmanual.io/usage/validators/#pre-and-per-item-validators).

**Comment by samuelcolvin** [comment]
I don't really understand what this has to do with aliases.

I don't see any bug here.

Validators are the solution, if you want the functionality a lot you can create custom types. 

If you want "default in the event of a validation error", that's a feature request, I think there might already be an issue about it.
