### ISSUE TITLE
Optional dates can’t use Field()

### ISSUE THREAD

**Issue by JimDabell** [samuelcolvin/pydantic#3458]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
        pydantic version: 1.8.2
       pydantic compiled: False
            install path: /home/www/.cache/pypoetry/virtualenvs/redacted-ydm62z-a-py3.10/lib/python3.10/site-packages/pydantic
          python version: 3.10.0 (default, Nov 18 2021, 00:02:14) [GCC 10.2.1 20210110]
                platform: Linux-5.10.47-linuxkit-aarch64-with-glibc2.31
optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

```py
from typing import Optional
from datetime import date
from pydantic import BaseModel, Field

class SuccessModelOne(BaseModel):
	floatTest: Optional[float]
	strTest: Optional[str]
	date: Optional[date]

class SuccessModelTwo(BaseModel):
	floatTest: Optional[float] = Field(description='This is a float test')
	strTest: Optional[str] = Field(description='This is a str test')

class FailureModel(BaseModel):
	date: Optional[date] = Field(description='This is a date test')
```

The success models work as expected. The failure model raises the following exception:

```py
TypeError: typing.Optional requires a single type. Got FieldInfo(default=PydanticUndefined, description='This is a date test', extra={}).
```

It seems like other field types are fine, but specifically optional `datetime.date` properties can’t have `Field()`s associated with them.

I checked [the documentation](https://pydantic-docs.helpmanual.io/usage/types/#datetime-types) and didn’t see anything relevant.

**Comment by yosoycentli** [comment]
Hi there, I would like to work on this issue.

**Comment by michaeltoqua** [comment]
Is there a workaround for this issue?

**Comment by yosoycentli** [comment]
I isn't
Sorry :(

**Comment by PrettyWood** [comment]
Hi
It has nothing to do with _pydantic_. You can reproduce the error with this
```py
from typing import Optional
from datetime import date

date: Optional[date] = date.today()
```
```console
TypeError: typing.Optional requires a single type. Got datetime.date(2022, 1, 12).
```

If you want your field to be named `"date"`, you can either use an alias for the import (which I recommend)
```py
...
from datetime import date as dtdate

class M(BaseModel):
	date: Optional[dtdate] = Field(description='This is a date test')
```

or rely on the `alias` parameter in _pydantic_

```py
from datetime import date

class M(BaseModel):
	thedate: Optional[date] = Field(alias='date', description='This is a date test')
```

Hope it helps!

**Comment by alexpovel** [comment]
This code is functional without workarounds (if you don't count the `import`...):

```python
from __future__ import annotations

from datetime import date
from typing import Optional

from pydantic import BaseModel, Field


class M(BaseModel):
    date: Optional[date] = Field(description="This is a date test")
```

See also [PEP 563](https://peps.python.org/pep-0563/).

**Comment by Adrien-LUDWIG** [comment]
I just stumbled upon this error on some code generated by the OpenAPI Python client generator.
The generated code looks just like the sample given by @alexpovel above (with `__future__.annotations` import) but a `TypeError` is raised anyway.

If anyone is in this case and wants to avoid renaming the property in the OpenAPI definition, using the option [`--name-mappings`](https://openapi-generator.tech/docs/customization/#name-mapping) of the generator seems like the best option. 

---

For completeness, I executed the code sample in the Python docker official images since 3.7 (appearance of `__future__.annotations` with [PEP 563](https://peps.python.org/pep-0563/)). Here are the different error raised:
 
```python
# Python 3.7 and 3.8
TypeError: Optional[t] requires a single type. Got FieldInfo(annotation=NoneType, required=True, description='This is a date test').

# Python 3.9 and 3.10
TypeError: typing.Optional requires a single type. Got FieldInfo(annotation=NoneType, required=True, description='This is a date test').

# Python 3.11 and 3.12
RecursionError: maximum recursion depth exceeded
```

The `pydantic` version is 2.7.1 except for Python 3.7, in which case it is 2.5.3.
