### ISSUE TITLE
Suggestion/feature_request - Use a single attribute for allow_extra and ignore_extra

### ISSUE THREAD

**Issue by liiight** [samuelcolvin/pydantic#351]
# Feature Request 

The usage of the `allow_extra` and `ignore_extra` attributes is kinda confusing. For example, to dissalow any additional attributes on the model you need to set them both to False.

I propose a single `extra_attributes` attribute, which will take an enum, like so:

```python
class ExtraAttributes(Enum):
    ALLOW = auto()
    DISALLOW = auto()
    IGNORE = auto()


class FooModel(BaseModel):
    bar = 5

    class Config:
        extra_attributes = ExtraAttributes.DISALLOW
```

I believe this will handle all the functionality of the two existing attributes while keeping the pythonic style of pydantic. Also, ExtraAttributes.IGNORE will be the default value to keep the same default as today.

The current attributes can still be in use and log a deprecation warning and they could be removed in a future release.

WDYT?

**Comment by samuelcolvin** [comment]
LGTM.

Happy to accept a PR.

Maybe just `extra` for the name.

As you say we'll need deprecation warnings for the old values.

**Comment by liiight** [comment]
So I started work on this and I hit a snag. Seems like `allow_extra` is used both for model init and when in __setattr__. So just setting one value to a default of ignore isn't enough.

So i'm not entirely sure how to proceed as it seems there is a use case for using two attributes.

**Comment by samuelcolvin** [comment]
Should still be possible.

Have a go and if you can't work it out I'll do it.
