### ISSUE TITLE
Error importing plugin "pydantic.mypy": cannot import name TypeVarDef

### ISSUE THREAD

**Issue by adam-pawluczuk** [samuelcolvin/pydantic#3528]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

On the newest pydantic and newest mypy (0.920) I get:

```
mypy .                                                 
pyproject.toml:1: error: Error importing plugin "pydantic.mypy": cannot import name TypeVarDef
Found 1 error in 1 file (errors prevented further checking)
```

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/USERNAME/opt/anaconda3/envs/ENVNAME/lib/python3.9/site-packages/pydantic
               python version: 3.9.7 (default, Sep 16 2021, 08:50:36)  [Clang 10.0.0 ]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

Related issues in mypy issue tracker:
https://github.com/python/mypy/issues/11767

**Comment by hauntsaninja** [comment]
See also this PR: https://github.com/samuelcolvin/pydantic/pull/3175#issuecomment-914897604

**Comment by hughhan1** [comment]
@manthey, is there an estimated timeline for when the pydantic mypy plugin will be compatible with mypy v0.920?

**Comment by manthey** [comment]
I don't know -- we need to ask a pydantic maintainer when they will issue a release.

**Comment by karlanke** [comment]
@samuelcolvin do you know when this might get released?

**Comment by jeeftor** [comment]
Is there a way to point to this pre-release version in pip?

**Comment by jeeftor** [comment]
Is there a way to pull this version into pip?

**Comment by gnmerritt** [comment]
For people who are wondering, version `1.9.1` is available on pip and includes this fix
