### ISSUE TITLE
parse_obj validates bad data and generates a very strange result

### ISSUE THREAD

**Issue by chlasch** [samuelcolvin/pydantic#3531]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/*****/Library/Caches/pypoetry/virtualenvs/api-v1-Tj7elRHn-py3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.6 (default, Oct 19 2020, 13:58:00)  [Clang 12.0.0 (clang-1200.0.32.2)]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

With the below code, I get a very strange result. This should fail to validate at all, since it's a list, not a dict

```py
from pydantic import BaseModel


class Something(BaseModel):
    typ: str


something = [{"typ": "something", "unrelated": {"unrelated": "unrelated"}}]

print(Something.parse_obj(something))

# I get
# Something(type='unrelated')
...
```

If I remove the `unrelated` key, then i get the expected error

```py
from pydantic import BaseModel


class Something(BaseModel):
    typ: str


something = [{"typ": "something"}]

print(Something.parse_obj(something))

# Traceback (most recent call last):
#   File "pydantic/main.py", line 574, in pydantic.main.BaseModel.parse_obj
# ValueError: dictionary update sequence element #0 has length 1; 2 is required
#
# The above exception was the direct cause of the following exception:
#
# Traceback (most recent call last):
#   File "example.py", line 10, in <module>
#     print(Something.parse_obj(something))
#   File "pydantic/main.py", line 577, in pydantic.main.BaseModel.parse_obj
# pydantic.error_wrappers.ValidationError: 1 validation error for Something
# __root__
#   Something expected dict not list (type=type_error)
```

Am I missing a known caveat that is causing this behavior?

**Comment by PrettyWood** [comment]
Hello @chlasch 
`parse_obj` is looking for a `dict` and tries to coerce.
```py
dict([{"typ": "something", "unrelated": {"unrelated": "unrelated"}}]) == {'typ': 'unrelated'}
```
So you end up with `Something(typ='unrelated')`
For the second case
```py
dict([{"typ": "something"}])
```
raises a `ValueError`

**Comment by chlasch** [comment]
> Hello @chlasch `parse_obj` is looking for a `dict` and tries to coerce.
> 
> ```python
> dict([{"typ": "something", "unrelated": {"unrelated": "unrelated"}}]) == {'typ': 'unrelated'}
> ```
> 
> So you end up with `Something(typ='unrelated')` For the second case
> 
> ```python
> dict([{"typ": "something"}])
> ```
> 
> raises a `ValueError`

Yep, I see that now.

Is this really intended behavior for `parse_obj`? The data being passed for validation is pretty far off from what what is expected.

Having such an odd result because of the implementation of python's `dict` function seems confusing at best.

In my specific case, the `Something` class is in a `Union` in another class, and the `something` dict *should* be validating to another type in that Union, which the data actually matches.

**Comment by chlasch** [comment]
Looks like this case was already brought in #1268, and v2 will correct this behavior.
