### ISSUE TITLE
Nested serialization regression between 1.8.2 and master

### ISSUE THREAD

**Issue by christianbundy** [samuelcolvin/pydantic#3544]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

I found a small regression between 1.8.2 and `master` that broke some tests for me -- I bisected and found that it started with 458f257dcbe4d307ad71c28a9947e30eab742131. Here's the test I used:

```python3
from typing import Optional
from pydantic import BaseModel, Field


class Model(BaseModel):
    value: Optional[str]
    nested: Optional[BaseModel]


def test_my_bug():
    assert (
        Model(value=None, nested=Model(value=None)).json(exclude_none=True)
        == '{"nested": {}}'
    )
```

In 1.8.2, options to `json()` (like `exclude_none`) were passed to all nested models, but in `master` that no longer occurs. Instead, we see:

```json
{ "nested": { "value": null } }
```

---

In my case, I noticed this because I had two models:

```python3
class Model(BaseModel):
    value: Optional[str]

class OuterModel(Model):
    nested: Optional[Model]

    def json(self, **kwargs):
        kwargs.set_default("exclude_none", True)
        return super().json(**kwargs)


# Usage:
OuterModel(nested=Model()).json()
```

In 1.8.2 this was overridden `json()` was used on all nested models as well, but in master this is only applied to the outer model. This means that we get `{ "nested": { "value": null } }` when previously we would've gotten `{ "nested": {} }` like above.

**Comment by samuelcolvin** [comment]
I think this is the same as #3542. If not, let me know and I'll reopen

**Comment by christianbundy** [comment]
I think when I posted the bug report they were slightly different, but it looks like @PrettyWood pushed another commit to take care of this. Thanks!
