### ISSUE TITLE
Advanced exclude official example failed

### ISSUE THREAD

**Issue by AlekseyLobanov** [samuelcolvin/pydantic#3558]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /tmp/venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
                     platform: Linux-5.4.0-91-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']

```
I just found that official exclude [example](https://pydantic-docs.helpmanual.io/usage/exporting_models/#advanced-include-and-exclude) is not working as expected.

I attached minimal snippet below which gives us similar output

```py
from pydantic import BaseModel, SecretStr


class User(BaseModel):
    id: int
    username: str
    password: SecretStr

user = User(
    id=42,
    username='JohnDoe',
    password='hashedpassword'
)
print(user.dict(exclude={"username":True}))
```

```
➜ python example.py
Traceback (most recent call last):
  File "example.py", line 14, in <module>
    print(user.dict(exclude={"username":True}))
  File "pydantic/main.py", line 510, in pydantic.main.BaseModel.dict
  File "pydantic/main.py", line 875, in _iter
  File "pydantic/main.py", line 779, in pydantic.main.BaseModel._get_value
  File "pydantic/utils.py", line 479, in pydantic.utils.ValueItems.__init__
TypeError: Unexpected type of exclude value <class 'bool'>
```

**Comment by PrettyWood** [comment]
@AlekseyLobanov Please use v1.9.0a1 for this feature. It's not part of v1.8 ;)

**Comment by AlekseyLobanov** [comment]
I think it _definitely_ should be mentioned likedefinitely

>New in version v1.5.

in Serialising subclasses.

Because I can not find "1.8" or "1.9" on this page. And I see v1.8.2 in right upper corner
