### ISSUE TITLE
Conda-forge distribution

### ISSUE THREAD

**Issue by dgasmith** [samuelcolvin/pydantic#356]
We typically release computational molecular science software on [conda](https://www.anaconda.com) as our requirements often involve extensive compiled programs. A popular channel is [conda-forge](https://conda-forge.org) which allows submission and automated builds of open source community packages.

I am happy to make the original submission and maintain the package there with you (if you wish) as an additional maintainer. Any objections to this deployment?

**Comment by samuelcolvin** [comment]
Fine by me. What does it require?

I'm amazed conda doesn't allow install from pypi.

**Comment by samuelcolvin** [comment]
I'll do it tomorrow.

Please prompt me if I forget.

**Comment by dgasmith** [comment]
Will do, feel free to ping me if you have any questions.

**Comment by samuelcolvin** [comment]
Great, will do.

**Comment by dgasmith** [comment]
Poke!

**Comment by samuelcolvin** [comment]
Done. Thanks.
