### ISSUE TITLE
validate_arguments decorator is creating copy of arguments instead of keeping references

### ISSUE THREAD

**Issue by juanzolotoochin** [samuelcolvin/pydantic#3565]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

When using `@validate_arguments` it seems that the reference to the original object arguments is lost, making it unable for the function to modify the object in place

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8.2
pydantic compiled: False
     install path: /root/.cache/bazel/_bazel_root/143636f84d400ba086751871f30d30df/external/pip_deps/pypi__pydantic/pydantic
   python version: 3.10.0 (default, Oct  4 2021, 23:05:56) [GCC 7.5.0]
         platform: Linux-5.10.47-linuxkit-x86_64-with-glibc2.27
```

```py
from typing import List
from pydantic import validate_arguments


@validate_arguments
def add_one(numbers: List[int]) -> None:
    for i in range(len(numbers)):
        numbers[i] += 1

    return id(numbers)


numbers = [1, 2]
argument_id = add_one(numbers)

print(id(numbers))
print(argument_id)

assert numbers == [2, 3] # passes without the decorator, fails with it

```

Output shows

```
# With @validate_arguments (different)
139624718827072
139624719156544

# Without @validate_arguments (same)
140046989633408
140046989633408
```

**Comment by samuelcolvin** [comment]
That's a side effect of validation.

Not a bug, create a discussion or feature request if you want it changing, but I think it would require a massive change to pydantic.

**Comment by juanzolotoochin** [comment]
Ok, at least this is useful to know I'm not crazy. The change in behavior was super weird and unexpected, it was also VERY time consuming to figure out what was going on. Is it documented anywhere?

I worked around it by defining a custom decorator for this:

```
from pydantic import validate_arguments

def custom_validator(func):
    validated_func = validate_arguments(func)

    def wrapper(*args, **kwargs):
        validated_func.validate(*args, **kwargs)
        return func(*args, **kwargs)

    return wrapper

@custom_validator
def add_one(numbers: List[int]) -> None:
    for i in range(len(numbers)):
        numbers[i] += 1

    return id(numbers)
```

Since I only use this in tests and performance is not an issue this works for all of my use cases.

**Comment by samuelcolvin** [comment]
Probably not documented explicitly.

Happy to accept a PR to add a warning to the docs.
