### ISSUE TITLE
`pydantic.Json[List[str]]` raise error 

### ISSUE THREAD

**Issue by Wasdee** [samuelcolvin/pydantic#3568]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8.2
pydantic compiled: False
install path: C:\Users\nutch\.virtualenvs\rpi-DVT96Pzy\Lib\site-packages\pydantic
python version: 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]
platform: Windows-10-10.0.22000-SP0
optional deps. installed: ['dotenv', 'typing-extensions']

```

```py
import pydantic

class Settings(BaseSettings):
    cam_hostnames: Json[List[str]]
    cam_nicknames: Json[List[str]]

    username: str
    password: SecretStr

    class Config:
        env_file = '.env'
        env_file_encoding = 'utf-8'

settings = Settings()
```

This raises
```
Traceback (most recent call last):
  File "secret\path", line 30, in main
    settings = Settings()
  File "secret\path\lib\site-packages\pydantic\env_settings.py", line 36, in __init__
    super().__init__(
  File "secret\path\lib\site-packages\pydantic\main.py", line 406, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for Settings
cam_hostnames
  JSON object must be str, bytes or bytearray (type=type_error.json)
cam_nicknames
  JSON object must be str, bytes or bytearray (type=type_error.json)
```

This is in conflict with [the docs](https://pydantic-docs.helpmanual.io/usage/types/#json-type)

 that
```py
...

class ComplexJsonModel(BaseModel):
    json_obj: Json[List[int]]

...
```

**Comment by CircleOnCircles** [comment]
`Json[List[int]]` fails as well.

**Comment by ischaojie** [comment]
so, what values are in your `.env` file

**Comment by CircleOnCircles** [comment]
> so, what values are in your `.env` file

`cam_nicknames=['camA', 'camB']`

**Comment by kamilturek** [comment]
@CircleOnCircles I've managed to work it out this way:
```
$ cat .env
cam_nicknames='["camA", "camB"]'
```
```
Python 3.10.1 (main, Dec  6 2021, 22:18:13) [Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydantic import BaseSettings
>>> class Settings(BaseSettings):
...     cam_nicknames: list[str]
...     class Config:
...             env_file = '.env'
... 
>>> Settings().dict()
{'cam_nicknames': ['camA', 'camB']}
>>> 
```

As per [docs](https://pydantic-docs.helpmanual.io/usage/settings/#parsing-environment-variable-values):
> Complex types like list, set, dict, and sub-models are populated from the environment by treating the environment variable's value as a JSON-encoded string.

**Comment by Wasdee** [comment]
> ```python
> import pydantic
> 
> class Settings(BaseSettings):
>     cam_hostnames: Json[List[str]]
>     cam_nicknames: Json[List[str]]
> 
>     username: str
>     password: SecretStr
> 
>     class Config:
>         env_file = '.env'
>         env_file_encoding = 'utf-8'
> 
> settings = Settings()
> ```

I tested my side. as you result confirmed. 

```bash
$ cat .env
cam_nicknames='["camA", "camB"]'
cam_num='[12, 32]'
```

```python
import pydantic

class Settings(pydantic.BaseSettings):
    cam_nicknames: list[str]
    cam_num: list[int]

    class Config:
        env_file = '.env'

settings = Settings()

print('cam_nicknames:', settings.cam_nicknames) # cam_nicknames: ['camA', 'camB']
print('cam_num:', settings.cam_num) # cam_num: [12, 32]
```

In conclude, don't declare type as `Json[...]`
