### ISSUE TITLE
'create_model' method is missing 'Optional' type hint

### ISSUE THREAD

**Issue by Leletir** [samuelcolvin/pydantic#3585]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/*****/workspace/toolbox/python-libs/*****/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.6 (default, Dec  2 2021, 10:50:07)  [Clang 12.0.0 (clang-1200.0.32.29)]
                     platform: macOS-11.6.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']

```

First of all, thank you for `Pydantic`, it's an amazing library !! It saves hours of work !

I'm nor sure it's a bug, and it's only on the type hinting. I think there is a mistake on `create_model` type hints. 

I have this following code ('user.py'):

```py
from pydantic import create_model

class UserModel(BaseModel):
    auth_expiration: int
    id: str

class UserFactory:
    def __init__(self, oidc_scopes: typing.List[str]):
        self._scopes = oidc_scopes

    def create_user_model(self) -> Type[User]:
        # TODO Manage optional 'None' instead of ...
        fields = {scope: (type(scope), ...) for scope in self._scopes}
        return create_model(
            "User",
            **fields,
            __base__=UserModel,
        )
```

When I'm linting this code with mypy, I have the following errors:
```shell
user.py:92: error: Argument 2 to "create_model" has incompatible type "**Dict[str, Tuple[Type[str], ellipsis]]"; expected "Optional[Type[BaseConfig]]"
user.py:92: error: Argument 2 to "create_model" has incompatible type "**Dict[str, Tuple[Type[str], ellipsis]]"; expected "Optional[str]"
user.py:92: error: Argument 2 to "create_model" has incompatible type "**Dict[str, Tuple[Type[str], ellipsis]]"; expected "Optional[Dict[str, classmethod[Any]]]"
```

I've looked at the code of 'create_model', and the signature is the following:
```py
def create_model(
    __model_name: str,
    *,
    __config__: Type[BaseConfig] = None,
    __base__: Type['Model'] = None,
    __module__: str = __name__,
    __validators__: Dict[str, classmethod] = None,
    **field_definitions: Any,
) -> Type['Model']:
```

If I've understood well the 'Optional' option for typing module (I'm still a newbie with python type hinting), most of these parameters should be Optional, like in the example bellow:

```py
def create_model(
    __model_name: str,
    *,
    __config__: Optional[Type[BaseConfig]] = None,
    __base__: Optional[Type['Model']] = None,
    __module__: Optional[str] = __name__,
    __validators__: Optional[Dict[str, classmethod]] = None,
    **field_definitions: Any,
) -> Type['Model']:
```

Since you've done the work on handling None values in the method itself (not sure about `__module__` though).

What do you think ? If you agree I can open a PR and do the code :)

Have a good day.

**Comment by samuelcolvin** [comment]
Can you check if it's fixed in v1.9?

**Comment by Leletir** [comment]
Hello @samuelcolvin, thank you for your answer.

with 1.9.0a2, I have the following error:
```py
user.py:90: error: No overload variant of "create_model" matches argument types "str", "Dict[str, Tuple[Type[str], ellipsis]]", "Type[User]"
user.py:90: note: Possible overload variants:
user.py:90: note:     def create_model(__model_name, str, *, __config__: Optional[Type[BaseConfig]] = ..., __base__: None = ..., __module__: str = ..., __validators__: Dict[str, classmethod[Any]] = ..., **field_definitions: Any) -> Type[BaseModel]
user.py:90: note:     def [Model <: BaseModel] create_model(__model_name, str, *, __config__: Optional[Type[BaseConfig]] = ..., __base__: Union[Type[Model], Tuple[Type[Model], ...]], __module__: str = ..., __validators__: Dict[str, classmethod[Any]] = ..., **field_definitions: Any) -> Type[Model]
```

I can see that the parameters `__config__`, `__base__` and `__validators__` are now Optional.

Maybe it's due to the method I use to create the field_definition:
```py
fields = {scope: (type(scope), ...) for scope in self._scopes}
```

**Comment by samuelcolvin** [comment]
I've tried this and it seems to be a limitation of mypy, I can't find a way to modify the signature(s) of `create_model` to fix this.

The simplest answer is to change your code to

```py
fields: Dict[str, Any] = {scope: (type(scope), ...) for scope in self._scopes}
```
And the errors go away.

---

Closing this as I know of no way to fix this in pydantic.

**Comment by Leletir** [comment]
Thank you @samuelcolvin !! Have a good day :)
