### ISSUE TITLE
Infinite loop in parse_datetime when parsing str value "infinite"

### ISSUE THREAD

**Issue by ar45** [samuelcolvin/pydantic#3590]
### Checks

* [ x] I added a descriptive title to this issue
* [ x] I have searched (google, github) for similar issues and couldn't find anything
* [x ] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /Users/aron/.virtualenvs/server-aiohttp/lib/python3.9/site-packages/pydantic
               python version: 3.9.1 (default, Dec 28 2020, 11:24:06)  [Clang 12.0.0 (clang-1200.0.32.28)]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions', 'email-validator']

```

```py
import pydantic
from datetime import datetime

class Model(pydantic.BaseModel):
    dt: datetime
    

Model(dt='infinity')   # Hangs forever

```

**Comment by PrettyWood** [comment]
Hey this bug was already reported and fixed https://github.com/samuelcolvin/pydantic/security/advisories/GHSA-5jqp-qgf6-3pvh
Thanks

**Comment by ar45** [comment]
Oops. I checked and missed on that 😮

Great Thanks!
