### ISSUE TITLE
Test error with Python3.10

### ISSUE THREAD

**Issue by tillea** [samuelcolvin/pydantic#3604]
# Bug

There is a [bug report against the Debian packaged version](https://bugs.debian.org/1002387) which is about the `distutils` usage.  I simply removed that test in a [patch](https://salsa.debian.org/python-team/packages/pydantic/-/blob/master/debian/patches/distutils_is_deprecated.patch).  Unfortunately when I try to build the package now there are some new errors arising.

In case you can not reproduce this with Python3.10 I can sent a full build log.

Kind regards, Andreas.

**Comment by samuelcolvin** [comment]
This was fixed in #2885 and will be released in v1.9 (which should be released today).

These warnings are also muted by `setup.cfg`.
