### ISSUE TITLE
Cannot mock Field default_factory

### ISSUE THREAD

**Issue by jooola** [samuelcolvin/pydantic#3611]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Hello there !

I try to mock the `get_now` function that is used as factory for the `when` field. But this doesn't seem to work as expected. Maybe I am missing something important, as I am unsure if this is actually expected or if I should use a workaround.

I tried to provide `when` while creating the expected object. 

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
$ .venv/bin/python3 -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /home/jo/git/github.com/jooola/earhorn/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
                     platform: Linux-5.10.0-10-amd64-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

```py
from datetime import datetime
from unittest import mock

from pydantic import BaseModel, Field


def get_now():
    return datetime.now()


class Event(BaseModel):
    when: datetime = Field(default_factory=get_now)
    name: str


now = datetime.now()


def test_event():
    with mock.patch("tests.pydantic_test.get_now") as get_now_mock:
        get_now_mock.return_value = now

        EXPECTED = Event(when=now, name="test")
        assert Event(name="test") == EXPECTED

```

**Comment by PrettyWood** [comment]
Hi @jooola 
Unfortunately it's "expected" because of how mocking works. You would have the same with a plain `dataclass`.
You can read https://stackoverflow.com/questions/61257658/python-dataclasses-mocking-the-default-factory-in-a-frozen-dataclass for more information.
In your case, the easiest workaround is `Field(default_factory=lambda: get_now())`

**Comment by jooola** [comment]
Thanks for the link, it is clearer now.
