### ISSUE TITLE
Object construction yields incorrect results when passed a list of dictionaries as a field initializer

### ISSUE THREAD

**Issue by mkromer-tc** [samuelcolvin/pydantic#3614]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.9.0\n            pydantic compiled: False\n                 install path: /Users/mkromer/.pyenv/versions/3.6.8/envs/tcex3-3.6.8/lib/python3.6/site-packages/pydantic\n               python version: 3.6.8 (default, Aug 25 2021, 09:55:39)  [GCC Apple LLVM 12.0.0 (clang-1200.0.32.29)]\n                     platform: Darwin-19.6.0-x86_64-i386-64bit\n     optional deps. installed: ['typing-extensions']
```

When initializing a union input with a list of dictionaries, the handler in validate() and parse_obj() will attempt to see if the input value can be converted to a dictionary with `dict()`.  However, if the input is a *list of dictionaries*, (at least, a list with an even number of keys in the first value's dictionary) dict() will succeed but will return a dictionary based on the pairwise key *names*, i.e. `dict([{'key_a': 'value_a', 'key_b': 'value_b'}])` will return `{ 'key_a': 'key_b' }` which is not the desired result.

Because of this, model inputs which accept `Union[Thing, List[Thing]]` will fail, but `Union[List[Thing], Thing]` will succeed.  It is highly desirable to have both formats work regardless of order.

```py
from typing import Any, Optional, Union, List

from pydantic import BaseModel

class KV(BaseModel):
    key: str
    type: Optional[str]
    value: Any


class MyModel(BaseModel):
    input_1: Union[KV, List[KV]]

data = [
    {"key": "domain", "value": "supercalifragilisticexpialidocious.com"},
    {"key": "specialsauce", "value": "another.com"},
]

mm = MyModel(input_1=data)
print(mm)

```

**Comment by PrettyWood** [comment]
Hi @mkromer-tc 
You can use the [new `Config.smart_union` option](https://pydantic-docs.helpmanual.io/usage/model_config/#smart-union) like this
```py
class MyModel(BaseModel, smart_union=True):
    input_1: Union[KV, List[KV]]
```
and it should work as expected

**Comment by mkromer-tc** [comment]
Actually, it won't fix the issue I described.  The issue here is that with an input
```py

data = [ { 'key_a': 'value_a',
                 'key_b': 'value_b' } ]
```

`dict(data)` *succeeds* even though it gives a useless result.  This is an artifact of dict() allowing a sequence of sequences as an input value, which is *meant* to be a list of (key, value) items.

If you try the test case I added you can see what I mean; because dict() is succeeding when there is an even number of keys in the first element of the list, the dict gives you back `{ 'key_a': 'key_b' }` which is a nonsense value.

**Comment by mkromer-tc** [comment]
Oh, I should point out that since a model has a field of Any, that field is never validated, so the normal validation of a required key doesn't fire.  This is what allows the malformed result from `dict()` to pass validation by accident when the first key is the only key checked.  If the model's input for `value` was `str` the dict() check will catch that `value` is missing.

**Comment by mkromer-tc** [comment]
Huh, maybe I had a local version snarl with python 3.6, because smart_union seems to be doing the right thing now with 3.9.  Since 3.6 is deprecated maybe it's not an issue.
