### ISSUE TITLE
mypy type checking doesn't seem to work

### ISSUE THREAD

**Issue by gjcarneiro** [samuelcolvin/pydantic#366]
# Bug

For bugs/questions:
* OS: **ubuntu 18.10**
* Python version `import sys; print(sys.version)`: **3.7**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **master**

Where possible please include a self contained code snippet describing your 
bug, question, or where applicable feature request:

```py
from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, NoneStr

class Model(BaseModel):
    age: int
    first_name = 'John'
    last_name: NoneStr = None
    signup_ts: Optional[datetime] = None
    list_of_ints: List[int]

m = Model(age=42, list_of_ints=[1, '2', b'3'])
print(m.age)
# > 42

Model()
# will raise a validation error for age and list_of_ints
```

The above is the example from the docs: https://pydantic-docs.helpmanual.io/#usage-with-mypy

With `mypy 0.650`, doesn't raise any validation error.

Moreover, changing `print(m.age)` to `print(m.agexxx)`, it still doesn't give any error saying that the field name is wrong.

**Comment by samuelcolvin** [comment]
We should make the docs clearer, but while mypy won't give a false negative when it parses a pydantic model, it obviously can't check if model validation is going to pass or fail.

Also as per #245 mypy can't check whether an attribute exists.

This is a (completely understandable) limitation of mypy. You might want to use dataclasses which mypy should support better.

**Comment by gjcarneiro** [comment]
Yes, please make the docs clearer.  Essentially I can't use pydantic if I want static type checking.   The docs say:

> because pydantic data structures are just instances of classes you define; auto-completion, linting, mypy and your intuition should all work properly with your validated data.

Well, I would claim that, no, mypy does not work correctly with pydantic.  The docs are misleading.

**Comment by samuelcolvin** [comment]
That's fair, I'll update docs.

Some things do work however

```py
from pydantic import BaseModel

class Test(BaseModel):
    test_int: int
    test_str: str

m = Test(test_int=42, test_str='foobar')
print(123 + m.test_str)
```

Returns:
```
(env) pydantic 0 1.19s ➤  mypy --ignore-missing-imports --follow-imports=skip --strict-optional test.py 
test.py:11: error: Unsupported operand types for + ("int" and "str")
```

While the same with `print(123 + m.test_int)` would pass.

So I would say mypy and pydantic work together partially, "Essentially I can't use pydantic if I want static type checking." is a bit too far the other way.

**Comment by samuelcolvin** [comment]
see #372.
