### ISSUE TITLE
Error with walidate Empty List

### ISSUE THREAD

**Issue by krzysieqq** [samuelcolvin/pydantic#367]
I have problem with validate lists. If I pass empty list to validator I don't have any ValidationError which should be thrown because List have declared values. If I pass to list any value, like empty str everything seems to work fine. Am I doing something wrong?
```py
from typing import List
from pydantic import BaseModel,constr
class lists(BaseModel): 
    list1: List[constr(min_length=1, max_length=2)] = None
    list2: List[int]
    list3: List[str]

```
```py
lists(**{'list1': [], 'list2': [], 'list3': []})
Out[2]: <lists list2=[] list3=[] list1=[]>

In [3]: lists(**{'list1': [''], 'list2': [''], 'list3': ['']})
ValidationError: 2 validation errors
list2 -> 0
  value is not a valid integer (type=type_error.integer)
list1 -> 0
  ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)

```

**Comment by samuelcolvin** [comment]
This is "correct" since an empty list is a valid list and has no elements to validate.

What you need is `conlist` a bit list `constr` which constrains length, we discussed this in #161 but it hasn't been implemented.

PR welcome.

You could also do this with [`@validators`](https://pydantic-docs.helpmanual.io/#validators).

**Comment by krzysieqq** [comment]
Small workaround for empty list

```py
@validator('list1', 'list2', 'list3', pre=True, whole=True)
def check_if_list_has_value(cls, value):
    if not value:
        return None
    return value
```

**Comment by samuelcolvin** [comment]
Great.

Btw, just `return value or None` would be more succinct.

**Comment by dvdblk** [comment]
If someone finds this issue, best way to do it now is via [`conlist`](https://docs.pydantic.dev/usage/types/#arguments-to-conlist).
