### ISSUE TITLE
Deeply nested models do not exist

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [samuelcolvin/pydantic#3678]
### Checks

* [x] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
 pydantic version: 1.8.2
            pydantic compiled: False
            install path: /***/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.7 (default, Oct  5 2021, 10:17:32)  [GCC 9.3.0]
                     platform: Linux-5.11.0-43-generic-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'typing-extensions']
```

I need to create a dict in a very specific format, so I have been using pydantic to ensure that users provide the 
right information. I created a set of `BaseModel` classes that can be nested within each other and when we call the `self.dict(exclude_none=True)` function on the top parent it converts them from pydantic objects to dicts. The following 
are some stripped down `BaseModel` objects I've created:

```py
from pydantic import BaseModel

class Button(BaseModel):
    text: str
    style: str
    value: str
    action_id: Optional[str] = None

class Actions(BaseModel):
    elements: List[Button]

class Message(BaseModel):
    blocks: List[Union[Actions]]

```

When we try to nest the Button object within a couple layers of pydantic objects, it simply doesn't render.

```py
message = Message(
        blocks=[
            Actions(
                elements=[
                    Button(
                        text='some text',
                        style='random',
                        value='test',
                        action_id='test',
                    )
                ]
            ),
        ]
    )
```

This returns:

```py
{
 'blocks': []
}
```

Which doesn't contain the data from the `Actions` object. The expected output should be:

```py
{
 'blocks': [
   {
     'elements': [
      {
       'text': 'some text',
       'style': 'random',
       'value': 'test',
       'action_id': 'test'
     } 
    ]
   }
 ]
}
```

I thought maybe it was null, but I can create the array `elements` outside and just pass it in as a parameter and it still doesn't exist. This makes me think that for some reason deeply nested objects are possibly not recognized by pydantic?

**Comment by bmizhen** [comment]
I just tested it with the latest code from the main branch and it works as expected.

`from typing import Optional, List, Union

from pydantic import BaseModel


class Button(BaseModel):
    text: str
    style: str
    value: str
    action_id: Optional[str] = None


class Actions(BaseModel):
    elements: List[Button]


class Message(BaseModel):
    blocks: List[Union[Actions]]


message = Message(
    blocks=[
        Actions(
            elements=[
                Button(
                    text='some text',
                    style='random',
                    value='test',
                    action_id='test',
                )
            ]
        ),
    ]
)

print(message)
`

**Comment by yasamoka** [comment]
Works normally here, gives the expected output. Version 1.9.0.

**Comment by Nathan-Nesbitt** [comment]
Closing because I cannot continue to test this as I am no longer with the team that found it!
