### ISSUE TITLE
Feature Request: multiple_of support for constrained numerics

### ISSUE THREAD

**Issue by StephenBrown2** [samuelcolvin/pydantic#368]
I would like there to be an option for constraining ints, floats, and Decimals to be a multiple of another such entity.

For example: I have a minute field that can only be in multiples of 15, or an hour field that could be in multiples of 0.5.

This would align with jsonschema and OpenAPI definitions, and be output as 'multipleOf' on affected fields.

I've got an implementation working locally, but wanted to know if the feature is desired/acceptable.

**Comment by samuelcolvin** [comment]
In general I works say you could just do this with validators, but I agree that doesn't help with schema. 

Either we could add this or add a genetic way to modify the schema on a field.

I think the second option would be more powerful.

**Comment by StephenBrown2** [comment]
Definitely, the second option would be powerful, but the validation is important for the model in my mind. Previously I had been using a custom validator, but having it part of the `conint|float|decimal(` call makes my model definition much cleaner.

Perhaps the Schema class could be used? But I'm not entirely sure how that would work.

I'll submit my PR with the current changes, and we can continue to discuss whether to go with that or the more powerful option.

**Comment by samuelcolvin** [comment]
> add a genetic way to modify the schema on a field.

This would be best done with an argument to `Schema` eg. 

```py
def modify_foobar_schema(schema):
  return {'multipleOf': 5, **schame}

class MyModel(BaseModel):
  foobar: int = Schema(..., modify_schema=modify_foobar_schema)
```
