### ISSUE TITLE
Adding `list[Annotated[str, Field(min_length=1)]]` before other fields causes unrelated ValueError

### ISSUE THREAD

**Issue by fictorial** [samuelcolvin/pydantic#3702]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /Users/brianhammond/Desktop/pez/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.0 (default, Jan 11 2022, 16:51:17) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-12.1-x86_64-i386-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```

```py
from typing import Annotated
from pydantic import Field, BaseModel

NonEmptyStr = Annotated[str, Field(min_length=1)]

class Foo(BaseModel):
    xs: list[NonEmptyStr]
    id: NonEmptyStr

foo_ok = Foo(id="some_id", xs=["hello"])
foo_too_short = Foo(id="", xs=["hello"])
```

Unexpected error:

```
ValueError: `Field` default cannot be set in `Annotated` for 'id'
```

Yet, if the `xs` field is moved after `id`, no problem:

```py
from typing import Annotated
from pydantic import Field, BaseModel

NonEmptyStr = Annotated[str, Field(min_length=1)]


class Foo(BaseModel):
    id: NonEmptyStr
    xs: list[NonEmptyStr]


foo_ok = Foo(id="some_id", xs=["hello"])
foo_too_short = Foo(id="", xs=["hello"])
```

Expected error:
```
pydantic.error_wrappers.ValidationError: 1 validation error for Foo
id
  ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)
```

The error occurs also if such a field is defined in another class, but only if defined *earlier*:

```py
from typing import Annotated
from pydantic import Field, BaseModel

NonEmptyStr = Annotated[str, Field(min_length=1)]


class Bar(BaseModel):
    xs: list[NonEmptyStr]


class Foo(BaseModel):
    id: NonEmptyStr


foo_ok = Foo(id="some_id", xs=["hello"])
foo_too_short = Foo(id="", xs=["hello"])
```

Unexpected error:

```
ValueError: `Field` default cannot be set in `Annotated` for 'id'
```

Defined later:

```py
from typing import Annotated
from pydantic import Field, BaseModel

NonEmptyStr = Annotated[str, Field(min_length=1)]


class Foo(BaseModel):
    id: NonEmptyStr


class Bar(BaseModel):
    xs: list[NonEmptyStr]


foo_ok = Foo(id="some_id", xs=["hello"])
foo_too_short = Foo(id="", xs=["hello"])
```

Expected error:

```py
pydantic.error_wrappers.ValidationError: 1 validation error for Foo
id
  ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)
```

I'm guessing but it seems like some kind of reference is being held onto between contexts...

Thanks for any help, info, etc.

**Comment by fictorial** [comment]
Perhaps this is related to https://github.com/samuelcolvin/pydantic/issues/2971

**Comment by fictorial** [comment]
I forked this repo, applied the workaround from https://github.com/samuelcolvin/pydantic/issues/2971 but alas, it wasn't the root cause...

**Comment by fictorial** [comment]
The `.default` on field info was `None` and not `Undefined` ...

**Comment by fictorial** [comment]
Hmm, it seems that the actual default value is being referenced later.

**Comment by jordan-dimov** [comment]
I have essentially the same issue with a FastAPI view which is decorated with:

    response_model = List[schemas.AnyPlant]

where AnyPlant is defined as:

    AnyPlant = Annotated[
        Union[Herb, Shrub, Tree],
        Field(discriminator='plant_type'),
    ]

The error I get is: 

    ValueError: `Field` default cannot be set in `Annotated`
