### ISSUE TITLE
Issue with import in dataclasses on version 1.9.0 in TravisCI

### ISSUE THREAD

**Issue by umluizlima** [samuelcolvin/pydantic#3742]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Hi!

While maintaining a personal project I noticed that the build started to fail on TravisCI. It had been a while since I last touched it, so I started to look into it and it seems to be an issue while importing `BaseSettings` on `pydantic` 1.9.0.

Here's a screenshot of the build logs, where it raises a `ImportError: /home/travis/virtualenv/python3.10-dev/lib/python3.10/site-packages/pydantic/dataclasses.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyDescr_IsData`:
<img width="1019" alt="Screen Shot 2022-01-27 at 13 38 51" src="https://user-images.githubusercontent.com/9170476/151403130-79723d8f-653c-4329-a032-cc2ee287624d.png">

I then went back into CI build history to the last time it finished successfully (11/28/2021) and noticed that it was using `pydantic` 1.8.2, as shown below:
<img width="1019" alt="Screen Shot 2022-01-27 at 13 42 11" src="https://user-images.githubusercontent.com/9170476/151403816-4081b689-17e1-4eed-8578-e024655180a1.png">

After this I specified `pydantic` to be 1.8.2 in my `requirements.txt` and the build passed. I could not reproduce this locally.

I apologize if this issue doesn't belong to `pydantic` itself, or maybe to `FastAPI` as it was installed as a sub dependency before, or even to TravisCI.

Here's a link to the PR in which I noticed the issue: https://github.com/umluizlima/user-manager/pull/49

**Comment by samuelcolvin** [comment]
`PyDescr_IsData` is somewhere deep in the C API of python.

I suspect this relates to the age of the OS any which manylinux base we use.

I'm closing this issue for now.
