### ISSUE TITLE
Skip optional fields

### ISSUE THREAD

**Issue by dgasmith** [samuelcolvin/pydantic#378]
# Feature Request

We often drop pydantic objects into a NoSQL database where the individual object (document) structure is fairly sparse with quite a few defaults. To save space we often prune out the defaults as they can be regenerated on the fly fairly quickly. To this end, it would be useful to be able to drop results that have been defaulted when serializing automatically.

```py
from pydantic import BaseModel
from typing import Optional

class User(BaseModel):
    id: int
    value: Optional[int]= None # Or some other decorator like Skip[int]?

u = User(id=5)
>>> print(u)
User id=5 value=None
>>> print(u.dict())
{'id': 5, 'value': None}

# Desired feature
>>> print(u.dict(skip_optional=True))
{'id': 5}

>>> u2 = User(id=5, value=5)
{'id': 5, 'value': 5}
```

Again, happy to add some code here if this is a feature you would consider.

**Comment by samuelcolvin** [comment]
Humm, seems to me to be two ways of doing this:
1. when serialising the model, check whether each field's value matches its default, and ignore ones that do.
2. keep a record of which values are missing (and/or have the default value?) when initially parsing the input data to create a model.

My preference would be for 1. since it won't affect parsing performance and shouldn't affect serialisation performance unless `skip_optional=True` is set.

There's also the question do we:
* skip all fields which have the default value from the model
* or, skip only fields which are (somehow?) annotated as "skipped when default"

let me know your thoughts on both these points and we'll go from there.

My suspicion is that that is possible, but we need to think about the best way of doing it.

**Comment by dgasmith** [comment]
1) Our implementation is to add a set called `changed_keys` which becomes a copy of the input dictionary keys and then if a field is set during a run the `changed_keys` set is updated with that key. When `dict` is called the `exclude` field is updated with this `changed_keys` set. The effect on the performance would likely be minimal.

2) I think it would be good to have control over which fields are excluded by default. This could either be in the `Config.skip_defaults={"key1", ...}` where the exclude field would be `changed_keys & skip_defaults` or using a custom type like `value: DefaultSkip[str]= "hello` which would then internally build the `skip_defaults` set.

After thinking about it, the `Config.skip_defaults` (or whatever name) seems like the way to go. We might even be able to rig it so that `Config.skip_defaults = `:
 - `True`, skip all fields not given in the input or changed.
 - `False`, current functionality
 - `set()`, only skip these fields if not changed.

**Comment by samuelcolvin** [comment]
I'm not keen at all on using a `DefaultSkip` type, that's a misuse of types (perhaps we shouldn't have done it for `JSON` either).

Regarding `Config.skip_defaults`, I think this is just an added complication. If you really need it you can easily implement it yourself by implementing your own `CustomBaseModel`. Or am I missing something?

The `changed_keys` approach makes sense, this is roughly what I've used before [here](https://github.com/samuelcolvin/aiohttp-toolbox/blob/14b1a4a94355826f5921c7066bd6ca2284534165/atoolbox/bread/main.py#L334-L347).

Question: is this something that really needs to be added to pydantic? I'm not saying it definitely shouldn't be, but I'm keen to avoid the library growing esponentially and that involves being sure something is necessary before adding it.

**Comment by dgasmith** [comment]
Agreed on `DefaultSkip` (I actually suggested it due to the `JSON` field!).

This doesn't need to be in pydantic, and we do have our own `CustomBaseModel` currently. An argument for having this in pydantic is that `changed_keys` touches the `__init__`, `__setattr__` and `dict` functions which is fairly low level. I get a bit nervous that we may miss an edge case.

Either way these conversations help clarify our implementation and helps me find the line of what should be added to pydantic and what we should write on our own.

**Comment by samuelcolvin** [comment]
On reflection, I'm happy to accept a PR to add `fields_set` to a model. 

It will require a change to the signature of `validate_model` but I'm ok with that, we'll just need to add a "breaking change" notice to the release notes.

I would wait until #373 is merged to work on this to avoid lots of conflicts.

**Comment by dgasmith** [comment]
Great, I will work on it after #373. Should be a straightforward change.

**Comment by dgasmith** [comment]
Planning to work on this a bit this weekend. To recap the idea:
 - Add a `_fields_set = set()` attribute to the MetaModel (or BaseConfig?) so we have an idea what is defaulted and was not.
 - We modify `self.dict` to include a `skip_defaults=False`

Questions:
 - Do we want a Config that can alter the default of this value?

**Comment by samuelcolvin** [comment]
`__fields_set__` should be on the model itself.

I think the config property is unnecessary, people can do that themselves if they want.

**Comment by dgasmith** [comment]
Ok, so we should add another slot for `__fields_set__`?

**Comment by samuelcolvin** [comment]
Yes

**Comment by samuelcolvin** [comment]
Yes

**Comment by codedumps** [comment]
И что в итоге делать? Как пропускать Optional? Я решил на свою дурную голову fastapi использовать, а там вместо нормального marshmallow это говно. Автор, аутист ебучий, что за хуйню, ты придурок жизни написал, запили мне skip_optional, блять.

**Comment by PaulRudin** [comment]
Incidentally, you can achieve something similar by using a root validator with pre=True to add data for a derived field. So you don't have a property, but you have the computed value created when the model is created. This works fine for immutable models (which is my use case).
