### ISSUE TITLE
Mangled data for union type input 

### ISSUE THREAD

**Issue by robcxyz** [samuelcolvin/pydantic#3800]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: False
               python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
                     platform: Linux-5.8.0-45-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
```

In this example, I can't understand why pydantic is mangling the type input. 

```python
from pydantic import BaseModel
from typing import Union, List


class Foo(BaseModel):
    bar: Union[str, dict, List[dict]]

f = Foo(bar=[{'foo': 'bar', 'stuff': 'things'}])
assert f.bar == {'foo': 'stuff'}
```

Why is the type changing from a list to a dict and further mangling the keys into a key value pair? Don't know if this is pydantic specific or just typing issues.

**Comment by PrettyWood** [comment]
Hi @robcxyz 
You can see https://github.com/samuelcolvin/pydantic/issues/3614#issuecomment-1004322903 to fix your issue.
The problem is that pydantic by default tries to coerce against types of the union.
And `dict([{'foo': 'bar', 'stuff': 'things'}]) == {'foo': 'stuff'}`
Hope it helps

**Comment by robcxyz** [comment]
Perfect thank you so much @PrettyWood
