### ISSUE TITLE
Assignment to enum field does not converts type

### ISSUE THREAD

**Issue by GoldsteinE** [samuelcolvin/pydantic#384]
# Bug

* OS: Linux lptp 4.20.6-arch1-1-ARCH #1 SMP PREEMPT Thu Jan 31 08:22:01 UTC 2019 x86_64 GNU/Linux
* Python version: 3.7.2
* Pydantic version: StrictVersion ('0.18.2')

```py
from pydantic import BaseModel
from enum import Enum


class TestEnum(Enum):
    a = "a"
    b = "b"


class Model(BaseModel):
    q: TestEnum = TestEnum.a


m = Model()
m.q = "b"
print(m.q)
print(type(m.q))
```
gives
```
b
<class 'str'>
```
IMO, pydantic should either disallow such assignment or automatically convert `str` to enum member. For now `m.q` has actual type `str` while it's mypy revealed type would be `TestEnum`.

**Comment by samuelcolvin** [comment]
as per the documentation you need:

```py
class Model(BaseModel):
    q: TestEnum = TestEnum.a

    class Config:
        validate_assignment = True
```

Let me know if it still doesn't work.
