### ISSUE TITLE
`error checking inheritance` with Generic Alias Types (PEP 585)

### ISSUE THREAD

**Issue by sz3lbi** [samuelcolvin/pydantic#3879]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: C:\Users\Norbert\Desktop\repos\tw_action_planner\venv\Lib\site-packages\pydantic
               python version: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.19044-SP0
     optional deps. installed: ['typing-extensions']
```

Hello,
I have found a bug when using Pydantic with the SQLModel and Alembic libraries, but it can be ealisy reproduced without the use of those libraries.

In general, when I am importing my models in Alembic's `env.py` file and then run the automatic revision generation, I get the error:
`RuntimeError: error checking inheritance of 'ServerConfig' (type: str)`
It is caused by using the generic alias type `list["ServerConfig"]`. When I import the `List` from the `typing` and then use it instead, everything works fine.
Why am I using a string as a type annotation? To prevent the circular imports as described at [SQLModel: Type Annotations and Runtime](https://sqlmodel.tiangolo.com/tutorial/code-structure/#type-annotations-and-runtime)

To simplify things, I have created the MRE and published it as a repo: https://github.com/sz3lbi/pydantic_generic_alias_types_bug
When you run the `ok.py` file, everything works as expected and running the `error.py` causes the `RuntimeError`. To simulate the Alembic imports, I am importing models inside the `__init__.py` file.

The only information I have found about the bug is this comment on the Pydantic's GitHub: https://github.com/samuelcolvin/pydantic/issues/2132#issuecomment-1012686279

**Comment by aleksul** [comment]
I think this is a duplicate of #2798. If you can, please confirm that PR #3681 fixes this issue.

**Comment by sz3lbi** [comment]
It looks like it does. Thanks @aleksul.
