### ISSUE TITLE
Not enforced field constraints when using Sequence

### ISSUE THREAD

**Issue by finswimmer** [samuelcolvin/pydantic#3890]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) <strike>and still think this is a bug</strike>

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /home/finswimmer/tmp/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
                     platform: Linux-5.4.0-90-generic-x86_64-with-glibc2.29
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

```py
from typing import Sequence

from pydantic import BaseModel, Field


class A(BaseModel):
    t: Sequence[int] = Field(min_items=1)
```

Hello everyone,

running the above code snippet raises this error:

```
ValueError: On field "t" the following field constraints are set but not enforced: min_items. 
For more details see https://pydantic-docs.helpmanual.io/usage/schema/#unenforced-field-constraints
```

I have read the mentioned documentation, but I don't understand why it should apply here. So I'm not sure whether this is a bug report or more question to understand what's going on.

I my real world scenario I have a List of objects derived from a class which inherits from another class. Using `List[MyClass]` leads to an error by mypy due to https://mypy.readthedocs.io/en/stable/common_issues.html#variance. That's why I'm trying to use `Sequence` instead of `List` here.

So is the error message by pydantic here correct or is it a bug?

Thanks a lot!

fin swimmer

**Comment by samuelcolvin** [comment]
Looks like we just don't support `min_items` for Sequences. I guess we could add it, but I think better to wait for a rewrite in v2.
