### ISSUE TITLE
How to unpack other BaseSettings configuration under BaseSettings without using some variable

### ISSUE THREAD

**Issue by anandtripathi5** [samuelcolvin/pydantic#3891]
I'm facing a issue in unpacking of BaseSettings configurations for example

from pydantic import BaseSettings, Field

```
class One(BaseSettings):
    v1 = '123'
    
class Base(BaseSettings):
    v2 = '1234'
    one = One()
    
settings = Base()

```
Now I can access v1 by
`settings.one.v1`

My question is how can I use v1 by 
`settings.v1`

I dont want to use `locals` or `vars` to unpack

**Comment by BCarley** [comment]
I think you might have accidentially set the wrong label, this is not a `bug`.

What is stopping you from using `settings = One()` in this case? This kind of question is more of a `python` help question and would be better suited to something like [`StackOverflow`](https://stackoverflow.com/).

**Comment by anandtripathi5** [comment]
So consider that I am using Base as application settings object. That is being used every where in the application. Previous to pydantic I was using simple class with environment variables inside. Now I want to categorize three-four variables in some class object and have to put that inside base configuration.
for now I can use it in a nested way like
`settings.S3.some_bucket ` (if S3 here is One) but I want to use it in a non nested way. something like `settings.some_bucket`
@BCarley 
Hope now you think its not a general question for Stackoverflow. I

**Comment by anandtripathi5** [comment]
ohh yeah I missed that one. Thanks for this

**Comment by BCarley** [comment]
@anandtripathi5 - do you want to close the issue and remove the `bug` label?
