### ISSUE TITLE
Include a PEP 561 marker file

### ISSUE THREAD

**Issue by je-l** [samuelcolvin/pydantic#390]
# Feature Request

Hi,

The new version 0.19 has improved typing support which is great, but looks like it doesn't work out of the box. I had similar problems as described in #245 , but after adding the installation to MYPYPATH it works fine.

I think a PEP 561 marker file `py.typed` should be added so that tools like mypy can utilize the inline type information without any configuration. Reading mypy docs looks like there is a downside that `zip_safe` must be disabled for this.

https://mypy.readthedocs.io/en/latest/installed_packages.html
https://www.python.org/dev/peps/pep-0561/

**Comment by samuelcolvin** [comment]
Very annoying about the `zip_safe` thing, but I guess no choice.

PR welcome.

**Comment by samuelcolvin** [comment]
Should be fixed and released in `v0.20a1`, I've done an alpha release so we can check this works without affecting most users.

Please install with `pip install pydantic==0.20a1` and let me know if the issues are all fixed for you?

**Comment by samuelcolvin** [comment]
Just tried this myself and it seems to work fine.

**Comment by je-l** [comment]
Tested the release and it indeed seems to be working nicely! The example in #245 gives an informative error message `pydantic_repro.py:8: error: "Model" has no attribute "agee"; maybe "age"?`
