### ISSUE TITLE
Question: How to use a reserved BaseModel attribute?

### ISSUE THREAD

**Issue by batisteo** [samuelcolvin/pydantic#395]
# Question 

* OS: **GNU/Linux Fedora 29**
* Python version: **3.6.8**
* Pydantic version: **0.19**

I’d like to migrate from `attr.s` to Pydantic, but I’ve got a couple of models that have the name _schema_ as attribute. Ideally, I would like to not change other parts of the code base except from the model itself.

```python
from pydantic import BaseModel


class Card(BaseModel):
    card_schema: tuple

    class Config:
        fields = {"card_schema": "schema"}


class Transaction(BaseModel):
    card: Card


card = Card(schema=("abc", "xyz"))

card.schema
# <bound method BaseModel.schema of <class '__main__.Card'>>

card.schema()
# {'title': 'Card', 'type': 'object', 'properties': {'schema': {'title': 'Schema', 'type': 'array'}}, 'required': ['schema']}

card.card_schema
# ('abc', 'xyz')


transaction = Transaction(card=card)
```
```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    transaction = Transaction(card=card)
  File "~/proj/.venv/lib64/python3.6/site-packages/pydantic/main.py", line 214, in __init__
    self.__setstate__(self._process_values(data))
  File "~/proj/.venv/lib64/python3.6/site-packages/pydantic/main.py", line 386, in _process_values
    return validate_model(self, input_data)  # type: ignore
  File "~/proj/.venv/lib64/python3.6/site-packages/pydantic/main.py", line 551, in validate_model
    raise ValidationError(errors)
pydantic.error_wrappers.ValidationError: 1 validation error
card -> schema
  field required (type=value_error.missing)
```

Having a look at #243 it seems that the following names for model attributes are not allowed:
```
Config
construct
copy
dict
fields
json
parse_file
parse_obj
parse_raw
schema
schema_json
to_string
update_forward_ref
validate
```
Would it be possible to consider renaming some of these methods with underscore, like `_schema` or `__schema__`?

Maybe something like what [django-meta is doing](https://django-meta.readthedocs.io/en/latest/models.html#usage).

I know it would be a breaking change, that’s what the `0.*` is for, right? :grimacing:

**Comment by samuelcolvin** [comment]
Good news! This was fixed yesterday in release `0.20a1`, please check that and let me know if you still have problems (you'll need to use field aliases, aka `Config.fields`).

I'll make that alpha release a proper release in a few days unless we find any problems.

**Comment by batisteo** [comment]
It’s indeed fixing the ValidationError. Thanks!

**Comment by batisteo** [comment]
> Would it be possible to consider renaming some of these methods with underscore, like `_schema` or `__schema__`?

Or allowing shadowing the way does Django with defaulting Model.objects to Model._default_manager?

https://stackoverflow.com/questions/34427817/django-difference-between-base-manager-and-objects

**Comment by samuelcolvin** [comment]
I see your point on renaming, perhaps we should have started out by naming all those methods `_...` eg. `_dict`, this is what `named_tuple` does for example. 

However changing all those models now would break a lot of code, SemVar or not this would take me alone hours to fix across all the projects using pydantic. It would also upset mypy and IDEs when people access "private" properties.

I think the best solution at this stage is aliases.

**Comment by batisteo** [comment]
I know :pensive:

**Comment by batisteo** [comment]
> It would also upset mypy and IDEs when people access "private" properties.

Do you get warnings from IDE when you access, for example, [`_make()` or `_asdict()` of a NamedTuple](https://docs.python.org/3/library/collections.html?highlight=collections%20namedtuple#collections.somenamedtuple._make)?

**Comment by samuelcolvin** [comment]
In pycharm yes.
