### ISSUE TITLE
Feature request: ForwardRef support for dataclasses

### ISSUE THREAD

**Issue by ceelian** [samuelcolvin/pydantic#397]
# Bug

With python 3.7+ `from __future__ import annotations` the example is broken and raises an exception.

* OS: OS X 10.13.6 (17G4015)
* Python version: **3.7.1**
* Pydantic version: **0.19**

```py
# only the following line was changed compared to the example
# in the docs https://pydantic-docs.helpmanual.io/#nested-dataclasses
from __future__ import annotations 

from pydantic import UrlStr
from pydantic.dataclasses import dataclass

@dataclass
class NavbarButton:
    href: UrlStr

@dataclass
class Navbar:
    button: NavbarButton

navbar = Navbar(button=('https://example.com',))
print(navbar)
```

```bash
 python foo.py
Traceback (most recent call last):
  File "foo.py", line 13, in <module>
    navbar = Navbar(button=('https://example.com',))
  File "<string>", line 3, in __init__
  File "/tmp/env/lib/python3.7/site-packages/pydantic/dataclasses.py", line 25, in _pydantic_post_init
    d = validate_model(self.__pydantic_model__, self.__dict__)
  File "/tmp/env/lib/python3.7/site-packages/pydantic/main.py", line 508, in validate_model
    f"field {field.name} not yet prepared and type is still a ForwardRef, "
pydantic.errors.ConfigError: field button not yet prepared and type is still a ForwardRef, you'll need to call MetaModel.update_forward_refs()

```

**Comment by samuelcolvin** [comment]
This isn't a bug, it's a feature request.

> the example is broken and raises an exception

Wrong, this isn't the example. This is some other code that looks like the example, adding lazy type evaluation via `from __future__ import annotations` completely changes the context.

**Comment by samuelcolvin** [comment]
should be fixed by #399, let me know if this fixes the issue for you.

**Comment by ceelian** [comment]
Well, the example code works in a standalone script with the new version, but not in my pytest in the project I use it. Can't figure it out why at the moment, but I am pretty sure that might not be related to pydantic. Although the error I get is from the new version:

`pydantic.errors.ConfigError: field "button" not yet prepared so type is still a ForwardRef, you might need to call MetaModel.update_forward_refs().`

 and the python env with pytest is exactly the same as with the standalone script.

**Comment by samuelcolvin** [comment]
Because, for pydantic to be able to resolve type annotations, they need to be global in the module.

**Comment by ceelian** [comment]
Ah, got it. Thank you for clarification and the fast implementation of the new feature!

**Comment by viniciusd** [comment]
Sorry for getting back to this issue, but I am currently facing this error on Python 3.8.0 and I am not sure what exactly you mean with `they need to be global in the module` @samuelcolvin 

I currently have:
```
class Foo(BaseModel):
    value: Optional[str]

class FlightMediaListPayload(BaseModel):
    foos: List[Foo]
```

They are both in the same module.

**Comment by dpriskorn** [comment]
> Because, for pydantic to be able to resolve type annotations, they need to be global in the module.

I'm a beginner of pydantic. I don't understand "global in the module" and run into the same error as @ceelian. Could someone elaborate?
