### ISSUE TITLE
Parse object/file/raw with Union type

### ISSUE THREAD

**Issue by ka7eh** [samuelcolvin/pydantic#3985]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
I did some search, but I couldn't find anything saying if this behavior is intentional and discussed before or a bug.

If I have a model with an attribute that accepts both `str` and `int`, and `str` is the first entry in `Union`, then `parse_obj_as` and similar functions always cast the attribute to `str`. If `str` is put at the end, the parsing works fine.

I expected the values to get parsed as they are specified in the object, regardless of the order of the items in `Union`.
Check out the code snippet below for an example.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /home/kaveh/Workspace/Dev/OpenSource/ctsm-api/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.2 (main, Feb 12 2022, 18:28:09) [GCC 11.2.0]
                     platform: Linux-5.16.15-76051615-generic-x86_64-with-glibc2.34
     optional deps. installed: ['dotenv', 'typing-extensions']

...
```

```py
import pydantic
import typing

class A(pydantic.BaseModel):
  value1: typing.Union[str, int]
  value2: typing.Union[int, str]

# `value1` is parsed as `str` and `value2` as int. I expected to get `int` for both values.
pydantic.parse_raw_as(A, '{"value1": 1, "value2": 2}')    # A(value1='1', value2=2)

# Both `value1` and `value2` are parsed as `str`, which is expected.
pydantic.parse_raw_as(A, '{"value1": "a", "value2": "b"}')    # A(value1='a', value2="'b')
...
```

**Comment by PrettyWood** [comment]
Hi @ka7eh. You can set `Config.smart_union = True`

**Comment by ka7eh** [comment]
My bad! Apparently, I didn't do enough research. :)
Thanks for the help, @PrettyWood.
