### ISSUE TITLE
mypy broke `Schema` behavior

### ISSUE THREAD

**Issue by Derfirm** [samuelcolvin/pydantic#400]
# Bug

* OS: macOS 10.14.3 (18D109)
* Python version : 3.7.0
* Pydantic version: 0.20
* mypy version: 0.670

```py
from pydantic import BaseModel, Schema


class User(BaseModel):
    name: str = Schema(..., description="User name", example="John")
    surname: str = Schema(..., description="Surname", example="Doe")
```
After update to new version of `mypy` command `mypy --ignore-missing-imports example.py` will fail with results
```
example.py:5: error: Incompatible types in assignment (expression has type "Schema", variable has type "str")
example.py:6: error: Incompatible types in assignment (expression has type "Schema", variable has type "str")
```

**Comment by samuelcolvin** [comment]
Yes, you'll need to add `#  type: ignore` to those lines. This is because as of #391 mypy can now read pydantic type annotations properly.
