### ISSUE TITLE
BaseSettings does not work with hyphens in secrets file name.

### ISSUE THREAD

**Issue by parkournerd** [samuelcolvin/pydantic#4001]
Environment:
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /home/tin/Code/crowdprivy/crowdprivy/backend/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.2 (main, Mar 11 2022, 18:50:48) [GCC 10.2.1 20210110]
                     platform: Linux-5.17.0-3.1-liquorix-amd64-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']

Bug:
    When I use BaseSettings WITH the secrets_dir provided, secrets importing works fine with a secrets file name of "auth_symmetric_key" but not "auth-symmetric-key". The contents are identical. It seems like the hyphen is messing things up.

**Comment by samuelcolvin** [comment]
Please provide a self contained example of the problem.

**Comment by parkournerd** [comment]
My bad, I thought secrets were handled like ENV files and happened to name my first secret the name of a setting.
