### ISSUE TITLE
Using string as type parameter fails when used with builtins (in Python 3.9+)

### ISSUE THREAD

**Issue by jkinkead** [samuelcolvin/pydantic#4003]
# Bug

Using a string for a type name fails when using builtins. This works as expected with other types.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: False
                 install path: /Users/jkinkead/.pyenv/versions/3.9.12/envs/myenv-3.9.12/lib/python3.9/site-packages/pydantic
               python version: 3.9.12 (main, Apr 11 2022, 10:35:43)  [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-11.6.5-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Example:

```py
import pydantic
from typing import List

# This is fine.
class WorksFine(pydantic.BaseModel):
    field: List["str"]

# This raises an exception.
class DoesNotWork(pydantic.BaseModel):
    field: list["str"]
```

Obviously the above is a canned example. I ran into this porting some classes with forward refs to use the 3.9 built-in type parameters, and had to convert to using `from __future__ import annotations` instead.

**Comment by samuelcolvin** [comment]
This is a limitation of python 3.9, I believe it should work in 3.10.
