### ISSUE TITLE
[Feature request] [VS Code] No auto complete when using pydantic.dataclasses.dataclass

### ISSUE THREAD

**Issue by giuliano-oliveira** [samuelcolvin/pydantic#4006]
# Feature request

Similar to the issue that #2721 solves, VS Code can't auto complete models constructor parameters when using `pydantic.dataclasses.dataclass`.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /tmp/hello-world/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
                     platform: Linux-5.10.105-1-MANJARO-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

Example Code:
```python
import pydantic
from pydantic.dataclasses import dataclass

@dataclass
class Hello:
    n: int
    s: str

hello = Hello(n=1, s="a")
hello.n
```

VS Code:

https://user-images.githubusercontent.com/13181797/164987610-f6704c45-3afd-4b92-9a8a-b9addeb83dd9.mp4

# Workaround:
You can import python pure dataclass instead of pydantic's dataclass when type checking, as stated by @JosXa [here](https://github.com/microsoft/python-language-server/issues/1898#issuecomment-743645817):

```python
from pydantic.dataclasses import dataclass
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass as dataclass
```

**Comment by samuelcolvin** [comment]
There is not bug in pydantic described here.

**Comment by giuliano-oliveira** [comment]
@samuelcolvin Are you sure? it's simillar to the issue that this PR solves: https://github.com/samuelcolvin/pydantic/pull/2721

Or you mean this issue should be a feature request? ( I was undecided about this when creating this issue sry)

**Comment by samuelcolvin** [comment]
Maybe it's the same as #2721. There was m really wasn't enough detail on the issue.

Either way, it's a feature request.
