### ISSUE TITLE
[BUG] Issue with email-validator in test environment

### ISSUE THREAD

**Issue by cgaunet** [samuelcolvin/pydantic#4009]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Since [email-validator](https://github.com/JoshData/python-email-validator) dependency has been bumped in 1.2.0, it refuses domain name like `@example.com`

I believe many projects (including ours) use such domain names in testing environments.
For this case, email-validator has given a parameter to be used in testing environments that disable the raise of an error if testing domain names are used in testing environments (`test_environment=True`)

The `requirements.txt` file of Pydantic specifies versions that are prior to 1.2.0 and thus working perfectly.
However, the `setup.py` file of Pydantic specifies version >=1.0.3 and the breaking change of email-validator has not been fixed

# Suggestion

I suggest that `setup.py` points the same version of `email-validator` as the one of `requirements.txt`

**Comment by sholmesy** [comment]
Encountered this exact issue when upgrading all our services, feels such a bizarre choice for the dependancy to invalidate `example.com` as it is fairly common usage. 

I agree that either of the solutions proposed above (documenting or passing down the argument) seem reasonable.

**Comment by samuelcolvin** [comment]
It seems 1.2.1 mostly reversed the changed and removed `example.com/org/net` from invalid domains.

With that, I don't think any change is necessary.

But thanks for altering me to this and proposing the change.

**Comment by fozt** [comment]
Hello, the emails `john@example.test`, `john@example.local` and others with domains `['arpa', 'invalid', 'local', 'localhost', 'onion', 'test']` are also invalid. Do you plan to change to `test_environment=True`?
