### ISSUE TITLE
Ability do have calculated fields

### ISSUE THREAD

**Issue by daltonmatos** [samuelcolvin/pydantic#401]
# Question / Feature Request 

* OS: **Linux**
* Python version `import sys; print(sys.version)`: **3.6.6 (default, Aug  9 2018, 14:01:04)**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **0.14**

Hello!

I would like to know if there is possible to have calculated fileds (at deserializarion time) in a pydantic Model.

A simple example:

```py
from typing import List
from pydantic import BaseModel

class Container(BaseModel):
    items: List[int] = []

instance = Container(**{"items": [1, 2, 3, 7])
print(instance.json())
```

The idea is that this code could print:
```
{
"items": [1, 2, 3, 7],
"size":  4
}
```

The `size` field (and any other, if necessary) would be calculated on the fly, during deserialization.

The main idea is to think of a way to declare this calculated field named `size`.

If it's not currently possible, what do you think about the idea of having this kind of field?

Thanks,

**Comment by samuelcolvin** [comment]
It's entirely possible.

Either with [validators](https://pydantic-docs.helpmanual.io/#validators) (you need to declare another field `size` **after** `items`, the validator will need to have `always=True` and take `values` as a keyword argument., then it can just `return len(values.get('items', []))`.

otherwise, you could just implement a property:

```py
...
@property
def size(self):
    return len(self.items)
```

**Comment by daltonmatos** [comment]
Thanks for the suggestion. The method I think is the best is the `property` implementation, but just addint the property to the model seems to not add this field to the final deserialized content:


```python
In [1]: from pydantic import BaseModel                                                                                                                                                        

In [2]: from typing import List                                                                                                                                                               

In [3]: class Container(BaseModel): 
   ...:     items: List[int] = [] 
   ...:     @property 
   ...:     def size(self): 
   ...:         return len(self.items) 
   ...:                                                                                                                                                                                       

In [4]:                                                                                                                                                                                       

In [4]: instance = Container(**{"items": [1,2,3]})                                                                                                                                            

In [5]: print(instance.json())                                                                                                                                                                
{"items": [1, 2, 3]}

In [6]:  
```

Is this what you meant for the `property` implementation?


The validator implementation works as expected, this is the model I used:

```python
In [13]: class Container(BaseModel): 
    ...:     items: List[int] = [] 
    ...:     size: int = 0 
    ...:     @validator('size', always=True) 
    ...:     def validate_size(cls, v,  values, **kw): 
    ...:         return len(values.get('items', [])) 

```

Thanks,

**Comment by samuelcolvin** [comment]
Yes, exactly.
