### ISSUE TITLE
Root validators pre=False are called before type checking

### ISSUE THREAD

**Issue by afcruzs** [samuelcolvin/pydantic#4017]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
               python version: 3.9.12 (main, Apr  5 2022, 06:56:58)  [GCC 7.5.0]
                     platform: Linux-5.13.0-40-generic-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'typing-extensions']
```

According to the [docs](https://pydantic-docs.helpmanual.io/usage/validators/#root-validators), root validators with `pre=False` should execute `after field validation.` However, I can see that when there's a type mismatch, they are executed before, see this snippet:

```py
from pydantic import BaseModel, validator, root_validator

class RunTimeConfig(BaseModel):

    x: int = 32
    double_x: int = None

    @root_validator(pre=False)
    def double_x_val(cls, values):
        values["double_x"] = values["x"] * 2
        return values

    @validator("x")
    def x_val(cls, x):
        print("exec x_val")
        return x

# This throws KeyError: 'x on double_x_val, instead of failing with a type checking error
print(RunTimeConfig(x="oops"))
```

If we don't access `values['x']` in the root validator, it will indeed fail with `value is not a valid integer (type=type_error.integer)` after executing `double_x_val`.  

*What I was expecting*: `@root_validator(pre=False)` will give me all the values 1) *after* type checking, and *2) after filling defaults*. Interestingly, if there isn't type mismatch (ie `x=42`), it follows the order I expected: `x_val -> double_x_val`.

Let me know if I'm reading incorrectly `after field validation.`, or if there's another suggestion for what I'm doing (see context below).

---
### Context

In a nutshell, I ended up here after reading https://github.com/samuelcolvin/pydantic/issues/1729#issuecomment-661868143.  I'm looking for dynamic fields creation, reminiscent of `__post_init__`, I tried with `@validators` as well but the type checking problem remains. I *could* add type checking manually on either type of validator, but I feel like that defeats the purpose a little bit.

*Workaround I've tried*: setting `pre=True` does fail with type checking before executing (what I expect). Unfortunately, it does execute the root_validator before it fills any default values (2nd thing I expected). See:

```py
class RunTimeConfig(BaseModel):

    x: int = 32
    double_x: int = None

    @root_validator(pre=True)
    def double_x_val(cls, values):
        values["double_x"] = values["x"] * 2
        return values

    @validator("x")
    def x_val(cls, x):
        print("exec x_val")
        return x

# This throws KeyError: 'x', instead of taking the 32 as default and run succeed on creating double_x
print(RunTimeConfig())
```

**Comment by samuelcolvin** [comment]
I think you just need `@root_validator(pre=False, skip_on_failure=True)`

**Comment by salman-altuwayjiri** [comment]
> 
Also if you check the example code in the [docs](https://pydantic-docs.helpmanual.io/usage/validators/#root-validators):
```py
class UserModel(BaseModel):
    username: str
    password1: str
    password2: str

    @root_validator
    def check_passwords_match(cls, values):
        pw1, pw2 = values.get('password1'), values.get('password2')
        if pw1 is not None and pw2 is not None and pw1 != pw2:
            raise ValueError('passwords do not match')
        return values
```
it checks the values if it is not none though in the model is required to be a string

**Comment by sharpnife** [comment]
```pre=False``` is not necessary it seems, ```@root_validator(skip_on_failure=True)``` is enough.
