### ISSUE TITLE
Is there a way to exclude invalid object from a list of objects with specific type?

### ISSUE THREAD

**Issue by Bahus** [samuelcolvin/pydantic#402]
# Question | Feature Request

Pre-requirements:

* OS: Mac OS X 10.14.3
* Python version `import sys; print(sys.version)`: 3.6.3
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.20

Hi, first of all thank you for the great package!

The questions is: if I have a nested list of objects how can I remove invalid object keeping only valid ones during a validation process?

Here is an example:

```py
from pydantic import BaseModel, conint
from typing import List


class Apple(BaseModel):
    weight: conint(gt=10)
    color: str


class BackPack(BaseModel):
    apples: List[Apple]


data = {
    'apples': [
        dict(weight=13, color='red'),
        dict(weight=21, color='green'),
        dict(weight=4, color='red'),
    ]
}

print(BackPack.parse_obj(data))
```

There is one "invalid" apple with a weight less then 10, so after validation is completed I want it to be removed from the list but keep the good ones. The only way I was able to find is to do a "manual" parsing of `data` before passing it to `BackPack` contructor:

```python
apples = []
for apple in data['apples']:
    try:
        apples.append(Apple.parse_obj(apple))
    except pydantic.ValidationError:
        # logging
        pass

BackPack(apples=apples)
```

But this solution is not elegant and clean, is there a better one?

Thank you in advance.

**Comment by samuelcolvin** [comment]
First of all, thanks for taking the time to format and explain your question clearly, this makes such a difference and made me far more willing to spend some time answering.

The short answer, unfortunately, is "not easily".

You can use validators, but you need `pre=True` and `whole=True` to get access to the raw data, otherwise, the exception has already been raised. Unfortunately, that means the data you have to process can be anything.

Here's one way of doing it, I'm not convinced it's that much better than your current approach:

```py
from pydantic import BaseModel, conint, validator, Decimal
from typing import List

class Apple(BaseModel):
    weight: conint(gt=10)
    color: str

class BackPack(BaseModel):
    apples: List[Apple]

    @validator('apples', pre=True, whole=True)
    def remove_bad_apples(cls, apples):
        if not isinstance(apples, (list, tuple)):
            # if we get here the apple doesn't look valid,
            # we return the original object and let normal pydantic validation
            # do it's stuff
            return apples

        good_apples = []
        for apple in apples:
            if isinstance(apple, dict):
                weight = apple.get('weight')
                if weight and isinstance(weight, (int, float, Decimal)):
                    if weight > 10:
                        good_apples.append(apple)
                    continue
            # if we get here the apple doesn't look valid,
            # we return the original object and let normal pydantic validation
            # do it's stuff
            return apples
        return good_apples

data = {
    'apples': [
        dict(weight=13, color='red'),
        dict(weight=21, color='green'),
        dict(weight=4, color='red'),
    ]
}

print(BackPack.parse_obj(data))
```

**Comment by samuelcolvin** [comment]
On reflection, here's a much cleaner way of doing things.

```py
from pydantic import BaseModel, validator
from typing import List

class Apple(BaseModel):
    weight: int
    color: str

class BackPack(BaseModel):
    apples: List[Apple]

    @validator('apples', whole=True)
    def remove_bad_apples(cls, apples):
        return [a for a in apples if a.weight > 10]

data = {
    'apples': [
        dict(weight=13, color='red'),
        dict(weight=21, color='green'),
        dict(weight=4, color='red'),
    ]
}

print(BackPack.parse_obj(data))
```

Unfortunately because you've removed `conint`, the schema now won't include that restriction. You could probably get around that using the `Schema` type if you care about it.

**Comment by Bahus** [comment]
Oh... In reality of course `"Apple"` model contains a lot of different fields (some of them nested) so your proposal is hard to implement for such complex objects. 

The improved solution I came up with may look like:

```python
class BackPack(BaseModel):
    apples: List[Apple]

    @validator('apples', pre=True, whole=True)
    def remove_bad_apples(cls, apples):
        filtered_apples = []

        for apple in apples:
            value, error = validate_model(Apple, apple, raise_exc=False)
            if not error:
                filtered_apples.append(value)

        return filtered_apples
```

However in this case apples validation is done twice thus performance can be a bit degraded but not critical.

I'm thinking about a sort of `processor` parameter for a validator, which allows to return already validated pydantic models (instead of raw values) from a validator. Or even it can be a separate method, e.g.:

```python
class BackPack(BaseModel):
    apples: List[Apple]

    @processor('apples', pre=True, whole=True)
    def remove_bad_apples(cls, apples):
        filtered_apples = []

        for apple in apples:
            try:
                filtered_apples.append(Apple.parse_obj(apple))
            except pydantic.ValidationError:
                # logging
                continue

        return filtered_apples
```

Does it make a sense?

**Comment by samuelcolvin** [comment]
I think as of v0.20 the validation will not be run twice for each model, see [here](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/main.py#L413).
