### ISSUE TITLE
BaseSettings dotenv configuration does not search parent directories

### ISSUE THREAD

**Issue by jpieger** [samuelcolvin/pydantic#4058]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: ~/.local/lib/python3.10/site-packages/pydantic
               python version: 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
                     platform: Linux-5.17.4-zen1-1-zen-x86_64-with-glibc2.35
     optional deps. installed: ['dotenv', 'typing-extensions']
```

Dotenv file loading via BaseSettings works differently than via dotenv directly.
When I load a .env file via dotenv, then the module will look in the current working directory and then it will search the parent directories recursively, until a .env file is found.

Pydantic will only check the the current working directory.

Assume the following directory structure:
```
.
├── .env
└── subfolder
    └── example.py
```
With the content of `.env`:
```
TEST=from_file
```

And `example.py`:

```py
import dotenv
import pydantic

class Example(pydantic.BaseSettings):
    test: str

    class Config:
        env_file = ".env"

    
if __name__ == "__main__":
    print(dotenv.dotenv_values())

    print(Example())
```

When I run the code while inside the directory with the `.env` file, everything works as expected:
```bash
$ python subfolder/example.py                                            
OrderedDict([('TEST', 'from_file')])
test='from_file'
```

But running the code from a subfolder, pydantic behaves differently from dotenv:
```bash
$ cd subfolder
$ python example.py                                                               
OrderedDict([('TEST', 'from_file')])
Traceback (most recent call last):
  File "/tmp/foo/subfolder/example.py", line 14, in <module>
    print(Example())
  File "~/.local/lib/python3.10/site-packages/pydantic/env_settings.py", line 36, in __init__
    super().__init__(
  File "~/.local/lib/python3.10/site-packages/pydantic/main.py", line 406, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Example
test
  field required (type=value_error.missing)
```

Imho this difference in behavior is a bug. The wording of the [documentation](https://pydantic-docs.helpmanual.io/usage/settings/#dotenv-env-support) suggests to me that the `.env` support works in the same way as dotenv handles it.

**Comment by samuelcolvin** [comment]
I think best if we keep the behaviour the same as currently, PR welcome to improve documentation on this.

**Comment by johnziebro** [comment]
@jpieger

Couldn't you just do the following to check parent directories for the .env file?

```
.
├── .env
└── subfolder
    └── example.py
```

```
With the content of .env:
TEST=from_file
```

```python
import dotenv
from pydantic import BaseSettings

class Settings(BaseSettings):
	test: str
	
	class Config:
		env_file = dotenv.find_dotenv()
		case_sensitive = False
```

**Comment by jpieger** [comment]
> Couldn't you just rely on [dotenv.find_dotenv()](https://github.com/theskumar/python-dotenv/blob/master/src/dotenv/main.py#L271) method as the value for Config's env_file attribute to check parent directories for the .env file

This is what we ended doing in the end. It behaves slightly different than what a built-in solution would do (as the .env file is only searched once when the module is imported and not every time when the BaseSettings object is instantiated), but this difference is not relevant for our use case.

One pitfall that we did stumble over, was that `find_dotenv()` does not start in the cwd by default, but from the file where it was called. We had to pass the argument `usecwd=True` in order to get the correct behaviour.

```python
class Example(pydantic.BaseSettings):
    test: str

    class Config:
        env_file = dotenv.find_dotfile(usecwd=True)
```

**Comment by johnziebro** [comment]
Is this implemented and if so, what version is it in? Thank you.

**Comment by analog-cbarber** [comment]
The problem with using `find_dotenv` in the model config is that it will get called when the module is first imported, so if you change your directory prior to instantiating an instance of your settings, you may not get what you expect.
