### ISSUE TITLE
Mypy plugin does not type check values in constructor

### ISSUE THREAD

**Issue by brent-moffit** [samuelcolvin/pydantic#4065]
### Checks

* [✅ ] I added a descriptive title to this issue
* [✅ ] I have searched (google, github) for similar issues and couldn't find anything
* [✅ ] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /Users/XXXX/.pyenv/versions/3.10.3/envs/pydantic-test/lib/python3.10/site-packages/pydantic
               python version: 3.10.3 (main, Apr 28 2022, 03:08:31) [Clang 13.1.6 (clang-1316.0.21.2.3)]
                     platform: macOS-12.3.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Output of `mypy --version`:
```
mypy 0.950 (compiled: yes)
```

When constructing a model instance, type-checkers do not check the type of `__init__` arguments.  This seems to be a problem with the pydantic mypy plugin, not pydantic itself, as when run a `ValidationError` is raised at initialization.  It would helpful to catch these errors before runtime with a static type checker, as models are most often instantiated using values in `__init__`.

Example:
```py
from typing import Literal
from pydantic import BaseModel


class Fruit(BaseModel):
    kind: Literal["apple", "orange"]
    count: int


f = Fruit(kind="banana", count="a bunch") # When run ValidationError is raised, but no errors when type checking
f.kind = "pear" # mypy correctly detects that this is an error
f.count = "a bushel" # mypy also detects that this is an error
```

**Comment by samuelcolvin** [comment]
This is not a bug but a limitation of the plugin, hopefully one day we can make the plugin more powerful, but it's a big piece of work.

But fundamentally, if you know the types of things before runtime, you may as well user dataclasses.

**Comment by alenzo-pinc** [comment]
> **For future reference:**
> 
> I use this workaround for constructor auto-completion and mypy typechecking:
> 
> ```python
> from typing import Literal, TYPE_CHECKING
> from pydantic import BaseModel
> 
> if TYPE_CHECKING:
>     from dataclasses import dataclass
> else:
>     def dataclass(cls):
>         return cls
> 
> @dataclass
> class Fruit(BaseModel):
>     kind: Literal["apple", "orange"]
>     count: int
> 
> 
> f = Fruit(kind="banana", count="a bunch") # now the typechecker detects the errors
> ```

Have you noticed any issues with this approach? @Fabbi

**Comment by Fabbi** [comment]
> Have you noticed any issues with this approach? @Fabbi 

I haven't noticed anything. But I've only used pydantic in one project yet. 

The runtime part should be safe though as `dataclass` is only the identity function in that case

**Comment by beedub** [comment]
> But fundamentally, if you know the types of things before runtime, you may as well user dataclasses.

@samuelcolvin do you mind expanding on this statement?

**Comment by StuartBertram** [comment]
Late to the party, but we've just hit this and I _have_ found a problem with the workaround: Pylint.

We had a field of type `str` on an object that was being created within a function that took a parameter of type `str | None`. The type checker doesn't notice that, but it fails validation at runtime. If we apply the dataclass workaround then Pylint says that it isn't expecting keyword args in the constructor call. But MyPy and Ruff are happy.

The hard part is presumably that you can pass strings to fields of type `UUID` or `int` and Pydantic will parse them (even without using `model_validate(...)`) and you can have validator functions that coerce `None` to some other value, so it's not always purely a type-checking thing.
