### ISSUE TITLE
Optional environment variables with default values in nested Settings models leads to a validation error

### ISSUE THREAD

**Issue by tivaliy** [samuelcolvin/pydantic#4089]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /Users/user/.virtualenvs/sandbox/lib/python3.9/site-packages/pydantic
               python version: 3.9.12 (main, Mar 26 2022, 15:44:31)  [Clang 13.1.6 (clang-1316.0.21.2)]
                     platform: macOS-12.3.1-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```
I faced with a small issue when using optional environment variables ONLY in nested `BaseSettings` models.

```py
from typing import Optional
from pydantic import BaseModel, BaseSettings

class SubModel(BaseModel):
    v1: Optional[str] = 'foo'

class Settings(BaseSettings):
    v0: str
    sub_model: SubModel

    class Config:
        env_nested_delimiter = '__'

Settings(_env_file='.env').dict()

ValidationError: 1 validation error for Settings
sub_model
  field required (type=value_error.missing)
```

and here is the content of `.env` file:

```sh
$. cat .env

V0=bar
```

Expectation (I can be wrong) that even if my nested Settings class contains ONLY variables with default values they should be populated.
Here is an example if at least one parameter is mandatory in nested Settings class:

```py
In [37]: from typing import Optional
    ...: from pydantic import BaseModel, BaseSettings
    ...:
    ...:
    ...: class SubModel(BaseModel):
    ...:     v1: Optional[str] = 'foo'
    ...:     v2: str
    ...:
    ...:
    ...: class Settings(BaseSettings):
    ...:     v0: str
    ...:     sub_model: SubModel
    ...:
    ...:     class Config:
    ...:         env_nested_delimiter = '__'
    ...:

In [38]: cat .env
V0=foo
SUB_MODEL__V2=bar

In [39]: Settings(_env_file='.env').dict()
Out[39]: {'v0': 'foo', 'sub_model': {'v1': 'foo', 'v2': 'bar'}}
```

**Comment by samuelcolvin** [comment]
I don't really understand what the problem is here. The `sub_model` field is required because it has no default, the fact that all the fields in the type of `sub_model` are optional, doesn't automatically make that field optional.

You should set `sub_model: SubModel = SubModel()` to stop it being required.

My I misunderstanding you?
