### ISSUE TITLE
exclusiveMinimum/Maximum should be boolean

### ISSUE THREAD

**Issue by OrIOg** [samuelcolvin/pydantic#4108]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

As the [documentation](https://swagger.io/docs/specification/data-models/data-types/#range) say `exclusiveMinimum` and `exclusiveMaximum` should be boolean.
Assigning by example `gt`(greater than) to 4 should affect the `minimum` to 4 and set `exclusiveMinimum` to `true` instead of setting `exclusiveMinimum` to 4.
Same for  `lt`(lesser than) and `exclusiveMaximum`

```python
from enum import Enum
from pydantic import BaseModel, Field

class MainModel(BaseModel):
    """
    This is the description of the main model
    """
    snap: int = Field(
        42,
        title='The Snap',
        description='this is the value of snap',
        gt=30,
        lt=50,
    )

# this is equivalent to json.dumps(MainModel.schema(), indent=2):
print(MainModel.schema_json(indent=2))
```

Current result:
```json
{
  "title": "MainModel",
  "description": "This is the description of the main model",
  "type": "object",
  "properties": {
    "snap": {
      "title": "The Snap",
      "description": "this is the value of snap",
      "default": 42,
      "exclusiveMinimum": 30,
      "exclusiveMaximum": 50,
      "type": "integer"
    }
  }
}
```
But should output:
```json
{
  "title": "MainModel",
  "description": "This is the description of the main model",
  "type": "object",
  "properties": {
    "snap": {
      "title": "The Snap",
      "description": "this is the value of snap",
      "default": 42,
      "minimum": 30,
      "exclusiveMinimum": true,
      "maximum": 50,
      "exclusiveMaximum": true,
      "type": "integer"
    }
  }
}
```

**Comment by savage-alex** [comment]
@OrIOg I think you are correct to have opened this. OpenAPI 3.0.x does indeed want exclusiveMinimum or Maximum as a boolean as its based on a draft 
Extract from JsonSchema docs
![image](https://user-images.githubusercontent.com/25430683/210381800-f04a4520-0204-49fc-9a9e-7ab8f39246ed.png)

Extract from OpenAPI docs that you linked above.
![image](https://user-images.githubusercontent.com/25430683/210381631-90cb3406-2dee-4460-8f30-d73718c258aa.png)

From OpenAPI 3.1 onwards it has fill Json Schema support which is number based which you originally said. Any thoughts?

**Comment by OrIOg** [comment]
@savage-alex, yes Indeed. 
I didn't know at the time and completely forgot the mention it here.

@RobinTail discovered the same problem after a change I made in [openapi3-ts](https://github.com/metadevpro/openapi3-ts/issues/83).

We might need some way to let the users decides which schema(openapi) version they need.

**Comment by savage-alex** [comment]
No worries at all. Sorry to comment on such an old thread. I came across someone's OpenAPI which had exclusiveMinimum as a number and they linked this thread as the reasons why. 

Spectral (https://github.com/stoplightio/spectral) complained about it so I did a little digging. The thread linked above sounds very similar to our investigation of - wow there are 2 ways to do this depending on the schema version!

**Comment by samuelcolvin** [comment]
See https://github.com/pydantic/pydantic/issues/4666, in V2 we'll be targeting JSON Schema [2020-12](https://json-schema.org/draft/2020-12/release-notes.html) which is compliant with OpenAPI 3.1.

`exclusiveMinimum` and `exclusiveMaximum` should definitely be numbers, not bools.

**Comment by savage-alex** [comment]
Thank you @samuelcolvin
