### ISSUE TITLE
When the field value is None by default, the validator is ignored

### ISSUE THREAD

**Issue by bina20** [samuelcolvin/pydantic#4132]
I have defined a class as:

```
class MyModel(BaseModel):
   a: float | None
   b: float | None
   c: float | None

```
For my calculations, I need either` a` and `b` (both of them must be defined) or `c` (c alone is enough). So I defined a validator as below:
   
```
    @validator('c')
    def check_params(cls, v, values, **kwargs):
        if v is None:
            if values["a"] is None or values["b"] is None:
                raise ValueError("either c or a and b must be known")
```

but when I try MyModel() the validator doesn't raise an error. However, if I set `c` to None, e.g. MyModel(c=None) the validator will work just fine.

**Comment by samuelcolvin** [comment]
This is not a bug, you need `validate_always`.
