### ISSUE TITLE
Nested Settings Model Required Field Not Working

### ISSUE THREAD

**Issue by jordantshaw** [samuelcolvin/pydantic#4147]
### Checks

* [ x] I added a descriptive title to this issue
* [x ] I have searched (google, github) for similar issues and couldn't find anything
* [x ] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
 pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /Users/jshaw/miniconda3/envs/data-api/lib/python3.9/site-packages/pydantic
               python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:52)  [Clang 13.0.1 ]
                     platform: macOS-12.4-x86_64-i386-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

```py

class SubModel(BaseModel):
    v1: str = Field(...)


class Settings(BaseSettings):
    v0: str = Field(...)
    sub_model: SubModel = SubModel()

    class Config:
        env_nested_delimiter = '__'
```

I am having an issue when trying to set a required field in a SubModel using environment variables.  I want SubModel.v1 field to be required, but set from either an environment variable or .env file.  However, when I attempt this, I just get a validation error.

`pydantic.error_wrappers.ValidationError: 1 validation error for SubModel
v1
  str type expected (type=type_error.str)`

The behavior seems just fine when its a required field on the main Settings class.  Any ideas?

**Comment by aminalaee** [comment]
I think this works ok:

```python

class SubModel(BaseModel):
    v1: str = Field(...)


class Settings(BaseSettings):
    v0: str = Field(...)
    sub_model: SubModel
    class Config:
        env_nested_delimiter = '__'
```

The `SubModel` is instantiated too early in the code.

**Comment by jordantshaw** [comment]
> I think this works ok:
> 
> ```python
> class SubModel(BaseModel):
>     v1: str = Field(...)
> 
> 
> class Settings(BaseSettings):
>     v0: str = Field(...)
>     sub_model: SubModel
>     class Config:
>         env_nested_delimiter = '__'
> ```
> 
> The `SubModel` is instantiated too early in the code.

Ahhh I see.  Thank you for the help!
