### ISSUE TITLE
`json` Method on BaseModel is including `__initialised__`

### ISSUE THREAD

**Issue by mahyarmirrashed** [samuelcolvin/pydantic#4149]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/user/.conda/envs/distributed/lib/python3.6/site-packages/pydantic
               python version: 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)  [GCC 7.3.0]
                     platform: Linux-5.17.11-200.fc35.x86_64-x86_64-with-fedora-35-Thirty_Five
     optional deps. installed: ['typing-extensions']
```

```py
from pydantic.dataclasses import dataclass

@dataclass(frozen=True)
class BaseRPCRequest(BaseModel):
  pass

print(BaseRPCRequest().json())
```

For some reason, this prints `'{"__initialised__": true}'` rather than the empty dictionary I expected.

**Comment by mahyarmirrashed** [comment]
I know that there is the JSON dumping feature for dataclasses: https://pydantic-docs.helpmanual.io/usage/dataclasses/#json-dumping. However, there doesn't seem to be anything in that document pointing to how you can deserialize the dataclass.

**Comment by samuelcolvin** [comment]
If you want deserialisation, use BaseModel inheritance, if you want a dataclass, user methods from dataclasses.

But this is a question for discussions, not a bug.
