### ISSUE TITLE
Turn off autocorrect

### ISSUE THREAD

**Issue by ciforusalterra** [samuelcolvin/pydantic#416]
# Question

For bugs/questions:
* OS: Windows
* Python version `import sys; print(sys.version)`: python 3.7.2
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.20.1

I want to turn autocorrect type from pydantic. For example I want to get an error when I pass integer to string variable instead of fix it. How to achieve that behaviour? Thanks.

**Comment by samuelcolvin** [comment]
duplicate #284, #360.
