### ISSUE TITLE
Model copy(update=) not validating

### ISSUE THREAD

**Issue by dgasmith** [samuelcolvin/pydantic#418]
# Question

Currently calling `copy` with `update=` does not validate the updated data and we can end up with odd cases like this:

```py
import pydantic

class ChildModel(BaseModel):
    v: int

class Model(BaseModel):
    c: ChildModel

>>> m = Model(c={"v": 5})
>>> print(m.c)
ChildModel v=5

>>> m2 = m.copy(update={"c": {"v": 3}})
>>> print(m2.c)
{'v': 3}
```

One can also imagine a case where the updated data is completely incorrect as well. A current workaround would be to do the following:
```py
>>> m3 = m.copy(update={"c": m.c.copy(update={"v": 3})})
>> print(m3.c)
ChildModel v=3
```

This seems a bit awkward. A possible fix would be to call `__init__` rather than `construct` in the copy constructor if `update is not None`. We use this feature quite a bit to alter immutable models.

**Comment by samuelcolvin** [comment]
this was by design, copy was supposed to be quick and thereby avoid all the validation logic.

I would say, we'd be better to have another method `copy_validate` (better name required) which copies and updates the model while validating the update data.

At the risk of getting into another discussion the ones recently raging in python-ideas, we could alternatively use the `+` operator for this, so something like

```py
m3 = m + {"c": {"v": 3}}
print(m3.c)
ChildModel v=3
```

But maybe that's completely mad?

**Comment by dgasmith** [comment]
Maybe a bit too much overloading without the new `dict + dict` PEP going through in 3.9 or whatever it ends up being?

I would argue a bit that `update` would be expected to be slightly slower than straight `copy`. The name does need to be a shorter and have a more clear syntax than `Model(**{**other.dict(), **update})` or it isn't worth it.

**Comment by samuelcolvin** [comment]
how about `update` complies with `validate_assignment`, eg. it's validated only if `validate_assignment = True`?

**Comment by dgasmith** [comment]
That would certainly cover a case I would consider a bug otherwise, but it wouldn't quite work for our use case. Happy to make a PR to patch `validate_assignment` however.

**Comment by samuelcolvin** [comment]
ok, what about adding a `validate=None` argument, means:

* `None` - use `validate_assignment` to decide whether to validate `update`
* `True` - always validate `update`
* `False` - never validate `update`

?

**Comment by dgasmith** [comment]
Thinking on it a bit `validate_assignment` should work for us, it just involves setting another flag that we do not usually set and remembering to do so. Do you still want a `validate=None` flag?

**Comment by samuelcolvin** [comment]
I think best to implement this in our own logic.

**Comment by phinate** [comment]
> I think best to implement this in our own logic.

did a PR ever get submitted along these lines? definitley a feature I would like, especially for the case of immutable models where you're constantly making new copies, this would simplify a lot of validation boilerplate

is there a workaround for in the meantime if not? :)

**Comment by PrettyWood** [comment]
@phinate How about
```py
from typing import TypeVar

from pydantic import BaseModel as PydanticBaseModel
from pydantic.utils import deep_update

Model = TypeVar('Model', bound='BaseModel')

class BaseModel(PydanticBaseModel):
    def update(self: 'Model', update_dict: dict[str, object]) -> 'Model':
        new_dict = deep_update(self.dict(), update_dict)
        return self.__class__(**new_dict)

class ChildModel(BaseModel):
    v: int

class Model(BaseModel):
    c: ChildModel

m = Model(c={"v": 5})
assert repr(m) == 'Model(c=ChildModel(v=5))'

m2 = m.update({"c": {"v": '3'}})
assert repr(m2) == 'Model(c=ChildModel(v=3))'
```
Probably buggy in some edge cases as I didn't try it out with complex examples.
Hope it helps still!

**Comment by JacobHayes** [comment]
For folks wanting a drop in for the `copy` method so all uses validate (unless explicitly requested not to), I started using:
```python
    def copy(self: _Model, *, validate: bool = True, **kwargs: Any) -> _Model:
        copy = super().copy(**kwargs)
        if validate:
            return self.validate(
                dict(copy._iter(to_dict=False, by_alias=False, exclude_unset=True))
            )
        return copy
```
It's probably (much) less performant than stock, if that matters for your use cases.

**Comment by indigoSam** [comment]
> I think best to implement this in our own logic.

@samuelcolvin  👋😸  Was this ever implemented? Or should we still use community solutions? Thank you!

**Comment by indigoSam** [comment]
> I think best to implement this in our own logic.

@samuelcolvin  👋😸  Was this ever implemented? Or should we still use community solutions? Thank you!

**Comment by Pandede** [comment]
Why this issue is closed? This issue makes partial updating the model impossible.

**Comment by sasilver75** [comment]
A year later we cry for edification

**Comment by constatza** [comment]
This is such a useful feature, why does it not receive any attention? Maybe open feature request?

**Comment by Red-Eyed** [comment]
Workaround, if you don't need to keep original reference:
```python
from pydantic import BaseModel

class ChildModel(BaseModel):
    v: int = 2

class Model(BaseModel):
    c: ChildModel = ChildModel()

m = Model()
print(m)

m2 = m.model_copy(update={"c": {"v": 3}})
print(m2)


# workaround
m3 = m.model_validate(m.model_dump() | {"c": {"v": 3}})
print(m3)
```

```python
# output
c=ChildModel(v=2)
c={'v': 3}
c=ChildModel(v=3)
```
