### ISSUE TITLE
smart_deepcopy causing sqlalchemy boolean value error on import

### ISSUE THREAD

**Issue by coneybeare** [samuelcolvin/pydantic#4183]
pydantic version : 1.9.1
sqlalchemy version: 1.4.37

app/models/base_model.py:15: in <module>
    class CommonBase(VersionedBaseModel, Timestamp):
/usr/local/lib/python3.10/site-packages/pydantic/main.py:299: in __new__
    fields[ann_name] = ModelField.infer(
/usr/local/lib/python3.10/site-packages/pydantic/fields.py:411: in infer
    return cls(
/usr/local/lib/python3.10/site-packages/pydantic/fields.py:342: in __init__
    self.prepare()
/usr/local/lib/python3.10/site-packages/pydantic/fields.py:445: in prepare
    self._set_default_and_type()
/usr/local/lib/python3.10/site-packages/pydantic/fields.py:473: in _set_default_and_type
    default_value = self.get_default()
/usr/local/lib/python3.10/site-packages/pydantic/fields.py:345: in get_default
    return smart_deepcopy(self.default) if self.default_factory is None else self.default_factory()
/usr/local/lib/python3.10/site-packages/pydantic/utils.py:627: in smart_deepcopy
    elif not obj and obj_type in BUILTIN_COLLECTIONS:
/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py:582: in __bool__
    raise TypeError("Boolean value of this clause is not defined")
E   TypeError: Boolean value of this clause is not defined
https://github.com/samuelcolvin/pydantic/blob/8846ec4685e749b93907081450f592060eeb99b1/pydantic/utils.py#L654

**Comment by samuelcolvin** [comment]
Please answer the questions in the issue template, please give more detail, please format your code/traceback so it's readable.

**Comment by coneybeare** [comment]
You are too quick! was editing my comment to do just that after an accidental `<enter>` press. Will resubmit

**Comment by samuelcolvin** [comment]
Sorry about that, I've reopened so you can update.

**Comment by coneybeare** [comment]
Crossed comments, added a new issue, closing this as dupe
