### ISSUE TITLE
__init__.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))

### ISSUE THREAD

**Issue by Liuxw17** [samuelcolvin/pydantic#4205]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
ImportError: dlopen(/Users/xxx/.local/share/virtualenvs/backend-8q-GUuhq/lib/python3.8/site-packages/pydantic/__init__.cpython-38-darwin.so, 0x0002): tried: '/Users/xxx.local/share/virtualenvs/backend-8q-GUuhq/lib/python3.8/site-packages/pydantic/__init__.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))

```

macOS 12.4

```py
from pydantic import BaseModel
class BaseModel(Representation, metaclass=ModelMetaclass):
...
...
```

**Comment by samuelcolvin** [comment]
you have the wrong binary installed, this is not a but with pydantic.

**Comment by samuelcolvin** [comment]
if you install pydantic with just `pip install pydantic` and you have a recent version of pip, the correct wheel should be installed.

**Comment by lekirill** [comment]
have same problem when installing Pydantic with Poetry

python 3.10
poetry 1.2.0

> ImportError: dlopen(/Users/xxx/Library/Caches/pypoetry/virtualenvs/env/lib/python3.10/site-packages/pydantic/__init__.cpython-310-darwin.so, 0x0002): tried: '/Users/xxx/Library/Caches/pypoetry/virtualenvs/env/lib/python3.10/site-packages/pydantic/__init__.


is there correct wheel in Poetry?

**Comment by samuelcolvin** [comment]
Poetry shouldn't require a specific wheel.

There's definitely a wheel for python3.10 on MacOS.

If pydantic is installing and working properly with pip, the problem is with poetry.

**Comment by lekirill** [comment]
thank you

i think the issue with poetry

in my case helped:
- fully remove pydantic from env
- reinstall with pip: `arch -arm64 pip install "pydantic[email,dotenv]" --no-cache`

**Comment by leeyisoft** [comment]
ARCHFLAGS="-arch arm64" pip install pydantic  --compile --no-cache-dir
