### ISSUE TITLE
"Dump only" attributes in order to differentiate between validation of inbound data and serialization of outbound data.

### ISSUE THREAD

**Issue by croshchupkin** [samuelcolvin/pydantic#422]
Is it possible to add the support of the subj to pydantic models (to Config, perhaps)?

What I'm talking about is the case when I, for instance, have a REST API which allows to POST new users and GET user's info. With a library like Marshmallow, I could define the User schema as follows:

```
class UserSchema(Schema):
    id = fields.Integer(dump_only=True)
    name = fields.String(validate=validate.Length(min=1, max=128),
                         required=True)
    created_at = fields.DateTime(format='iso', dump_only=True)
    
    class Meta(object):
        ordered = True
        strict = True

    @decorators.post_load
    def post_load(self, data):
        data['name'] = data['name'].strip()
    return data
```

With this, it's possible to validate only the user name on POST (and have only the user name in the results returned after the validation) while also dumping id and creation date as JSON on GET.

**Comment by samuelcolvin** [comment]
My instinct is that this is best done outside pydantic.

I would implement (indeed I have) a wrapper class that includes a valididation "Model", but also lost of other data/logic about that data type.

Something like 

```py
class UserSchema:
    class PostModel(BaseModel):
        name: str
    
        @validator('name')
        ...

    get_fields = 'id', 'name', 'created_at'

    async def get_from_db(...)
        pass
```

You can see something kind of like that [here](https://github.com/samuelcolvin/aiohttp-toolbox/blob/master/atoolbox/bread/main.py).

Hope that makes sense, let me know if it doesn't suffice.

**Comment by samuelcolvin** [comment]
kind of related to #64, but I decided that was a bad idea.
