### ISSUE TITLE
Default values of arbitrary types are reconstructed on init

### ISSUE THREAD

**Issue by layday** [samuelcolvin/pydantic#424]
# Bug

For bugs/questions:
* OS: Darwin
* Python version `import sys; print(sys.version)`: 3.7.2
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.21

Where possible please include a self contained code snippet describing your 
bug, question, or where applicable feature request:

```py
import pydantic


class Test:
    pass


class Foo(pydantic.BaseModel):
    test: Test = Test()

    class Config:
        arbitrary_types_allowed = True


assert Foo().test is Foo().test
```

**Comment by samuelcolvin** [comment]
see #154.

I understand this is confusing, but I think it's the correct behaviour.

**Comment by layday** [comment]
That appears to be a different issue though? The `assert` raises in my case.
