### ISSUE TITLE
Type validation can lead to type change and truncation in a silence mode

### ISSUE THREAD

**Issue by amirhessam88** [samuelcolvin/pydantic#4246]
### Checks

* [] I added a descriptive title to this issue
* [] I have searched (google, github) for similar issues and couldn't find anything
* [ ] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

I think the `validators` should not change the `type`; in a large code base that would lead to some bugs that cannot be found easily. For example, I put some simple examples below, that all will pass. I understand your intention @samuelcolvin  for the cases that loading data into a model, however, when `pydantic` is used for some wrappers, that would be really scary that user could get away with any sort of inputs and truncation would happen at some of them and the user is not aware of it, especially in data-science models. This at some point would force the user to check some other functionalities such as `get_params()` of a model, to see what was the "FINAL" validated `inputs` that been passed to the model; or in better words, what `pydantic` decided to be the results of the passed inputs. Appreciate your thoughts or plans for the future.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.9.1
            pydantic compiled: True
```

```py
from pydantic import BaseModel, validator

class Foo(BaseModel):
    var_str : str
    var_int: int
        
    @validator("var_str")
    @classmethod
    def check_var_str(cls, value: str) -> str:
        if not isinstance(value, str):
            raise TypeError("The input var_str must be a str dtype.")
        else:
            return value
        
    @validator("var_int")
    @classmethod
    def check_var_int(cls, value: int) -> int:
        if not isinstance(value, int):
            raise TypeError("The input var_int must be a int dtype.")
        else:
            return value
        
    def print_vars(self):
        print(f"var_str : {self.var_str}; type : {type(self.var_str)}")
        print(f"var_int : {self.var_int}; type : {type(self.var_int)}")
        print("--------------------------")

        
# Examples:
vars_lst = [{"var_str" : "42", "var_int" : 3},
            {"var_str" : 42, "var_int" : 3.14},
            {"var_str" : True, "var_int" : 3.14}
           ]
for vs in vars_lst:
    foo = Foo(**vs)
    foo.print_vars()

...
```

**Comment by samuelcolvin** [comment]
This is a known problem, there are lots of issues about it, see the "strict" label.

This is addressed in the [plan for pydantic V2](https://pydantic-docs.helpmanual.io/blog/pydantic-v2/).
