### ISSUE TITLE
Raise ValidationError immediately

### ISSUE THREAD

**Issue by fellnerse** [samuelcolvin/pydantic#425]
# Question

For bugs/questions:
* OS: macOS Majove
* Python version: 3.7.2
* Pydantic version: 0.21

Is it possible to tell pydantic to raise the ValidationError immediately, instead of trying to validate the whole input? If validating an attribute fails, that will be referenced later by validating a different one, this will raise completely different exception and suppresses the first one caught by pydantic:

```py
import pydantic

class A(List(str)):
    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        if sorted(v, key=str.lower) != v:
            raise ValidationError(
                "list is not sorted:\n"
                f"{sorted(v, key=str.lower)} != {v}"
            )
        return v

class B(BaseModel):
    a: A
    b: Dict[str, str]

    @validator("b", whole=True, always=True)
     def validate_b(cls, v, values):
     a = values["a"]
     # do stuff with values from a, but get KeyError because the Exception was suppressed
     return v
...
```

**Comment by samuelcolvin** [comment]
no possible, you'll need to update `validate_b` to cope with the case that `'a'` is missing from `values`.

You don't need to do any validation in `validate_b` in that case since you know something else has already gone wrong.
