### ISSUE TITLE
get_field_config is not working as I would expect

### ISSUE THREAD

**Issue by bunyk** [samuelcolvin/pydantic#426]
# Bug

* OS:  Ubuntu 16.04.6 LTS (Xenial Xerus)
* Python version: 3.7.0 (default, Sep 25 2018, 19:06:08) [GCC 5.4.0 20160609]
* Pydantic version: 0.21

This could probably be feature request, I'm not sure, because I have not found in documentation what I want to do here.

What I want to achieve, is to have model with snake_case fields in python, and CamelCase in JSON. 

I have found code to automatically add aliases to fields here: 
https://github.com/samuelcolvin/pydantic/pull/165/files#diff-b8260ce70f59117b68c0e40067b1bbf9R565

So I wrote small example myself:

```py
from datetime import date
from pydantic import BaseModel, BaseConfig

class Person(BaseModel):
    name: str
    birthday: date

    class Config(BaseConfig):
        @classmethod
        def get_field_config(cls, name):
            field_config = super().get_field_config(name) or {}
            print('!!!!!!!', field_config)
            if 'alias' not in field_config:
                print('creating alias for', name)
                field_config['alias'] = ''.join(p.upper() for p in name.split('_'))
            return field_config

p = Person(name='Taras', birthday=date(1990, 8, 1))
print(p.json(by_alias=True))
```
I get following output: 
```
{"name": "Taras", "birthday": "1990-08-01"}
```
But I want:
```
{"Name": "Taras", "Birthday": "1990-08-01"}
```
Also, from the print statements I have added it seems that method `get_field_config` is not called at all.

**Comment by samuelcolvin** [comment]
The main problem you have is that the method has changed it name from `get_field_config` to `get_field_schema` (best to always check the current code base).

Here's a working example:

```py
import re
from datetime import date
from pydantic import BaseModel

class Person(BaseModel):
    name: str
    birthday: date

    class Config:
        allow_population_by_alias = True

        @classmethod
        def get_field_schema(cls, name):
            field_config = super().get_field_schema(name) or {}
            if 'alias' not in field_config:
                field_config['alias'] = re.sub(r'_([a-z])', lambda m: m.group(1).upper(), name.title())
            return field_config

p = Person(name='Taras', birthday=date(1990, 8, 1))
print(p.json(by_alias=True))
