### ISSUE TITLE
Default of None converts non-optional fields to optional

### ISSUE THREAD

**Issue by dp-alvarez** [samuelcolvin/pydantic#4261]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

It looks like Pydantic pydantic treats fields with an default Value of None as optional even if they are not marked as such.
I also tried setting validate_all = True and the behavior is the same.

This behavior seems strange to me, and conflicts with the [documentation here](https://pydantic-docs.helpmanual.io/usage/validators/#validate-always).
Changing `None` to a different invalid value would make the example in the documentation behave as described.

```py
import pydantic

class MyModel(pydantic.BaseModel):
    int_with_default_int: int = 123
    int_with_default_none: int = None
    class Config:
        validate_all = True

MyModel(int_with_default_none=None) # this is accepted
MyModel() # this is also accepted
MyModel(int_with_default_int=None) # this is correctly rejected
```

# Environment

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.9.1
pydantic compiled: True
install path: /home/___/.venv/lib/python3.10/site-packages/pydantic
python version: 3.10.5 (main, Jun  8 2022, 09:26:22) [GCC 11.3.0]
platform: Linux-5.18.11-xanmod1-x86_64-with-glibc2.33
optional deps. installed: ['typing-extensions']
```

**Comment by samuelcolvin** [comment]
This is the documented behaviour of pydantic v1.x.

It's not a bug, but the behaviour will change in pydantic V2.

**Comment by dp-alvarez** [comment]
Thanks for the (very) quick response!

I searched and couldn't find this mentioned in the documentation, maybe it was removed as it is planned to change?

The bit at https://pydantic-docs.helpmanual.io/usage/validators/#validate-always mentions different behavior so it should probably be changed.
