### ISSUE TITLE
Default validators are not executed when defining a custom validator for another field

### ISSUE THREAD

**Issue by ivan94fi** [samuelcolvin/pydantic#4268]
### Checks

* [✔] I added a descriptive title to this issue
* [✔] I have searched (google, github) for similar issues and couldn't find anything
* [✔] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.1
            pydantic compiled: False
                 install path: /home/***/anaconda3/envs/***/lib/python3.9/site-packages/pydantic
               python version: 3.9.6 (default, Aug 18 2021, 19:38:01)  [GCC 7.5.0]
                     platform: Linux-4.15.0-156-generic-x86_64-with-glibc2.27
     optional deps. installed: ['devtools', 'typing-extensions']
```

```py
from pydantic import BaseSettings, validator

class Config(BaseSettings):
    input_resolution: int
    output_resolution: int
    scale_factor: int = None

    @validator("scale_factor")
    def compute_scale_factor(cls, v, values):
        if v is not None:
            raise ValueError("scale_factor cannot be passed, it is computed automatically")
        out_res = values["output_resolution"]
        in_res = values["input_resolution"]

        scale_factor = out_res / in_res
        if not scale_factor.is_integer():
            raise ValueError("Scale factor must be integer.")

        return int(scale_factor)

    class Config:
        validate_assignment = True
        validate_all = True
        extra = "forbid"
        env_file_encoding = "utf-8"
        env_nested_delimiter = "__"

c = Config()
```

### Expected outcome
Validation error, input and output resolution are required.

### Actual outcome
Validation on input and output resolution is not executed, the custom validator for scale_factor is executed and fails with a `KeyError` because `values` does not contain `input_resolution` or `output_resolution`.

If the custom validator is deleted, the validation error on missing output and input resolution is thrown.

**Comment by samuelcolvin** [comment]
This is not a bug, it's a question.

This behaviour is documented, the validator is called either if validation of `input_resolution` and `output_resolution` fails.

Add.

```py
        try:
            out_res = values["output_resolution"]
            in_res = values["input_resolution"]
        except KeyError:
            # validation failed and values is not complete, skip the rest of this
            return
```

In future, please use discussions unless you are absolutely sure you're are reporting a bug.

**Comment by ivan94fi** [comment]
Thank you, sorry for the misunderstanding.

Moving this to discussions as I clearly still miss something.
