### ISSUE TITLE
Support for AWS S3 paths as Pydantic Types?

### ISSUE THREAD

**Issue by adivekar-utexas** [samuelcolvin/pydantic#4272]
### Discussed in https://github.com/samuelcolvin/pydantic/discussions/4271

<div type='discussions-op-text'>

<sup>Originally posted by **adivekar-utexas** July 23, 2022</sup>
I work at Amazon and we are planning to use Pydantic for validating data. A lot of this data is stored on [AWS S3](https://aws.amazon.com/s3/) and we want to validate S3 paths.

Concretely:
AWS S3 paths are basically Urls. I have looked within Pydantic and they do not seem to be supported.

They follow a [few rules](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html), here are the important ones:
- An S3 path must start with `s3://` (this is meant to be like the `https://` schema).
- Max length = 1023, min length = 8 (due to bucket restrictions below)
- The first string after `s3://` is the bucket name, which must be between 3 and 64 chars and consist only of lowercase letters, numbers, dots (.), and hyphens (-) ([See here for a few more restrictions](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html)). E.g.`s3://my-bucket/` and `s3://my-bucket` (without `/`) both have the bucket name `my-bucket`.
- The part after the bucket name (if it exists) is called the "key". E.g. `s3://my-bucket/some/key/path`, the `some/key/path` is the key. Notice it does not start with `/`. 
- S3 uses forward slashes `/` to create virtual "folders" (internally, the sharding is done based on key). A key is an S3 "folder" if ends with `/`, e.g. `s3://my-bucket/some/folder/path/`, otherwise it is an "object".
- Whitespaces are allowed in the middle of the key part of the path (but they are discouraged).

It would be so nice to have a Pydantic Type like `S3Path`, which when passed a string in the constructor, does the following:
1. Validates a string is a valid S3 path
2. Populates attributes: 
    - bucket: str
    - key: Optional[str]
    - is_folder: bool  # which tells you if the key is a folder (i.e. ends with `/`)

I have looked in the Pydantic docs and on Google, nothing seems to exist for this use case. I've tried to extend `AnyUrl` but it has not worked. 

Could this please be added?</div>

**Comment by samuelcolvin** [comment]
Closing this to avoid duplication, I'll reply on this discussion.

**Comment by shreyansoa** [comment]
Hey @samuelcolvin were you able to solve for this?

**Comment by samuelcolvin** [comment]
Not yet, pydantic v2 is not related yet.
