### ISSUE TITLE
Make command on docs or docs-serve is failing.

### ISSUE THREAD

**Issue by sp1rs** [samuelcolvin/pydantic#4288]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
On running `make docs` or `make docs-serve` I am getting the following error. Any help is appreciated.

```
flake8 --max-line-length=80 docs/examples/
python docs/build/main.py
error in hypothesis_property_based_test.py: Traceback (most recent call last):
  File "/Users/temporaryadmin/open-source/pydantic/docs/examples/hypothesis_property_based_test.py", line 2, in <module>
    from hypothesis import given, strategies as st
AttributeError: type object 'Path' has no attribute '_flavour'

1 errors, not writing files
```

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /Users/temporaryadmin/open-source/pydantic/pydantic
               python version: 3.10.5 (v3.10.5:f377153967, Jun  6 2022, 12:36:10) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-12.1-x86_64-i386-64bit
     optional deps. installed: ['devtools', 'dotenv', 'email-validator', 'typing-extensions']
...
```

**Comment by samuelcolvin** [comment]
https://github.com/samuelcolvin/pydantic/pull/4231#issuecomment-1188673712

Error seems to be with pipenv and hypothesis. I think you could have found this with a search of issues, please search first.
