### ISSUE TITLE
BaseModel with attribute "self" throws TypeError

### ISSUE THREAD

**Issue by je-l** [samuelcolvin/pydantic#430]
# Bug

For bugs/questions:
* OS: Fedora 29
* Python version: 3.7.2
* Pydantic version: 0.21

```py
from pydantic import BaseModel


d = {
    "self": 1,
}

class Model(BaseModel):
    self: int

Model.parse_obj(d)  # TypeError: __init__() got multiple values for argument 'self'
```

I'm not certain if this would be complex to support, but would be nice if models with `self` attributes would be possible.

**Comment by samuelcolvin** [comment]
probably possible if `parse_obj` was modified to not use `__init__`.

**Comment by samuelcolvin** [comment]
fixed in v1.
