### ISSUE TITLE
Richer timedelta / timestamp parsers?

### ISSUE THREAD

**Issue by aldanor** [samuelcolvin/pydantic#432]
I was wondering whether it would make sense to steal a parser bit from pandas, allowing for much richer timedelta and timestamp parsing? (e.g., see [here](https://github.com/pandas-dev/pandas/blob/58a4151c0a7909ea20191ce11b8eebe08b6f2af0/pandas/_libs/tslibs/timedeltas.pyx#L323) for timedeltas)

This way, you could have `'3 micros', '1h2m'` etc as valid timedeltas which is arguably much nicer.

**Comment by samuelcolvin** [comment]
fine by me, PR welcome.

**Comment by dgasmith** [comment]
+1 for this! I didn't have a chance to hack at it last time, but would be very useful.

**Comment by samuelcolvin** [comment]
On reflection I'm anti this in general, pydantic v2 will use [speedate](https://github.com/samuelcolvin/speedate) which I think covers everything required.
