### ISSUE TITLE
v1.9.1 release missing from `HISTORY.md` on `master`

### ISSUE THREAD

**Issue by edmorley** [samuelcolvin/pydantic#4325]
The latest version of Pydantic is v1.9.1, however the most recent version mentioned in the HISTORY.md file on `master` is v1.9.0:
https://github.com/samuelcolvin/pydantic/blob/9a0ae097bfdefa9bfb41e19d71a5001fe8240e36/HISTORY.md

It seems the new changelog entry for 1.9.1 was only added to the 1.9.1 tag/branch:
https://github.com/samuelcolvin/pydantic/blob/v1.9.1/HISTORY.md#v191-2022-05-19

...however that tag is not what people see when first navigating to the repo to find out recent changes :-)

**Comment by samuelcolvin** [comment]
I need to pick some of those changes into master, I am aware of this.
