### ISSUE TITLE
isinstance expectation out of sync with pydantic validation logic

### ISSUE THREAD

**Issue by Joshuaalbert** [samuelcolvin/pydantic#4340]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Pydantic treats `BaseModel`'s with the sample shape as the same thing in a `Union`, at least when it comes to object instantiation. This leads to counterintuitive things like not allowing code that depends on `isinstance` of `BaseModel` instance properties to be reliable. The example below shows this, and one can imagine how this could riple into problems in code. This goes against the schema which will correctly point out that the union exists.

Note: this also clearly affects JSON serialisation, since the serialisation makes no mention of the specific model class, so any two things with the same shape will be treated the same at deserialisation, and again one member of the type set will be arbitrarily chosen.

### Example Code

```Python
from pydantic import BaseModel

class A(BaseModel):
    a:float

class A2(BaseModel):
    a:float

class B(BaseModel):
    a: Union[A,A2]
    b: Union[A,A2]

s = B(a=A(a=1.),b=A2(a=1.))
print(s) # both a and b are treated as instances of A
assert isinstance(s.a, A)
assert isinstance(s.b, A2) # fails
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /home/albert/miniconda3/envs/tha_py/lib/python3.9/site-packages/pydantic
               python version: 3.9.12 (main, Jun  1 2022, 11:38:51)  [GCC 7.5.0]
                     platform: Linux-5.13.0-52-generic-x86_64-with-glibc2.34
     optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [X] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
You need SmartUnion

**Comment by Joshuaalbert** [comment]
I will also note that the problem of type coersion still remains as stated in the issue description, however there is a note of caution in the documentation that hints that this might be standardised in v2.

From [here](https://pydantic-docs.helpmanual.io/usage/model_config/#smart-union) we have,

> Note that this option [smart_union] does not support compound types yet (e.g. differentiate List[int] and List[str]). This option will be improved further once a strict mode is added in pydantic and will probably be the default behaviour in v2!

**Comment by samuelcolvin** [comment]
Did you see:

https://pydantic-docs.helpmanual.io/blog/pydantic-v2/#strict-mode

**Comment by Joshuaalbert** [comment]
I have now!

**Comment by Joshuaalbert** [comment]
@samuelcolvin `smart_union` wouldn't be able to do anything in the case that the structure are identical between types in the `Union`. That's a problem again when `isinstance` is a fundamental component of the programmers code. This [post](https://janhendrikewers.uk/serialization_of_pydantic_data_models_with_json_whilst_preserving_type_data.html) talks about exactly the same problem, and has to implement a customer JSON hook. Is there anyway to make this kind of boiler plate a part of pydantic?

**Comment by samuelcolvin** [comment]
Yes it would because we check the type of `A` in the first pass it the Union, see

https://github.com/pydantic/pydantic-core/blob/fdf42b8b0d0684bc2cac04d34c40fe4b0d33498d/src/validators/new_class.rs#L72

And

https://github.com/pydantic/pydantic-core/blob/fdf42b8b0d0684bc2cac04d34c40fe4b0d33498d/src/validators/union.rs#L78
