### ISSUE TITLE
ClassVar with square brackets

### ISSUE THREAD

**Issue by TojikCZ** [samuelcolvin/pydantic#435]
Is Pydantic supposed to support ClassVar only in it's bare form?

* OS: Linux
* Python version: 3.7.2
* Pydantic version: 0.21

```py
from typing import ClassVar
from pydantic import BaseModel

class TestClass(BaseModel):
    foo: ClassVar[int] = 5

print(TestClass.foo)

Traceback (most recent call last):
  File "/home/tojik/git/tanks/test/test_pydantic.py", line 7, in <module>
    class TestClass(BaseModel):
  File "/usr/lib/python3.7/site-packages/pydantic/main.py", line 190, in __new__
    config=config,
  File "/usr/lib/python3.7/site-packages/pydantic/fields.py", line 118, in infer
    schema=schema,
  File "/usr/lib/python3.7/site-packages/pydantic/fields.py", line 87, in __init__
    self.prepare()
  File "/usr/lib/python3.7/site-packages/pydantic/fields.py", line 152, in prepare
    self._populate_sub_fields()
  File "/usr/lib/python3.7/site-packages/pydantic/fields.py", line 180, in _populate_sub_fields
    if issubclass(origin, Tuple):  # type: ignore
  File "/usr/lib/python3.7/typing.py", line 713, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```
Erasing [int] makes it work

As i am new to typing in Python i was not aware it could be used without square brackets.

**Comment by samuelcolvin** [comment]
Simple as this isn't currently implemented. 

Pull request welcome, otherwise I'll work on it at some point in the future.

Thanks for reporting.

**Comment by tyrylu** [comment]
It appears that changing the condition at main.py:170 from `if ann_type == ClassVar:` to `if ann_type == ClassVar or (hasattr(ann_type, "__origin__") and ann_type.__origin__ == ClassVar):` should fix it, but i don't like accessing `__origin__`. Any ideas how to detect this better?

**Comment by samuelcolvin** [comment]
https://github.com/samuelcolvin/pydantic/blob/46b1e89a65a50ae31e3f793ac590050f3383ac51/pydantic/fields.py#L182

Any numerous other places we already have to use `__origin__` a lot. Pydantic could have had the tag ling "Using type.__origin__ to inspect annotations".

Your fix could be simplifed to

```py
if ann_type == ClassVar or getattr(ann_type, '__origin__', None) == ClassVar:
```

Would be great if you could submit a PR for this.

**Comment by tyrylu** [comment]
Alright, will do. :-)
