### ISSUE TITLE
Improve README.rst

### ISSUE THREAD

**Issue by pilosus** [samuelcolvin/pydantic#446]
I've conducted a small survey amongst my colleagues about what they would like to be improved in *pydantic* as a github project. Many of them said that an almost blank ``README.rst`` make them think the package is not really alive. I think it's a good point. As many developers use GitHub as a kind of social network, checking for projects people they follow like or star, we need a quick introduction to what *pydantic* is. I know it's already in the documentation. But saving people a few mouse clicks may make a difference.

`README.rst` should not copy or extend a great documentation we already have. Instead it should tell GitHub users (i.e. developers) the most essential things about *pydantic* in a concise manner. 
I'd suggest the following structure:

* Intro (what's pydantic)
* Installation (pip)
* A Simple Example (a first example from the docs)
* Contributing (link to contributing section in the docs)
* Links
  * Documentation
  * License
  * Releases in the CheeseShop
  * Source code (GitHub link)
  * Issue tracker (GitHub Issues)
  * Test status
  * Test coverage

**Comment by pilosus** [comment]
@samuelcolvin actually I already have a draft version. It's compiled from the pydantic docs to follow the structure from above. If you think that having a richer README would help, I can submit a PR so that it's easier to make a final version of README

**Comment by samuelcolvin** [comment]
Sounds good, but:
* Shouldn't be too long. Eg. Less than ~800px high
* Keep using rst so it can also be used for pypi.
* Make the documentation link very prominent incase people think "that's all there is" when looking at the readme.

**Comment by samuelcolvin** [comment]
Also no need for github links in the readme.

Perhaps we should include download numbers from pypi/bigquery.

Conda-forge link should be added too.
