### ISSUE TITLE
[Question] How to generate example for documentation

### ISSUE THREAD

**Issue by timonbimon** [samuelcolvin/pydantic#456]
# Question

I would like to use pydantic to define what a config.json that configures my application should look like.
What is the best way to auto-generate an example config.json using the Pydantic Model?
I would like to use this as documentation for my users, so that they don't have to look into the code to see what the config.json should look like.

**Comment by samuelcolvin** [comment]
Simplest would be to use just `SettingsModel().schema()` to create a schema for the config file. You could also look at [`Schema`](https://pydantic-docs.helpmanual.io/#schema-creation) to add help text to each field.

You could also use just `SettingsModel().json()` to create an example with default settings (assuming all fields have defaults and are not required) or `SettingsModel(foobar='example value for foobar').json()`
