### ISSUE TITLE
Support ForwardRef in Python 3.6

### ISSUE THREAD

**Issue by mooncake4132** [samuelcolvin/pydantic#463]
Currently pydantic only supports `ForwardRef` in Python 3.7. It will be great if it can also be supported in Python 3.6. Although a `ForwardRef` can't be explicitly created in Python 3.6, it can be implicitly created:
```py
class A(BaseModel):
    a: 'A' = None
```
If you take a look at the `ForwardRef` class in [Python 3.6](https://github.com/python/cpython/blob/4508bc37dd80c71adfaa0925a67c438389817076/Lib/typing.py#L216) and [Python 3.7](https://github.com/python/cpython/blob/86fbe0287dd774022fd2b6c2dcbfbb5573a0b874/Lib/typing.py#L435), they share a very similar interface. The only major difference I spotted is that in python 3.6, `ForwardRef` is named as `_ForwardRef` and the method `_evaluate` in python 3.7 is named as `_eval_type` in python 3.6.

Quickly looking through the code I believe we can change https://github.com/samuelcolvin/pydantic/blob/a704662ae4cde638c0e1b68126a2f89828787641/pydantic/utils.py#L24-L28
to
```py
try: 
     from typing import ForwardRef  # type: ignore 
 except ImportError: 
     # python 3.6 
    from typing import _ForwardRef as ForwardRef
```
and
https://github.com/samuelcolvin/pydantic/blob/a704662ae4cde638c0e1b68126a2f89828787641/pydantic/main.py#L456-L459
to
```py
 for f in cls.__fields__.values(): 
     if type(f.type_) == ForwardRef: 
         f.type_ = f.type_._eval_type(globalns, localns or None)  # type: ignore 
         f.prepare() 
```

**Comment by samuelcolvin** [comment]
Humm, I'm not completely opposed to it, but why not just upgrade to 3.7?

3.7 has been released and stable for some time now, the chance of a bugs from upgrading is tiny, the only reason I can imagine is that you can't upgrade, eg. your tied to an OS with 3.6.

**Comment by mooncake4132** [comment]
Unfortunately we are not able to upgrade to 3.7 due to some of our dependencies (i.e. tensorflow and some projects that used the name `async`)

**Comment by samuelcolvin** [comment]
humm, shame.

Ok, PR welcome to all `ForwardRef` with 3.6.

**Comment by mooncake4132** [comment]
Thanks. I'll prepare a PR once https://github.com/samuelcolvin/pydantic/pull/464 lands.

**Comment by gangefors** [comment]
@mooncake4132 Do you have a PR for this in the works? I'm also in a place where we want to support both py36 and py37 using ForwardRef.

**Comment by mooncake4132** [comment]
@gangefors I'm currently in a situation where I don't easily have internet connection everyday. Feel free to grab it if you need it now.

**Comment by xNinjaKittyx** [comment]
I also would love this feature. Even though the technical reasons to upgrade to 3.7 may be few, there's plenty of corporate reasons why you wouldn't be able to do so.

**Comment by samuelcolvin** [comment]
PR welcome.

**Comment by samuelcolvin** [comment]
Done.
