### ISSUE TITLE
Question: Does Pydantic support conditional aliasing

### ISSUE THREAD

**Issue by JakeSummers** [samuelcolvin/pydantic#466]
Suppose that I have a class like this: 

	class Property(BaseModel): 
		address: str
		is_house: bool

When `is_house` is true, I would like to serialize this to:

	{
		"houseAddress": "123 street street"
	}

When `is_house` is set to false, I would like to serialize this to: 

	{
		"apartmentAddress": "123 street street"
	}

Does Pydantic support conditional aliasing?

**Comment by samuelcolvin** [comment]
Much the simplest (both to write and understand) approach would be something like:

```py
p = Property(address='xxx', is_house=whatever)
key = 'houseAddress' if p.is_house else 'apartmentAddress'
data = {key: p.address}
```

In short the answer is no, but that's probably right - doing so would be unnecessarily complicated.

**Comment by JakeSummers** [comment]
Thanks @samuelcolvin !
