### ISSUE TITLE
Transformation or mappings of fields

### ISSUE THREAD

**Issue by Atheuz** [samuelcolvin/pydantic#468]
# Question
Is it possible to define a field in your model, that takes a given input and transforms/maps it into the type you actually want.

So for instance, say I have the string: "1,2,3,4,5" and I want to turn that into [1,2,3,4,5]. Is that possible, if so can someone tell me how as I would like to make this a lot more obvious in the documentation.

```py
import pydantic
from typing import List

class Settings(pydantic.BaseModel):
    items: List = pydantic.Schema(fn=lambda x: x.split(","))

items = "1,2,3,4,5"
conf = Settings(items=items)
print(conf.items)
# > [1,2,3,4,5]
```

**Comment by samuelcolvin** [comment]
Yes, this is what [`validators`](https://pydantic-docs.helpmanual.io/#pre-and-whole-validators) are for, you'll need `pre=True, whole=True` in this case.
