### ISSUE TITLE
"Dump only" and "load only" fields

### ISSUE THREAD

**Issue by Paul-Ilyin** [samuelcolvin/pydantic#477]
# Feature request

I guess, it would be useful to have an option to create "dump only" and "load only" fields in BaseModels. 

"load_only" fields can be often used in web APIs in cases where we have some information we don't want to expose in our api
Examples of usage: 
- users' passwords
- fields with models for internal usage: e.g. we have models which are irrelevant for clients, but these models do some work in api handlers 

"dump only" fields can be useful in situations when we don't want clients to modify some things like ids of some entities or hashed passwords. 

In my opinion, it should look like this:
```py
from pydantic import BaseModel

class MyModel(BaseModel):
    a: int
    b: str
    c: bool
    class Config:
        load_only = {"a"}
        dump_only = {"b"}
```

I wanted to add this feature in #471 and @samuelcolvin thinks that it is rarely needed, but if lots of people vote it up, he would accept this PR, so let me know if it is useful.

Also, in my opinion, it is more convenient than nested excludes because if we want to reuse some of our models, we would always have to keep exclude dict somewhere, but I think that the information about excludes is relevant to the model itself.
Also, the information about load_only and dump_only fields can be obtained in some external tools like API documentation and other things

**Comment by samuelcolvin** [comment]
Thanks for asking the question.

This could also be accomplished via `Schema(..., readonly=True)` or whatever.

**Comment by haizaar** [comment]
(Probably related - not sure my usecase deserves a dedicated question issue)

I need to keep `version` field together with model instance to pass it back to for optimistic concurrency checking when issuing update request to upstream API. However I don't want this field to participate in object comparisons.
Also *version* is quite a common attribute name (think software packages), so I would like not to hijack 
it for internal needs. I tried to define it as `_version`, but pydantic discards attributes starting with underscore it seems.

Here are some details:

I have API that models documents returned from ElasticSearch. ES response schema in the nutshell is as follows:
```json
GET /users/1
{
  "_id": 1,
  "_version": 1,
  "_source": {
    "name": "foo"
  }
}
```
So I model user class in Pydantic as:
```python
class User(BaseModel):
    id: Optional[int]
    name: str

    @classmethod
    def from_es_obj(cls, obj: dict):
        return cls(id=obj["_id"], **obj["_source"])
```

But how to define `version` field such that given `api.users.get()` that returns `User`s by id, `User(id=1, name="foo") == api.users.get(1)` will hold true. I can use my own BaseModel and override `__eq__` method - is this a recommended approach? It would still does not solve the issue that actual object can't have its own `version` field (like in *software version*) Is there any *meta* space that I can use to hold utility information like that?

**Comment by samuelcolvin** [comment]
If you want custom `equals` behaviour, overriding `__eq__` would be the best approach, although for you future sanity you might be better off adding your own `equivalent()` (or whatever) method for this particular purpose.

Apart from special comparison behaviour I'm not clear why `version` is a special field. Maybe ask another question and reference this if it turns out to be the same thing.

**Comment by Midnighter** [comment]
Adding to the OP: Maybe I'm conflating several issues here but I think it'd be pretty useful to be able to exclude fields from the generated schema by default. Especially if it was in combination with database models as I asked for in #491.

My use-case would be in combination with FastAPI where returned pydantic models are used to automatically generate documentation for API endpoints. So what I have in mind is to exclude certain fields both from being serialized and returned, as well as from being documented in the automatically generated schema. (Also a question for @tiangolo probably.)

A current work-around is to define two models where one's fields are a subset of the other's.

**Comment by tiangolo** [comment]
@haizaar about the `_id` and `_version`, I think you can just use `alias`:

```Python
class User(BaseModel):
    id: Optional[int] = Schema(None, alias="_id")
    version: str = Schema(None, alias="_version")
    name: str
```

**Comment by tiangolo** [comment]
About what @Midnighter says, I think it could be something like adding the same `include` and `exclude` taken by `.dict()` and `.json()` to the `Config` subclass.

And then having `.dict()`, `.json()` and `schema()` check that in the `Config`.

Would something like that be acceptable @samuelcolvin ?

**Comment by samuelcolvin** [comment]
> And then having `.dict()`, `.json()` and `schema()` check that in the `Config`.

Sounds good to me, provided those method still take `include` and `exclude` as arguments and uses those if they're provided.

**Comment by samuelcolvin** [comment]
But that doesn't cover the "dump only" case.

The relates to const as implemented in #469 and the suggestion of `Final` as discussed in #502.

I guess there's a difference between a field which appears in the schema and can be passed through for parsing, and a field which is ignored in schema and on parsing, but only appears when you dump the model.

Personally I think `const` and possibly `Final` in future are sufficient.

**Comment by tiangolo** [comment]
Yep, I think I'm deviating from the original issue.

**Comment by samuelcolvin** [comment]
I think this is all covered by other issues, specifically #624.
