### ISSUE TITLE
confusing sentence in docs#validators

### ISSUE THREAD

**Issue by bukowa** [samuelcolvin/pydantic#479]
# Question
https://pydantic-docs.helpmanual.io/#validators

````txt
If validation fails on another field (or that field is missing) it will not be included in values, hence if 'password1' in values and ... in this example.
````
This sentence is confusing to me, what does it mean "that field is missing":

**Comment by samuelcolvin** [comment]
`values` is a dictionary, `password1` is not in it.

Not sure how to make it clearer, but if you do I'd be happy to accept a PR to improve it.
