### ISSUE TITLE
typesafe constructors

### ISSUE THREAD

**Issue by graingert** [samuelcolvin/pydantic#48]
In code where I know the types are valid it would be better if `SomeModel(v=3)` were type checked

For data where I'm not sure of the type, I'd like to use a factory function: `SomeMode.parse(**kwargs)`

**Comment by samuelcolvin** [comment]
We do need a way to initialise models without running validation. This will be required for pickle (#40) and `copy()`/`copy_replace()` immutable methods.

The approach I was going to use was a special kwarg `Model(trusted_=TrustedData(**kwargs))` since json extra couldn't include `TrustedData` instances it would be impossible to spoof data validation.

`parse()` would be clearer but would break 99% of usage which is just `Model(**untrusted_data)`.

I'll give some more thought about which to use.

**Comment by graingert** [comment]
```python
Model(trusted_=TrustedData(**kwargs))
```

would not work because mypy won't know what types TrustedData should take.

**Comment by graingert** [comment]
> `parse()` would be clearer but would break 99% of usage which is just `Model(**untrusted_data)`.

pydantic is in 'Development Status :: 4 - Beta', so that's probably OK

**Comment by samuelcolvin** [comment]
no one cares about pypi classifiers, but I do tend to folow semvar and at v0.2/3 we definitely make changes to the API.

However my concern isn't with existing users, it's that the library should be as easy and simple to user as possible. `Model.parse(**data)` is less pythonic and natural than `Model(**data)`

**Comment by graingert** [comment]
@samuelcolvin `Model(**data)` being unsafe is not pythonic.

**Comment by graingert** [comment]
```Model.construct(**kwargs)``` being typesafe would work for me, but I don't think mypy supports it.

**Comment by samuelcolvin** [comment]
With your approach `Model(**data)` would be more unsafe as it wouldn't validate the data.

However, there's also the question of #39. If we have `parse_json()` it would make sense to have `parse()` too.

**Comment by graingert** [comment]
> With your approach Model(**data) would be more unsafe as it wouldn't validate the data.

It would be more safe because mypy validates the data.

**Comment by samuelcolvin** [comment]
I'm not that bothered about mypy, I think it's still pretty immature and I've had significantly problems with it myself. It's a nice to have, not a requirement.

**Comment by graingert** [comment]
@samuelcolvin how about `Model(**data)` supports mypy typechecks and parsing whereas `Model.parse(**data)` just parses.

eg
```python
class Model(BaseModel):
    foo: str
    bar: int

m = Model(foo='three', bar='3') # m is constructed correctly at runtime but fails to typecheck under mypy
n = Model.parse(foo='three', bar='3') # n is constructed correctly at runtime and passes typecheck.
```

**Comment by graingert** [comment]
this way people running mypy are happy, and so are those who are not.

**Comment by samuelcolvin** [comment]
I'm not sure what you mean by "supports mypy typechecks"? 

mypy is a static type checker. It reads code and tries to spot type inconsistencies, that's all.

**Comment by graingert** [comment]
@samuelcolvin eg when you use namedtuple:


```python
from typing import NamedTuple


class Model(NamedTuple):
    foo: str
    bar: int


m = Model(foo='three', bar='3')
```

you get:

src/datascience/foo.py:9:4: error: Argument 2 to "Model" has incompatible type "str"; expected "int"

**Comment by graingert** [comment]
closing in favour of #50

**Comment by samuelcolvin** [comment]
Reopening this.

I'm going to add `construct` as a classmethod to `BaseModel` and use it to create models using trusted values, then use that for:
* copying models
* pickling/unpickling models
