### ISSUE TITLE
Inconsistency between @dataclass and BaseModel

### ISSUE THREAD

**Issue by madisvain** [samuelcolvin/pydantic#484]
# Bug

For bugs/questions:
* OS: OSX
* Python version: 3.7.2
* Pydantic version: 0.23

There seems to be an inconsistency between using dataclasses or BaseModel whereas a dataclass raises a TypeError but BaseModel raises a pydantic ValidationError that you are expecting.

```py
from pydantic.dataclasses import dataclass

@dataclass
class User:
    id: int

user = User()
TypeError: __init__() missing 1 required positional argument: 'id'
```

Same with BaseModel

```py
from pydantic import BaseModel

class User(BaseModel):
    id: int

user = User()
pydantic.error_wrappers.ValidationError: 1 validation error
id
  field required (type=value_error.missing)
```

**Comment by samuelcolvin** [comment]
I'm afraid that's just a fundamental difference between them.

Unless someone else has am idea I don't, I don't think this is fixable.

**Comment by madisvain** [comment]
@samuelcolvin thank you for the response and the library

**Comment by samuelcolvin** [comment]
No problem, thanks for using it.
