### ISSUE TITLE
Checking of Config class

### ISSUE THREAD

**Issue by kshpytsya** [samuelcolvin/pydantic#497]
* OS: Linux
* Python version: 3.7.3
* Pydantic version: 0.24

It it would be useful to check the `Config` class to contain only supported options, to avoid the situation illustrated below:

```py
from pydantic import BaseModel


class C(BaseModel):
    class Config:
        # note the intentional extra "s" in the option name
        validate_assignments = True

    f1: int = 0


o = C()
# hey, why doesn't this fail?.. Oh, a typo...
o.f1 = []
```

**Comment by samuelcolvin** [comment]
Disagree, can be useful to add other things to config for custom models.
