### ISSUE TITLE
parse config from non-BaseModel class

### ISSUE THREAD

**Issue by graingert** [samuelcolvin/pydantic#50]
read the annotations recursively from a class and generate a validator at runtime:

```python
# pydantic
from typing import Callable, Any, TypeVar

_T = TypeVar('_T')


def parse(cls: Callable[..., _T], config: Optional[BaseConfig] = None, **kwargs: Any) -> _T:
    """
    Process annotations on cls, run verification on kwargs and return a new
    instance of cls or raise a validation error.
    """
    ...
```

```python
# model.py
import pydantic
import typing

class OtherModel(typing.NamedTuple):
    foo: int
    bar: int

class Model(typing.NamedTuple):
    foo: str
    bar: int
    baz: OtherModel


m = pydantic.parse(Model, foo='three', bar='3', baz={'foo': '1', 'bar': '2'})
print(m)

**Comment by graingert** [comment]
validators could be cached in a WeakMap of type to validator.

**Comment by samuelcolvin** [comment]
This should be bossible, `_process_values` will need moving off `BaseModel` the field inference out of `MetaModel.__new__`. Your `parse` method will also need to take `config` as an argument.

**Comment by graingert** [comment]
cals also read the annotations recursively from a function and generate a validator at runtime:

```python
# model.py
import pydantic
import typing

class OtherModel(typing.NamedTuple):
    foo: int
    bar: int

def create_stuff(*, foo: str, bar: int, baz: OtherModel) -> Foo:
    pass
```

m = pydantic.parse(create_stuff, foo='three', bar='3', baz={'foo': '1', 'bar': '2'})
print(m)

**Comment by samuelcolvin** [comment]
not really of interest to me. Happy to review a PR if one is submitted.
