### ISSUE TITLE
Register validators for arbitrary classes

### ISSUE THREAD

**Issue by dconathan** [samuelcolvin/pydantic#501]
# Feature Request

I've got a need to "register" (?) arbitrary validators for custom classes.  Right now I can achieve the functionality I want doing something like this:

```py
from typing import Any
import pydantic.validators
from pydantic import BaseModel

class Foo:
    pass

def foo_validator(v: Any) -> Foo:
    if isinstance(v, Foo):
        return v
    if v == "Foo":
        return Foo()
    raise ValueError("Must be a Foo or the string 'Foo'")

pydantic.validators._VALIDATORS.append((Foo, [foo_validator]))

class Bar(BaseModel):
    foo: Foo

bar = Bar(foo="Foo")
```
This feels a *little* hacky.
So:
1) Is there already a better way to do something like this that I'm not seeing?
2) Would it be possible to support something less hacky than this?  e.g.

```py
pydantic.register_custom_validator((Foo, [foo_validator]))
```
And then `pydantic.validators.find_validators` could do something like this:
```py
    for val_type, validators in _VALIDATORS + _CUSTOM_VALIDATORS:
        try:
            if issubclass(type_, val_type):
                return validators
        except TypeError as e:
            raise RuntimeError(f'error checking inheritance of {type_!r} (type: {display_as_type(type_)})') from e
```

Happy to start working on PR if this seems feasible/reasonable/etc.

**Comment by samuelcolvin** [comment]
Best to use `__get_validators__` on `Foo` like [this](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/types.py#L201).

Then you can setup `Foo` to validate as you wish.

**Comment by dconathan** [comment]
Thanks!

For completeness, here's how to implement the above:

```py
from typing import Any
from pydantic import BaseModel

class Foo:
    @classmethod
    def __get_validators__(cls):
        def validator(v: Any) -> "Foo":
            if isinstance(v, cls):
                return v
            if v == "Foo":
                return cls()
            raise ValueError("Must be a Foo or the string 'Foo'")
        yield validator

class Bar(BaseModel):
    foo: Foo

bar = Bar(foo="Foo")
```

**Comment by samuelcolvin** [comment]
that will work, but generally more readable if you put the validator method as a classmethod on the `Foo` class as we do on all the pydantic validator classes, eg. `UrlStr`.

**Comment by inikolaev** [comment]
@samuelcolvin Is there a way to do the same for the classes that I don't control? E.g. I'm using a class from a 3rd party library and would like to use it inside a pydantic model. 

Seems like I'm forced to set `allow_arbitrary_type` in this case, but I'm not sure if that works in cases when I have to use a factory method to construct an instance, e.g.:

```python
class MyModel(BaseModel):
    version: VersionInfo
```

Where `VersionInfo` comes from `server` and can be constructed from a string value using `VersionInfo.parse`.

In this case I guess I would still have to declare a validator inside a class or fallback to the solution mentioned above :(

**Comment by samuelcolvin** [comment]
Best to inherit from `VersionInfo` and add validation as per above.

**Comment by hiaselhans** [comment]
I ran into this issue as well.

Sometimes it is not suitable to inherit from a base class. For example when it is a c++ implemented base class.

the "solution" from @dconathan works for that case, but since it is very hackish, I think it would be nice to implement a way to define per-type validators in the BaseModel. Let's say to have a default_validators tuple in BaseModel.Config?
