### ISSUE TITLE
Add Final type annotation to validate against concrete value

### ISSUE THREAD

**Issue by likern** [samuelcolvin/pydantic#502]
# Question | Feature Request | Bug

For bugs/questions:
* OS: **Ubuntu 18.04.2 LTS**
* Python version `3.7.3 (default, Mar 26 2019, 00:55:50) `
* Pydantic version `0.24`

Hello, could you please help?
I'm developing webhook framework which allows message passing based on types of incoming payload (usually all protocol is sent to webhook and it's required to validate data manually, I want to do that based on pydantic models)

Source code looks like this:
```py
@webhook.middleware(IssueEvent)
async def issue_event(issue: IssueEvent):
    print("[EVENT] Some general event")

@webhook.handler(IssueOpened)
async def issue_opened(event: IssueOpened):
    print("[EVENT] Issue was opened")
```
With the following schema definitions:

```py
class IssueAction(str, Enum):
    opened = 'opened'
    edited = 'edited'
    deleted = 'deleted'
    closed = 'closed'
    unassigned = 'unassigned'
    unlabeled = 'unlabeled'

class IssueEvent(BaseModel):
    action: IssueAction
    issue: IssuePayload
    assignee: Optional[Any]
    label: Optional[Any]
    repository: IssueRepository
    sender: IssueSender
    installation: IssueInstallation

class IssueOpened(IssueEvent):
    action: IssueAction = IssueAction.opened
```

**Problem:** I expected these schemas means / works like the following:

- For type `IssueEvent` field `action` is **required** and should be **one the values** of `IssueAction`
- For type `IssueOpened` field `action` is **required** (as overwrites previous value) and should be **exactly of value** `opened`

But it turned out other payloads also pass validation for `IssueOpened` (with different `action`).

**How to implement my intention that `action` of `IssueOpened`?:**
- is required field
- value of that field should be exactly of **IssueAction.opened**
- no any defaults are defined for field `action`

It would be very good to have similar syntax as above, using Enums. Because for webhooks it makes very easy to implement validation logic - applying the most general schema and later making some specializations of general one.

**Comment by likern** [comment]
@samuelcolvin  I have found the following proposal for adding `Final` type annotation, which exactly works as I expected.
Some links:

- [mypy](https://github.com/python/mypy/pull/5522)
- [typing_extensions](https://github.com/python/typing/pull/583)

As I've I understood `Final` will eventually be put into `typing` module, but now it's in `typing_extensions` for being accessible for all Python versions.

```py
from typing import Final

NO: Final = 0
YES: Final = 255

class BaseEngine:
    RATE: Final[float] = 3000

YES = 1  # Error!

class Engine(BaseEngine):
    RATE = 9000  # Also an error!
```

My example in this case will be:
```py
from typing import Final
class IssueOpened(IssueEvent):
    action: Final[IssueAction] = IssueAction.opened
```

**Is it possible to implement this `Final`?** 

As I understand `Final`to pydantic this would mean:

 - to compare `action` field of JSON exactly against value `IssueAction.opened`. If `action` is not equal validation should fail.

**Comment by samuelcolvin** [comment]
#469 is working on "const" right now, I think that would satisfy what you want, I'm merge #469 in a couple of days an release.

We could also use `Final` to do the same thing as `const` but it's trick until it's added to python proper, perhaps pydantic could have it's own version of `Final` which late works the same as `typing.Final`.

Also coincidentally, #503 also asked last night is basically looking for the same thing. Until #469 is merged, I would suggest you use the `validator` logic i suggest in #503.

Hope that helps, let me know if you have any more questions.

**Comment by dmontagu** [comment]
@likern I think the [`Literal`](https://mypy.readthedocs.io/en/latest/literal_types.html) type is intended for the validation aspect of your use case, whereas `Final` only says something about whether a property can be overridden. (That may separately be of interest, but as I see it, it is an orthogonal concern).

So, for example, for IssueOpened, it could be annotated:
```
from typing_extensions import Literal

class IssueOpened(IssueEvent):
    action: Literal[IssueAction.opened] = IssueAction.opened
```
If you annotated the class this way, mypy would know that attribute always has value `IssueAction.opened`. Then, for example if you had
```
issue = IssueOpened(...)
def f(action: Literal[IssueAction.closed, IssueAction.deleted]):
     ...
```
`mypy` would flag an error if you ever called `f(issue.action)`.

As far as I'm aware, the `Literal` type is not integrated with `pydantic`, but based on the mypy docs I think this is the way a use case like this is supposed to be handled.
