### ISSUE TITLE
python2 compatibility?

### ISSUE THREAD

**Issue by toumorokoshi** [samuelcolvin/pydantic#51]
Hi,

This may be a weird question for a project that's targetting type annotations in python3, but what's your opinion on Python 2 support?

I ask this because we're considering picking up a new validation / serialization library for a project we work on, and python2 is a requirement.

http://transmute-core.readthedocs.io/en/latest/

As you probably know, it's just a matter of a function which attaches a `__annotations__` parameter to the object. In transmute, we just provide a decorator "@attributes" that does this.

If you're open to Python 2 support, but just don't want to do the work to enable it, I can give it a shot.

**Comment by samuelcolvin** [comment]
I'm afraid I'm not at all open to python 2.

For me the python community is giving far too much time to supporting an obsolete version. All code written today (and for the last year) should be python 3 and all projects written in python 2 should bite the bullet and migrate before doing anything else.

I migrated TutorCruncher's main code base from 2 to 3 last year. Roughly 100k lines of code, It took me on my own around 3 weeks. Any other project (provided it has test coverage above 95%) should be able to be migrated at a similar rate. Any code base written in python 2 without such coverage should be abandoned immediately.

Ignoring my strong opinions on python 2, there are numerous technical problems with supporting python2 beyond just `__annotations__`:
* f-strings
* no u-strings
* `super()`
* classes without `object` inheritance.
* python3 metaclasses
* type annotations all over the place
* python3 type dict merging
* kwarg only `*` notation

The entire library would have to be rewritten in an uglier language - python six. Six is even uglier than python 2.

**Comment by samuelcolvin** [comment]
(thanks for your interest though, and thanks for asking the question - it gave me a chance to explain why I'm not willing to support python2)

**Comment by graingert** [comment]
@toumorokoshi might be possible to use pybackwards one day.

**Comment by samuelcolvin** [comment]
Why not put the effort into migrating the python 2 code to python 3 instead of putting effort into going backwards.

The migration process uncovers numerous subtle bugs and make your code base unequivocally better.

**Comment by toumorokoshi** [comment]
I write most of my code in Python3. It's really the hundreds of other services owned by other teams have code written in 2 that forces that compatibility requirement.

I salute the sentiment for pushing forward! Unfortunately, it makes Pydantic unviable for us. But thanks for explaining!
