### ISSUE TITLE
Validator is passed wrong value

### ISSUE THREAD

**Issue by pkarp0** [samuelcolvin/pydantic#519]
#  Bug
The validator is passed the wrong value:
```

from pydantic import BaseModel, validator 
class Example(BaseModel):
    attr: Dict[str, List[str]]

     @validator('attr')
     def valid_attr(cls, v):
         print(v)
         return v
 
e = Example(**dict(attr={"x": ['hi'], "y":['this','that']}))
hi
this
that

```
In this snippet I would expect the validator to get the value of attr which is {"x": ['hi'], "y":['this','that']}. Instead the values on the list are passed in.

 
For bugs/questions:
* OS: mac os 10.14.3
* Python version `import sys; print(sys.version)`:3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.24

**Comment by samuelcolvin** [comment]
This is not a bug, please read the documentation. You'll need to use `whole=True`.

**Comment by pkarp0** [comment]
Thanks for the fast reply.  The documentation may need clarification around when to use `whole`.

**Comment by samuelcolvin** [comment]
ok, happy to accept a PR to improve it.
