### ISSUE TITLE
Assignment to attribute changes id() but not referenced object

### ISSUE THREAD

**Issue by khaeru** [samuelcolvin/pydantic#521]
The example below is simplified from a larger package in which a line like `assert a.common is b.common` is used as a consistency check. I want to ensure that multiple instances of `Foo` share references to the same instance of a common object.

When migrating that package from traitlets to pydantic, the assertion began to fail.

As the example shows, `id(…)` gives *different* values for the original object, and the references to it in two instances of `Foo`; but the *same* value for attributes of the common object itself. I feel this is counterintuitive.

Maybe related to #154.

* OS: Ubuntu 19.04
* Python version: 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
* Pydantic version: 0.25

```py
from pydantic import BaseModel


class Common(BaseModel):
    # …attributes…
    x: int = 3
    pass


class Foo(BaseModel):
    common: Common

    def common_id(self):
        return id(self.common), id(self.common.x)

    def get_x(self):
        return self.common.x


c = Common()
a = Foo(common=c)
b = Foo(common=c)

# Objects appear to be different:
print((id(c), id(c.x)), a.common_id(), b.common_id(), sep='\n')
# (140498727091728, 9079072)
# (140498727091872, 9079072)
# (140498727092016, 9079072)

print(a.common is b.common)
# False

# …but are in fact linked:
c.x = 5
print(c.x, a.get_x(), b.get_x())
# 5 5 5

print(a.common.x is b.common.x)
# True
```

For now, I've worked around this by subclassing `BaseModel` and overloading `validate()` to replace `value.copy()` with simply `value` in the code below:
https://github.com/samuelcolvin/pydantic/blob/fe72ba13f469377057112d2f301f52cd3b206467/pydantic/main.py#L426-L434

**Comment by samuelcolvin** [comment]
I'm afraid this is a perfect example of how hard it is to please everyone ... #154.

I don't really see a way around this, I think not share items between model instances is probably right.

**Comment by tobias-huermann** [comment]
I expected also that its possible to share instances. I have a bigger model (~20 classes) with many references between and it is shared with the outer world via JSON. Would be awesome if pydantic could support something like object identities in some way. So also serialization does take care on that. E.g. [$ref](https://json-spec.readthedocs.io/reference.html) could be used for the serialization of instances already integrated in the JSON string.

```
class Person(BaseModel):
    id: int
    name = 'Jane Doe'


class Car(BaseModel):
    id: int
    owner: Person
    driver: Person


def test_pydantic():
    hannah = Person(id=11)
    hannah.name = "Hannah"
    test = Car(id=55, owner=hannah, driver=hannah)
    hannah.name = "?" # currently no effect because copied at constructor
    print(f"Driver: {id(test.driver)} Owner: {id(test.owner)}") # currently different ids because copied at constructor
    json_string = test.json()
    print(f"JSON: {json_string}")
    # JSON {"id": 55, "owner": {"id": 11, "name": "Hannah"}, "driver": {"id": 11, "name": "Hannah"}}
    car_reinstanced = Car.parse_raw(json_string)
    print(f"Driver: {id(car_reinstanced.driver)} Owner: {id(car_reinstanced.owner)}") # expected to be same
```

**Comment by khaeru** [comment]
I found I was able to remove a workaround for this, because #2193 / v1.8 added the option to set `Config.copy_on_model_validate = False` (https://pydantic-docs.helpmanual.io/changelog/#changes) 👍🏽
