### ISSUE TITLE
How to have a single validator for multiple fields?

### ISSUE THREAD

**Issue by jamesob** [samuelcolvin/pydantic#522]
This seems pretty basic so I wouldn't be surprised if I'm missing something obvious, but from a close read of the documentation I can't figure out how to have a validator which acts on multiple fields in a BaseModel, i.e. something like

```python
class Model(BaseModel):
  foo: int
  bar: int

  @model_validator(...)
  def compare_foo_and_bar(cls):
    # This is a nonsense example
    if not (foo - bar):
      raise ValueError(...)
```

**Comment by samuelcolvin** [comment]
Away from my computer so can't give a full example, but basically, the validator can take `values` as an argument.

The docs has an example with passwords.

**Comment by jamesob** [comment]
Cool, thanks. For posterity here's the example mentioned (I think): https://github.com/jamesob/pydantic/blob/fe72ba13f469377057112d2f301f52cd3b206467/docs/examples/validators_simple.py#L14-L20

This looks like `values` is the raw data coming in - is there a way to do a post-deserialization validation on the resulting BaseModel instance?

**Comment by samuelcolvin** [comment]
Not on the resulting `Model` (unless you did it manually yourself), but I don't think `values` is "raw data", I think it's already been validated.

**Comment by jamesob** [comment]
Cool, thanks for the great library.

**Comment by rothwelljeff** [comment]
Continuing from the above example, if I set the validation to run as such:
```
@model_validator('foo', 'bar')
  def compare_foo_and_bar(cls, value, values, **kwargs):
    # validator here...
```
This will run whenever either `foo` or `bar` attributes change, BUT that means when `foo` changes, then the `value` param is whatever `foo` is, and whenever `bar` changes, `value` becomes whatever `bar` is.  I assume the `values` param would then have all the other attributes in a dict.  So how can I possibly write a predictable validator if there's no way of knowing what I'm being passed as the `value`.  Essentially the code is saying "Either 'foo' or 'bar' changed, not telling you which one, but here's the value!"  Which is not very useful.

**Comment by samuelcolvin** [comment]
>  BUT that means when foo changes, then the value param is whatever foo is, and whenever bar changes, value becomes whatever bar is

No it doesn't. This is just a validator, it's a function that is called when these values are validated, it doesn't mean `foo` is set to `bar` or visa-versa.

> not telling you which one

No it doesn't. You can use use the `field` argument to identify which field is changing.

---

More generally: if you want help you would be well advised to change your tone.

If you are going state negative/critical things, take some time to check that what you're saying is correct. Incorrect, negative assertions are a pretty efficient way of pissing people off.

**Comment by anikolaienko** [comment]
@samuelcolvin 
I don't understand, sorry, so if, for instance, I want to verify if either of fields: `foo` or `boo` exists but not both at the same time, how can I do that?

Thanks.

**Comment by PrettyWood** [comment]
Hi @anikolaienko 
You could go with something like this

```python
from typing import Dict, Optional

from pydantic import BaseModel, validator


class Model(BaseModel):
    foo: Optional[str]
    boo: Optional[str]

    # Validate the second field 'boo' to have 'foo' in `values` variable
    # We set `always=True` to run the validator even if 'boo' field is not set
    @validator('boo', always=True)
    def ensure_only_foo_or_boo(cls, boo: Optional[str], values: Dict[str, Optional[str]]):
        foo = values.get('foo')
        if foo is not None and boo is not None:
            raise ValueError('only one of "foo" or "boo" can be set')
        if foo is None and boo is None:
            raise ValueError('one of "foo" or "boo" needs to be set')
        return boo
```

Hope it helps!

**Comment by anikolaienko** [comment]
Hi @PrettyWood , I appreciate your help! But this doesn't work for me. I still don't understand what is `values` because in my case `values` is empty dictionary when `boo` is not present.

I figured that I can use `root_validator(cls, values):` very nice and easy for this purpose.

**Comment by m-ocean-it** [comment]
> Hi @PrettyWood , I appreciate your help! But this doesn't work for me. I still don't understand what is `values` because in my case `values` is empty dictionary when `boo` is not present.
`values` would contain only already validated values. The invalid ones would be left out.

**Comment by anikolaienko** [comment]
@PrettyWood , @m-ocean-it I ended up using `root_validator`

Here is my example:
```python
from pydantic import BaseModel, Field, root_validator

class HelloWorldModel(BaseModel):
    foo: Optional[str] = Field(title="foo")
    boo: Optional[str] = Field(title="boo")

    @root_validator()
    def validate(cls, values: Dict[str, Any]) -> Dict[str, Any]:
         if values.get("foo") and values.get("boo"):
              raise ValueError("Expected only one, either `foo` or `boo`, not together")
         return values
```

**Comment by Expurple** [comment]
@anikolaienko, your code doesn't handle `False`ish values correctly: `HelloWorldModel(foo='', boo='')` doesn't raise the expected error. The fix is to check `"foo" in values and "boo" in values` instead of `values.get("foo") and values.get("boo")`.

Also, it's unclear whether you need at least one field to be set. Your code allows both fields to be `None`.

**Comment by nik-hil** [comment]
I have added it like this. The doc is not clear about how to do multiple fields validation in one validator..

```python
class Sample(BaseModel):
    duration_start: int
    duration_end: int

    @model_validator(mode="after")
    @classmethod
    def check_durations(cls, data: Any) -> Any:
        duration_start = data.duration_start
        duration_end = data.duration_end

        if duration_start is not None and duration_end is not None:
            if duration_start <= duration_end:
                raise ValueError("duration_start must be greater than duration_end")
        return data
```
