### ISSUE TITLE
Support for JSON 7.0 conditionals?

### ISSUE THREAD

**Issue by Lachele** [samuelcolvin/pydantic#529]
# Question | Feature Request

For bugs/questions:
* OS: Pop_OS 19.10
* Python version 3.7.3
* Pydantic version 0.25

It would be useful for me if conditionals (if, then, else) were supported. 

In this example, I'm not using code because I realize there might be alternate ways to do this thing I need done.  I have read many docs, but I am new at implementation.

Example situation:

'animal' is an Enum, which holds 'cat', 'dog', and 'horse'.  

'sounds' is also an enum, but it changes depending on 'animal'.  Horse has 'neigh', 'whinny' and 'snort'; cat has 'purr', 'meow', 'hiss';  dog has 'bark', 'whine' and 'growl'. 

Is there some way to get Pydantic to write this into Schema?  I understand that JSON 7.0 supports this.  I can probably use custom validation to validate existing JSON, but I'd love for it to be explicit in the schema.  And, yes, I can write that part of the schema myself if needed.

Thanks!

**Comment by tiangolo** [comment]
@Lachele there's currently no way to make Pydantic generate JSON Schema with `if`, `then`, `else`.

For now, I think you would have to use `Union` and validation.

Also, you can use `Schema` to pass any other keyword argument to be included in the final schema for each field: https://pydantic-docs.helpmanual.io/#schema-creation

**Comment by Lachele** [comment]
Thanks!  It's not that big a deal in my schema.  I was just wondering if I missed something.  Thanks for the tip about including custom keywords - I had missed that!
