### ISSUE TITLE
Feature request: Object creation - skip Optional elements that are nulls

### ISSUE THREAD

**Issue by wshayes** [samuelcolvin/pydantic#530]
# Feature Request

```py
class Metadata(BaseModel):
    src: str = "genbank"
    species_id: Optional[str]
...
```

When I create this Metadata object - it shows up as:

```
metadata = {"src": "genbank", "species_id": None}
```
Is it possible to create this object without the null elements? I like to add potential elements in the object to help with documentation and recommendations on keys to use, but I'd rather not have them show up unless they have a non-null value.

Great library - it's been a delight to use!

**Comment by samuelcolvin** [comment]
no problem, thank you.

You can use [`skip_defaults`](https://pydantic-docs.helpmanual.io/#copying) on `dict()` or `json()`.

**Comment by tiangolo** [comment]
@wshayes as in your case I think you want to use it with FastAPI, I have planned to include a way to add `skip_defaults` to *path operations*. I haven't implemented it yet but it's coming.

**Comment by wshayes** [comment]
Thank you both!
