### ISSUE TITLE
[Question] JSON object as dict?

### ISSUE THREAD

**Issue by berislavlopac** [samuelcolvin/pydantic#533]
# Question

Unless I'm missing something,`.json()` method returns a JSON string, while `.dict()` returns the Python dict with native objects, e.g. for datetime. Is there a way to retrieve a dict of JSON-ready values, without doing  a double conversion like:

```py
json_dict = json.loads(data_object.json())
```

Thank you!

**Comment by samuelcolvin** [comment]
Not that I know of, you could reuse the [`pydantic_encoder`](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/json.py#L41) function, but you would still need some of your own logic.

**Comment by tiangolo** [comment]
There was an attempt at adding something similar at https://github.com/samuelcolvin/pydantic/pull/317

And there's a discussion about it at https://github.com/samuelcolvin/pydantic/issues/377

Citing Samuel in that issue:

> Ugly though it is I doubt anything will catch `ujson.loads(model.json())`.

So, if you have installed `ujson`, you should get good performance using that.

---

Alternatively, if you are using FastAPI, you could use an opinionated version with `jsonable_encoder`: https://fastapi.tiangolo.com/tutorial/encoder/

---

Edit: I hadn't seen the `pydantic_encoder`. Just that might do it.

**Comment by berislavlopac** [comment]
Thank you @tiangolo , seems that `jsonable_encoder` is precisely what I need, as I'm using Fast API indeed. :smile:

**Comment by tiangolo** [comment]
Cool! @berislavlopac
