### ISSUE TITLE
'extra' config option not supported for dataclasses

### ISSUE THREAD

**Issue by ricardo8990** [samuelcolvin/pydantic#534]
Bug
---
For bugs/questions:
* OS: macOS 10.14.4
* Python version `import sys; print(sys.version)`: Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24)
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.25

The following code works:

```py
from pydantic import BaseModel

class UA(BaseModel):
    id:str

    class Config:
        extra='ignore'

u=UA(id='asd')
print(u)
# > UA id='asd'

u=UA(id='asd', extra='test')
print(u)
# > UA id='asd'
```

However, using dataclasses:
```py
from pydantic.dataclasses import dataclass

class Config:
    extra='ignore'

@dataclass(config=Config)
class UB:
    id:str

u=UB(id='asd')
print(u)
# > UB(id='asd')

u=UB(id='asd', extra='test')
# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# <ipython-input-52-d7537e1b6861> in <module>
# ----> 1 u=UB(id='asd', extra='test')
#
# TypeError: __init__() got an unexpected keyword argument 'extra'
```

Is there a way to use `extra='ignore'` for dataclasses? Otherwise, How can I use a shared Config class for many models, since I have 8 different classes with the same config class.

**Comment by samuelcolvin** [comment]
pydantic's dataclasses don't override the `__init__` method for dataclasses, so I'm afraid `extra` won't work. Can't easily think of a way around this.

Regarding sharing `Config`: `Config` supports inheritance so you should be able to do:

```py
class MainConfig:
    'whatever config you like'

class UA(BaseModel):
    id: str

    class Config(MainConfig):
        pass
```
