### ISSUE TITLE
timedelta serialization->de-serialization precision error

### ISSUE THREAD

**Issue by Lepercon5000** [samuelcolvin/pydantic#535]
# Bug

For bugs/questions:
* OS: Windows/Linux
* Python version `import sys; print(sys.version)`: 3.6.7
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.23

Where possible please include a self contained code snippet describing your 
bug, question, or where applicable feature request:

```py
from pydantic import BaseModel
from datetime import timedelta
from typing import Optional

class Foo(BaseModel):
    name: str
    time_delta: Optional[timedelta]

Foo.parse_raw(Foo(name="Bar", time_delta=timedelta(seconds=0.767607)).json())
```

What is going on is the float value that represents the timedelta deserializes with some precision error and the regex (pydantic.datetime_parse.standard_duration_re) does not allow for float values that are longer than 6 digits.

**Comment by samuelcolvin** [comment]
I agree `int` and `float` should both be accepted by `timedelta` and interpreted as seconds.

PR welcome.

Better not to convert them to strings, but rather just pass them to `timedelta(seconds=value)`.

**Comment by Lepercon5000** [comment]
After some further investigation, I was only able to reproduce the issue when using ujson as the json serializer (I was unable to repoduce it using the builtin json module).  Either way, there is still a possible issue if the BaseModel constructor is passed a high precision float value.

@samuelcolvin is there a reason why the standard_duration_re was implemented, but then on serialization the timedelta was serialized using timedelta.total_seconds()?

My thinking is to utilize the standard_duration_re for validation and to switch timedelta's json encoder to just output the strings representation of a timedelta (timedeltas.__str__ output) as the standard_duration_re seems to parse the results just fine. A change like this will not break back comparability in-theory, as the validator will not change and it will handle float input still.

**Comment by samuelcolvin** [comment]
sorry for the delay in responding to this.

I don't really want to change the standard serialization for `timedelta`:
1. for me total seconds a as a float makes the most sense as a default
2. it would break lots of peoples code.

Most people aren't serializing pydantic models to re-load them into pydantic (if you want to do that you'd be better off using pickle), but to use in other systems/languages eg. databases or js - in both of these situations using `str(delta)` would break things for them a lot.

**Comment by PrettyWood** [comment]
This issue doesn't seem to be relevant anymore. Closing the issue.
