### ISSUE TITLE
Include format with Secret types

### ISSUE THREAD

**Issue by djlambert** [samuelcolvin/pydantic#546]
# Feature Request

It'd be nice if `SecretStr` and `SecretBytes` included the `format` attribute with value `password` to hint UIs to mask the password.

```json
    "secretKey": {
        "title": "Secret Key",
        "type": "string",
        "description": "Secret key",
        "writeOnly": true,
        "format": "password",
        "example": "your secret key"
    },
```

**Comment by samuelcolvin** [comment]
you mean in the schema?

**Comment by djlambert** [comment]
Yes, sorry should have specified.

**Comment by tiangolo** [comment]
@djlambert they have `{"writeOnly": true}`. That's what is recommended by the JSON Schema spec for passwords specifically: http://json-schema.org/latest/json-schema-validation.html#rfc.section.10.3

There's no official `format` of "`password`" in the specs.

And the `writeOnly` is supposed to convey the equivalent message. So, I think having an additional, custom `password` format could misguide developers.

**Comment by djlambert** [comment]
It wouldn't be custom, it's in the OpenAPI specs https://swagger.io/specification/#dataTypes

**Comment by tiangolo** [comment]
You're right @djlambert.

It's not in JSON Schema but it's indeed in OpenAPI.

I think that deserves a PR.

**Comment by Atheuz** [comment]
Here's a PR: https://github.com/samuelcolvin/pydantic/pull/1424

**Comment by Atheuz** [comment]
This can be closed.
