### ISSUE TITLE
Could __post_init_original__ run before pydantic validation?

### ISSUE THREAD

**Issue by HeavenVolkoff** [samuelcolvin/pydantic#557]
# Question

* OS:
  > Linux 64-bit
* Python version `import sys; print(sys.version)`:
  > 3.7.3 (default, Mar 26 2019, 21:43:19) 
     [GCC 8.2.1 20181127]
* Pydantic version `import pydantic; print(pydantic.VERSION)`:
  > 0.26

Currently pydantic runs a dataclass' original `__post_init__` **after** its validation. However that limits valid use cases in which a required field is calculated inside the `__post_init__`. This is exemplified in python's dataclass documentation [here](https://docs.python.org/3/library/dataclasses.html#post-init-processing).

Python's example fails pydantic's validation:
```py
from dataclasses import field
from pydantic.dataclasses import dataclass

@dataclass
class C:
    a: float
    b: float
    c: float = field(init=False)

    def __post_init__(self):
        self.c = self.a + self.b

c = C(0.1, 0.2)
# Raises:
# ValidationError: 1 validation error
# c
#   field required (type=value_error.missing)
```
This behaviour is enforced here:
https://github.com/samuelcolvin/pydantic/blob/426325820738328ce4c023d43fbddad07d62f4a0/pydantic/dataclasses.py#L27-L32

**Comment by samuelcolvin** [comment]
I'd be happy with the change if it didn't break any existing tests.

**Comment by HeavenVolkoff** [comment]
@samuelcolvin I opened pull request https://github.com/samuelcolvin/pydantic/pull/560 with the changes. All tests seem to be passing fine. Could you review it?

**Comment by sevaho** [comment]
If I many I want to reopen this issue.

Shouldn't there be a way to disable this functionality with a global config variable?
I liked it that pydantic has done it's validation and then your code in the __post_init__ gets triggered.

Now you kinda have to validate the payload inside the __post_init__ again or is my workflow wrong?

```
from dataclasses import asdict

from pydantic.dataclasses import dataclass


class GlobalConfig:
    validate_assignment = True
    validate_all = True
    use_enum_values = True


@dataclass(config=GlobalConfig)
class Date(object):
    year: int
    month: int
    day: int


@dataclass(config=GlobalConfig)
class Calendar(object):
    date: Date

    def __post_init__(self):
        print("TRIGGERED")
        print(type(self.date))


try:
    # this triggers the post_init without validation
    calendar2 = Calendar(**{"date": {"year": 1995, "month": 3, "day": "wong"}})
except Exception:
    pass
```

Yes the fix is easy here just create a Date object and do ```Calendar(**{date: date_object})```

But what if I have a deep nested structure with a lot of composition do I need to create each object separately before creating my parent class?

**Comment by samuelcolvin** [comment]
Moved that discussion to another issue, see #566.
