### ISSUE TITLE
Empty list is a valid dict

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#558]
```py
from typing import Dict
from pydantic import BaseModel

class MyModel(BaseModel):
    d: Dict[int, int]

print(MyModel(d=[]))
#> MyModel d={}
```

**Comment by samuelcolvin** [comment]
Two options: either you can or can't pass a list to a dict field. 

An empty list should not be a special case.

Feedback welcome: should we prevent lists being passed to a dictionary. If this change is required it should happen in a major version bump.

**Comment by samuelcolvin** [comment]
Either way we should document it.

**Comment by layday** [comment]
Not just lists, any empty or two-element iterable is valid.

**Comment by samuelcolvin** [comment]
duplicate of #1268
