### ISSUE TITLE
Intended behavior of aliases?

### ISSUE THREAD

**Issue by qubidt** [samuelcolvin/pydantic#565]
# Question

For bugs/questions:
* OS: **Linux/MacOS**
* Python version `import sys; print(sys.version)`: **3.7**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **0.27**

I'm having some difficulty understanding how this library is supposed to be used when `alias`s are defined. I don't seem to be getting the behavior I would expect, as a primarily not-python programmer

> tl;dr: alias: what do?

## Expectations

to be able to define an `alias` for a class field that will be used during json serialization only (as a substitute for the property name)

## Observations

The [documentation states](https://pydantic-docs.helpmanual.io/#model-config):

> `allow_population_by_alias`
>
> whether or not an aliased field may be populated by its name as given by the model attribute, rather than strictly the alias; please be sure to read the warning below before enabling this (default: `False`)

implying the following:

```python
class User(BaseModel):
    id: Optional[int] = 0
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    class Config:
        ignore_extra = False
        allow_population_by_alias = False
        fields = {'first_name': 'firstName', 'last_name': 'lastName'}

sally = User(firstName='Sally', lastName='Mae')
assert sally.dict(by_alias=False) == {'id':0, 'first_name': 'Sally', 'last_name':'Mae'}
```

## Confusion

1. accessing fields seems inconsistent with calling constructors (**especially** with the default config values):

    ```python
    print(sally.first_name)             # Works
    # print(sally.firstName)            # AttributeError: 'User' object has no attribute 'firstName'

    print(User(firstName='Leroy'))      # Works
    # print(User(first_name='Leroy'))   # pydantic.error_wrappers.ValidationError: 1 validation error
                                        # first_name
                                        #   extra fields not permitted (type=value_error.extra)
    ```

    Is this design intended? It seems counter-intuitive to me

2. `allow_population_by_alias` from my perspective seems incorrectly named. It seems to do the opposite of what I expected
   * `sally.fields['first_name'].name == 'first_name'`
   * `sally.fields['first_name'].alias == 'firstName'`
   * I expected this to mean:
        ```python
        if (User.Config.allow_population_by_alias == False):
            User(first_name='Jeri')  # OK
            User(firstName='Jeri')   # raises Exception
        elif (User.Config.allow_population_by_alias == True):
            User(first_name='Jeri')  # OK
            User(firstName='Jeri')   # OK
        ```
   * should it not be named `allow_population_by_field_name` ?

3. Is there a way to have the inverse behavior of the strict (default) parameters? I would like:

    ```python
        sally = User(first_name='Sally')    # OK
        # sally = User(firstName='Sally')   # AttributeError: 'User' object has no attribute 'firstName'
    ```

    when `allow_population_by_alias == False`

4. Why is `allow_population_by_alias` a feature at all?

   the only benefit seems to be the ability to:
   ```python
   User(**some_user_dict)
   ```
   instead of (for example; I don't know how pydantic would implement this)
   ```python
   User.parse_obj(some_user_dict, by_alias=True)
   ```
   ? It's not immediately obvious to me why this should be a class-level configuration, causing the need for the big disclaimer on its usage.

Is there some fundamental design I'm just missing? I feel like I'm not on the same page with how aliases are implemented in this library (which is otherwise very well designed, IMO)

**Comment by samuelcolvin** [comment]
thanks for the detailed question, I'll give a quick answer now as I need to leave the office, if it's still unclear feel free to ask further.

aliases as I think of them are

> a mapping between the names of fields used "publicly" and the names used in your application

Where publicly means in javascript, in an API, in the file you're parsing etc.

I'm aware lots of people use them in other ways, but that's what I think they should be used for.

`allow_population_by_alias` does have the wrong name, it should probably be `allow_population_by_not_alias` or something less ugly. See #160 for a discussion around why it exists. It might well have been a mistake to implement it or implement it the way it is, but I think a lot of people use it as an escape hatch now.

`print(sally.firstName)` doesn't work, I suppose there's nothing us implementing it, but as per my definition of aliases above it would be redundant.

If that makes sense I'd be very happy to accept a PR or recommendations on how to make the docs clearer.

You might also be interested in #477.

**Comment by qubidt** [comment]
Thank you, that really does clear up my questions about the design goals. I still do have a couple small questions about how this works in practice, particularly:

Given that `alias` is the 'public' name of your field, e.g. in files/other languages/json/etc. whereas the field names are internal to your application (to reiterate what you said), does the use of it in the generated constructors not conflict with this goal?

```
class Person(pydantic.BaseModel):
	id: int
	first_name: Optional[str] = pydantic.Schema(None, alias='firstName')

samwell = Person(id=101, firstName='Samwell')
print(samewell.first_name)
```

You can't reasonably avoid using both fields internally, no? In this situation it seems the choices are:

1. Use `field.alias` in all constructor calls and `field.name` in all field accesses
	* This still seems inconsistent to me. I wouldn't necessarily consider constructor calls as 'public' in the general sense. Particularly, I have in mind instances completely internal to your module, not even inter-language or inter-system
2. Only use `alias` at system/API/language boundaries
	* Perhaps represent app-internal structs with a separate pydantic model or a plan dataclass
	* Adds burden of mantaining a similar but separate set of models. Maybe do some clever inheritence/property stuff to make this more automatic.
3. Use `allow_population_by_alias` and use the field name everywhere, accepting the big warning about it
	* This feels like a bad idea, I agree with the warning that the behavior introduced seems undeseriable. 
4. Just use the aliased name as the field names and avoid the `alias` mechanic altogether.
	* I don't think my linter will be very happy about this, not even considering what names are valid for our existing json schemas that python might forbid

I think 1) is the most reasonable choice and 3) is the laziest one (if you consider having to mentally maintain both aliases as effort).

I'm leaning towards 1) even though I don't think I'm completely comfortable with it. Do you have any suggestions? Maybe I'm framing this the wrong way. The languages I'm familiar with are statically typed, could this just be some fundamental misunderstanding of how dynamically-typed languages should be used?

Thanks for the quick response, and the library. Of all the ones serving a similar role I've tried, pydantic has been my favorite to use in practice.

**Comment by samuelcolvin** [comment]
> Thanks for the quick response, and the library. Of all the ones serving a similar role I've tried, pydantic has been my favorite to use in practice.

Thanks a lot.

Most people go with 1). In general this isn't a problem since you (mostly) create a model once using something like `MyModel(**external_data)` and from from then on access the data via field names.

3) is really their for places where misdesign means you have to effectively do `MyModel(**my_old_model.dict())`, if you've designed things correctly this shouldn't be required - if you do want to serialise or copy models use `pickle` or `copy()`.

By the way, the concept of `alias` (albeit by another name) exists in similar libraries for statically types languages, eg [`rename` in rust-serde](https://serde.rs/field-attrs.html).

**Comment by qubidt** [comment]
Thanks, sounds good.  

> If that makes sense I'd be very happy to accept a PR or recommendations on how to make the docs clearer.

I'd love to contribute, even though technical writing isn't my strong suit. If I figure out some concrete improvements to the wording in the docs I'll be sure to submit a PR.

**Comment by mfulgo** [comment]
Note: This option was renamed to `allow_population_by_field_name` in `v1.0`.
