### ISSUE TITLE
Pre and post parsing triggers for dataclasses

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#566]
If I many I want to reopen this issue.

Shouldn't there be a way to disable this functionality with a global config variable?
I liked it that pydantic has done it's validation and then your code in the __post_init__ gets triggered.

Now you kinda have to validate the payload inside the __post_init__ again or is my workflow wrong?

```
from dataclasses import asdict

from pydantic.dataclasses import dataclass


class GlobalConfig:
    validate_assignment = True
    validate_all = True
    use_enum_values = True


@dataclass(config=GlobalConfig)
class Date(object):
    year: int
    month: int
    day: int


@dataclass(config=GlobalConfig)
class Calendar(object):
    date: Date

    def __post_init__(self):
        print("TRIGGERED")
        print(type(self.date))


try:
    # this triggers the post_init without validation
    calendar2 = Calendar(**{"date": {"year": 1995, "month": 3, "day": "wong"}})
except Exception:
    pass
```

Yes the fix is easy here just create a Date object and do ```Calendar(**{date: date_object})```

But what if I have a deep nested structure with a lot of composition do I need to create each object separately before creating my parent class?

_Originally posted by @sevaho in https://github.com/samuelcolvin/pydantic/issues/557#issuecomment-497622839_

**Comment by samuelcolvin** [comment]
Probably best that we have another trigger method.

The problem is we should probably have called the trigger called after parsing `__post_init__` and had another name for before. However now we've changed it, I don't really want to change it back. So it's too late for that

I guess best that we add another method `__post_init_post_parse__` and document when each is called?

PR welcome.

**Comment by sevaho** [comment]
made a pull request #567
