### ISSUE TITLE
pylint complain on models with validators since version 0.27

### ISSUE THREAD

**Issue by MartinWallgren** [samuelcolvin/pydantic#568]
Bug

For bugs/questions:
* OS: **Linux (Debian 9)**
* Python version `import sys; print(sys.version)`: 
**3.7.3 (default, May 22 2019, 11:07:29)
[GCC 6.3.0 20170516]**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **0.27**

Where possible please include a self contained code snippet describing your 
bug, question, or where applicable feature request:

the below model causes `pylint model.py` to complain about 
model.py:12:4: E0213: Method should have "self" as first argument (no-self-argument)
model.py:12:4: R0201: Method could be a function (no-self-use)
model.py:7:0: R0903: Too few public methods (1/2) (too-few-public-methods)

```py
from typing import Optional

import pydantic


class DemoModel(pydantic.BaseModel):

    some: Optional[str] = None

    @pydantic.validator("some")
    def check_some(cls, val):
        return val

```

These complaints does not occur with pydantic 0.26.

Marking the validator as @classmethod will cause it to not execute at all, so the only option I have found is to disable these checks in pylint.

**Comment by samuelcolvin** [comment]
The major change in v0.27 was that pydantic was compiled with cython, I guess this makes introspection by pylint of the pydantic code harder or impossible.

There might be some way to trick pylint into think you're using the non-compiled pydantic code (should behave exactly the same), but I'm afraid that's a question for pylint.

Otherwise I don't really know how to help as I've never used pylint.

Let me know if you find a solution.

**Comment by gangefors** [comment]
The issue seems to be in the published version of pydantic.

To replicate this I cloned the pydantic git and did the following.

Running pylint in a docker container with the source mounted I see the following.
```
$ docker run --rm -it -v `pwd`:/src -w /src -e https_proxy python:3.7 bash -c "pip install -q pylint && cat demo_model.py && pylint demo_model.py" 
# pylint: disable=missing-docstring
from typing import Optional

import pydantic


class DemoModel(pydantic.BaseModel):

    some: Optional[str] = None

    @pydantic.validator("some")
    def check_some(cls, val):
        return val

------------------------------------
Your code has been rated at 10.00/10
```

But if I use the published pydantic version I get the errors mentioned in the bug report.
```
$ docker run --rm -it -v `pwd`/demo_model.py:/src/demo_model.py -w /src -e https_proxy python:3.7 bash -c "pip install -q pydantic==0.27 pylint && cat demo_model.py && pylint demo_model.py"
# pylint: disable=missing-docstring
from typing import Optional

import pydantic


class DemoModel(pydantic.BaseModel):

    some: Optional[str] = None

    @pydantic.validator("some")
    def check_some(cls, val):
        return val
************* Module demo_model
demo_model.py:12:4: E0213: Method should have "self" as first argument (no-self-argument)
demo_model.py:12:4: R0201: Method could be a function (no-self-use)
demo_model.py:7:0: R0903: Too few public methods (1/2) (too-few-public-methods)

------------------------------------
Your code has been rated at -1.67/10
```

This might be related to the cython changes done for this release.


And on a side note. When introducing potentially breaking changes, please step up the major version to indicate this. It's hell to investigate and fix test environments due to breaking changes in minor version bumps.

**Comment by samuelcolvin** [comment]
confirmed with

```
curl -L https://files.pythonhosted.org/packages/28/06/5faf55ff0fc320c508bbdc6d3a85ca1da7537fb42617863eda1a524e4bcd/pydantic-0.27-py36.py37.py38-none-any.whl > pydantic-0.27-py36.py37.py38-none-any.whl
pip uninstall -y pydantic
pip install pydantic-0.27-py36.py37.py38-none-any.whl
pylint test.py
```
Doesn't give the error, while default install from pypi does.

**Comment by samuelcolvin** [comment]
You might be able to use something like the above for linting, but make sure you're using the compiled pydantic for tests and production.

**Comment by samuelcolvin** [comment]
@gangefors 

> And on a side note. When introducing potentially breaking changes, please step up the major version to indicate this. It's hell to investigate and fix test environments due to breaking changes in minor version bumps.

1. I'm following semvar, we're pre version 1 so everything can be a breaking change, but here I did use a new minor version for this change - the biggest change I could make except for upreving to v1 which I think you'd agree would be more confusing.
2. I documented it [**very**](https://github.com/samuelcolvin/pydantic/blob/master/HISTORY.rst#v027-2019-05-30) prominently in the change log.
3. I created a [pre-release](https://pypi.org/project/pydantic/0.27a1/) to test cython, left the pull request #548 open for a couple of days for feedback and ask people to check it worked.

Is that really not sufficient?

But we should move to version 1, I agree.

**Comment by samuelcolvin** [comment]
I would suggest you use something like pyup.io to upgrade dependencies, the changelog included in PRs will avoid "hell".

**Comment by gangefors** [comment]
I hear you regarding following semvar. But then one could argue that it's easy to stay at 0.x.y for all future releases which would make life easy for the developer but not for the users.

This software is awesome and we have considered it really stable for many versions now sans a few minor breaking changes. We do hope that you decide to "release" it soon. Thanks for your work and fast respones in the community.

**Comment by samuelcolvin** [comment]
thanks, I agree - just trying to work out if there's anything big I want to change before releasing.

**Comment by pawelrubin** [comment]
This is still an issue in pydantic 1.5.1.

**Comment by dewei-verkada** [comment]
Seeing the same issue on pydantic 1.5.1

**Comment by daniel-demelo** [comment]
I'm also having the same issue :/

**Comment by daniel-demelo** [comment]
The code works, its just the pylint complain that annoys, but in the meantime this error could be disabled if you write this comment on top of the class
# pylint: disable=E0213

I did find this information on this post:
https://stackoverflow.com/questions/27965324/how-to-disable-pylint-no-self-use-warning

**Comment by yustoris** [comment]
Please reopen, I also have the same issue. It is very annoying

**Comment by samuelcolvin** [comment]
What's the problem in pydantic? As far as I know this is an issue with pylint.

I need some indication of what pydantic is doing wrong or how we might fix it to reopen this.

---

If you find the open source code I work on in my free time and give away for free annoying, don't use it.

**Comment by gangefors** [comment]
pydantic isn't doing anything wrong, it's pylint that can't introspect the code properly.

AFAICT `pydantic.validator` returns a `classmethod` type object and pylint should be able to pick this up but it doesn't.

There might be ways to rewrite the code to make pylint happy, but I do think that it would be better to make pylint handle the code as it is written since it's totally valid code.

**Comment by samuelcolvin** [comment]
I'm pretty sure the code is typed correctly since it passes mypy and didn't used to, but the typing around validators is pretty complicated, I wouldn't be surprised if it was too complicated for pylint.

---

In general I find mypy + black + isort + flake8 enough. That more does pylint provide?

**Comment by pmav99** [comment]
@samuelcolvin 
Even flake8 complains about the first argument not being `self`. Furthermore, I don't think that changing linters is something that most people would consider.

Nevertheless, the problem is clearly with pylint which doesn't support custom decorators/descriptors.

A hackish workaround is to add a `@classmethod` decorator after the `pydantic.validator` one. For simple cases it seems to work and it does silence the linters. Not sure if there are any side-effects though and I haven't tested it in bigger codebases:

``` python
import pydantic

class Model(pydantic.BaseModel):

    value: int

    @pydantic.validator("value")
    @classmethod
    def _get_the_answer(cls, val: int) -> int:
        print(val)
        return 42

instance = Model(value=3)
print(instance)
``` 

In my case, I will probably just add an explicit `# pylint: disable=no-self-argument,no-self-use` though

**Comment by johnthagen** [comment]
> Even flake8 complains about the first argument not being `self`.

This still happens, but it does only when the [`pep8-naming`](https://pypi.org/project/pep8-naming/) `flake8` plugin is installed.

```py
from pydantic import BaseModel, validator


class DemoModel(BaseModel):
    name: str

    @validator("name")
    def check_some(cls, val: str) -> str:
        return val
```

```bash
$ pip list
Package           Version
----------------- --------
click             7.1.2
flake8            3.9.1
flake8-polyfill   1.0.2
mccabe            0.6.1
pep517            0.10.0
pep8-naming       0.11.1
pip               21.1.1
pip-tools         6.1.0
pycodestyle       2.7.0
pydantic          1.8.1
pyflakes          2.3.1
setuptools        56.0.0
toml              0.10.2
typing-extensions 3.10.0.0
wheel             0.36.2
```

```bash
$ flake8 main.py
main.py:8:21: N805 first argument of a method should be named 'self'
```

**Comment by johnthagen** [comment]
To configure `pep8-naming` flake8 plugin to work with Pydantic `@validator`'s, either set the following CLI flag:

```
flake8 --classmethod-decorators=classmethod,validator
```

Or set the following configuration option in `setup.cfg` / `flake8.ini` / `tox.ini`:

```ini
[flake8]
classmethod-decorators =
    classmethod
    validator
```

**Comment by calvo-jp** [comment]
> @samuelcolvin
> Even flake8 complains about the first argument not being `self`. Furthermore, I don't think that changing linters is something that most people would consider.
> 
> Nevertheless, the problem is clearly with pylint which doesn't support custom decorators/descriptors.
> 
> A hackish workaround is to add a `@classmethod` decorator after the `pydantic.validator` one. For simple cases it seems to work and it does silence the linters. Not sure if there are any side-effects though and I haven't tested it in bigger codebases:
> 
> ```python
> import pydantic
> 
> class Model(pydantic.BaseModel):
> 
>     value: int
> 
>     @pydantic.validator("value")
>     @classmethod
>     def _get_the_answer(cls, val: int) -> int:
>         print(val)
>         return 42
> 
> instance = Model(value=3)
> print(instance)
> ```
> 
> In my case, I will probably just add an explicit `# pylint: disable=no-self-argument,no-self-use` though

Thanks. This works and looks cleaner for me

**Comment by TommyDuc** [comment]
> @samuelcolvin Even flake8 complains about the first argument not being `self`. Furthermore, I don't think that changing linters is something that most people would consider.
> 
> Nevertheless, the problem is clearly with pylint which doesn't support custom decorators/descriptors.
> 
> A hackish workaround is to add a `@classmethod` decorator after the `pydantic.validator` one. For simple cases it seems to work and it does silence the linters. Not sure if there are any side-effects though and I haven't tested it in bigger codebases:
> 
> ```python
> import pydantic
> 
> class Model(pydantic.BaseModel):
> 
>     value: int
> 
>     @pydantic.validator("value")
>     @classmethod
>     def _get_the_answer(cls, val: int) -> int:
>         print(val)
>         return 42
> 
> instance = Model(value=3)
> print(instance)
> ```
> 
> In my case, I will probably just add an explicit `# pylint: disable=no-self-argument,no-self-use` though

Adding `@classmethod` will not work before still makes PyCharm complain and putting it after will not call the validator.
I just added # noqa: N805

**Comment by samuelcolvin** [comment]
Pycharm works fine if you use the plugin.

**Comment by TommyDuc** [comment]
> Pycharm works fine if you use the plugin.

I do have the plugin and it works for most cases except this one.

**Comment by samuelcolvin** [comment]
I think you might need to import validator directly.

**Comment by TheBubblePopped** [comment]
I am using mypy too @samuelcolvin but i am using disallow_untyped_defs = True and i am def getting that error on self :(

**Comment by caffeinatedMike** [comment]
> To configure `pep8-naming` flake8 plugin to work with Pydantic `@validator`'s, either set the following CLI flag:
> 
> ```
> flake8 --classmethod-decorators=classmethod,validator
> ```
> 
> Or set the following configuration option in `setup.cfg` / `.flake8` / `tox.ini`:
> 
> ```ini
> [flake8]
> classmethod-decorators =
>     classmethod
>     validator
> ```

Saved my freaking sanity (or what's left of it). Thanks!
