### ISSUE TITLE
choice checking of custom data types

### ISSUE THREAD

**Issue by jakubsielewicz** [samuelcolvin/pydantic#569]
# Question

* OS: Windows10
* Python version `import sys; print(sys.version)`: 3.7.3
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.26

```py

from pathlib import Path
from enum import Enum
from typing import List

from typing import Optional
from pydantic import BaseModel, UrlStr


class Coding(BaseModel):
    code: Optional[str]


class CodeableConcept(BaseModel):
    coding: Optional[List[Coding]]
    text: Optional[str]


class PatientContactRelationshipCode(Enum):
    emergencycontact = 'C'
    employer = 'E'
    federalagency = 'F'
    insurancecompany = 'I'
    nextofkin = 'N'
    stateagency = 'S'
    unknown	= 'U'

class PatientContactRelationshipCoding(BaseModel):
    coding: Coding = Coding.code(PatientContactRelationshipCode)


class PatientContactRelationship(BaseModel):
    codeableconcept: CodeableConcept = List[PatientContactRelationshipCoding]

class PatientContact(BaseModel):
    relationship: Optional[List[PatientContactRelationship]]

class PatientBase(BaseModel):
    contact: Optional[List[PatientContact]]


fname  = (Path(__file__).parent / "../test/codeconcept.json").resolve()

# codeconcept.json =
# {
#   "contact": [
#     {
#       "relationship": [
#         {
#           "coding": [
#             {
#               "code": "XX"
#             }
#           ]
#         }
#       ]
#     }
#   ]
# }

try:
    m = PatientBase.parse_file(fname)
    print(m)
except ValidationError as e:
    print(e)

```
Output:
Traceback (most recent call last):
  File ".\test-harness.py", line 28, in <module>
    class PatientContactRelationshipCoding(BaseModel):
  File ".\test-harness.py", line 29, in PatientContactRelationshipCoding
    coding: Coding = Coding.code(PatientContactRelationshipCode)
AttributeError: type object 'Coding' has no attribute 'code'

What Im trying to do here is check for valid code within a very deep hierarchy. I know that I could just use the the Enum function at the root and have in other appllications, but the schema that I have to work is forcing me down this complex nested route. 
The output I was hoping to get is an invalid code based on validation.
Any help greatly appreciated.

**Comment by dmontagu** [comment]
@jakubsielewicz  It's not clear to me what your intention is. The reason this fails is that `Coding.code` would refer to an attribute of the *class* `Coding`, not an instance, but in pydantic only actual *instances* of a model have the annotated properties. As you noted, if you had declared 
```python
class Coding(BaseModel):
    code: Optional[PatientContactRelationshipCode]
```
it would be able to parse your json correctly (assuming the code was valid; I'm not sure if `"XX"` is meant to be a variable here or not).

Could you describe what specifically is not handled correctly by the `code: Optional[PatientContactRelationshipCode]` version? Ideally with an example json payload you want to be able to validate, but that would not be handled correctly by the enum-based approach.

**Comment by jakubsielewicz** [comment]
```py

from pathlib import Path
from enum import Enum
from typing import List, Union

from typing import Optional
from pydantic import BaseModel, UrlStr, ValidationError


class PatientContactRelationshipCode(Enum):
    emergencycontact = 'C'
    employer = 'E'
    federalagency = 'F'
    insurancecompany = 'I'
    nextofkin = 'N'
    stateagency = 'S'
    unknown	= 'U'


class PatientContactRelationshipCoding(BaseModel):
    code: PatientContactRelationshipCode


class PatientContactRelationship(BaseModel):
    coding: List[PatientContactRelationshipCoding]


class PatientContact(BaseModel):
    relationship: Optional[List[PatientContactRelationship]]


class PatientBase(BaseModel):
    contact: Optional[List[PatientContact]]


fname  = (Path(__file__).parent / "../test/codeconcept.json").resolve()

# codeconcept.json =
# {
#   "contact": [
#     {
#       "relationship": [
#         {
#           "coding": [
#             {
#               "code": "XX"
#             }
#           ]
#         }
#       ]
#     }
#   ]
# }

try:
    m = PatientBase.parse_file(fname)
    print(m)
except ValidationError as e:
    print(e)
```
The code above fixed the issue - i was just looking at it for too long - thanks for the steer
