### ISSUE TITLE
Allow "human name" to be specified in model config

### ISSUE THREAD

**Issue by cjw296** [samuelcolvin/pydantic#571]
# Feature Request

There should be a way to give pydantic models a human readable name. 
If my model is class `VirtualMachine(BaseModel)` I can have a name of `Virtual Machine`?

@tiangolo suggested this should go on model config.

**Comment by tiangolo** [comment]
@samuelcolvin I was thinking on adding an attribute to the `Config` class, like `schema`, `extra_schema` or similar, that would allow adding things like `title`, `description`, etc.

Currently, it's possible to describe these on fields using `Schema`, and even extra extensions to JSON Schema, but not on models (`BaseModel`).

Adding a single extra attribute to `Config` would be the minimum API change. Other option would be to add extra attributes like `title`, `description` and another `extra_schema` (or similar).

I was also thinking of populating a model's JSON Schema description with the class' docstring, when provided.

What do you think?

**Comment by samuelcolvin** [comment]
Sounds good to me. I thought the description was already pulled from the docstring but maybe that was in the first version of the schema?

The only question I'd have is: do we want `titla` and `plural_title` eg. "Virtual Machine" and "Virtual Machines" like django does?

**Comment by tiangolo** [comment]
> Sounds good to me. I thought the description was already pulled from the docstring

That's possible, I don't remember well. I'll make sure it keeps doing it/does it anyway.

> The only question I'd have is: do we want titla and plural_title eg. "Virtual Machine" and "Virtual Machines" like django does?

`title` is part of the JSON Schema spec, `plural_title` isn't. We can include it if you prefer to.

---

What would you like extra in the `Config`?:

1. Do you want a single `schema` attribute?

2. Or `title` (2b. possibly `plural_title`), `description`, and `schema` (or 2c. `extra_schema`)?

**Comment by cjw296** [comment]
I’d go for both, with computed, sensible defaults.

**Comment by tiangolo** [comment]
Still, the idea is for `schema` or `extra_schema` to receive a `dict` that can contain `title`, `plural_title` and even any other custom extension to JSON Schema.

The question is, first, which attribute name: `schema`, `extra_schema`, `schema_extra`?

And second, apart from that, do we want an extra `title`? An extra `description`? An extra `plural_title`? These would override anything that was set with those keys in the `schema` attribute I guess. It would be mostly as syntactic sugar.

**Comment by tiangolo** [comment]
So, I'm currently checking #531 , and checking the code, I discovered/realized that this, with respect to the specific feature of human names,  is already implemented.

I had forgotten about it. :man_shrugging: 

@cjw296 use `title` inside the `Config`. And if you want to use a `description`, it is indeed taken from the docstring.

It's actually semi-documented here: https://pydantic-docs.helpmanual.io/#schema-creation

@samuelcolvin should we change this issue for *my* feature request of extending the `schema` or should I open a new one?

**Comment by samuelcolvin** [comment]
new issue, I don't understand what extra you want on `schema`.
