### ISSUE TITLE
Recover Model from ValidationError data

### ISSUE THREAD

**Issue by asmodehn** [samuelcolvin/pydantic#574]
# Question

My usecase might be a bit different than most. I want to use pydantic to validate user input.
And upon validation error, potentially prompt the user for another input.

* OS: Linux (Ubuntu 18.04)
* Python version `import sys; print(sys.version)`: '3.7.2 (default, Jan  8 2019, 16:12:09) \n[GCC 7.3.0]'
* Pydantic version `import pydantic; print(pydantic.VERSION)`: StrictVersion ('0.25')

I am not sure [ValidationError](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/error_wrappers.py#L51) has enough information to recover original intent (type annotations -or other info- of the model hierarchy) in order to reattempt the validation. Especially it doesn't seem obvious how to read through `error['loc']` while walking through the original model hierarchy...

I was wondering if there was any code example to do something like that ?
If I eventually get some code working I'll post it here.

Thanks !

**Comment by samuelcolvin** [comment]
It doens't, you'll either want to:
* reparse the data your passed to the model in another way
* or call [`validate_model`](https://github.com/samuelcolvin/pydantic/blob/v0.27/pydantic/main.py#L579) directly, if pass `raise_exc = False` you can get back both the `ValidationError` instance and the data that was valid.
