### ISSUE TITLE
module 'cython' has no attribute 'compiled'

### ISSUE THREAD

**Issue by mivade** [samuelcolvin/pydantic#584]
# Bug

* OS: macOS
* Python version `import sys; print(sys.version)`: 3.7.3
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **?**

After `pip install pydantic`, I get the following when trying to import anything from `pydantic`:

```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-3cd21b2a399c> in <module>
----> 1 from pydantic import BaseModel

~/miniconda3/envs/starlette/lib/python3.7/site-packages/pydantic/__init__.py in <module>
      1 # flake8: noqa
----> 2 from . import dataclasses
      3 from .class_validators import validator
      4 from .env_settings import BaseSettings
      5 from .error_wrappers import ValidationError

~/miniconda3/envs/starlette/lib/python3.7/site-packages/pydantic/dataclasses.py in <module>
      6 from .errors import DataclassTypeError
      7 from .fields import Required
----> 8 from .main import create_model, validate_model
      9 from .utils import AnyType
     10 

~/miniconda3/envs/starlette/lib/python3.7/site-packages/pydantic/main.py in <module>
     66     compiled: bool = False
     67 else:  # pragma: no cover
---> 68     compiled = cython.compiled
     69 
     70 

AttributeError: module 'cython' has no attribute 'compiled'
```

Note that this gets resolved by installing Cython, but this should not be a requirement. This is likely related to #555.

**Comment by samuelcolvin** [comment]
Which version of pydantic (these questions are there for a reason)?

This was fixed in the most recent release via #573

**Comment by mivade** [comment]
The version I get when I `pip install`. I get the import error when trying to even import the version and hence I could not answer that question.

**Comment by mivade** [comment]
For future reference:

```
$ pip list | grep pydantic
pydantic         0.27
```

**Comment by mivade** [comment]
It looks like that is one version back, but then I'm not sure why `pip` chose to get an older version.

**Comment by samuelcolvin** [comment]
`pip install -U pydantic`

**Comment by mivade** [comment]
```
$ pip install -U pydantic
Requirement already up-to-date: pydantic in ./miniconda3/envs/starlette/lib/python3.7/site-packages (0.27)
```

**Comment by mivade** [comment]
According to PyPI when I just checked now, it looks like 0.27 is the latest version available: https://pypi.org/project/pydantic/

**Comment by samuelcolvin** [comment]
Yes, looks like release of v0.28 failed. I'll fix it tomorrow.

**Comment by samuelcolvin** [comment]
sorry about this, `v0.28` is released. Please install that and try.

**Comment by mivade** [comment]
That did it. Thanks!
