### ISSUE TITLE
Remove nulls during parse_file

### ISSUE THREAD

**Issue by jakubsielewicz** [samuelcolvin/pydantic#588]
# Question | Feature Request

* Python version `import sys; print(sys.version)`: 3.7
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.26

With regard to the following code and outputs:

```py
class SomeModel(BaseModel):
    a: Optional[str]
    b: Optional[str]
    c: Optional[str]
...
myjsonfile.json:
{
     "a" : "mya"
     "b" : "myb"
}

sm = SomeModel.parse_file(myjsonfile.json)
print(sm.json())
{
     "a" : "mya"
     "b" : "myb"
     "c" : null
}

```
Would it be possible to include a feature in the parse_file or perhaps add another helper function that would return the json without null values - this would need to apply across deeply nested structures including lists and dicts? Any advise greatly appreciated.

**Comment by samuelcolvin** [comment]
This is the same as #587
