### ISSUE TITLE
switch from ujson to orjson

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#589]
I got an email some time ago from @ijl:

> removed (I was asked to remove the content of the email)

(I asked if they could create an issue but I guess it got forgotten)

If we want to move to orjson (and it sounds to me like a pretty good idea) it should be done before v1.

I guess we should make `orjson` a requirement and use it always rather than switch between ujson and json.

Any feedback on this?

I guess it would allow us to simplify `pydantic_encoder` eg. by no longer having to deal with datetime objects.

However there would also be some breaking changes I think.

@tiangolo do you have any view on this? I know you have a significant requirement for serialising to JSON but also to "JSON-like python objects". Does orjson help or hinder this?

**Comment by tiangolo** [comment]
Thanks for tagging me!

I received a very similar email suggesting it for FastAPI, and the PR never arrived as well :joy: 

I was thinking about writing a PR to try it out here and see what would happen but never found the time.

I don't think this would affect my use cases, or if anything, would improve them. But I haven't checked thoroughly.

**Comment by ijl** [comment]
I think the use in both projects would be rather involved. If the goal is to remove ujson, I have a minimal patch in #599.

**Comment by samuelcolvin** [comment]
replaced by #714.
