### ISSUE TITLE
Configurable SecretStr

### ISSUE THREAD

**Issue by jasonkuhrt** [samuelcolvin/pydantic#596]
This issue revisits this comment https://github.com/samuelcolvin/pydantic/issues/462#issuecomment-480326378 by @tiangolo.

I think it would be a good idea that there is a standard way of getting secrets exported for propagation to other services.

This is not something that tends to happen in three tier apps where e.g. the db creds are secret but rather a case that happens _a lot_ when dealing with microservice architectures wherein request payloads may serialize and deserialize multiple times through the end to end request lifecycle.

`.json()` to me is semantically like `.export` and as such defaulting to revealing secret makes sense. But that would be a breaking change.

Other approaches:

- `.json(reveal_secrets=True)`
- `.export()`

But maybe we can take the breaking change path via https://github.com/samuelcolvin/pydantic/issues/576 and then:

- `.json(keep_secrets=True)`

To be clear I don't see `.json` as being something used for logging. Something like `structlog` would work with `pydantic.dict()` instead:

```
log.info('something', data=model.dict())
```

I _think_ `.dict` defaulting to maintaining secrets seems right. But we could have, too:

```
log.info('something', data=model.dict(reveal_secrets=True))
```

But than we should make considerations around API consistency across methods and ensure usability is good overall, not just per case.

**Comment by samuelcolvin** [comment]
I think this is unnecessary.

The purpose of `SecretStr` is questionable anyway, or rather, it has relatively few useful applications. The environment in which you're processing "secret" values has to be trusted, so why not just use `str`?

Given this I think it's overkill to add another argument to `dict()` (and associated methods) and then pass the setting around recursively.

You can accomplish the same thing with your own custom encoder very easily:

```py
from pydantic import BaseModel, SecretStr
from pydantic.json import pydantic_encoder

def custom_encoder(obj):
    if isinstance(obj, SecretStr):
        return obj.get_secret_value()
    else:
        return pydantic_encoder(obj)

class Model(BaseModel):
    password: SecretStr = None

    def json(self) -> str:
        return super().json(encoder=custom_encoder)

print(Model(password='testing').json())
```

If you really wanted you could use your own custom `BaseModel` that adds another keyword argument `reveal_secrets=False` to `json()` and uses the above encoder if `reveal_secrets=True`.

**Comment by jasonkuhrt** [comment]
> The environment in which you're processing "secret" values has to be trusted, so why not just use str

For example it can be a breach of data policy to log patient identifiable information. The trust levels between a tightly controlled internal database and, say, an external service Datadog, are far from equal.

**Comment by samuelcolvin** [comment]
ok, I still think the above `enoder` solution would be best.

**Comment by jasonkuhrt** [comment]
@samuelcolvin cool, and thanks for hearing the case out.

**Comment by samuelcolvin** [comment]
It occurs to me that we could use parameterised types eg. `SecretStr['json']` or as a function `SecretStr(json=True)`, like we do for `constr` but I'm not sure it's worth it.

**Comment by jasonkuhrt** [comment]
@samuelcolvin oooh... I love that. Controlling the secret string semantics at the field level seems great 😅

**Comment by jasonkuhrt** [comment]
@samuelcolvin between `SecretStr(json=True)` and `SecretStr['json']` the former, function form, seems most clear and extensible. The latter would be confusing to me.

**Comment by samuelcolvin** [comment]
The only reason for `SecretStr['json']` is that it wouldn't upset mypy, but maybe that's a minor concern.

**Comment by jasonkuhrt** [comment]
General comment: I think it wouldn't hurt to get more use-case feedback before making a call on the nuances of the api, if any, like you said:

> but I'm not sure it's worth it.

If it is worth it, though, your field-based approach is clearly the way forward I think.

**Comment by samuelcolvin** [comment]
I've asked for feedback on lots of issues (see the "feedback" label), very few people (compared to the number of stars, projects using pydantic or downloads) give feedback.

**Comment by jasonkuhrt** [comment]
Me being too utopian :D

**Comment by jasonkuhrt** [comment]
@samuelcolvin shall we re-open this issue with a new title, maybe `Configurable SecretStr`?

**Comment by haizaar** [comment]
Just bumped into this... Tried to use SecretStr to store token data, but then discovered that I can't render it to JSON model and return to client (e.g. during login). 

It will be great to have `SecretStr['json']` and `SecretStr[json=True]` which will cause `model.json()` to include the secret but omit it from model's `repr()` and `str()` when logging it.

P.S. Speaking of feedback :)

**Comment by Atheuz** [comment]
@samuelcolvin
I'm looking into implementing this, but it's been a while since I've looked at the pydantic  library itself and how things are implemented so I wanted to ask before I proceed:

Is there any example of a type that is output differently using the `json()` call when compared to `repr()` or `str()`, and if so how is that specified in the library?

More generally: How would you like to see this be implemented?

It looks like the Color type maybe does something like it:

```py
import pydantic
from pydantic.color import Color

class Config(pydantic.BaseModel):
    a: pydantic.SecretStr
    b: pydantic.PaymentCardNumber
    c: pydantic.ByteSize
    d: Color

def main():
    c = Config(a="abc", b=4065972557141631, c=52000, d='hsl(180, 100%, 50%)')
    print(str(c))
    print(repr(c))
    print(c.json())

if __name__ == '__main__':
    main()
```

=>

```
a=SecretStr('**********') b='4065972557141631' c=52000 d=Color('cyan', rgb=(0, 255, 255))
Config(a=SecretStr('**********'), b='4065972557141631', c=52000, d=Color('cyan', rgb=(0, 255, 255)))
{"a": "**********", "b": "4065972557141631", "c": 52000, "d": "cyan"}
```

**Comment by samuelcolvin** [comment]
I think the solution is to wait until I implement customised serialisation.

I'm hoping to work on it fairly soon.

**Comment by Atheuz** [comment]
@samuelcolvin I saw the json_encoders option that you can add:
```py
import pydantic
from pydantic.color import Color

class Config(pydantic.BaseModel):
    a: pydantic.SecretStr
    b: pydantic.PaymentCardNumber
    c: pydantic.ByteSize
    d: Color

    class Config:
        json_encoders = {
            pydantic.SecretStr: lambda v: v.get_secret_value(),
        }

def main():
    c = Config(a="abc", b=4065972557141631, c=52000, d='hsl(180, 100%, 50%)')
    #print(c.__dict__.items())
    print(str(c))
    print(repr(c))
    print(c.json())

if __name__ == '__main__':
    main()
```
=>
```
a=SecretStr('**********') b='4065972557141631' c=52000 d=Color('cyan', rgb=(0, 255, 255))
Config(a=SecretStr('**********'), b='4065972557141631', c=52000, d=Color('cyan', rgb=(0, 255, 255)))
{"a": "abc", "b": "4065972557141631", "c": 52000, "d": "cyan"}
```

Isn't this good enough?

**Comment by samuelcolvin** [comment]
Yes that's a temporary solution, but not how it should look long term.

**Comment by Atheuz** [comment]
Would it be worthwhile to add the json_encoders bit to the to the documentation example code for SecretStr and SecretBytes or would you rather just wait until you're working on customised serialisation?

**Comment by samuelcolvin** [comment]
Or we could fix this but editing [`pydantic_edcoder`](https://github.com/samuelcolvin/pydantic/blob/e3243d267b06bda2d7b2213a8bad70f82171033c/pydantic/json.py#L43), that would be a better temporary solution.

**Comment by Atheuz** [comment]
@samuelcolvin Made a PR, at #1313

**Comment by Atheuz** [comment]
@samuelcolvin made a different PR, at #1328 that just documents an approach to make it plain-text dumpable using the json method.

**Comment by roma-glushko** [comment]
This conversation was based mainly around `json()` method. I personally use rarely/have seen few cases where `json()` was needed tbh, but `dict()` is whole another story.

Here is what I mean:

```python
import datetime
import logging

from fastapi import APIRouter
from pydantic import BaseModel, SecretStr

router: APIRouter = APIRouter()

logger = logging.getLogger(__name__)

class ApiKey(BaseModel):
    name: str
    created_at: datetime.datetime
    access_token: SecretStr
    refresh_token: SecretStr
    scopes: list[str]

async create_api_key(user_id: str) -> ApiKey:
    # doing something to get info for ApiKey model
    # ...
    data = await request(user_id)

    # check for errors

    api_key: ApiKey = ApiKey(**data.json())

    logger.debug(
        "API has been obtained",
        extra={
            "user_id": user_id,
            "api_key": api_key.dict() # I don't to reveal secrets here, masked values are just fine
        }
    )
    
    return api_key
    
@router.post("/api/{user_id}")
async def create_api_key(
        user_id: str
        # ...
) -> ApiKey:
    return await create_api_key(user_id)  # I do want to reveal secrets here, because they are needed by upstream microservice

```

In that case, `ApiKey` is a simple "plain" model, but also could imagine having nested models with SecretStr fields. 

In those cases, I don't think that the encoder is the answer really, so I'm curious what @samuelcolvin thinks about it.

**Comment by blerrgh** [comment]
This discussion is a bit old, but I second @roma-glushko that dict() often needs to be able to export secrets.

Being able to use `model.dict(reveal_secrets=True)` or similar would be super useful for me.

A field level function option `SecretStr(dict=True)` would work okay, but for my use cases it would be more valuable to be able to decide if secrets are revealed or not per dict() call, much like the example above.
