### ISSUE TITLE
List[Tuple[str, str]] not validated correctly

### ISSUE THREAD

**Issue by greyltc** [samuelcolvin/pydantic#597]
If I write:
```
from pydantic.dataclasses import dataclass
from dataclasses import field
from typing import List, Tuple


class MyConfig:
    validate_assignment = True
    arbitrary_types_allowed = True


@dataclass(config=MyConfig)  # type: ignore
class Cell():
    user_vars: List[Tuple[str, str]] = field(default=None)

c = Cell()
```

Now I expect that `c.user_vars = [(True,14)]` should raise a datatype validation error because neither `True` nor `14` are strings, but that assignment works fine.

**Comment by dmontagu** [comment]
This is expected behavior -- if you just annotate with `str`, it will cast the inputs to string if possible.

If you want it to disallow non-string inputs, change `str` to `pydantic.StrictStr`.

I confirmed that this version of your code raises the expected errors:

```python
from dataclasses import field
from typing import List, Tuple

from pydantic import StrictStr
from pydantic.dataclasses import dataclass


class MyConfig:
    validate_assignment = True
    arbitrary_types_allowed = True


@dataclass(config=MyConfig)  # type: ignore
class Cell():
    user_vars: List[Tuple[StrictStr, StrictStr]] = field(default=None)


c = Cell()

c.user_vars = [(True, 14)]
"""
pydantic.error_wrappers.ValidationError: 2 validation errors
user_vars -> 0 -> 0
  str type expected (type=type_error.str)
user_vars -> 0 -> 1
  str type expected (type=type_error.str)
"""

```

**Comment by samuelcolvin** [comment]
also no need for `field(default=None)` this is incorrect usage.. Has someone suggested that somewhere? It should be corrected.

**Comment by greyltc** [comment]
Thanks for the clarification!

@samuelcolvin What's incorrect about ` = field(default=None)`? Do you just mean it's not needed because it's shorter to just do ` = None`?
Is ` = field(default=None, metadata={"color": "purple"})` also incorrect then? Because that's what I'm actually doing, I just left out the metatata kw in this example because it's unrelated.

**Comment by samuelcolvin** [comment]
Oh, sorry I missed what you were doing, I thought you were using `pydantic.fields.Field`. Ignore me.

Probably because I was thinking about #577.
