### ISSUE TITLE
Map string value to int

### ISSUE THREAD

**Issue by krzysieqq** [samuelcolvin/pydantic#598]
Hi,
I have field that should contains only specific string e.g.:
race: ['Men', 'Women', 'Unknown Race',]
I need to map this values after validation to Int 
'Men' = 0
'Women' = 1
'Unknown Race' = 3

It should be something like below but I know that's doesn't work
```py
from pydantic import BaseModel

class GenderEnum(IntEnum):
    'Men' = 0
    'Women' = 1
    'Unknown Race' = 2

class CheckGenderModel(BaseModel):
    gender: GenderEnum
    class Config:
        use_enum_values=True

person = CheckGenderModel(**{'gender': 'male'})
person.gender = 1 
```
Thanks for help and have a nice day :)

@edit
As a small workaround I could check it like below but I don't think it's best way
```py
from pydantic import BaseModel, conint, validator

class CheckGenderModel(BaseModel):
    gender: conint(ge=0, le=2)

    @validator('gender', pre=True)
    def check_gender(cls, value):
        gender = {
            'Male': 0,
            'Female': 1,
            'Unknown Race': 2,
        }

        if value and value in gender.keys():
            return gender[value]
        else:
            raise ValueError('gender should be one of these values: ' + ', '.join(gender.keys()))
```

**Comment by dmontagu** [comment]
try:
```python
from enum import Enum

class GenderEnum(Enum):
    male = "Men"
    female = "Women"
    unknown = "Unknown Race"
```
(The right side of the equals signs should be the strings you want to match, if they are different.)

I think that will accomplish what you are trying to accomplish here. If you need to map those strings to specific numbers, you have to do that separately -- pydantic parses the enum by looking for the values, not the keys.

The left hand side of the `=` has to have valid python variable identifiers, so you can't use a string like `'Unknown Race'` like you had in your first version.

**Comment by samuelcolvin** [comment]
Really enjoying the idea that men and women are races.

@krzysieqq you idea of a work around is good, except you can do it slightly more elegantly:

```
gender_lookup = {'Male': 0, 'Female': 1, 'Unknown Race': 2}

class CheckGenderModel(BaseModel):
    gender: int

    @validator('gender', pre=True)
    def check_gender(cls, value):
        try:
            return gender_lookup[value]
        except KeyError:
            raise ValueError('gender should be one of these values: ' + ', '.join(gender_lookup))
```

If on the other hand the input values are valid python identifiers, you could instead do something like

```py
class Choices(int, Enum):
    anne = 1
    ben = 2
    charlie = 3
    dave = 4

    @classmethod
    def __get_validators__(cls):
        cls.lookup = {v: k.value for v, k in cls.__members__.items()}
        yield cls.validate

    @classmethod
    def validate(cls, v):
        try:
            return cls.lookup[v]
        except KeyError:
            raise ValueError('invalid value')

class Model(BaseModel):
    choice: Choices

debug(Model(choice='charlie'))
```

**Comment by krzysieqq** [comment]
Thx :)

**Comment by mmoerdijk** [comment]
```python
class Choices(int, Enum):
    anne = 1
    ben = 2
    charlie = 3
    dave = 4

class Model(BaseModel):
    choice: Choices
    @pydantic.validator('choice', pre=True)
    def validate_choice(cls, value):
        try:
            return Choices[value]
        except KeyError as e:
            raise ValueError(f"Error validating choice: {e}")
```

**Comment by mmoerdijk** [comment]
This alternative also works and does not require modifications to the enum:

```python
class Choices(int, Enum):
    anne = 1
    ben = 2
    charlie = 3
    dave = 4

class Model(BaseModel):
    choice: Choices
    @pydantic.validator('choice', pre=True)
    def validate_choice(cls, value):
        try:
            Choices[value]
        except KeyError as e:
            raise ValueError(f"Error validating choice {e}")
```

**Comment by e-compagno** [comment]
@mmoerdijk your solution has a small typo as it should be `[c.name for c in Choices]`.

However both solutions seem not to provide the right schema: `Model.schema()` produces

```
{'title': 'Model',
 'type': 'object',
 'properties': {'choice': {'$ref': '#/definitions/Choices'}},
 'required': ['choice'],
 'definitions': {'Choices': {'title': 'Choices',
   'description': 'An enumeration.',
   'enum': [1, 2, 3, 4],
   'type': 'integer'}}}
```

while the `enum` should show as allowed values `["anne",  "ben",  "charlie",  "dave"]`

**Comment by llk2why** [comment]
> 

Hi, @samuelcolvin, It seems this code use the v1.x APIs, I want to implement it with the 2.x version [__get_pydantic_core_schema__](url:https://docs.pydantic.dev/latest/usage/types/custom/#customizing-validation-with-__get_pydantic_core_schema__), but I failed to figure out how to use it properly, could you implement a 2.x Api version.

**Comment by elidchan** [comment]
I have posted a V2 solution that enables serialization/deserialization of enums using their names (see above)

However, as with the V1 solutions, the `schema()` is still incorrect, which impacts the OpenAPI docs generated by FastAPI.
