### ISSUE TITLE
Different default behavior between serialization and de-serialization is error prone

### ISSUE THREAD

**Issue by wouterdb** [samuelcolvin/pydantic#602]
Feature Request

```py
import pydantic
    
class Project(pydantic.BaseModel):
    source: str
    validate_: bool = False

    class Config:
        # validate is not a valid field name, because BaseModel has a validate method
        # use alias so we can use a validate field in the json and validate_ in python
        fields = {"validate_": {"alias": "validate"}}

def roundtrip(project_in: Project) -> None:
    """Convert to json and back """
    project_out = Project(**project_in.dict())
    print(f"input: {project_in.validate_}, output: {project_out.validate_}")

projectt = Project(source="test", validate=True)
roundtrip(projectt)

projectf = Project(source="test", validate=False)
roundtrip(projectf)
```
this results in 

```
input: True, output: False
input: False, output: False
```

due to the constructor using aliases by default, but `dict` doesn't use aliasses by default

It would be better if the deafults were the same, so that the round trip code works as expected. 
see also https://inmanta.com/2019/06/18/pydantic-puzzlers/

**Comment by samuelcolvin** [comment]
You're not the first to ask about this, it's exactly what [`allow_population_by_alias`](https://pydantic-docs.helpmanual.io/#model-config) was designed to fix.

**Comment by samuelcolvin** [comment]
> My guess is that this asymmetry is a historical accident that has grown into the code and is very hard to change now, as it will break a lot of people’s code.

Not an accident at all, aliases are often really useful. Other libraries eg. rust's serde-json has similar concepts.

If you want no asymmetry, you can use `project_in.dict(by_alias=True)`.

**Comment by wouterdb** [comment]
I agree that having both the ability to use or not use aliases is very useful, the confusing thing is that the default behavior is opposite.
