### ISSUE TITLE
Using a custom contructor

### ISSUE THREAD

**Issue by LennyPenny** [samuelcolvin/pydantic#605]
I'm trying to add a custom custructor to my pydantic mode, however it doesn't seem to work. 

Python Version: 3.7.3

Example code: 
```python
from pydantic import BaseModel


class Test(BaseModel):
    def __init__(self, **kwargs):
        super().__init__(self, *kwargs)
        self.__test_field = "test"


Test()
```

Could you send me working version?

**Comment by samuelcolvin** [comment]
Please take the time to review you code before asking trivial questions.

You can't assign to attributes of a model which haven't been defined.

But the following works fine.

```py
from pydantic import BaseModel

class Test(BaseModel):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        print('hello')

Test()
```
