### ISSUE TITLE
Possible to make dynamic models with required fields?

### ISSUE THREAD

**Issue by gtalarico** [samuelcolvin/pydantic#614]
Hi and thanks for your work in this library, I am really enjoying it.

# Question

Is there a way to make fields in dynamic model required?
Seems like they are always set with a type + default value. I tried all options.

For bugs/questions:
* Pydantic version: `0.25`

Where possible please include a self contained code snippet describing your 
bug, question, or where applicable feature request:

```py

from pydantic import BaseModel, create_model

class TestBase(BaseModel):
    x: int

TestDynamic = create_model('TestDynamic',  x=(int,0))
TestDynamic2 = create_model('TestDynamic',  x=0)
TestDynamic3 = create_model('TestDynamic',  x=int)

>>> TestBase.__fields
{'x': <Field(x type=int required)>}

>>> TestDynamic.__fields__
{'x': <Field(x type=int default=0)>}
>>> TestDynamic2.__fields__
{'x': <Field(x type=int default=0)>}
>>> TestDynamic3.__fields__
{}

...
```

**Comment by samuelcolvin** [comment]
Entirely possible, use an ellipsis `...`

**Comment by gtalarico** [comment]
Thanks @sam-bristow . I appreciate the help 🤝 !
