### ISSUE TITLE
Type Hint for create_model

### ISSUE THREAD

**Issue by gtalarico** [samuelcolvin/pydantic#615]
# Question/Bug ?

* Python version `3.7.3`
* Pydantic version: `0.28`

Type Hint for `create_model` seems to be missing, and fails with Fast API.

In the code below, when I hover over over `t1` my editor shows (`t1: Test`).
When I hover over `t2` I get no type.
(vscode with mypy)

I found [this issue](https://github.com/samuelcolvin/pydantic/issues/525) which added the type hint, but for some reason it doesn't seem to be working for me. 

I then use those as models with Fast API, and again the dynamic class fails type checks.

```py
from pydantic import BaseModel, create_model, ValidationError
from fastapi import FastAPI, Body

# Base Model
class Test(BaseModel):
    x: int


# Dynamic Model
TestDynamic = create_model('TestDynamic', x=0)

t1 = Test(x=1) # hover shows `t1: Test`
t2 = TestDynamic(x=1) # hover  shows no type

app = FastAPI()

# Passes
@app.post("/points/", response_model=Test)
def create_test_1(test_obj: Test):
    return test_obj

# Fails: mypy: invalid type TestDynamic
@app.post("/points/", response_model=TestDynamic)
def create_test_2(test_obj: TestDynamic):
    return test_obj

...
```

Thanks in advance, and I am sorry if I missing something basic. 
I am just starting to learn python typing.

## Screenshots

![Screen Shot 2019-06-21 at 2 07 14 PM](https://user-images.githubusercontent.com/9513968/59951473-e486f600-942d-11e9-8c46-a82869e26d21.png)

![image](https://user-images.githubusercontent.com/9513968/59951513-01232e00-942e-11e9-9b53-ddd6395923fb.png)

**Comment by dmontagu** [comment]
I don't believe this is a bug; rather, it is related to dynamic typing. While mypy can make use of `Type[...]` as a type hint for the sake of, e.g., functions expecting a type as an argument, it doesn't currently allow variables to be used as annotations due to challenges with dynamic types. This is discussed more in this issue:
https://github.com/python/mypy/issues/3494 

As a workaround, you can do:
```python
if typing.TYPE_CHECKING:
    TestDynamic = BaseModel  # this is an alias, so mypy is okay with it
else:
    TestDynamic = create_model("TestDynamic", x=0)  # this is a variable, so mypy is not okay if you use it as an annotation
```

**Comment by indigoviolet** [comment]
^ the workaround above is worth including in the `create_model` docs, it's pretty hard to find

**Comment by cj** [comment]
@dmontagu @indigoviolet I just ran into this, but how do you do it with multiple BaseModel's joined as one? i.e.:

```python
if TYPE_CHECKING:
    AddressDetailsModel = AddressCoords, AddressGeoPolygonAndImageModel
else:
    AddressDetailsModel = create_model("AddressDetailsModel", __base__=(AddressCoords, AddressGeoPolygonAndImageModel))
```

**Comment by tcztzy** [comment]
Personally, I use `inspect` and `ast` to generate code and write to `_generated_types.py` to make linter happy.

**Comment by alercelik** [comment]
> @dmontagu @indigoviolet I just ran into this. How do you do it with multiple BaseModel's joined as one?
> 
> i.e.:
> 
> ```python
> if TYPE_CHECKING:
>     AddressDetailsModel = AddressCoords, AddressGeoPolygonAndImageModel
> else:
>     AddressDetailsModel = create_model("AddressDetailsModel", __base__=(AddressCoords, AddressGeoPolygonAndImageModel))
> ```

Use type union feature
if TYPE_CHECKING:
    AddressDetailsModel = AddressCoords | AddressGeoPolygonAndImageModel
else:
    AddressDetailsModel = create_model("AddressDetailsModel", __base__=(AddressCoords, AddressGeoPolygonAndImageModel))
```python

**Comment by mecampbellsoup** [comment]
> Personally, I use `inspect` and `ast` to generate code and write to `_generated_types.py` to make linter happy.

Like this idea. Could you show an example of your workflow please?
