### ISSUE TITLE
Possible to give a more useful error message on partial type?

### ISSUE THREAD

**Issue by therefromhere** [samuelcolvin/pydantic#623]
# Feature Request

Is it possible to give a more useful error message on partial type?

I think my code here is incorrect because I've not specified the parameters to `typing.Dict`, but would it be possible for this to give a more useful error message than "TypeError: issubclass() arg 1 must be a class"?

```py
from typing import Any, Dict

import pydantic
from pydantic.schema import model_schema

class Foo(pydantic.BaseModel):
  d: Dict
  # should be
  # d: Dict[Any, Any]
  
model_schema(Foo)
```
```
TypeError: issubclass() arg 1 must be a class
```

**Comment by samuelcolvin** [comment]
The solution is to allow naked `Dict` and treat it like `dict`.

This was referenced at https://github.com/samuelcolvin/pydantic/issues/545#issuecomment-495943391

PR welcome to fix this.

**Comment by drunkwcodes** [comment]
I think it is sufficient to give better error message in `validator.py` as #545 mentioned by now because the #625 should be dropped.

**Comment by samuelcolvin** [comment]
why should #625 be dropped?

**Comment by drunkwcodes** [comment]
It should be dropped when missing parameters is probably an error.
The usual cases for `Dict` parameters are `Dict[str, str]` or `Dict[str, Union[...]]`.

IMO it is better to raise exception to notice developers that there is a undetermined type.

**Comment by samuelcolvin** [comment]
that's not consistent with python standard library or with mypy which accepts unparameterised generics when `disallow_any_generics` is False.

**Comment by drunkwcodes** [comment]
I'm convinced by the option and the semantic error which claims "everything is object in the json schema" in that PR test.
