### ISSUE TITLE
@validator checks if method is already used which does not play nice with create_model

### ISSUE THREAD

**Issue by hmvp** [samuelcolvin/pydantic#626]
# Bug

For bugs/questions:
* OS: not relevant
* Python version `import sys; print(sys.version)`: 3.7.3
* Pydantic version `import pydantic; print(pydantic.VERSION)`: master

Two issues with the same origin:

We use something like this
```py
import pydantic

def generate_validator(key):
    def validator(v, values):
            value = values[key]
            if value == v:
                raise ValueError()
    return validator

def create_validation_model():
    whole_validators = {
        "validator_for_xxx": pydantic.validator("some field")(generate_validator("xxx"))
        "validator_for_yyy": pydantic.validator("some field")(generate_validator("yyy"))
    }
    fields = ...
    return pydantic.create_model("Something", *fields, __validators__=whole_validators)
```
This fails because the second call to `pydantic.validator` does a check on `f.__qualname__` which is the same for both functions even though they are different validators and the way we give them to `create_model` ensures uniqueness on the class.

As a workaround I can set `__qualname__` on the generated function but that seems a bit weird and I am not sure if that does not have unintended consequences. 

Second issue is that when calling `create_validation_model` for the second time it fails regardless. As a workaround I added `pydantic.class_validators._FUNC = set()` to the beginning of that function. Again not really what I would like to do

**Comment by samuelcolvin** [comment]
you're using `__validator__` not `__validators__`, I wonder if that's part of the problem?

**Comment by hmvp** [comment]
Ah that was a typo, I am using `__validators__`

**Comment by hmvp** [comment]
The issue is the check in @validator `class_validators.py` line 53-57

**Comment by samuelcolvin** [comment]
links are useful

https://github.com/samuelcolvin/pydantic/blob/ccdf8e12cd59f92e0fc362e7485c09918b1b5cac/pydantic/class_validators.py#L53-L57

**Comment by samuelcolvin** [comment]
Should be fixable, PR welcome, in the meantime, something like this works fine:

```py
import pydantic
from devtools import debug

def generate_validator(field, key):
    def validator(v, values):
        if key not in v:
            raise ValueError('!')
        return v

    validator.__qualname__ = 'validate_' + field
    return pydantic.validator(field)(validator)

def create_validation_model():
    whole_validators = {
        'validator_for_foo': generate_validator('foo', 'xxx'),
        'validator_for_bar': generate_validator('bar', 'yyy'),
    }
    fields = {'foo': (str, ...), 'bar': (str, ...)}
    return pydantic.create_model('MyModel', **fields, __validators__=whole_validators)

m = create_validation_model()
debug(m, m(foo='xxx thing', bar='yyy thing'))
debug(m(foo='xxx thing', bar='yy thing'))
```

**Comment by hmvp** [comment]
Yes that is my current workaround. However calling create_validation_model a second time also fails. The workaround for that is resetting `_FUNCS`

**Comment by hmvp** [comment]
I suspect the new allow_reuse parameters solves this issue.

**Comment by hmvp** [comment]
Can confirm that #941 with adding `allow_reuse` fixes my issue
