### ISSUE TITLE
Parse string to json/dictionary

### ISSUE THREAD

**Issue by GetCurious** [samuelcolvin/pydantic#631]
# Question
How do i parse `"user_cred": "{\"user_id\": \"13\"}"` **?**

from [https://github.com/samuelcolvin/pydantic/issues/133](url)
Tried so far...
```
class Model(BaseModel):
    ...
    user_cred: Json[Dict[str,int]]
    ...
```

Error:
`  JSON object must be str, bytes or bytearray (type=type_error.json)`

Expected when called:
```
{
...
user_cred: { user_id: 12},
...
}
```

**Comment by samuelcolvin** [comment]
works fine for me, your JSON was invalid. 

```py
from typing import Dict
from pydantic import BaseModel, Json

class Model(BaseModel):
    user_cred: Json[Dict[str, int]]

print(Model(user_cred='{"user_id": 123}'))
```

Questions like this are a waste of time, please check your code before creating them.
