### ISSUE TITLE
The validator of the type hints classes are evaluated with apparently weird input

### ISSUE THREAD

**Issue by devtud** [samuelcolvin/pydantic#635]
Bug or Question

* OS: **Debian**
* Python version `import sys; print(sys.version)`: **3.7.2**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **0.29**

Hi,

I work with some models and below I tried to simplify the idea:

```py
class Parent(BaseModel):
    siblings: List[Parent]

    @validator('siblings', whole=True, pre=True)
    def validate_siblings(cls, siblings):
        ...

class Child1(Parent):
    siblings: List[Union[Child2, Child3]]

class Child2(Parent):
    siblings: List[Union[Child3, Child5, Child6]]

.....
```

Note that the parent validator may be overwritten or not, it doesn't matter in this situation.

When a `Child2` is instantiated (with `siblings=[child6_obj]` for example) --> the validator is called for the `Child2` class. The problem is that all the validators for the possible `Child2.siblings` types are also evaluated (which are `Child3, Child5, Child6`). And from my debugging, they are called with `child_obj.dict()`, so `validate_siblings` validator receives a list of `dict`s as param even if the `Child2` object is instantiated with a list of objects (`siblings=[child6_obj]`).

In my case, the validator of `Child3` will raise an error.

First of all, Is this the correct behavior? 

Secondly, do you spot any bad practice/idea in my snippet?

--- EDIT

Some more details about `def validate_siblings(cls, siblings)` implementation:
- the main purpose of the method is to check the types of items inside `siblings` param (which is a list)
- so, for example, when `Child1` is instantiated (`c = Child1(siblings=[obj1, obj2])`), I expect the validator is called with `[obj1, obj2]`, and its logic is to check if both objects in the list are instances of `Child2` or `Child3`. I achieve this by looking in `Child1.__annotations__`.
- to reiterate, I don't expect a `dict` in `validate_siblings` validator, but only the objects I use in my code. Maybe I didn't understand how validators work and what are the situations in which they are called/evaluated.

**Comment by samuelcolvin** [comment]
Humm, your example is fairly complicated so I'm trying to build a minimum viable demonstration of the problem.

I tried the following

```py
from typing import List
from devtools import debug

from pydantic import BaseModel, validator

class Foo(BaseModel):
    v: int

class Bar(BaseModel):
    foo: List[Foo]

    @validator('foo', pre=True, whole=True)
    def validate_foo(cls, v):
        debug(v)
        return v

foo1 = Foo(v=1)
foo2 = Foo(v=2)
bar = Bar(foo=[foo1, foo2])
debug(bar)
```
But it outputs
```
test.py:14 validate_foo
    v: [
        <Foo v=1>,
        <Foo v=2>,
    ] (list) len=2
test.py:20 <module>
    bar: <Bar foo=[<Foo v=1>, <Foo v=2>]> (Bar)
```

Which I think is correct. Could you expand on this example so it's a concrete demonstration of the problem?

**Comment by devtud** [comment]
Thank you for replying @samuelcolvin.

I understand that indeed the problem becomes more clear if a running code is attached, so here I slimmed my real code while keeping the issue.

```py
from __future__ import annotations

from typing import List, Union

from devtools import debug
from pydantic import BaseModel, validator


class Tag(BaseModel):
    siblings: List[Union[Tag, str]]

    @validator('siblings', pre=True, whole=True)
    def validate_siblings(cls, siblings):
        debug(siblings)
        assert isinstance(siblings[0], (Tag, str)), f'Got type {type(siblings[0])}'
        return siblings


Tag.update_forward_refs()


class FooterTag(Tag):
    siblings: List[str]


class ATag(Tag):
    siblings: List[str]


ATag.update_forward_refs()


class LiTag(Tag):
    siblings: List[Union[ATag, str]]


LiTag.update_forward_refs()


class UlTag(Tag):
    siblings: List[LiTag]


UlTag.update_forward_refs()


class SectionTag(Tag):
    siblings: List[Union[FooterTag, UlTag, str]]


SectionTag.update_forward_refs()

if __name__ == '__main__':
    section_tag = SectionTag(siblings=[
        UlTag(siblings=[
            LiTag(siblings=['oops'])
        ])])
    debug(section_tag)
```

Please note in the output below the assertion error. That `dict` is my problem.

```
test.py:14 validate_siblings
Traceback (most recent call last):
    siblings: ['oops'] (list) len=1
test.py:14 validate_siblings
    siblings: [
  File "./test.py", line 56, in <module>
        <LiTag siblings=['oops']>,
    LiTag(siblings=['oops'])
    ] (list) len=1
  File "pydantic/main.py", line 246, in pydantic.main.BaseModel.__init__
test.py:14 validate_siblings
  File "pydantic/main.py", line 642, in pydantic.main.validate_model
    siblings: [
  File "pydantic/fields.py", line 303, in pydantic.fields.Field.validate
        <UlTag siblings=[<LiTag siblings=['oops']>]>,
  File "pydantic/fields.py", line 335, in pydantic.fields.Field._validate_sequence_like
    ] (list) len=1
test.py:14 validate_siblings
  File "pydantic/fields.py", line 422, in pydantic.fields.Field._validate_singleton
    siblings: [
        {
  File "pydantic/fields.py", line 296, in pydantic.fields.Field.validate
            'siblings': ['oops'],
        },
  File "pydantic/fields.py", line 422, in pydantic.fields.Field._validate_singleton
    ] (list) len=1
  File "pydantic/fields.py", line 296, in pydantic.fields.Field.validate
  File "pydantic/fields.py", line 429, in pydantic.fields.Field._validate_singleton
  File "pydantic/fields.py", line 436, in pydantic.fields.Field._apply_validators
  File "pydantic/class_validators.py", line 202, in pydantic.class_validators._generic_validator_basic.lambda11
  File "pydantic/main.py", line 454, in pydantic.main.BaseModel.validate
  File "pydantic/main.py", line 455, in pydantic.main.BaseModel.validate
  File "pydantic/main.py", line 246, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 642, in pydantic.main.validate_model
  File "pydantic/fields.py", line 291, in pydantic.fields.Field.validate
  File "pydantic/fields.py", line 436, in pydantic.fields.Field._apply_validators
  File "pydantic/class_validators.py", line 169, in pydantic.class_validators._generic_validator_cls.lambda2
  File "./test.py", line 15, in validate_siblings
    assert isinstance(siblings[0], (Tag, str)), f'Got type {type(siblings[0])}'
AssertionError: Got type <class 'dict'>
```

**Comment by romeo1m** [comment]
Just a note that this still happens in **v0.30**.

**Comment by samuelcolvin** [comment]
yes, I haven't fixed it yet :-)

PR welcome, otherwise I'll look when I get a chance.

**Comment by samuelcolvin** [comment]
I think this is fixed in v1, comment here or create a new issue if I'm wrong.
