### ISSUE TITLE
Allow arbitrary content types when deserializing

### ISSUE THREAD

**Issue by thedrow** [samuelcolvin/pydantic#64]
My data is compressed and serialized to MsgPack.
I'd like be able to use parse_raw() with my choice of compression algorithm as well.
Should I simply override parse_raw? That works as a workaround.
Kombu has a registry for serialization methods and compression methods.
Should pydantic have one as well?
Another (and in my opinion, better) alternative is to allow to pass a Deserializer object through the model's constructor.

**Comment by samuelcolvin** [comment]
Easiest just to deserialize your data and pass it straight to `parse_obj` or just to the model's constructor.

It's possible all the `parse...` methods were a distraction and shouldn't have happened.

I'm definitely not adding any arguments to a model's constructor, it should always be possible to create a model with `Model(**data)`, anything that gets in the way of that I'm opposed to

However we could add a `Serializer/Deserializer` attribute to a models so you could create a subclass of a model with serialises and deserialises in a customisable way.

I think that's still a little ugly, I would say better to have some higher level class like `API` (better name needed) which implements load, dump, error handling, OPTIONS requests etc. Does that make sense?
