### ISSUE TITLE
Request for an expedited 0.31 release to fix subclassing?

### ISSUE THREAD

**Issue by Lnaden** [samuelcolvin/pydantic#664]
# Question 

For bugs/questions:
* OS: All
* Python version `import sys; print(sys.version)`: All
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.31

I would like to request an expedited release for 0.31 to fix the subclass __init__ calling `BaseModel` from #644? I normally would not make such as request as its not an urgent rush since any release we do can pin around 0.30, but I'm weary to leave a release which alters the fundamentals of Python class inheritance imitation un-patched for long.

Thanks in advance!

**Comment by samuelcolvin** [comment]
Okay, I'm making a `v0.30.1` release now.

**Comment by Lnaden** [comment]
Awesome, thank you so much!

**Comment by samuelcolvin** [comment]
release v0.30.1 done, will be available in pypi once builds have completed, probably ~20 minutes.
