### ISSUE TITLE
Values param in validator is empty.

### ISSUE THREAD

**Issue by sharon8** [samuelcolvin/pydantic#674]
# Question | Feature Request | Bug

For bugs/questions:
* OS: **MacOS 10.13.6**
* Python version: **3.6.5 (v3.6.5:f59c0932b4)**
* Pydantic version: **0.28**

```py
from operator import attrgetter
from typing import Optional, List
from pydantic import BaseModel, Schema, EmailStr, validator


class CorporateId(BaseModel):
    type: str
    id: EmailStr

    @validator('type', pre=True, always=True)
    def verify_type_is_email(cls, v, *, values, **kwargs):
        # Need to fix a bug in data where type is not an email
        return v if '@' in v else values['id']


class SourceMoniker(BaseModel):
    primary_email: EmailStr
    raw_id: str


class ServiceProvidersData(BaseModel):
    is_admin = False  
    is_suspended: bool
    is_deleted: bool
    raw_user_id: str
    app_id: str
    additional_fields = {}
    source_moniker: SourceMoniker
    primary_identifier: EmailStr = None

    @validator('primary_identifier', pre=True)
    def populate_primary_identifier(cls, v, values):
        # populating primary_identifier when it is not populated
        return v or values['source_moniker']['primary_email']


class Identity2User(BaseModel):
    user_id: str = Schema(..., alias='_id')
    user_type: str = Schema(..., alias='_type')
    tenant_id: str
    corporate_id: List[CorporateId]
    service_providers_data: ServiceProvidersData
    sur_name: str = None
    given_name: str = None
    groups = []
    is_external: bool
    is_virtual: bool
    creation_time: PendulumDateTime
    update_time: PendulumDateTime = None
    groups_data = []
    org_unit: str = None

    @validator('service_providers_data', pre=True)
    def service_providers_data_v(cls, v) -> ServiceProvidersData:
        # service providers data structure is {<app_id>: {data}}. Adding the app_id to the data returned since
        # it is also needed
        app, res = v.popitem()
        res["app_id"] = app
        return ServiceProvidersData(**res)

    @validator('corporate_id', whole=True)
    # sorting the list to prevent comparison failures between Identity2User instances
    def sort_corporate_id(cls, v):
        return v.sort(key=attrgetter("id"))
...
```
I've tried to use this nested model (Identity2User is the one called from my code).
I have a breakpoint in the validator method "verify_type_is_email" and when it is reached I see that values is an empty dictionary.
I need to have access to the other property ("id") to populate the validated property ("type") properly.
Do you have any ideas or suggestions regarding why values is empty in this case?

An example of the data injected to the model is:
```
<class 'dict'>: {'_id': 'user_063ab1fe8663ff97a2e177e09db3', '_type': 'user', 'tenant_id': 'tenant_70e4b2a567a24159ad6b495b3620', 'corporate_id': [{'type': 'tstgo365com.onmicrosoft.com', 'id': '8klzf@tstgo365com.onmicrosoft.com'}], 'service_providers_data': {'34': {'is_suspended': False, 'is_deleted': False, 'is_external': False, 'raw_user_id': '34534a9c-36a0-4814-af66-09da9128c351', 'additional_fields': {}, 'source_moniker': {'primary_email': '8klzf@tstgo365com.onmicrosoft.com', 'raw_id': '34534a9c-36a0-4814-af66-09da9128c351'}}}, 'sur_name': '8klZF', 'given_name': 's', 'is_external': False, 'is_virtual': False, 'creation_time': 1563452402716, 'update_time': 1563452402716, 'groups_data': []}
```

**Comment by dmontagu** [comment]
The values dictionary gets built incrementally in the order the attributes are listed. Try putting the type attribute below the email attribute in the class definition and see if that fixes it.

**Comment by sharon8** [comment]
Thanks @dmontagu . This solved my issue completely.
Perhaps it should be added as a comment to the documentation of the values parameter?

**Comment by dmontagu** [comment]
@sharon8 I believe this is documented under the `Validators` heading on the docs:
> where validators rely on other values, you should be aware that:
>
>    * Validation is done in the order fields are defined, eg. here password2 has access to password1 (and name), but password1 does not have access to password2. You should heed the warning below regarding field order and required fields.
>
>    * If validation fails on another field (or that field is missing) it will not be included in values, hence if 'password1' in values and ... in this example.

Is there somewhere else you think it would be useful to include this information?

**Comment by danields761** [comment]
@dgasmith, documentation isn't clear about field ordering: looking to sources of `pydantic.main.MetaModel` you can see that annotation-only fields will be placed on first places.

**Comment by samuelcolvin** [comment]
from [here](https://pydantic-docs.helpmanual.io/#usage-mypy)

> ## Warning
> 
> Be aware that using annotation only fields will alter the order of your fields in metadata and errors: annotation only fields will always come first, but still in the order they were defined.

Please explain how you would make this sentence clearer?

**Comment by danields761** [comment]
Uups, sorry. I missed that article.

**Comment by pkerpedjiev** [comment]
> If validation fails on another field (or that field is missing) it will not be included in values

I don't get this. If validation fails on another field before the validator is called, why is the validator even called?
