### ISSUE TITLE
Feature request: include model name in ValidationError message

### ISSUE THREAD

**Issue by dmontagu** [samuelcolvin/pydantic#677]
# Feature Request

I frequently find myself scratching my head as I look at validation errors when trying to parse a nested model, since I can only see the fields that failed to be parsed. (Occasionally I share field names between models when it makes sense, but even when I don't, it still seems to take another mental step to figure out where the problem lies.)

I think it would make debugging easier if the error message included the name of the type, so that, for example (taken from the docs):
```python
class UserModel(BaseModel):
    name: str
    password1: str
    password2: str

...

try:
    UserModel(name='samuel', password1='zxcvbn', password2='zxcvbn2')
except ValidationError as e:
    print(e)
"""
2 validation errors
name
  must contain a space (type=value_error)
password2
  passwords do not match (type=value_error)
""" 
```
becomes:
```python
class UserModel(BaseModel):
    name: str
    password1: str
    password2: str

...

try:
    UserModel(name='samuel', password1='zxcvbn', password2='zxcvbn2')
except ValidationError as e:
    print(e)
"""
2 validation errors for UserModel
name
  must contain a space (type=value_error)
password2
  passwords do not match (type=value_error)
"""
```

(in particular, `2 validation errors` -> `2 validation errors for UserModel`)

I've implemented this in https://github.com/samuelcolvin/pydantic/pull/676 if the proposal is of interest.

**Comment by samuelcolvin** [comment]
:+1:
