### ISSUE TITLE
[QUESTION] Value is not valid error after updating to version 0.30

### ISSUE THREAD

**Issue by jonathanrsmjtk** [samuelcolvin/pydantic#681]
# Question 

Hello, i have a computer with specifications below:
My computer
* OS: Windows 10
* Python version : 3.7.3
* Pydantic version: 0.26 (now 0.30)

before i updated to version 0.30, my program can run my own schemas, but this error occured after updated to version 0.30:

![image](https://user-images.githubusercontent.com/49324622/61621359-05e13900-ac9d-11e9-8665-db11127c6aac.png)
 i tried to fetch all of my SQL Server data. But, if i don't use schema as my response model, like:
`@router.get("/")`
it would run successfully
any suggestions? thank you before

**Comment by samuelcolvin** [comment]
Impossible to help unless you can show the code that is causing this. 

Self constrained example would be great.

**Comment by jonathanrsmjtk** [comment]
> Impossible to help unless you can show the code that is causing this.
> 
> Self constrained example would be great.

okay, lets say my table has columns named "a", "b", "c"
and this is my schema looks like:
`from typing import List`
`import datetime`
`from pydantic import BaseModel`

`class myTableSchema(BaseModel):`
    `a:int = None`
    `b:int = None`
    `c:int = None`
 
my model to fetch data of my table:
`from sqlalchemy import Boolean, Column, ForeignKey, Integer, String, Date, DateTime, NVARCHAR, VARCHAR, Unicode, Text, Float`
`from sqlalchemy.orm import relationship`

`from app.db.database import Base`

    
`class myTable(Base):`
    `__tablename__ = "myTable"`

   ` a = Column(Integer, nullable=True, primary_key=True)`
    `b = Column(Integer, nullable=True)`
    `c = Column(Integer, nullable=True)`
i used sqlalchemy + pyodbc to connect

**Comment by samuelcolvin** [comment]
Yet ungrading to `v0.30.1` as I think this might have been fixed. Otherwise look at the changes in `__init__` and `_parse_obj`.

You also might consider using `from_orm`.

**Comment by jonathanrsmjtk** [comment]
> Yet ungrading to `v0.30.1` as I think this might have been fixed. Otherwise look at the changes in `__init__` and `_parse_obj`.
> 
> You also might consider using `from_orm`.

still error
when i tried to upgrade it succeed to upgrade with this notification:
![image](https://user-images.githubusercontent.com/49324622/61625579-45ac1e80-aca5-11e9-8435-a84aa9f82b4c.png)

this is the complete errors:
`INFO: Started server process [13388]
INFO: Waiting for application startup.
INFO: ('127.0.0.1', 53372) - "GET /myTable/ HTTP/1.1" 500
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "c:\users\jonat\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 370, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "c:\users\jonat\anaconda3\lib\site-packages\starlette\applications.py", line 133, in __call__
    await self.error_middleware(scope, receive, send)
  File "c:\users\jonat\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 122, in __call__
    raise exc from None
  File "c:\users\jonat\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 100, in __call__
    await self.app(scope, receive, _send)
  File "c:\users\jonat\anaconda3\lib\site-packages\starlette\middleware\base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File ".\app\main.py", line 16, in db_session_middleware
    response = await call_next(request)
  File "c:\users\jonat\anaconda3\lib\site-packages\starlette\middleware\base.py", line 45, in call_next
    task.result()
  File "c:\users\jonat\anaconda3\lib\site-packages\starlette\middleware\base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "c:\users\jonat\anaconda3\lib\site-packages\starlette\exceptions.py", line 73, in __call__
    raise exc from None
  File "c:\users\jonat\anaconda3\lib\site-packages\starlette\exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "c:\users\jonat\anaconda3\lib\site-packages\starlette\routing.py", line 585, in __call__
    await route(scope, receive, send)
  File "c:\users\jonat\anaconda3\lib\site-packages\starlette\routing.py", line 207, in __call__
    await self.app(scope, receive, send)
  File "c:\users\jonat\anaconda3\lib\site-packages\starlette\routing.py", line 40, in app
    response = await func(request)
  File "c:\users\jonat\anaconda3\lib\site-packages\fastapi\routing.py", line 122, in app
    skip_defaults=response_model_skip_defaults,
  File "c:\users\jonat\anaconda3\lib\site-packages\fastapi\routing.py", line 54, in serialize_response
    raise ValidationError(errors)
pydantic.error_wrappers.ValidationError: 42 validation errors
response -> 0
  value is not a valid dict (type=type_error.dict)
response -> 1
  value is not a valid dict (type=type_error.dict)
response -> 2
  value is not a valid dict (type=type_error.dict)
response -> 3
  value is not a valid dict (type=type_error.dict)
response -> 4
  value is not a valid dict (type=type_error.dict)
response -> 5
  value is not a valid dict (type=type_error.dict)
response -> 6
  value is not a valid dict (type=type_error.dict)
response -> 7
  value is not a valid dict (type=type_error.dict)
response -> 8
  value is not a valid dict (type=type_error.dict)
response -> 9
  value is not a valid dict (type=type_error.dict)
response -> 10
  value is not a valid dict (type=type_error.dict)
response -> 11
  value is not a valid dict (type=type_error.dict)
response -> 12
  value is not a valid dict (type=type_error.dict)
response -> 13
  value is not a valid dict (type=type_error.dict)
response -> 14
  value is not a valid dict (type=type_error.dict)
response -> 15
  value is not a valid dict (type=type_error.dict)
response -> 16
  value is not a valid dict (type=type_error.dict)
response -> 17
  value is not a valid dict (type=type_error.dict)
response -> 18
  value is not a valid dict (type=type_error.dict)
response -> 19
  value is not a valid dict (type=type_error.dict)
response -> 20
  value is not a valid dict (type=type_error.dict)
response -> 21
  value is not a valid dict (type=type_error.dict)
response -> 22
  value is not a valid dict (type=type_error.dict)
response -> 23
  value is not a valid dict (type=type_error.dict)
response -> 24
  value is not a valid dict (type=type_error.dict)
response -> 25
  value is not a valid dict (type=type_error.dict)
response -> 26
  value is not a valid dict (type=type_error.dict)
response -> 27
  value is not a valid dict (type=type_error.dict)
response -> 28
  value is not a valid dict (type=type_error.dict)
response -> 29
  value is not a valid dict (type=type_error.dict)
response -> 30
  value is not a valid dict (type=type_error.dict)
response -> 31
  value is not a valid dict (type=type_error.dict)
response -> 32
  value is not a valid dict (type=type_error.dict)
response -> 33
  value is not a valid dict (type=type_error.dict)
response -> 34
  value is not a valid dict (type=type_error.dict)
response -> 35
  value is not a valid dict (type=type_error.dict)
response -> 36
  value is not a valid dict (type=type_error.dict)
response -> 37
  value is not a valid dict (type=type_error.dict)
response -> 38
  value is not a valid dict (type=type_error.dict)
response -> 39
  value is not a valid dict (type=type_error.dict)
response -> 40
  value is not a valid dict (type=type_error.dict)
response -> 41
  value is not a valid dict (type=type_error.dict)`

should i downgrade my pydantic version due to this error?

**Comment by samuelcolvin** [comment]
Try that version and see if it fixes your problem.
