### ISSUE TITLE
Can we have __post_init_post_parse__ for BaseModel please?

### ISSUE THREAD

**Issue by pykong** [samuelcolvin/pydantic#691]
I am painfully missing a method on `BaseModel` which is called after parsing has finished.
Akin to `__post_init_post_parse__` which is right now only available for data classes.

Are there any plans to implement such?

**Comment by samuelcolvin** [comment]
What do you want to do there?

The simplest option now would be to override `__init__`:

```py
class MyModel(BaseModel):
    foo: int
    bar: float

    def __init__(self, **data: Any):
        super().__init__(**data)
        print('do my stuff...')
```

A few problems with that approach:
* It won't be called for `from_orm` or a few other ways of creating a model instance
* It wouldn't allow you to raise exceptions which are wrapped in a standard `ValidationError` if there are problems with the data

A couple of options:
* anther method on a model, something `post_parse` which is called after parse, allows parsing errors to be raised and adds them to a new `__all__` or `__base__` key in the error.
* a special value to `@validator` like `@validator('__after__')` which means that validator is called last.

**Comment by pykong** [comment]
@samuelcolvin Thank you for your fast and in-depth reply.

You asked:
> What do you want to do there?

Well, I am in need of the method in question to populate a dict member of my class with additional data: 
https://github.com/jpscaletti/copier/blob/901051677fe88c9559d0db65bde2ad07384163b2/copier/config/objects.py#L70

This population should always happen, representing an inherent behavior of that said class.
Hence, it being most logically to put the assignment logic in the class itself. However, it is crucial for that assignment to happened after the validation has run.

The reason being that I abuse validators to do some data transformation upfront. Namely, resolving `str` to `Paths`. (Side question: _Should we maybe introduce another decorator dedicated for data transformation versus data validation?_)

**Comment by samuelcolvin** [comment]
I think your `__init__` solution is fine. You could also add another field `folder_name: str = None` and populate it using a validator:

```py
@validator('folder_name')
def populate_folder_name(cls, v, values):
    return values.get('folder_name')
```

**Comment by pykong** [comment]
@samuelcolvin If you say the init solution is the way to go, I am fine with that.
My main concern is not to abuse `pydantic` in a way of having unintended consequences.

I am closing this.

**Comment by samuelcolvin** [comment]
great. I think that should remain fine, although I've been wrong before :-).

I think we still need `@validator('__after__')` or `@validator('__root__')` or something, but I guess that's another issue for the future.

**Comment by mezhaka** [comment]
@samuelcolvin Is this still a recommended way to do that:
```python
@validator('folder_name')
def populate_folder_name(cls, v, values):
    return values.get('folder_name')
```
it seems I get empty values when I try it.

**Comment by yasinyildiza** [comment]
@mezhaka 

First, you need to change the order of the fields; i.e., dependent field `s` should come after the field that it depends on `i`.
That's because the fields are validated in the order they are declared.
Second, since `s` is not provided while creating the model instance, its validator is never called.
To enforce it, you need to set `always=True` argument in the validator.

The following should work:

```
from pydantic import validator, BaseModel

class M(BaseModel):
    i: int
    s: str = ""
    
    @validator("s", always=True)
    def populate_s(cls, v, values):
        return str(values["i"])

m = M(i=1)
print(m)
```

**Comment by bluenote10** [comment]
The problem with the suggested `__init__` approach is that it loses that type information. For instance:

![grafik](https://user-images.githubusercontent.com/3620703/167448324-064b40e6-5376-42c4-85d1-a4be13cbbaa2.png)

But when overriding `__init__` manually that information is lost, i.e., wrong constructor calls compile (assuming `init_typed`) and autocompletion stops working.

It would be great to have a true `__post_init__(self)` exactly like dataclasses have.

**Comment by miili** [comment]
a `__post_init__(self)` would be really great!

**Comment by samuelcolvin** [comment]
Ok, we'll add it in V2.

**Comment by R0ll1ngSt0ne** [comment]
Any way to get it _before_ v2? It seems like v2 is only half of the way there :(

**Comment by fzyzcjy** [comment]
Hi, is there any backport, or when will v2 be released? This is super helpful!

**Comment by sumit-kumar2002** [comment]
2022 is over now , is v2 coming out anytime soon ?

**Comment by samuelcolvin** [comment]
In Q1.

**Comment by bswck** [comment]
This would be useful for my case either.

**Comment by teej** [comment]
This is now available in v2 as `model_post_init` ([docs](https://docs.pydantic.dev/latest/api/main/#pydantic.main.BaseModel.model_post_init)).
