### ISSUE TITLE
Do we need a decorator for data transformation?

### ISSUE THREAD

**Issue by pykong** [samuelcolvin/pydantic#693]
_Should we maybe introduce another decorator dedicated for data transformation versus data validation?_  

#### validator vs formatter
- A `validator` should conditionally raise but return the original object unaltered
- A `transformer`/`formatter` should not raise but eventually, return an altered object.

So the question is does the need for data transformation (which I suppose exist for many users and use cases) justify a new distinct functionality to separate both concerns? Or is it just bikeshedding semantics here? If indeed implemented what should the order of execution be, i.e. do we first validate then transform or vice versa?

Example:
https://github.com/jpscaletti/copier/blob/901051677fe88c9559d0db65bde2ad07384163b2/copier/config/objects.py#L73-L75

Here I abuse validators to do data transformation. It works perfectly fine. But it does not strike me as clean.

**Comment by samuelcolvin** [comment]
No, I don't think we need extra complications and overheads.

Transformation use validators is fine.

We could document it better and maybe rename the decorator.

**Comment by samuelcolvin** [comment]
Ref  #578

**Comment by pykong** [comment]
Sorry, for the duplication. Missed that.

Great. I like we are going to keep things simple, with renaming `validator` to parse.

Thanks for telling that it is not actual abuse if I use `validator` for transformation purposes!
