### ISSUE TITLE
ForwardRef and dataclasses when referencing same class

### ISSUE THREAD

**Issue by pauleveritt** [samuelcolvin/pydantic#704]
# Question

Similar to #397, I'm using Python 3.7, importing annotations, and have a dataclass with a field that stores an optional instance of the same class.

This works fine under `dataclasses.dataclass` but fails under `pydantic.dataclasses.dataclass`:

For bugs/questions:
* OS: macOS
* Python version `3.7.3 (default, Apr 20 2019, 07:46:47) `: **?**
* Pydantic version `0.31`: **?**

```py
from __future__ import annotations
from typing import Optional

from pydantic.dataclasses import dataclass


@dataclass
class Resource:
    parent: Optional[Resource] = None


print(Resource())
```

...yields:

```
pydantic.errors.ConfigError: field "parent" not yet prepared so type is still a ForwardRef, you might need to call MetaModel.update_forward_refs().
```

I can solve it by adding above the class `Resource=ForwardRef('Resource')` but `ForwardRef` is private (not in `typing.__all__`) so I get a warning.

I'll continue by suppressing the warning. Just curious if I'm approaching this wrong.

**Comment by samuelcolvin** [comment]
I don't think `ForwardRef` is private, it's definitely [documented](https://docs.python.org/3/library/typing.html#typing.ForwardRef) as something you might use, I suspect not being in `__all__` is an oversight.

You just have to call `update_forward_refs`.

```py
from __future__ import annotations
from typing import Optional

from pydantic.dataclasses import dataclass


@dataclass
class Resource:
    parent: Optional[Resource] = None

Resource.__pydantic_model__.update_forward_refs()
print(Resource())
```

We might need to update the error message to be clearer for dataclasses, PR welcome.

**Comment by pauleveritt** [comment]
Ah, it was this part that I was missing: `__pydantic_model__`. Thanks for the fast response.

**Comment by samuelcolvin** [comment]
Closing for now, but could do with better docs and/or error message if anyone is keen to do it.

**Comment by formigone** [comment]
FWIW: using `pydantic==1.9.0, python==3.8.x` in early 2022. Got that same error (although, I'm extending `pydantic.BaseModel`), but was confused because I had other models in the same module with a recursive reference, and no error had been thrown until now that I added a new model to the same module.

In my case, the issue was that the new model (`class Q`) specified a field of type `X`, where class `X` has an attribute whose value is a list of `X`. What solved my issue was defining `class X` lexically before `class Q`.

Example of broken model:

```python
from __future__ import annotations

from typing import List
from pydantic import BaseModel

class Q(BaseModel):
   group: X

class X(BaseModel):
   name: str
   children: List[X]
```

Example of working model:

```python
from __future__ import annotations

from typing import List
from pydantic import BaseModel

class X(BaseModel):
   name: str
   children: List[X]

class Q(BaseModel):
   group: X
   # By the time execution gets to this line, `X` has already
   # been defined, so things "just work"
```
