### ISSUE TITLE
Version 0.28 needed for Speckle

### ISSUE THREAD

**Issue by grootstebozewolf** [samuelcolvin/pydantic#705]
# Question | Feature Request | Bug

For bugs/questions:
* OS: **?**
* Python version `import sys; print(sys.version)`: **?**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **?**

Where possible please include a self contained code snippet describing your 
bug, question, or where applicable feature request:

```py
import pydantic

...
```

**Comment by samuelcolvin** [comment]
No details whatsoever.

Please update
