### ISSUE TITLE
Allow custom json encoder / decoder

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#714]
makes more sense, perhaps we could have `dump_json` and `load_json` attributes of `Config` which are then used in `parse_json()`, `json()` and `schema_json()` (and anywhere else we use encode/decode json that I've forgotten about).

_Originally posted by @samuelcolvin in https://github.com/samuelcolvin/pydantic/pull/599#issuecomment-516968833_

**Comment by samuelcolvin** [comment]
as discussed in #599 @pablogamboa suggested allowing a custom JSON encoder / decoder library.

This would allow libraries like orjson to be used without making them explicit dependencies of pydantic.

The problem here is going to be how to deal with the `default` argument with standard lib `json` and `orjson` allow, but not `ujson`.

**Comment by samuelcolvin** [comment]
If this requires a breaking change it should be done with the bump to version 1.

**Comment by MrMrRobat** [comment]
Did you think about implementing something similar to @JrooTJunior done in https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/utils/json.py?

**Comment by samuelcolvin** [comment]
I would prefer more like the [`json_serialize`](https://docs.aiohttp.org/en/stable/client_quickstart.html#json-request) argument in aiohttp, so the end user is responsible for implementing a function that correct encodes or decodes JSON.

**Comment by JrooTJunior** [comment]
Yes. `json_serialize` is more good way.

I want to remove this code from aiogram.
> https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/utils/json.py

**Comment by dutradda** [comment]
is anyone implementing this now?
If not, I want to implement this feature.

**Comment by samuelcolvin** [comment]
No one has started this. PR very welcome.
