### ISSUE TITLE
Consider ordering fields so **all** annotated fields come first

### ISSUE THREAD

**Issue by dmontagu** [samuelcolvin/pydantic#716]
# Feature Request

**Proposal: Change field ordering so that all annotated fields occur in order, regardless of whether they have a default value**

Various confusion seems to arise from the ordering of fields based on whether there is a default value. (See #674 #483 #203)

While it is probably unreasonably hard to determine the order of fields if allowing non-annotated fields (due to the difference between namespace and annotations), it *is* possible to at least have all annotated fields in order, ignoring the existence of default values (I made a pull request for this, #715 ).

In practice, it seems that most people are annotating all fields of their models, so, I suspect there would be less confusion if all annotated fields come in order, and then any non-annotated fields follow those.

(I figured this would probably require some discussion.)

(Note: this should probably be a 1.0 thing given it may break validators in subtle ways.)

On a related note, **has there been any consideration of *requiring* all variables to have annotations (in 1.0)**? With #715 that would mean fields were *always* in the expected order.

**Comment by samuelcolvin** [comment]
This makes sense to me.

As I read it I was thinking about requiring annotations.

I think we should have a `Config` setting for whether annotations should be required.

The only remaining question is what the default value for `Config.require_annotations` should be?

**Comment by dmontagu** [comment]
I think it would be awkward to have `require_annotations` be opt in -- I suspect it would be very rarely used.

I can imagine theoretical situations where leaving out an annotation provides some dynamic field inference capability that you can't replicate with annotations in place, but if that capability is necessary it should probably be handled by `create_model` instead anyway. (Maybe I'm missing something about what can be done if you drop annotations?)

Given that, it seems to me like the main benefit of not requiring annotations is reducing visual clutter. However, given the difficulty of determining the order of attributes if both annotation-only and namespace-only values are present, well... it's a lot easier to explain a missing annotation in an error message than it is to explain why the parsers are getting called in an unexpected order. And then right next to the description of the config value would be a perfect place for a warning box in the docs. This seems to outweigh the visual benefits in my opinion.

(If it were possible to get annotations and namespace in order, I admit that *would* be nice.)

**Comment by samuelcolvin** [comment]
okay agreed, default `Config.require_annotations = True`.

**Comment by samuelcolvin** [comment]
fixed by #715
