### ISSUE TITLE
JSON Schema for 'Tuple' could be more specific

### ISSUE THREAD

**Issue by DCjanus** [samuelcolvin/pydantic#718]
Feature Request 

```py
from pydantic import BaseModel
from typing import List, Tuple

class Foo(BaseModel):
    pair: Tuple[str, int]

print(Foo.schema())
```

Output:

```json
{
    "title": "Foo",
    "type": "object",
    "properties": {
        "pair": {
            "title": "Pair",
            "type": "array",
            "items": [
                {
                    "type": "string"
                },
                {
                    "type": "integer"
                }
            ]
        }
    },
    "required": [
        "pair"
    ]
}
```

Maybe we should put ["maxItems: 2"](https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.4.3) and ["minItems: 2"](https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.4.4) in this situation.

**Comment by samuelcolvin** [comment]
yup, PR welcome.

**Comment by tiangolo** [comment]
Have in mind that having a JSON array (Python `list`) of schemas as in:

```
"items": [
                {
                    "type": "string"
                },
                {
                    "type": "integer"
                }
            ]
```

Means that:

> [...] validation succeeds if each element of the instance [the JSON array] validates against the schema at the same position, if any.

Ref: http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.4.1

That means that there's an implicit restriction on how many items are acceptable and the exact type of each item at each position.

---

Now, also have in mind that if you plan on using this in OpenAPI, by OpenAPI it's not valid, a JSON array can have only one type, so, only one schema. This is one of the few small differences between JSON Schema and OpenAPI.

**Comment by DCjanus** [comment]
fair enough to me

**Comment by lewisbelcher** [comment]
Looks like OpenAPI [support mixed type arrays using `anyOf`](https://swagger.io/docs/specification/data-models/data-types/#array) @tiangolo (under the section "Mixed-Type Arrays").

If JSON Schema also support using `{max,min}Items` (the site is down at the moment so I can't check the latest format), then wouldn't it be preferable to use this format and get support for both JSON Schema and OpenAPI?

(I recently got caught out by this when parsing a schema generated by FastAPI)

**Comment by tiangolo** [comment]
So, Pydantic is outputing valid JSON Schema, and if the two types in the tuple are different, there's no other way to generate a schema for that.

So, OpenAPI is simply not compatible with that type of data :cry: . But Pydantic*is* compatible with it. And if you use it with FastAPI, *your* API will be able to handle and validate that data, it's just OpenAPI the part that can't handle it.

So, if you need to be fully compatible with OpenAPI, you would have to restrain yourself from using tuples.

On another note, OpenAPI v 3.1.0 (the next one) will be compatible with several JSON Schema features (I'm not sure about tuples, though).

**Comment by lewisbelcher** [comment]
Ah I see! Thanks for clearing that up.

Maybe we could detect if an array is homogeneous, and use the "`oneOf`/`{min,max}Items`" form if it is? It would make the schemas more concise, and probably help with the difficulties in using ellipses in `Tuple`s too by just omitting `maxItems` (I'm not sure if this breaks the JSON Schema spec though, my experiments with online validators was inconclusive..).

Or perhaps it's worth seeing what OpenAPI 3.1.0 brings first? (Good news about that by the way :+1:)
