### ISSUE TITLE
Change BaseSettings defaults

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#721]
> So, to do before version 1:

I would like to see these two BaseSettings Config fields default to the following:

```py
class Settings(BaseSettings):

  class Config:
    env_prefix = ""
    case_insensitive = True
```

_Originally posted by @jasonkuhrt in https://github.com/samuelcolvin/pydantic/issues/576#issuecomment-518889641_

**Comment by samuelcolvin** [comment]
I definitely agree about `case_insensitive`, not so sure about `env_prefix`, but I guess you're probably right.

**Comment by samuelcolvin** [comment]
I've got extremely frustrated with aliases in `BaseSettings` a number of times:
* they don't work well with inheritance
* you very often want to look for more than one alias, eg. [here](https://github.com/samuelcolvin/aiohttp-toolbox/blob/4846214cd9523cc50683ec6b08350412ec13d81b/atoolbox/settings.py#L107) I have redis `'redis_settings': 'REDISCLOUD_URL'` so aiohttp-toolbox works "out of the box" (no pun intended) on heroku with the redis cloud plugin I regularly use, but it's a slightly mad default. It would be much better if I could set multiple env varibles to inspect `{'REDISCLOUD_URL', 'REDIS_URL'}` or whatever.
* aliases are weird when initialising normally using arguments (eg. for testing) when you don't want to look for env variables, eg. I'd expect to do `Settings(pg_dsn='postgres://postgres@localhost:5432/test_db')` not have to respect the env var name and do `Settings(DATABASE_URL='postgres://postgres@localhost:5432/test_db')`

How do we work around this?

I'd therefore like to completely change how environment variables are interpreted in `BaseSettings`:

```py
from pydantic import BaseSettings

class Settings(BaseSettings):
    pg_dsn: str = 'postgres://postgres@localhost:5432/app'

    class Config:
        fields = {'pg_dsn': {'env': {'DATABASE_URL', 'PG_DSN'}}}

# or using Field (#577):
class Settings(BaseSettings):
    pg_dsn: str = Field('postgres://postgres@localhost:5432/app', env={'DATABASE_URL', 'PG_DSN'})

# creating manually for testing (here i can use the raw field name since alias hasn't changed):
settings = Settings(pg_dsn='postgres://postgres@localhost:5432/testing')
```
as discussed on #747 `env` would be completely case insensitive.

thoughts?

**Comment by dmontagu** [comment]
> It would be much better if I could set multiple env varibles to inspect {'REDISCLOUD_URL', 'REDIS_URL'} or whatever.
+1

In general aliases seem to make more sense to me in the context of `BaseModel` than `BaseSettings`. This proposal seems good to me.

**Comment by skewty** [comment]
I personally prefer the 2nd `Field` method as a developer new to **pydantic** is more likely to notice and use parameters there.  The nested `Config` from my experience with my team here is less common and comes as a surprise :tada:.

While the usage of `set` for `env` is correct in your example, I also think using a `list` there would be more typical and reduce confusion of it being a `dict`.  Are the additional features of `set` being used?  Was it chosen simply because items should be unique and because order is not important?   Perhaps the ordering offered by a `list` is an important **feature** to some.

**Comment by samuelcolvin** [comment]
Yes order of `env` may well be important. Either should work.
