### ISSUE TITLE
When changing 1 attribute how to validate full object?

### ISSUE THREAD

**Issue by sevaho** [samuelcolvin/pydantic#725]
# Question

Please complete:
* OS: Arch Linux 5.2.6
* Python version `import sys; print(sys.version)`: 3.7.4
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.32

When changing an attribute of an initated object, how can I revalidate the whole object? for example if I change the attribute age and it is older than 18 my status should be changed to 'grown-up'.

```py
from pydantic.dataclasses import dataclass


class GlobalConfig:
    validate_assignment = True
    validate_all = True
    use_enum_values = True


@dataclass(config=GlobalConfig)  # type: ignore
class T:
    a: int
    b: int

    def __post_init__(self):
        assert self.a != self.b, f"a cannot be the same as b, got a: {self.a} and b: {self.b}"


a = T(a=1, b=2)
# a = T(a=2, b=2) > throws error

a.a = 2 # this should throw an error but how?
print(a)
```

**Comment by samuelcolvin** [comment]
This is not possible, if you were using a subclass of `BaseModel` you could implement your own `__setattr__` which calls super, then does it's own checks.

If you're using `dataclass` I don't see a solution other than ugly overrighting `T.__pydantic_model__.__setattr__`

**Comment by LaundroMat** [comment]
Sorry to resurrect this, but I was wondering the same. Would it not be helpful to set `allow_mutation` in the BaseModel's config to `True` by default then?
