### ISSUE TITLE
How to model a dict of union values?

### ISSUE THREAD

**Issue by jasonkuhrt** [samuelcolvin/pydantic#726]
I would like to do something along the following lines:

```py
class Foo(BaseModel):
  a: str
  b: str

class Bar(BaseModel):
  c: str
  d: str

class Stuff(BaseModel):
  __root__: Dict[str, Union[Foo, Bar]]
```

The `Stuff` implementation was based on trying a pattern I saw in the docs but it does not work: `TypeError: custom root type cannot allow mapping`

How would we achieve this in Pydantic?

**Comment by jasonkuhrt** [comment]
To clarify, the issue is about parse-side api. Consider this:

```py
class Stuff(BaseModel):
  e: Union[Foo, Bar]
```

Then we could:

```py
stuff: Dict[str, Union[Foo, Bar]] = { k: Stuff.parse_obj(v) for k,v in some_data.items() }
```

Is there a similar `parse_obj` api for when dealing with just `Union[Foo, Bar]` types?

**Comment by dmontagu** [comment]
@jasonkuhrt If you look in the fastapi codebase, I think this is accomplished by using `field.validate`, where `field` is a pydantic `Field` (that class may be renamed soon).

-----

I have accomplished this pattern in my own code using generics (I think this is unnecessary, but I've actually used this pattern; I haven't yet figured out how/tried to do it using `field.validate`):

```python
T = TypeVar("T")

class _ResultMaker(GenericModel, Generic[T]):
    result: T

...

    return _ResultMaker[type_](result=response.json()).result  # type: ignore
```
You can see this in context here: https://github.com/dmontagu/fastapi_client/blob/master/example/client/api_client.py#L17

(I think I understood the question, but if not, let me know.)

**Comment by jasonkuhrt** [comment]
Hey @dmontagu I am not sure we're on the same page, at least I didn't fully follow your example. Here's some more context from my side;

Image this YAML file:

```yaml
some-id-1:
  type: model-kind-1
  foo: "bar"
some-id-2:
  type: model-kind-2
  wut: "qux"
some-id-3:
  type: model-kind-2
  wut: "flo"
```

How would you read that into Python typed by Pydantic?

In TypeScript, we would represent that type as:

```ts
type ModelKind1 = {
  type: "model-kind-1"
  foo: string
}

type ModelKind2 = {
  type: "model-kind-2"
  wut: string
}

type MyYamlData = {
  [ id: string ]: ModelKind1 | ModelKind2
}
```

(as for parsing, that would be something like [io-ts](https://github.com/gcanti/io-ts))

**Comment by dmontagu** [comment]
@jasonkuhrt 

This works for me:
```python
from typing import Dict, Generic, TypeVar, Union

from pydantic import BaseModel
from pydantic.generics import GenericModel


class Foo(BaseModel):
    a: int
    b: int


class Bar(BaseModel):
    c: str
    d: str


T = TypeVar("T")


class _ResultMaker(GenericModel, Generic[T]):
    result: T


loaded_input = {"hello": {"a": 1, "b": 2}, "world": {"c": "c", "d": "d"}}

print(_ResultMaker[Dict[str, Union[Foo, Bar]]](result=loaded_input).result)
# {'hello': <Foo a=1 b=2>, 'world': <Bar c='c' d='d'>}
```

**Comment by dmontagu** [comment]
Here's end-to-end for the example you gave with yaml:
```python
from io import StringIO
from typing import Any, Dict, Generic, Type, TypeVar, Union

import yaml
from pydantic import BaseModel
from pydantic.fields import Field
from pydantic.generics import GenericModel
from typing_extensions import Literal

T = TypeVar("T")


class _ResultMaker(GenericModel, Generic[T]):
    result: T


def parse_obj_to_type(obj: Any, desired_type: Type[T]) -> T:
    return _ResultMaker[desired_type](result=obj).result


class ModelKind1(BaseModel):
    type_: Literal["model-kind-1"] = "model-kind-1"
    foo: str


class ModelKind2(BaseModel):
    type_: Literal["model-kind-2"] = "model-kind-2"
    wut: str


MyYamlData = Dict[str, Union[ModelKind1, ModelKind2]]


loaded_input = {"hello": {"a": 1, "b": 2}, "world": {"c": "c", "d": "d"}}
desired_type = Dict[str, Union[ModelKind1, ModelKind2]]

yaml_data = StringIO(
    """
some-id-1:
  type: model-kind-1
  foo: "bar"
some-id-2:
  type: model-kind-2
  wut: "qux"
some-id-3:
  type: model-kind-2
  wut: "flo"
"""
)

loaded_yaml_data = yaml.safe_load(yaml_data)
print(parse_obj_to_type(loaded_yaml_data, MyYamlData))
# {'some-id-1': <ModelKind1 foo='bar' type_='model-kind-1'>, 'some-id-2': <ModelKind2 wut='qux' type_='model-kind-2'>, 'some-id-3': <ModelKind2 wut='flo' type_='model-kind-2'>}
```

**Comment by dmontagu** [comment]
To be clear, this does not give you a *model* that holds the data. So if that is your goal (which is maybe where my disconnect is), yeah, this wouldn't work. I think that would require a modification to how pydantic works.

Separately, I don't *think* there is a way to use `Union` as a root type, but the above pattern still works to parse it into one of the two types if that works as a workaround.

**Comment by jasonkuhrt** [comment]
@dmontagu 🙏 I didn't bend my mind enough, thanks so much for the expanded explanation. I can definitely give this a spin.

It seems like some effort for a basic use-case. Maybe we can lower the bar with additions to the Pydantic API.

**Comment by dmontagu** [comment]
@samuelcolvin Do you know a better way to implement this function:

```python
T = TypeVar("T")


class _ResultMaker(GenericModel, Generic[T]):
    result: T


def parse_obj_to_type(obj: Any, desired_type: Type[T]) -> T:
    return _ResultMaker[desired_type](result=obj).result
```
That doesn't make use of `GenericModel`? I feel like it should be possible, but I'm not really sure where to begin.

**Comment by samuelcolvin** [comment]
No need AFAIK for generics, I would use something like

```py
from typing import Dict, Union
from typing_extensions import Literal
from pydantic import BaseModel

data = {
    'some-id-1': {
        'type': 'model-kind-1',
        'foo': 'bar',
      },
    'some-id-2': {
        'type': 'model-kind-2',
        'wut': 'qux',
      },
    'some-id-3': {
        'type': 'model-kind-2',
        'wut': 'flo',
      },
}

class K1(BaseModel):
    type: Literal['model-kind-1']
    foo: str

class K2(BaseModel):
    type: Literal['model-kind-2']
    wut: str

class Stuff(BaseModel):
    result: Dict[str, Union[K1, K2]]

s = Stuff(result=data)
debug(s.result)
```

gives:

```
test.py:32 <module>
    s.result: {
        'some-id-1': <K1 type='model-kind-1' foo='bar'>,
        'some-id-2': <K2 type='model-kind-2' wut='qux'>,
        'some-id-3': <K2 type='model-kind-2' wut='flo'>,
    } (dict) len=3
```

The only problem I can see is that the `__root__` type can't be a `dict` so we have to use `result`.

However I think that check could be removed which would allow this to work.

**Comment by dmontagu** [comment]
@samuelcolvin But what if the type I want to pull out is dynamically determined? That's the capability I'm trying to reproduce.

In particular, I'm using a function with this signature:
```python
def parse_obj_to_type(obj: Any, desired_type: Type[T]) -> T:
```
to parse the input to the specified model in my openapi-generator-based API client. The alternative would be to (automatically) create a separate model for each possible result type that wasn't already itself a valid model, but that seems worse than just using this function and generics.

Thinking about this more, I think using the generics might actually be a better way to accomplish this than I thought since it will automatically cache the concrete model; the alternative approaches I had in mind would probably involve rebuilding the field each time.

**Comment by samuelcolvin** [comment]
I'm not opposed to `parse_obj_to_type` since it's a standalone function it doesn't conflict with anything else.

But I would say it's different from the original question here.
