### ISSUE TITLE
Serialize models with __root__

### ISSUE THREAD

**Issue by Pasha19** [samuelcolvin/pydantic#730]
# Question

* Python version `import sys; print(sys.version)`: 3.6
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.30

How to serrialize models with __root__

```py
from pydantic import BaseModel
from typing import List

class Pets(BaseModel):
    __root__: List[str]

pets = Pets(__root__=['dog', 'cat'])
print(pets.json())
```
result: `{"__root__": ["dog", "cat"]}`
How can I get `["dog","cat"]`?

**Comment by samuelcolvin** [comment]
`pets.__root__`

**Comment by Pasha19** [comment]
`pets.__root__` is list. But I need to serialize it to json string. Class `Pets` is just simple example, `__root__` can be list of another model.

**Comment by samuelcolvin** [comment]
Just for future reference "`["dog","cat"]`" is ambiguous, it could be a python object or a JSON string without the quotes, best to be clear what you're taking about.

I guess `json()` should be changed as per v1 to serialize `m.__root__` if it's defined that would fundamentally change it's behaviour from `dict()` but I think makes sense.

Anyone else, thoughts?

**Comment by tommyjcarpenter** [comment]
what is the pydantic 2 version of this question? because __root__ is gone

**Comment by will-e-yams** [comment]
@tommyjcarpenter , the v2 property is just `.root`.
