### ISSUE TITLE
Improve auto-generated JSON Schema title when none provided

### ISSUE THREAD

**Issue by skewty** [samuelcolvin/pydantic#743]
# Feature Request
## schema.py:280
Current:
```python
s = dict(title=schema.title or field.alias.title())
```
Proposed:
```python
# provide better title for PEP8 snake case names
s = dict(title=schema.title or field.alias.title().replace('_', ' '))
```

**Comment by skewty** [comment]
Would you accept this change as a PR?

**Comment by samuelcolvin** [comment]
PR sounds good.

I guess no harm in including this in v1 since it's so small.

**Comment by dmontagu** [comment]
Given this breaks a lot of fastapi tests (presumably mostly just requiring modifications to generated schemas), @tiangolo do you have any issues with this change?

**Comment by samuelcolvin** [comment]
Okay, let's wait until v1.1.

**Comment by samuelcolvin** [comment]
except I guess if it's a breaking change, it would make more sense to include it in v1.

@tiangolo what do you think?

**Comment by skewty** [comment]
@tiangolo would you like me to also update the title field in the schema unit tests to ensure that's all it is?

**Comment by samuelcolvin** [comment]
I'm pro this change, it seems like a no brainer, especially if it's a breaking change, to include it in v1.

@skewty please fix the PR and I'll merge.

**Comment by skewty** [comment]
#624 would essentially make loading and dumping camelCase names (JSON typical) easy but the change I made doesn't help when alias is camelCase.

example:  'thisFieldName' -> 'Thisfieldname'

I was a bit surprised that `alias` was used as a fallback when `title` is not specified instead of plain old `name`.

If `name` was used instead of `alias` it is likely reasonable to assume the name is in snake_case (PEP8 and all).  In this case, it capitalizes nicely.

Following the 80% / 20% rule..  I think 80% of the people would be using snake_case field names in python and camelCase names for aliases (JSON export).  Given this, I think using `name` instead of `alias` makes sense.  `title` is, of course, offered for those who have specific requirements.

As an alternative, we could try and detect snake_case using something simple like `if '_' in s` and applying a snakeToCamelCase converstion when false..   This of course is more compute intensive and "magic".

Your thoughts?

**Comment by samuelcolvin** [comment]
fine by me, but I'd be interested in @tiangolo's feedback.

**Comment by skewty** [comment]
Further to the small change suggested above.. I thought I would share my findings below and offer my labor to help with coding.  I appreciate all the great work, time and effort that has gone into pydantic and feel it will have a prominent place in the code I work on at work.  I am willing to assist and help with any suggestion / change I propose.  Additionally, I'd like to help get the project to v1.0 so **fastapi** can catch-up and then I can use it more at work.  (That is the deal I have with my Software Architect at work.)

------------------------------------------------

In looking for ways to achieve the title behavior I was looking for I investigated using sub-classing and monkey patching.  Neither would be easy / nice / maintainable.  I discovered that the (S.O.L.I.D.) **O**pen for (**some types of**) extension leaves some room for improvement as presently written.

During my brief investigation, I found that the biggest obstacle was that so many free standing methods are used (and are additionally called in a nested fashion).  A mix of composition, builder and inheritance could be leveraged here.

If these free standing methods were brought into BaseModel (or another class) as `@classmethod`s then functionality could be much more easily overridden.  (Neither the code, nor the unit tests would really need to change much either.)

Additionally, small code changes like adding a `_get_title() -> str` method could be added.

For Example:
```python
class FieldSchemaBuilder(...):
    ...
    @classmethod    
    def get_title(cls, field, schema) -> str:
        return schema.title or field.alias.title().replace('_', ' ')

    @classmethod
    def model_process_schema(...): ...

    @classmethod
    def model_type_schema(...): ...

    @classmethod
    def field_schema(...): 
        ...
        s = dict(title=cls._get_title(field, schema))
        ...

class BaseModel(...):
    ....
    __builder_class__ = FieldSchemaBuilder
    ....
```

As before, your thoughts?

**Comment by samuelcolvin** [comment]
The reasons we use free standing methods are:
1. They're often easier to reason with than complex class-based inheritance models
2. We want to avoid adding more attributes (methods, classmethods, properties etc.) to `BaseModel` since it pollutes the namespace and may conflict with fields people want to implement. Aliases are useful, but annoying and can be confusing.

The `__builder_class__` (or similar) would therefore be a good way of working around this. In turn I have two concerns with that approach:
1. It shouldn't negatively effect performance.
2. It should be as simple as possible to get your head around when you first meet pydantic.

I think a better approach might be to move these methods to the `Config` class, that way we don't need a new concept, and all the existing logic for inheritance on `Config` would work.

We might need to modify `Config` initialisation a little to provide access to the model, but that shouldn't be too hard.

@skewty what do you think?

**Comment by skewty** [comment]
@samuelcolvin I had considered that actually but feel that what those methods do isn't really "config" related.  When I asked myself what I felt they did "they build" came to mind.  With that I additionally didn't think it ideal design for `Config` to have two responsibilities. 

What if the builder methods were left where they are and more `get_title()` style methods were used by the builder methods as feature requests came in?  The `get_title()` methods could live inside `Config` as suggested.

NOTE: if `field.name` is used instead of `field.alias` to generate `schema.title` as proposed above I wouldn't need a get_title() at all.

What would the preferred approach be?:
1. create methods inside `BaseConfig` like `get_field_schema`.
2. create variables inside `BaseConfig` like `alias_generator`.

If the user will be doing the same boiler plate code for each `Config` then it makes sense to
allow them to specify a `BaseModel.__base_config_class__ = MyBaseConfig` if this isn't already possible (quick inspection leads me to believe it is hard coded).  I haven't put the time in to fully understand how your nested `Config` works in pydantic's code.  Perhaps I can find some time for this later today.

I could see in my work project (we have some interaction with web clients) using:

```python
class JSONBaseConfig(BaseConfig):
    alias_generator = snake_to_camel_case

class JSONBaseModel(BaseModel):
    __base_config_class__ = JSONBaseConfig
    def dict():
        # change default for by_alias=True
    def json():
        # change default for by_alias=True

class MyWorkClassA(JSONBaseModel):
    ...

class MyWorkClassB(JSONBaseModel):
    ...
    class Config:
        # some override not in MyWorkClassA
```

**Comment by samuelcolvin** [comment]
Let's fix `get_title` to not use alias and be implemented in the best way possible.

Further changes, eg. overriding lots of methods on config can wait for now and might not be required at all.

**Comment by hongqn** [comment]
> Let's fix `get_title` to not use alias and be implemented in the best way possible.

Has this fix released?

**Comment by TomerYogev** [comment]
>> Let's fix get_title to not use alias and be implemented in the best way possible.

> Has this fix released?

I think it wasn't :(
