### ISSUE TITLE
converting normal dataclass to pydantic dataclass

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#744]
# Feature Request

Please complete:
* OS: **Ubuntu**
* Python version `import sys; print(sys.version)`: **3.7.4**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **v0.32.1**

Would be great if `pydantic.dataclasses.dataclass` could convert an exsting dataclass to a validated/parsed dataclass.

This currently doesn't work and you just get back the normal dataclass.

```py
from dataclasses import dataclass
from typing import Optional
import pydantic.dataclasses

@dataclass
class File:
    hash: str
    name: Optional[str]
    size: int
    content: Optional[bytes] = None

FileChecked = pydantic.dataclasses.dataclass(File)
f = FileChecked(hash='xxx', name=b'whatever.txt', size='456')
debug(f)
# doesn't currently convert name to a str or size to an int
```

**Comment by hound672** [comment]
What if add another function for it?

**Comment by PrettyWood** [comment]
Hi,
I modified pydantic `dataclass` decorator to support builtin dataclasses and add validation.
I would like some feedback on [this feature](https://github.com/samuelcolvin/pydantic/pull/1817/files#diff-f6a3306d2b8af9561be776c047b45436R687): the nested dataclasses are all validated by pydantic.
I thought it would make more sense as the dataclasses can come from external packages but I was trying to see if there was some weird cases where it would be unexpected (in which case we could add something in the Config or directly in the decorator like `recursive = False`)
