### ISSUE TITLE
Model-wide validation (dependent fields)

### ISSUE THREAD

**Issue by iii-xvi** [samuelcolvin/pydantic#767]
# Can i make validation e.g.:

* [RequireIfMissing](http://www.formencode.org/en/latest/modules/validators.html#formencode.validators.RequireIfMissing)
* [RequireIfMatching](http://www.formencode.org/en/latest/modules/validators.html#formencode.validators.RequireIfMatching)

---

* OS: **Linux**
* Python version `import sys; print(sys.version)`: **3.6.9**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **0.29**

```py
import pydantic

class Model(pydantic.BaseModel):
    f1: int = None
    f1_dependent: float = None

    f2: int = None
    f2_dependent: float = None

    # something like
    # require_if("f1_dependent", present="f1")
    # require_if("f2_dependent", present="f2", expected_value=4)
    
```

**Comment by samuelcolvin** [comment]
see discussion on #506

**Comment by samuelcolvin** [comment]
simply answer: yes, use validators.
