### ISSUE TITLE
Exotic Type: DatePast and DateFuture

### ISSUE THREAD

**Issue by miketheman** [samuelcolvin/pydantic#769]
# Feature Request

An example like this?

```py
from datetime import date, timedelta

from pydantic import BaseModel
from pydantic import DatePast


class Model(BaseModel):
    date_past: DatePast = None

m = Model(date_past=date.today() - timedelta(1))

print(m.dict())
# > {'date_past': datetime.date(2019, 8, 18)}

try:
    Model(date_past=date.today() + timedelta(1))
except ValidationError as e:
    print(e)
"""
1 validation error
date_past
  value is not a valid DatePast: date is not in the past 
  (type=value_error.date_past; reason=date is not in the past)
"""
```

Would that be a useful validation to add to the exotic types?

**Comment by samuelcolvin** [comment]
Sounds good to me.

PR welcome, might have to be deferred until v1.1

**Comment by miketheman** [comment]
Fair, thanks for the timeline expectation, I'll try building the validation logic on my end before considering a PR.

**Comment by samuelcolvin** [comment]
Makes sense.

You can implement your own [custom types](https://pydantic-docs.helpmanual.io/#custom-data-types) for `PastDate` and `FutureDate` etc., then submit a PR with that code when the time comes.

**Comment by Kludex** [comment]
@samuelcolvin Would you still accept a PR with it? It's been almost 2 years, so...

**Comment by samuelcolvin** [comment]
Thanks @Kludex, yes I would.

**Comment by v3ss0n** [comment]
how about currentdate?

**Comment by samuelcolvin** [comment]
It'll be included in v2 with luck, see https://github.com/pydantic/pydantic-core/issues/229 PR to implement welcome.
