### ISSUE TITLE
Optional fields on dataclasses

### ISSUE THREAD

**Issue by viniciusd** [samuelcolvin/pydantic#771]
# Bug

* OS: OS X
* Python version: 3.7.1
* Pydantic version: 0.32

I can't initialize a Pydantic's dataclass missing optional fields, even though that's possible with Pydantic's BaseModel.

```py
import pydantic

class User(pydantic.BaseModel):
  id: int
  name: Optional[str]

User(id=1)

@pydantic.dataclass
class User:
  id: int
  name: Optional[str]

User(id=1)
```

The dataclass one gives me the error message:
```
TypeError: __init__() missing 1 required positional argument: 'name'
```

**Comment by samuelcolvin** [comment]
That's a limitation of dataclasses, this piece of logic is handled completely by python's standard dataclass implementation.

I can see both arguments but I think this is probably correct.

**Comment by viniciusd** [comment]
I see, then I am going back to `BaseModel`, because that's a feature I can't opt-out.

Thanks for the prompt response

**Comment by dmontagu** [comment]
I believe you can solve it by putting `name: Optional[str] = None` in the class definition if you want to stick with dataclasses. Not sure if that’s a problem for you though.
