### ISSUE TITLE
Add validation for payment card numbers

### ISSUE THREAD

**Issue by matin** [samuelcolvin/pydantic#788]
A common validation for any payment system or e-commerce site is validating a debit / credit card number.

The validation would like _something_ like this and be defined in `pydantic.types`:

```python
class PaymentCardNumber(str):
    """
    Based on: https://en.wikipedia.org/wiki/Payment_card_number
    """
    strip_whitespace = True
    min_length: int = 12
    max_length: int = 19

    @classmethod
    def __get_validators__(cls) -> 'CallableGenerator':
        yield not_none_validator
        yield str_validator
        yield constr_strip_whitespace
        yield constr_length_validator
        yield cls.validate_digits
        yield cls.validate_length_based_on_bin
        yield cls.validate_luhn_check_digit

    @classmethod
    def validate_digits(cls, value: str) -> str:
        if not value.isdigit():
            raise ValueError('payment card number must be digits')
        return value

    @classmethod
    def validate_length_based_on_bin(cls, value: str) -> str:
        """
        Validate length based on BIN for major brands:
        https://en.wikipedia.org/wiki/Payment_card_number#Issuer_identification_number_(IIN)
        """
        if value[0] == '4':  # Visa
            length = 16
            brand = 'Visa'
        elif 51 <= int(value[:1]) <= 55:  # Most common Mastercard range
            length = 16
            brand = 'Mastercard'
        elif value[:1] in {'34', '37'}:  # Amex
            length = 15
            brand = 'Amex'
        else:
            length = None
            brand = None
        if length and len(value) != length:
            raise ValueError(f'Length for a {brand} card must be {length}')
        return value

    @classmethod
    def validate_luhn_check_digit(cls, value: str) -> str:
        """
        Based on: https://en.wikipedia.org/wiki/Luhn_algorithm
        """
        sum_ = int(value[-1])
        length = len(value)
        parity = length % 2
        for i in range(length - 1):
            digit = int(value[i])
            if i % 2 == parity:
                digit *= 2
            if digit > 9:
                digit -= 9
            sum_ += digit
        valid = sum_ % 10 == 0
        if not valid:
            raise ValueError('Card number is not luhn valid')
        return value
```

**Comment by dmontagu** [comment]
If this is *not* accepted for any reason, I personally think it would be an improvement over the current example in the docs under the "Custom Data Types" heading (which is currently `StrictStr`).

(And even if it is, I would be in favor of a more sophisticated example under that heading.)

I think this example much more clearly demonstrates pydantic's utility for creating domain-specific validations.

**Comment by samuelcolvin** [comment]
@matin great example, thank you.

PR welcome.

@dmontagu, happy to improve the "Custom Data Types" section of the docs, I'm pretty sure it won't have been looked at or improved for a long time. However I think the example used in that section should be clearly unrealistic while still demonstrating the utility. I think something applicable to the real work is confusing, inviting the question "is this just demonstrating the functionality, or should I actually use it? If I can use it, are there other things I need to consider".

Better to have an example in the line of `FruitValidator`: "confirm foo is a valid fruit" or something where no one is confused about whether it has real world usage.
