### ISSUE TITLE
Object of type '_Literal' is not JSON serializable

### ISSUE THREAD

**Issue by sahuguet** [samuelcolvin/pydantic#791]
# Feature Request
Support Literal type for JSON Schema generation.

Please complete:
Linux-4.14.137+-x86_64-with-Ubuntu-18.04-bionic
3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
0.32.2

**Please read the [docs](https://pydantic-docs.helpmanual.io/) and search through issues to
confirm your feature hasn't been asked for before, or already implemented.**

Where possible please include a self contained code snippet describing your feature request:

```py
class All(BaseModel):
  test_enum = Literal['1', '2', '3']
  
  class Config():
    arbitrary_types_allowed = True

print(All.schema_json(by_alias=False, indent=2))
```

```
TypeError: Object of type '_Literal' is not JSON serializable
```

**Comment by dmontagu** [comment]
@sahuguet 

You should use:
```python
class All(BaseModel):
  test_enum: Literal['1', '2', '3']
  
  class Config():
    arbitrary_types_allowed = True

print(All.schema_json(by_alias=False, indent=2))
```

Note the change from `test_enum = Literal['1', '2', '3']` to `test_enum: Literal['1', '2', '3']`
