### ISSUE TITLE
EmailStr is not case-sensitive on local part of email per RFC 5321

### ISSUE THREAD

**Issue by henriklindgren** [samuelcolvin/pydantic#798]
# Bug

EmailStr validate-method performs lower() on whole string including local part, violating RFC 5321 by not conforming to 
> The local-part of a mailbox MUST BE treated as case sensitive.
https://tools.ietf.org/rfc/rfc5321.txt

See
https://github.com/samuelcolvin/pydantic/blob/79017111aa030873f2dc54576e2c768d154b1be5/pydantic/networks.py#L383

* OS: Any
* Python version `import sys; print(sys.version)`: Any
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.32.2

Where possible please include a self contained code snippet describing your bug:

```py
import pydantic
assert pydantic.EmailStr.validate('AbC@example.com') == 'AbC@example.com'
```

**Comment by samuelcolvin** [comment]
Thanks for reporting, PR welcome to fix this.

**Comment by dmontagu** [comment]
Closing as it looks like this was addressed by #801. Thanks for the contribution @henriklindgren!

**Comment by slavugan** [comment]
this RFC 5321 looks outdated as most email services works with emails as case insensitive, and following this RFC just complicates our life. just IMHO.

**Comment by emilpaw** [comment]
Is there a simple way to get the old behavior back?

**Comment by amirsoroush** [comment]
> If you want case insensitive email, inherit EmailStr and convert the value to lowercase.
> 
> ```
> class CustomEmailStr(EmailStr):
>     @classmethod
>     def validate(cls, value: EmailStr) -> EmailStr:
>         email = validate_email(value)[1]
>         return email.lower()
> ```
> 
> Note: validate method overrode the EmailStr's validate method. That's why had to include the lines of the EmailStr validation.

It's now called `_validate()`:

https://github.com/pydantic/pydantic/blob/main/pydantic/networks.py#L418
