### ISSUE TITLE
Validating subclasses

### ISSUE THREAD

**Issue by timonbimon** [samuelcolvin/pydantic#807]
# Question

I was wondering what the best way to validate subclasses is?
Something along the sorts of

```python
import pydantic
class MyClass:
    pass
class MySubClass(MyClass):
    pass
class MyOtherClass:
    pass

class Foo(BaseModel):
    a_class_not_an_object: Type[MyClass]
```
where I would expect both

```python
Foo(a_class_not_an_object=MyClass)
Foo(a_class_not_an_object=MySubClass)
```
to work, but
```python
Foo(a_class_not_an_object=MyOtherClass)
```

to throw an error.
Is the way to go to implement a custom type or is there a way pydantic supports this out-of-the-box?

Have a good weekend :)

**Comment by samuelcolvin** [comment]
Might be possible to achieve this now using validator decorators. Please let us know whether or not you get it to work.

I'd be happy to accept a PR to implement it out of the box if it's something multiple people want.

**Comment by timonbimon** [comment]
Alright, I've been freeriding long enough. 😉
Just made a MR that should resolve the issue. :) 
Thanks for making an awesome library. pydantic rocks 💯
