### ISSUE TITLE
Please remove "email-validator not installed, email fields will be treated as str." warning

### ISSUE THREAD

**Issue by cjw296** [samuelcolvin/pydantic#815]
Anything that imports pydantic ends up spamming a warning with "email-validator not installed, email fields will be treated as str."

This isn't helpful, especially when projects aren't even using email fields. 
My suggestion would be to just remove the warning and have email fields raise an exception if they're used and email-validator isn't present.

If you really must keep the warning, please only emit it if an email field is actually used.

**Comment by victornoel** [comment]
Isn't that something coming from FastAPI? See https://github.com/tiangolo/fastapi/blob/master/fastapi/openapi/models.py#L16

**Comment by cjw296** [comment]
@victornoel - thank you for pointing that out, you're absolutely correct!

**Comment by victornoel** [comment]
@cjw296 do you plan to open an issue at fastapi or I can do it? :)

**Comment by victornoel** [comment]
I've done it: https://github.com/tiangolo/fastapi/issues/542

**Comment by cjw296** [comment]
Perfect, thanks!
