### ISSUE TITLE
exception in find_validators

### ISSUE THREAD

**Issue by borisz** [samuelcolvin/pydantic#816]
# Bug

Please complete:
* OS: OSX
* Python version `import sys; print(sys.version)`: 
3.7.4 (default, Sep 12 2019, 22:07:27) 
[Clang 11.0.0 (clang-1100.0.33.8)]
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.32.2

I wonder if this is a bug, or is the same name for a variable and type forbidden?

The example works, if I use 

`origin: Origin Schema(Origin())` instead of `Origin: Origin Schema(Origin())`

Thanks!

Where possible please include a self contained code snippet describing your bug:

```py
#!python3
from pydantic import Schema, BaseModel
import json


class Origin(BaseModel):
    cc: str = "xz"


class Address(BaseModel):
    Origin: Origin = Schema(Origin())
    # lower case origin works, but I try to keep the case.
    # what is wrong wit Origin as var name?
    # origin: Origin = Schema(Origin()) # works


j = json.loads("""{ "Origin": { "cc": "de" }}""")
a = Address(**j)
```

**Comment by samuelcolvin** [comment]
Your code is invalid.

Because the field is called `Origin`, it redefines the meaning of `Origin` in the annotation.

Same happens without pydantic:

```py
class Bar:
    pass

class Foo:
    Bar: Bar = 'new value of Bar'

debug(Foo.__annotations__)
"""
test.py:9 <module>
    Foo.__annotations__: {'Bar': 'new value of Bar'} (dict) len=1
"""
```
