### ISSUE TITLE
Automatically creating validators for certain types

### ISSUE THREAD

**Issue by viniciusd** [samuelcolvin/pydantic#825]
# Question

* Python version: `3.7`
* Pydantic version: `0.32`

I am trying to automatically generate pre-validators for some specific types (e.g., datetime) in order to complement Pydantic's.

In order to accomplish that, I am using something similar to the following exert.

However, it turns out my `decode` function is never called and I don't understand why. Thoughts?

```py
from contextlib import suppress
from functools import partial
import datetime
import typing

from pydantic import BaseModel
from pydantic import validator


class Validator(BaseModel):
    def __new__(cls, *args, **_kwargs):
        for item, _type in typing.get_type_hints(cls).items():
            with suppress(TypeError):
                if issubclass(_type, datetime.datetime):
                    parser_name = f"parse_{item}"
                    custom_validator = partial(lambda __type, _, value: decode(value, __type), _type)
                    custom_validator.__name__ = custom_validator.__qualname__ = parser_name
                    custom_validator.__module__ = cls.__module__
                    setattr(cls, parser_name, validator(item, pre=True)(custom_validator))
        return BaseModel.__new__(cls, *args)


def decode(value):
    return datetime.strptime(value, "%m/%d/%Y %H:%M")
```

**Comment by dmontagu** [comment]
Validators are actually set up by the BaseModel metaclass, if I recall correctly; I think this is why you aren’t getting the desired behavior when you modify the `__new__` function. (Note that if your approach did work, it would likely add a great deal of performance overhead since it would add validators every time the model was instantiated.)

The outcome you are trying to accomplish is almost certainly still possible though. Let me think about it for a bit..

**Comment by viniciusd** [comment]
Appreciate your response.

I am aware that it will certainly add some performance cost by adding them as the `__new__` magic method. I've been browsing Pydantic source code and I am reaching the same explanation you proposed. At least I am at the right path [to understanding why it doesn't work].

**Comment by dmontagu** [comment]
@viniciusd Three approaches:

1. Inject a validator:
    * This is the closest I could come to your approach; it works in the example below, but I don't guarantee it that it would behave exactly right with regard to inheritance, etc.
    * I would consider this non-idiomatic for pydantic; see 2. below for the idiomatic approach.)
<details>
  <summary><b>Click to expand</b></summary>

```python
from datetime import datetime

from pydantic import BaseModel
from pydantic.class_validators import Validator
from pydantic.utils import lenient_issubclass

def custom_datetime_validator(value):
    print("validated datetime")
    return value
datetime_validator = Validator(
    custom_datetime_validator, pre=False, whole=False, always=False, check_fields=False
)

class BaseDatetimeModel(BaseModel):
    def __init_subclass__(cls):
        for name, f in cls.__fields__.items():
            if not lenient_issubclass(f.type_, datetime):
                continue
            f.class_validators.update({f"validate_datetime_{name}": datetime_validator})
            f.prepare()

class DatetimeModel(BaseDatetimeModel):
    x: datetime

print(DatetimeModel(x=0))
# validated datetime
# DatetimeModel x=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)
```
</details>

-----

2. Create a custom type to use as your field annotation
    * I believe this is the idiomatic approach
<details>
    <summary><b>Click to expand</b></summary>

```python
from datetime import datetime

from pydantic import BaseModel
from pydantic.datetime_parse import parse_datetime

def custom_datetime_validator(value):
    print("validated datetime")
    return value

class CustomParsedDatetime(datetime):
    @classmethod
    def get_validators(cls):
        yield parse_datetime
        yield custom_datetime_validator

class DatetimeModel(BaseModel):
    x: CustomParsedDatetime

print(DatetimeModel(x=0))
# validated datetime
# DatetimeModel x=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)
```
</details>

-----

3. Update `pydantic.validators._VALIDATORS`
    * This uses a private API, so use of this approach should probably be discouraged, but unlike approach 1 I am fairly confident it will work everywhere, and doesn't require a subclass.
<details>
  <summary><b>Click to expand</b></summary>

```python
from datetime import datetime

from pydantic import BaseModel
from pydantic.validators import _VALIDATORS

def custom_datetime_validator(value):
    print("validated datetime")
    return value

for type_, validators in _VALIDATORS:
    if type_ is datetime:
        validators.append(custom_datetime_validator)

class DatetimeModel(BaseModel):
    x: datetime

print(DatetimeModel(x=0))
# validated datetime
# DatetimeModel x=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)
```
</details>

-----

@samuelcolvin is there a public API for updating the contents of `pydantic.validators._VALIDATORS`? Or would you just recommend the use of option 2 above?

**Comment by dmontagu** [comment]
Also, note that with approach 2 above, if you don't want to run into mypy issues due to the datetime subclass in other parts of your code, you could replace it with:

```python
from typing import TYPE_CHECKING:

if TYPE_CHECKING:
    CustomParsedDatetime = datetime
else:
    class CustomParsedDatetime(datetime):
        @classmethod
        def get_validators(cls):
            yield parse_datetime
            yield custom_datetime_validator
```

**Comment by viniciusd** [comment]
Thank you very much @dmontagu, that's a lot of learning about Pydantic internals

I managed a fourth approach, which even I myself would discourage but it ran. It consists of inheriting from the metaclass itself instead of BaseModel:

<details>
<summary>Click to expand</summary>
```py
from contextlib import suppress
from functools import partial
from datetime import datetime

from pydantic import BaseModel
from pydantic import validator
from pydantic.main import MetaModel


class Validator(MetaModel):
    def __new__(mcs, name, bases, namespace, **kwargs):
        for item, _type in namespace["__annotations__"].items():
            # Suppress TypeError in case there is some typing instead of raw
            # types, e.g., Union[str, int]
            with suppress(TypeError):
                if issubclass(_type, datetime):
                    parser_name = f"parse_{item}"
                    custom_validator = partial(
                        lambda __type, value: decode(value, __type), _type
                    )
                    custom_validator.__name__ = (
                        custom_validator.__qualname__
                    ) = parser_name
                    custom_validator.__module__ = namespace["__module__"]
                    namespace[parser_name] = validator(item, pre=True)(
                        custom_validator
                    )
        return MetaModel.__new__(mcs, name, bases, namespace)

def decode(value):
    return datetime.strptime(value, "%m/%d/%Y %H:%M")

if getattr(BaseModel, "__class__") != Validator:
    # Replace pydantic.BaseModel's metaclass with our own custom metaclass
    setattr(BaseModel, "__class__", Validator)

```
</details>

**Comment by samuelcolvin** [comment]
The correct approach is a custom type or use of standard class validators.

I don't think any other approach should be necessary, but if I'm missing something let me know.

**Comment by viniciusd** [comment]
Well, my initial point is exactly about automatically creating class validators instead of manually doing that for each field. Thanks anyway.

**Comment by samuelcolvin** [comment]
You could use a class validator on all fields then examine the field argument to check the type of the field.

**Comment by viniciusd** [comment]
Is there a way to make a validator run against all fields or do I need to manually insert the list of fields?
