### ISSUE TITLE
Make all validated fields available in validator

### ISSUE THREAD

**Issue by pykong** [samuelcolvin/pydantic#834]
It would be highly useful to have allnames of the fields submitted to a validator available upon validation. For example we may introduce a new parameter `fields` that holds those (_See example below_).

This would allow for example to filter `values` depending on whether they appear in `fields`.

````py

from pydantic import BaseModel, ValidationError, validator


class DemoModel(BaseModel):
    one: str
    two: str
    three: str   
    four: str
   
    @validator('one', 'two', 'three')
    def custom_check(cls, v, fields, values):
        print(fields)  # will output: ('one', 'two', 'three',)
        filtered_values = { k, v for k, v in values.items() if k in fields }  # excludes 'four'
        for x in filtered_values:
            # do some custom cross-validation
            # needing to be restricted to: 'one', 'two', 'three'

        return v
````

**Comment by samuelcolvin** [comment]
This is probably best achieved using root validators (#817) once v1 is released.

In a future release we'll add a custom exception which can include a custom `loc` to get around root validators using `__root__` as `loc`, but that won't be part of v1.
