### ISSUE TITLE
Feature Request: Support for typing_extensions.Annotated (from PEP 593)

### ISSUE THREAD

**Issue by dmontagu** [samuelcolvin/pydantic#837]
# Feature Request
### Support for `typing_extensions.Annotated` (from PEP 593)

This could offer a nice way to solve the problem of assigning a `Schema` to a field without upsetting mypy, and without introducing an auxiliary function returning type `Any` (as discussed in https://github.com/samuelcolvin/pydantic/issues/577):

Instead of
```python
class MyModel(BaseModel):
    x: int = Schema(..., ge=0)
    y: str
```
The API could be:
```python
from typing_extensions import Annotated

class MyModel(BaseModel):
    x: Annotated[int, Schema(ge=0)]
    y: str
```

* Mypy support for this `typing_extensions.Annotated` was added in mypy 0.730.
* See [PEP 593](https://www.python.org/dev/peps/pep-0593/) for more details about `typing_extensions.Annotated`.

**Comment by dmontagu** [comment]
Also note: mypy has `typing_extensions` as a dependency, so you wouldn't need to install any additional packages to use this capability to get mypy checks to pass.

(And as long as we don't drop support for the `= Schema(..., ge=0)` api, no existing checks would break.)

@samuelcolvin It might be worth considering this option more seriously prior to releasing V1.0, in case it allows us to drop the `Field(...)` function in #824.

**Comment by tiangolo** [comment]
That's interesting. Although it makes the code more verbose and (subjectively) less intuitive.

I like that the `= Field(...)` is somewhat similar to dataclasses `field()` functions: https://docs.python.org/3/library/dataclasses.html#dataclasses.field

**Comment by dmontagu** [comment]
@tiangolo I think that's a good point on both counts.

At any rate, I think it should be possible to handle this more completely by way of a mypy plugin (I'm already using the plugin I've opened a PR for in pydantic in all my projects, and I plan to get it into a release-worthy state as soon as v1.0 drops). Given the limited scope of issues that type-hinting as `Any` could cause, this seems like it may be preferable to supporting `Annotated` anyway.

That said, I think it may still make sense to support `Annotated` for compatibility with other frameworks that may choose to use it. I'd be happy to wait to implement it until someone requests it for more practical reasons though 😄.

**Comment by samuelcolvin** [comment]
See my response on #824. 

My only other question: is there any change whatsoever that the pep get's declined and we're left with unofficial syntax? I guess if that does happen and mypy stops supporting `Annotated`, we could change back in future.

**Comment by samuelcolvin** [comment]
In summary I'm keen to implement this, I think it should be backwards compatible so can happen after v1.

As discussed on #824 and here, use of `x: Whatever = Field(...)` should continue to work and is likely to be the primary way most people use `Field`.

**Comment by tiangolo** [comment]
In recent versions `Field()` is now a function, so mypy doesn't complain.

And @dmontagu 's mypy plugin is working great.

I would think this specific issue could be closed and we could open a new one if there's a new use case that benefits from `Annotated`, what do you think?

**Comment by mcgfeller** [comment]
PEP 593 is now in Python 3.9. Would this help to have better support for Pydantic in PyRight, PyLance and hence VS Code, making Option 2 of https://github.com/microsoft/python-language-server/issues/1898 feasible? Best regards, Martin

**Comment by pikeas** [comment]
Would love to see Pylance and Pydantic playing nicely together without the decorator hack!

**Comment by JacobHayes** [comment]
@pikeas If you get a chance, try out https://github.com/samuelcolvin/pydantic/pull/2147 and see if 1: it works and 2: Pylance plays nicely.

**Comment by pikeas** [comment]
@JacobHayes 

```
from typing import Annotated
# also tried from typing_extensions import Annotated

class FooModel(BaseModel):
    value1: str
    value2: Annotated[str, []]

foo = FooModel()
```

No errors but Pylance still only sees `**data: Any` when hovering `FooModel`

**Comment by thomascobb** [comment]
As a test I put the decorator hack at the end of `pydantic.dataclasses`:
```python
if TYPE_CHECKING:
    from dataclasses import dataclass
```
Now Pylance gives type hinting for this:
```python
from pydantic.dataclasses import dataclass

@dataclass
class Foo:
    value1: str
    value2: Annotated[str, Field(description="Something else")]

f = Foo("boo", value2="foo")
```
All tests still pass, but I don't know if this has made mypy ignore any internal tests...
