### ISSUE TITLE
ValidationError in child model short-circuits validation in recursive model

### ISSUE THREAD

**Issue by AJLivine** [samuelcolvin/pydantic#838]
# Bug

* OS: **macOS 10.14.6**
* Python version: **3.7.4 (default, Sep 10 2019, 17:04:46)
[Clang 10.0.1 (clang-1001.0.46.4)]**
* Pydantic version: **0.32.2**

(Sorry if this should've been a feature request; the short-circuiting of recursive validation seems to qualify as a bug.)

I'm looking at pydantic models as replacements for Django Forms and Formsets in my company's software since (a) there's so much less ceremony in pydantic models, (b) they're more general and don't complect data validation with html generation, and (c) they put runtime type checking exactly where python needs it.

My naive assumption was that a recursive model should be a replacement for a Django Formset (essentially a recursive Form if you haven't used Django), which performs validation on a parameterized set of Forms of a single class. But, when I tried to give a recursive model a bunch of bad data I found that only the first child model object's errors are reported (slightly altered from the recursive model docs example to simplify):

```py
from typing import List
from pydantic import BaseModel, ValidationError

class Foo(BaseModel):
    count: int
    size: float = None

class Circus(BaseModel):
    foos: List[Foo]

try:
    Circus(foos=[Foo(count=1, size="hi"), Foo(count="low")])
except ValidationError as e:
    print(e.errors())
```

This yields:

```
[{'loc': ('size',), 'msg': 'value is not a valid float', 'type': 'type_error.float'}]
```

Only the first `Foo`'s `size` error is reported, even though the second `Foo` has a bad `count`. The same problem holds for recursive models with more than one kind of simple child (again adapted and simplified from the docs):

```py
class Bar(BaseModel):
    apple: str

class Spam(BaseModel):
    foo: Foo
    bar: Bar

try:
    Spam(foo=Foo(), bar=Bar())
except ValidationError as e:
    print(e.errors())
```

This yields:
```
[{'loc': ('count',), 'msg': 'field required', 'type': 'value_error.missing'}]
```
After a quick look at the codebase, I think the problem is related to this from the docs:

> Validation code should not raise ValidationError itself, but rather raise ValueError or TypeError (or subclasses thereof) which will be caught and used to populate ValidationError.

I can see elegantly maintain associations between child model objects and their errors in all cases might be tricky, and given this deliberate choice for simple models (and a good and laudable choice at that), I suppose the fix can't be as simple as:

* handling `ValidationError` everywhere you're handling `TypeError, ValueError`; and
* perhaps adding a method that lists all children and any ValidationErrors associated with a child so you know which children were problematic.

I imagine this is also a problem for fastapi, which needs functionality similar to Django Formsets to properly report api errors. @tiangolo Does fastapi have a workaround in place for this?

**Comment by dmontagu** [comment]
I think this isn't a bug in pydantic -- the problem is with your python code.

```python
Circus(foos=[Foo(count=1, size="hi"), Foo(count="low")])
```
In this code, you are actually *evaluating* `Foo` first.

It is a fundamental part of how python works that the above code is essentially equivalent to the following:
```
foo1 = Foo(count=1, size="hi")
foo2 = Foo(count="low")
Circus(foos=[foo1, foo2])
```

If you were to pass a dictionary to `Circus` that should be parsed by circus, you'll see you get all the errors you are expecting:
```python
from typing import List
from pydantic import BaseModel, ValidationError

class Foo(BaseModel):
    count: int
    size: float = None

class Circus(BaseModel):
    foos: List[Foo]

circus_data = {
    "foos": [{"count": 1, "size": "hi"}, {"count": "low"}]
}

try:
    Circus(**circus_data)
except ValidationError as e:
    print(e.errors())
# [
#     {
#         'loc': ('foos', 0, 'size'),
#         'msg': 'value is not a valid float',
#         'type': 'type_error.float'
#     },
#     {
#         'loc': ('foos', 1, 'count'),
#         'msg': 'value is not a valid integer',
#         'type': 'type_error.integer'}
# ]
```

So I don't think this is actually an issue with either pydantic or fastapi.

**Comment by AJLivine** [comment]
Jeez. Of course. I'm not an expert on python parsing/AST/interpretation, but 
(a) I should've recognized that was more magic than pydantic was capable of
(b) I should've thought that it's more magic than you'd even want
(c) I should've extrapolated from the docs example with dicts
This is exactly the right behavior.

Thanks, and sorry for distracting during the 1.0 push.

**Comment by dmontagu** [comment]
No problem! Thanks for closing this issue, but please feel free to post more issues if you notice other behavior you think might be a pydantic bug.

**Comment by tiangolo** [comment]
Thanks @dmontagu ! :cake: :bowing_man:
