### ISSUE TITLE
Is it possible to use async methods as validators?

### ISSUE THREAD

**Issue by adpham95** [samuelcolvin/pydantic#857]
## Is it possible to use async methods as validators, for instance when making a call to a DB for validating an entry exists? 

* OS: Ubuntu **18.04**
* Python version: **3.7.1**
* Pydantic version: **0.30.0**

```py
from pydantic import BaseModel, validator

fake_db = {
    "foo": "bar"
}

async def call_to_db(id):
    return fake_db[id]

class Test(BaseModel):
    foo: str
    bar: str
        
    @validator('bar')
    async def bar_validator(cls, value, values):
        if values["bar"] == "foo":
            return await call_to_db("foo")
    
t = Test(foo="foo", bar="foo")
print(t)
```
Result: `Test foo='foo' bar=<coroutine object Test.bar_validator at 0x7f2213ca82c8>`

**Comment by samuelcolvin** [comment]
No.

That would involve the whole of pydantic being asynchronous.

You should do all asyncronous validation outside pydantic models after other validation has completely.

This might sound annoying, but actually it provides a clear divide between pure data validation and checking the data is valid as per your database etc.

**Comment by synchronizing** [comment]
@samuelcolvin Integrating Pydantic + Tortoise (async ORM) + FastAPI (async), how would you recommend one go about validating entries in the database? Validating database relationships/entries via Pydantic interface makes sense to me, but I'm no contributor or expert of the source.

From my understanding, the [`@validate_arguments`](https://pydantic-docs.helpmanual.io/usage/validation_decorator/#async-functions) decorator has asynchronous support, so why wouldn't the `@validator` have the same?

**Comment by AndreMPCosta** [comment]
> @samuelcolvin Integrating Pydantic + Tortoise (async ORM) + FastAPI (async), how would you recommend one go about validating entries in the database? Validating database relationships/entries via Pydantic interface makes sense to me, but I'm no contributor or expert of the source.
> 
> From my understanding, the [`@validate_arguments`](https://pydantic-docs.helpmanual.io/usage/validation_decorator/#async-functions) decorator has asynchronous support, so why wouldn't the `@validator` have the same?

I share the same problem, did you find a solution @synchronizing ?

**Comment by synchronizing** [comment]
> I have the same problem, did you find a solution @synchronizing ?

We are now just doing the validation within our routes.

```python
@router.post(
    path="/",
    summary="...",
    response_model=schemas.PlatformOut,
    responses={
        status.HTTP_201_CREATED: {
            "description": "The request was successful.",
        },
        status.HTTP_409_CONFLICT: {
            "description": "A platform with this name or URL already exists.",
        },
    },
    status_code=status.HTTP_201_CREATED,
)
@version(1)
async def create_new_platform(platform: schemas.PlatformCreateIn):
    if await models.Platform.exists(name=platform.name):
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="A platform with this name already exists.",
        )
    elif await models.Platform.exists(url=platform.url):
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="A platform with this URL already exists.",
        )

    return await models.Platform.create(**platform.dict())
```

**Comment by AndreMPCosta** [comment]
@synchronizing I will use a similar approach, thanks!

**Comment by tupui** [comment]
I needed to do this and this is how I mannaged:

```python
@validator("foo")
def validate_foo(cls, v):

    async def func():
        return 'Something'

    loop = asyncio.get_event_loop()
    result = loop.run_in_executor(None, func)

    return result
```

**Comment by lucasrabaca** [comment]
tried @tupui but the error still remais, saying that the variable is a coroutine and not returning its value.

how am i supposed to fetch additional data for the model with computed_fields or any other solution if pydantic does not allow additional async queries?

`
Model:
    versions: fields.ReverseRelation[GrammarRuleVersion] = []


    # async function:
    async def current_version(self) -> Optional[RuleVersion]:
        return await self.versions.filter(mode="production").first()


# Generated Schema:
ModelSchema = pydantic_model_creator(
    Model, computed=["current_version"], name="ModelSchema"
)

`
In this scenario current_version is never awaited by pydantic, so its value is always None.

**Comment by tupui** [comment]
> tried @tupui but fastapi says i'm attached to a different loop.

@lucasrabaca did you try my second snippet? This code is starting a new thread and so there should be no conflict as the event loop is within this thread.

> how am i supposed to fetch additional data for the model with computed_fields or any other solution if pydantic does not allow additional async queries?
> 
> ``
> Model:
> versions: fields.ReverseRelation[GrammarRuleVersion] = []
> 
> ```
> # async function:
> async def current_version(self) -> Optional[RuleVersion]:
>     return await self.versions.filter(mode="production").first()
> ```
> 
> ``
> 
> #Generated Schema:
> ModelSchema = pydantic_model_creator(
> Model, computed=["current_version"], name="ModelSchema"
> )
> 
> In this scenario current_version is never awaited by pydantic, so its value is always None.
> 
> RuntimeWarning: coroutine 'Model.current_version' was never awaited

Your `current_version` being async, you have to await it. But you cannot with pydantic as explained in this thread. The only way is to start a new process/thread and await there.

**Comment by bluebrown** [comment]
I want async validators too. But tbf, half of the use cases shown here are not even worth it. Username is not unique for example, that should be solved with a unique constraint on the database column and then can just try to insert and check for errors. No need to go n+1 on this.

**Comment by Tatayoyoh** [comment]
Hi there !

I was facing the same problem with the following stack :  Pydantic + ODMantic (async ODM) + MongoDB + FastAPI (async)

I wanted to fetch some database data on validation process (convert an ObjectId into a full json entity dict on the fly)

The solution for me was to use **sync** AND **async** [ODMantic Mongo engines](https://art049.github.io/odmantic/engine/) in the same time.

Then I was able to use Pydantic validation with sync engine, and use FastAPI with async engine.

I hope it will help :)

```python
from odmantic import Model, Reference
from odmantic import Field
from bson import ObjectId
from typing import List

# ASYNC engine
from motor.motor_asyncio import AsyncIOMotorClient
from odmantic import AIOEngine
async_client = AsyncIOMotorClient('mongodb://db-compare-backend-database-mongo:27017/')
async_engine = AIOEngine(client=async_client, database='simple_db')

# SYNC engine
from pymongo import MongoClient
from odmantic import SyncEngine
sync_client = MongoClient('mongodb://db-compare-backend-database-mongo:27017/')
sync_engine = SyncEngine(client=sync_client, database='simple_db')


def fetch_database_model(modelClass, obj_id:ObjectId):
    # SYNC engine
    data = sync_engine.find_one(modelClass, modelClass.id == obj_id)   
    if not data:
        raise ValueError("No %s found with ObjectId(%s)"%(modelClass.__name__, obj_id))
    res = data.dict()
    res['id'] = str(res['id']) # convert ObjectId to str
    return res

class ModelObjectId(ObjectId):
    """
        Pydantic / ODMantic custom field type
        https://art049.github.io/odmantic/fields/#custom-field-types
    """
    _model = None
    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        if cls._model == None:
            raise ValueError("No model provided")
        if isinstance(v, ObjectId):  # Handle data coming from MongoDB
            # SYNC engine for validation
            return fetch_database_model(cls._model, v)
        if isinstance(v, str):       # Handle data coming from FastAPI request
            return ObjectId(v)
        else:
            raise ValueError("%s validation Error"%(cls.__name__))


class School(Model):
    name: str = Field()

class Skill(Model):
    description: str = Field()

class Student(Model):
    class SkillObjectId(ModelObjectId):
        _model = Skill

    fullname: str = Field()
    school:School = Reference()  # how ODMantic manage single reference
    skills:List[SkillObjectId]   # how ODMantic manage multi references


from fastapi import FastAPI
app = FastAPI()

@app.post("/skill", response_model=Skill)
async def create_skill(skill: Skill):
    """json body
        {
            "description":"C++"
        }
    """
    # ASYNC engine
    await async_engine.save(skill)
    return skill

@app.post("/student", response_model=Student)
async def create_student(student: Student):
    """json body
        {
            "fullname": "John Doe",
            "skills": [
                "65ad4a6fg6th4rt_SKILL_ID_1",
                "aef4ze6erhg6g7z_SKILL_ID_2",
            ],
            "school": {
                "name":"Santai School"
            }
        }
    """
    # ASYNC engine
    await async_engine.save(student)
    return student
    
@app.get("/students")
async def students():
    # ASYNC engine
    students = await async_engine.find(Student)
    return students
```

Test with Curl :
```bash
# Create skills first
curl -X POST http://localhost:9999/skill -H 'Content-Type: application/json' -d '{"description":"C++"}'
# {"description":"Python3","id":"64b969147c8ee365bf265f35"}

curl -X POST http://localhost:9999/skill -H 'Content-Type: application/json' -d '{"description":"Python3"}'
# {"description":"Python3","id":"64b969147c8ee365bf265f35"}

# Use returned skills IDs to create a student
curl -X POST http://localhost:9999/student -H 'Content-Type: application/json' -d '{"fullname": "John Doe", "skills": ["64b969147c8ee365bf265f35", "64b969147c8ee365bf265f35"], "school": {"name":"Santai School"}}'

# Retrieve students
curl http://localhost:9999/students
```

**Comment by ddanier** [comment]
As we had the same issue in our FastAPI projects I just released https://pypi.org/project/pydantic-async-validation/ to add pydantic like async validation to your models. Note that validation is not done in the model constructor nor will this be possible in the future. It is meant as an easy and structured was to define validators using a pydantic like registration approach.

Example code:
```python
import pydantic
from pydantic_async_validation import async_field_validator, AsyncValidationModelMixin


class SomethingModel(AsyncValidationModelMixin, pydantic.BaseModel):
    name: str

    @async_field_validator('name')
    async def validate_name(self, value: str) -> None:
        if value == "invalid":
            raise ValueError("Invalid name")


valid_instance = SomethingModel(name="valid")
await valid_instance.model_async_validate()

invalid_instance = SomethingModel(name="invalid")
await invalid_instance.model_async_validate()  # will raise normal pydantic ValidationError
```

**Comment by kriscode1** [comment]
> If there is already an event loop (like this would be used with FastAPI), you need to start another thread:
> 
> ```python
> import concurrent.futures
> import asyncio
> 
> 
> @validator("foo")
> def validate_foo(cls, v):
> 
>     async def func():
>         return 'Something'
> 
>     pool = concurrent.futures.ThreadPoolExecutor(1)
>     result = pool.submit(asyncio.run, func()).result()
> 
>     return result
> ```

This example would still block the event loop if called in a running loop. We'd need `async def validate_foo` ... `await ...` to give control back.

**Comment by cj** [comment]
> As we had the same issue in our FastAPI projects I just released https://pypi.org/project/pydantic-async-validation/ to add pydantic like async validation to your models. Note that validation is not done in the model constructor nor will this be possible in the future. It is meant as an easy and structured was to define validators using a pydantic like registration approach.
> 
> Example code:
> 
> ```python
> import pydantic
> from pydantic_async_validation import async_field_validator, AsyncValidationModelMixin
> 
> 
> class SomethingModel(AsyncValidationModelMixin, pydantic.BaseModel):
>     name: str
> 
>     @async_field_validator('name')
>     async def validate_name(self, value: str) -> None:
>         if value == "invalid":
>             raise ValueError("Invalid name")
> 
> 
> valid_instance = SomethingModel(name="valid")
> await valid_instance.model_async_validate()
> 
> invalid_instance = SomethingModel(name="invalid")
> await invalid_instance.model_async_validate()  # will raise normal pydantic ValidationError
> ```

@ddanier thank you for that! It works really well. The only issue is it removes the pyright types:

Without AsyncValidationModelMixin:

![image](https://github.com/pydantic/pydantic/assets/1819/91d9bfd9-ef3a-490a-b228-91063979fc09)

With AsyncValidationModelMixin:

![image](https://github.com/pydantic/pydantic/assets/1819/173126c6-a8ec-428f-8f26-c730d6fbe3e5)

**Comment by cj** [comment]
@ddanier I found a fix for the typing issue; in metaclasses.py line 17; you can change it to (make sure to add the missing imports):
```
@dataclass_transform(kw_only_default=True, field_specifiers=(Field,))
class AsyncValidationModelMetaclass(ModelMetaclass):
```

**Comment by ddanier** [comment]
@cj I just did create a new issue in https://github.com/team23/pydantic-async-validation to track this:
https://github.com/team23/pydantic-async-validation/issues/6

**Comment by adriangb** [comment]
One thing you may be able to do is:
- Create an `anyio` `BlockingPortal` in a dependency / outside of validation
- Put that in a `ContextVar`
- Access the `BlockingPortal` from within a sync validation function and use that to call the async portion of it (which could just be a closure within the sync validation function)
