### ISSUE TITLE
custom json encoder spins an infinite loop that eats all RAM

### ISSUE THREAD

**Issue by euri10** [samuelcolvin/pydantic#863]
# Question

Please complete:
* OS: debian 11
* Python version `import sys; print(sys.version)`: 3.7.4+ (default, Sep  4 2019, 08:03:05) 
[GCC 9.2.1 20190827]
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.32.2

**Please read the [docs](https://pydantic-docs.helpmanual.io/) and search through issues to
confirm your question hasn't already been answered.**

Where possible please include a self contained code snippet describing your question:

```py
from typing import Optional

from pydantic import BaseModel

import base64

class File(BaseModel):
    name: str
    content: bytes
    type: Optional[str]

    class Config:
        orm_mode = True
        json_encoders = {
            bytes: lambda v: base64.b64encode(v)
        }

content = b'\x01'*3
f = File(name='myname', content=content)
print(base64.b64encode(content))
print(f)
print(f.json())
```

once it hits the last print it goes in an infinite loop back and forth from line 257 : `return _iterencode(o, 0)` in the below snippet  (it's from json/encode.py in stdlib, sorry cant find link) to `            bytes: lambda v: base64.b64encode(v)` in my snippet and subsequently eats all my ram.
I've no idea if this qualify as a bug or it's an ovious misuse, so I tagged as a question 1st :)

 
```
        else:
            _iterencode = _make_iterencode(
                markers, self.default, _encoder, self.indent, floatstr,
                self.key_separator, self.item_separator, self.sort_keys,
                self.skipkeys, _one_shot)
        return _iterencode(o, 0)
```

**Comment by jtmiclat** [comment]
@euri10 The problem stems from JSON not supporting `bytes` type. JSON spec only supports, `string`, `number`, `integer`, `boolean`, `null`. Python json module even raises an error is you try to `json.dumps` bytes value.  It seems `json_encoders` should only return JSON serializable for it to work.

When you do the `base64.b64encode` it returns bytes and tries to run encode it again hence the infinite loop. 

The solution is to decode it to a string when converting after base64 enocding. 
```
class File(BaseModel):
    name: str
    content: bytes
    type: Optional[str]

    class Config:
        orm_mode = True
        json_encoders = {
            bytes: lambda v: base64.b64encode(v).decode()
        }
```

**Comment by euri10** [comment]
Thanks, I didn't know for json and bytes
