### ISSUE TITLE
Improve docs on validator

### ISSUE THREAD

**Issue by dr-leo** [samuelcolvin/pydantic#864]
Please expand the documentation on the args and kwargs supported by `validator` (aside from value, pre and whole). The `config` arg is not sufficiently explained. How does it relate to the model-wide `Config` class? 

In particular, I'd like to understand if I can enable assignment Validation at field Level when it is disabled at model Level.

The above concerns both the online docs and the doc string.

Thanks.

**Comment by samuelcolvin** [comment]
This isn't a bug, but a question and a request for documentation improvements.

`config` is the model wide `Config` object. it can also be accessed on class-decorator-validators because it's use by many of the standard validators and may be useful in custom type validators.

I'd be happy to accept a PR to improve this part of the documentation and the docstring, but I would wait for #856 to be merged first.

> In particular, I'd like to understand if I can enable assignment Validation at field Level when it is disabled at model Level.

I'm not sure this would be possible at the moment (happy to be proved wrong). You can definitely do assignment validation, but AFAIK there's no way of telling the validator that it's being called during assignment rather than initialisation.

**Comment by dr-leo** [comment]
I was indeed unsure about the proper classification of this issue.
 
On assignment Validation: It seems irrelevant to know whether a validator has been called upon initialization or assignment. What matters is that it is called at all. So the question is: If assignment Validation is disabled by model-wide Config, will a custom validator be called upon assignment of a particular field? Put differently, is assignment Validation always model-wide (i.e. all or nothing)? For Performance it could be useful to select individual fields for assignment Validation.

On a separate note: If `pre=False`, when will the custom validator be called in relation to built-in validators? Always last? 

And does `pre=True` solely alter the calling sequence amongst validators for the given field even when there are custom validators for multiple fields?  

 At this Point you'll have realized that I am a newbie.

**Comment by samuelcolvin** [comment]
The easiest thing in situations like this is to consult the source (that's not a fob-off "do it yourself" answer, it's honestly the quickest route to an answer, all I'm doing at this point is checking the source myself).

One of the underrated advantages of writing python (vs. c, c++ or rust) is that the source is a (mostly) human-readable absolute definition of logic.

> Put differently, is assignment Validation always model-wide (i.e. all or nothing)?

Currently, yes:

https://github.com/samuelcolvin/pydantic/blob/799cd370fe78b4172a81f5dc6ea5ad086bbd2978/pydantic/main.py#L259-L264

> If `pre=False`, when will the custom validator be called in relation to built-in validators? Always last?

yes:

https://github.com/samuelcolvin/pydantic/blob/799cd370fe78b4172a81f5dc6ea5ad086bbd2978/pydantic/fields.py#L449-L450

> And does `pre=True` solely alter the calling sequence amongst validators for the given field even when there are custom validators for multiple fields?

Not entire sure what you mean here, but `pre=True` means that that validator is added to `pre_validators` which are called before all other validation for that field:

https://github.com/samuelcolvin/pydantic/blob/799cd370fe78b4172a81f5dc6ea5ad086bbd2978/pydantic/fields.py#L425-L428

The only slight complexity here is the special `Json` type which will be added to the end of `pre_validators` and will therefore be called after any other pre validators:

https://github.com/samuelcolvin/pydantic/blob/master/pydantic/fields.py#L415

---

Hope that all makes sense. Please ask if you need more clarification. I agree lots of this could do with ending up in the documentation and perhaps we should be more willing to link to the source when explaining logic.

**Comment by dr-leo** [comment]
Thanks. This is very helpful. And I realize there is merit in taking time to look at the sources before asking such Questions. 

Last question, I promise: Why can custom validators be passed a Config object even though it can (and maybe should) be accessed via `cls.Config`?

I'll consider filing a PR to make the docs a bit more explicit.

**Comment by samuelcolvin** [comment]
You should use `cls.__config__` not `cls.Config` as the second won't be set unless you have an explicit Config object, also I'm not sure it will benefit from the inheritance logic.

The reason it exists is that the same logic is used to call all validators, not just class decorator validators, look at `validators.py` for many examples of config's usage.

**Comment by dr-leo** [comment]
Thanks for These hints. I'll look into this asap.
