### ISSUE TITLE
Is it possible to have a schema with no $ref references ?

### ISSUE THREAD

**Issue by neimad1985** [samuelcolvin/pydantic#889]
Versions:
* OS: Ubuntu 18.04
* Python: 3.7.4
* Pydantic: 0.32.2

Hi,

First of all a huge thanks for the great work done on this package, glad that you are reaching version 1.0 soon !

I have the following simple models: a car and an engine, a car holds an engine.

```py
from pydantic import BaseModel

class Engine(BaseModel):
    size: int

class Car(BaseModel):
    engine: Engine
```

If I print the car's schema I get this:

```py
print(Car.schema_json(indent=4, sort_keys=True))

# >>> {
#     "definitions": {
#         "Engine": {
#             "properties": {
#                 "size": {
#                     "title": "Size",
#                     "type": "integer"
#                 }
#             },
#             "required": [
#                 "size"
#             ],
#             "title": "Engine",
#             "type": "object"
#         }
#     },
#     "properties": {
#         "engine": {
#             "$ref": "#/definitions/Engine"
#         }
#     },
#     "required": [
#         "engine"
#     ],
#     "title": "Car",
#     "type": "object"
# }
```

I would prefer very much to have this, a recursive engine schema inside the car's one:

```py
# >>> {
#     "definitions": {},
#     "properties": {
#         "engine": {
#             "properties": {
#                 "size": {
#                     "title": "Size",
#                     "type": "integer"
#                 }
#             },
#             "required": [
#                 "size"
#             ],
#             "title": "Engine",
#             "type": "object"
#         }
#     },
#     "required": [
#         "engine"
#     ],
#     "title": "Car",
#     "type": "object"
# }
```

The pydantic documentation states that:
> “sub-models” with modifications (via the Schema class) like a custom title, description or default value, are recursively included instead of referenced.

So I tried and modified my code by using the Schema class to trigger something but still did not obtain what I wanted:

```py
from pydantic import BaseModel
from pydantic import Schema

class Engine(BaseModel):
    size: int = Schema(..., title="a size")

class Car(BaseModel):
    engine: Engine = Schema(..., title="an engine")

print(Car.schema_json(indent=4, sort_keys=True))

# >>> {
#     "definitions": {
#         "Engine": {
#             "properties": {
#                 "size": {
#                     "title": "a size",
#                     "type": "integer"
#                 }
#             },
#             "required": [
#                 "size"
#             ],
#             "title": "Engine",
#             "type": "object"
#         }
#     },
#     "properties": {
#         "engine": {
#             "allOf": [
#                 {
#                     "$ref": "#/definitions/Engine"
#                 }
#             ],
#             "title": "an engine"
#         }
#     },
#     "required": [
#         "engine"
#     ],
#     "title": "Car",
#     "type": "object"
# }
```

Instead I got a "allOf" in the car's schema which I do not understand and still no recursive engine schema.

My question is: is it possible to achieve what I want ? No definitions sections, just recursive schemas.

I know I could have some problems with cross referencing schemas (A referencing B and B referencing A), but I do not care of this detail since I know my schemas do not have this kind of thing.

Did I miss or misunderstood something in the documentation (which I read several times) ?
I even tried to inspect pydantic's code to find an answer but the section (schema.py) which generates the schemas is a bit too complicated for me.

Thank you for your time and go on with the greak work :)

**Comment by neimad1985** [comment]
Kind ping ? :)

**Comment by samuelcolvin** [comment]
It's not possible to achieve what you want right now, you'd have to either manually create your schema or manually re-arrange the dict returned from `schema()`.

I don't know if what you're desiring is even valid JSON Schema? But either way I think it's beyond the bounds of pydantic to provide this level of flexibility.

**Comment by neimad1985** [comment]
Ok thank you for responding :)

**Comment by samuelcolvin** [comment]
@dmontagu @tiangolo, I'm not that good on JSON schema.

Would the above request be valid JSON scheme?

**Comment by dmontagu** [comment]
Based on my reading of [these docs](https://json-schema.org/understanding-json-schema/structuring.html), it seems to me the use of `$ref` is optional. So I think this is a valid JSON schema.

That said, my strong suspicion is that it would be rather painful to support both kinds of generation.

Certainly any heavy refactoring of the logic behind the schema generation would not be fun, and I personally would be loathe to try to implement a feature like this (especially considering I leave the consumption of the schema to tooling, so am not concerned with the details of its structure). Moreover, I know fastapi makes use of some relatively raw output of pydantic in order to build the openapi schema, and that logic may need attention if another kind of output were added.

But it *might* be possible without *too* much work by using a config value to tell subsequent calls to not build the schema using references. If someone worked on this and was able to produce a clean implementation that didn't add substantial complexity I wouldn't necessarily be opposed.

Overall though, this seems like it would add a lot more ongoing cognitive burden that it would be worth -- debugging and/or tweaking the schema generation is already very difficult due to the many recursive function calls and relatively complex logic, and this would add a fork somewhere deep in the heart of it all.

**Comment by dmontagu** [comment]
I would not be opposed to adding utilities for post-processing the generated schema(s) though.

**Comment by samuelcolvin** [comment]
as per #892, perhaps `schema_extra` should accept a function which mutates the schema after it's generated. (or add another Config setting)

We could then provide a standard method for rearranging the schema to insert sub-model schemas inline.

That would sound like the simplest work around?

**Comment by dmontagu** [comment]
Yeah, support for a schema-postprocessing function would be great!

**Comment by knowBalpreet** [comment]
I am using pydantic with fastapi, and have JSON schemas available for all models. Currently, there is no way for me to use them directly, If I put the entire schema in `schema_extra`, I can see the apt model in UI. But the validation does not work. Is there a way to support this?

**Comment by samuelcolvin** [comment]
> Currently, there is no way for me to use them directly

please explain what you mean by this.

**Comment by knowBalpreet** [comment]
I have the json schemas available for models, I want to use them directly with my routes. Currently, i am putting entire json schema like following:

```py
class AddBrand(BaseModel):
  class Config:
    schema_extra = {
        "properties": {
            "name": field('string', description="Name of the brand", minLength=1, example="Tyroo"),
            "image_url": field('string', description="Main Logo of the brand", minLength=1, example="http://vidtech.ai/images/place-holder-0.png"),
            "guidelines": {
                "type": "object",
                "properties": {
                    "colors": {
                        "type": "object",
                        "properties": {
                            "primary": field('array', minItems=2, maxItems=2, items=field('string')),
                            "secondary": field('array', minItems=4, maxItems=4, items=field('string'))
                        },
                        "required": [
                            "primary",
                            "secondary"
                        ]
                    }
                },
                "required": [
                    "colors"
                ]
            },
            "duration_cap": field('integer', description="Maximum duration length for a video", example=-1),
            "custom_attributes": {
                "type": "object",
                "properties": {
                    "fonts": field('array', description="Brand specific fonts", items=field('string')),
                    "templates": field('array', description="Brand specific templates", items=field('string')),
                    "audios": field('array', description="Brand specific audios", items=field('string'))
                },
                "required": [
                    "fonts",
                    "templates",
                    "audios"
                ]
            },
            "hardcodings": {
                "type": "object",
                "description": "Hardcodings for the brand",
                "properties": {
                    "background": {
                        "type": "object",
                        "properties": {
                            "use": field('boolean', description="Should we use background or not?"),
                            "templates": field('array', description="On which templates should we reflect these changes?", items=field('string')),
                            "media": {
                                "type": "object",
                                "properties": {
                                    "type": field('string', description="Type of media. image/video/etc'"),
                                    "value": field('string', description="Value of the selected media type")
                                },
                                "required": [
                                    "type",
                                    "value"
                                ]
                            },
                            "resizer": {
                                "type": "object",
                                "properties": {
                                    "type": field('string', description='The type of resizer', example='balli', enum=['smart', 'stupid', 'balli']),
                                    "position": field('string', example='center', description='The alignment of image in placeholder', enum=['left', 'top', 'center', 'bottom', 'right']),
                                    "background": field('string', example='extend_bg', description='The background of image.', enum=['transparent', 'blur', 'extend_bg'])
                                },
                                "required": [
                                    "type",
                                    "position",
                                    "background"
                                ]
                            }
                        },
                        "required": [
                            "use",
                            "templates",
                            "media",
                            "resizer"
                        ]
                    }
                }
            },
            "metadata": {
                "type": "object",
                "properties": {
                    "feeds": field('array', items=field('string'), description="Unique ids of all product feeds")
                }
            }
        },
        "required": [
            "name",
            "image_url"
        ]
    }
```
This creates model on ui, but it does not validate the input data. I want the capability to parse input data like it does when i create classes for everything

**Comment by knowBalpreet** [comment]
and will the post-processor work like an original validator? Also, will it be viable if I continue with this approach for defining models and probably will get support for this? Because it is too much pain to create 8-10 level deep models, also getting all those models on UI which are of no use.
Thanks in advance!

**Comment by knowBalpreet** [comment]
bump

**Comment by samuelcolvin** [comment]
Please stop "bump"ing. I'm not paid to answer your questions.

The solution is described above. Read it.

**Comment by dmontagu** [comment]
@knowBalpreet It sounds like you might be trying to generate a model from a schema? This is not currently possible directly in pydantic.

Perhaps try looking at https://github.com/koxudaxi/datamodel-code-generator?

**Comment by dmontagu** [comment]
I see. Then yeah, I don't think this is supported.

> and will the post-processor work like an original validator? Also, will it be viable if I continue with this approach for defining models and probably will get support for this? Because it is too much pain to create 8-10 level deep models, also getting all those models on UI which are of no use.
Thanks in advance!

I don't think there has been much interest in "cleaning up" the generated schemas. I don't think there will be much official support for this going forward unless there is more demand, or unless you are willing to contribute it yourself. (And it doesn't bring undesirable amounts of additional complexity.)

**Comment by Pietervanhalem** [comment]
I found a Postprocessing fix for this using recursion. This transformation also works for definitions in definitions and so on.

```python
from pydantic import BaseModel
import json
MAX_TRIES = 100

def replace_value_in_dict(item, original_schema):
    if isinstance(item, list):
        return [replace_value_in_dict(i, original_schema) for i in item]
    elif isinstance(item, dict):
        if list(item.keys()) == ['$ref']:
            definitions = item['$ref'][2:].split('/')
            res = original_schema.copy()
            for definition in definitions:
                res = res[definition]
            return res
        else:
            return { key: replace_value_in_dict(i, original_schema) for key, i in item.items()}
    else:
        return item

class Engine(BaseModel):
    size: int

class Car(BaseModel):
    engine: Engine
        
        
schema = Car.schema()
for i in range(MAX_TRIES):
    if '$ref' not in json.dumps(schema):
        break
    schema = replace_value_in_dict(schema.copy(), schema.copy())
    
del schema['definitions']
print(json.dumps(schema, indent=4))
```
gives
```
{
    "title": "Car",
    "type": "object",
    "properties": {
        "engine": {
            "title": "Engine",
            "type": "object",
            "properties": {
                "size": {
                    "title": "Size",
                    "type": "integer"
                }
            },
            "required": [
                "size"
            ]
        }
    },
    "required": [
        "engine"
    ]
}
```

**Comment by italovieira** [comment]
One option is to use jsonref:

```python
import jsonref
...

jsonref.loads(Car.schema())

```
I just don't know how it compares in performance.

**Comment by Hubro** [comment]
I am trying to use the schema exported from Pydantic [as my database schema in rxdb](https://rxdb.info/rx-schema.html). However, it doesn't seem like rxdb schemas support "$ref", as it crashes with a complaint about my key names not matching the property name regex. Exporting JSON schemas with no "$ref"s would be very helpful for this scenario.

**Comment by triumph1** [comment]
> One option is to use jsonref:
> 
> ```python
> import jsonref
> ...
> 
> jsonref.loads(Car.schema_json())
> ```
> 
> I just don't know how it compares in performance.

YOU SAVED MY DAY
thank you so much!!

**Comment by aditrades** [comment]
> One option is to use jsonref:
> 
> ```python
> import jsonref
> ...
> 
> jsonref.loads(Car.schema_json())
> ```
> 
> I just don't know how it compares in performance.

Great approach. exactly what I was looking for!

**Comment by bkis** [comment]
For anyone needing the [jsonref](https://pypi.org/project/jsonref/)-based solution from above adjusted to Pydantic v2, where `BaseModel.schema_json()` (which returned a `str`) has been "replaced" by `BaseModel.model_json_schema()` (which returns a `dict[str, Any]`), this seems to work just fine:

```py
jsonref.replace_refs(SomeModel.model_json_schema())
```

**Comment by Viicos** [comment]
This issue is now tracked in https://github.com/pydantic/pydantic/issues/12023.
