### ISSUE TITLE
JSON Schema with external $ref as a model

### ISSUE THREAD

**Issue by miniscruff** [samuelcolvin/pydantic#892]
# Feature Request
I have begun to use pydantic models to create JSON schema files to publish and reference internally on my team. This has allowed us to create very easy to read python classes that create well-defined JSON schemas. The process has been really smooth so far and I am very grateful to all the work that has been put into this project.

My process is basically to create models, take the schema, wrap that schema with some extra metadata, create a JSON file and push it to one of our servers.

I have run into two, rather small, problems. ( I may create another issue for the second one later ) The first of which is the inability to reference external JSON schemas as a field. Such as one from here http://schemastore.org/json/.

An example test case would be:
```py
def test_model_with_ref_only():
    class Dep(BaseModel):
        class Config:
            schema_ref = "http://example.com/schema.json"

    class Model(BaseModel):
        dep: Dep

    expected = {
        'title': 'Model',
        'type': 'object',
        'properties': {'dep': {'$ref': 'http://example.com/schema.json'}},
        'required': ['dep'],
    }

    assert Model.schema() == expected
```
Note that the model is not added as a definition as well as $ref being the only field.

And I am sure there are other alternatives that would solve this problem but I felt this matched the existing configurations well, but of course, if another approach or naming would make more sense let me know.

I have forked, branched and written the code to handle this test case but wanted to bring it up as an issue first. If this looks right to you I can make a pull request or wait for version 1.0.

**Comment by samuelcolvin** [comment]
sorry for the slow response, not sure how this slipped through the gaps.

Couldn't this be done now with `schema_extra`? or by allowing function for `schema_extra` which allowed you to modify the schema?

That would seem like a more flexible solution.

**Comment by miniscruff** [comment]
No problem, I thought I tried schema_extra before but I guess I didn't do a good job as it worked just fine today in the office.

It does create an extra model and includes the title and empty properties object but VS Code seems to deal with it fine and provides the help I expect.

```
class Dep(BaseModel):
        class Config:
            schema_extra = {
                "$ref": "http://example.com/schema.json",
            }

    class Model(BaseModel):
        dep: Dep
```
Is what I have and it works just fine. ( Although I just typed this out now so I will check when I go in tomorrow to make sure. )

**Comment by dmontagu** [comment]
Just adding a note here for future reference if anyone tries to implement this -- it should probably be possible to make use of a classmethod to generate the schema to make it easier to inspect the actual class during schema generation.

**Comment by miniscruff** [comment]
I will close this issue as it works as expected and what I would of done would just be a weird special case.

**Comment by mcgfeller** [comment]
### Beware in Pydantic 2:

The `$ref` value must not be a str (leads to erros in JSON Schema generation in 2.5). It should be a jsonable non-str object. According to https://cswr.github.io/JsonSchema/spec/definitions_references/, it must be a JSON reference within the schema, or an URI. So you may use `AnyUrl`, which works fine.

**Comment by glopesdev** [comment]
@mcgfeller I came up against this exact problem, but my `$ref` needs to be a file reference, e.g. `{ "$ref" : "schema.json" }`. This string cannot be passed directly to `AnyUrl` but it is valid to write by hand in a JSON schema. Not sure how to pass it to a PydanticV2 model without having Pydantic try to interpret this as a local reference.

Also note for anyone hitting this issue, `schema_extra` has been renamed to `json_schema_extra`.

What I have right now:

```
class ModelRef(BaseModel):
    class Config:
        json_schema_extra = {
            "$ref": "schema.json"
        }
```

Crashes with `KeyError`:

```
    defs_ref = self.json_to_defs_refs[json_ref]
               ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'schema.json'
```

**Comment by mcgfeller** [comment]
@glopesdev : If you use a str like  `"schema.json"`, it goes through the code path that raises the `KeyError`. You cannot use anything that is `isinstance(anything ,str)`.

Try `pathlib.Path` for the filename - it's not a subclass of str (so doesn't go through the key lookup code), but should still be jsonable.

**Comment by glopesdev** [comment]
> Try pathlib.Path for the filename - it's not a subclass of str (so doesn't go through the key lookup code), but should still be jsonable.

@mcgfeller Thank you for the suggestion, it did sound very reasonable and I had not thought about it. Sadly, it does not solve the problem. Rewriting the model like this:

```
class ModelRef(BaseModel):
    class Config:
        json_schema_extra = {
            "$ref": Path("schema.json")
        }
```

Results in the following `TypeError`:

```
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type WindowsPath is not JSON serializable
```

**Comment by mcgfeller** [comment]
@glopesdev: You may want to pass the schema dict through `to_jsonable_python` from `pydantic_core`:


```python
schema : dict = ModelRef.model_json_schema()
print(json.dumps(pydantic_core.to_jsonable_python(schema)))
```

If you're in a FastAPI environment, use `jsonable_encoder` from  `fastapi.encoders`, but I think FastAPI does apply this automatically from JSON output.

**Comment by glopesdev** [comment]
> You may want to pass the schema dict through to_jsonable_python from pydantic_core

@mcgfeller Thank you so much, it works beautifully now!

For some reason I was not realizing that it was actually the final serialization step which was failing and not the schema generation itself. It feels there should be an easier way to specify all of this, but it works for now.

**Comment by glopesdev** [comment]
@mcgfeller It turns out that `Path` still doesn't work for a slightly modified example:

```python
class ModelRef(BaseModel):
    class Config:
        json_schema_extra = {
            "$ref": Path("schema.json#/$defs/ModelType")
        }
```

The problem is that using `Path` on windows will convert all forward slashes to backslashes and make the `$ref` path non-canonical.

I have to confess going in I never expected passing a simple string literal would turn out to be so complicated!

**Comment by mcgfeller** [comment]
@glopesdev Hmm, it gets a bit messy. You can use `pathlib.PurePosixPath` instead of Path, so you'll get Posix semantics even if you're on Windows. 

However, this isn't registered in `to_jsonable_python`, so you need to tell it to `serialize_unknown` - it serializes it as `str()`,  so you're finally at a string again....

``` Python
print(json.dumps(pydantic_core.to_jsonable_python(schema, serialize_unknown=True)))
``` 
If you use `jsonable_encoder` from `fastapi.encoders`, you won't need that trick, as it probably works for subclasses of classes it can encode.

However, if you want to follow a [JSON schema standard](https://json-schema.org/understanding-json-schema/structuring), you will probably need something like  [`AnyUrl`](https://docs.pydantic.dev/latest/api/networks/#pydantic.networks.AnyUrl) from Pydantic and  fill it with the URL form of a filename, like `pydantic.AnyUrl("file:///schema.json#/$defs/ModelType")`

Pydantic should really support the standard a bit better here.

**Comment by glopesdev** [comment]
Thank you @mcgfeller again for your insights. I will consider our options in the near-term, but in the meantime I have also opened a new issue to discuss explicitly this edge case.
