### ISSUE TITLE
Disable all validations

### ISSUE THREAD

**Issue by prostomarkeloff** [samuelcolvin/pydantic#897]
# Question

Please complete:
* OS: Ubuntu 18.04
* Python version `import sys; print(sys.version)`:
3.7.3 (default, Apr  3 2019, 19:16:38) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.32.2

Hello anyone,
It possible to disable all validations of incoming data?

```py
import pydantic

class MyModel(pydantic.BaseModel):
    class Config:
        validation = False

...
```

**Comment by dmontagu** [comment]
I am also very interested in this question, as in many cases in my code I *know* the values are correct and don't require validation. It would also be nice to have an API for initializing a model instance from known-valid inputs without needing to go through the various alias-lookups etc.

In general though I wouldn't want to disable the validation at the *model* level, but rather on a per-initialization basis. (So a separate classmethod for initializing from known-valid values would be nice.)

I *think* this is possible in one way or another; I'll see if I can make any progress.

----

@prostomarkeloff if you really do want "models" with validation disabled, you might try using vanilla dataclasses?

**Comment by dmontagu** [comment]
Okay, yes, I got this working (based on `BaseModel.validate`):

The following method could be added to your model subclass if you want to do 100% unvalidated assignment:
```python
    @classmethod
    def unvalidated(__pydantic_cls__: "Type[Model]", **data: Any) -> "Model":
        for name, field in __pydantic_cls__.__fields__.items():
            try:
                data[name]
            except KeyError:
                if field.required:
                    raise TypeError(f"Missing required keyword argument {name!r}")
                else:
                    data[name] = field.default
        self = __pydantic_cls__.__new__(__pydantic_cls__)
        object.__setattr__(self, "__dict__", data)
        object.__setattr__(self, "__fields_set__", set(data.keys()))
        return self
```

I did some performance tests and for data-heavy models, and the performance difference is enormous:

<details>
    <summary>Click to expand the benchmark script</summary>

```python
from contextlib import contextmanager
import time
from datetime import datetime
from typing import List, Dict, Iterator

from pydantic import BaseModel


class DoubleNestedModel(BaseModel):
    number: int
    message: str


class SubDoubleNestedModel(DoubleNestedModel):
    timestamps: List[datetime]


class NestedModel(BaseModel):
    number: int
    message: str
    double_nested: DoubleNestedModel


class SubNestedModel(NestedModel):
    timestamps: List[datetime]


class Model(BaseModel):
    nested: List[Dict[str, NestedModel]]


class SubModel(Model):
    other_nested: Dict[str, List[NestedModel]]
    timestamps: List[datetime]


def get_sub_model(timestamp: datetime) -> SubModel:
    timestamps = [timestamp] * 5
    sub_double_nested = SubDoubleNestedModel(number=1, message="a", timestamps=timestamps)
    sub_nested = SubNestedModel(number=2, message="b", double_nested=sub_double_nested, timestamps=timestamps)

    nested = [{letter: sub_nested for letter in 'abcdefg'}]
    other_nested = {letter: [sub_nested] * 5 for letter in 'abcdefg'}
    return SubModel(nested=nested, other_nested=other_nested, timestamps=timestamps)


def get_sub_model_unvalidated(timestamp: datetime) -> SubModel:
    timestamps = [timestamp] * 5
    sub_double_nested = SubDoubleNestedModel.unvalidated(number=1, message="a", timestamps=timestamps)
    sub_nested = SubNestedModel.unvalidated(number=2, message="b", double_nested=sub_double_nested,
                                            timestamps=timestamps)

    nested = [{letter: sub_nested for letter in 'abcdefg'}]
    other_nested = {letter: [sub_nested] * 5 for letter in 'abcdefg'}
    return SubModel.unvalidated(nested=nested, other_nested=other_nested, timestamps=timestamps)


@contextmanager
def basic_profile(label: str) -> Iterator[None]:
    t0 = time.time()
    yield
    t1 = time.time()
    print(f"{label}: {(t1 - t0):,.3f}s")


def run():
    n_warmup_runs = 1000
    n_runs = 10000

    timestamp = datetime.utcnow()
    sub_model = get_sub_model(timestamp)
    unvalidated_sub_model = get_sub_model_unvalidated(timestamp)

    assert sub_model == unvalidated_sub_model

    for _ in range(n_warmup_runs):
        get_sub_model(timestamp)
        get_sub_model_unvalidated(timestamp)

    with basic_profile("validated"):
        for _ in range(n_runs):
            get_sub_model(timestamp)

    with basic_profile("unvalidated"):
        for _ in range(n_runs):
            get_sub_model_unvalidated(timestamp)


run()
```
</details>

The result:
```
validated: 2.918s
unvalidated: 0.083s
```
That's a 35x speedup. Not surprising, given that validators are called on each list element / dict value. But I think it may be worth using an API like this if you know it's safe.

Note: in my testing, removing the field checks and default value inference sped things up even further to an ~43x speedup, but I think having the field and default checks are worthwhile.

@samuelcolvin do you think there is any room for a method like this on the `BaseModel` class? (Maybe with a little more polish in case I'm mishandling some edge cases?) Or do you think this should be left to users to implement at their own risk?

**Comment by samuelcolvin** [comment]
This is what `construct` is for:

https://github.com/samuelcolvin/pydantic/blob/6cda388c7a1af29d17973f72dfebd98cff626988/pydantic/main.py#L417

It definitely needs documenting but I don't think we need a new method.

If it's signature needs changing to do what you want, we should do that pre v1 if possible.

**Comment by dmontagu** [comment]
@samuelcolvin I wasn't aware of that, that's nice.

It seems to me that 1) support for default values, and 2) not needing to manually specify the `fields_set` would go a long way toward making it more of a drop in replacement for `__init__` when the input data is known-valid.

I think it would be easier to justify the refactor efforts if it was literally just a matter of adding `.construct` for the speed up, as opposed to the more potentially involved refactor currently required.

**Comment by dmontagu** [comment]
I would be in favor of a private method like `_construct` instead of what is currently called `construct`, and have `construct` use defaults if missing and set the `fields_set` based on the keyword arguments provided.

I would also understand if you didn't want to add a breaking API change this far into the 1.0 beta stuff. I would definitely be in favor of adding the above-described functionality though even if it needs to be a different method name or a private call. But I can always just define it on custom base class, so it's not the end of the world.

**Comment by prostomarkeloff** [comment]
> I am also very interested in this question, as in many cases in my code I _know_ the values are correct and don't require validation. It would also be nice to have an API for initializing a model instance from known-valid inputs without needing to go through the various alias-lookups etc.
> 
> In general though I wouldn't want to disable the validation at the _model_ level, but rather on a per-initialization basis. (So a separate classmethod for initializing from known-valid values would be nice.)
> 
> I _think_ this is possible in one way or another; I'll see if I can make any progress.
> 
> @prostomarkeloff if you really do want "models" with validation completely disabled under all circumstances, you might try using vanilla dataclasses?

Thank you for answer! What about dataclasses? Firstly, i don't want to mix really different libraries in one project, secondly, dataclasses slower than pydantic. Some models in my project need this feature.

**Comment by prostomarkeloff** [comment]
> Okay, yes, I got this working (based on `BaseModel.validate`):
> 
> The following method could be added to your model subclass if you want to do 100% unvalidated assignment (beyond checking field names and falling back to default values):
> 
> ```python
>     @classmethod
>     def unvalidated(__pydantic_cls__: "Type[Model]", **data: Any) -> "Model":
>         for name, field in __pydantic_cls__.__fields__.items():
>             try:
>                 data[name]
>             except KeyError:
>                 if field.required:
>                     raise TypeError(f"Missing required keyword argument {name!r}")
>                 if field.default is None:
>                     # deepcopy is quite slow on None
>                     value = None
>                 else:
>                     value = deepcopy(field.default)
>                 data[name] = value
>         self = __pydantic_cls__.__new__(__pydantic_cls__)
>         object.__setattr__(self, "__dict__", data)
>         object.__setattr__(self, "__fields_set__", set(data.keys()))
>         return self
> ```
> 
> I did some performance tests and for data-heavy models, and the performance difference is enormous:
> Click to expand the benchmark script
> 
> The result:
> 
> ```
> validated: 2.918s
> unvalidated: 0.083s
> ```
> 
> That's a 35x speedup. Not surprising, given that validators are called on each list element / dict value. But given the performance benefits I think it may be worth using an API like this if you know it's safe. Currently it's probably bit risky due to the lack of type checking, but it would be very easy to use a mypy plugin to set the signature in the same way currently done in #722 for the `__init__` function. So I think this could be supported in a statically checked way. (Note: this would not call any custom validators or similar.)
> 
> Note: in my testing, removing the field checks and default value inference sped things up even further to an ~43x speedup, but I think having the field and default checks are worthwhile.
> 
> @samuelcolvin do you think there is any room for a method like this on the `BaseModel` class in pydantic proper? (Maybe with a little more polish in case I'm mishandling some edge cases?) Or do you think this should be left to users to implement at their own risk?

Awesome! I think it's what i need.

**Comment by samuelcolvin** [comment]
> I would also understand if you didn't want to add a breaking API change this far into the 1.0 beta. 

Hopefully this wouldn't be much of a breaking change, and it would be to an as-yet undocumented feature.

> I would be in favor of a private method like _construct instead of what is currently called construct, and have construct use defaults if missing and set the fields_set based on the keyword arguments provided.

Please have a look at #898 which is my proposal for how to fix this.

If you think that it would be useful, it'll also need documentation of `construct` adding.

**Comment by trallnag** [comment]
Here is a snipped how I use `construct`:

```python
def enhance_data(request: Request, data: Data) -> EnhancedData:
    """Enhances data in-place by adding attributes.

    Args:
        request (Request): Request object
        data (Data): Data where attributes will be added to.
    """
    
    data = data.dict()

    data["request"] = request

    for alert in data["alerts"]:
        specific = set(alert["annotations"]) - set(data["common_annotations"])
        alert["specific_annotations"] = {k: alert["annotations"][k] for k in specific}

        specific = set(alert["labels"]) - set(data["common_labels"])
        alert["specific_labels"] = {k: alert["labels"][k] for k in specific}

    return EnhancedData.construct(**data)
```

Do give you an idea, @dashsatish

**Comment by mr-bjerre** [comment]
@dashsatish does this help? https://pydantic-docs.helpmanual.io/usage/models/#creating-models-without-validation

**Comment by tanyaofei** [comment]
try this

```python
from pydantic import fields as pydantic_field
pydantic_fields.ModelField.validate = lambda *args, **kwargs: (args[1], None)
```

**Comment by jasonhuling** [comment]
Is there an equivalent to the `construct` method but for scenarios where you may be using `parse_raw_as` or `parse_obj_as`?

**Comment by vadikam100500** [comment]
how to skip validation in v2.3.0?

**Comment by Kludex** [comment]
> How to skip validation in v2.3.0?

We have the `SkipValidation` (https://docs.pydantic.dev/latest/usage/validators/#special-types).

**Comment by smivv** [comment]
Hello guys, is there a way to disable validation for the entire `BaseModel`?
Would be nice to have some flag in `ConfigDict` that will disable validation by default.

**Comment by treykeown** [comment]
For anyone else searching, I made a quick and dirty hack around this. This is ***NOT*** safe for production and is definitely not fully correct.

```py
from pydantic.fields import FieldInfo
from pydantic_core import ArgsKwargs

class NoValidator:
    def validate_python(self, args_kwargs: ArgsKwargs, self_instance):
        model_fields = cast(dict[str, FieldInfo], self_instance.__pydantic_fields__)
        # print(model_fields)
        args = list(args_kwargs.args)
        mapping = dict(args_kwargs.kwargs) if args_kwargs.kwargs else dict()
        for field, info in model_fields.items():
            assert not info.init_var
            if not info.kw_only:
                mapping[field] = args.pop(0)
        for field, value in mapping.items():
            setattr(self_instance, field, value)

YourModel.__pydantic_validator__ = NoValidator()
```

**Comment by NikosAlexandris** [comment]
> try this
> 
> it will disable all validations and **type converting** in your project, and `parse_obj()`, `from_orm()`, `BaseModel#__init__` will loss of ability to convert type, some functions such as fastapi json-deserialize for `str` to `int` , make sure you know what you are doing
> 
> ```python
> from pydantic import fields as pydantic_field
> pydantic_fields.ModelField.validate = lambda *args, **kwargs: (args[1], None)
> ```

Is `pydantic_fields` a typo (against `pydantic_field`) ?

**Comment by NikosAlexandris** [comment]
If I am not wrong, available solutions in Pydantic are not doing a _complete_ switch-off of validation operations. Something that can help to test things at runtime (think of a CLI program for example where each and every function is validated using Pydantic).

- Comment https://github.com/pydantic/pydantic/issues/897#issuecomment-1760587892 means to deactive an existing model, right ?
- Comment https://github.com/pydantic/pydantic/issues/897#issuecomment-1695492233 (i.e. using [model_construct](https://docs.pydantic.dev/latest/api/base_model/#pydantic.main.BaseModel.model_construct) see: https://docs.pydantic.dev/latest/concepts/models/#creating-models-without-validation) means to do the same in a per-model basis 
- Comment https://docs.pydantic.dev/latest/api/functional_validators/#pydantic.functional_validators.SkipValidation is useful in Annotations

It would be interesting and useful to be able to just switch off everything that should happen with Pydantic. Is this possible while still not breaking basic functionality like checking field names and setting default values ?

**Comment by spillai** [comment]
This works for pydantic-v2

```python
from contextlib import contextmanager
from copy import deepcopy

from pydantic import BaseModel


@contextmanager
def disable_validators():
    """Context manager to temporarily disable Pydantic validators."""

    def no_validation_init(self, **kwargs):
        object.__setattr__(self, "__dict__", kwargs)

    print("Disabling Pydantic validators")
    _init = deepcopy(BaseModel.__init__)
    BaseModel.__init__ = no_validation_init
    yield
    BaseModel.__init__ = _init
    print("Re-enabling Pydantic validators")
```

Usage: 
```python
import pytest
from pydantic import BaseModel, Field, ValidationError

class TestModel(BaseModel):
    name: str = Field(default="John", max_length=10)

# Test that validation is enabled by default
with pytest.raises(ValidationError):
    TestModel(name="John Doe cannot be longer than 10 characters")

# Test that validation is disabled when the context manager is used
with disable_validators():
    TestModel(name="John")
    TestModel(name="John Doe cannot be longer than 10 characters")

# Test that validation is re-enabled after the context manager is exited
with pytest.raises(ValidationError):
    TestModel(name="John Doe cannot be longer than 10 characters")
```
