### ISSUE TITLE
Setting default values with Type[T]/Literal does not work as expected

### ISSUE THREAD

**Issue by timonbimon** [samuelcolvin/pydantic#901]
# Bug

Please complete:
* OS: **Mac OSX**
* Python version `import sys; print(sys.version)`: **3.7.3**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **1.02b**

There seems to be a bug specific to the combination of inheritance with the Type[T] fields.

```py
import pydantic
from pydantic import BaseModel
from typing import Union
from typing import Type

class Range(BaseModel):
    dtype: Union[Type[float], Type[int]]

class IntRange(Range):
    dtype: Type[int] = int

IntRange()
```
gives

```
pydantic.error_wrappers.ValidationError: 1 validation error for IntRange
dtype
  field required (type=value_error.missing)
```

whereas

```py
import pydantic
from pydantic import BaseModel
from typing import Union
from typing import Type

class Range(BaseModel):
    dtype: Union[Type[float], Type[int]]

class IntRange(Range):
    dtype: int = 3

IntRange()
```
works as expected.

Addendum:

```py
import pydantic
from pydantic import BaseModel
from typing_extension import Literal

class Range(BaseModel):
    dtype: Literal[float, int]

class IntRange(Range):
    dtype: Literal[int] = int

IntRange()
```
also does not work, so it does not seem to be specific to Type only

**Comment by timonbimon** [comment]
On second inspection it does not seem to be about inheritance but rather setting default values for Type[T] or Literal fields.

```py
class IntRange(BaseModel):
    dtype: Type[int] 
    
IntRange.__fields__
```
gives
```
{'dtype': <ModelField(dtype type=typing.Type[int] required)>}
```
whereas
```py
class IntRange(BaseModel):
    dtype: Type[int] = int
    
IntRange.__fields__
```
gives
```
{}
```

**Comment by dmontagu** [comment]
I don't think `Literal[int]` is meant to work -- see the [`Literal` docs](https://mypy.readthedocs.io/en/latest/literal_types.html).

What version of pydantic are you using? Your first example works for me on the master branch.

**Comment by timonbimon** [comment]
huh, you're right! 

just checked out the repo and installed from source and then it works!
I guess I'll just wait for the next release then :)

Thanks a lot for the quick reply!
