### ISSUE TITLE
Aliased fields feel weird when used with ORM

### ISSUE THREAD

**Issue by notpushkin** [samuelcolvin/pydantic#906]
* OS: Linux ([`bitnami/python:3-prod`](https://github.com/bitnami/bitnami-docker-python))
* Python version: 3.7.0
* Pydantic version: 0.32.2

Say, I wanted to use an ORM object's field called `price_with_discount` in a JSON field `price`:

```py
from dataclasses import dataclass
from pydantic import BaseModel

@dataclass  # for simplicity -- this might as well be any ORM object
class Product:
    price: int

    @property
    def price_with_discount(self):
        return self.price // 2

p = Product(price=500)

class ProductSchema(BaseModel):
    class Config:
        orm_mode = True

    price_with_discount: int = Schema(None, gt=0, alias="price")

ProductSchema.from_orm(p)
#        => <ProductSchema price_with_discount=500>
# expected: <ProductSchema price=250>

_.json()                   
#        => '{"price_with_discount": 500}'
# expected: '{"price": 250}'
```

As for me, this looks the other way around: the schema's field name is suddenly exposed instead of an alias (which was supposed to be a public name), and the value is taken from ORM field denoted by the alias instead of the field name.

**Comment by samuelcolvin** [comment]
surely you mean `# expected: <ProductSchema price_with_discount=250>`? It wouldn't make sense for price to be 250, plus the field is called `price_with_discount`.

But I agree it's weird in this case, however I can understand it looks odd in this situation.

The solution is probably `load_alias` and `dump_alias` #624 which will hopefully implemented in v1.1 or similar?

**Comment by dmontagu** [comment]
Also, note there is some substantially more flexible handling for `from_orm` using custom `GetterDict` types, so you should be able to do anything you want with `from_orm`. But I agree `load_alias` and `dump_alias` may offer a simpler api.

**Comment by samuelcolvin** [comment]
I guess we could also add a `by_alias=True` kw argument to `from_orm`?

**Comment by notpushkin** [comment]
@samuelcolvin Thank you for explanation!

> plus the field is called `price_with_discount`

Seems like I don't understand what “alias” means then :) The docs say its “the public name of the field”, but it is a bit vague in terms of what we consider public. Right now it seems that data from ORM is considered public (it is read from ORM by an alias) and `.json()` value (with `by_alias=False`, which is default) isn't. It might be only me but it definitely is counterintuitive to me. Am I missing something?

> I guess we could also add a `by_alias=True` kw argument to from_orm?

Maybe also a separate `orm_alias` argument to `Schema`?

**Comment by samuelcolvin** [comment]
The reason is that the same logic is used in `from_orm` as is used when creating a model from foreign/public data.

I agree it's confusing, but it's not trivial to fix.

The correct solution for v1 is customising `GetterDict`, `_decompose_class` or using [pre-root-validators](https://pydantic-docs.helpmanual.io/usage/validators/#root-validators). I don't think we need `orm_alias`.
