### ISSUE TITLE
Serialize model with SecretStr

### ISSUE THREAD

**Issue by ashears** [samuelcolvin/pydantic#919]
# Question
I would like to call .dict() method on a model with a secret str type.

The use case is that I want to log this model with the secret still hidden, but need to send the payload with it as the true string.

Currently, I get: TypeError: Object of type SecretStr is not JSON serializable

Is there a function that can be called on a model with SecretStr type that will turn it into a dictionary with the Secrets visible?

Environment:
pydantic: 0.32.2
OS: macOS
python: 3.7.0

**Comment by samuelcolvin** [comment]
Please complete the opening questions of an issue. They are there for a
good reason.

What version of pydantic are you using?

**Comment by ashears** [comment]
Apologies for not including, added to the orginal post

**Comment by ashears** [comment]
After reading this thread: https://github.com/samuelcolvin/pydantic/issues/133, I realize the way I was intending to use it was incorrect and the thread had examples to solve my use case. Closing this issue.
