### ISSUE TITLE
Validate on assignment to attribute

### ISSUE THREAD

**Issue by petroswork** [samuelcolvin/pydantic#92]
Currently pydantic does not validate when I assign to an attribute. Is it possible to perform validations in this case, too?

**Comment by samuelcolvin** [comment]
In theory it should be possible. `__setattr__` is already overridden, so it should be as simple as extending [this](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/main.py#L109-L114).

Happy to accept a PR, but you'll need to add a `Config` option which defaults to false.

**Comment by samuelcolvin** [comment]
fixed via #94
