### ISSUE TITLE
allow_population_by_field_name expected behavior?

### ISSUE THREAD

**Issue by stefanondisponibile** [samuelcolvin/pydantic#920]
# Question

What is the expected behavior of the `allow_population_by_field_name`?
I'll reference #565 here as it stated that:

```
if (User.Config.allow_population_by_alias == True):
    User(first_name='Jeri')  # OK
    User(firstName='Jeri')   # OK
```

This was the expected behavior for me too, and I'm quite sure I also used it like that somewhere in my code.

This seems no longer the case (see example below) since `allow_population_by_field_name` seems to allow population **only** by field name.

**Is this intended?**
If so, may I suggest to change this option to `populate_by_field_name` as it seems to stick more to this behavior?

If not, am I missing something?

Please complete:
* OS: **Ubuntu 18.04.3 LTS**
* Python version `import sys; print(sys.version)`: **3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42)**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **0.32.2** (tested also on **0.30**)

**Please read the [docs](https://pydantic-docs.helpmanual.io/) and search through issues to
confirm your question hasn't already been answered.**

Where possible please include a self contained code snippet describing your question:

```py
from pydantic import BaseModel


class MyModel(BaseModel):
    foo: str = None

    class Config:
        fields = {"foo": {"alias": "bar"}}
        allow_population_by_field_name = True


def populate_by_alias():
    model = MyModel(bar="foobar")
    print(f"Populating by alias (aka 'public name'): {model}")


def populate_by_internal():
    model = MyModel(foo="foobar")
    print(f"Populating by internal                 : {model}")


def main():
    populate_by_alias()
    populate_by_internal()


if __name__ == "__main__":
    main()
...
```

**Comment by samuelcolvin** [comment]
you're using version v0.32.2 but `allow_population_by_field_name` is the new config name as of v1 which isn't yet released, if you try with `pip install pydantic==1.0b2` it should work fine.

I've tried to make this clear at the top of the first page of docs, but I agree it could be clearer.

**Comment by stefanondisponibile** [comment]
Thank you @samuelcolvin , I should've seen that.
