### ISSUE TITLE
Behaviour of keep_untouched is unclear in docs

### ISSUE THREAD

**Issue by retnikt** [samuelcolvin/pydantic#924]
# Bug

* Python version `import sys; print(sys.version)`: 3.7.3
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.32.2

The `keep_untouched` attribute on a model's Config affects the behaviour for properties' **values**, not their **type annotations**. This is unclear, and is also made particularly misleading by the wording of [this error message](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/validators.py#L572):
```
RuntimeError: no validator found for {type_} see `keep_untouched` or `arbitrary_types_allowed` in Config
```
These should both be improved, and perhaps the config attribute's name should also be changed?

**Comment by samuelcolvin** [comment]
I agree the name isn't that clear, but I think it's too late to change.

Happy to accept a PR to update the documentation, or even update the error message if we can do it asap.
