### ISSUE TITLE
Get secrets in json from a model with Secret types

### ISSUE THREAD

**Issue by ashears** [samuelcolvin/pydantic#925]
# Question
Is there a method for exporting a model with the Secrets visible?
For displaying the secrets, I know of the following method:
```
print(sm.password.get_secret_value())
```
Yet this does not apply to exporting an entire model.
What I am thinking would be a method such as: 
```
print(sm.json(display_secrets=True))
```

Currently, I think this would be achieved with the json_encoders config property. 
If this is the case, would that be worth including a line in the Secret types example?

Please complete:
* OS: **macOS, linux**
* Python version: **3.7**
* Pydantic version: **0.32.2**

**Comment by ashears** [comment]
It seems that 
```
    class Config:
        json_encoders = {
            SecretStr: lambda v: v.get_secret_value()
        }
```
Solves my use case in a satisfactory way. 
I would propose that this information should be in the Secret types example, as may be a common use case for this type.
Regardless, I will close this issue as the functionality is understood by me.

**Comment by dmontagu** [comment]
```python
    class Config:
        json_encoders = {
            SecretStr: lambda v: v.get_secret_value()
        }
```
This seems like a bad idea -- anywhere the model gets dumped to json, it will show the secret. While you'd still be safe if you print the model directly, this seems like an easy way to make yourself feel safer than you really are. In particular, if your approach to logging dumps objects to json, you could easily end up including secrets in the logs precisely in a way this type was supposed to help you avoid, and that you wouldn't have done in the first place if you didn't think the secret type was going to keep you safe.

If you are going to use a secret type, I personally think some manual intervention to access the value *should* be required.

**Comment by ashears** [comment]
Thanks for the input @dmontagu !
I can see what you mean. I'll think some more about it.
At first that was what I had, a standard dict that I manually sanitized.

I wanted to log something before using it as a request payload, and thought the SecretStr type could be a clean pythonic way to have a model with a sanitized version and an unsanitized version.

**Comment by dmontagu** [comment]
Can you not just perform the manual conversion to json where necessary? That's what I do in the few places where I use a `SecretX`

**Comment by internetofjames** [comment]
Can we reopen this? I think being able to choose when Secret values are revealed during JSON encoding is an important feature.

For example, in certain places in code, you'd want to serialize the model and keep values secret (e.g. logging). In other areas, you might want to serialize models and reveal the secret value (e.g. serializing a model for a request payload).

@samuelcolvin thoughts on this?

**Comment by samuelcolvin** [comment]
We won't change the default, might be able to make it easier to configure though.

**Comment by internetofjames** [comment]
I dug around in the source code and have come up with this workaround:

```python
from datetime import datetime

from pydantic import BaseModel, SecretStr
from pydantic.json import pydantic_encoder


class SimpleModel(BaseModel):
    foo: str
    bar: SecretStr = None
    baz: int = 1
    dt: datetime = datetime.now()


def show_secrets_encoder(obj):
    if type(obj) == SecretStr:
        return obj.get_secret_value()
    else:
        return pydantic_encoder(obj)


if __name__ == "__main__":
    sm = SimpleModel(foo="foo", bar="secretbar", baz=2)
    print(sm.json(encoder=show_secrets_encoder))
    print(sm.json())
```

Which outputs:
```
{"foo": "foo", "bar": "secretbar", "baz": 2, "dt": "2021-08-30T11:55:35.842227"}
{"foo": "foo", "bar": "**********", "baz": 2, "dt": "2021-08-30T11:55:35.842227"}
```

Not sure how sound this is or if it is the best way to achieve this desired functionality (you'd just modify the check for `SecretBytes`  to handle that type also).

**Comment by internetofjames** [comment]
@samuelcolvin I see, I think making it easier or perhaps just adding some additional documentation might help. See my above example. If this seems like a good solution to you, I'd be happy to open a PR adding it to the documentation.
