### ISSUE TITLE
UrlStr not available anymore in new pydantic version

### ISSUE THREAD

**Issue by jrmlhermitte** [samuelcolvin/pydantic#928]
# Bug
```
In [1]: from pydantic import UrlStr
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-7415c2080b43> in <module>
----> 1 from pydantic import UrlStr

ImportError: cannot import name 'UrlStr' from 'pydantic' (/...../lib/python3.7/site-packages/pydantic/__init__.py)

```
pydantic version 1.0

**Comment by samuelcolvin** [comment]
Please read the docs. Including the release notes, three URL types names have changed.

**Comment by jrmlhermitte** [comment]
it doesn't show up in the release notes [here](https://pypi.org/project/pydantic/)

**Comment by samuelcolvin** [comment]
> Breaking Change: complete rewrite of URL parsing logic

**Comment by dradux** [comment]
> Breaking Change: complete rewrite of URL parsing logic
Seems a bit short on details, in any event I got the "cannot import name 'UrlStr'" error - hopefully this will help others. 
UrlStr has been removed (see https://github.com/samuelcolvin/pydantic/pull/755 for more details). AnyUrl is likely what you should change it to but there's also AnyUrl, AnyHttpUrl, HttpUrl, and HttpsUrl.

**Comment by Lawouach** [comment]
Hei,

I got caught in that one too. Might I suggest the HISTORY to be a bit clearer when fields are removed? Cheers.
