### ISSUE TITLE
Search box on docs

### ISSUE THREAD

**Issue by euri10** [samuelcolvin/pydantic#931]
# Feature Request
there is none or I have an issue with the site ?
is it possible to have one please (https://www.mkdocs.org/user-guide/configuration/#search)

Please complete:
* OS: **?**
* Python version `import sys; print(sys.version)`: **?**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **?**

**Please read the [docs](https://pydantic-docs.helpmanual.io/) and search through issues to
confirm your feature hasn't been asked for before, or already implemented.**

![img](https://i.imgur.com/sUDLScN.png)

**Comment by samuelcolvin** [comment]
weird, it used to be there, now has vanished.

**Comment by samuelcolvin** [comment]
thanks for reporting, fixed and deployed.
