### ISSUE TITLE
Create fake model in Config.schema_extra

### ISSUE THREAD

**Issue by chbndrhnns** [samuelcolvin/pydantic#937]
# Question

I am using pydantic with FastAPI and would like to auto-generate example models based on the pydantic schema. I know that I can make use of `schema_extra` in the inner `Config` class. 

However, I am missing a way to generate this property out of a `fake()` method or based on the defaults. There is no `self` and no `cls` instance available in `Config` to access outside methods or properties.

Is there a suggested way to achieve this and have it all in one place? (like schema, config, example).

May it is my knowledge of Python that is lacking here. Then I would still like to be enlightened.

Please complete:
* OS: macOS 10.14.6
* Python version: 3.7.4
* Pydantic version: 0.32.2

Where possible please include a self contained code snippet describing your question:

```py
import pydantic

class M(BaseModel):
    id: int

    @classmethod
    def fake(cls):
        return cls(
            id=random.randint(0, 1000)
        )

    class Config:
        schema_extra = {
            'example': {
                'id': 1
            }
        }

m = M(id=1)
```

**Comment by samuelcolvin** [comment]
If I've understood this, it should be possible by allowing `schema_extra` to be a function, see #892.

Let me know if not.

**Comment by dmontagu** [comment]
@samuelcolvin We should make sure the solution to #892 allows classmethods; I think a naive approach might not handle them, but I also don't think it should be too hard to add support for it. So, I think it's worth trying to get it right the first time.
