### ISSUE TITLE
Add validator for template strings (and TemplateStr type?)

### ISSUE THREAD

**Issue by MrMrRobat** [samuelcolvin/pydantic#938]
# Feature Request

```py
from pydantic import BaseModel, ValidationError, TemplateStr


class Person(BaseModel):
    name: str
    greeting_template: TemplateStr['name']

    @property
    def greeting(self):
        return self.greeting_template.format(name=self.name)


person = Person(name='John', greeting_template='Hello, {name}!')
print(person.greeting)  # Hello, John!

try:
    Person(name='Emmy', greeting_template='Oops!')
except ValidationError as e:
    print(e)
'''
1 validation error for Person
greeting_template
  invalid template string, expected keys: ('name',), actual keys: () (type=value_error.str.template; expected_keys=('name',); actual_keys=())
'''
```
I think this kind of validator can be useful.

Also, do you think it should be a separate type like in example, or should it be implemented in constr?
Once we agree on implementation details, I can make a PR.

**Comment by samuelcolvin** [comment]
Is there a safe way to do the substitution?

http://lucumr.pocoo.org/2016/12/29/careful-with-str-format/

**Comment by dmontagu** [comment]
So basically, f-strings pose injection risks. That's a very interesting vulnerability! Thanks for sharing @samuelcolvin I wasn't aware of that.

**Comment by samuelcolvin** [comment]
Yes. 

Alternative is our own templating logic (horror), or using an external library, but must of them don't allow untrusted templates.

**Comment by MrMrRobat** [comment]
Well, that's good catch, @samuelcolvin

We have built-in string.Formatter.parse method, which gives us information about formatted string keys:

```py
import json
from string import Formatter

ALLOWED_KEY = 'name'


def check_str(string: str):
    for literal_text, field_name, format_spec, conversion in Formatter().parse(string):
        print(json.dumps(locals(), indent=4))
        print(field_name == ALLOWED_KEY)


check_str('Harmless hello to {name}')
check_str('Potential injection attack to {name.__class__}')
"""
{
    "conversion": null,
    "format_spec": "",
    "field_name": "name",
    "literal_text": "Harmless hello to ",
    "string": "Harmless hello to {name}"
}
True
{
    "conversion": null,
    "format_spec": "",
    "field_name": "name.__class__",
    "literal_text": "Potential injection attack to ",
    "string": "Potential injection attack to {name.__class__}"
}
False

"""
```

So in my implementation, this vulnerabilities will be eliminated on validation.

**Comment by samuelcolvin** [comment]
Okay, that's interesting, but what do we allow?

Just simple string substitution, or things like formatters, getitem, some getattr?

Also native formatting does allow "if" blocks and loops.

Surely better to leave this out of pydantic and let people do it their own way.

I don't think this requires any other changes to pydantic does it?

**Comment by MrMrRobat** [comment]
> Surely better to leave this out of pydantic and let people do it their own way.

Agreed. So I guess a simplest way to resolve it is to check the keys as they were written in type so `TemplateStr['name.__class__!r:20']` will allow strings with exactly same key: `'foo {name.__class__!r:20}'` and not `'foo {name!r}'` or `'{name.__class.__name__}'`, etc.

> I don't think this requires any other changes to pydantic does it?

Don't think so either

**Comment by samuelcolvin** [comment]
What do others think?

Feedback very welcome.

Would you ever use this feature?

See #942 for an example implementation.

**Comment by koxudaxi** [comment]
I don't know when we need the feature.
Also, I have read the example, I feel it is too difficult to understand. (eg:  `d: TemplateStr[3]` number is a count of positional argument)

@MrMrRobat 
I think you should tell us when we need the feature with **real** case.
I don't find the situation.

**Comment by MrMrRobat** [comment]
> I think you should tell us when we need the feature with real case.

Well, now I'm building a service where some strings could be edited from external API and reloaded in application. So this type is very useful in this case, when you need to make sure that they have all needed keys and no additional keys in them.

Other case is when we use some environment variables, config, etc, which must contain specific key/keys.

For example:
```py
class Messages(BaseModel):
    greeting: TemplateStr['username']
    wrong_action: TemplateStr['action']
    ...

with open('messages.json') as f:
    messages = Messages(**json.load(f))

**Comment by samuelcolvin** [comment]
Sorry I'm being dumb, I'm still not clear from this example what `TemplateStr` does.

**Comment by MrMrRobat** [comment]
No problem!  Does this one seems clearer?

```py
from pydantic import BaseModel, ValidationError, TemplateStr


class Messages(BaseModel):
    greeting: TemplateStr['username']
    wrong_action: TemplateStr['action']

good_messages = {
    'greeting': 'Hello, {username}!', 'wrong_action': 'This is wrong: {action}'
}
bad_messages = (
    {'greeting': 'Hello, world!', 'wrong_action': 'Oops, that was wrong'},
    {'greeting': 'Hello, {username} and {othername}', 'wrong_action': '{action.__class__}'}
)

Messages(**good_messages)  # ok!

for bad in bad_messages:
    try:
        Messages(**bad)
    except ValidationError as e:
        print('\n', e)

'''
 2 validation errors for Messages
greeting
  invalid template string, expected keys: {'username'}, actual keys: set() (type=value_error.str.template; expected_keys={'username'}; actual_keys=set())
wrong_action
  invalid template string, expected keys: {'action'}, actual keys: set() (type=value_error.str.template; expected_keys={'action'}; actual_keys=set())

 2 validation errors for Messages
greeting
  invalid template string, expected keys: {'username'}, actual keys: {'othername', 'username'} (type=value_error.str.template; expected_keys={'username'}; actual_keys={'othername', 'username'})
wrong_action
  invalid template string, expected keys: {'action'}, actual keys: {'action.__class__'} (type=value_error.str.template; expected_keys={'action'}; actual_keys={'action.__class__'})
'''

**Comment by koxudaxi** [comment]
@MrMrRobat 
Thank you for your example.
The feature may use to check a custom template of an email.
However, I don't know that we should implement it with pydantic 🤔

**Comment by samuelcolvin** [comment]
Okay, I've thought about this and I don't think it belongs in pydantic.

It's somewhat confusing and not a core part of what pydantic does, it's also easy enough to implement out side pydantic.

Sorry, hope that's okay.
