### ISSUE TITLE
Models to XML

### ISSUE THREAD

**Issue by chopraaa** [samuelcolvin/pydantic#943]
I'm trying to use Pydantic to create models from data in CSVs and it's doing the job perfectly. I'm using multiple models then referencing them from within the others.

My motive is to dump the data in the main Model as an XML. Would you recommend a way to do this or is the best way to go about it - iterate through each object and generate the XML as it comes?

**Comment by samuelcolvin** [comment]
I haven't done this, so best to try for yourself.

You might want to use `model.__fields__` to get the types of each field, or you might just use `model.dict()`.

Let us know if you have trouble with anything.

**Comment by SammyHerring** [comment]
Hey - I was wondering if anything ever came from this. I'm looking into this use case at the moment. The easiest option might be going from JSON to XML - as suggested - but if there was an inbuilt option that would be awesome!

**Comment by gawry** [comment]
@SammyHerring one option would be using [dicttoxml](https://github.com/quandyfactory/dicttoxml)
