### ISSUE TITLE
changing default values of BaseConfig

### ISSUE THREAD

**Issue by vdwees** [samuelcolvin/pydantic#953]
In my project I want to make the default behaviour of models to throw an error if instantiated with extras. Rather than add a Config class to every model, I did this when I imported pydantic:
```py
from pydantic import BaseConfig, Extra
BaseConfig.extra = Extra.forbid
```
It worked as expected, but wondering if this would be considered abusing the API? I couldn't  find this snippet in the docs.

**Comment by samuelcolvin** [comment]
Yes I think this could be confusing, best to use something like

```py
class MyBaseModel(BaseModel):
    class Config:
        extra = Extra.forbid
```

Then use that as the base class for all models, `Config` will inherit same as the outer class.
