### ISSUE TITLE
New bool implemenation breaks validators

### ISSUE THREAD

**Issue by eschaar** [samuelcolvin/pydantic#954]
# Bug

* OS: Ubuntu 18.04
* Python version : 3.6.8
* Pydantic version: 1.0

New bool implementation seems to break the **'values'** parameter in **validators**; everything from the first boolean property defined including the property itself is no longer part of **'values'**.

In code below you will see that **'values'** is an empty dict and the test will fail.
If you put **'has_name'** below **'name'** property it will work again, and **'name'** will be available in **'values'**. 

Temporary work-around is to put all boolean properties as last in the class definition.

```py
from pydantic import BaseModel, validator


class SexyModel(BaseModel):

    has_name: bool = False
    name: str

    @validator('has_name')
    def check_has_name(cls, v, values, **kwargs):
        print(f"Passed values to validator: {values}")
        if v and not values.get('name', ''):
            raise ValueError('Invalid name')
        return v


class TestSexyModel:

    def test_name(self):
        SexyModel(
            **dict(
                name="YourMaMa",
                has_name=True,
            )
        )

        assert True

```

**Comment by samuelcolvin** [comment]
This isn't related to `bool`, but the new way fields are ordered. See [here](https://pydantic-docs.helpmanual.io/usage/models/#field-ordering)
