### ISSUE TITLE
How to describe json array ?

### ISSUE THREAD

**Issue by foozzi** [samuelcolvin/pydantic#956]
# How to describe json array ?

i have json 
```json
{'items':{'one':'one', 'two':'two'}, 'item1':'val', 'item2':'val'}
```
```py
import pydantic

class SomeClass(BaseModel):
    items: List[str, int] - how to validate each item?
```

**Comment by samuelcolvin** [comment]
It's not very clear what you're trying to achieve, but I would guess you're looking for something like

```py
from pydantic import BaseModel

class MyModel(BaseModel):
    items: Dict[str, str]
    item1: str
    item2: str
```

**Comment by foozzi** [comment]
@samuelcolvin but i can't validate item 'one' and 'two' for example

**Comment by samuelcolvin** [comment]
so you want the key and value to be the same?

You'd need to use a [validator](https://pydantic-docs.helpmanual.io/usage/validators/) on `items` and check from there.

**Comment by foozzi** [comment]
![DeepinScreenshot_выберите-область_20191101164139](https://user-images.githubusercontent.com/1178208/68022561-5a894c80-fcad-11e9-898e-cb680a245d87.png)
```python
class UserPayload(BaseModel):
    user: Dict[str, int]
    jwtToken: str
    refreshToken: str

**Comment by samuelcolvin** [comment]
I'm afraid I'm still not sure what you're asking.

You might want to use [a sub-model](https://pydantic-docs.helpmanual.io/usage/models/#recursive-models)?

**Comment by foozzi** [comment]
@samuelcolvin yep! thx you!!
