### ISSUE TITLE
mypy plugin support for dataclasses

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/pydantic#957]
While thinking about https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/48 I wondered whether we should change

https://github.com/samuelcolvin/pydantic/blob/0c18619769e3b4a975dea01f6e7f189a15639863/pydantic/dataclasses.py#L108-L112

and instead extend the mypy plugin to support `pydantic.dataclasses.dataclass`. Could we use the normal dataclass support, but also allow the `config` kwarg?

@dmontagu what do you think?

**Comment by dmontagu** [comment]
I think this should be pretty easy actually. There is a hook for when a decorator gets called, and we could just apply the dataclasses plugin’s hook inside that hook. I may not have time to work on this for a week or so, but no need to block on me if someone else wants to get their hands dirty with mypy 😅.

**Comment by samuelcolvin** [comment]
great, anyone keen feel free to submit a PR.

**Comment by samuelcolvin** [comment]
@koxudaxi would the above change help or hinder your pycharm plugin?

**Comment by koxudaxi** [comment]
@samuelcolvin 
The changed does not affect my pycharm plugin.
The pycharm plugin resolves the full module path of `@dataclass` and checks whether the path is `pydantic.dataclasses.dataclass`

**Comment by dmontagu** [comment]
I just wanted to drop a link to [this comment](https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/48#issuecomment-548738800) which explains precisely what additional information could be supported by the extension.

I think it should be straightforward to get mypy to recognize both the pydantic-specific dataclass decorator, and also to recognize all of the attributes described in that comment.

**Comment by PrettyWood** [comment]
Issue closed by https://github.com/samuelcolvin/pydantic/pull/966
