### ISSUE TITLE
PostgresDsn fails for google cloud dsn

### ISSUE THREAD

**Issue by euri10** [samuelcolvin/pydantic#960]
# Bug

Please complete:
* OS: 
debian buster

* Python version `import sys; print(sys.version)`: 

3.7.5rc1 (default, Oct  8 2019, 16:47:45) 
[GCC 9.2.1 20190909]

* Pydantic version `import pydantic; print(pydantic.VERSION)`:

1.0 

**Please read the [docs](https://pydantic-docs.helpmanual.io/) and search through issues to
confirm your bug hasn't already been reported.**

Where possible please include a self contained code snippet describing your bug:

the following assert added to the tests of postgres dsn `def test_postgres_dsnencodes():` fails

```
assert Model(a='postgresql://user:password@/db_name?host=/cloudsql/project-name:region:instance-name&port=5432').a == 'postgresql://user:password@/db_name?host=/cloudsql/project-name:region:instance-name&port=5432'
```

this is a valid postgres dsn in google cloud sql (https://cloud.google.com/appengine/docs/flexible/python/using-cloud-sql-postgres)

**Comment by samuelcolvin** [comment]
weird, doesn't look anything like DSN to me. What do other libraries think?

**Comment by euri10** [comment]
Pending issue in asyncpg :
https://github.com/MagicStack/asyncpg/issues/419
Working with psycopg2 :
https://stackoverflow.com/a/51061723

Le lun. 4 nov. 2019 à 11:32 PM, Samuel Colvin <notifications@github.com> a
écrit :

**Comment by samuelcolvin** [comment]
What exactly is the error from pydantic?

**Comment by euri10** [comment]
```――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― test_postgres_dsnencodes ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    def test_postgres_dsnencodes():
        class Model(BaseModel):
            a: PostgresDsn
    
        assert Model(a='postgres://user:pass@localhost:5432/app').a == 'postgres://user:pass@localhost:5432/app'
        assert Model(a='postgresql://user:pass@localhost:5432/app').a == 'postgresql://user:pass@localhost:5432/app'
>       assert Model(a='postgresql://user:password@/db_name?host=/cloudsql/project-name:region:instance-name&port=5432').a == 'postgresql://user:password@/db_name?host=/cloudsql/project-name:region:instance-name&port=5432'

tests/test_networks.py:246: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

__pydantic_self__ = Model(), data = {'a': 'postgresql://user:password@/db_name?host=/cloudsql/project-name:region:instance-name&port=5432'}, values = {}, fields_set = {'a'}
validation_error = ValidationError(model='Model', errors=[{'loc': ('a',), 'msg': 'URL host invalid', 'type': 'value_error.url.host'}])

    def __init__(__pydantic_self__, **data: Any) -> None:
        # Uses something other than `self` the first arg to allow "self" as a settable attribute
        if TYPE_CHECKING:
            __pydantic_self__.__dict__: Dict[str, Any] = {}
            __pydantic_self__.__fields_set__: 'SetStr' = set()
        values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
        if validation_error:
>           raise validation_error
E           pydantic.error_wrappers.ValidationError: 1 validation error for Model
E           a
E             URL host invalid (type=value_error.url.host)

pydantic/main.py:276: ValidationError
```

**Comment by samuelcolvin** [comment]
I think this is a genuinely invalid url you have `/db_name` as the host which surely can't be valid?

**Comment by euri10** [comment]
I think, despite being genuinely weird, that the url is valid, see for instance https://github.com/GoogleCloudPlatform/python-docs-samples/blob/fe969c35b66fe3a1e854723e88f6ba79b63f7309/appengine/flexible/cloudsql_postgresql/app.yaml#L13

**Comment by dmontagu** [comment]
I'm assuming the host is actually just `''`, which I agree is weird.

I think for *most* cases this would be more likely to be a mistake rather than intended. So it might make sense to create a different type (maybe not in pydantic?) to handle this.

On the other hand, if this is the standard way to integrate with the Google Cloud AppEngine, maybe it is worth handling directly by pydantic? (Even if so, I wouldn't mind requiring the use of a different class, kind of like `HttpUrl` vs `AnyHttpUrl`.)

**Comment by rushilsrivastava** [comment]
@samuelcolvin Considering that this is a format that is valid and used by the GCP platform, would you be open to accepting a potential PR for this?

**Comment by bgohla** [comment]
According to the `libpq` [docs](https://www.postgresql.org/docs/13/libpq-connect.html) it is allowed to use a path name in place of a host name in the connection URIs, in which case the it is interpreted as the directory where the Unix socket resides.

Additionally, all parts after the scheme are optional.

The relevant passage from section 33.1.1.2 is 

> The host part is interpreted as described for the parameter host. In particular, a Unix-domain socket connection is chosen if the host part is either empty or looks like an absolute path name, otherwise a TCP/IP connection is initiated. Note, however, that the slash is a reserved character in the hierarchical part of the URI. So, to specify a non-standard Unix-domain socket directory, either omit the host part of the URI and specify the host as a named parameter, or percent-encode the path in the host part of the URI:


> postgresql:///dbname?host=/var/lib/postgresql
> postgresql://%2Fvar%2Flib%2Fpostgresql/dbname



Clearly, this implementation falls short.
