### ISSUE TITLE
Assigning data to dict field in a pydantic model causes validation?

### ISSUE THREAD

**Issue by davidpricedev** [samuelcolvin/pydantic#961]
# Question

I am trying to assign some data to a dict object that is part of a pydantic model. I am getting some validation that I didn't expect - and don't want. Is this validation intended? If so, are there settings that I can tune to disable that validation? Reproduction code is below.

Please complete:
* OS: macos 
* Python version `import sys; print(sys.version)`: 3.7.4
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 1.0

**Please read the [docs](https://pydantic-docs.helpmanual.io/) and search through issues to
confirm your question hasn't already been answered.**

Where possible please include a self contained code snippet describing your question:

```py
import json
from typing import Dict, Optional

from pydantic import BaseModel


class FailCase(BaseModel):
    req_field: str
    opt_field: Optional[str]
    audit_field: Optional[Dict]

    @classmethod
    def from_flat_json(cls, flat_json: dict):
        return cls(
            audit_field=flat_json,
            **flat_json,
        )

if __name__ == "__main__":
    test_case_str = """
    {
        "req_field": "qwerty",
        "opt_field": "dvorak",
        "other": "random_stuff",
        "and_more": "stuff",
        "some_are_null": null
    }
    """
    test_case = json.loads(test_case_str)
    result = FailCase.from_flat_json(test_case)

    # Expected:
    #   successful deserialization of both the projected/direct fields and
    #   the audit dict field.

    # Causes:
    #> pydantic.error_wrappers.ValidationError: 1 validation error for FailCase
    #> audit_field -> some_are_null
    #>   none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by samuelcolvin** [comment]
Thanks for reporting, this is definitely a bug, it happens with 3.7 but not 3.6.

Here is a minimal demonstration:

```py
from typing import Dict
from pydantic import BaseModel

class MyModel(BaseModel):
    foo: Dict

test_case = {'x': 'a', 'y': None}
m = MyModel(foo=test_case)
print(repr(m))
```

I imagine it's a weird subtlety with how we introspect `Dict`.

There's another related bug where the same happens with both python 3.6 and 3.7 if you use `Dict[str, Any]`.

I will fix on Wednesday and release a fix when I'm back at desk.

**Comment by dmontagu** [comment]
As a short term workaround, if you replace `Any` with `Optional[Any]` you won't get this error. More specifically to this example, if you replace `Dict` with `Dict[Optional[Any], Optional[Any]]`, you won't get those errors. (You could maybe replace it with `Dict[str, Optional[Any]]` too.)

But yeah, hopefully this can just get fixed quickly.

**Comment by dmontagu** [comment]
@samuelcolvin Note that the same error happens for other generics, not just `Dict`.

Actually, I think the issue is just that `Any` is not allowed to be `None`; I'm guessing this is related to the refactor of how `None is handled`.

Here's an example:

```
from typing import Any

from pydantic import BaseModel


class MyModel(BaseModel):
    foo: Any

m = MyModel(foo=None)
print(repr(m))
"""
pydantic.error_wrappers.ValidationError: 1 validation error for MyModel
foo
  none is not an allowed value (type=type_error.none.not_allowed)
"""
```
