### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'min_items'

### ISSUE THREAD

**Issue by aknaut** [samuelcolvin/pydantic#965]
# Bug

Please complete:
* OS:  Windows 10
* Python version `import sys; print(sys.version)`: 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)]
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 1.0

I get an AttributeError while trying to generate a schema for a dictionary with values of type list.

Example:
```py
from typing import Dict, List
from pydantic import BaseModel

class SomeSchema(BaseModel):
    entries: Dict[str, List[int]]

SomeSchema.schema()
```
Which results in `AttributeError: 'NoneType' object has no attribute 'min_items'`

Is this a bug or do I need to define the schema in a different way?

**Comment by samuelcolvin** [comment]
Thanks for reporting, fixed on #969. Let me know if that fixes your problem, I'll release an update in a day or two.
