### ISSUE TITLE
Nested generic models

### ISSUE THREAD

**Issue by NowanIlfideme** [samuelcolvin/pydantic#967]
# Bug / Feature Request

Nested generic models seem to be significantly bugged, at least in 0.32.2 (I believe it's the same for 1.0?)

* OS: **Windows 10**
* Python version `import sys; print(sys.version)`: **3.7.3 (conda-forge)**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **0.32.2**

Tagging @dmontagu as per request from gitter.

It seems the direct issue I had in 0.30 doesn't exist, but I'm still unable to do what I wanted to do. 😛 

Ideally I would be able to set parametrized hierarchies of models using one generic TypeVar, and have them pick them up (as `OSet` below), similarly to `template<typename T>` in C++.

The way it currently works (`OUnset` and `OListNested` below) doesn't seem to support type checking, and doesn't support roundtripping in dicts at all (due to not knowing what to set in the generic type).

I would expect to be able to pass and "inherit" (for lack of better term in my knowledge) the same `TypeVar`s down the hierarchy of models, and enforce the concrete types. Also, it's strange that `OUnset` and `OListNested` work at all (though I guess X[T] is a subclass of X...), but I think that behaviour might be useful, as long as the caveats are documented.

Currently:

```py
>>> import sys
>>> import pydantic
>>> import typing
>>> from pydantic.generics import GenericModel
>>> print(sys.version)
3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) [MSC v.1900 64 bit (AMD64)]
>>> print(pydantic.VERSION)
0.32.2
>>> AT = typing.TypeVar("AT")
>>>
>>> class InnerT(GenericModel, typing.Generic[AT]):
...     a: AT
...
>>> inner_int = InnerT[int](a=8)
>>> inner_str = InnerT[str](a="ate")
>>>
>>> class OUnset(GenericModel, typing.Generic[AT]):      
...     """This seems to work, allowing any InnerT[X]."""
...     i: InnerT  # just the generic
... # works:
...
>>> o_unset_int_int = OUnset[int](i=inner_int)
>>> # works, but might be unintuitive:
...
>>> o_unset_int_str = OUnset[int](i=inner_str)
>>> # Can't round-trip through dict due to not knowing the type
... 
>>> d_uii = o_unset_int_int.dict()
>>> d_uii
{'i': {'a': 8}}
>>>
>>> OUnset[int](**d_uii)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Conda\envs\bugs_pydantic\lib\site-packages\pydantic\main.py", line 275, in __init__
    values, fields_set, _ = validate_model(__pydantic_self__, data)
  File "C:\Conda\envs\bugs_pydantic\lib\site-packages\pydantic\main.py", line 785, in validate_model
    raise err
pydantic.error_wrappers.ValidationError: 1 validation error for OUnset[int]
i
  Type InnerT cannot be used without generic parameters, e.g. InnerT[T] (type=type_error)
>>> # IMO this should require InnerT[AT] instead of InnerT in
... # the definition (see OSet below)
... # -----------------
...
>>> class OListNested(GenericModel, typing.Generic[AT]):       
...     """This works (didn't in 0.30), but doesn't type-check."""
...     ii: typing.List[InnerT]
... # works:
... 
>>> o_list_int_int = OListNested[int](ii=[inner_int])
>>> # works, but might be unintuitive:
...
>>> o_list_int_str = OListNested[int](ii=[inner_str])
>>> # Still can't round-trip (same problem as OUnset)
...
>>> d_lii = o_list_int_int.dict()
>>> d_lii
{'ii': [{'a': 8}]}
>>>
>>> OListNested[int](**d_lii)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Conda\envs\bugs_pydantic\lib\site-packages\pydantic\main.py", line 275, in __init__
    values, fields_set, _ = validate_model(__pydantic_self__, data)
  File "C:\Conda\envs\bugs_pydantic\lib\site-packages\pydantic\main.py", line 785, in validate_model
    raise err
pydantic.error_wrappers.ValidationError: 1 validation error for OListNested[int]
ii -> 0
  Type InnerT cannot be used without generic parameters, e.g. InnerT[T] (type=type_error)
>>> # -----------------
... # Expected this to work and enforce the same type, like templates in C++.
... # But it produces an error due to InnerT[AT] as below.     
... 
>>> class OSet(GenericModel, typing.Generic[AT]):
...     i: InnerT[AT]
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in OSet
  File "C:\Conda\envs\bugs_pydantic\lib\site-packages\pydantic\generics.py", line 31, in __class_getitem__
    raise TypeError(f'Type parameters should be placed on typing.Generic, not GenericModel')
TypeError: Type parameters should be placed on typing.Generic, 
not GenericModel
>>> # This errors upon definition. Maybe premature erroring?   
... InnerT[AT]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Conda\envs\bugs_pydantic\lib\site-packages\pydantic\generics.py", line 31, in __class_getitem__
    raise TypeError(f'Type parameters should be placed on typing.Generic, not GenericModel')
TypeError: Type parameters should be placed on typing.Generic, 
not GenericModel
```

Expected:

```py
>>> # ...
>>> class OSet(GenericModel, typing.Generic[AT]):
...     i: InnerT[AT]
...     
>>> os_int_int = OSet[int](i=inner_int)
>>> os_int_int.dict()
{'i': {'a': 8}}
>>> OSet[int](**os_int_int.dict()) == os_int_int
True
>>> os_int_str = OSet[int](i=inner_str)
ValidationError: Type of `i` (inner_str) doesn't match OSet[int] (int != str).
```

**Comment by NowanIlfideme** [comment]
OK, switching to 1.0 (which I can't in my dev environment due to FastAPI not catching up yet).

A lot more is allowed (yay!) but behavior is still strange/unexpected.
Roundtripping seems to work, but we can instantiate abstract types: `InnerT[AT](a='whatever')`

```py
>>> import sys
>>> import pydantic
>>> import typing
>>> from pydantic.generics import GenericModel
>>> print(sys.version)
3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) [MSC v.1900 64 bit (AMD64)]
>>> print(pydantic.VERSION)
1.0
>>> AT = typing.TypeVar("AT")
>>>
>>> class InnerT(GenericModel, typing.Generic[AT]):
...     a: AT
...
>>> inner_int = InnerT[int](a=8)
>>> inner_str = InnerT[str](a="ate")
>>> 
>>> class OSet(GenericModel, typing.Generic[AT]):
...     i: InnerT[AT]
... # This works!
... 
>>> os_int_int = OSet[int](i=inner_int)
>>> os_int_int.dict()
{'i': {'a': 8}}
>>>
>>> OSet[int](**os_int_int.dict()) == os_int_int
True
>>> # But wait, the inner type isn't set. Why can we instantiate it?
...
>>> os_int_int
OSet[int](i=InnerT[AT](a=8))
>>>
>>> type(os_int_int.i)
<class '__main__.InnerT[AT]'>
>>> # And we don't check the type ever.
... # This succeeds, but expected behaviour would be to raise, 
no?
... 
>>> os_int_str = OSet[int](i=inner_str)
>>> os_int_str
OSet[int](i=InnerT[AT](a='ate'))
>>> os_int_str.dict()
{'i': {'a': 'ate'}}
>>>
>>> OSet[int](**os_int_str.dict()) == os_int_str
True
>>> # Same for list, so at least that's consistent :)
...
>>> class OList(GenericModel, typing.Generic[AT]):
...     ii: typing.List[InnerT[AT]]
...
>>> ol_int_int = OList[int](ii=[inner_int])
>>> ol_int_int
OList[int](ii=[InnerT[AT](a=8)])
>>>
>>> ol_int_int.dict()
{'ii': [{'a': 8}]}
>>> # Round-tripping seems to work
... # (need to test more levels just in case)
...
>>> OList[int](**ol_int_int.dict())
OList[int](ii=[InnerT[AT](a=8)])
```

**Comment by NowanIlfideme** [comment]
I may be missing some finesse regarding typing and Generics, but happy to learn. 

I guess my main questions are:

- Should you allow instantiating generic models? I assume yes, as `typing.Generic` subclasses can be created:

```py
>>> import typing
>>> AT = typing.TypeVar('AT')
>>> class M(typing.Generic[AT]):
...     def __init__(self, z: AT):
...         self.z = z
...
>>> M(z=1)
<__main__.M object at 0x000002AB1CC43E48>
>>> M[AT](z=1)
<__main__.M object at 0x000002AB1CC43F98>
>>> M[int](z=1)
<__main__.M object at 0x000002AB1CC530B8>
>>>
```

- Should sub-models declared with the same `TypeVar`s as parent models be `[]`'d as well? That sounds like a difficult task, but might be optimal? 

- Should generic models type check when doing validation? I guess you could make the user use their own validators if they really want them...

**Comment by dmontagu** [comment]
Something seems awry with your 1.0 example from the second comment, but I'm having a really hard time following it due to the naming. Also, it will be hard to copy and work with due to including the interpreter `>>>` and `...`s.

Could you format the code into a block without the `>>>` and `...`s so I can just copy/paste it into an editor and work on it? It would be great if you could rename things to have more meaningful names too, but I guess I can get by without that.

-----

I think in the context of pydantic, yes, generic models should type check (that's basically the whole point of pydantic, after all), and I think it also makes sense to disallow instantiating models with unspecified TypeVars, rather than treating it as `Any`. I can't think of a context where you'd *want* to leave the TypeVar unspecified, so it seems like this is more likely to be the result of a mistake in your code than desirable behavior (and you could always parametrize with `Any` if you don't want checks).

------

> Should sub-models declared with the same TypeVars as parent models be []'d as well?

I have no idea what you mean by this 😅

**Comment by NowanIlfideme** [comment]
Sorry, that's apparently what happens when submitting bugs late at night!
Sorry for the initial ">>> ", I was thinking about doctests.

I agree with your comments, incorporated them in the new examples below. Hopefully this should be more clear.



----

Duplicated in the gist here:
https://gist.github.com/NowanIlfideme/5ba7ef94cff8a24b5ccfe3169d3585d3

```py
import sys
import pydantic
import typing
from pydantic.generics import GenericModel

print(sys.version)
print(pydantic.VERSION)


AT = typing.TypeVar("AT")
BT = typing.TypeVar("BT")


#######
#  1  #
#######

# This works properly
class InnerT(GenericModel, typing.Generic[AT]):
    a: AT


# These should work (OK)
inner_int = InnerT[int](a=8)
inner_str = InnerT[str](a="ate")
inner_dict_any = InnerT[typing.Any](a={})
inner_int_any = InnerT[typing.Any](a=7)

# This should fail to validate (OK)
try:
    InnerT[int](a="ate")
except pydantic.error_wrappers.ValidationError:
    print("This correctly fails.")


#######
#  2  #
#######

# This should work and force the same type for AT:
class OuterT_SameType(GenericModel, typing.Generic[AT]):
    i: InnerT[AT]


OuterT_SameType[int](i=inner_int)
OuterT_SameType[str](i=inner_str)

# This should fail to validate
try:
    OuterT_SameType[int](i=inner_str)
except pydantic.error_wrappers.ValidationError:
    print("This correctly fails.")
else:
    print("This should fail, but was OK")

# This should also fail
try:
    OuterT_SameType[int](i=inner_dict_any)
except pydantic.error_wrappers.ValidationError:
    print("This correctly fails.")
else:
    print("This should fail, but was OK")

# This should also fail, as the type is "wider" than Inner[int]
try:
    OuterT_SameType[int](i=inner_int_any)
except pydantic.error_wrappers.ValidationError:
    print("This correctly fails.")
else:
    print("This should fail, but was OK")


#######
#  3  #
#######

# This should be OK and support any of the `inner_*` objects
class OuterT_Any_Proper(GenericModel, typing.Generic[AT]):
    i: InnerT[typing.Any]


# These should work
OuterT_Any_Proper[int](i=inner_int)
OuterT_Any_Proper[int](i=inner_str)
OuterT_Any_Proper[int](i=inner_dict_any)
OuterT_Any_Proper[int](i=inner_int_any)


#######
#  4  #
#######

# These definitions should not be allowed

# Can't figure out inner type
class OuterT_Any_Improper(GenericModel, typing.Generic[AT]):
    i: InnerT


# Notice the Outer is BT, while Inner is AT
class OuterT_Mismatched_Types(GenericModel, typing.Generic[BT]):
    i: InnerT[AT]

```

Regarding `OuterT_Mismatched_Types`, I'm actually not entirely sure about this. What about nested models where we use BT in one place and AT in another? Perhaps definition of the class should be allowed, but not instantiation, unless a concrete type can be figured out for it.

**Comment by samuelcolvin** [comment]
have a look at #962 please.

Coincidentally this might fix your problems with `TypeVar`

**Comment by samuelcolvin** [comment]
@NowanIlfideme please let me know if #962 fixed your problem?

**Comment by samuelcolvin** [comment]
@NowanIlfideme any answer on whether this is fixed by #962 which was released in v1.1.

**Comment by NowanIlfideme** [comment]
I've been unable to test this out since I'm fixed by FastAPI and thus testing this out in my "real-world" project isn't feasible. I also moved away for using Pyandtic for this part of the code (still kept it where possible, since it's awesome 😛) due to project time constraints. Sorry for ignoring the previous ping.

**Comment by NowanIlfideme** [comment]
Testing my gist on 1.2, I still get the same results as before. Though I believe the error was mostly on my incorrect interpretation on functionality. 

My (incorrect) intuition was that the GenericModel would enforce parametrization of the field types to the upper type. That is, if I used a GenericModel[AT] within a GenericModel[AT] it would "share" the AT parameter. In reality, it only checks direct fields with the type AT, while keeping Generic fields Generic.

I understand this is currently out of Pydantic's scope, and probably not a very common use case (generics don't seem popular by themselves, especially nested generics; I was able to do without in a satisfactory manner on my project). 

-----

Perhaps it's better to reframe this as a feature request?

It would be neat if we could force Generics in fields to conform to the supertype:

```python
class SubFieldType(GenericModel, typing.Generic[AT]
    name: str
    value: AT

class MyTemplateModel(GenericModel, typing.Generic[BT, CT]):
    direct_field: BT
    sub_field: SubFieldType[CT]

model = MyTemplateModel[str, int](direct_field="hi", sub_field={"name": "name", "value": 3})
model.sub_field.value == 3

try:
    model = MyTemplateModel[str, int](direct_field="hi", sub_field={"name": "name", "value": "THREE"})
except ValidationError:
    print("Correctly validated that THREE is not an int.")
```

I'm not sure whether it should be the "new" base functionality or an additional thing, or whether it even makes sense for the Pydantic to do this. Feel free to close if not. 😃

**Comment by dmontagu** [comment]
@NowanIlfideme Thank you for putting together that gist; it was very helpful and a good starting place for implementation.

I finally got around to working on this, and opened #1104 which I think addresses the issues in your gist.

------

One thing I disagreed with in your gist:

```python
# This should also fail, as the type is "wider" than Inner[int]
try:
    OuterT_SameType[int](i=inner_int_any)
except pydantic.error_wrappers.ValidationError:
    print("This correctly fails.")
else:
    print("This should fail, but was OK")
```

I'm not sure this case should actually fail, because we generally allow things to be parsed when possible, and in this case, it *can* be safely parsed. In particular, if you were declare models with the fields you'd get by substituting the typevars manually, no validation error would be raised. Moreover, it would probably be *more challenging* to implement it in a way where this raised an error anyway.

So I think for consistency, this should be allowed, and in #1104 it works.

**Comment by NowanIlfideme** [comment]
Seems reasonable to me, especially since it's in line with how it works now with Dict/List. Plus more use cases vs the "purist" implementation, and easier to check at runtime. I tried to think of a useful counterexample where the "purist" behavior is preferable, but couldn't.
