### ISSUE TITLE
Byte and Time Conversion Types

### ISSUE THREAD

**Issue by dgasmith** [samuelcolvin/pydantic#971]
# Feature Request

For many of our `BaseSettings` classes we have fields that either describe a time duration or byte size, typically we have to pick a unit ('GB' or 's') that these should be represented in and users must pass in a value in that unit. It would be more convenient if users could specify `3 TiB` or `30 m` and have this be cast to the correct type. I see two possible implementations, the first where the units type are parametrized and cast to this value:

```
class Config(BaseSettings):
    size: ByteSize['GB']

c = Config(size='1TB')
assert isinstance(c.size, float)
assert c.size == 1000
```

The other where the value remains an object:

```
class Config(BaseSettings):
    size: ByteSize

c = Config(size='1TB')
assert isinstance(c.size, ByteSize)
assert c.size.to('GB') == 1000
assert int(c.size) == int(1e9)
```

Similar structures can be built for a `TimeUnit` object. Several questions:
1) Anyone have thoughts on the implementation or names?
2) Would you want this contributed to pydantic?

**Comment by samuelcolvin** [comment]
I'd be happy with `ByteSize`, but I think it should always just be an int. As with `AnyUrl` it could have some method to format it or change the base, but it should inherit from and/or act like an int representing bits.

Regarding `1s` or `30m`, this would be a change to the `timedelta` parsing, fine by me as long as it is clear and obviously deterministic.

**Comment by dgasmith** [comment]
Ok, I can add the `ByteSize['GB']` implementation that would inherit from a `float` for cases like `size: ByteSize['GB'] = '5 MB'`.

Makes sense for `timedelta`.

**Comment by samuelcolvin** [comment]
I real think any disk or memory size should inherit from int. I wouldn't accept something that inherited from float as I think it would lead to problems.

Also:

`MB` vs `MiB`, should we be technically accurate and call `1 MB = 1,000,000` or follow convention and use `1 MB = 1,048,576`?

I guess we should give the technically correct meaning to `MB` and MiB` (1,000,000 and 1,048,576 respectively) and document it clearly.

But this isn't going to be useful to many people, from [here](https://en.wikipedia.org/wiki/Kilobyte):

> On modern systems, all versions of Microsoft Windows including the newest (as of 2019) Windows 10 divide by 1024 and represent a 65,536-byte file as "64 KB".[9] Conversely, Mac OS X Snow Leopard and newer represent this as 66 kB, rounding to the nearest 1000 bytes.[14] File sizes are reported with decimal prefixes.[15]

ubuntu 18.04 follows the windows convention. 

When taking RAM rather than disk, I think the binary base is even more common.

**Comment by dgasmith** [comment]
`int` will lead to its own problems unless we always case to bytes:

```
class Config(BaseSettings):
    size: ByteSize['GB']

c = Config(size='1MB')
assert c.size = 0.001
```

This would lean towards the second implementation proposed.

My plan was to strictly follow `MiB` vs `MB` depending on input.

**Comment by samuelcolvin** [comment]
I understand, but I would disagree with parameterisation.

U would suggest:

```py
class MyModel(BaseModel):
    size: ByteSize

print(MyModel(size='1MB'))
#>  size=1000000

print(MyModel(size='1MiB'))
#>  size=1048576

print(MyModel(size=100))
#>  size=100

print(MyModel(size='1MB').size.human_readable())
#>  1MB
```

Maybe your usage is a bit too different and might be best left as you're own custom type?

There's also the problem of whether to accept `Mbit` where we might need to round (down?) to the nearest byte.

**Comment by samuelcolvin** [comment]
(please can you move the duration stuff to a separate issue to avoid confusion).

**Comment by samuelcolvin** [comment]
> but wouldn't this suggest that the value would not be just an int

You mean the `human_readable` method? Well my idea is that `ByteSize` would inherit from `int` but provide some extra methods. 

Just as [`AnyUrl`](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/networks.py#L70) inherits from `str` and has extra methods.

**Comment by samuelcolvin** [comment]
something like 

```py
class ByteSize(int):
    def human_readable(self):
        if self < 1000:
            return str(self)
        elif self < 1_000_000:
            return f'{self / 1000:0.2}KB'
        elif self < 1_000_000_000:
            return f'{self / 1_000_000:0.2}MB'
        else:
            return f'{self / 1_000_000_000:0.2}GB'


b = ByteSize(1073741824)
print(b.human_readable())
print(b + 1)
```

**Comment by samuelcolvin** [comment]
The `timedelta` stuff here is covered by #432
