### ISSUE TITLE
Include class name in repr

### ISSUE THREAD

**Issue by Trim21** [samuelcolvin/pydantic#974]
# Question

I'm not sure this should be a question or a feature request.

Please complete:
* OS: **any**
* Python version `import sys; print(sys.version)`: **3.7.4**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **1.0**

Where possible please include a self contained code snippet describing your question:

```python
from pydantic import BaseModel


class M(BaseModel):
    a: str
    b: int

    def __repr__(self):
        return f'{self.__class__.__name__}<{self.__repr_str__(", ")}>'

    __str__ = __repr__


if __name__ == '__main__':
    m = M(a='a', b=2)
    print(m)
```

`M<a='a', b=2>` would be more readable than `a='a', b=2`

**Comment by samuelcolvin** [comment]
Use `print(repr(m))` and you'll get `M(a='a', b=2)`.

Or you could use [devtools'](https://pypi.org/project/devtools/) `debug()` instead of `print()` and you'll get

![image](https://user-images.githubusercontent.com/4039449/68403194-75a80080-0174-11ea-964a-d0a23f15a8e7.png)

**Comment by cthoyt** [comment]
I would also like to understand this choice
