### ISSUE TITLE
mypy annotation and constrained lists recommendation

### ISSUE THREAD

**Issue by jrwalk** [samuelcolvin/pydantic#975]
# Question

Please complete:
* OS: Debian 10 (`python:3.7-slim` Docker image)
* Python version: 3.7.5
* Pydantic version 0.32.2

Hello!  I'm hoping to find the best practice for the interaction between `mypy` checks and the `ConstrainedList`/`conlist()` `pydantic` types.   For the MWE below, we're expecting a `BaseModel` taking a fixed-length list of floats (this is used as a request body in `FastAPI`):

```py
from pydantic import BaseModel, conlist

class EmbeddingRequest(BaseModel):
    embedding: conlist(float, min_items=100, max_items=100)
```

which behaves as expected, but complains when run through mypy checks (same error as in the older #239 issue).  From #862 it sounds like it's still on deck to add improvements to documentation for mypy+constrained types, so hopefully this can help.  Alternately, I suppose this might be something that is resolved in v1.0/1.1 - for the time being I'm pinned to 0.32.2 for FastAPI compatibility, but I doubt that will last long.

Older issues propose a few options:

### option 1

per #239, 

```py
from typing import List, Type
from pydantic import BaseModel, conlist

Vector: Type[List[float]] = conlist(float, min_items=100, max_items=100)

class EmbeddingRequest(BaseModel):
    embedding: Vector
```

runs, but complains that `Vector` is not valid as a type (and defining it as type `ConstrainedList` rather than `List[float]` per #156 fails for type mismatch).

### option 2

also in #239 , explicitly subclassing the type

```py
from pydantic import BaseModel, ConstrainedList

class Vector(ConstrainedList):
    item_type = float
    min_items = 100
    max_items = 100
    __args__ = [float]

class EmbeddingRequest(BaseModel):
    embedding: Vector
```

functions properly and passes `mypy`, but forcing the explicit `__args__` overloading for it to behave properly relative to `conlist()` feels evil to me.

### option 3

just punt and add a `type: ignore` flag on the original `conlist` call.

Any advice on this would be much appreciated!

**Comment by samuelcolvin** [comment]
What happens with option 2, but removing `__args__ = [float]` and then use `Vector[float]`?

**Comment by samuelcolvin** [comment]
oh, that probably doesn't work but would be the best solution,

The other thing to do is

```py
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    Vector = List[float]
else:
    Vector = conlist(float, min_items=100, max_items=100)
```
or something.

**Comment by jrwalk** [comment]
yeah `Vector[float]` throws a type error - `'type' object is not subscriptable`

**Comment by samuelcolvin** [comment]
Best to do 

```py
from typing import List
from pydantic import BaseModel, Field

class EmbeddingRequest(BaseModel):
    embedding: List[float] = Field(..., min_items=100, max_items=100)

EmbeddingRequest(embedding=list(range(100)))
```

We could perhaps allow paramaterising of `ConstrainedList` as per my suggestion in future?

**Comment by jrwalk** [comment]
Import cycling on `TYPE_CHECKING` worked, but I imagine a more stable solution is desirable.

That `Field` functionality is new in v1.0, right?  That's a breaking change for FastAPI (though it's [slated for a fix](https://github.com/tiangolo/fastapi/issues/635)) so that won't work for the time being.  Can get the equivalent functionality with `pydantic.Schema` in the older version but `mypy` doesn't like it.

It sounds like the play is to use the shim with import cycling until FastAPI supports `pydantic>=1.0.0`, then use the `Field` type which should give the cleanest solution.  I do really like the idea of parameterized `ConstrainedList` as a way to define constrained types in a way that feels very consistent with the rest of `typing`'s behavior.

**Comment by samuelcolvin** [comment]
Yup, `Field()` is the best solution as of v1. As well as changing the name in v1 we made `Field` a function with return type `Any` to avoid mypy complaining. 

I'd be happy to accept a PR to implement parameterized `ConstrainedList`.

**Comment by jrwalk** [comment]
rad, I'll start taking a crack at that!

**Comment by hmvp** [comment]
Some remarks regarding conlist:
- the `__args__` thing was a mistake in hindsight. I didn't realize at the time that the class would be use directly. But is is probably easy to modify the code to set `__args__` from `item_type`.. 

We currently have something like this:
```python
class InstanceListMeta(type):
    """Metaclass allow for easier creating constrained lists.

    All this code should be removed once pydantic has a nicer interface for contrained lists
    """

    def __new__(metacls: Type[T], name: str, bases: Tuple[type, ...], namespace: Dict[str, Any], **kwds: Any,) -> T:
        if "__args__" not in namespace and "item_type" in namespace:
            namespace["__args__"] = [namespace["item_type"]]
        return super().__new__(metacls, name, bases, namespace)  # type: ignore

class InstanceList(ConstrainedList, metaclass=InstanceListMeta):
    pass

```

- I could not get a properly parameterized conlist to work in combination with cython. But given that a lot has changed since then it might just work now. I would welcome it since we run into the same issues..

**Comment by hmvp** [comment]
Hmmm just using this will also work on python >3.6
```
class InstanceList(ConstrainedList):
    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        cls.__args__ = [cls.item_type]
```

**Comment by AngryUbuntuNerd** [comment]
the Field solution is not sufficient using FastAPI, as those can only be used for bodies, not query strings:

`AssertionError: Param: [name] can only be a request body, using Body(...)`

**Comment by jrwalk** [comment]
@AngryUbuntuNerd there's a good chance the `fastapi.Query` construct would provide sufficient validation, what exactly are you trying to do?

**Comment by PrettyWood** [comment]
Hi everyone
Does something like https://github.com/samuelcolvin/pydantic/pull/2553 sound like a good solution to you?
The goal is to leverage `Annotated` instead of struggling with Generic or dynamic types

**Comment by rustam-python** [comment]
If you (as I'm) don't get what does it means: "With the new Annotated syntax, it should now be possible to make it work properly"

In Python 3.9+:

```python
class _Artist(pydantic.BaseModel):
    image: typing.Annotated[list, pydantic.conlist(_Image, min_items=5, max_items=5)]
```

**Comment by genos** [comment]
Thanks, @rustam-python, but unfortunately this approach skips any validation. For example:

```python
from typing import Annotated
from pydantic import BaseModel, confloat

# mypy likes this
class ProbabilityAnnotated(BaseModel):
    p: Annotated[float, confloat(ge=0, le=1)]

# mypy doesn't like this
class Probability(BaseModel):
    p: confloat(ge=0, le=1)

# this doesn't throw an error
pa = ProbabilityAnnotated(p=10)

# this throws an error
p = Probability(p=10)
```

**Comment by leesei** [comment]
Bump, issue reproduced with genos' code

Python 3.10.5
pydantic==1.9.1
mypy==0.961
mypy-extensions==0.4.3

**Comment by holocronweaver** [comment]
It seems @genos code did not work because the `Annotated` was malformed.

The syntax is verbose, `conlist` is much cleaner and concise. Hopefully the mypy plugin can fix this in the future to avoid such clutter?

Python 3.10.6
pydantic==1.10.2
mypy==0.971
mypy-extensions==0.4.3

```
from typing import Annotated
from pydantic import BaseModel, Field, conlist

# mypy likes this
class VectorAnnotated(BaseModel):
    xs: Annotated[list[str], Field(min_items=1, max_items=5)]
# mypy doesn't like this
class Vector(BaseModel):
    xs: conlist(float, min_items=1, max_items=5)
# this now throws an error!
va = VectorAnnotated(xs=[float(x) for x in range(10)])
# this throws an error
v = Vector(xs=[float(x) for x in range(10)])
```

Based on syntax I found in [this comment](https://github.com/pydantic/pydantic/issues/3080#issuecomment-1206806049).

**Comment by glarrain-cdd** [comment]
@holocronweaver it seems there is a mistake in your example because the field in `VectorAnnotated` is for a list of str, and in `Vector` it is a list of float

**Comment by holocronweaver** [comment]
@glarrain-cdd Updated, though this doesn't change the output with the versions listed, which fail on item count rather than type.
