### ISSUE TITLE
Exceptions in __post_init__ aren't wrapped

### ISSUE THREAD

**Issue by bochecha** [samuelcolvin/pydantic#981]
# Bug

Please complete:
* OS: **Ubuntu 19.04**
* Python version `import sys; print(sys.version)`: **3.7.3**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **1.0**

I'm using a dataclass with a `init=False` field. These fields are not meant to be provided to the dataclass constructor, but rather computed in `__post_init__`.

Here is a simplified example:

```py
import dataclasses
import pydantic

@pydantic.dataclasses.dataclass(frozen=True)
class MyDataclass:
    field1: int
    field2: int = dataclasses.field(init=False)

    def __post_init__(self):
        object.__setattr__(self, 'field2', compute_field2(self.field1))

    @pydantic.validator('field1', pre=True)
    def validate_field1(cls, value: int) -> int:
        # do something with `value`, might raise an exception
        ...
```

In the validator, a failure (e.g with a `ValueError`) gets wrapped in a `pydantic.error_wrappers.ValidationError`.

But in the `__post_init__` it does not, the exception is raised directly.

This difference makes it harder than it should be to handle the errors.

Workarounds would be:

1.  make it possible for the `validate_filed1` validator to set the `field2` attribute;

    this is currently not possible because validators operate on the class, not the instance;

2.  prevalidate the `__post_init__` computation of `field2` in a `field1` validator:

    ```python
    @pydantic.validator('field1')
    def validate_field2(cls, value: int) -> int:
        return compute_field2(value)
    ```

    this is simple, but means `compute_field2()` is called twice, which could have a significant impact if the function is costly;

3.  manually make the `__post_init__` raise a `ValidationError`:

    ```python
        def __post_init__(self):
            try:
                object.__setattr__(self, 'field2', compute_field2(self.field1))
            except Exception as e:
                raise ValidationError([ErrorWrapper(e, 'field1')], self.__class__)
    ```

    the API to create a `ValidationError` doesn't seem to be documented, I had to read the Pydantic code to figure it out (and I'm not entirely convinced I got it right), which makes me think users of Pydantic aren't supposed to create `ValidationError` themselves;

All in all, it would be really great if Pydantic could wrap errors raised by `__post_init__` like it wraps errors raised by validators, as it would offer a more consistent API.

I guess the difficulty would be to figure out the `loc` of the error?

**Comment by samuelcolvin** [comment]
I'm not sure if `dataclasses.field(init=False)` works, you might need to use `InitVar` as [documented](https://pydantic-docs.helpmanual.io/usage/dataclasses/#initialize-hooks).

Regarding catching errors in `__post_init__`, it guess it might be possible. I've no idea right now how much of a change it would require. The `loc` should be `__root__`.

You might be able to use [root validators](https://pydantic-docs.helpmanual.io/usage/validators/#root-validators) instead?

**Comment by bochecha** [comment]
> I'm not sure if dataclasses.field(init=False) works, you might need to use InitVar as documented.

`InitVar` is to get the field value passed to `__post_init__`, but I don't need that, what I need is for the generated `__init__` not to expect a `field2` argument, because users of my API shouldn't pass `field2` to the constructor, it should get computed in `__post_init__`.

> You might be able to use root validators instead?

Woah, I didn't know about those. That indeed gets me pretty close to what I want! :slightly_smiling_face:

```python
import dataclasses
import math

import pydantic


@pydantic.dataclasses.dataclass(frozen=True)
class MyDataclass:
    field1: int
    field2: int = dataclasses.field(init=False)

    @pydantic.root_validator(pre=True)
    def compute_field2(cls, values):
        field1 = values['field1']

        if field1 < 0:
            raise ValueError(f'field1 must be positive: {field1}')

        values['field2'] = math.sqrt(field1)

        return values
        
        
dc1 = MyDataclass(field1=42)

try:
    dc2 = MyDataclass(field1=-1)

except pydantic.error_wrappers.ValidationError as exc:
    print(exc)
```

The only minor issue now is cosmetic: `__root__` is not really understandable as a location for the error.

I'm using this to parse and validate a TOML configuration file. Each table in the config ends up as a dataclass, recursively. I'd like to be able to tell the users the exact key they got wrong in the config (e.g `field1`). Telling them they got `__root__` wrong is not very friendly. :sweat_smile:

**Comment by samuelcolvin** [comment]
Yes, customising `loc` would be useful.

I've created #982 to discuss that since it's slightly different from the initial question/feature request here.

**Comment by bochecha** [comment]
With root validators and #982, I can do everything for which I was trying to use `__post_init__`.

As a result I don't need anything from this issue, and wouldn't mind if you closed it.

Of course if you want to keep it open because you're interested in wrapping errors from `__post_init__`, feel free to keep it. :slightly_smiling_face:

**Comment by samuelcolvin** [comment]
If someone else wants this, feel free to comment and I can reopen.

I'm closing this for tidiness sake
