### ISSUE TITLE
mypy complains about pre=True root validators

### ISSUE THREAD

**Issue by bochecha** [samuelcolvin/pydantic#984]
# Bug

Please complete:
* OS: **Ubuntu 19.04**
* Python version `import sys; print(sys.version)`: **3.7.3**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **1.0**

With the code found in the [root validators](https://pydantic-docs.helpmanual.io/usage/validators/#root-validators) documentation:

```py
from pydantic import BaseModel, root_validator


class UserModel(BaseModel):
    username: str
    password1: str
    password2: str

    @root_validator(pre=True)
    def check_card_number_omitted(cls, values):  # type: ignore
        assert 'card_number' not in values, 'card_number should not be included'
        return values
```

Mypy has the following to say:

```
9: error: "classmethod" not callable
```

The following change pleases mypy, but of course that changes the semantics:

```diff
-    @root_validator(pre=True)
+    @root_validator
```

**Comment by samuelcolvin** [comment]
Thanks for reporting. Fixed by #985
