### ISSUE TITLE
value validation dependent on another value

### ISSUE THREAD

**Issue by hudecof** [samuelcolvin/pydantic#989]
# Question

How to validate value os `value` based on the `type`.
Image you have property based mode, there you could store several types of propertis, means like `str`, `bool`, `int` ...

My current code represents the  `value` as arbitrary `str`, no other validation is performed. But Iif  want to use **pydantic** to to the validation bases on the `type`, how should I do that?

Please complete:
* OS: **MacOS**
* Python version `import sys; print(sys.version)`: **3.7.4**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **0.32.2**

**Please read the [docs](https://pydantic-docs.helpmanual.io/) and search through issues to
confirm your question hasn't already been answered.**

Where possible please include a self contained code snippet describing your question:

```py
from enum import Enum
from pydantic import BaseModel

class PropertyTypeEnum(str, Enum):
    str = "str"
    int = "int"
    bool = "bool"
    ip = "ip"
    json = "json"
    key = "key"

class PropertyBase(BaseModel):
    name: str
    type: PropertyTypeEnum
    value: str
    active: bool = False
...
```

**Comment by samuelcolvin** [comment]
Probably best to use validations, something like

```py
from enum import Enum
from typing import Any
from pydantic import BaseModel, validator

class PropertyTypeEnum(str, Enum):
    str = "str"
    int = "int"
    bool = "bool"
    ip = "ip"
    json = "json"
    key = "key"

class PropertyBase(BaseModel):
    name: str
    type: PropertyTypeEnum
    value: Any
    active: bool = False

    @validator('value')
    def parse_value(cls, value, values):
        try:
            type = values['type']
        except KeyError:
            # happens if "type" validation fails
            return value
        
        if type == PropertyTypeEnum.str:
            return str(value)
        elif type == PropertyTypeEnum.int:
            return int(value)
        ...
```

**Comment by hudecof** [comment]
@samuelcolvin thanks for quick response, I will try
