### ISSUE TITLE
How to create backref field?

### ISSUE THREAD

**Issue by heckad** [samuelcolvin/pydantic#991]
# Question

Please complete:
* OS: windows 10
* Python version: 3.8.0
* Pydantic: 0.32.2

```py
from typing import List
from typing import Optional

import pydantic


class Point(pydantic.BaseModel):
    x: int
    y: int

    shape: Optional['Shape'] = None  # Shoud be backref


class Shape(pydantic.BaseModel):
    points: List[Point] = []


Point.update_forward_refs()

shape = Shape()
shape.points.append(Point(x=1, y=2))

assert shape.points[0].shape is shape
```

Is it possible?

**Comment by samuelcolvin** [comment]
[yes](https://pydantic-docs.helpmanual.io/usage/postponed_annotations/)

**Comment by heckad** [comment]
And how?

**Comment by samuelcolvin** [comment]
The docs are pretty clear, if you're still having trouble after trying a setup, please ask here with code from your attempt.

**Comment by heckad** [comment]
In the documentation, I didn't find anything that can have abstract filed (filed that ignore when serialising) and can be added after deserialising or added to the model. Nothing!

**Comment by heckad** [comment]
@samuelcolvin, did you understand my question and what I want to do?

**Comment by samuelcolvin** [comment]
as per [this](https://pydantic-docs.helpmanual.io/usage/models/#faux-immutability) explanation, `shape.points.append(Point(x=1, y=2))` will never cause validation to occur. This is a limitation of python.

Beyond that, I'm not sure what you're asking.

**Comment by heckad** [comment]
Sqlalchemy has the ability (by relationships) for setting backref and when you append something this is immediately added as a backref to the object that was added. 

```
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm import sessionmaker

engine = create_engine('sqlite:///:memory:')

Base = declarative_base(bind=engine)
Session = sessionmaker(bind=engine)


class Shop(Base):
    __tablename__ = 'shops'
    id = Column(Integer, primary_key=True)

    name = Column(String)

    books = relationship('Book', backref='shop')


class Book(Base):
    __tablename__ = 'books'
    id = Column(Integer, primary_key=True)

    name = Column(String)

    shop_id = Column(ForeignKey(Shop.id))


if __name__ == '__main__':
    Base.metadata.create_all()
    session = Session()

    book = Book(name='Властелин колец')
    shop = Shop(name='Мир книг')

    shop.books.append(book)

    assert book.shop is shop
```

**Comment by samuelcolvin** [comment]
okay, I understand better what you're asking about.

This isn't currently possible with pydantic, see #659.
