### ISSUE TITLE
Add default_factory to Field like in dataclass.field.

### ISSUE THREAD

**Issue by heckad** [samuelcolvin/pydantic#993]
Need to generate UUID by a special custom function. In dataclass can add default_factory for it but in BaseModel mode can't. It needs to be fixed.

**Comment by samuelcolvin** [comment]
This can be done using a [`validator`](https://pydantic-docs.helpmanual.io/usage/validators/).

See #866.

**Comment by heckad** [comment]
It is not apparent and very strange. What prevents to do as in the standard lib?

**Comment by samuelcolvin** [comment]
Nothing prevents it. As explained in #866 I'm pro adding a `default_factory` argument to `Field`. Would you like to submit a PR?
