### ISSUE TITLE
Current best practices for combining `pydantic` & `mypy`

### ISSUE THREAD

**Issue by DBCerigo** [samuelcolvin/pydantic#995]
Part 1: there seems to be an inconsistency between the conclusion from this issue #245 being "Solution here is to use dataclasses which I think mypy should work with properly.", and then this pydantic docs page https://pydantic-docs.helpmanual.io/usage/mypy/
Is the conclusion of that issue now defunct, and inheriting from `BaseModel` is supposed to work correctly with `mypy`, or are the docs incorrect? I raise this as in our current usage of `BaseModel` we get the ("`mypy` not working") behaviour from #245 and not the ("`mypy` working") behaviour from docs.

Part 2: given we really like `pydantic` (a thanks and congrats to all contributors to it!), what is currently advised by core `pydantic` devs as the best practice to use `pydantic` while still get type-checking with `mypy`. The options I found are: 
a. Use `pydantic.dataclasses` as per https://pydantic-docs.helpmanual.io/usage/dataclasses/#nested-dataclasses
b. Use the `pydantic.mypy` plugin* as per https://pydantic-docs.helpmanual.io/mypy_plugin/
The hope with this question is that it can provide advice to others out there looking to combine `mypy` & `pydantic` on how best to do so currently 😸

Other refs for `mypy` + `pydantic` usage: #366 #957 #156 #238 

*Note, in this same docs page it states that `mypy` works with `pydantic` (assuming implying with `BaseModel` also) out of the box, which is again not what #245 concludes 😬

(I personally think `mypy` is pretty 👎, so I appreciate the presumed headache it causes you all too, but that optional type-hinting in general is very 👍)

**Comment by samuelcolvin** [comment]
The solution is to use the [mypy plugin](https://pydantic-docs.helpmanual.io/mypy_plugin/) with that mypy should work correctly.

yes, #245 is outdated.

**Comment by DBCerigo** [comment]
@samuelcolvin having just installed `pydantic=1.1`, with a setup.cfg as:
```
[mypy]
plugins = pydantic.mypy
```
I'm getting `error: Error importing plugin 'pydantic.mypy'`!

**Comment by DBCerigo** [comment]
Can confirm, installing `pydantic=1.1` didn't force an upgrade in `mypy` version. I was getting the `error: Error importing plugin 'pydantic.mypy'` with `mypy=0.720`. I upgraded to `mypy=0.740`, and now the error is resolved :)

**Comment by samuelcolvin** [comment]
I've just tried this myself and it works fine:

```py
> mkdir scratch
> cd scratch
> touch app.py
[copy python https://pydantic-docs.helpmanual.io/mypy_plugin/]
> touch setup.cfg
[copy the two lines from above]
> pip install -U pydantic mypy
...
> mypy app.py 
app.py:16: error: "Model" has no attribute "middle_name"
app.py:17: error: Missing named argument "age" for "Model"
app.py:17: error: Missing named argument "list_of_ints" for "Model"
Found 3 errors in 1 file (checked 1 source file)
```

**Comment by samuelcolvin** [comment]
> Can confirm, installing `pydantic=1.1` didn't force an upgrade in `mypy` version. I was getting the `error: Error importing plugin 'pydantic.mypy'` with `mypy=0.720`. I upgraded to `mypy=0.740`, and now the error is resolved :)

mypy is not a dependency of pydantic, thus it can't force mypy to update.

**Comment by DBCerigo** [comment]
I guess with the `pydantic-mypy` plugin introduced in 1.1, `mypy` is now a dep of `pydantic`? 🤷‍♂️ It's not biggy to me :) just hopefully to try to help make improvements.

**Comment by dmontagu** [comment]
@DBCerigo As far as I understand, nothing has changed about pydantic's relationship with mypy. It was a development-only dependency before, and it still is.

If you never import `pydantic.mypy` (and it should *only* be imported when mypy is running using the plugin), you don't need to have mypy installed.

If you want to use the mypy plugin while type-checking your code using mypy, then yes, you'd need to have mypy installed 😄. But that was also the case before.

**Comment by DBCerigo** [comment]
@dmontagu appreciated, sounds completely right :) thanks for responding

**Comment by samuelcolvin** [comment]
No, mypy is definitely not a dependency of pydantic because you can use
pydantic without mypy.

In theory mypy could become an optional dependency on pydantic, but without
reading the docs that wouldn't have helped you.

We could however add a note to the docs pointing out the minimum version of
mypy required to use plugins.

**Comment by joshua-s** [comment]
I am still having this issue with mypy 0.782 and pydantic 1.6.1

**Comment by AlexKLWS** [comment]
Also having this issue with mypy 0.782 and pydantic 1.6.1

**Comment by Ben2146053** [comment]
If your using the [mypy ](https://marketplace.visualstudio.com/items?itemName=matangover.mypy) plugin on VS Code you could be getting the error
` error: Error importing plugin 'pydantic.mypy'`
what you need to do is go into the plugins virtual machine and pip install pydantic because its not installed yet
`%USERPROFILE%\.mypyls\Scripts\activate`
`pip install pydantic`

**Comment by AIGeneratedUsername** [comment]
Mypy works from command line, but fails with pre-commit:

```
mypy.....................................................................Failed
 - hook id: mypy - exit code: 2 setup.cfg:23:1: error: Error importing plugin 'pydantic.mypy': No module named 'pydantic' [misc] 
```

Any ideas how to fix?

**Comment by Reskov** [comment]
I was able to solve issue using [additional_dependencies](https://pre-commit.com/#config-additional_dependencies)

```yaml

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.800
  hooks:
  - id: mypy
    additional_dependencies:
      - 'pydantic'
```
